#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 5 - dynamic angle fashion shots of
#        high heels on a woman's legs, fashion magazine advertising quality,
#        both close-up and full-body/zoomed-out shots that use composition,
#        lighting and guiding lines to focus attention on the heels,
#        bottom-center "5" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+5+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "Extreme low-angle close-up on a single crimson patent-leather stiletto, ankle arched mid-step on glistening wet asphalt at night, neon signage bleeding into soft bokeh behind, rain droplets caught on the heel's edge, shot like a Guy Bourdin editorial with saturated color contrast and hard directional flash. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Crimson Stiletto in Rain"

queue_job 2 \
  "Full-body fashion shot descending a sweeping white marble staircase, woman's legs and towering nude stiletto sandals centered by the staircase's converging balustrade lines, golden hour light raking across from a tall window, soft haze, Vogue-style grandeur reminiscent of Peter Lindbergh's architectural compositions, the heels sharply lit while surroundings fall into gentle falloff. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Marble Staircase Descent"

queue_job 3 \
  "Studio macro shot against seamless matte black backdrop, a single spotlight raking across a jeweled ankle-strap heel, leg crossed at the knee, skin glowing with soft rim light, every stitch and buckle in crisp focus, styled like a luxury Jimmy Choo campaign still, minimal negative space drawing the eye straight to the strap's glinting hardware. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Jeweled Ankle-Strap Macro"

queue_job 4 \
  "Wide editorial shot on a red carpet under crossing spotlight beams, woman's legs striding forward in metallic platform heels, paparazzi flashes freezing motion, shallow depth of field collapsing the crowd into a warm blur while the heels stay tack-sharp at the base of the frame, composition echoing Helmut Newton's theatrical glamour and command of light. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Red Carpet Metallic Platforms"

queue_job 5 \
  "Dynamic mid-stride shot on a glossy reflective floor inside a minimalist gallery space, one heel lifted off the ground in motion blur, the other planted sharp and still, mirrored reflection doubling the silhouette, cool blue-white lighting with a single warm spotlight pooling exactly where the heel meets the floor, evoking a Steven Meisel motion-study campaign. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Gallery Floor Mid-Stride"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "Dynamic extreme low-angle macro shot of a sleek patent leather crimson stiletto heel stepping onto a pristine, wet dark granite surface. Sharp cinematic lighting creates a crisp specular reflection on the glossy red shoe, while dramatic directional shadows form leading diagonal lines directly targeting the heel. Highly detailed texture of the leather, refined stitch work, and liquid droplets. Fashion magazine spread aesthetics, high-contrast chiaroscuro, sharp focus, 8k resolution, award-winning luxury advertisement. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Crimson Stiletto on Wet Granite"

queue_job 7 \
  "Full-length editorial fashion photograph of a model in motion, captured from a ground-level dynamic Dutch angle. She wears a structured, oversized monochrome coat, stepping down a grand marble staircase where every sharp step edge acts as a converging line directing the eye straight to her neon cyan high heels. Intentionally placed spotlighting illuminates her footwear while the upper torso fades into soft, elegant shadow. Vogue cover style, dramatic depth of field, subtle motion blur on the background, 8k professional advertisement photo. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Marble Staircase, Neon Cyan Heels"

queue_job 8 \
  "Low-angle medium shot of a fashion model seated on a sleek metallic polished counter in a rain-slicked night setting. Her long legs cross elegantly, bringing a pair of metallic gold ankle-strap pumps into sharp, illuminated focus in the central foreground. Vivid magenta and ice-blue neon reflections trace the contours of the heels, contrasting intensely against deep surrounding shadows. Hyper-detailed texture, shallow depth of field, cinematic editorial color grading, luxury footwear commercial photo. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Metallic Gold Pumps, Neon Reflections"

queue_job 9 \
  "Wide-angle landscape shot of a high-fashion model standing atop a vast, minimalist sand dune under a deep indigo dusk sky. Atmospheric golden spotlight naturally vignetting from above creates an intense radial light pool concentrated exclusively around her feet, highlighting a pair of vibrant emerald-green velvet high heels. Soft dune ridges sweep inward as natural framing lines leading directly to her ankles. High-end luxury print ad, 8k resolution, crisp texture detail, pristine composition, professional fashion magazine layout. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Emerald Heels on Sand Dune"

queue_job 10 \
  "Dynamic worm's-eye angle looking up from a Brutalist concrete courtyard. A model steps across a glass floor tile, with the camera pointing upward to emphasize a pair of sculpted matte-black architectural high heels against a stark sky. Geometric concrete pillars frame the shoes in a tight natural aperture, using strong geometric symmetry to lock the viewer's gaze onto the heel silhouette. Razor-sharp detail, high-fashion campaign photography, raw texture, flawless lighting contrast, 8k quality. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Architectural Black Heels, Worm's-Eye"


# --- ChatGPT ---
queue_job 11 \
  "A dynamic low-angle fashion editorial photograph focused on a woman's elegant high heels, one foot stepping forward on a glossy black studio floor while the other leg extends behind, emphasizing the sculptural silhouette of the shoes and graceful lines of the legs. Dramatic directional lighting creates crisp highlights along the polished heels and subtle reflections beneath them, with the rest of the woman's outfit fading into a sophisticated shadowy background. Luxury fashion magazine advertising quality, meticulous professional photography, refined styling, shallow depth of field, powerful perspective, sophisticated contrast, premium footwear campaign aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "ChatGPT" "Low-Angle Studio Stride"

queue_job 12 \
  "A full-body fashion campaign photograph of an elegant woman wearing striking high heels, standing beside a monumental modern architectural staircase, captured from a dramatic low three-quarter angle. The staircase rails, geometric steps, and elongated shadows form strong leading lines that converge toward the high heels, directing the viewer's attention to the footwear while preserving the complete fashion silhouette. Sophisticated tailored outfit, confident poised stance, subtle wind movement in the fabric, dramatic afternoon sunlight, cinematic architectural composition, luxury fashion magazine advertising quality, professional editorial photography, crisp textures and controlled highlights. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "ChatGPT" "Staircase Leading Lines"

queue_job 13 \
  "An extreme close-up fashion photograph of a woman's legs in elegant high heels crossing over one another while walking across a luxurious marble floor, captured at ground level with a dynamic diagonal perspective. The camera is positioned close to the shoes, making the high heels the unmistakable visual centerpiece, with sharp focus on the leather texture, delicate straps, heel structure, and contact with the reflective floor. The background dissolves into soft architectural shapes and creamy highlights, creating depth without competing with the footwear. High-end fashion magazine advertising, sophisticated luxury footwear campaign, professional studio-quality photography, dramatic controlled lighting, refined color grading, sensual but tasteful editorial styling. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "ChatGPT" "Crossed Legs on Marble Floor"

queue_job 14 \
  "A cinematic full-body fashion editorial photograph of a woman walking through a glamorous modern hotel lobby wearing dramatic high heels, captured from a low dynamic perspective slightly behind and to the side. The polished floor creates a subtle reflection while architectural columns, illuminated walls, and converging floor patterns naturally guide the eye toward her feet. Her flowing coat and confident stride create movement, while a carefully placed pool of light falls brightest around the high heels, making the footwear the compositional focal point despite the wider scene. Luxury fashion advertising campaign, high-end fashion magazine aesthetic, professional commercial photography, realistic skin and fabric textures, sophisticated lighting, elegant cinematic atmosphere, sharp footwear detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "ChatGPT" "Hotel Lobby Cinematic Walk"

queue_job 15 \
  "A dramatic overhead-to-low perspective fashion photograph of a woman seated on the edge of a sculptural velvet lounge chair, one leg extended forward so her high heel dominates the foreground while the rest of her elegant fashion silhouette recedes into the composition. The unusual camera angle creates strong depth and perspective, with the pointed shoe and heel rendered in razor-sharp detail while her face and upper body remain secondary. Soft spotlighting isolates the footwear against a luxurious dark interior, with subtle reflections, velvet textures, and carefully arranged fashion accessories surrounding the scene. Premium footwear advertising, fashion magazine cover quality, professional editorial photography, dynamic composition, sophisticated luxury aesthetic, controlled studio lighting, realistic materials and textures. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "ChatGPT" "Velvet Lounge Chair Close-Up"


# --- Grok fast ---
queue_job 16 \
  "Dynamic low-angle close-up fashion shot of a woman's legs in glossy black stiletto high heels, the pointed toes and sleek arches filling most of the frame, dramatic side lighting creating sharp highlights and deep shadows on the patent leather, soft bokeh background of a luxurious marble floor, fashion magazine advertising quality, ultra-sharp professional photo, high-end editorial style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Grok fast" "Black Stiletto Close-Up, Marble Floor"

queue_job 17 \
  "Full-body dynamic fashion shot of a confident woman standing in a modern glass-walled loft, wearing red patent high heels, the camera positioned at a slight low angle so the sharp lines of the floorboards and architectural beams guide the eye straight to the high heels, soft cinematic lighting with a spotlight accent on the shoes, elegant pose with one foot slightly forward, fashion magazine advertising quality professional photo, high-end editorial. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Grok fast" "Red Heels in Glass-Walled Loft"

queue_job 18 \
  "Dramatic overhead close-up fashion shot of a woman's crossed legs resting on a velvet chaise, shiny metallic gold high heels catching the light, the camera tilted at a dynamic angle so the curves of the heels dominate the composition, soft directional lighting creating elegant reflections, shallow depth of field, fashion magazine advertising quality professional photo, luxurious editorial style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Grok fast" "Gold Heels on Velvet Chaise"

queue_job 19 \
  "Dynamic full-body fashion shot of a stylish woman walking down a rain-slicked city street at dusk, wearing sleek white pointed-toe high heels, the wet pavement reflections and converging perspective lines of the buildings all directing attention to the shoes, cool blue hour lighting with warm highlights on the heels, confident stride, fashion magazine advertising quality professional photo, high-end street editorial. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Grok fast" "White Heels on Rainy Street"

queue_job 20 \
  "Dynamic mid-shot fashion photograph of a woman's legs stepping out of a luxury sports car, glossy emerald green high heels catching a strong rim light, the open car door and curved body lines creating natural guiding shapes that lead the eye directly to the shoes, dramatic evening lighting with soft background bokeh of city lights, fashion magazine advertising quality professional photo, cinematic editorial style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Grok fast" "Emerald Heels, Sports Car Exit"


# --- Qwen 3.7 Plus Thinking ---
queue_job 21 \
  "Extreme close-up dynamic low-angle fashion shot of a woman's legs wearing glossy black patent leather stiletto high heels, stepping forward on a rain-slicked neon-lit city street. Motion blur on the background city lights emphasizes speed and dynamism. Fashion magazine advertising quality, professional photo, sharp focus on the intricate details and reflections on the heels, dramatic chiaroscuro lighting highlighting the arch of the foot and separating it from the dark, blurred background. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus Thinking" "Neon City Street Stride"

queue_job 22 \
  "Full body dynamic Dutch angle fashion shot of a woman striding confidently down a grand, sunlit marble hallway. She wears a flowing emerald green haute couture gown, but the composition uses strong architectural leading lines of the floor tiles and a focused, dramatic spotlight to draw the viewer's attention directly and exclusively to her striking crimson red high heels. Fashion magazine advertising quality, professional photo, 35mm lens, high-end editorial aesthetic, crisp details, vibrant colors, Vogue cover style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus Thinking" "Marble Hallway, Crimson Heels"

queue_job 23 \
  "Mid-shot dynamic angle fashion photography of a woman's legs posed mid-step on a modern minimalist concrete staircase. She is wearing metallic silver strappy high heels. The composition relies on strong diagonal lines of the stairs and a dramatic side-lighting setup to create deep, directional shadows, ensuring the viewer's eye is immediately captured by the gleaming, high-contrast high heels. Fashion magazine advertising quality, professional photo, 85mm lens, shallow depth of field, luxury brand aesthetic, clean and sharp rendering. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus Thinking" "Concrete Staircase, Silver Straps"

queue_job 24 \
  "Full body dynamic action shot of a woman mid-stride in a breezy, elegant beige trench coat in a chic urban plaza. The camera angle is low and dynamic, capturing the movement of the fabric. While the full figure and surrounding softly blurred city architecture are visible, a subtle natural vignette and a precise beam of warm golden-hour sunlight isolate and highlight her gold-embellished high heels, making them the undeniable, glowing focal point of the image. Fashion magazine advertising quality, professional photo, highly detailed, 50mm lens, cinematic fashion advertising. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus Thinking" "Golden-Hour Plaza Walk"

queue_job 25 \
  "Dynamic low-angle close-up fashion shot of a woman's legs stepping out of a vintage luxury car onto a red carpet. She is wearing intricate, crystal-encrusted nude high heels. The shallow depth of field beautifully blurs the car door and the background crowd, while a sharp, high-contrast professional flash photography style keeps the absolute, crisp focus on the texture, sparkle, and elegant form of the high heels. Fashion magazine advertising quality, professional photo, high-end glamour, crisp 50mm lens rendering, sharp catchlights on the crystals. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus Thinking" "Vintage Car, Crystal Heels"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "Dynamic low-angle close-up fashion shot of a woman's legs in glossy red patent stiletto high heels stepping off a black marble staircase, arch of the foot emphasized, calf muscles elegantly tensed, fashion magazine advertising quality professional photo, dramatic hard studio lighting with specular highlights gliding along the shoe curves, shallow depth of field with razor-sharp focus on the heels, background melting into soft dark bokeh, shot on 85mm f/1.4, Vogue editorial aesthetic, rich color grading. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Black Marble Staircase Step"

queue_job 27 \
  "Full-body dynamic fashion shot of an elegant woman in a flowing champagne silk evening gown wearing glittering gold stiletto high heels, striding down a long mirrored art-deco corridor, symmetrical perspective lines of the walls and floor tiles converging directly toward her feet, a single overhead spotlight pooling on the floor beneath her heels while the rest of the hall fades into atmospheric haze, fashion magazine advertising quality professional photo, editorial composition engineered to lock the viewer's eye on the shoes, shot on 35mm, cinematic contrast, luxury campaign aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Mirrored Art-Deco Corridor"

queue_job 28 \
  "Extreme close-up dynamic angle fashion shot of a woman's legs in black patent leather stiletto heels captured mid-stride on a rain-slicked city street at night, water splashing frozen in motion around the sole, neon signs reflecting in the wet asphalt and on the glossy shoe surface, fashion magazine advertising quality professional photo, dramatic rim lighting sculpting the legs, slight dutch tilt for kinetic energy, high-speed flash freezing the droplets, sharp focus locked on the heels, editorial street-style luxury aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Rain-Slicked Street at Night"

queue_job 29 \
  "Wide editorial fashion photograph of a woman reclining on a sculptural white designer sofa in a minimalist luxury penthouse, wearing nude pointed-toe stiletto heels with her legs extended prominently into the foreground of the frame, natural light from floor-to-ceiling windows casting a bright beam that falls exactly across her legs and shoes while the rest of the room sits in soft shadow, the sofa's geometric lines acting as leading edges guiding the eye toward the heels, fashion magazine advertising quality professional photo, shot on 50mm, muted sophisticated color palette, high-end campaign composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Penthouse Sofa Recline"

queue_job 30 \
  "Dynamic ground-level upward angle fashion shot of a model descending a sweeping marble grand staircase, her crimson sole-red stiletto heels placed precisely on the step edge as the brightest point of the frame, a cascade of warm chandelier light running down the stairwell like a natural spotlight following her descent, the diagonal balustrade and stair edges forming strong leading lines aimed straight at her feet, dress train flowing upward behind her, fashion magazine advertising quality professional photo, sharp focus on the heels with elegant depth falloff, opulent haute couture campaign aesthetic, shot on 35mm. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Grand Staircase Descent"


# --- DeepSeek Think Search ---
queue_job 31 \
  "Extreme close-up, dynamic low angle fashion shot of a woman's legs wearing sleek, glossy black stiletto high heels. The camera is positioned on the ground, looking up, emphasizing the length of the legs and the sharp point of the heel. A single, powerful spotlight illuminates the shoes, creating dramatic, high-contrast reflections on the patent leather. The background is a dark, blurred runway with subtle bokeh from distant lights. Fashion magazine advertising quality professional photo, sharp focus on the stiletto heel and the arch of the foot. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Runway Spotlight Close-Up"

queue_job 32 \
  "Full-body dynamic fashion shot, a woman in a flowing crimson dress is captured mid-stride in a modern architectural space with polished concrete floors. She is wearing striking, metallic silver high heels. The composition uses the strong leading lines of the floor and the geometric walls to draw the viewer's eye directly to her feet. A dynamic, slightly tilted camera angle (Dutch angle) adds a sense of motion and energy. Professional fashion magazine advertising photo, cinematic lighting with a cool color grade. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Concrete Space, Dutch Angle"

queue_job 33 \
  "Dynamic low-angle fashion shot of a woman's legs and torso, stepping out of a luxury car. She is wearing vibrant red-soled high heels. The camera is placed low to the ground, creating a powerful and aspirational perspective. The composition uses the rule of thirds, placing the high heels prominently in the lower third of the frame, making them the undeniable focal point. The lighting is bright and sunny, typical of a high-end lifestyle advertisement. Fashion magazine advertising quality professional photo. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Luxury Car Exit, Red Soles"

queue_job 34 \
  "Fashion magazine advertising quality professional photo, a minimalist and artistic mid-shot of a woman's legs wearing avant-garde, sculptural high heels. She is standing still on a seamless, brightly lit white background. The key element is the strong, sharp shadow cast by her legs and the intricate heels, creating a striking graphic shape on the floor. The composition and lighting are designed to make the silhouette of the high heels the most compelling part of the image, focusing all attention on their unique design. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "White Background Silhouette"

queue_job 35 \
  "Dynamic full-body fashion shot, backlit silhouette of a woman walking through a misty, neon-lit city street at night. She is wearing iconic, crystal-embellished high heels that catch and refract the colorful lights, creating a sparkling effect. The camera is positioned behind her at a slight angle. The composition uses the dark, moody environment and the backlighting to create a strong contrast, making the glittering high heels the brightest and most focused point in the image, pulling the viewer's attention directly to them. Fashion magazine advertising quality professional photo. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Neon Street Backlit Silhouette"


# --- MiniMax M3 ---
queue_job 36 \
  "Cinematic extreme close-up low-angle fashion shot from street level looking upward at glossy red patent-leather stiletto high heels on a woman's legs, with razor-sharp focus on the heel and ankle and the calf softly dissolving into bokeh. Wet cobblestones mirror the figure and amplify the shoe's silhouette. Moody golden-hour backlight rims the leg and shoe with luminous amber, deep cinematic shadows. Editorial fashion magazine advertising quality, shot on 85mm f/1.4, warm filmic color grading. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Extreme Close-Up, Street-Level, Wet Cobblestones"

queue_job 37 \
  "Dynamic full-body editorial fashion shot of a tall woman in a tailored black midi dress striding across a stark white city crosswalk, captured in profile from a low three-quarter angle. Bold zebra-stripe leading lines from the crosswalk converge toward her glossy black pointed-toe stiletto high heels, anchoring the viewer's eye directly on the footwear. Soft overcast daylight, muted minimalist palette, slight motion blur on the trailing leg for kinetic energy. Hasselblad medium-format quality, advertising-grade retouching, ultra-high resolution. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Walking on a Zebra Crosswalk, Profile View"

queue_job 38 \
  "High-end studio fashion shot of a model's legs crossed at the knee wearing electric-blue satin platform high heels with crystal embellishments, photographed against a curved seamless backdrop. Dramatic dual gel lighting — hot magenta key from camera left, cool teal fill from the right — both rim-lighting the silhouette of the shoe and leg with saturated neon edges. A polished reflective floor doubles the visual weight of the heels. Vogue editorial aesthetic, hyper-detailed skin texture and fabric sheen, 100mm macro lens feel, professional advertising print quality. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Studio, Dual-Gel Neon Lighting, Reflective Floor"

queue_job 39 \
  "Cinematic wide editorial fashion shot of a model reclining on a grand marble staircase in a gilded art-deco hotel lobby, captured from a low worm's-eye angle at the base of the stairs. The receding diagonal lines of the marble steps and brass handrail act as guiding lines that funnel the viewer's gaze directly to her nude satin pointed stiletto high heels propped on a lower step. Soft warm chandelier light from above with deep amber tones, polished marble reflections, dust motes in the air, an atmosphere of opulence. Shot on Phase One IQ4 150MP, Vogue Italia cover quality. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Marble Art-Deco Staircase, Worm's-Eye, Guiding Composition"

queue_job 40 \
  "Dramatic rooftop fashion editorial at blue hour, full-body low-angle shot of a woman standing at the edge of a concrete rooftop terrace with the city skyline rendered as creamy bokeh behind her. She wears a sleek cobalt silk gown and chrome metallic strappy stiletto high heels that catch the last warm rim of the setting sun. The metallic shoes and the leading lines of the rooftop parapet and concrete seams pull the viewer's gaze down to the footwear. Cinematic dusk gradient sky, cool teal shadows with hot orange rim light on the shoes, anamorphic lens flare, ultra-cinematic Hollywood advertising aesthetic, 8K resolution. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"5\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Rooftop Blue-Hour, Full-Body Silhouette, Chrome Heels"


echo "✅ All 40 jobs queued in scheduleri"
