#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 2 - highly aesthetic poster style,
#        woman in a red dress tracing a sports car's curvy lines with her
#        finger as she walks by, bottom-center "2" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+2+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A woman in a flowing red dress strolls past a gleaming vintage sports car, her fingertip grazing its curved chrome fender as she passes, sun-drenched coastal boulevard behind her, warm golden-hour light, glossy travel-poster illustration style, bold flat color blocking, elegant mid-century typography energy without text, sweeping curves echoing between her silhouette and the car's bodywork. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Retro Riviera Glamour"

queue_job 2 \
  "Under wet neon reflections, a woman in a slinky red dress trails one finger along the sculpted curves of a parked sports car as she walks by, rain-slicked asphalt mirroring pink and cyan signage, moody cinematic poster composition, high-contrast chiaroscuro lighting, sleek editorial illustration rendering, sense of quiet seduction and motion frozen mid-stride. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Neon Noir Night"

queue_job 3 \
  "Minimalist high-fashion poster: a woman in a sharp red dress walks past a sleek sports car, her finger tracing its sweeping curve in one fluid gesture, stark negative space background, muted studio-gray backdrop, clean vector-flat illustration style, confident graphic silhouette, magazine-cover elegance, restrained palette of red, black, and cream. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Vogue Minimalist Editorial"

queue_job 4 \
  "A woman in a vivid red sundress ambles along a seaside piazza, fingertip skimming the curved bodywork of a parked sports car, whitewashed buildings and bougainvillea in the background, travel-poster illustration aesthetic, saturated Mediterranean light, playful painterly texture, joyful and breezy mood, dynamic diagonal composition drawing the eye along the car's curve. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Mediterranean Sun Poster"

queue_job 5 \
  "Art Deco-inspired poster: a woman in an elegant red gown passes a streamlined sports car, her hand gliding along its curved chrome line, geometric sunburst background, metallic gold and crimson palette, bold graphic linework reminiscent of vintage motorsport advertising, glamorous and aerodynamic, strong symmetrical poster framing. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Art Deco Grand Prix"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "Highly aesthetic poster style: an elegant illustration of a woman in a flowing, vintage crimson red dress walks with graceful poise, her gloved hand delicately tracing the sweeping, chrome side profile of a classic 1930s coupe. The style is art deco with geometric patterns, soft golden light, and palm trees in the background. At the bottom-right corner, a small inset text panel reads: '1. CLASSIC GRACE'. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Classic Grace"

queue_job 7 \
  "Highly aesthetic poster style: a dramatic cyberpunk street photograph from outside an elevated train station. A woman in a sleek, high-tech asymmetric red dress walks past an illuminated hypercar, rain-slicked pavement reflecting blue and neon lights. Her extended finger traces the sharp, complex composite wing lines. At the bottom-right corner, a small inset text panel reads: '2. NEON SCULPT'. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Neon Sculpt"

queue_job 8 \
  "Highly aesthetic poster style: a minimalist abstract poster featuring simple graphic forms. Two main simplified graphical lines are present: a curving red line representing a woman's motion, and a series of geometric, dark grey curves representing a car's body. The forms intersect elegantly, with a simple hand symbol tracing the contours. At the bottom-right corner, a small inset text panel reads: '3. GEOMETRIC MOTION'. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Geometric Motion"

queue_job 9 \
  "Highly aesthetic poster style: a high-speed, long-exposure motion blur capture. A woman in a vibrant, flowing red gown creates a blurred trail of color as she walks alongside a moving modern sports car. Her hand is a focused point of light tracing the hard, defined lines. At the bottom-right corner, a small inset text panel reads: '4. DYNAMIC LINES'. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Dynamic Lines"

queue_job 10 \
  "Highly aesthetic poster style: a graphic-design-heavy poster with a macro-view focus. The top half is a detailed macro photo of a woman's manicured fingernail tracing a high-gloss metallic red car panel. The bottom half is a vector-style illustration of a woman in a red dress walking by a similar car, viewed from a low perspective. At the bottom-right corner, a small inset text panel reads: '5. THE TRACE'. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "The Trace"


# --- ChatGPT ---
queue_job 11 \
  "A highly aesthetic luxury automotive poster: an elegant woman in a flowing red dress walks slowly beside a sculptural exotic sports car, tracing the car's long curving body line with one fingertip as she passes, her gesture following the aerodynamic contour from the front fender toward the door. Dramatic three-quarter side view, deep charcoal studio environment, glossy metallic car surface, controlled reflections, sculptural shadows, sophisticated fashion-editorial composition, cinematic rim lighting, rich contrast, minimal luxury advertising aesthetic, refined red-black-silver palette, graceful movement frozen in a single striking moment. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "ChatGPT" "Scarlet Curves"

queue_job 12 \
  "A highly aesthetic poster-style composition featuring an elegant woman in a vivid red dress walking alongside a futuristic high-performance sports car, gently tracing its sweeping aerodynamic curves with her index finger as she moves past it. Her dress creates a dynamic flowing silhouette contrasting with the precise mechanical geometry of the vehicle. Low camera angle, elongated perspective, dramatic studio lighting, glossy reflections sliding across the sculpted bodywork, dark minimalist background, subtle atmospheric haze, fashion magazine meets premium automotive campaign, sophisticated cinematic framing, luxurious and sensual without exaggeration, strong visual rhythm between the woman's silhouette and the car's curves. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "ChatGPT" "Touch of Speed"

queue_job 13 \
  "A highly aesthetic luxury poster showing a woman in a striking red evening dress walking past an exotic sports car, her hand extended naturally as her fingertip traces the elegant curved line of the car's side panel while she walks. The woman is captured in profile, graceful posture and flowing fabric, while the sports car dominates the composition with sculpted aerodynamic surfaces and precise highlights. Dark architectural showroom, polished floor reflections, dramatic directional spotlight, deep shadows, subtle warm highlights, sophisticated editorial photography, premium automotive advertising aesthetic, carefully balanced negative space, restrained color palette dominated by black, silver and vivid red, exceptionally clean composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "ChatGPT" "Red Against Chrome"

queue_job 14 \
  "A highly aesthetic cinematic poster: a stylish woman wearing a long crimson-red dress walks beside a low exotic sports car, slowly following the vehicle's flowing body contour with her fingertip as she passes, almost as if reading its aerodynamic shape by touch. Her red silhouette contrasts dramatically against the dark metallic automobile. Three-quarter rear perspective, sweeping composition, glossy black floor, carefully controlled reflections, sculptural studio lighting, thin rim light outlining both the woman and vehicle, luxurious fashion-editorial atmosphere, subtle motion in the dress, sophisticated minimalism, premium car campaign aesthetic, visually elegant rather than literal. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "ChatGPT" "Following the Line"

queue_job 15 \
  "A highly aesthetic poster composition of an elegant woman in a vibrant red dress walking past a breathtaking sculptural sports car, her arm extended casually and one finger tracing the continuous curving contour of its polished bodywork as she walks. The car's aerodynamic silhouette forms a powerful visual arc through the composition, mirrored by the flowing fabric of her dress. High-fashion editorial styling, dramatic side lighting, dark luxurious showroom, mirror-like floor, controlled specular highlights, atmospheric depth, cinematic shadows, sophisticated negative space, premium automotive campaign, modern art-direction, bold yet minimal visual language, exceptionally polished and intentional composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "ChatGPT" "The Contour"


# --- Grok fast ---
queue_job 16 \
  "Highly aesthetic poster style, square composition: elegant woman in a flowing red dress walking slowly past a sleek black sports car at dusk, her delicate finger tracing the sensual curvy lines of the hood and fender with soft focus and cinematic grace. Warm golden-hour light wraps her figure and glints off the polished bodywork, refined minimalist background with subtle city bokeh. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Grok fast" "Dusk Golden-Hour Hood Trace"

queue_job 17 \
  "Highly aesthetic poster style, square composition: sophisticated woman in a tailored red dress strolling beside a low, aerodynamic silver sports car under soft studio-like moonlight, her finger gliding along the car's elegant side curves in a slow, sensual motion. Cool blue-silver lighting, sharp reflections on the metallic surface, clean negative space and luxurious atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Grok fast" "Moonlit Side Curves"

queue_job 18 \
  "Highly aesthetic poster style, square composition: graceful woman in a vibrant red evening dress walking past a deep crimson sports car in an empty modern plaza at twilight, her fingertip gently following the car's dramatic flowing lines from front to rear. Soft purple-pink sky gradients, gentle rim light outlining her silhouette and the vehicle's contours, ultra-refined fashion-editorial mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Grok fast" "Twilight Plaza Crimson Car"

queue_job 19 \
  "Highly aesthetic poster style, square composition: elegant woman in a structured red dress moving fluidly beside a matte-black hypercar in a minimalist underground parking structure, her finger tracing the sharp yet sensual curves of the bodywork with poised confidence. Dramatic single-source overhead lighting, deep shadows, high-contrast monochrome palette with the red dress as the sole vivid accent. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Grok fast" "Underground Parking Hypercar"

queue_job 20 \
  "Highly aesthetic poster style, square composition: refined woman in a silky red dress walking along a sunlit coastal road next to a pearlescent white sports car, her finger delicately following the car's sculpted hip and shoulder lines as she passes. Bright natural daylight with soft lens flare, airy atmosphere, crisp details and luxurious fashion-photography finish. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Grok fast" "Coastal Road Pearl Sports Car"


# --- Qwen 3.8 Omni Flash Thinking ---
queue_job 21 \
  "Highly aesthetic poster-style composition, elegant fashion-meets-automotive mood. A beautiful woman in a flowing red silk dress walks beside a sleek black sports car, gently tracing the car's curvy body lines with her fingertip as she passes. Dramatic side lighting, glossy reflections, cinematic depth, refined negative space, luxury editorial atmosphere, subtle motion blur, rich color contrast between red fabric and dark metallic car. No extra text. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Glossy Black Car, Side Lighting"

queue_job 22 \
  "Art deco inspired poster, ultra aesthetic and graphic. A stylish woman in a long crimson gown walks past a streamlined vintage-futuristic sports car, her finger delicately following the sculpted curve of the fender. Gold geometric accents, sunset gradient background, bold silhouettes, elegant symmetry, luxurious retro-modern palette, sharp poster composition, soft glow, refined linework. No extra text. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Art Deco Vintage-Futuristic Car"

queue_job 23 \
  "Neon noir poster style, cinematic and sensual. A woman in a vivid red dress walks along a rain-slick city street beside a glossy sports car, tracing its aerodynamic curves with one finger while neon reflections ripple across the metal. Moody blue and magenta lighting, wet asphalt highlights, shallow depth of field, high-contrast shadows, futuristic urban elegance, atmospheric haze, premium automotive poster look. No extra text. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Neon Noir Rainy Street"

queue_job 24 \
  "Minimal surreal fashion poster, highly aesthetic and clean. A graceful woman in a flowing red dress walks beside a floating sports car in a pastel void, her fingertip tracing the impossible smooth curve of the car's body. Soft dreamlike lighting, empty negative space, sculptural composition, delicate motion, editorial beauty, muted background with strong red accent, polished modern poster design. No extra text. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Surreal Floating Car"

queue_job 25 \
  "Vintage glamour poster, dramatic and luxurious. A glamorous woman in a deep red velvet dress walks past a classic sports car under a focused studio spotlight, slowly tracing the car's rounded hood line with her finger. Film grain, rich shadows, golden highlights, elegant pose, timeless automotive advertising aesthetic, strong contrast, refined composition, cinematic elegance. No extra text. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Vintage Glamour Spotlight"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "A highly aesthetic poster-style composition: an elegant woman in a flowing red dress walking past a vintage cherry-red sports car, her fingertip gliding slowly along the car's curvy sculpted fender line as she passes. Sun-drenched Mediterranean street, cream pastel facades, warm golden-hour light, long soft shadows, retro 1960s travel-poster color grading, refined negative space in the upper third. Side tracking shot at hip level, subtle film grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Riviera Retro, Golden-Hour Side Tracking Shot"

queue_job 27 \
  "A highly aesthetic poster-style composition, minimalist editorial fashion photography: a poised woman in a fitted red dress walking past a matte pearl-white sports car inside a vast white studio, her finger tracing the car's sweeping curved roofline in one continuous motion. Crisp hard directional light, graphic elongated shadows, generous clean negative space, high-fashion magazine aesthetic, muted palette where the red dress is the only saturated color. Eye-level side view, ultra-clean graphic layout. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Minimalist Editorial, Studio Hard Light"

queue_job 28 \
  "A highly aesthetic poster-style composition, cinematic night scene: a confident woman in a sleek red dress striding past a glossy black sports car on rain-soaked city asphalt, her finger drawing a slow deliberate line across the car's curvy rear haunch. Neon signs reflecting in puddles and streaking along the car's body, teal-and-magenta palette with the red dress glowing, low dramatic angle, light atmospheric haze, noir poster mood, strong contrast. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Neon Noir, Low Angle Rain-Soaked Street"

queue_job 29 \
  "A highly aesthetic poster-style composition, 1960s glamour photography: a graceful woman in a red halter dress walking along a sunlit harbor promenade past a classic silver roadster, her fingertip tracing the car's long curving hood line. Monaco-style waterfront, yachts softly blurred in the background, pastel morning sky, warm Kodak Portra film tones, gentle grain, elegant editorial poster layout with wide empty sky space. Three-quarter angle, medium shot. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Harbor Glamour, Vintage Film Three-Quarter Angle"

queue_job 30 \
  "A highly aesthetic poster-style composition, wide cinematic shot: a woman in a long flowing red dress walking beside a burnt-orange classic sports car parked on an empty desert highway at sunset, her hand trailing along the car's curvy side profile as she moves. Dramatic gradient sky in peach and violet, heat haze on the horizon, long shadows stretching across the asphalt, epic minimal landscape, vintage poster color grading, strong horizontal symmetry. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Desert Highway, Wide Cinematic Sunset"


# --- DeepSeek Think Search ---
queue_job 31 \
  "A highly aesthetic Art Deco luxury poster, vertical composition. A woman in a flowing crimson silk dress walks past a midnight-blue sports car, her extended index finger tracing the car's curvy aerodynamic lines. Low front three-quarter angle, polished chrome reflections, warm gold and deep navy palette, geometric sunburst background, glossy marble floor, opulent 1920s glamour, dramatic cinematic lighting, ultra-detailed, high-contrast poster art. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Art Deco Luxury Poster"

queue_job 32 \
  "A highly aesthetic neo-noir cyberpunk poster, rain-slick city street at night. A woman in a red satin dress walks by a black sports car, her finger tracing its curvy silhouette through the wet neon reflections. High overhead angle, magenta and cyan neon glow, puddled asphalt mirroring the car's curves, fog, cinematic tension, moody shadows, futuristic poster style, hyper-detailed. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Neo-Noir Cyberpunk Poster"

queue_job 33 \
  "A highly aesthetic minimalist Swiss-style poster. A woman in a sharp red dress walks in profile beside a silver sports car, her fingertip tracing its curvy side profile. Eye-level side angle, soft even studio light, clean negative space, geometric blocks of white, grey, and red, precise composition, Bauhaus-inspired elegance, flat graphic shadows, modern high-fashion poster. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Minimalist Swiss Poster"

queue_job 34 \
  "A highly aesthetic surreal desert dream poster. A woman in a red dress walks slowly past a chrome sports car half-buried in golden sand, her finger tracing the car's curvy heat-hazed lines. Wide shot, low horizon, golden-hour sunlight, long dramatic shadows, shimmering mirage, dreamlike atmosphere, warm amber and crimson palette, cinematic surrealism, luxury editorial poster. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Surreal Desert Dream Poster"

queue_job 35 \
  "A highly aesthetic high-fashion graphic poster. Bird's-eye view of a woman in a vivid red dress walking beside a white sports car, her finger tracing its curvy sculpted lines. Stark white studio floor, hard flash lighting, deep black shadows, bold red accent, asymmetrical composition, modern luxury campaign, ultra-clean, photorealistic poster style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "High-Fashion Graphic Poster"


# --- MiniMax M3 ---
queue_job 36 \
  "Highly aesthetic poster style, square composition. A cinematic side-profile shot of a woman in a flowing red silk halter dress walking slowly past a low-slung matte black Lamborghini Huracán parked along a rain-slicked Tokyo street at midnight. Her left index finger trails delicately along the car's rear fender curve, tracing the rising shoulder line, her arm fully extended in an elegant horizontal line parallel to the ground. Her expression is calm, almost reverent, lips slightly parted, eyes half-lidded in appreciation. Harsh neon signage — magenta kanji and cyan store logos — reflects off the wet asphalt and the car's polished body. The red of her dress pops against deep indigo shadows and electric blue highlights. A single overhead streetlight casts a sharp rim light along her shoulder and the car's roofline. Shallow depth of field, the background bokeh dissolving into ribbons of color. Poster-grade composition with strong negative space above. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Midnight Neon Noir"

queue_job 37 \
  "Highly aesthetic poster style, square composition. A wide editorial shot inside a sun-drenched glass-walled car gallery at golden hour. A woman in a structured crimson midi dress with a thigh slit walks gracefully along the passenger side of a vintage red Ferrari 250 GTO, her fingertips just barely brushing the sculpted curve of the front wheel arch and flowing upward along the door line. She is captured mid-stride, weight shifted to her back leg, her hair catching the warm amber sunlight pouring through floor-to-ceiling windows. Dust motes float in the volumetric light beams. The composition is symmetrical and balanced — the car and woman form a single horizontal sweep across the middle third of the frame. Warm honey tones on the polished car paint, soft cream highlights on her skin, deep wine shadows. Editorial fashion photography aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Golden Hour Showroom"

queue_job 38 \
  "Highly aesthetic poster style, square composition. A dreamlike wide shot on a coastal highway at blue hour, a sleek silver McLaren 720S parked diagonally on the asphalt with the Pacific Ocean blurred in the deep teal background. A woman in a long flowing vermilion chiffon dress walks barefoot along the driver's side of the car, her right hand reaching down to trace the rising character line along the door with her fingertip, fabric of her dress trailing behind her in the soft sea breeze. The horizon line sits in the upper third, leaving generous sky for negative space. Cool steel-blue and lavender tones dominate, with the woman's red dress as the singular hot focal point against the muted palette. Gentle rim lighting from the dying sky catches her silhouette and the car's roof edge. Cinematic, ethereal, painterly atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Coastal Blue Hour"

queue_job 39 \
  "Highly aesthetic poster style, square composition. A minimalist high-fashion studio shot against a seamless charcoal-grey backdrop. A woman in a sculptural architectural red dress — sharp shoulders, fitted bodice, flared peplum hem — walks in profile across the frame from right to left, beside a glossy obsidian Porsche 911 GT3. Her index finger glides along the car's signature curved hip line at the rear quarter panel, the gesture creating a mirror symmetry between the curve of the car and the curve of her body. Studio lighting: a single hard key light from the upper left sculpting both forms, a soft red gel fill bouncing subtly off her dress onto the car's paint. The red reads as the only chromatic note in an otherwise monochromatic frame. Strong graphic poster geometry — diagonal of the car, horizontal of her walk, vertical of her arm. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Studio Monochrome Pop"

queue_job 40 \
  "Highly aesthetic poster style, square composition. A low cinematic angle looking up at a woman in a satin scarlet slip dress with thin gold chain straps walking past a vintage cherry-red Porsche 911 Carrera RS parked on a cobblestone European alley at night in the rain. Her left hand trails along the car's curved rear fender, fingertip lightly following the famous ducktail spoiler line, droplets running down her arm. Her gaze is cast downward, contemplative and tender, lips painted the same red as the car. Warm amber light spills from a nearby café window on the left, catching the rain as it falls in diagonal streaks; cool blue moonlight from the right carves the shadows. The wet cobblestones reflect both the car and the woman in a perfect mirrored pool beneath them. Rich color contrast — scarlet, amber, deep teal — film-grain texture, vintage romance-movie poster mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"2\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Rainy Night Romance"


echo "✅ All 40 jobs queued in scheduleri"
