#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 8 - fancy car drifting on wet Tokyo
#        street at night, dynamic camera angles and cinematic lighting,
#        mood of power, motion, drive, careless energy, varying POV from
#        almost directly above down to from inside the car,
#        bottom-center "8" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+8+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A bird's-eye drone shot looks straight down at a fire-orange supercar drifting through a rain-soaked Tokyo intersection at night, its tires screaming twin arcs of white smoke across mirrored asphalt. Neon signage smears into ribbons of pink and cyan beneath the chassis. The composition feels weightless and reckless, pure kinetic geometry, cinematic top-down framing with dramatic motion blur and glossy reflections. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Directly Overhead"

queue_job 2 \
  "From a high oblique crane angle, the camera hovers above and behind a matte-black GT-R sliding sideways through a neon Tokyo alley at night, sheets of rain kicked up by the rear wheels catching headlight glare. Skyscraper signage towers over the frame, streaking red and violet across wet pavement. The shot feels predatory and fast, cinematic depth of field, motion-charged and unapologetically bold. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "High Oblique Crane Angle"

queue_job 3 \
  "A low, street-level tracking shot runs parallel to a chrome-silver coupe as it drifts broadside through a Shibuya-style crossing at night, tires screeching against slick tarmac, sparks skittering from the undercarriage. Rain streaks horizontally across the lens, neon storefronts blur into smears of color, headlights flare like comet tails. The framing feels visceral and immediate, raw cinematic grit, drenched in restless urban adrenaline. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Street-Level Tracking Shot"

queue_job 4 \
  "An extreme low-angle shot, camera nearly scraping the wet asphalt, watches a crimson sports car's rear tire tear sideways just inches from the lens, throwing a curtain of spray and orange sparks into the dark. Neon reflections ripple across the flooded street beneath the chassis, headlights blaze overhead like twin suns. The mood is visceral, dangerous, and electric, close enough to feel the heat of the drift. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Extreme Low Angle Near Wheels"

queue_job 5 \
  "From inside the car, the driver's point of view frames white-knuckled hands gripping a leather steering wheel as the windshield fills with blurred neon streaks and rain-smeared Tokyo skyline whipping past at night. The dashboard glows faint amber, mirrors flash with headlight glare from a car sliding behind. The moment feels intimate yet chaotic, raw adrenaline, cinematic first-person tension, pure reckless momentum. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Inside the Car, Driver's POV"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "High-angle bird's-eye view looking almost directly down at a sleek, custom supercar power-sliding across a rain-slicked Tokyo intersection at night. Glowing neon signs and vibrant billboards reflect off the wet asphalt, casting rich magenta, cyan, and gold streaks. Throws of tire smoke and water spray swirl dynamically from the spinning wheels, capturing raw power, continuous motion, and a reckless, high-energy drive. Cinematic contrast, intense motion blur on the pavement, crisp dramatic lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Top-Down Overhead View"

queue_job 7 \
  "Dynamic drone shot positioned high above street level, tracking a metallic wide-body exotic sports car drifting sideways along a neon-lit Tokyo avenue in the rain. Towering skyscrapers with shimmering Japanese text line the background. Water spray kicks off the spinning rear tires under harsh, dramatic street lamps, conveying pure velocity, unbridled energy, and an aggressive, careless atmosphere. Rich cinematic reflections and vibrant night lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "High Three-Quarter Drone Angle"

queue_job 8 \
  "Ultra-low, ground-level tracking shot side-by-side with a hypercar sliding at extreme speeds through wet Tokyo streets at night. Glowing wet pavement, sharp specular reflections, and intense water spray coming off the spinning rims. High-contrast cinematic lighting with deep shadows and vibrant neon glows, capturing maximum drive, speed, and raw horsepower with a high-octane, careless vibe. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Low Street-Level Tracking Angle"

queue_job 9 \
  "Low-angle front perspective looking directly at the aggressive front grille of a high-end luxury sports car coming mid-drift into a corner. Volumetric smoke and rain spray erupt from behind the glowing headlights, with neon Tokyo streetlights creating long, vivid light trails across the wet road. Motion blur paints the surrounding urban background, oozing intense motion, unyielding momentum, and a dangerous, confident energy. Photorealistic, cinematic color grading. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Head-On Low Front Chase Angle"

queue_job 10 \
  "First-person point of view from inside the driver's seat of a customized supercar, hands gripped on a race-spec steering wheel, counter-steering through a drift. Through the rain-beaded windshield, the vibrant, neon-lit streets of Tokyo at night streak past in heavy motion blur. The digital dashboard glows softly while colorful exterior city lights cast chaotic reflections across the leather cabin, evoking pure power, instant reaction, and an adrenaline-fueled, reckless drive. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "First-Person Interior POV"


# --- ChatGPT ---
queue_job 11 \
  "A luxurious high-performance sports car drifting through a rain-soaked Tokyo intersection at night, viewed from an almost directly overhead perspective, the car carving a sharp sweeping arc through glossy black asphalt while water explodes outward from all four tires, long tire marks and reflected neon forming graphic curves across the street, dense Tokyo buildings and glowing storefronts compressed into a dramatic urban pattern below, colorful Japanese signs reflected in puddles, cinematic lighting with intense highlights, deep shadows, misty atmosphere, powerful sense of speed and controlled chaos, dynamic motion blur around the environment while the car remains crisp, sophisticated automotive photography, bold composition, careless energetic attitude, premium cinematic action-film aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "ChatGPT" "Almost Directly Above"

queue_job 12 \
  "A sleek exotic sports coupe drifting sideways across a wet Tokyo street at night, captured from a dramatic high oblique angle as if from a nearby rooftop, front wheels sharply counter-steering while the rear swings outward, thick spray of water erupting behind the tires, reflections of red, cyan and amber Tokyo neon stretching across the soaked pavement, traffic lights and blurred pedestrians safely distant on sidewalks, towering buildings disappearing into humid night haze, headlights cutting through the mist, cinematic contrast, low-angle-looking light reflections, strong diagonal composition, intense speed and motion, reckless carefree energy, polished high-end automotive commercial photography mixed with an action movie frame. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "ChatGPT" "High Oblique Rooftop View"

queue_job 13 \
  "A powerful luxury sports car violently drifting around a rain-drenched Tokyo corner at night, captured from an extremely low street-level front three-quarter viewpoint, the camera almost touching the wet pavement as the car charges diagonally toward the frame, front grille and sharp headlights dominating the composition, rear tires sliding outward and throwing a huge fan of water into the air, wet asphalt reflecting fragmented neon signs and glowing storefronts, blurred Tokyo traffic streaking in the background, dramatic backlight through rain and vapor, cinematic lens flare, aggressive perspective, crisp vehicle details against atmospheric motion blur, raw power, momentum and careless nighttime energy, premium cinematic automotive campaign aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "ChatGPT" "Street-Level Front Three-Quarter View"

queue_job 14 \
  "A luxurious performance coupe drifting at high speed through a narrow wet Tokyo street at night, camera positioned extremely close beside the moving car at wheel height, tracking parallel with the vehicle as the rear end slides dramatically toward the outside of the turn, spinning tires cutting through standing water and sending droplets across the lens, sculpted bodywork catching streaks of neon pink, blue and warm amber light, Japanese storefronts and illuminated signs stretching into colorful motion trails behind it, reflections rippling across the pavement, intense cinematic lighting, shallow depth of field, dynamic perspective and strong sense of acceleration, the scene feeling spontaneous, powerful and slightly reckless, like a frame from a stylish nighttime driving film. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "ChatGPT" "Beside the Car"

queue_job 15 \
  "A cinematic interior view from inside a luxurious sports car drifting through rainy Tokyo at night, camera positioned low between the driver and center console looking diagonally forward through the windshield, the steering wheel turned sharply as the driver controls the slide, hands and illuminated dashboard instruments visible in the foreground, windshield covered with rain droplets and sweeping reflections, the Tokyo street outside tilted dramatically by the drift, neon signs and headlights smearing into colorful streaks across the glass, water spraying past the side windows, occasional glimpses of the sliding hood and wet road, atmospheric cabin lighting, powerful cinematic contrast, visceral sense of speed and movement, carefree rebellious energy, immersive high-end automotive film aesthetic, realistic materials and finely detailed interior. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "ChatGPT" "From Inside the Car"


# --- Grok fast ---
queue_job 16 \
  "Aerial bird's-eye view looking almost straight down on a sleek high-end sports car drifting hard through a rain-slicked Tokyo intersection at night, neon reflections stretching and spinning across the wet asphalt like liquid light, tire smoke and water spray curling outward in perfect arcs, powerful motion and careless energy radiating from the controlled slide, ultra-cinematic lighting with sharp highlights and deep shadows, dynamic overhead perspective emphasizing pure speed and dominance. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Grok fast" "Almost Directly From Above"

queue_job 17 \
  "High-angle three-quarter view from above and slightly behind a luxurious exotic car sideways-drifting on a glistening wet Tokyo street at night, city lights and neon signs streaking into long reflections on the pavement, the car's body low and aggressive as it carves through the rain, cinematic lighting with dramatic contrast, raw power and effortless motion, careless high-energy vibe, dynamic camera capturing the full arc of the slide. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Grok fast" "High Three-Quarter Aerial"

queue_job 18 \
  "Low-to-mid side tracking shot racing alongside a fancy performance car in a full drift on a rain-soaked Tokyo avenue at night, headlights cutting through mist, neon glow painting the wet road and car body, sparks and water droplets flying, intense cinematic lighting, pure drive and kinetic force, careless adrenaline-fueled energy, dynamic motion blur on the background while the car stays razor-sharp. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Grok fast" "Mid-Level Tracking Side"

queue_job 19 \
  "Aggressive low-angle front three-quarter view of a high-end sports car sliding sideways toward the camera on a shiny wet Tokyo street at night, headlights flaring, rain spraying upward, neon reflections exploding across the asphalt, cinematic lighting with strong rim light and deep blacks, overwhelming sense of power, motion, and reckless drive, dynamic composition that feels like the car is about to pass right under the lens. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Grok fast" "Low Front Three-Quarter"

queue_job 20 \
  "Point-of-view from the driver's seat inside a luxury sports car mid-drift on a wet Tokyo street at night, hands on the wheel, dashboard and steering wheel in sharp focus, city neon and rain-streaked windshield blurring past in a wild kinetic rush, reflections dancing across the glass, cinematic interior lighting mixed with external neon glow, intense power, motion, and careless high-energy drive, the world outside spinning with controlled chaos. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Grok fast" "From Inside the Car"


# --- Qwen 3.8 Max ---
queue_job 21 \
  "A fancy car drifting on a wet Tokyo street at night from almost directly above. Bird's-eye top-down drone shot showing the vehicle's roof and the curving tire marks on the glowing puddles. Dynamic camera angles and cinematic lighting emphasizing the vibrant neon reflections off the dark asphalt. The mood is power, motion, drive, a careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Top-Down Bird's-Eye View"

queue_job 22 \
  "A fancy car drifting on a wet Tokyo street at night viewed from a high diagonal angle. Shot from a pedestrian overpass looking down at the sports car sliding sharply through a busy intersection. Dynamic camera angles and cinematic lighting with glowing cyberpunk signs illuminating the mist and rain. The mood is power, motion, drive, a careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "High Diagonal Angle"

queue_job 23 \
  "A fancy car drifting on a wet Tokyo street at night captured in a low side-profile tracking shot. Eye-level perspective parallel to the sliding vehicle, capturing heavy water splashing from the spinning tires. Dynamic camera angles and cinematic lighting highlighting the sleek aerodynamic curves against the dark city backdrop. The mood is power, motion, drive, a careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Low Side-Profile Tracking Shot"

queue_job 24 \
  "A fancy car drifting on a wet Tokyo street at night shot from an extreme low angle tracking the rear quarter-panel. Focus on the aggressive wheel spin and thick tire smoke mixing with the wet street. Dynamic camera angles and cinematic lighting piercing through the shadows with bright red taillights and neon street signs. The mood is power, motion, drive, a careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Extreme Low Angle, Rear Quarter-Panel"

queue_job 25 \
  "A fancy car drifting on a wet Tokyo street at night seen from inside the car. Driver's POV looking out the passenger window, showing the luxurious leather steering wheel and glowing dashboard in the immediate foreground. Dynamic camera angles and cinematic lighting casting ambient neon glows across the interior cabin as the blurred city rushes by. The mood is power, motion, drive, a careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Interior Cockpit, Driver's POV"


# --- GLM 5.3 Max ---
queue_job 26 \
  "Top-down aerial view, camera almost directly overhead, capturing a sleek black luxury sports coupe mid-drift through a rain-slicked Tokyo intersection at night. Glowing white S-curves of tire tracks carve through the wet asphalt, neon signs bleeding pink, cyan, and gold reflections across the mirrored street. Headlights cast two long radiating beams cutting through drifting tire smoke. Cinematic high-contrast lighting, moody urban atmosphere, reckless power and velocity frozen from the sky. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Top-Down Aerial"

queue_job 27 \
  "Elevated three-quarter overhead angle from a rooftop vantage point, looking down at roughly 45 degrees onto a metallic silver supercar sliding sideways through a narrow neon-drenched Tokyo street at night. Rain streaks the frame, taillights smear red across the wet pavement, a rooster tail of water spray fans out behind the rear wheels. Towering buildings with glowing kanji signage frame the scene, anamorphic cinematic lighting, dramatic shadows, dynamic diagonal composition conveying motion and careless energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "High Three-Quarter Angle"

queue_job 28 \
  "Eye-level side tracking shot, perfectly parallel to a deep midnight-blue JDM sports coupe caught mid-drift on a glistening Tokyo boulevard at night. Neon signs, vending machines, and passing taxis blur into horizontal streaks of light behind the car, its wet body panels rippling with reflections. Water sprays from the rear wheels in a glowing fan, headlights carving through light fog. Cinematic lighting, shallow depth of field, a mood of raw power, speed, and untamed confidence. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Eye-Level Side Tracking Shot"

queue_job 29 \
  "Extreme low worm's-eye angle from street level, camera inches above the wet asphalt, looking up at a pearl-white luxury GT drifting toward the lens on a rain-soaked Tokyo street at night. Blinding headlights flare directly into the camera, mirror-like puddles exploding with reflected neon pinks and electric blues, tire spray fanning out like mist. Glowing signage and the city skyline loom overhead, cinematic lens flares, dramatic upward perspective emphasizing dominance, power, and reckless momentum. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Low Worm's-Eye Angle"

queue_job 30 \
  "Interior view from the passenger seat, framed on the driver mid-drift on a rain-slicked Tokyo street at night. Gloved hands wrench the steering wheel, dashboard gauges glowing amber and red, the rain-streaked windshield smearing the outside world into ribbons of neon pink, cyan, and white. City reflections slide across the wet glass, cinematic rim lighting traces the driver's silhouette, motion blur pulls everything sideways, a mood of adrenaline, control, and careless thrill. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "From Inside the Car"


# --- DeepSeek Think Search ---
queue_job 31 \
  "Almost directly top-down overhead drone shot of a fancy car drifting on a wet Tokyo street at night, seen from straight above as it slides sideways through a neon-lit intersection, tire smoke curling around the roof, rain-slick asphalt mirroring pink and cyan signs, dynamic camera angles and cinematic lighting, mood of power, motion, drive, and careless energy, high contrast, motion blur, photorealistic." \
  "DeepSeek Think Search" "Top-Down Overhead Drone Shot"

queue_job 32 \
  "High three-quarter aerial crane shot looking down at a fancy car drifting on a wet Tokyo street at night, camera tilted dynamically above and behind the slide, neon kanji reflections streaking across wet pavement, tire spray and rain in the air, dynamic camera angles and cinematic lighting, mood of power, motion, drive, and careless energy, ultra-detailed and energetic." \
  "DeepSeek Think Search" "High Three-Quarter Aerial Crane Shot"

queue_job 33 \
  "Low ground-level side tracking shot, camera skimming inches above wet Tokyo asphalt as a fancy car drifts past at night, wheels angled hard, tire smoke billowing, neon signs smeared into motion trails, dynamic camera angles and cinematic lighting, mood of power, motion, drive, and careless energy." \
  "DeepSeek Think Search" "Low Ground-Level Side Tracking Shot"

queue_job 34 \
  "Low front three-quarter chase angle, almost directly in the path of a fancy car drifting on a wet Tokyo street at night, headlights flaring, rain and neon reflections exploding across the lens, the car sliding toward camera then whipping away, dynamic camera angles and cinematic lighting, mood of power, motion, drive, and careless energy." \
  "DeepSeek Think Search" "Low Front Three-Quarter Chase Angle"

queue_job 35 \
  "From inside the car, over-the-shoulder passenger POV through the windshield as a fancy car drifts on a wet Tokyo street at night, driver counter-steering, neon city blurring through rain-streaked glass, dashboard glow, dynamic camera angles and cinematic lighting, mood of power, motion, drive, and careless energy." \
  "DeepSeek Think Search" "Inside the Car, Passenger POV"


# --- MiniMax M3 ---
queue_job 36 \
  "A sleek matte-black Nissan GT-R drifting sideways through a rain-slicked Tokyo intersection at night, neon signs bleeding pink and cyan across the wet asphalt. Shot almost directly from above, looking straight down, the car carving a perfect arc through standing water with spray fanning out behind it. Dynamic top-down composition, cinematic lighting from overhead billboards and traffic signals, motion blur on the tires, reflections shimmering. Mood: raw power, reckless speed, untouchable energy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Overhead"

queue_job 37 \
  "A luxury silver Lamborghini Huracán sliding around a wet Shibuya corner at night, tail lights streaking red through the rain. High three-quarter aerial angle, slightly behind and above, the rooftop of the car dominating the frame as it slides toward the camera. Tokyo's glowing storefronts and vending machines blurred beneath, rain droplets catching neon, cinematic shallow depth, reflections everywhere. Mood: dominant, untamed, pure adrenaline. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "MiniMax M3" "High Bird's-Eye, Three-Quarter Top"

queue_job 38 \
  "A custom widebody Porsche 911 drifting low and fast along a rain-drenched Tokyo street at night, smoke pouring off the rear tires. Low side-tracking angle, camera nearly at tire height, the car roaring past horizontally across the frame, wet road mirroring every neon reflection. Cinematic orange streetlight rim, blue shadow tones, motion blur in the background buildings, hyper-detailed car body, splashing puddles frozen mid-air. Mood: wild, fearless, unstoppable. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Low Side Tracking Shot"

queue_job 39 \
  "A glossy black Mercedes-AMG GT sliding sideways toward the camera on a wet Tokyo avenue at night, headlights slicing through the rain. Front three-quarter hood-level angle, the car's aggressive grille and wide fender filling the foreground as it drifts closer, neon Tokyo signage exploding in the wet asphalt behind. Cinematic volumetric rain, blue-purple highlights on the bodywork, warm amber undertones from storefronts. Mood: cinematic chaos, control under pressure, pure thrill. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Front Three-Quarter, Hood-Level"

queue_job 40 \
  "A black Toyota Supra drifting hard through a rain-soaked Tokyo backstreet at night, windshield wipers swinging across the glass, hands gripping the steering wheel tight. Shot from inside the cabin, driver's POV looking out through the windshield and side window, the wet road rushing past, neon signs streaking across the glass, dashboard glowing faintly. Cinematic first-person perspective, rain on the windshield catching every light, blurred motion of the city outside, sharp focus on the wheel and the road ahead. Mood: reckless, alive, fully committed to the drive. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"8\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Inside the Car, Driver POV"


echo "✅ All 40 jobs queued in scheduleri"
