#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 9 - colorful berries close-up/macro
#        shots (farmers market display down to a couple of berries on a
#        wooden table), bright and colorful, bottom-center "9" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+9+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A close-up of an overflowing farmers market berry stall: wooden crates stacked with strawberries, blueberries, raspberries, blackberries, and golden berries, their colors clashing in vivid contrast under warm morning light. Dew still clings to the skins, catching soft highlights. Shot like a still-life food photograph, shallow depth of field, rustic wood grain textures framing the edges. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Farmers Market Display"

queue_job 2 \
  "A tighter macro shot of a rustic woven basket brimming with mixed berries, raspberries sharp in focus in the foreground while blueberries and blackberries blur softly behind in a dreamy bokeh. Golden hour light rakes across the surface, saturating reds, deep purples, and near-black tones into a rich, painterly palette. The composition feels intimate, almost like a Dutch still-life study. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Woven Basket, Mixed Berries"

queue_job 3 \
  "An extreme macro shot of a small ceramic bowl cradling a handful of berries, individual seeds and glistening dew droplets rendered in crisp texture. Sunlight rakes low across the surface, casting long soft shadows and igniting the reds and blues with saturated glow. The framing is tight and sculptural, evoking a high-end culinary photograph. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Ceramic Bowl, Extreme Macro"

queue_job 4 \
  "A dynamic macro shot of berries spilling and rolling across a weathered wooden table, strawberries, blueberries, and raspberries caught mid-motion with a few droplets of juice glistening nearby. Dramatic side lighting sculpts each berry's form, deep shadows contrasting against the warm wood grain, colors popping in a bold, almost cinematic still-life style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Berries Spilling on Wood"

queue_job 5 \
  "A minimalist extreme macro of just two berries, one plump strawberry and one dew-flecked blueberry, resting side by side on a rustic wooden table. Soft natural window light falls diagonally, shallow depth of field melting the background into warm blur, the composition quiet and painterly like a single-subject still-life study. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Two Berries, Minimal Table"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "Macro photo of a lively farmers market stall display packed with vibrant summer berries. Ripe, glossy red strawberries, plump dark blackberries, deep indigo blueberries, and vivid scarlet raspberries are arranged in rustic wooden punnets side by side. Natural bright morning sunlight illuminates the crisp textures, water droplets, and rich jewel-toned colors of the fruit. High detail, shallow depth of field focusing on the overlapping berries in the foreground with a soft, warm blurred background. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Farmers Market Berry Array"

queue_job 7 \
  "Extreme macro close-up of a rustic oak table surface hosting translucent red currants, glossy black currants, and golden-green striped gooseberries. Soft natural directional light reveals fine surface details, fine tiny hairs on the gooseberry skin, and crystal-clear water droplets clinging to the vibrant skins. The color palette bursts with contrasting ruby red, emerald green, and deep violet tones against the warm, dark grain of the wood. Cinematic lighting, sharp focus on the central cluster. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Dew-Kissed Gooseberries & Currants"

queue_job 8 \
  "Vibrant macro shot of fresh blueberries, bright red raspberries, and golden groundcherries scattered across a weathered teak table. Sunlight filters through, accentuating the dusty bloom on the indigo blueberry skins, the rich velvety texture of the raspberries, and the fiery orange hue of the physalis. High contrast, saturated natural colors, crisp detail, with a gently blurred background highlighting the scattered fruit composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Mixed Berry Splash on Sunlit Wood"

queue_job 9 \
  "Close-up shot of two oversized, plump blackberries resting side by side with a pair of brilliant red raspberries on a dark mahogany wood surface. Warm golden-hour light catches the individual glossy drupelets of the berries, creating intense highlights and saturated color contrasts between deep purple-black and vivid crimson. Ultra-detailed macro photography, razor-sharp focus on the fruit textures with smooth bokeh. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Golden Hour Berry Pair"

queue_job 10 \
  "High-angle macro photograph of a colorful market display featuring an eclectic mix of bright berries, vibrant purple mulberries, bright pink salmonberries, translucent red currants, and dark wild blueberries. The berries form a dense, vivid mosaic of contrasting colors and textures, backlit by soft, diffused outdoor daylight to make the colors pop. Crisp details on berry surfaces, water droplets, and delicate stems, with a ultra-shallow depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Exotic Berry Medley Display"


# --- ChatGPT ---
queue_job 11 \
  "A vibrant photorealistic macro photograph of a colorful farmers market berry display, overflowing with blueberries, raspberries, strawberries, blackberries, red currants, black currants, gooseberries, and golden berries arranged in rustic wooden crates. Bright natural morning light makes every berry glossy and saturated, with tiny droplets of water catching the light. Extremely detailed skin texture, delicate stems and leaves, rich reds, deep blues, purples, pinks, and golden yellows, shallow depth of field, softly blurred market stalls and shoppers in the background, inviting summer atmosphere, professional food photography, crisp foreground details and luminous highlights. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "ChatGPT" "Berry Market Glow"

queue_job 12 \
  "A close-up photorealistic food photograph of several small wicker baskets filled with different fresh berries at a lively farmers market, with red strawberries, bright raspberries, dark blackberries, glossy blueberries, ruby red currants, black currants, pale green gooseberries, and tiny golden berries creating a vivid natural color palette. The camera is positioned just above the display, focusing sharply on the berries in the nearest baskets while the surrounding market softly dissolves into colorful bokeh. Strong but natural daylight, sparkling moisture droplets, intricate berry textures, realistic imperfections, rich saturated colors, cheerful summer mood, premium editorial food photography, beautiful layered composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "ChatGPT" "Colorful Berry Baskets"

queue_job 13 \
  "An extreme macro photograph of a mixed pile of fresh berries spilling from a rustic wooden market tray, with a few strawberries, raspberries, blueberries, blackberries, red currants, purple currants, gooseberries, and golden berries overlapping naturally. The camera is extremely close to the fruit, revealing tiny hairs on raspberries, translucent currant skins, delicate strawberry seeds, subtle bloom on blueberries, and minute water droplets. Bright colorful lighting with soft sunlight from the side, vivid reds, magentas, blues, violets, greens, and golds, creamy shallow depth of field, highly detailed foreground, dreamy blurred farmers market atmosphere behind, joyful fresh summer feeling, sophisticated commercial food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "ChatGPT" "Berry Cascade"

queue_job 14 \
  "A minimalist photorealistic macro still life of only a few exceptionally beautiful berries resting on a weathered wooden table, featuring two ripe berries in the sharpest foreground with several different colorful berries loosely scattered farther behind. Deep blue blueberry, vivid red raspberry, glossy blackberry, ruby currants, and a small golden berry create striking color contrast against warm natural wood grain. Tiny droplets of moisture sparkle on the fruit, with soft afternoon sunlight creating delicate shadows and glowing translucent edges. Extremely shallow depth of field, intimate camera angle almost level with the table, exquisite fruit texture, realistic imperfections, bright cheerful colors, elegant editorial food photography, simple composition with generous visual breathing room. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "ChatGPT" "Two Berries on Wood"

queue_job 15 \
  "A spectacular ultra-close macro photograph looking across a wooden table covered with a carefully arranged rainbow of fresh berries, transitioning naturally from golden gooseberries and orange berries through red strawberries and raspberries into purple currants, dark blackberries, and deep blue blueberries. The camera focuses on a small cluster of berries in the middle while the surrounding fruit becomes beautifully abstract through extreme shallow depth of field. Bright diffused daylight, intense natural color, glossy surfaces, microscopic textures, delicate stems, tiny droplets, subtle reflections, rich wooden grain underneath, fresh farmers market feeling, colorful yet realistic, premium commercial food photography, cinematic macro optics and exceptionally crisp detail where the focus falls. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "ChatGPT" "Rainbow Berry Macro"


# --- Grok fast ---
queue_job 16 \
  "Bright and colorful close-up of a vibrant farmers market berry display, overflowing baskets of mixed berries in every shade, deep red strawberries, glossy blueberries, juicy blackberries, golden raspberries, and plump purple mulberries, arranged in rustic wooden crates under soft natural daylight, macro detail on glistening skins and tiny water droplets, rich saturated colors, shallow depth of field, ultra-detailed, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Grok fast" "Farmers Market Berry Display"

queue_job 17 \
  "Macro close-up of a few colorful berries scattered on a rustic wooden table, bright red strawberries next to indigo blueberries and ruby raspberries, soft morning light highlighting their juicy textures and vibrant hues, tiny seeds and fine surface details sharply focused, warm wood grain in the background, cheerful and vivid color palette, high-resolution photorealism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Grok fast" "Mixed Berries on Wooden Table"

queue_job 18 \
  "Extreme close-up macro shot of a cascading pile of multicolored berries tumbling from a farmers market basket onto a wooden surface, vivid reds, blues, purples, and golds of strawberries, blueberries, blackberries, and raspberries catching bright sunlight, glistening with freshness, ultra-sharp details on individual berries, lively and saturated colors, professional food photography style. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Grok fast" "Cascade of Colorful Berries"

queue_job 19 \
  "Bright macro photograph of a tight cluster of different-colored berries resting on a weathered wooden table, one perfect strawberry, a few blueberries, and a couple of raspberries in sharp focus against a softly blurred background, radiant natural light enhancing their juicy brightness and rich pigments, crisp textures and fine details, cheerful and colorful food close-up. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Grok fast" "Single-Focus Berry Cluster"

queue_job 20 \
  "Close-up macro view transitioning from a lively farmers market berry stall filled with rainbow-hued berries in wooden displays to a simple arrangement of a few mixed berries on a wooden table in the foreground, vibrant reds, blues, and purples glowing under bright daylight, ultra-detailed skins and droplets, saturated joyful colors, photorealistic depth and clarity. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Grok fast" "Farmers Market to Table Transition"


# --- Qwen 3.8 Omni Flash ---
queue_job 21 \
  "An ultra-high-resolution macro shot of a bustling farmer's market stall overflowing with fresh produce. Focus on vibrant clusters of strawberries, blueberries, raspberries, and blackberries arranged in rustic wooden crates. Sunlight filters through an open-air canopy, creating dappled lighting that enhances the natural glossiness and deep saturation of the fruit skins. Dew drops cling delicately to the berries, reflecting tiny rainbows. Shallow depth of field blurs the background shoppers into soft bokeh, keeping the foreground fruits razor-sharp and inviting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash" "Rainbow Harvest Display"

queue_job 22 \
  "A cinematic close-up composition featuring a scattered handful of mixed berries, ruby red cherries, golden gooseberries, and deep purple mulberries, resting on a weathered oak table surface. Soft, warm morning sunlight streams from the left side, casting long, gentle shadows and highlighting the intricate textures of the wood grain against the smooth, taut skin of the fruit. The colors are vivid yet natural, emphasizing freshness and organic beauty. High-detail texture rendering captures every pore and stem. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash" "Morning Light on Wood"

queue_job 23 \
  "An extreme macro photography style image focusing tightly on three single berries placed diagonally across the frame: one glossy strawberry, one matte-finish blueberry, and one textured raspberry. The lens is positioned inches away, revealing microscopic details like hair-like filaments on the strawberry seeds and the waxy bloom on the blueberry. Bright, even studio lighting eliminates harsh shadows, allowing the intense, saturated colors to pop against a clean, neutral light-gray background. Sharp focus peaks on the central berry, with slight falloff towards the edges. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash" "Jewel-Toned Micro World"

queue_job 24 \
  "A top-down angled view looking into a woven wicker basket filled with an abundant mix of seasonal berries. Blackberries, currants, and huckleberries tumble over each other, creating a chaotic but beautiful pattern of dark purples, blues, and blacks contrasted by bright reds. Natural daylight illuminates the scene, bringing out the juicy translucency of some berries while others remain opaque and rich. The surrounding environment hints at a sunny orchard floor with blurred green leaves in the periphery. Rich color grading emphasizes vibrancy and freshness. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash" "Farm-Fresh Assortment"

queue_job 25 \
  "A stylized, high-contrast macro shot of dew-covered berries isolated against a pure white background to maximize color intensity. Clusters of electric-blue bilberries, neon-pink dragonfruit segments (interpreted as exotic berries), and fiery-orange sea buckthorn berries dominate the frame. The lighting is crisp and cool, enhancing the jewel-like appearance of the fruit surfaces. Every droplet of water acts as a miniature lens, refracting light and adding sparkle. The composition is dynamic, with berries appearing to float slightly above the surface due to precise shadow control. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash" "Neon Nature Close-Up"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "Vibrant farmers market stall overflowing with wooden crates of fresh berries: glossy red strawberries, deep purple blackberries, bright blue blueberries, and pink raspberries stacked in colorful mounds, morning sunlight streaming across the display, saturated natural colors, shallow depth of field, shot on 50mm f/1.8, cheerful summer atmosphere, ultra-detailed textures, crisp fruit skins with tiny dew droplets, colorful chalkboard signs blurred in background, high dynamic range, professional food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Farmers Market Berry Bazaar"

queue_job 27 \
  "Extreme macro shot of a single ripe blackberry and a plump raspberry side by side on a weathered oak wooden table, individual drupelets sparkling with micro water droplets, rich magenta and inky purple tones popping against warm honey-toned wood grain, soft diffused window light, 100mm macro lens, f/2.8, razor-sharp focus on fruit texture, creamy bokeh background, hyper-detailed, vivid saturated colors, studio-quality food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Extreme Macro Blackberry & Raspberry Duo"

queue_job 28 \
  "Top-down flat lay of a generous handful of mixed berries scattered across a rustic reclaimed wooden table: ruby strawberries with green leafy caps, sapphire blueberries, deep burgundy cherries, and golden yellow goldenberries, bright cheerful daylight, playful scattered composition, bold saturated color palette, 35mm lens, deep depth of field, natural wood knots and grain visible, fresh and appetizing, editorial food magazine style, crisp and clean. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Scattered Berry Confetti on Rustic Wood"

queue_job 29 \
  "Stunning close-up of a small cluster of plump fresh blueberries piled on a dark walnut wooden table, dusty blue bloom on the skins catching golden morning light, a few green and pink unripe berries adding color contrast, backlit rim lighting, water droplets glistening, 90mm macro lens, f/4, rich indigo and turquoise color grading, luminous and bright, extreme detail, professional macro food photography, joyful summer mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Blueberry Cluster Close-Up with Dew"

queue_job 30 \
  "Bright close-up of three glossy red strawberries with fresh green stems arranged on a light farmhouse wooden table, warm golden-hour sunlight casting soft long shadows, tiny seeds in sharp focus, vivid scarlet red against pale golden wood, two blueberries resting nearby for color contrast, 85mm lens, f/2.0, dreamy soft bokeh, fresh-picked harvest feeling, cheerful pastel and saturated tones, high-resolution commercial food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Strawberry Trio on Sunlit Farmhouse Table"


# --- DeepSeek Think Search ---
queue_job 31 \
  "A vibrant close-up macro shot of a farmers market berry display, overflowing wooden crates filled with bright red strawberries, deep blue blueberries, glossy black blackberries, and golden raspberries, dew droplets glistening on the fruit, colorful handmade price signs tucked between the crates, warm morning sunlight streaming across the stall, shallow depth of field with creamy bokeh, hyper-detailed textures, saturated colors, professional food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Farmers Market Berry Display"

queue_job 32 \
  "A bright and colorful macro photograph of three berries resting on a weathered wooden table, one plump red raspberry, one dark blue blueberry, and one shiny black currant, arranged in a loose triangle, soft natural window light from the side, visible wood grain and tiny berry hairs in sharp focus, vivid saturated hues against the warm brown wood, shallow depth of field, high-end food photography, crisp detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Rustic Wooden Table Trio"

queue_job 33 \
  "An extreme close-up of a ceramic bowl filled with a rainbow assortment of fresh berries, crimson strawberries, purple acai berries, bright orange physalis, green gooseberries, and ruby red currants, each berry glistening with moisture, vivid complementary colors, soft diffused daylight, macro lens detail showing tiny seeds and skin textures, cheerful and appetizing composition, ultra-saturated color palette. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Rainbow Berry Bowl Macro"

queue_job 34 \
  "A bright macro shot of a cupped pair of hands holding a colorful mix of freshly picked berries, red strawberries, blue blueberries, golden raspberries, and black mulberries tumbling slightly between the fingers, sunlit outdoor setting with soft green background bokeh, glowing natural light, hyper-realistic skin and fruit texture, vivid jewel-toned colors, joyful harvest mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Handful of Fresh Berries"

queue_job 35 \
  "A minimalist bright macro photograph of just two berries on a rustic wooden cutting board, one vibrant red strawberry and one deep blue blueberry side by side, dramatic soft studio lighting, rich saturated colors, fine details of seeds and glossy skin, warm wood grain texture, clean uncluttered composition with generous negative space, high-end commercial food photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Couple of Berries on Wooden Board"


# --- MiniMax M3 ---
queue_job 36 \
  "A vibrant farmer's market produce stand overflowing with an abundant, colorful arrangement of fresh berries in rustic woven baskets and wooden crates. Glossy red strawberries, plump blueberries, ruby raspberries, golden raspberries, deep purple blackberries, pale white mulberries, and bright pink currants are artfully piled together under warm morning sunlight. Shallow depth of field, soft bokeh of market stalls in the background, sun flares and natural highlights bouncing off the berries' dewy surfaces. Shot at f/2.8, eye-level angle, vivid saturated colors, hyper-realistic photography style, ultra-sharp detail on the foreground berries. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Farmer's Market Stand Display"

queue_job 37 \
  "Extreme macro photograph of a single ripe raspberry resting on a weathered, sunlit wooden table, every tiny drupelet and hair-like trichome rendered in razor-sharp detail. A shallow drop of morning dew sits on the fruit's surface, refracting light. Warm golden hour light streams in from the left, casting soft elongated shadows across the textured oak grain. Hyper-detailed, photorealistic, vibrant raspberry red against honey-toned wood, with a creamy blurred background. Shot at f/4, 100mm macro lens, ultra-high resolution. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Macro Single Berry on Wooden Table"

queue_job 38 \
  "A simple, intimate still life of two berries placed on a softly lit rustic wooden table: one halved strawberry showing its juicy cross-section with seeds and pale core, alongside one whole plump blueberry. Soft natural window light from the upper left, muted earth-tone linen napkin partially visible at the edge of the frame. Clean minimalist composition, shallow depth of field, painterly background blur, warm color palette balancing crimson red and deep indigo against golden wood tones. Photorealistic food photography, f/2.0, 85mm lens, natural color grading. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Berry Couple on Rustic Wooden Table"

queue_job 39 \
  "Tight macro shot of a colorful cluster of mixed berries, bright red strawberries, golden gooseberries, white currants, deep blue blueberries, and dark purple elderberries, packed densely together filling the entire frame. Each berry catches the light differently: glossy reflections, translucent highlights, soft shadows between fruits. Slight water droplets on surfaces for freshness. Vivid, saturated, joyful color palette. Studio-quality product photography look with soft diffused overhead lighting, ultra-sharp focus across the cluster, f/5.6, 60mm macro, rich color depth, 8K detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Macro Cluster of Mixed Color Berries"

queue_job 40 \
  "Closeup photograph of a wooden farmer's crate freshly filled to overflowing with bright red strawberries, the hero variety front and center. Background softly blurred showing neighboring crates of contrasting berries, blueberries, blackberries, raspberries, creating a colorful market context. Strong natural sunlight, soft shadow play, dewy fruit surfaces, vivid crimson reds dominating with pops of blue and purple behind. Slight film-grain warmth, editorial food photography style, eye-level angle, f/3.5, 50mm lens, high contrast yet natural color rendering. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"9\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Farmer's Crate Closeup, Single Variety Hero"


echo "✅ All 40 jobs queued in scheduleri"
