#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 4 - romantic photorealistic couple
#        with car, watching a night sky from a hill with a big city view,
#        varying couple positions (both on the hood, one inside and one on
#        the hood, both in front of the car), mood and angles vary,
#        bottom-center "4" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+4+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "Photorealistic romantic scene on a quiet hillside overlook at night, a couple lying back together against the windshield on the hood of a parked car, faces tilted upward toward a star-scattered sky, a sprawling city skyline glowing in soft bokeh far below. Warm skin tones against cool blue shadow, wide-angle composition balancing intimacy with vastness, cinematic golden-to-night color grade, shallow depth of field, Roger Deakins-inspired naturalistic lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Lying on Hood, Windshield View"

queue_job 2 \
  "Photorealistic night photograph shot from a low ground-level angle looking up past the car's hood, a couple seated close together, shoulders touching, fingers interlaced, heads tilted back to take in the Milky Way overhead, the distant metropolis forming a glittering horizontal band of light beneath the hill's edge. Soft rim lighting from the city glow, gentle romantic mood, 35mm lens character, subtle film grain, cool nocturnal palette with warm highlights on their faces. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Seated Together, Low Angle"

queue_job 3 \
  "Photorealistic candid moment, one partner leaning out through the open driver's window with chin resting on folded arms atop the door frame, the other seated on the hood turned toward them mid-laugh, the car parked at a hillside vantage with the city's lights sprawled out below like scattered embers. Medium shot, three-quarter angle, warm interior dashboard glow mixing with cool starlight, tender playful atmosphere, shallow focus isolating the couple against the blurred skyline. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Window Lean, Hood Laugh"

queue_job 4 \
  "Photorealistic wide establishing shot, a couple standing close in front of the parked car, backs resting against the hood, one arm draped over the other's shoulder as they gaze out at the vast city panorama glowing beneath the dark hillside, a canopy of stars stretching above. Cinematic silhouette-forward lighting with the skyline's ambient glow rimming their forms, cool deep-blue night tones, contemplative romantic mood, slight high-angle drone-style perspective emphasizing scale. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Standing Against Hood, Panorama"

queue_job 5 \
  "Photorealistic intimate scene, one partner lying flat on the car's hood gazing straight up at the stars, the other sitting cross-legged beside them, pointing toward a constellation with a soft smile, the hillside falling away to a dense, glittering city grid below. Close telephoto framing compressing the skyline into a luminous backdrop, warm-cool contrast between skin tones and ambient city light, dreamy shallow-focus atmosphere, quiet playful intimacy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Lying Down, Pointing at Stars"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "Wide-angle romantic photorealistic photograph of a young couple sitting together on the hood of a classic vintage coupe, parked at the edge of a high grassy hill overlooking a vast, glowing metropolis at night. Soft, warm city light glows on the horizon, while a clear night sky filled with faint stars and subtle nebulae stretches above. The couple is wrapped in a cozy woven blanket, leaning against each other. Cinematic lighting, deep atmospheric blues and warm golden city reflections, soft focus on the distant cityscape, high detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Blanket on Hood, Vintage Coupe"

queue_job 7 \
  "Eye-level low-angle romantic photorealistic shot of an off-road SUV parked on a mountain overlook at night. One person sits on the vehicle's warm hood looking up at the sky, while the partner leans out of the open passenger window, resting their elbows on the frame to look up at them. In the far background, a dense, sparkling city grid spreads out across the valley floor under a deep navy night sky. Moody teal and amber color grading, wet pavement reflecting ambient light, photorealistic texture on the car metal and leather jackets. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Hood and Window, SUV Overlook"

queue_job 8 \
  "Romantic photorealistic night scene taken from behind a sleek modern sedan parked on a rocky cliffside. In front of the car, a couple stands close together near the edge, silhouettes framed by the dazzling sea of city lights spread across the panoramic horizon below. Soft moonlight illuminates the car's subtle body lines and taillight accent glow. A dramatic night sky with faint milky way dusty trails stretches above. Tender atmosphere, filmic grain, 35mm lens style, rich contrast and deep shadows. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Cliffside Silhouettes, Sedan"

queue_job 9 \
  "Medium photorealistic romantic shot of a couple reclining side-by-side on the hood of a retro convertible, parked at a scenic hill viewpoint at night. The couple is laughing, one pointing up at a shooting star across a clear starry sky. Below the hill, soft bokeh lights of a sprawling city outline the landscape. Gentle rim lighting from the distant city lights highlights their faces and clothes. Natural skin tones, warm intimacy, rich dark tones, highly detailed photorealism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Reclining on Convertible Hood"

queue_job 10 \
  "Photorealistic high-angle shot looking over the roof of a parked station wagon towards a breathtaking nocturnal vista. One person is seated comfortably on the hood with their knees pulled up, looking at the starry sky, while the other is visible inside through the front windshield, sitting in the driver seat looking up through the sunroof. Distant city lights shimmer across a foggy valley, creating a glowing horizon line. Soft mist, moody indigo lighting, nostalgic cinematic look, highly realistic textures. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Sunroof and Hood, Foggy Valley"


# --- ChatGPT ---
queue_job 11 \
  "A romantic photorealistic night scene on a grassy hill overlooking a vast glowing metropolis, a stylish young couple sitting together on the hood of a parked luxury car, their shoulders touching as they quietly gaze at a brilliant star-filled sky. The city spreads across the distant valley with thousands of warm lights, subtle atmospheric haze between the hill and skyline, soft moonlight outlining their silhouettes and the contours of the car, intimate relaxed body language, cinematic wide-angle photography from slightly behind and below, realistic skin, clothing and reflections, natural depth of field, sophisticated romantic film aesthetic, deep midnight blues contrasted with warm city lights, peaceful and contemplative mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "ChatGPT" "Shoulders Touching on Hood"

queue_job 12 \
  "A romantic photorealistic cinematic image of a couple parked on a secluded hill above a spectacular city at night. The woman sits comfortably on the car hood while the man remains inside the driver's seat with the door open, both turned toward each other and the enormous starry sky beyond the windshield. The glowing dashboard subtly illuminates the man's face while cool moonlight falls across the woman and polished bodywork. Vast city skyline below, distant skyscrapers shimmering through light mist, countless stars overhead, elegant sports coupe, natural intimate interaction, three-quarter rear camera angle, realistic night photography, subtle lens flare, soft atmospheric perspective, rich contrast between warm interior light and cool moonlight, romantic but understated mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "ChatGPT" "Driver's Seat and Hood"

queue_job 13 \
  "A romantic photorealistic scene on a hilltop overlook, a couple standing together in front of their parked car, leaning lightly against its front hood while looking upward at a spectacular clear night sky filled with stars. The woman rests one hand on the hood and the man stands beside her with an arm around her waist, their silhouettes framed against the distant city lights. The entire metropolitan skyline stretches across the horizon below them, glowing softly through atmospheric haze. Elegant dark car, subtle reflections on its paint and windshield, moonlit landscape, realistic skin and clothing textures, cinematic 35mm photography, low frontal camera angle, expansive composition, gentle breeze moving the woman's hair, intimate sense of wonder and escape, sophisticated romantic movie still. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "ChatGPT" "Standing Against Hood, Arm Around Waist"

queue_job 14 \
  "A highly romantic photorealistic night photograph of a couple enjoying a secluded hilltop above a brilliant modern city. Both sit on the hood of their car facing away from the camera, their legs hanging over the front edge, leaning slightly toward each other while watching the Milky Way and scattered stars above the distant skyline. The car is positioned diagonally across the foreground, its metallic surface catching soft moonlight. Vast panoramic city view beneath the hill, warm windows forming delicate patterns in the darkness, subtle fog over the urban landscape, realistic star illumination, cinematic long-exposure atmosphere while keeping the couple naturally sharp, wide-angle composition from a low side perspective, intimate silence, dreamy yet believable photorealism, premium automotive and lifestyle photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "ChatGPT" "Backs to Camera on Hood"

queue_job 15 \
  "A romantic photorealistic cinematic scene where a couple has stopped their car on a grassy hill overlooking a huge city at night. The man sits on the hood with his back against the windshield, while the woman sits sideways in the open passenger doorway with one foot inside the car and one foot on the ground, both gazing toward the stars and distant city lights. Their positions create a natural asymmetrical composition around the vehicle, suggesting an unplanned intimate pause during a night drive. Soft headlights faintly illuminate the foreground grass, warm interior light spills from the open door, cool moonlight outlines the couple and car, enormous city panorama below, star-filled sky above, realistic atmospheric haze, subtle reflections, cinematic 50mm photography, elegant natural poses, quiet romantic melancholy, premium photorealistic film aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "ChatGPT" "Hood and Open Passenger Door"


# --- Grok fast ---
queue_job 16 \
  "Romantic photorealistic image, square composition: a young couple sitting close together on the hood of a classic car parked on a quiet hill, both gazing up at a vast starry night sky above a glowing big city skyline in the distance. Soft cool moonlight mixes with warm city lights reflecting on the car's polished surface, intimate and serene atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Grok fast" "Sitting Close on Classic Car Hood"

queue_job 17 \
  "Romantic photorealistic image, square composition: a couple on a hillside overlooking a sprawling city at night — one person sitting inside the open driver's side of a sleek modern car, the other leaning on the hood beside them, both looking up at the star-filled sky. Gentle side lighting from the distant city glow, soft bokeh of lights below, quiet and tender mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Grok fast" "Driver's Side and Hood Lean"

queue_job 18 \
  "Romantic photorealistic image, square composition: a couple standing close in front of their car on a hilltop at night, arms around each other, watching the brilliant night sky stretch above a glittering metropolis far below. Low-angle view emphasizing the vast sky and city lights, cool blue moonlight with warm orange city reflections on the car, deeply intimate atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Grok fast" "Standing Embrace in Front of Car"

queue_job 19 \
  "Romantic photorealistic image, square composition: a couple both reclining on the wide hood of a vintage car parked on a grassy hill, heads tilted upward toward a clear starry night sky, the sprawling illuminated city visible in the valley beneath them. Soft overhead moonlight, subtle lens flare from distant lights, calm and dreamy romantic mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Grok fast" "Both Reclining on Vintage Hood"

queue_job 20 \
  "Romantic photorealistic image, square composition: side-angle view of a couple on a hill overlooking a big city at night — one person sitting on the passenger-side hood of the car, the other leaning halfway out of the open door, both quietly watching the starry sky. Cool nocturnal tones mixed with warm city glow reflecting on the vehicle, intimate and contemplative atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Grok fast" "Passenger Hood and Open Door"


# --- Qwen 3.8 Omni Flash Thinking ---
queue_job 21 \
  "Photorealistic romantic night scene on a quiet hill overlooking a glowing big city skyline. A young couple sits closely together on the hood of a sleek dark car, wrapped in a soft blanket, gazing up at a star-filled sky. Warm headlights illuminate their faces gently, city lights sparkle in the distance, cinematic composition, intimate mood, realistic skin tones, shallow depth of field, elegant car reflections. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Blanket on Hood, Headlights Glow"

queue_job 22 \
  "Cinematic photorealistic image of a couple on a hill at night with a vast illuminated city below. One person sits inside the parked car through the open driver-side window, while the other leans on the hood, their hands almost touching as they look toward the stars. Soft moonlight, warm interior car glow, romantic atmosphere, realistic textures, moody blue and amber color palette, wide-angle composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Window and Hood, Hands Almost Touching"

queue_job 23 \
  "Romantic photorealistic scene with a couple standing in front of a classic car parked on a hill, backs gently turned to the camera as they watch the night sky and distant city lights. The car's polished surface reflects the stars and urban glow, soft breeze in their clothes, tender embrace, cinematic framing, realistic lighting, peaceful intimate mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Standing in Front of Classic Car"

queue_job 24 \
  "Aerial cinematic view of a couple lying side by side on the hood of a modern car parked on a hill, looking up at a brilliant starry sky above a glittering metropolis. Long exposure night photography feeling, soft city bokeh, realistic car details, romantic and dreamlike atmosphere, gentle warm light from the headlights, high-angle composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Aerial View, Lying on Hood"

queue_job 25 \
  "Photorealistic romantic night portrait of a couple positioned in front of and around a vintage car on a hill overlooking a huge city skyline. One sits on the hood with knees drawn up, while the other stands close beside the car, both gazing at the stars. Moody twilight tones, soft rim lighting, realistic fabric and skin texture, intimate storytelling, cinematic wide composition with deep atmospheric perspective. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Hood and Standing Beside Car"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "A romantic, photorealistic square composition, wide rear shot: a classic car parked on a grassy hilltop overlook, a young couple sitting close together on its hood wrapped in one plaid blanket, her head resting on his shoulder as they gaze at the glittering megacity sprawled in the valley below and the star-filled sky above. Warm bokeh of a million city lights, faint amber haze rising from the streets, soft moonlight rim-lighting their hair, 85mm lens, shallow depth of field, subtle film grain, tender nostalgic mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Blanket on Hood, Head on Shoulder"

queue_job 27 \
  "A romantic, photorealistic square composition, side-profile medium shot: a woman lies back on the hood of a vintage sedan gazing up at the stars, while the man sits in the driver's seat with the door open, leaning his head out — watching her instead of the sky. Hilltop overlook with the vast city glowing in the valley far below. Cool blue moonlight on the car's curves, warm glow of the interior dome light spilling onto the gravel, shallow depth of field, delicate film grain, hushed intimate atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Reclining Hood and Open Driver Door"

queue_job 28 \
  "A romantic, photorealistic square composition, front view: a couple slow-dancing in the pool of warm headlight beams cast by their parked car on a hilltop overlook, her dress and his open jacket stirred by the night breeze, the dazzling city skyline spread across the valley below and stars scattered overhead. Cinematic rim-light halo around their silhouettes, soft lens flare from the headlights, gentle motion in the fabric, 35mm lens, dreamy romantic mood, fine analog grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Slow Dancing in Headlight Beams"

queue_job 29 \
  "A romantic, photorealistic square composition, low angle from ground level beside the car: a couple lying flat side by side on the wide hood of a retro car, her finger pointing at a shooting star streaking across the deep night sky above the endless glittering city in the valley below. Faint Milky Way band, dreamy pastel-night tones, soft mist drifting over the distant skyscrapers, long-exposure star feel, skin rendered naturally, serene sense of wonder, subtle film texture. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Lying Flat, Pointing at Shooting Star"

queue_job 30 \
  "A romantic, photorealistic square composition, rear view from behind: a couple sitting on the ground in front of their car, backs resting against the front bumper, her leaning into his shoulder, both silently watching the sea of city lights far below the hill and the quiet starry sky. The car's dark silhouette frames them at the edges of the shot, dew glinting on the grass, cool teal night tones against the warm sodium-vapor glow of the city, wide-angle lens, deep calm and togetherness, cinematic photorealism with gentle grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Seated on Ground Against Bumper"


# --- DeepSeek Think Search ---
queue_job 31 \
  "Romantic photorealistic image, close-up shot of a couple lying side by side on the hood of a vintage car, gazing up at a vast, star-filled night sky. The camera is positioned at a low angle from the front of the car, capturing their silhouettes against the deep blue and purple hues of the cosmos. The sprawling city lights twinkle far below the hill, creating a soft, warm bokeh in the background. The mood is intimate and dreamy. Fashion magazine advertising quality professional photo, cinematic lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Lying on Hood, Low-Angle Silhouettes"

queue_job 32 \
  "Romantic photorealistic image, cinematic wide shot from behind a classic car parked on a grassy hill. A woman sits on the hood, leaning back on her hands, while a man leans out from the open passenger window, both looking up at a brilliant, shooting-star-filled night sky. The composition uses the car's shape as a leading line, drawing the eye toward the couple and the city skyline glittering in the distance below. The scene is bathed in cool moonlight and warm city glow. Fashion magazine advertising quality professional photo, anamorphic lens flare. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Hood and Passenger Window Lean"

queue_job 33 \
  "Romantic photorealistic image, dynamic low-angle shot of a couple standing in front of a sleek, modern car, embracing each other while looking up at the Milky Way stretching across the night sky. The camera is positioned near the ground, emphasizing the vastness of the sky and the city panorama below the hill. The car's headlights cast a soft, warm glow on the couple, contrasting with the cool, deep blues of the night. The mood is epic and romantic. Fashion magazine advertising quality professional photo, wide-angle lens. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Standing Embrace, Milky Way"

queue_job 34 \
  "Romantic photorealistic image, playful and candid shot of a couple sitting on the hood of a retro car, the woman pointing excitedly at a constellation while the man watches her with a smile. The camera angle is slightly tilted (Dutch angle), adding a sense of joy and spontaneity. The background features a breathtaking view of a sprawling metropolis at night, its lights reflecting softly on the car's polished surface. The mood is cheerful and loving. Fashion magazine advertising quality professional photo, warm and inviting color grade. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Pointing at a Constellation"

queue_job 35 \
  "Romantic photorealistic image, over-the-shoulder shot from inside a car, looking out through the windshield. A man sits in the driver's seat, and a woman sits on the hood just beyond the glass, both their heads tilted up toward a spectacular, glowing nebula in the night sky. The composition frames the couple and the sky through the windshield, with the city lights a distant, glittering tapestry below. The mood is quiet, contemplative, and deeply romantic. Fashion magazine advertising quality professional photo, shallow depth of field focusing on the couple and the sky. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Through the Windshield, Nebula Above"


# --- MiniMax M3 ---
queue_job 36 \
  "Photorealistic romantic image, square composition. A wide cinematic shot from slightly above and behind a sleek dark grey sedan parked on a hilltop overlooking a vast glittering city skyline at night. A young couple lies side by side on the car's hood, their heads close together near the windshield, gazing up at a sky full of stars. She is in a soft cream knit sweater, hair loose and spilling across the warm metal of the hood; he is in a black hoodie, one arm folded behind his head as a pillow, the other draped gently across her shoulder. The car's hood reflects the faint starry sky like dark water. Below the hill, the city unfolds in layers of warm amber, cool blue, and white neon — buildings rising like distant mountains of light. A thin crescent moon hangs low. The mood is hushed, intimate, dreamlike. Soft ambient light from the city below softly illuminates their faces from beneath. Long exposure star trails faint in the sky above. Subtle lens flare from a distant skyscraper. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Side by Side on the Hood, Sedan"

queue_job 37 \
  "Photorealistic romantic image, square composition. A medium shot of a vintage cherry-red coupe parked on a hilltop cliff edge, the panoramic city skyline glowing far below. The young woman sits sideways on the hood, legs dangling toward the camera, her profile lit by the city glow, head tilted down with a gentle smile toward the open driver-side door. The young man sits in the driver's seat, leaning out through the doorframe, one elbow resting on the window edge, looking up at her with quiet adoration, his face half in soft shadow. They are mid-conversation, close, almost touching foreheads. She wears a delicate blush slip dress; he wears a loose white linen shirt, sleeves rolled. The car is parked so the city lights form a perfect horizontal band across the middle of the frame behind them. Warm tungsten glow from the dashboard spills out the open door onto the asphalt. The night sky above is inky and full of stars. The mood is tender, candid, cinematic-romantic. Soft bokeh from the distant city towers. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Sideways on Hood, Driver Door Open"

queue_job 38 \
  "Photorealistic romantic image, square composition. A low-angle shot from ground level looking up at a couple sitting on the asphalt directly in front of a matte black SUV parked on a hilltop, the car's headlights turned off, the city skyline sprawling behind and below them like an ocean of light. The woman sits cross-legged, leaning her head against the man's shoulder; he sits with his legs stretched out and crossed at the ankles, his chin resting on top of her head, both looking up at the starry sky in peaceful silence. She is in an oversized denim jacket over a white tee; he is in a worn leather jacket. The car's front grille and license plate frame them like a monument. The headlights are off, but the city glow below the hill paints the underside of their faces and the car's bumper in cool cyan and warm gold. The sky above is deep navy, scattered with thousands of pinpoint stars and the soft band of the Milky Way. Romantic, quiet, awe-struck atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Seated on Asphalt, SUV Grille Frame"

queue_job 39 \
  "Photorealistic romantic image, square composition. A wide full-body shot of a couple standing close together in front of a classic midnight-blue muscle car parked at the very edge of a hilltop overlook, the sprawling city skyline glittering far below. They stand in soft three-quarter profile, his arms wrapped around her from behind, her hands resting on his, both faces tilted up toward the star-filled sky. She is in a long satin emerald-green dress that catches the city light; he is in a dark wool overcoat, collar turned up. Their breath is faintly visible in the cool night air. The car's chrome grille and round headlights gleam faintly on either side of them. The city below is rendered in warm sodium-orange and cool electric-blue points of light stretching to the horizon. Above, the sky is vast and deeply black with thousands of stars and a faint nebula glow. The mood is cinematic-romantic, vintage-modern, intimate against scale. Gentle rim light from the city silhouettes their forms. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Standing Embrace, Muscle Car Edge"

queue_job 40 \
  "Photorealistic romantic image, square composition. A close-medium shot of a couple sitting close together on the hood of a pearl-white convertible sports car parked on a hilltop, the soft-top down, the city skyline glowing in soft bokeh far behind and below. They sit facing slightly toward each other, foreheads almost touching, eyes closed, sharing a quiet private moment under the stars. She wears a chunky knit oatmeal-colored cardigan, her hands cupping a takeaway coffee cup between them; he wears a navy cable-knit sweater, his hand resting gently over hers on the cup. Wisps of steam rise from the coffee into the cold night air. The car's white hood and windshield frame them softly. The city below is a soft blur of warm honey light, out of focus, while the sky above is sharp with stars and a low golden moon. The mood is cozy, romantic, intimate — like a stolen moment between two people in love. Warm soft key light from an unseen streetlight on the hill behind the camera. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"4\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Foreheads Almost Touching, Coffee on Hood"


echo "✅ All 40 jobs queued in scheduleri"
