#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 3 - cinematic melancholy style, two
#        prisoners playing tic-tac-toe (noughts and crosses) drawn using
#        combs or wooden sticks, the game frame formed by the shadow of jail
#        bars falling through a small window, bottom-center "3" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+3+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "Cinematic melancholy, two aging prisoners hunched over a low stone bench in a dim cell, drawing tic-tac-toe with splintered wooden combs as X and O markers, the game grid itself formed by the diagonal shadow of jail bars falling through a small barred window onto worn concrete, muted grey-blue palette, grainy 35mm film texture, quiet desperation in their tired faces. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Diagonal Bar Shadows"

queue_job 2 \
  "Wide cinematic shot, two prisoners seated cross-legged on a stone floor inside a cramped cell, hunched over a game scratched into dust using broken teeth of a comb, the tic-tac-toe frame cast entirely by barred-window shadow stretching long across the floor between them, sepia-toned melancholy lighting, single shaft of harsh daylight, film-noir composition, weathered fabric and stubbled faces. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Wide Establishing Shot"

queue_job 3 \
  "Overhead cinematic angle looking straight down at two pairs of scarred hands and a wooden comb resting mid-move, the tic-tac-toe grid drawn faintly in chalk dust where barred-window shadow lines intersect on the stone floor, desaturated melancholic tones, soft film grain, isolated composition emphasizing silence and confinement, faces cropped out of frame entirely. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Overhead Top-Down"

queue_job 4 \
  "Cinematic melancholy shot from outside the cell looking in through iron bars, two prisoners rendered as soft silhouettes bent over their game, the barred window's own shadow projected onto the rear wall forming the tic-tac-toe grid behind them, cold blue moonlight against warm amber interior glow, atmospheric haze, contemplative stillness, reminiscent of a 1970s prison drama still. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Silhouettes Through the Window"

queue_job 5 \
  "Extreme close-up, shallow depth of field, weathered fingers placing a splintered comb-tooth marker onto a tic-tac-toe grid etched in dust, the faint crosshatch of window-bar shadow just visible crossing the lines, two blurred prisoner silhouettes fading into the melancholic background, muted cinematic color grade, tactile grain, intimate and quietly tragic mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Extreme Close-Up on the Board"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "Two gaunt prisoners in a small, shadowed cell, using a long shadow from a high window as the grid lines, scratching an X and O into the concrete floor with worn wooden sticks. Only one face is visible, looking at the floor in resignation. Low light, film grain. Frame created by a high, slatted cell window shadow. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Grid Scratched in Concrete"

queue_job 7 \
  "Close-up on the dirty hands of two prisoners, one placing a third stick, forming an X on a rough, improvised grid scratched into a brick wall. A small, frosted higher window provides cool, distant light. Frame created by the shadow of a high window grill. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Hands Marking the Grid"

queue_job 8 \
  "A long shot looking through a narrow corridor toward a dark cell. Two silhouetted figures huddle on the floor. A sharp geometric shadow from the window casts the grid across their game on the stone. Frame created by a barred cell window shadow. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Long Shot Through Corridor"

queue_job 9 \
  "Close-up of a broken plastic comb scratching an O onto a metal surface, already marked with an unfinished game. One prisoner's hands are visible, and the face of the other is reflected in a wet puddle. Frame created by a high window with wire mesh shadow. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Comb Scratching on Metal"

queue_job 10 \
  "Medium shot of two prisoners on a dusty bench during an indoor exercise time, scratching the game into the wood with combs. A larger window with heavy bars creates a detailed grid across the entire bench. Frame created by a large window with heavy metal bars shadow. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Bench Game, Heavy Bars"


# --- ChatGPT ---
queue_job 11 \
  "Cinematic melancholy scene inside a dim, weathered prison cell, two prisoners sitting on opposite sides of a small patch of concrete floor, quietly playing tic-tac-toe. The game board is not drawn normally: the nine-square frame is created entirely by the long rectangular shadows cast by the iron bars of a small high prison window, forming a naturally perfect grid across the dusty floor. One prisoner carefully draws an X using several thin wooden sticks, while the other places a small O using a broken wooden comb, both intensely focused on the game. Cold gray walls, shafts of pale afternoon light, floating dust particles, deep surrounding darkness, restrained expressions, loneliness and quiet companionship, cinematic composition, subtle film grain, desaturated colors, dramatic chiaroscuro, poetic visual storytelling. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "ChatGPT" "The Game of Shadows"

queue_job 12 \
  "A highly cinematic melancholy prison interior with two prisoners sitting cross-legged on the floor opposite one another, absorbed in a slow game of noughts and crosses. A tiny barred window high on the wall becomes the source of the entire composition: its iron bars project sharp rectangular shadows onto the concrete floor, naturally creating the tic-tac-toe grid between the men. One prisoner uses a broken wooden comb to arrange an O inside one square, while the other holds a thin wooden stick ready to make an X. Their worn hands and improvised game pieces become the visual focus, while their faces remain partially hidden in shadow. Pale winter sunlight, dusty air, cracked plaster, muted gray-brown palette, strong negative space, deep cinematic shadows, melancholy atmosphere, intimate human moment, arthouse film aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "ChatGPT" "Nine Squares of Light"

queue_job 13 \
  "A poetic cinematic poster-style scene inside an austere prison cell, two prisoners quietly playing tic-tac-toe on the bare floor using nothing but improvised wooden objects. The unusual game board is formed by the shadows of the prison window itself: vertical and horizontal iron bars cast a precise nine-cell grid of light and darkness across the concrete floor. One prisoner carefully scratches an X into the dusty surface with a thin wooden stick, while the other uses the teeth of a broken comb to position a crude O. Both men lean toward the board with serious concentration, their friendship and boredom suggested through their quiet shared ritual. Single small barred window, late-afternoon sunlight, long shadows, dusty atmosphere, worn clothing, rough concrete, desaturated cinematic palette, strong chiaroscuro, subtle film grain, melancholic realism, carefully composed negative space. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "ChatGPT" "Prison Chess Without a Board"

queue_job 14 \
  "A cinematic melancholy composition inside an old prison cell where two prisoners play noughts and crosses on the floor. The camera looks diagonally across the room toward a tiny barred window, whose sunlight projects the exact shape of its iron framework onto the floor, transforming the prison shadow into a natural tic-tac-toe board. One prisoner reaches into the illuminated grid with a small wooden stick, drawing an X, while the other holds a worn wooden comb and studies the remaining spaces. Their bodies sit mostly in darkness while the game board glows in the narrow beam of sunlight, creating a powerful contrast between confinement and a tiny moment of play. Old cracked walls, rough concrete, worn prison clothes, suspended dust, quiet expressions, muted earth tones, atmospheric haze, dramatic volumetric light, slow contemplative mood, sophisticated cinematic photography, arthouse poster aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "ChatGPT" "A Game in the Sunlight"

queue_job 15 \
  "A deeply melancholic cinematic poster depicting two prisoners facing each other across a prison-cell floor, playing an improvised game of tic-tac-toe. The small barred window behind them casts a beautiful geometric shadow onto the floor, and the intersecting shadows of the bars naturally form the nine-square game grid. One prisoner is making his final move with a thin wooden stick, while the other watches silently, holding several pieces of a broken wooden comb that have been used to create the noughts and crosses. The board exists only because of the sunlight and the prison bars, turning the architecture of confinement into a temporary game. Sparse cell, chipped concrete, worn clothing, pale golden light surrounded by deep blue-gray darkness, long dramatic shadows, floating dust, subtle facial emotion, loneliness mixed with companionship, cinematic depth, poetic symbolism, restrained high-end film still aesthetic, desaturated color grading. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "ChatGPT" "The Last Move"


# --- Grok fast ---
queue_job 16 \
  "Cinematic melancholy style, square composition: two weary prisoners sitting on a cold concrete floor inside a dim jail cell, quietly playing tic-tac-toe. They draw the X's and O's using broken wooden sticks and a worn comb, while the perfect grid of the game is formed by the sharp shadow of the barred window cast across the floor by a single shaft of pale light. Soft volumetric light, muted desaturated tones, heavy atmosphere of quiet resignation. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Grok fast" "Barred Window Shaft of Light"

queue_job 17 \
  "Cinematic melancholy style, square composition: two silent prisoners crouched near a small high window in a bleak prison cell, engrossed in a game of noughts and crosses. One man carefully places marks with a wooden stick while the other waits, the entire game board created by the geometric shadow of the jail bars falling across the dusty floor. Low-key lighting, cool blue-gray palette, soft film grain, deep sense of isolation and fleeting human connection. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Grok fast" "Crouched by the High Window"

queue_job 18 \
  "Cinematic melancholy style, square composition: two middle-aged prisoners sitting side by side on a thin mattress in a narrow cell, playing tic-tac-toe with quiet concentration. They use a comb and small wooden splinters to mark the board, whose lines are perfectly formed by the elongated shadow of the barred window stretching across the floor in the late afternoon light. Muted earthy tones, gentle rim light, intimate yet desolate atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Grok fast" "Mattress-Side Afternoon Game"

queue_job 19 \
  "Cinematic melancholy style, square composition: high-angle view of two prisoners on the cold stone floor of an old jail cell, absorbed in a game of noughts and crosses. One draws with a wooden stick, the other with a metal comb, the game grid created entirely by the sharp, geometric shadow of the small barred window. Soft directional light cutting through dust, desaturated cinematic color grade, profound sense of stillness and quiet endurance. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Grok fast" "High-Angle Stone Floor View"

queue_job 20 \
  "Cinematic melancholy style, square composition: two prisoners leaning against the damp wall of a dimly lit cell, playing tic-tac-toe on the floor using wooden sticks and a broken comb. The bars of the small window cast a perfect crosshatched shadow that becomes the game board, illuminated by a single cold beam of morning light. Moody low-key lighting, subtle film grain, restrained emotional tension and quiet melancholy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Grok fast" "Damp Wall, Cold Beam of Light"


# --- Qwen 3.8 Omni Flash Thinking ---
queue_job 21 \
  "Cinematic melancholy scene, two weary prisoners sitting on a cold concrete floor in a dim cell, quietly playing tic-tac-toe. The game board is formed by the sharp shadow of prison bars falling from a small high window, creating a natural noughts-and-crosses grid on the dusty ground. They use worn wooden sticks and a broken comb to mark their moves, scratching faint lines into the dirt. Soft blue-gray light, deep shadows, emotional stillness, realistic film grain, shallow depth of field, poetic prison atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Dust Grid, Blue-Gray Light"

queue_job 22 \
  "Wide cinematic shot inside a bleak prison cell, two prisoners facing each other on the floor, absorbed in a silent game of tic-tac-toe. The small barred window casts long prison-bar shadows across the concrete, forming the perfect square frame for the game. One prisoner holds a wooden stick, the other drags a comb through dust to draw a cross. Melancholic mood, muted colors, soft shafts of light, floating dust particles, realistic textures, quiet desperation and fragile human connection. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Wide Shot, Facing Each Other"

queue_job 23 \
  "Over-the-shoulder cinematic view from behind one prisoner, showing another prisoner's tired hands placing wooden sticks onto a tic-tac-toe game drawn in the dust. The board's frame is created entirely by the shadow of jail bars streaming through a tiny window, falling across the floor like a prison within a prison. A rusty comb lies nearby, used to scratch noughts and crosses into the concrete. Moody low-key lighting, cold blue tones, intimate composition, emotional restraint, photorealistic detail, melancholy film still aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Over-the-Shoulder Hands"

queue_job 24 \
  "Side-profile cinematic composition, two prisoners seated opposite each other in a sparse cell, playing tic-tac-toe with simple wooden sticks and a comb. The small window above them casts striped prison-bar shadows onto the floor, forming the game's grid without any drawn lines. Their expressions are calm but sorrowful, lost in a quiet moment of distraction. Soft rim light, dusty air, desaturated palette, deep shadows, realistic skin texture, melancholic poetic atmosphere, like a still from an art-house prison drama. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Side-Profile, Striped Shadows"

queue_job 25 \
  "Close-up cinematic detail shot, focusing on two prisoners' hands and the floor of a dim cell where a tic-tac-toe game is being played. Wooden sticks serve as pieces, while a worn comb scratches faint noughts and crosses into the dust. The game frame is created by the dramatic shadow of prison bars falling from a small window, stretching across the concrete in perfect lines. Moody chiaroscuro lighting, cold blue and gray tones, subtle film grain, emotional intimacy, melancholy realism, powerful storytelling through small details. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Close-Up on Hands and Comb"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "A cinematic, melancholic square composition, high three-quarter angle looking down: inside a dim stone cell, a narrow shaft of morning light pierces a small barred window high on the wall, casting the shadow of the iron bars onto the floor as two vertical and two horizontal lines intersecting in a crisp, sharp grid — a perfect tic-tac-toe frame. Two prisoners in faded gray uniforms crouch on opposite sides of the glowing grid; one solemnly places an X made of two crossed splintered wooden sticks into a square, while an O outlined with curved shards of a broken comb already sits nearby. Floating dust motes in the beam, cold blue shadows against one warm amber shaft, desaturated palette, fine film grain, quiet contemplative mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Chiaroscuro High Angle, Morning Shaft of Light"

queue_job 27 \
  "A cinematic, melancholic square composition, floor-level low angle: inside a dim stone cell, a narrow shaft of morning light pierces a small barred window high on the wall, casting the shadow of the iron bars onto the floor as two vertical and two horizontal lines intersecting in a crisp, sharp grid — a perfect tic-tac-toe frame. Two prisoners in faded gray uniforms crouch on opposite sides of the glowing grid; one solemnly places an X made of two crossed splintered wooden sticks into a square, while an O outlined with curved shards of a broken comb already sits nearby. Floating dust motes in the beam, cold blue shadows against one warm amber shaft, desaturated palette, fine film grain, weary rivalry between the two men. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Floor-Level Low Angle, Weary Rivalry"

queue_job 28 \
  "A cinematic, melancholic square composition, static wide shot of an entire dim cell: high above, a small barred window releases one long diagonal beam of dusty light; where it lands on the flagstone floor, the shadow of the bars forms a sharp grid — two vertical and two horizontal lines, a tic-tac-toe frame. Two prisoners sit small in the frame on opposite sides of the grid, one arranging curved pieces of a broken comb into an O, the other holding two crossed wooden sticks ready for the next X. Vast negative space of cold stone walls, faint tally marks scratched near the window, sepia-dust palette with deep blacks, brutalist silence, profound loneliness and quiet companionship, heavy film grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Wide Static Cell, Loneliness in Vast Space"

queue_job 29 \
  "A cinematic, melancholic square composition, intimate close-up with shallow depth of field: the weathered, calloused hands of a prisoner gently place a curved shard of broken black comb, completing an O inside a shadow grid cast by the iron bars of a small window above — two vertical and two horizontal lines sharp on the rough concrete. The crossed wooden sticks of an X rest in the neighboring square; behind, the second prisoner's face floats out of focus, watching in half-light. Gritty texture of stone and skin, desaturated tones with warm highlights, soft volumetric haze in the light shaft, somber tender mood, analog film grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Intimate Close-Up, Hands and the Broken Comb"

queue_job 30 \
  "A cinematic, melancholic square composition, eye-level medium two-shot at dusk: the last amber rays of evening fall through a small barred window, stretching the shadow of the bars into a fading tic-tac-toe grid on the floor — two vertical and two horizontal lines dissolving into blue darkness. One prisoner, gray-stubbled and hollow-eyed, places the final X of two crossed wooden sticks; across the grid, the other watches with a faint bittersweet smile, curved fragments of a broken comb already forming the O's. Warm dying light against encroaching cold shadow, dust suspended in the beam, muted amber-and-slate palette, tender hopeless warmth, heavy cinematic grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Dusk Two-Shot, The Last Move"


# --- DeepSeek Think Search ---
queue_job 31 \
  "Cinematic melancholy style. Top-down overhead shot inside an old prison cell. Two prisoners sit cross-legged on a cold concrete floor, playing tic-tac-toe. The 3x3 frame is formed only by the shadow of jail bars cast from a small high window. One prisoner uses a comb, the other a wooden stick, to scratch noughts and crosses into the dust. Sparse cell, muted blue-grey palette, dust motes in a narrow beam of light, quiet despair, 35mm film grain, shallow depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Top-Down Overhead Shot"

queue_job 32 \
  "Cinematic melancholy style. Wide side-profile shot, late afternoon amber light entering through a small barred window. Two prisoners kneel on opposite sides of a tic-tac-toe grid created by the shadow of jail bars falling across the stone floor. One draws an O with a comb, the other traces an X with a wooden stick. Long shadows, peeling walls, chipped paint, silence, faded warm and cold contrast, anamorphic lens flare, somber atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Wide Side-Profile, Amber Light"

queue_job 33 \
  "Cinematic melancholy style. Intimate close-up on weathered hands and the shadow-made tic-tac-toe frame. Two prisoners, faces soft in the background, play noughts and crosses using a comb and wooden sticks to mark the dusty floor. The grid is cast by the shadow of jail bars from a tiny window. Rain streaks on the glass, grey daylight, damp air, muted desaturated tones, slow-cinema mood, macro detail, melancholic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Close-Up on Hands and Grid"

queue_job 34 \
  "Cinematic melancholy style. Low-angle shot from floor level. A small window high in a dark cell projects the shadow of its jail bars onto the floor, forming a perfect tic-tac-toe frame. Two prisoners sit in silhouette, one using a comb, the other a wooden stick, drawing noughts and crosses. Harsh single-source light, deep shadows, dust, cramped composition, hopelessness, high contrast, cinematic still. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Low-Angle Silhouettes"

queue_job 35 \
  "Cinematic melancholy style. Symmetrical medium shot, overcast diffused light through a small barred window. Two prisoners face each other, playing tic-tac-toe on the floor. The game frame is created by the shadow of jail bars; they draw noughts and crosses with a comb and wooden sticks. Cold concrete, worn uniforms, almost no color except pale skin and dull grey, quiet resignation, slow shutter, soft-focus background. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Symmetrical Medium Shot"


# --- MiniMax M3 ---
queue_job 36 \
  "Cinematic melancholy style, square composition. A low-angle intimate shot inside a dim concrete prison cell. Two male prisoners in faded grey uniforms sit cross-legged facing each other on a worn stone floor. Between them, a tic-tac-toe grid is scratched into the dust, perfectly illuminated by a square of soft daylight falling through a small barred window high on the back wall — the shadow of the iron bars forming the lines of the game itself. One prisoner uses the broken handle of a wooden comb to slowly carve an X into the stone; the other holds two sharpened wooden toothpicks crossed in his fingers, about to place his O. Their faces are half-lit, half in shadow, expressions exhausted but quietly absorbed in the small ritual. Muted desaturated palette — slate grey walls, olive uniforms, dusty cream sunlight. Subtle dust motes drift through the single shaft of light. Film-grain, shallow depth of field, the background cell dissolving into soft darkness. The mood is hushed, resigned, tender in its sadness. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Floor Between Them"

queue_job 37 \
  "Cinematic melancholy style, square composition. A wide symmetrical shot inside a long cold prison corridor at dusk, looking down the length of the hall toward a small barred window at the far end. Two prisoners sit on the floor in the foreground, their backs to the camera, rendered as soft silhouettes. Between them, the bars of the distant window cast a sharp crosshatch shadow pattern across the stone floor — perfectly forming a tic-tac-toe grid that connects them visually to the light source. One silhouette leans forward to place a small wooden matchstick as his mark; the other sits back, arms resting on his knees, watching. The corridor walls are textured peeling paint in faded institutional green. A single shaft of amber sunset light cuts through the window bars, painting thin orange lines across the floor and the men's shoulders. Cool teal shadows everywhere else. The composition is stark, lonely, painterly — like a Hopper painting filtered through a prison drama. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Silhouette Duel"

queue_job 38 \
  "Cinematic melancholy style, square composition. A top-down bird's-eye view of two prisoners playing tic-tac-toe on the wooden floor of a cell. The frame is dominated by the grid of a tic-tac-toe board drawn directly onto the aged planks, the lines formed by the shadow of iron bars projected through a small high window — the shadow falls diagonally across the floor, creating a soft crosshatch pattern. One prisoner, in a faded blue cotton uniform, is reaching into the frame from the left edge, his weathered hand placing a small black comb as his X mark. The other prisoner, in a grey uniform, reaches in from the right edge, his scarred hand setting down a tiny carved wooden cross made from a broken chair rung as his O. Only their hands and forearms are visible. Dust and wood shavings are scattered around the board. Cool washed-out daylight, high contrast between the bright squares of window light and the deep shadow of the bars. Documentary texture, restrained, melancholic stillness. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Overhead Ritual"

queue_job 39 \
  "Cinematic melancholy style, square composition. A medium shot framed through the iron bars of a prison cell door, looking inward. In the background, two prisoners sit on the floor in front of a small barred window — the window's shadow projects a perfect tic-tac-toe grid onto the dusty concrete between them. The man on the left, older, gaunt, hollow-cheeked, holds two plastic combs crossed into an X, hovering them over the board with trembling hands, his eyes distant and sorrowful. The younger man on the right sits with his back against the wall, knees drawn up, watching quietly, a small wooden stick tucked behind his ear and several more tucked into his shirt pocket like chess pieces. Pale morning light filters through the window in cold white-blue tones. The bars of the door create a vertical foreground layer that overlays the entire scene — cinematic depth, layered melancholy. Color palette of faded denim blue, cement grey, and the warm yellow-cream of aged plastic combs. The mood is contemplative, almost sacred — a tiny ritual of humanity inside a cage. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Through the Bars"

queue_job 40 \
  "Cinematic melancholy style, square composition. A tight close-up on a section of rough concrete floor, with two pairs of weathered hands entering the frame from opposite sides. The tic-tac-toe grid is formed entirely by the crisscross shadow of jail bars cast from a small window just out of frame above — the shadow lines sharp and dark against sun-bleached stone. On the left, a prisoner's rough hands carefully set down a small dark wooden comb shaped like an X. On the right, another prisoner's hands hesitate over an almost-completed row, holding a tiny wooden stick between thumb and forefinger. In the soft upper background, slightly out of focus, the two men can be seen sitting across from each other — one with shaved head and downcast eyes, the other with longer unkempt hair leaning back against the wall, exhausted but faintly smiling. Late afternoon light, warm gold turning to amber, long shadows. The image has a hand-painted quality — muted earth tones, visible film grain, the texture of stone and wood emphasized. Quiet, resigned, deeply human. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"3\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Last Game of the Day"


echo "✅ All 40 jobs queued in scheduleri"
