#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 6 - cozy cafe atmosphere, warm
#        lighting, extreme close-up macro shots of coffee, latte art, pastries
#        and process detail, no people in focus or only softly blurred,
#        bottom-center "6" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+6+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "Extreme close-up of dark espresso streaming into a white ceramic cup, the liquid catching warm amber light as it swirls and crema forms on the surface, a barista's hand softly blurred at the edge of frame holding the portafilter, background dissolved into a warm bokeh of café shelves and string lights, shallow depth of field, rich cinematic warmth, shot on 85mm macro lens. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Coffee Pour"

queue_job 2 \
  "Macro shot of steamed milk pouring into a flat white, a rosette pattern blooming across the crema in slow motion, warm golden light glancing off the milk pitcher's spout, droplets suspended mid-air, faint blurred silhouette of a barista's arm at the frame's edge, cozy café interior dissolved into soft warm bokeh behind, tight focus, glossy texture detail, intimate and inviting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Latte Art Pour"

queue_job 3 \
  "Close-up of freshly roasted coffee beans tumbling from a grinder hopper into fine grounds, warm directional light catching the oily sheen on each bean, fine dust particles drifting through a shaft of golden sunlight, wooden countertop textures softly visible below, background a warm blur of jars and pendant lamps, no visible faces, macro detail, tactile and rustic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Bean Grinding"

queue_job 4 \
  "Tight shot of a spoon stirring a cappuccino, cinnamon dust swirling atop the foam, warm steam curling upward and catching the afternoon light, condensation beading on the saucer beside it, café patrons reduced to soft warm blurs of color in the far background, cozy wood and brass tones, shallow focus, gentle and nostalgic atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Steam and Stir"

queue_job 5 \
  "Macro close-up of a flaky croissant on a rustic plate, butter melting into golden pools between the layers, warm morning light raking across the crumb texture, a wisp of steam rising from a nearby cup blurred at the frame's edge, café background dissolved into soft warm amber bokeh, no people in focus, tactile, appetizing, intimate still-life mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Pastry Detail"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "A close-up, macro photo capturing a golden, rich stream of freshly brewed espresso pouring smoothly from a stainless steel portafilter into a white ceramic cup. The background features a soft, warm bokeh of dark wood and ambient café string lights, with the barista's focused hand subtly blurred holding the cup handle. Deep amber tones, steam gently rising, moody and atmospheric, shallow depth of field, sharp detail on the liquid flow. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Espresso Pour Into Cup"

queue_job 7 \
  "An intimate extreme close-up of a barista's hands using a fine-nozzle silver kettle to pour hot water over fresh coffee grounds in a glass V60 dripper. The roasted coffee bed blooms and bubbles with rich golden foam and tiny air pockets. Soft golden hour light filters through a nearby window, illuminating fine dust motes and rising steam. Warm mahogany and dark bronze palette, cozy coffeehouse aesthetic, hyper-detailed texture on the wet coffee grounds, heavily blurred background. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Pour-Over Bloom, V60"

queue_job 8 \
  "A macro photograph focusing on the precise moment a metal milk pitcher pours velvety microfoam into a dark espresso shot, forming a delicate white tulip latte art pattern. The polished ceramic cup rests on a rustic, dark oak wooden table. Warm vintage indoor lighting, soft ambient glow, delicate steam ribbons, ultra-sharp detail on the swirling cream texture, with indistinct, warmly lit café patrons completely blurred in the soft-focus background. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Milk Pour, Tulip Latte Art"

queue_job 9 \
  "A detailed close-up shot of a freshly baked, golden-brown croissant being gently broken apart on a dark ceramic plate, revealing flaky, buttery layers and soft steam escaping from the center. A small jar of amber honey and a dusted espresso cup sit just out of focus beside it. Cozy autumn café vibe, warm tungsten lighting, rich tones of cinnamon, caramel, and dark wood, razor-sharp focus on the crumb texture, moody depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Croissant Break, Steam and Honey"

queue_job 10 \
  "A macro photo of an antique brass coffee grinder in action, capturing ground coffee drifting down into a small glass container below. Sunlight streams warmly through a rainy café window, casting a golden haze over polished copper details and loose, aromatic coffee beans scattered across a worn wooden counter. Rich warm color palette, soft bokeh, cinematic mood, hyper-detailed texture of the ground roast and metallic sheen, shallow focus with a blurred, cozy coffee shop interior behind. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Antique Grinder in Action"


# --- ChatGPT ---
queue_job 11 \
  "Warm cozy café atmosphere, professional lifestyle photography, extreme close-up of freshly brewed coffee flowing in a thin dark stream from a polished espresso machine into a small ceramic cup, only the cup, flowing coffee, and a barista's hand sharply in focus, rich crema forming on the surface, delicate reflections on stainless steel, softly glowing amber café lights, wooden counter, warm brown and caramel tones, shallow depth of field, background reduced to creamy circular bokeh with indistinct blurred figures, intimate inviting mood, highly detailed textures, natural photographic realism, cinematic warmth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "ChatGPT" "Espresso Stream Close-Up"

queue_job 12 \
  "Warm cozy café atmosphere, professional editorial photography, close-up of a freshly baked croissant resting on a handmade ceramic plate beside a small cup of cappuccino, delicate flaky layers and golden crust captured in exquisite detail, tiny crumbs scattered naturally across a dark wooden tabletop, soft morning sunlight mixing with warm pendant lighting, only the pastry and coffee sharply defined, background showing an indistinct softly blurred café interior with vague silhouettes of people, rich honey, cream, caramel, and coffee colors, shallow depth of field, tactile realistic textures, quiet luxurious mood, cinematic composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "ChatGPT" "Croissant and Cappuccino"

queue_job 13 \
  "Warm cozy café atmosphere, professional food photography, macro close-up of a barista's hand slowly dusting fine cocoa powder over the dense foam of a cappuccino, the motion of the powder clearly visible as a delicate brown cloud settling into the creamy white surface, the cup occupying most of the frame, intricate foam texture and cocoa particles rendered with extreme detail, warm amber pendant lamps glowing softly in the background, dark wood and brass accents, people reduced to indistinct blurred shapes, rich earthy orange, brown, beige, and cream palette, shallow depth of field, intimate handcrafted café feeling, realistic natural light and subtle cinematic contrast. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "ChatGPT" "Cocoa Dusting on Cappuccino Foam"

queue_job 14 \
  "Warm cozy café atmosphere, professional still-life photography, close-up of a small glass cup of espresso beside a brass coffee grinder actively releasing freshly ground coffee into a dosing cup, focus on the grinding process, fine coffee particles and textured roasted beans visible in exceptional detail, delicate highlights across the metal grinder, worn wooden counter and linen cloth adding tactile character, warm tungsten and window light creating golden reflections, café interior fading into a soft creamy blur with barely recognizable silhouettes in the distance, deep coffee browns, warm gold, terracotta, and muted cream colors, cinematic depth, quiet artisanal mood, photorealistic detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "ChatGPT" "Grinder Dosing Fresh Coffee"

queue_job 15 \
  "Warm cozy café atmosphere, professional cinematic photography, intimate close-up of a ceramic mug as hot chocolate is being slowly poured into it from a small metal pitcher, glossy chocolate surface swirling into layered patterns, a few tiny marshmallows resting beside the mug on a wooden table, visible steam rising gently through the warm light, emphasis on liquid movement, ceramic texture, condensation, and wood grain, soft amber lamps and candle-like highlights in the background, any people completely absent or reduced to vague blurred silhouettes at the far edge of the frame, rich chocolate, cinnamon, honey, and cream color palette, shallow depth of field, luxurious comforting winter café mood, highly realistic photographic textures. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "ChatGPT" "Hot Chocolate Pour"


# --- Grok fast ---
queue_job 16 \
  "Close-up photo of rich dark coffee streaming from a metal pitcher into a white ceramic cup, steam rising gently, barista's hand softly blurred in the background, shallow depth of field, warm golden cafe lighting, cozy atmosphere, highly detailed liquid and ceramic textures, warm earthy tones. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Grok fast" "Coffee Pouring Into Cup"

queue_job 17 \
  "Macro close-up of a freshly baked croissant being torn open, flaky golden layers and soft interior revealed, crumbs scattered on a wooden cafe table, warm amber lighting, soft bokeh background of blurred cafe shelves, no people visible, intimate cozy mood, rich warm colors, extreme detail on pastry texture. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Grok fast" "Croissant Torn Open"

queue_job 18 \
  "Tight close-up of creamy milk being poured into espresso, creating soft white swirls and latte art forming, ceramic cup and saucer in focus, steam rising, warm golden cafe light, everything else softly blurred, no faces or clear people, cozy intimate atmosphere, warm color palette, highly detailed liquid motion. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Grok fast" "Milk Poured Into Espresso"

queue_job 19 \
  "Detailed close-up of a barista's hands (slightly out of focus) arranging a stack of warm cinnamon rolls on a wooden board, thick icing dripping slowly, soft warm cafe lighting, cozy atmosphere, shallow depth of field with blurred background, rich warm tones, focus on pastry texture and glaze. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Grok fast" "Cinnamon Rolls Arrangement"

queue_job 20 \
  "Intimate close-up of hot chocolate being topped with a cloud of whipped cream and a light dusting of cocoa powder, ceramic mug in sharp focus, steam curling upward, warm amber lighting of a cozy cafe, soft blurred background with no distinct people, rich warm colors, highly detailed foam and powder texture. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Grok fast" "Hot Chocolate With Whipped Cream"


# --- Qwen 3.8 Max ---
queue_job 21 \
  "Cafe cozy atmosphere photo, warm lighting, macro photography focus on details, close-up photo of rich dark espresso coffee flowing from a portafilter into a ceramic cup, a barista's hand gently holding the cup, slightly blurred background with warm amber bokeh and no people, shallow depth of field, high resolution, photorealistic, cinematic lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Espresso Flowing Into Cup"

queue_job 22 \
  "Cafe cozy atmosphere photo, warm lighting, macro photography focus on details, extreme close-up of velvety milk being steamed and frothed in a stainless steel pitcher, creamy microfoam swirling beautifully, warm ambient cafe lights glowing softly in the heavily blurred background, warm tones, no people visible, shallow depth of field, photorealistic, highly detailed textures. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Steamed Milk Microfoam"

queue_job 23 \
  "Cafe cozy atmosphere photo, warm lighting, macro photography focus on details, close-up of a freshly baked artisan chocolate croissant being pulled apart, flaky golden crust and melting chocolate center, steam rising, warm rustic wooden table, heavily blurred background with warm string lights and no people, cozy warm color palette, high detail, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Chocolate Croissant Pulled Apart"

queue_job 24 \
  "Cafe cozy atmosphere photo, warm lighting, macro photography focus on details, macro shot of thick golden honey being poured over a warm slice of artisan sourdough toast with melting butter, glistening textures, blurred cozy cafe background showing warm wooden shelves without any people, soft warm afternoon sunlight, shallow depth of field, ultra-detailed, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Honey Over Sourdough Toast"

queue_job 25 \
  "Cafe cozy atmosphere photo, warm lighting, macro photography focus on details, close-up of an intricate rosetta latte art being poured into a mug, the rich contrast of dark crema and white milk, blurred background showing a warm cafe interior without any people, soft warm lighting, shallow depth of field, ultra-detailed, photorealistic, macro lens photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Rosetta Latte Art Pour"


# --- GLM 5.3 Max ---
queue_job 26 \
  "Extreme close-up photograph of a rich espresso shot pouring from a chrome portafilter into a small white ceramic cup, thick golden crema swirling on the surface, glossy dark liquid, warm amber cafe lighting, gentle steam catching the light, shallow depth of field with the coffee machine softly blurred behind, cozy coffeehouse mood, warm caramel and brown color palette, photorealistic macro detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Espresso Shot and Crema"

queue_job 27 \
  "Close-up photo of latte art in progress, a barista's hand tilting a stainless steel milk pitcher, a thin white stream of milk forming a delicate rosetta on the surface of a flat white, warm golden side lighting, blurred cafe interior with soft bokeh lights in the background, shallow depth of field, cozy atmosphere, warm beige and honey tones, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Latte Art Rosetta in Progress"

queue_job 28 \
  "Macro photograph of pour-over coffee brewing, hot water spiraling from a copper gooseneck kettle held by a hand, dark coffee grounds blooming inside a glass dripper, delicate steam rising, wooden counter surface, warm morning sunlight streaming through a window, everything beyond the dripper softly out of focus, cozy cafe ambiance, warm amber and walnut tones, photorealistic detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Pour-Over Coffee Brewing"

queue_job 29 \
  "Close-up photo of a steaming ceramic cup of coffee on a rustic wooden table, cinnamon sticks and star anise beside it, delicate wisps of steam rising in golden backlight, warm lamp glow, blurred silhouettes of people chatting far in the background bokeh, shallow depth of field, cozy cafe atmosphere, warm terracotta and honey color palette, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Steaming Cup With Cinnamon and Anise"

queue_job 30 \
  "Extreme close-up photograph of a fresh croissant being gently pulled apart by a hand, flaky buttery layers revealing soft interior, golden crumbs scattered on a linen napkin and wooden board, warm soft window light, blurred cafe interior with bokeh in the background, shallow depth of field, cozy bakery mood, warm golden-brown palette, photorealistic texture detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Croissant Pulled Apart"


# --- DeepSeek Think Search ---
queue_job 31 \
  "A macro close-up photography shot of a rich, dark stream of coffee pouring from a portafilter into a small ceramic cup. The stream is perfectly in focus, capturing the golden crema and tiny bubbles. The background is a soft, blurred bokeh of a warm, cozy cafe interior with twinkling fairy lights. A barista's hand is slightly visible at the top holding the portafilter, but it's out of focus. Warm, golden hour lighting. Focus on details, steam rising. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Coffee Pouring"

queue_job 32 \
  "A detailed close-up photo of a barista's hands expertly pouring steamed milk into a cup of espresso to create a delicate rosetta latte art pattern. The focus is razor-sharp on the white milk foam contrasting with the rich brown crema. The background is a completely blurred wash of warm amber and brown tones, suggesting a cozy, inviting cafe atmosphere. Soft, warm directional lighting highlights the texture of the foam and the ceramic cup. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Latte Art Creation"

queue_job 33 \
  "An extreme close-up shot of the group head of a polished, vintage-style espresso machine. A few golden drops of espresso are falling into a shot glass below. The lighting is warm and atmospheric, reflecting off the chrome and brass details of the machine. The background is a deep, dark blur with a hint of a wooden counter and a soft, warm glow from an unseen source. Focus is on the intricate details of the machine and the falling coffee. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Espresso Machine Detail"

queue_job 34 \
  "A beautifully lit close-up of a perfectly flaky, golden-brown croissant resting on a small, rustic ceramic plate. A cup of steaming hot coffee sits just behind it, with wisps of steam curling into the warm air. The focus is on the texture of the croissant's layers and the sheen of the coffee. The background is a soft, blurry bokeh of a cozy cafe window with raindrops on the glass. Warm, inviting, and comforting mood. No people visible. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Croissant and Coffee"

queue_job 35 \
  "A close-up, low-angle shot of a simple, elegant coffee cup filled with black coffee, sitting on a richly textured, dark wooden cafe table. The main focus is on the surface of the coffee, reflecting the warm ambient light of the cafe. The background is a soft, completely blurred out scene of other tables and chairs, with warm, glowing pendant lights. The atmosphere is quiet, peaceful, and cozy. No people are in focus. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Coffee Cup on Wooden Table"


# --- MiniMax M3 ---
queue_job 36 \
  "Close-up cinematic photo of a dark roasted coffee stream pouring in a thin, glossy ribbon from a polished chrome gooseneck kettle spout into a matte ceramic cup. The stream catches the warm ambient cafe lighting, turning amber where the light hits it, with soft steam rising in ribbons. Background is a creamy, out-of-focus bokeh of a cafe counter — blurred pastries, blurred warm pendant lamps, no people in focus. Shallow depth of field, f/1.8, 85mm, golden-hour warm color grading with rich browns, cream, and deep caramel tones. Cinematic still-life framing, hyper-detailed texture on the ceramic and the coffee surface. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Pour"

queue_job 37 \
  "Extreme close-up macro photograph of fresh espresso pulling through a stainless steel portafilter, the tiny blond crema forming tiger-stripe patterns on top of a dark ristretto. Hot crema bubbles micro-popping, light catching the oily sheen. Background is a softly blurred espresso machine body in brushed steel with warm reflections of cafe wood and brass. Warm tungsten color temperature, shallow DOF, 100mm macro lens, photorealistic, focus-locked on the crema texture. Warm umber, burnt sienna, and creamy hazelnut palette. No people in frame. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Crema"

queue_job 38 \
  "Overhead top-down photo of a fresh flat white in a wide rounded ceramic cup, milk-pour art slowly blooming into a delicate rosetta pattern on the crema. The foam is glossy and white against the deep coffee brown, with espresso-tinted edges bleeding inward. Surrounding scene is a worn wooden cafe table with a folded linen napkin, scattered coffee beans, and a blurred glass sugar jar in the upper corner — no people visible. Soft warm overhead pendant light, f/2.8, 50mm, cozy pastel-amber grading, very shallow depth of field pulling focus on the rosetta. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Latte Art"

queue_job 39 \
  "Cozy still-life photograph of a hand-thrown earthenware mug filled with cappuccino, thick foam slowly settling, soft swirls of steam twisting upward into the warm cafe air. Beside the mug on a rustic wooden table sits a small glass jar of cinnamon sticks, an open vintage paperback novel with yellowed pages, and a folded knit scarf. Background is a softly blurred window with warm string-lights, brick wall, and the silhouette of one distant patron completely defocused. Late-afternoon golden light pouring in from the left, f/2.0, 50mm, Kodak Portra 400 warm tones, intimate and quiet atmosphere, hyper-detailed mug texture. No people in focus. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Steaming Mug"

queue_job 40 \
  "Macro close-up of freshly roasted coffee beans tumbling mid-pour from a small burlap sack onto a worn wooden cafe tabletop, individual beans catching highlights in a mix of warm browns and oily dark roast sheen. A few beans mid-bounce, others rolling, wood grain visible beneath, a wisp of roaster smoke drifting through frame. Background is the dim warm interior of the cafe — blurred shelves of jars, blurred chalkboard menu, blurred brass fixtures, no people. Moody warm tungsten lighting, f/2.5, 90mm, hyperrealistic detail on bean texture and oils, soft golden-brown palette with rich shadow contrast. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"6\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Beans"


echo "✅ All 40 jobs queued in scheduleri"
