#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 1 - a doubtful man standing behind
#        the glass wall of an Apple Store holding an unopened iPhone box
#        labeled "iPhone 18 pro max 2TB" / "3650$", contrasted with an
#        excited woman beside him, mood/angle/lighting vary,
#        bottom-center "1" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+1+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A square composition with a subtle Dutch tilt: a doubtful man lingers behind the glass wall of an Apple Store at dusk, warm amber streetlight glazing the glass as he cradles an unopened iPhone box. Behind him, a woman hugs him tightly from behind, cheek pressed to his shoulder, smiling with excitement he doesn't share. Small text on the label reads \"iPhone 18 pro max 2TB\", large numerals beside it read \"3650\$\". Moody editorial feel, reflections blurring their silhouettes. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Dusk Embrace, Excited Girlfriend"

queue_job 2 \
  "A square composition, framed close and slightly off-center: a hesitant man stands behind the glass wall of an Apple Store in crisp daylight, holding an unopened iPhone box with visible reluctance. A woman peers over his shoulder from behind, arms wrapped around him, grinning wide with anticipation. The label's small text reads \"iPhone 18 pro max 2TB\", large numerals beside it \"3650\$\". Clean commercial-editorial lighting, sharp glass reflections. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Daylight Close Frame, Reluctant Buyer"

queue_job 3 \
  "A square composition, wide and symmetrical: a doubtful man stands behind the glass wall of an Apple Store at night, neon storefront light streaking across the glass as he holds an unopened iPhone box like a burden. Behind him a woman hugs him close, laughing, her excitement lighting up the frame in contrast to his hesitation. Small text on the label reads \"iPhone 18 pro max 2TB\", large numerals beside it \"3650\$\". Cinematic neo-noir mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Neon Night, Neo-Noir Hug"

queue_job 4 \
  "A square composition shot from a gentle side angle: a pensive man stands behind the glass wall of an Apple Store in soft morning light, an unopened iPhone box held loosely in his hands. A woman rests her chin on his shoulder from behind, arms around his waist, smiling contentedly, unaware of his doubt. The box label's small text reads \"iPhone 18 pro max 2TB\", large numerals beside it \"3650\$\". Warm, tender editorial tone. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Morning Tenderness, Chin on Shoulder"

queue_job 5 \
  "A square composition shot from a high angle looking down: an uncertain man stands behind the glass wall of an Apple Store under flat overcast light, gripping an unopened iPhone box with visible tension. Behind him, a woman hugs him from behind mid-bounce, beaming with delight at the purchase. Small text on the label reads \"iPhone 18 pro max 2TB\", large numerals beside it \"3650\$\". Muted, slightly detached documentary tone. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "High-Angle Overcast, Mid-Bounce Hug"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "A square, moody low-key photograph through a rain-streaked window: A couple is in front of a dimly lit, closed Apple Store at night. The man, wearing a beanie, stands behind his girlfriend, holding an unopened iPhone box. He looks away with a profoundly doubtful and worried expression, his hand resting on his chin. The woman, with her hands clasped in front of her face, has her eyes closed in joyous, excited disbelief, clearly anticipating the purchase. Inside, store lights are off, but warm streetlights illuminate them and the box from behind. The label on the box is partially obscured by shadows but clearly shows \"iPhone 18 pro max 2TB\" and \"3650\$\". In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Rainy Window Remorse"

queue_job 7 \
  "A square composition photograph from inside a brightly lit Apple Store, looking out: A doubtful man in a sharp denim jacket stands close to the glass, holding the unopened iPhone box with both hands, his head tilted down in deep contemplation and conflict, looking at the box as if questioning the decision. Behind him, outside the store, a very excited woman, with her arms thrown up in a cheer and a broad grin, is laughing and looking at the back of his head, urging him from the other side of the glass. The store interior lights are cool and clean, contrasting with a warm sunset on the street. The box label, clearly readable, states \"iPhone 18 pro max 2TB\" and \"3650\$\". In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "The Storefront Standoff"

queue_job 8 \
  "A high-contrast square composition photograph with a close-up angle: The shot focuses tightly on the faces and hands of a couple. An excited woman's face, radiant with a huge smile and eyes fixed on the man, is partially in the frame, her shoulder against the man. The doubtful man is looking directly at the camera with a stressed, furrowed brow, holding the unopened iPhone box awkwardly. His hand is half-covering the label, but \"iPhone 18 pro max 2TB\" and \"3650\$\" are distinct. Strong, dramatic overhead store lighting casts deep shadows on the man's doubtful features and bright highlights on the woman's excited ones. The store background is blurred, making the couple and box pop. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "High-Contrast Hesitation"

queue_job 9 \
  "A square composition photograph with an artistic, soft-focus feel: A medium shot of a couple standing by an Apple Store window, viewed from the exterior. A joyful, excited woman with a wide-eyed expression of wonder is leaning in, her head close to an unopened iPhone box, which is held delicately by her partner. The man, standing behind her, is looking down with a thoughtful, doubtful, slightly slumped posture, his hand on the back of his neck, as if lost in thought about the cost. The store interior is brightly lit with warm lights, contrasting against a cool, blue hour outside. The box label is visible with the text \"iPhone 18 pro max 2TB\" and large \"3650\$\". In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Blue Hour Indecision"

queue_job 10 \
  "A square composition photograph with a dynamic, low-angle perspective, from the exterior sidewalk: The image looks slightly upwards at a couple standing just behind the glass wall. An extremely excited woman is jumping slightly in place, her arms outstretched and mouth open in a joyful scream, pointing at the unopened iPhone box. The man next to her, holding the box, is visibly taken aback and looking sideways at her with a look of utter, concerned doubt and bewilderment, his shoulders slightly hunched. Bright, cool store lights illuminate them from inside, creating reflections of streetlights and passing people on the glass surface. The label on the box, positioned centrally, is perfectly legible with \"iPhone 18 pro max 2TB\" and large numerals \"3650\$\". In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Sidewalk Sticker Shock"


# --- ChatGPT ---
queue_job 11 \
  "A square composition: a doubtful man stands behind the glass wall of a modern Apple Store, holding an unopened iPhone box, his expression uncertain as he stares at the purchase. Beside him, an excited woman leans toward him with a bright enthusiastic smile, eagerly pointing at the box as if encouraging him to buy it. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Cool evening storefront lighting, reflections layered across the glass, cinematic eye-level angle, subtle contrast between his hesitation and her excitement. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "ChatGPT" "Evening Storefront, Encouraging Partner"

queue_job 12 \
  "A square composition viewed through the glass facade of an Apple Store: a doubtful man holds an unopened iPhone box close to his chest, eyebrows raised and visibly questioning the expensive purchase. His female partner stands beside him, excited and delighted, looking at the box with sparkling anticipation and gently pulling his arm toward the store. On the box label, small text reads \"iPhone 18 pro max 2TB\", with large numerals \"3650\$\". Warm interior store lighting contrasts with the cooler street outside, realistic glass reflections, slightly low camera angle, intimate couple framing, humorous emotional contrast between hesitation and excitement. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "ChatGPT" "Warm Interior, Pulling His Arm"

queue_job 13 \
  "A square cinematic composition inside the entrance of a sleek Apple Store, seen through a transparent glass wall. A doubtful man stands frozen with an unopened iPhone box in both hands, staring at its price with a worried expression, while his excited female partner stands next to him with an enormous delighted smile, gesturing enthusiastically toward the phone box. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Dramatic diagonal storefront lighting, bright reflections on the glass, shallow depth of field, slightly tilted three-quarter camera angle, playful visual storytelling emphasizing the couple's completely opposite reactions. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "ChatGPT" "Diagonal Lighting, Enormous Delighted Smile"

queue_job 14 \
  "A square composition of a couple standing behind the glass wall of a brightly illuminated Apple Store at night. The man cautiously holds an unopened iPhone box, looking doubtful and calculating the cost, his body slightly pulled backward as if reconsidering the purchase. His female partner stands close beside him, visibly excited, smiling warmly and holding his arm while eagerly looking at the box. On the box label, small text reads \"iPhone 18 pro max 2TB\", with large numerals \"3650\$\". Neon-like reflections from the storefront and surrounding city lights create layered highlights across the glass, moody blue-and-white illumination, cinematic three-quarter angle, realistic urban atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "ChatGPT" "Night Neon, Holding His Arm"

queue_job 15 \
  "A square editorial-style scene through the glass of an Apple Store: a doubtful man stands holding an unopened iPhone box, his face serious and conflicted as he looks down at the price, while his female partner stands shoulder-to-shoulder with him, visibly thrilled, smiling and pointing excitedly toward the box. The couple's contrasting body language tells the entire story: his hesitation against her unmistakable enthusiasm. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Soft cinematic storefront lighting, reflections of passing city lights on the glass, slightly elevated camera angle, crisp details, restrained humorous mood, natural couple interaction. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, clearly separated from the main scene." \
  "ChatGPT" "Elevated Angle, Pointing Excitedly"


# --- Grok fast ---
queue_job 16 \
  "A square composition: a doubtful man and an excited woman standing close together behind the glass wall of an Apple Store at dusk. The man holds an unopened iPhone box, looking uncertain, while the woman leans in with a bright smile and sparkling eyes, pointing at the box. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Soft blue hour lighting reflects on the glass, warm store lights glowing inside. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Grok fast" "Dusk Glass, Pointing at the Box"

queue_job 17 \
  "A square composition: low-angle view of a hesitant man and a thrilled woman pressed against the glass wall of a brightly lit Apple Store at night. The man grips an unopened iPhone box with a doubtful expression, while the woman excitedly clasps his arm, eyes wide with anticipation. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Cool neon reflections and sharp store lighting create high contrast on the glass. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Grok fast" "Low-Angle Night, Gripping His Arm"

queue_job 18 \
  "A square composition: side-angle cinematic shot of a doubtful man and an excited woman behind the glass wall of an Apple Store on a rainy afternoon. The man holds the unopened iPhone box, brows furrowed in hesitation, while the woman stands slightly ahead, beaming and gesturing toward the store with pure excitement. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Soft diffused daylight mixed with warm interior glow, raindrops streaking the glass. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Grok fast" "Rainy Afternoon Side Angle"

queue_job 19 \
  "A square composition: intimate close-up through the glass of a doubtful man and an excited woman inside the reflection of an Apple Store. The man holds an unopened iPhone box with a conflicted look, while the woman rests her chin on his shoulder, eyes shining with excitement and a hopeful smile. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Golden hour sunlight flares across the glass, soft bokeh of the store interior behind them. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Grok fast" "Golden Hour Chin on Shoulder"

queue_job 20 \
  "A square composition: high-angle view of a doubtful man and an excited woman standing behind the glass wall of a modern Apple Store. The man clutches the unopened iPhone box, looking unsure, while the woman jumps slightly with excitement, hands clasped, face full of pure enthusiasm. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Clean midday lighting with sharp reflections and cool white store illumination. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Grok fast" "High-Angle Midday, Jumping with Joy"


# --- Qwen 3.8 Omni Flash Thinking ---
queue_job 21 \
  "Square composition, photorealistic eye-level medium shot. A doubtful young man stands behind the glass wall of an Apple Store, holding an unopened iPhone box close to his chest with a hesitant expression. On the box label, small readable text says \"iPhone 18 pro max 2TB\", and large numerals show \"3650\$\". Outside the glass, his excited female partner leans forward with bright eyes and a joyful smile, pressing one hand against the glass and pointing at the iPhone box, clearly thrilled while he remains unsure. Clean Apple Store interior, soft daylight reflections on glass, realistic skin texture, shallow depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Eye-Level Daylight, Pressing Hand to Glass"

queue_job 22 \
  "Square composition, cinematic low-angle shot at night. A doubtful man stands behind the glass wall of an Apple Store, holding an unopened iPhone box with a worried, uncertain face. The box label contains small text reading \"iPhone 18 pro max 2TB\" and large bold numerals \"3650\$\". Beside him, also behind the glass, his excited girlfriend grabs his sleeve with one hand and gestures happily toward the box, eyes wide with joy and anticipation. Neon city lights reflect across the glass storefront, cool blue Apple Store lighting mixed with warm street glow, dramatic shadows, realistic photographic detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Low-Angle Night, Neon City Lights"

queue_job 23 \
  "Square composition, high-angle view looking slightly down into an Apple Store entrance. A doubtful man stands behind the glass wall, holding an unopened iPhone box with a confused, hesitant expression. The box label shows small readable text \"iPhone 18 pro max 2TB\" and large numerals \"3650\$\". His excited female partner stands just outside the glass, smiling broadly, clapping her hands together and leaning toward him as if encouraging him to buy it. Minimalist Apple Store interior, warm white lighting, polished floor reflections, clean modern atmosphere, realistic candid couple moment. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "High-Angle Entrance, Clapping Hands"

queue_job 24 \
  "Square composition, over-the-shoulder shot from behind an excited woman looking through the glass wall of an Apple Store. In front of her, a doubtful man stands behind the glass, holding an unopened iPhone box with a tense, uncertain expression. The box label includes small text \"iPhone 18 pro max 2TB\" and large numerals \"3650\$\". The woman's shoulder and partial profile are visible in the foreground, her face lit with joyful anticipation as she looks at him and the box. Rainy evening outside, soft bokeh city lights, reflections on wet glass, moody cinematic lighting, realistic photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Omni Flash Thinking" "Over-the-Shoulder, Rainy Evening"

queue_job 25 \
  "Square composition, frontal symmetrical shot. A doubtful man stands centered behind the glass wall of an Apple Store, holding an unopened iPhone box with a skeptical, hesitant look. The box label clearly reads \"iPhone 18 pro max 2TB\" in small text, with large numerals \"3650\$\". To his side, his excited female partner faces the camera with a radiant smile, one hand raised in delight and the other gently touching his arm, creating a strong contrast between her excitement and his doubt. Bright, clean Apple Store lighting, subtle glass reflections, crisp realistic details, balanced composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the couple and the iPhone box." \
  "Qwen 3.8 Omni Flash Thinking" "Frontal Symmetrical, Radiant Smile"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "A square composition: a doubtful man standing behind the glass wall of an Apple Store, clutching an unopened iPhone box to his chest, brows furrowed, biting his lip, while the woman beside him leans toward the glass with a huge excited smile, tugging his sleeve, eyes sparkling. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Clean minimalist interior, white oak display tables, soft diffused daylight, subtle reflections on the glass. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Clean Interior, Tugging His Sleeve"

queue_job 27 \
  "A square composition, dramatic low-angle shot from the sidewalk at night: behind the glowing glass wall of an Apple Store, an excited man raises an unopened iPhone box overhead like a trophy, laughing, while a doubtful woman beside him crosses her arms and squints skeptically at the price. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Neon city reflections streak across the glass, cool blue and warm tungsten contrast, wet pavement, cinematic night mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Low-Angle Night, Trophy Overhead"

queue_job 28 \
  "A square composition, cinematic medium shot from the street looking in through the storefront: warm golden-hour sunlight flares across the Apple Store glass. Inside, a doubtful man rubs his chin, staring at the unopened iPhone box in his hands, while the excited woman beside him clasps her hands under her chin, beaming, half-laughing. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Amber light, soft lens flare, floating dust, gentle reflections of passersby on the glass, romantic warm mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Golden-Hour Storefront, Hands Under Chin"

queue_job 29 \
  "A square composition, tight close-up shot through the glass wall of an Apple Store: an excited man presses an unopened iPhone box against the glass with both hands, face glowing with pure joy, while in the soft-focus foreground the doubtful woman's profile appears with a raised eyebrow and a skeptical half-smile, arms crossed. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Moody interior lighting, spotlight glow from display tables, shallow depth of field, blurred storefront bokeh behind. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Close-Up Glass, Skeptical Profile"

queue_job 30 \
  "A square composition, wide symmetrical shot from inside the Apple Store: a doubtful man leans back slightly, one hand pressed to his wallet pocket, hesitating with the unopened iPhone box in the other, while the excited woman beside him claps her hands mid-laugh, practically hopping with joy. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Cool blue-hour light pouring through the glass wall, clean white interior, faint reflections on the polished floor, playful humorous mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Wide Symmetrical, Clapping Mid-Laugh"


# --- DeepSeek Think Search ---
queue_job 31 \
  "A square composition, cinematic photography. A doubtful man stands outside an Apple Store, his face and figure clearly visible through the large, rain-streaked glass wall. He holds an unopened, pristine white iPhone box. His expression is one of deep uncertainty and quiet despair. The store's interior is brightly lit and filled with blurred, happy customers, creating a stark contrast. On the box label, sharp text reads \"iPhone 18 pro max 2TB\" next to large, imposing numerals \"3650\$\". Shot on a 50mm lens, shallow depth of field, muted color palette. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Rain-Streaked Glass, Quiet Despair"

queue_job 32 \
  "A square composition, brutalist and stark. A low-angle shot of a doubtful man standing behind the seamless glass wall of an Apple Store. The architecture is minimalist and imposing. He clutches an unopened iPhone box like a burden. The light from within is a cold, unforgiving blue, highlighting the sharp text on the box label: \"iPhone 18 pro max 2TB\" and the large, shocking price \"3650\$\". His face is partially in shadow, emphasizing his dilemma. Style of a sci-fi movie still, hyper-detailed, high contrast. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Brutalist Low-Angle, Cold Blue Light"

queue_job 33 \
  "A square composition in the style of a contemporary oil painting. A doubtful man stands behind the glass wall of an Apple Store, the scene slightly distorted as if viewed through water. He holds an unopened iPhone box. The glass reflects a warm, golden sunset, while the store's interior glows with a soft, ethereal light. The box's label, with its text \"iPhone 18 pro max 2TB\" and numerals \"3650\$\", is rendered with thick, expressive brushstrokes. Textured canvas feel, rich colors, artistic masterpiece. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Oil Painting Sunset Glow"

queue_job 34 \
  "A square composition, gritty street photography at night. An over-the-shoulder close-up of a doubtful man's reflection in the glass wall of an Apple Store. He holds an unopened iPhone box tightly. The glass acts as a mirror, showing his conflicted face superimposed over the brightly lit store interior. The store's stark LED lighting illuminates the box's label: \"iPhone 18 pro max 2TB\" and the large numerals \"3650\$\". Rain and neon signs from the street create a chaotic, colorful bokeh effect. 35mm film grain, raw, unfiltered. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Reflection Over-the-Shoulder, Neon Night"

queue_job 35 \
  "A square composition, minimalist conceptual art. A wide shot of a doubtful man standing behind the glass wall of an Apple Store. The entire background outside the store is an endless, solid gray void, making the store a glowing box. The man and his unopened iPhone box are the sole focus. The text \"iPhone 18 pro max 2TB\" and the numerals \"3650\$\" are crisp and clean on the box. The scene is silent and still, focusing on the pure geometry and the weight of the decision. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Minimalist Void, Glowing Box"


# --- MiniMax M3 ---
queue_job 36 \
  "A square composition: a young couple stands behind the floor-to-ceiling glass wall of an Apple Store at dusk. The man, mid-20s, in a beige trench coat, clutches an unopened white iPhone box against his chest with both hands, brows furrowed, lips pressed thin, eyes full of doubt as he stares at the price tag. Beside him, his girlfriend in a red knit sweater leans toward him with a wide grin, one finger pointing excitedly at the box, body language radiating anticipation. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Soft cool blue twilight outside contrasts with warm tungsten glow from inside the store reflecting on the glass. Subtle raindrops streak the window. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Dusk Twilight, Raindrops on the Window"

queue_job 37 \
  "A square composition shot through the Apple Store window glass at night, where two layers of reality overlap. The man in a dark wool overcoat is seen in sharp focus, looking down at an unopened iPhone box with a heavy, conflicted expression, his jaw slightly tight. Behind him and reflected in the glass, the woman in a sequined party dress appears translucent, mid-laugh, her hands clasped under her chin in pure excitement, a halo of magenta neon from the Apple logo glowing around her silhouette. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Cinematic chiaroscuro lighting: deep teal shadows, warm amber highlights on his face, cool magenta on hers. Wet street reflections in the foreground. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Ghostly Reflection, Neon Magenta Halo"

queue_job 38 \
  "A square composition: over-the-shoulder perspective from behind the woman, her auburn hair and cream-colored scarf framing the lower corners of the frame. She gazes through the glass wall of an Apple Store at her boyfriend, who stands a few feet away on the other side of the threshold, holding an unopened iPhone box at waist height, looking up at the glowing price display with a wince, one hand running nervously through his hair. She has turned her head halfway back toward the camera with a soft, knowing smile, eyes sparkling with excitement. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Bright, clean daylight, soft pastels — pale pink sky, white marble storefront, diffused midday sun. Shallow depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Over-the-Shoulder, Soft Pastel Daylight"

queue_job 39 \
  "A square composition in a wide cinematic street view at golden hour. A couple walks along the sidewalk in front of an Apple Store with floor-to-ceiling glass. The man in a navy hoodie walks slowly, head down, an unopened iPhone box dangling from one hand, his free hand shoved deep in his pocket, face showing resigned reluctance. The woman in a yellow sundress strides a half-step ahead, almost skipping, body turned back toward him, both arms thrown wide in gleeful anticipation, hair catching the amber sunset light. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Long warm orange and purple sunset shadows stretching across the pavement, the Apple Store interior glowing white behind the glass. Light flares from the low sun. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Golden-Hour Sidewalk, Skipping Ahead"

queue_job 40 \
  "A square composition shot from a dramatic low angle looking up at a couple framed by the Apple Store glass wall, with skyscrapers towering behind. The man in a charcoal suit holds the unopened iPhone box high against the glass like evidence, his face twisted in a painful grimace, sweat visible on his brow, eyes squeezed shut in doubt. The woman beside him in a sleek black evening dress has both fists pumped in the air in pure triumph, mouth open in a joyful shout, eyes blazing with excitement, silver jewelry glittering. On the box label, small text reads \"iPhone 18 pro max 2TB\", alongside large numerals \"3650\$\". Harsh noir lighting: a single sharp white spotlight from above cutting through fog, deep black shadows, the Apple Store interior glowing a sterile blue-white. Rain mist hangs in the air. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"1\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Low-Angle Noir, Triumphant Fists"


echo "✅ All 40 jobs queued in scheduleri"
