#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 10 - melancholic story of a young
#        woman and her dog in a post-apocalyptic city (few survivors left,
#        but some food still available in stores), bottom-center "10" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+10+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# NOTE: prompt 2 ("Empty Streets") was cut off mid-sentence on the source
# wiki page (ended at "...set" with no closing clause). Completed here with
# the standard closing clause used by every other prompt on both pages.
# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A young woman in a faded oversized coat wakes on a moss-covered mattress inside a crumbling apartment, sunlight slicing through a collapsed wall, her loyal mutt curled against her side. Dust motes drift in golden light, ivy creeping through broken windows, muted teal and rust palette, melancholic cinematic realism, soft grain, Studio Ghibli-meets-Tarkovsky mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Waking Alone"

queue_job 2 \
  "The woman walks a cracked, weed-split boulevard lined with rusted cars and silent storefronts, her dog trotting close at her heel, both dwarfed by empty high-rises fogged in morning haze. Faded advertisements peel from walls, birds circle overhead, desaturated blues and ash tones, quiet documentary-style framing, wide establishing shot, somber atmosphere reminiscent of Chernobyl photography. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Empty Streets"

queue_job 3 \
  "Inside a dim, overgrown convenience store, the woman kneels sorting dusty canned goods from a toppled shelf while her dog sniffs at a torn bag of kibble nearby, a single shaft of light through a shattered skylight illuminating floating dust. Warm amber interior against cold blue exterior glow, still-life composition, painterly texture, quiet survival tenderness. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "The Last Grocery"

queue_job 4 \
  "Perched on a rooftop ledge overlooking a skeletal skyline swallowed by fog, the woman sits with knees drawn to her chest, her dog resting its head in her lap, both watching the sun sink behind dead cranes and vine-wrapped towers. Muted lavender and burnt orange sky, contemplative silhouette lighting, melancholic widescreen composition, painterly realism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Rooftop Rest"

queue_job 5 \
  "By a small fire built from broken furniture in a gutted plaza, the woman shares a can of food with her dog, firelight flickering against overgrown fountain statues and a starless smog-veiled sky, her expression tired but tender. Intimate close framing, warm firelight versus cold ruin, soft cinematic grain, quiet hope amid desolation. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Quiet Companionship"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "A young woman in a worn leather jacket with a faded patch sitting on the hood of a rusted, abandoned car in a desolate city intersection, her scruffy golden retriever laying beside her resting its chin on her knees. Overgrown vines creeping up broken skyscrapers in the soft, gray morning light, empty street, scattered trash, cinematic, high detail, photorealistic, atmospheric melancholic mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "The Quiet Dawn"

queue_job 7 \
  "A young woman in a dark hooded raincoat holding a glowing flashlight inside an abandoned, dimly lit supermarket, searching through rows of half-empty shelves lined with dust-covered canned goods. Her medium-sized mix-breed dog with alert ears stands on guard next to her in the shadows, watchful, muted earth tones, somber tone, highly detailed textures, dramatic lighting, realistic photo. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Midnight Rations"

queue_job 8 \
  "A young woman leaning against a cracked glass storefront window of an old bookstore in a quiet post-apocalyptic city street, looking down at an old photograph in her hands with a sad, distant expression. Her loyal dog sits patiently at her feet on the damp asphalt, overcast lighting, puddle reflections of ruined buildings, nostalgic and tragic mood, photorealistic, 8k resolution, cinematic composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Echoes of the Past"

queue_job 9 \
  "A young woman with tied-back messy hair sitting at the edge of a high rooftop overlooking an expanse of a quiet, empty metropolis where nature is taking back the concrete. A German Shepherd mix rests close by her side, looking out over the horizon together, late afternoon golden light mixed with dark melancholic shadows, highly realistic, depth of field, atmospheric, film grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "High Vantage Point"

queue_job 10 \
  "A young woman wrapped in a heavy wool blanket sitting under the concrete overhang of a ruined bridge during a heavy downpour, sharing a small tin of canned meat with her dog. Rain streaming down around their small dry haven, flickering lantern glow casting soft warm highlights against the cold blue night, emotional and quiet moment, hyper-realistic, rich textures. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Shelter in the Rain"


# --- ChatGPT ---
queue_job 11 \
  "A cinematic photorealistic scene of a young woman walking slowly through a deserted post-apocalyptic city street with her loyal dog beside her, both visibly tired but quietly connected. Abandoned cars sit covered in dust and weeds, apartment buildings are weathered and partially damaged, storefronts are dark, yet one small grocery store remains intact with shelves still holding canned food, bottled water, and scattered basic supplies. The woman carries a worn backpack and wears practical layered clothing, while the dog stays close to her leg. Pale late-afternoon sunlight breaks through heavy clouds, creating long shadows across the empty street, with subtle traces of human survival such as a few distant curtains moving and faint smoke rising from one rooftop. Melancholic, intimate, subdued atmosphere, cinematic composition, realistic textures, emotional storytelling, muted colors with small warm accents. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "ChatGPT" "The Last Walk"

queue_job 12 \
  "A cinematic photorealistic interior of a nearly abandoned convenience store in a post-apocalyptic city, where a young woman and her dog quietly share a moment of survival. The woman sits on the floor beside an old checkout counter, opening a small can of food while her dog waits patiently beside her, looking up at her with trust. Behind them, surprisingly intact shelves contain canned vegetables, crackers, bottled water, and other simple food supplies, suggesting that survival is possible but loneliness remains overwhelming. Through the dusty front windows, an empty boulevard with abandoned buses, weeds, and damaged buildings can be seen under a cold gray sky. A small battery lantern provides the only warm light inside the store, illuminating the woman's face and the dog's fur. Melancholic, quiet, human, emotionally restrained, detailed cinematic realism, strong contrast between available food and the absence of people. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "ChatGPT" "A Meal for Two"

queue_job 13 \
  "A cinematic photorealistic scene inside a worn apartment high above a post-apocalyptic city, showing a young woman sitting beside a large cracked window with her dog curled up against her feet. The apartment contains very few possessions: a mattress, an old chair, several candles, a backpack, and a small table covered with canned food and bottles of water collected from abandoned stores. Outside, the vast city stretches into the distance, strangely quiet and almost completely empty, with overgrown streets, abandoned vehicles, broken windows, and only a few tiny signs of life such as a distant light glowing in another apartment. The woman gently rests one hand on her dog's head while staring silently toward the horizon, conveying companionship in a world where almost everyone else has disappeared. Cold blue-gray evening light mixes with a faint amber glow from the candles. Melancholic, intimate, atmospheric, realistic cinematic photography, subtle emotional storytelling. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "ChatGPT" "The Apartment Above the City"

queue_job 14 \
  "A cinematic photorealistic image of a young woman and her dog exploring a deserted supermarket in a post-apocalyptic city. The supermarket is dusty and partially damaged, with overturned shopping carts, broken ceiling panels, vines creeping through cracked windows, and shelves that have been heavily picked over, yet enough canned food, bottled water, dried goods, and preserved products remain to keep a few survivors alive. The woman stands motionless in one aisle, holding a flashlight while her dog investigates an abandoned shopping basket containing a recently opened food package. On a dusty checkout counter nearby sits a handwritten note left by another survivor, implying that someone else may still be somewhere in the city. Their discovery creates a mixture of hope and sadness rather than fear. Soft daylight filters through the ruined roof, illuminating floating dust particles. Melancholic post-apocalyptic realism, cinematic framing, detailed environmental storytelling, subdued natural colors, quiet tension. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "ChatGPT" "Someone Was Here"

queue_job 15 \
  "A wide cinematic photorealistic night scene of a young woman and her dog standing on the rooftop of a partially abandoned building, overlooking a vast post-apocalyptic city. The streets below are almost completely dark and empty, filled with abandoned cars, overgrown intersections, collapsed structures, and occasional pools of moonlight. In the distance, however, a handful of tiny warm lights glow from several surviving buildings, suggesting that a few other people are still alive. Beside the woman is a small backpack containing canned food and bottled water gathered during the day, while her dog sits quietly beside her, both staring toward the distant lights. She gently places one hand on the dog's back, sharing a silent moment of companionship and fragile hope. A cold moonlit sky contrasts with the tiny warm lights of the remaining survivors. Deeply melancholic but subtly hopeful, cinematic photography, realistic textures, atmospheric depth, restrained color palette, powerful visual storytelling. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "ChatGPT" "Lights in the Distance"


# --- Grok fast ---
queue_job 16 \
  "A young woman in a worn jacket walks slowly through the dusty, half-lit aisles of an abandoned supermarket in a crumbling post-apocalyptic city, her loyal dog padding quietly beside her as they carefully select a few remaining canned goods from the sparse shelves, soft gray light filtering through broken windows, melancholic atmosphere of quiet survival amid empty streets and distant ruins, no other people in sight. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Grok fast" "Empty Aisles, Shared Silence"

queue_job 17 \
  "From a cracked rooftop overlooking a silent, overgrown post-apocalyptic cityscape with empty roads and leaning buildings, a young woman sits with her dog resting its head on her lap, both gazing at the horizon under a muted overcast sky, a small bag of scavenged food from nearby stores beside them, conveying deep melancholy and fragile companionship in a world with few survivors left. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Grok fast" "Rooftop Watch"

queue_job 18 \
  "In the quiet shadow of a collapsed storefront in a near-empty post-apocalyptic city, a young woman and her dog share a simple meal of scavenged canned food and dry biscuits on a makeshift blanket, her hand gently stroking the dog's fur as soft light falls on their tired faces, the surrounding streets deserted except for the distant promise of more supplies still on store shelves, heavy with melancholic stillness. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Grok fast" "Shared Meal in the Rubble"

queue_job 19 \
  "A young woman and her dog walk side by side down a long, empty boulevard lined with shuttered shops and vine-covered cars in a post-apocalyptic city where almost no one remains, she carrying a modest bag of food gathered from still-stocked stores, their figures small against the vast silence and crumbling architecture, an atmosphere of quiet sorrow and enduring bond. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Grok fast" "Fading Footsteps"

queue_job 20 \
  "Inside a dusty, half-abandoned apartment overlooking a deserted post-apocalyptic city, a young woman sits by a broken window with her dog curled at her feet, carefully dividing the last of the day's scavenged food from nearby stores between them, soft evening light casting long shadows across the room, the scene steeped in melancholy, isolation, and the quiet comfort of their companionship. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Grok fast" "Last Light by the Window"


# --- Qwen 3.7 Plus ---
queue_job 21 \
  "A cinematic wide shot of a young woman in worn tactical gear kneeling beside her loyal German Shepherd in an abandoned supermarket aisle. Sunlight streams through broken windows, illuminating dust particles and scattered canned goods on the floor. The woman's face shows quiet sorrow as she gently strokes her dog's head, surrounded by shelves of untouched food in the desolate city. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus" "Empty Aisles, Full Hearts"

queue_job 22 \
  "An intimate close-up portrait of a young woman with matted hair and tear-streaked cheeks, sitting on cracked pavement outside a looted convenience store. Her small terrier mix rests its head on her knee, both gazing into the distance at the overgrown urban landscape. Faded advertisements and rusted cars create a haunting backdrop while fresh produce remains visible through the store's shattered glass doors. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus" "The Last Companions"

queue_job 23 \
  "A moody evening scene showing a young woman in a tattered hoodie sharing a can of beans with her aging golden retriever on the steps of an abandoned apartment complex. Warm amber light from a single working streetlamp casts long shadows across their weathered faces. Behind them, vines crawl up concrete walls and empty shopping carts litter the courtyard, but a nearby bodega still displays fresh bread through its intact window. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus" "Survival and Solitude"

queue_job 24 \
  "A melancholic medium shot of a young woman in a faded floral dress standing beside her border collie in front of a partially collapsed bookstore. She holds a dusty photograph while her dog sniffs at scattered paperback novels on the wet pavement. Rain has just stopped, leaving puddles that reflect the gray sky and skeletal remains of skyscrapers. Through a nearby pharmacy window, shelves of medicine and snacks remain undisturbed in the silent city. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus" "Memories Among the Ruins"

queue_job 25 \
  "A dramatic low-angle view of a young woman with determined eyes walking her rescue pit bull down a deserted boulevard lined with overgrown trees breaking through asphalt. She carries a backpack full of scavenged supplies while her dog trots faithfully beside her. Abandoned vehicles and crumbling facades surround them, yet a corner grocery store ahead shows lights still on and fresh vegetables visible through clean windows, suggesting pockets of life remain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "Qwen 3.7 Plus" "Hope in the Hollow City"


# --- GLM 5.3 Flash ---
queue_job 26 \
  "Cinematic wide shot, a young woman in her early twenties with tangled auburn hair and a worn olive coat stands in the aisle of an abandoned convenience store, holding a dusty can of peaches, her faithful scruffy terrier-mix dog sitting attentively beside her, looking up at her with soulful eyes. Flickering fluorescent light casts pale shadows across half-empty shelves still stocked with canned goods and sealed packages, dust particles floating in beams of gray daylight breaking through cracked storefront windows, melancholic atmosphere, muted desaturated color palette, post-apocalyptic urban decay, no other people anywhere, quiet loneliness and fragile hope, photorealistic, 35mm film grain, shallow depth of field. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Empty Aisles"

queue_job 27 \
  "Moody cinematic scene, a young woman in a faded red scarf walks down the center of a deserted city boulevard at dusk, her large mixed-breed dog trotting loyally at her side, both carrying a small plastic grocery bag from a surviving corner store between them, cracked asphalt overgrown with weeds, abandoned cars with shattered windows, tall derelict buildings with broken windows silhouetted against a bruised orange-and-violet sunset sky, streetlights dead and dark, utter emptiness of a city with almost no survivors, gentle bond between girl and dog, melancholic and tender mood, soft volumetric lighting, photorealistic, anamorphic lens flare, muted tones. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "The Long Walk Home"

queue_job 28 \
  "Intimate cinematic medium shot, a young woman with cropped dark hair sits on the curb outside a small grocery store whose lights still faintly glow inside, sharing an opened bag of bread with her golden-brown dog who eats gently from her hand, her expression tired but soft, faint smile, empty street stretching behind them into gray fog, abandoned shop signs hanging crooked, wet pavement reflecting dim store light, evening drizzle beginning to fall, poignant quiet companionship in a world emptied of people, yet the shelves inside still hold surviving food, melancholic warmth, desaturated blues and grays with a single warm light source, photorealistic, cinematic composition, film still aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Supper on the Curb"

queue_job 29 \
  "Sweeping cinematic wide shot at blue hour, a young woman in an oversized military jacket sits on the edge of a rooftop with her big shaggy dog leaning against her leg, both gazing out over a vast silent post-apocalyptic city skyline, crumbling towers, overgrown highways, a distant supermarket sign faintly lit, one of the last stores with food, tiny warm windows scattered sparsely across the dark buildings suggesting the few remaining survivors, soft haze over the city, emotional stillness and quiet grief mixed with resilience, the dog's head resting near her hand, painterly photorealism, teal and amber color grading, epic yet melancholic scale, volumetric fog. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Rooftop Refuge"

queue_job 30 \
  "Atmospheric cinematic close-up, a young woman in a soaked transparent rain poncho kneels in a puddle-covered alley behind a discount food store, pulling a slightly dented can of soup from a dropped paper bag, her small dog sheltering under her arm from heavy rain, water droplets frozen mid-air, dim glow of a surviving vending machine and a still-operating shop window in the background offering hope of food, garbage-strewn wet alley with graffiti-faded walls, no signs of other people, raw emotional intimacy between the girl and her only companion, cold blue-gray palette pierced by one warm light, hyper-detailed rain texture, photorealistic, shallow depth of field, somber cinematic mood. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "GLM 5.3 Flash" "Rain and Rations"


# --- DeepSeek ---
queue_job 31 \
  "A young woman in a tattered coat and her loyal German Shepherd walk through the empty aisles of an abandoned supermarket, shelves still partially stocked with canned goods, dust motes floating in shafts of pale light through broken skylights, overturned shopping carts, faded sale signs, muted grey and amber tones, cinematic wide shot, melancholic atmosphere, post-apocalyptic realism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "DeepSeek" "The Last Grocery Run"

queue_job 32 \
  "A young woman sits on the edge of a crumbling rooftop at dusk with her dog resting its head on her lap, overlooking a silent ruined city skyline, distant smoke rising, a single flickering streetlight below, her hand gently stroking the dog's fur, tears on her cheek, soft purple and ash-grey palette, emotional cinematic composition, photorealistic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "DeepSeek" "Rooftop Vigil"

queue_job 33 \
  "Close-up of a young woman kneeling on cracked asphalt outside a looted store, opening a single can of food with a rusty knife while her skinny dog watches patiently, their breath visible in cold air, empty streets stretching behind them, scattered debris and dead traffic lights, muted desaturated colors with warm highlight on the can, intimate melancholic mood, hyperrealistic detail. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "DeepSeek" "The Shared Can"

queue_job 34 \
  "A young woman with a backpack and her dog walking down the middle of an empty overgrown highway toward a hazy sun, abandoned cars rusting on the shoulders, a convenience store with intact windows glowing faintly in the distance, vines reclaiming the concrete, her expression tired but determined, cinematic back view, post-apocalyptic melancholy, muted earth tones, film grain. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "DeepSeek" "Walking the Silent Streets"

queue_job 35 \
  "A young woman and her dog curled up together sleeping in a blanket nest inside an abandoned grocery store aisle, surrounded by scattered cans and empty shelves, a small battery lantern casting warm light, her arm wrapped protectively around the dog, quiet grief and companionship, nighttime interior, soft chiaroscuro lighting, emotional post-apocalyptic scene, hyperdetailed photorealism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "DeepSeek" "Shelter in the Aisle"


# --- MiniMax M3 ---
queue_job 36 \
  "A young woman in a faded red jacket and worn combat boots kneels on the cracked tile floor of an abandoned supermarket, her fingers closing gently around a single dented can of peaches still sitting on a dusty shelf. Beside her, a scruffy brindle dog with intelligent, sorrowful eyes sits close to her leg, head tilted upward as if to ask what she has found. Tall metal shelving stretches into shadow on either side, most shelves long since stripped bare, a few scattered cans and torn cardboard boxes left behind like bones. Pale afternoon light falls through a broken skylight overhead, illuminating drifting dust motes and the woman's tired face, half-lit, half-shadowed, eyes reflecting a quiet grief. The mood is hushed and tender, the silence of a world almost emptied of people but not yet emptied of food. Cinematic composition, wide-angle, eye-level, soft contrast, muted earth tones with a single warm golden accent on the peaches. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Last Can of Peaches"

queue_job 37 \
  "A young woman sits on the concrete edge of an abandoned rooftop, her legs dangling over a city of broken skyscrapers that climb like tombstones toward a bruised violet dusk sky. She wears a patched gray hoodie, her hair loose and tangled by wind, and her arms are wrapped around a lean, weathered dog whose chin rests on her shoulder, both of them looking out over the silent urban sprawl below. Crumbling billboards hang crooked from rusting frames, ivy crawls up the sides of once-shiny towers, and distant windows catch the last copper light of the sun. No other living figures appear anywhere in the scene; the city feels vast, sleeping, and forgotten, yet a faint warm glow from a few lit convenience-store signs in the lower blocks suggests food is still waiting inside. Cinematic composition, rule-of-thirds framing with the subjects slightly left, deep depth of field, melancholic color grading in indigo and faded gold, painterly realism. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Rooftop Watch Over a Sleeping City"

queue_job 38 \
  "A young woman and her dog cross a long, half-collapsed concrete bridge in the early morning fog, the woman walking slowly with her hand resting on the dog's back, the dog stepping cautiously ahead on cracked asphalt littered with abandoned cars and rusting bicycles. She wears a long olive coat over layered sweaters, a canvas backpack slung low on one shoulder, and her face is turned downward, lost in thought, as if remembering someone who used to walk beside her. The bridge's suspension cables hang slack and tangled, one section has crumbled away into the pale river below, and the far end dissolves into milky white mist where the rest of the city lies, mostly empty, a few corner grocery stores still faintly lit through dirty windows with food on shelves no one has come to take. Cinematic composition, low angle from across the water, symmetrical framing, soft diffused light, cool desaturated palette with subtle warm highlights, a mood of quiet grief and fragile hope. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Crossing the Broken Bridge"

queue_job 39 \
  "A young woman stands in the open doorway of an old apartment on the fourth floor of a decaying residential building, her hand pressed against the doorframe, looking inward at a living room slowly being reclaimed by creeping green vines pushing through the floorboards and curling around an overturned couch. Her dog sits patiently just outside, ears perked, watching her with quiet empathy, leash hanging loose to the ground. Inside, faded family photos still cling to the wallpaper, a kettle sits on the stove untouched, and rain streaks down a tall window, turning the cityscape beyond into a watercolor blur of gray towers and empty streets. Food wrappers and unopened tins still rest on a kitchen counter; the world has not starved, it has simply stopped coming home. Cinematic composition, medium shot from a slight low angle, shallow depth of field with soft bokeh rain on glass, melancholic teal-and-amber grading, intimate and sorrowful atmosphere. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Returning to the Overgrown Apartment"

queue_job 40 \
  "A young woman crouches in a small square of cracked pavement where, impossibly, a wild garden of daisies, fennel, and clover still grows between chunks of fallen masonry, her dog curled beside her on a folded blanket, nose resting on her knee as she gently pours a precious capful of bottled water into her palm and lets him drink. She wears a denim jacket with the sleeves rolled up, her hair tied back messily, and her expression is the first soft, unguarded smile of the entire sequence, a small, fragile moment of peace in an otherwise ruined world. Behind them, a half-collapsed library stands open to the sky, its books scattered and swelling with rain, while across the empty plaza, the lit window of a small corner grocery glows faintly, shelves still stocked with canned goods, bread, and bottled water that no living neighbors remain to buy. Cinematic composition, intimate medium shot with the subjects framed by crumbling architecture on both sides, warm low sunlight breaking through clouds, soft natural color palette of moss green, dust beige, and pale gold, deeply emotional and tender. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"10\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Garden Between the Rubble"


echo "✅ All 40 jobs queued in scheduler"
