#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: CivitAi 10x10 Deathmatch - Image 7 - urban life 2D paper-cut art,
#        drive-ins, tram stops, markets, rooftops, laundromats and crosswalks
#        with adults only, bright layered paper work with depth and details,
#        bottom-center "7" marker
# Source: https://wiki.liutyi.info/display/AI/CivitAi+10x10+Deathmatch+-+Image+7+Drafts
# Structure: 8 models x 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 high ---
queue_job 1 \
  "A bright 2D paper-cut illustration of a retro drive-in fast food restaurant, flat layered cardstock shapes forming a neon paper sign and parked cars, adults ordering from a walk-up window rendered in bold cut silhouettes, crisp overlapping paper layers creating shallow depth, drop shadows between planes, saturated candy-bright colors, clean collage-style composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Drive-In Fast Food"

queue_job 2 \
  "A flat 2D paper-cut scene of adults waiting at a city tram stop, layered cut-paper silhouettes in coats holding umbrellas and briefcases, a paper tram gliding along a flat track, geometric paper buildings stacked behind in overlapping planes, bold graphic color blocking, soft layered shadows giving subtle dimension to an otherwise flat composition. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Tram Stop"

queue_job 3 \
  "A vivid 2D paper-cut collage of a corner newsstand kiosk, flat layered paper magazines and folded newspapers fanned across the counter, an adult vendor silhouette cut from bold cardstock handing change to a customer, stacked paper buildings and a striped awning above, bright saturated palette, crisp layered edges casting soft graphic shadows. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Corner Newsstand"

queue_job 4 \
  "A cheerful flat 2D paper-cut illustration of a rooftop laundry scene, layered cut-paper clothes pinned to crisscrossing lines against a skyline of stacked paper rooftops, an adult figure in silhouette hanging a paper shirt, pigeons cut from gray cardstock perched on a ledge, bright pastel-and-bold color contrast, clean layered depth throughout. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "Rooftop Laundry Line"

queue_job 5 \
  "A bold 2D paper-cut composition of adults waiting at a city bus stop under a flat paper shelter, layered silhouettes checking paper phones and folded maps, a paper bus arriving with rounded cut headlights, overlapping flat storefronts and lamp posts behind, richly saturated graphic colors, subtle layered shadows keeping the scene crisp and flat. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Claude Sonnet 5 high" "City Bus Stop"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "2D paper-cut illustration of a vibrant 1950s fast food drive-thru at dusk. Crisp layered paper silhouettes of classic cars lined up at the order station, with neon-lit paper signs glowing in bright magenta, warm yellow, and orange. Multi-layered paper background featuring a sleek diner building, palm trees, and a gradient twilight sky. Detailed drop shadows created by sharp paper edges, giving a tactile sense of depth and hand-crafted craftwork. Clean white cutouts for headlights and window highlights. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Fast Food Drive-Thru at Dusk"

queue_job 7 \
  "Intricate 2D paper-cut art depicting adult commuters standing under a glowing paper-craft street lamp, waiting at an urban tram stop at twilight. Sharp, distinct layers of cut paper creating depth: foreground figures in trench coats holding umbrellas, midground platform with textured brick detailing, and a background featuring an approaching yellow electric tram with glowing cut-out windows. A rich, vibrant color palette of teal, deep navy, golden yellow, and crimson red. Multi-layered paper depth with precise shadows between each sheet, creating a handcrafted, tactile aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Evening Tram Stop"

queue_job 8 \
  "A bright, colorful 2D paper-cut illustration of a bustling urban street corner with a food truck. Layered paper artwork featuring adult customers ordering at the counter, string lights glowing overhead, and detailed architectural facades of city apartment buildings rising in the background. Saturated paper tones of vibrant cyan, coral red, sunny yellow, and mint green. Deep paper shadows, clean hand-cut edges, and distinct layering that builds dimensional perspective. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Vibrant Street Food Truck Corner"

queue_job 9 \
  "Minimalist yet highly detailed 2D paper-cut visual of an illuminated urban laundromat view from across the street. Layered paper construction showing adult figures inside sitting on benches reading and waiting by rows of colorful washing machines. Vibrant paper palette using bright orange, cobalt blue, turquoise, and warm white. Precise paper overlay creating visible depth through overlapping walls, window frames, and interior shadows. Tactile, crisp paper edges with clean geometric cuts and rich ambient warmth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Late-Night Laundromat Window"

queue_job 10 \
  "Vibrant 2D paper-craft illustration of an urban rooftop coffee kiosk overlooking a dense city skyline. Adults relaxing on wooden paper-cut benches with coffee cups. Richly layered depth with foreground railings, midground counter with steaming espresso machine details, and background paper cutouts of skyscrapers under a bright sunset sky. Palette of rich violet, burnt amber, emerald green, and electric yellow. Dimensional drop shadows and precise paper-fold textures creating an intricate, hand-assembled 3D paper illusion. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Gemini 3.6 Flash" "Rooftop Coffee Kiosk"


# --- ChatGPT ---
queue_job 11 \
  "A vibrant urban fast-food drive-in rendered as intricate 2D paper-cut artwork, a small retro car stopped at the glowing ordering window, cheerful adult customers inside, a smiling adult server behind the counter, illuminated menu boards, striped awnings, paper cups, fries, parked cars, streetlights, and apartment buildings rising in the background. Bright layered paper in saturated red, yellow, orange, turquoise, blue, and cream, with crisp hand-cut edges, overlapping paper layers, subtle shadows between every layer, rich foreground details, atmospheric depth, playful urban energy, handcrafted papercraft aesthetic, clean composition with strong visual hierarchy. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "ChatGPT" "Drive-In at Midnight"

queue_job 12 \
  "A lively city tram stop depicted as detailed 2D paper-cut art, a group of adult commuters waiting along the platform, some standing together and chatting, others looking down the street, a colorful tram approaching in the middle distance, overhead electrical wires, advertising posters, street signs, bicycles, benches, trees, storefronts, and layered apartment facades behind them. Bright paper construction with vivid teal, coral, yellow, green, orange, blue, and warm cream layers, intricate cut-paper silhouettes, visible paper edges, delicate cast shadows, multiple overlapping layers creating strong dimensional depth, abundant small urban details, cheerful handcrafted paper diorama feeling. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "ChatGPT" "Tram Stop in the City"

queue_job 13 \
  "A dynamic downtown intersection transformed into elaborate 2D paper-cut artwork, adult pedestrians crossing at a wide zebra crossing, several cars and a city bus moving through the street, traffic lights, bicycles, storefronts, café tables, street trees, utility poles, signs, and tall buildings receding into the background. Bright colorful paper construction using cobalt blue, sunny yellow, vivid red, orange, mint green, and cream, with carefully layered cut-paper figures and architecture, crisp hand-cut contours, stacked foreground and background planes, soft paper shadows, tiny architectural and street details, energetic everyday urban atmosphere, sophisticated handcrafted paper illustration with impressive depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "ChatGPT" "Busy Crosswalk"

queue_job 14 \
  "A charming dense urban neighborhood rendered entirely as bright 2D paper-cut art, adults hanging laundry on a busy apartment rooftop while other adults relax beside small tables and potted plants, neighboring rooftops packed with water tanks, antennas, clotheslines, chimneys, fire escapes, windows glowing warmly, distant buildings, and a colorful evening sky. Rich layers of turquoise, magenta, orange, yellow, blue, red, and cream paper, intricate silhouettes, folded paper textures, overlapping architectural planes, subtle shadows separating every layer, tiny laundry and rooftop objects, strong sense of depth from foreground figures to distant city blocks, lively handcrafted urban papercraft aesthetic. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "ChatGPT" "Rooftop Laundry Evening"

queue_job 15 \
  "A colorful urban street corner created as sophisticated 2D paper-cut artwork, an open-air café filled with adult customers, some sitting at small round tables and others standing near the entrance, a barista serving drinks through the window, pedestrians passing by, a delivery bicycle, parked cars, street lamps, potted plants, storefront signs, balconies, and dense apartment buildings layered into the distance. Bright handcrafted paper using warm yellow, orange, red, turquoise, emerald green, cobalt blue, and cream, highly detailed cut-paper construction, crisp layered edges, dimensional paper shadows, overlapping foreground objects, intricate miniature urban details, lively everyday city atmosphere, polished editorial papercraft illustration with rich visual depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "ChatGPT" "Corner Café on a Busy Street"


# --- Grok fast ---
queue_job 16 \
  "Urban life 2d paper-cut art of a glowing late-night drive-in fast-food restaurant under bright neon signs, cars lined up with adults leaning out of windows ordering burgers and fries, layered paper silhouettes of staff in the open kitchen window, steam rising in cut-out shapes, bold colorful layers of building, streetlights and distant skyline, vibrant paper textures with sharp shadows and intricate depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Grok fast" "Neon Drive-In Night"

queue_job 17 \
  "Urban life 2d paper-cut art of adults waiting at a busy city tram stop on a bright morning, layered paper figures of people in coats and bags standing on the platform, a colorful tram approaching with open doors, cut-out buildings and street signs in the background, bright paper work with overlapping depth, detailed folds of clothing and urban architecture, cheerful saturated colors and crisp edges. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Grok fast" "Tram Stop Morning Rush"

queue_job 18 \
  "Urban life 2d paper-cut art of adults hanging laundry on a sunlit city rooftop, bright paper sheets and clothes fluttering in layered cut-out layers, neighboring buildings with windows and satellite dishes stacked in depth, potted plants and water tanks adding intricate details, vivid daylight colors and sharp paper shadows creating strong dimensional contrast. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Grok fast" "Rooftop Laundry Day"

queue_job 19 \
  "Urban life 2d paper-cut art of a lively evening street food market, adults gathered around brightly lit paper-cut stalls selling noodles and skewers, layered depth of hanging lanterns, steam clouds, and stacked food displays, detailed cut-outs of vendors and customers under string lights, bold saturated paper colors with rich shadows and urban clutter. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Grok fast" "Night Market Food Stalls"

queue_job 20 \
  "Urban life 2d paper-cut art of adults crossing a busy city crosswalk after a light rain, bright reflections on wet paper streets, layered silhouettes of people with umbrellas and bags, tall buildings and traffic lights stacked in depth, colorful storefronts and puddles adding intricate details, vibrant paper textures with clean edges and strong dimensional layering. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Grok fast" "Crosswalk After Rain"


# --- Qwen 3.8 Max ---
queue_job 21 \
  "Urban life 2d paper-cut art of a retro fast food drive-in restaurant at dusk. Bright paper work style with layered depth and details. Cars lined up with stylized adult drivers, glowing neon signs made of layered paper, checkered pavement, and a vibrant night sky with paper-cut stars and clouds. Intricate shadows and multi-layered paper textures creating a strong sense of 3D depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Neon Nights Drive-In"

queue_job 22 \
  "Urban life 2d paper-cut art of adults waiting for a tram at a bustling city stop. Bright paper work style with layered depth and details. Stylized adult figures in modern clothing holding coffee cups, a detailed paper-crafted tram approaching in the mid-ground, cobblestone streets, and layered city buildings in the background. Vibrant colors, intricate cut-out patterns, and dramatic lighting casting distinct paper-layer shadows. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Morning Tram Wait"

queue_job 23 \
  "Urban life 2d paper-cut art of a lively outdoor street food market in a city square. Bright paper work style with layered depth and details. Adult vendors and customers interacting around wooden stalls, layered paper awnings in bright reds and yellows, hanging string lights, and a detailed cobblestone ground. Rich textures, overlapping paper elements to create deep parallax, and vibrant, cheerful lighting. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Bustling Weekend Market"

queue_job 24 \
  "Urban life 2d paper-cut art of adults enjoying a lunch break in a city park. Bright paper work style with layered depth and details. Layered paper trees with intricate leaf cut-outs, park benches with stylized adult figures reading or eating, a winding paper-crafted path, and a backdrop of geometric city skyscrapers. Vivid greens, blues, and warm sunlight effects achieved through layered translucent paper aesthetics. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Urban Park Lunch Break"

queue_job 25 \
  "Urban life 2d paper-cut art of a cozy corner diner in a bustling city at night. Bright paper work style with layered depth and details. Adult patrons sitting at the counter, a detailed paper-crafted jukebox, checkered floor, large window showing a layered city street outside with glowing streetlamps. High contrast, vibrant warm interior lights against cool blue exterior paper layers, intricate cut-out details creating rich visual depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "Qwen 3.8 Max" "Midnight Corner Diner"


# --- GLM 5.3 Max ---
queue_job 26 \
  "Vibrant 2D paper-cut art of a retro drive-in fast food restaurant at dusk, adults in vintage cars ordering from window speakers, a roller-skating server delivering a tray, neon \"BURGERS\" sign glowing in layered pink and teal paper, chrome details cut from silver cardstock, palm trees in the background, layered depth of six or more stacked paper planes with soft drop shadows, bright saturated colored paper, crisp scissor-cut edges, intricate details on menus, headlights, and window frames. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Drive-In Diner at Dusk"

queue_job 27 \
  "Bright 2D paper-cut illustration of adults only waiting for a tram at a busy city stop: businesspeople with briefcases, a woman with headphones, a man reading a newspaper, a street musician with an accordion, overhead power lines strung across cut-paper rooftops, the tram approaching in warm yellow and red paper layers, layered depth with foreground passengers, midground tracks, and background apartment blocks, cheerful color palette, handcrafted kirigami feel, crisp cut edges, fine details in clothing folds, signage, and cobblestone texture. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Tram Stop, Morning Rush"

queue_job 28 \
  "Cheerful 2D paper-cut art scene of a bustling urban market street, adults browsing fruit stalls, a florist arranging bright paper flowers, a barista handing coffee through a kiosk window, striped awnings in red and white, hanging produce signs, layered depth of stacked stalls receding into the distance, vivid construction-paper colors with visible paper grain texture, sharp layered silhouettes casting subtle shadows between planes, rich micro-details in crates, price tags, bicycles, and café umbrellas. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Saturday Street Market"

queue_job 29 \
  "Layered 2D paper-cut artwork of adults socializing on a rooftop terrace café at sunset, couples at small tables with coffee cups, a waiter balancing a tray, string lights cut from golden paper, pigeons on the railing, distant skyscraper silhouettes in gradient blue and orange paper layers, layered atmospheric depth with seven receding city planes, bright warm palette, hand-cut paper collage aesthetic, crisp edges, intricate latticework railings, planters, and window details. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Rooftop Café at Sunset"

queue_job 30 \
  "Bright 2D paper-cut scene of a glowing late-night noodle stall on a city corner, adults seated on stools at a counter under a red paper lantern, steam rising in layered white cut-paper wisps, the cook ladling broth, a queue of customers under umbrellas, glowing shop signs in layered yellow and magenta paper, wet street reflections suggested by layered light-shape cutouts, strong layered depth from foreground stools to background buildings, vivid saturated palette, kirigami-style sharp cuts, dense detail in bowls, chopsticks, signage, and awning folds. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "GLM 5.3 Max" "Late-Night Noodle Stall"


# --- DeepSeek Think Search ---
queue_job 31 \
  "Urban life 2D paper-cut art, bright paper work, layered depth and details. A drive-in fast-food restaurant at dusk, adult customers in vintage cars ordering from a glowing menu board, a carhop on roller skates, neon signs, paper-cut trees and streetlights, stacked cardstock shadows, crisp cut edges, vivid colors. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Drive-In Paper-Cut Glow"

queue_job 32 \
  "Urban life 2D paper-cut art, bright paper work, layered depth and details. Adults only waiting for a tram at a city stop, holding coffee cups and briefcases, wearing coats, overhead wires, paper-cut buildings, morning sun, layered benches and tracks, bright paper collage, crisp shadows. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Tram Stop Morning Commute"

queue_job 33 \
  "Urban life 2D paper-cut art, bright paper work, layered depth and details. Adults only seated at a late-night diner counter beside a fast-food drive-in window, glowing signs, paper-cut stools, napkin holders, ketchup bottles, reflections in the window, layered depth with bright cut-paper colors. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Midnight Diner Counter"

queue_job 34 \
  "Urban life 2D paper-cut art, bright paper work, layered depth and details. Adults only on city rooftops hanging laundry between water towers and antennas, paper-cut skyline behind them, pigeons, potted plants, clotheslines, bright paper collage, layered depth and crisp shadows. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Rooftop Laundry Lines"

queue_job 35 \
  "Urban life 2D paper-cut art, bright paper work, layered depth and details. Adults only crossing a busy crosswalk during rush hour, paper-cut buses, taxis, traffic lights, storefronts, umbrellas, layered city depth, bright cut-paper colors, crisp edges. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "DeepSeek Think Search" "Crosswalk Rush Hour"


# --- MiniMax M3 ---
queue_job 36 \
  "A glowing mid-century drive-in fast food restaurant rendered in 2D paper-cut art style. Layered cardboard-colored cardstock in warm tangerine, mustard yellow, cherry red, and cream white, cut with crisp edges and stacked to create deep parallax depth. In the foreground, a chrome-trimmed convertible idles at the speaker post, the driver leaning toward the order box while a passenger holds a milkshake. Behind them, a row of tail-finned cars queues under a zig-zag roofline strung with paper lanterns. A jagged sign towers above with layered cut-out letters spelling the diner's name, flanked by a paper-cut milkshake and hamburger icon. A roller-skating carhop glides between cars carrying a tray. Streetlamps glow as small punched dots through the upper layers, casting layered shadows. Background layers show a highway overpass, distant drive-in movie screen, and a paper-cut moon with scalloped clouds. Bright, saturated paper palette, tactile depth, hand-cut folk-art feel. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Neon Drive-In at Dusk"

queue_job 37 \
  "A bustling urban tram stop at golden hour, depicted in 2D paper-cut art style. Stacked layers of construction paper in coral, sky blue, soft lavender, peach, butter yellow, and warm white create a deep, multi-tiered scene with crisp cut edges and visible paper grain. In the foreground, a line of adult commuters waits on a cobbled sidewalk: a man in a trench coat reading a folded newspaper, a woman in a beret clutching a paper grocery bag, a cyclist with a basket bike pausing at the curb, and an older gentleman leaning on a cane. Behind them, the broadside of an arriving streetcar rolls in on metal tracks, its windows glowing warm amber with tiny silhouettes of seated passengers. Overhead, a web of paper-cut trolley cables crisscrosses against a sunset sky punched with circular stars and crescent clouds. Background layers reveal layered tenement facades, a bakery with a striped awning, and a distant cathedral spire. A small paper-cut dog sits beside its owner. Bright, joyful palette, strong layered depth, folk-craft charm. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Waiting at the Tram Stop"

queue_job 38 \
  "A cozy neighborhood laundromat on a Saturday afternoon, told through 2D paper-cut art style. Brightly colored construction paper in mint green, lemon yellow, bubblegum pink, tangerine, cobalt blue, and cream stacked in deep, overlapping layers with hand-cut textures and crisp geometric silhouettes. Inside, a row of round-front washers hums along the back wall, each door a different pastel circle. In the foreground, an adult sits on a plastic chair reading a paperback, another folds a stack of towels on a folding table, a third peers into a dryer window. A string of paper pennants hangs overhead. Through the wide front window, the sidewalk outside is visible in additional layers: a newsstand, a fire hydrant, and a pigeon on the curb. Punched dots in the upper layer suggest dust motes in afternoon sun. Background shelves hold detergent boxes cut from patterned paper. Cheerful, lived-in, hand-cut folk-art feel with strong layered depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Inside the Corner Laundromat"

queue_job 39 \
  "A summer evening rooftop party between apartment buildings, expressed in 2D paper-cut art style. Hand-cut layers of construction paper in watermelon pink, sky teal, sunset orange, plum, marigold, and ivory create a deeply stacked scene with crisp silhouettes and rich tactile depth. In the foreground, a group of adults leans against a low brick parapet, mugs in hand, chatting over a string of paper-cut fairy lights. A small potted tomato plant, a folded lawn chair, and a portable speaker crowd the rooftop floor. A clothesline of sheets billows in the warm breeze on the right. Behind them, a chimneypot releases a curling cut-paper smoke trail. Farther back, neighboring rooftops layer into the distance: a pigeon coop, a satellite dish, a man watering tomato boxes, a woman reading on a chaise. The background sky fades through three layers — peach, lilac, deep blue — with a paper-cut moon and tiny punched-dot stars. Festive, intimate, folk-craft warmth with strong layered depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "MiniMax M3" "Rooftop Gathering"

queue_job 40 \
  "A busy downtown crosswalk during evening rush hour, captured in 2D paper-cut art style. Stacked layers of cardstock in saffron yellow, cobalt, vermilion, pistachio green, dusty rose, and cream are cut with crisp edges and arranged in deep overlapping tiers for maximum parallax depth. In the foreground, a sweep of white paper-cut crosswalk stripes cuts across the asphalt, with adult pedestrians mid-stride: a courier with a messenger bag, a woman in heels hailing a cab, a man in a suit checking his watch, a street vendor with a paper-cut pretzel cart. Behind them, a yellow taxi idles at the light, a delivery truck waits, and a cyclist threads between bumpers. Above the intersection, traffic lights dangle from a curved paper-cut cable, glowing as punched discs. Background layers reveal a wall of skyscrapers with hundreds of tiny lit windows cut as pinholes, a clock tower, a billboard, and the curved glass dome of a department store. A paper-cut pigeon perches on a lamppost. Vibrant, kinetic, hand-cut folk-art feel with rich layered depth. In the lower margin at the exact bottom center of the foreground, a solid black circle with a clearly legible white numeral \"7\" centered inside, set apart from the main subject." \
  "MiniMax M3" "The Crosswalk at Rush Hour"


echo "✅ All 40 jobs queued in scheduleri"
