#!/usr/bin/env bash
set -e

#MODEL="Diffusers/Qwen/Qwen-Image-2512 [25468b98e3]"   # ✅ fixed: added missing -

# ---- PROMPTS ----
# ---- PROMPT LIST ----
prompts=(
# 01 · Calligrapher Elderly Japanese woman, ~70s, calligrapher — ink brush at lower lip
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from deep charcoal to absolute black, concentrated heavily across the left and center. The far right edge reveals a close-up profile of an elderly Japanese woman in her seventies, facing left — only the outline of her face, the strong architecture of her cheekbone, and the silver-white fall of her upswept hair are visible. Her expression carries the stillness of a person who has long since made peace with silence. She holds a traditional Japanese fude calligraphy brush, its lacquered bamboo handle gripped loosely between her index and middle fingers, the soft ink-laden bristle tip resting delicately against the center of her lower lip. The faint sheen of black ink is barely visible on the bristle's edge. Typical studio low-key lighting with precision edge lighting traces the crown of her head, the ridge of her nose, the curve of her lower lip and jaw, and the gentle wrinkle lines of her hand — celebrating the texture and topography of aged skin while allowing all shadow areas to dissolve naturally into the background. The mood is ancient, meditative, and deeply reverential."
# 02 · NeurosurgeonMiddle-aged Nigerian woman, ~45s, neurosurgeon — surgical forceps at chin
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from dark slate to absolute black, with the heaviest mass of darkness occupying the left two-thirds. The far right edge introduces a close-up profile of a middle-aged Nigerian woman in her mid-forties, facing left — only the strong contour of her face, a sculptural cheekbone, and the edge of close-cropped natural hair are visible against the dark. Her gaze is internal, focused, the expression of someone visualizing a problem only she can see. She holds a pair of stainless steel surgical ring forceps — the closed tips resting firmly under her chin, the pivot joint level with her jaw, her fingers resting through the rings with clinical familiarity. The cold reflection of the steel instrument catches the edge light precisely. Studio low-key lighting with tight edge illumination outlines her forehead, the bridge of her nose, the full curve of her lips, and the sharp line of the instrument, showcasing the resilient texture of her dark skin, while the shadow side falls seamlessly into the black background. The tone is austere, brilliant, and electrifyingly composed."
# 03 · ArchitectYoung Polish woman, ~late 20s, architect — compass point at corner of lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep graphite to absolute black, pooling thickly on the left side and center of the frame. The far right edge reveals a close-up profile of a young Polish woman in her late twenties, facing left — only the clean line of her profile, the pale curve of her ear, and a loose strand of ash-blonde hair escaping from a bun are visible. Her expression is one of concentrated analysis, as though measuring something invisible. She holds a traditional drafting compass, its metal handle rising from her grip, the two legs closed together so that the fine brass pivot point rests lightly at the corner of her mouth where lip meets skin. Her fingers hold it the way a conductor holds a baton. Studio low-key lighting with refined edge illumination traces her brow, the sharp ridge of her nose, the compressed line of her lips, and the geometric cold glint of the brass instrument, while the unlit side of her face and hand dissolve entirely into the black. The mood is precise, architectural, and quietly formidable."
#04 · Jazz VocalistYoung Brazilian woman, ~30s, jazz musician — microphone head at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from dark warm brown to absolute black, massed across the left and center of the frame. The far right edge presents a close-up profile of a young Brazilian woman in her early thirties, facing left — only the sensuous curve of her profile, the fullness of her lips, and the voluminous coils of her natural hair silhouetted against the dark are discernible. Her expression is neither singing nor silence but the suspended moment between the two. She holds a vintage-style large-diaphragm dynamic microphone horizontally, the cylindrical steel mesh head pressed gently but deliberately against the center of her closed lips, fingers wrapped loosely around the body of the mic. The mic's grille reflects a thin crescent of edge light. Studio low-key lighting traces the peak of her forehead, the bridge of her nose, the dramatic fullness of her mouth, and the metal ridge of the microphone, celebrating the richness of her brown skin, while shadow envelops all else. The tone is suspended, cinematic, and achingly intimate"
# 05 · Watch RestorerMiddle-aged Swiss woman, ~50s, horologist — loupe pressed to eye, watchmaker's screwdriver at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep cool gray to absolute black, concentrated on the left and center of the frame. The far right edge reveals a close-up profile of a middle-aged Swiss woman in her early fifties, facing left — only the refined outline of her face, her reading glasses pushed up onto her forehead, and silver-streaked hair pinned neatly back are visible in the darkness. Her expression is that of a person accustomed to infinite patience with tiny things. She presses a brass jeweler's loupe firmly against her right eye with one hand; with the other, the flat blade of a precision watchmaker's screwdriver — barely 1.5mm wide — rests with casual authority against the curve of her upper lip, held between thumb and forefinger. Studio low-key lighting with pinpoint edge illumination traces her brow, the circular brass rim of the loupe, the ridge of her nose, the faint line of her lips, and the slender shaft of the screwdriver, its chrome steel catching a needle-thin highlight, while all shadows dissolve into pure black. The mood is exact, obsessive, and timelessly concentrated."
# 06 · Chess GrandmasterYoung Indian woman, ~mid 20s, chess grandmaster — queen chess piece at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from dark warm black to absolute black, densest on the left half and center of the frame. The far right edge introduces a close-up profile of a young Indian woman in her mid-twenties, facing left — only the clean arc of her profile, a long dark braid falling over one shoulder, and the delicate gold stud of an earring catching the edge light are visible. Her expression is remote and calculating, eyes focused somewhere far past the frame. She holds a full-sized tournament chess queen piece — ivory-white, its finial crown pointing upward — held between the pads of her thumb, index, and middle finger, its smooth base resting softly against the center of her lips. Studio low-key lighting traces her forehead, the straight ridge of her nose, the defined cupid's bow of her upper lip, and the polished dome of the chess piece, casting a faint reflected light back against her cheek, while her darker skin tones dissolve organically into the rich black background. The mood is strategic, regal, and unsettlingly still."
# 07 · GlassblowerOlder Mexican woman, ~60s, glassblower — blowpipe mouthpiece at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep warm black to absolute black, massed heavily across the left and center. The far right edge reveals a close-up profile of a Mexican woman in her early sixties, facing left — only the weathered and magnificent contour of her face, prominent cheekbones, deep-set eyes, and thick dark hair streaked with white are visible in profile. Her expression carries the confidence of a craft practiced for decades. The iron mouthpiece end of a glassblowing pipe — a narrow steel cylinder, worn smooth at the lips-end from years of use — is pressed against her slightly parted lips, her cheeks just barely hollowed in preparation for breath. Her fingers cradle the pipe with instinctive ease. Studio low-key edge lighting traces the sharp ridge above her brow, the strong arch of her nose, the parted lips, the cylindrical iron pipe, and the pronounced tendons of her hand, while the warm deep tones of her skin blend seamlessly into the black ground. The mood is elemental, commanding, and alive with latent heat."
# 08 · Marine BiologistYoung Australian Aboriginal woman, ~early 30s, marine biologist — glass pipette at lower lip
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep teal-black to absolute black, concentrated across the left and center. The far right edge reveals a close-up profile of a young Australian Aboriginal woman in her early thirties, facing left — only the strong and beautiful architecture of her profile, wide-set eyes, a generous mouth, and the tight coil of her dark hair caught in a knot are visible. Her expression holds a precise, curious intelligence. She holds a glass laboratory pipette at chest height — its slender transparent body rising diagonally from her grip, the tapered glass tip resting gently against the center of her lower lip, as if she is about to draw up a sample or is simply thinking. The glass is smooth and catching a single fine line of edge light along its length, nearly invisible until it catches. Studio low-key lighting traces the high point of her forehead, the wide bridge of her nose, the full lower lip where the glass rests, and the delicate length of the glass instrument, celebrating the deep richness of her skin tone, while all shadow flows naturally into pure black. The mood is oceanic in its calm — observational, sharp, and full of quiet wonder."
# 09 · CeramicistElderly Korean woman, ~75, ceramicist — loop trimming tool at lower lip
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from deep umber-black to absolute black, pooling densely across the left two-thirds and center of the frame. The far right edge reveals a close-up profile of an elderly Korean woman in her mid-seventies, facing left — only the deeply lined and magnificent contour of her face, the strong horizontal crease of her eyelid, and a loose knot of white hair are visible. Her expression is one of total absorption, the stillness of someone who has spent a lifetime listening to clay. She holds a loop trimming tool — a small wire-tipped instrument used to carve wet ceramics, its wooden handle gripped lightly between her fingers — with the curved stainless wire loop resting against the center of her lower lip, not pressing, merely touching, as though she is tasting the shape of a decision. Studio low-key lighting with exacting edge illumination traces the ridge of her brow, the deep furrow beside her nose, the fold of her upper lip, and the thin wire of the tool catching a near-invisible filament of highlight, while the profound texture of her aged skin — the landscape of a long craft life — is celebrated in every lit plane. All shadow dissolves without boundary into pure black. The mood is weathered, sovereign, and perfectly at rest."
# 10 · ConductorMiddle-aged Russian woman, ~50s, orchestral conductor — baton tip at upper lip
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep cool charcoal to absolute black, massed across the left side and center of the frame. The far right edge presents a close-up profile of a middle-aged Russian woman in her early fifties, facing left — only the imperious architecture of her profile, a high and wide Slavic forehead, and dark hair swept back with severe elegance are discernible against the dark. Her expression carries the authority of someone accustomed to silence falling when she raises her hand. She holds a white fiberglass orchestral baton — its narrow shaft angled slightly downward from her grip, the pointed tip resting with deliberate precision against the bow of her upper lip, steady as a metronome at rest. Her fingers hold the baton with the specific grip of decades of rehearsal. Studio low-key lighting traces the high plane of her forehead, the sharp bridge of her nose, the defined arch of her lips, and the white baton's taper catching a clean, cold highlight along its length, while all unlit surfaces merge into the absolute black ground. The mood is commanding, interior, and charged with the memory of sound."
# 11 · Tattoo ArtistYoung Filipina woman, ~late 20s, tattoo artist — rotary tattoo machine at chin
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep warm black to absolute black, concentrated heavily on the left and center. The far right edge reveals a close-up profile of a young Filipina woman in her late twenties, facing left — only the smooth curve of her profile, the soft geometry of her nose, and the dark fall of long straight hair are visible. Her expression is inward, private, the look of a person in the midst of a visual problem only they can solve. She holds a professional rotary tattoo machine — matte black aluminum body, slim and ergonomic — cradled in the practiced grip between her palm and fingers, the needle tip retracted and the front of the machine resting gently against the point of her chin, its weight supported there while she thinks. The machine's subtle metallic texture catches the edge light in broken facets. Studio low-key lighting with refined edge illumination traces the line of her jaw, the curve of her lower lip, the tip of her nose, and the angled body of the machine, celebrating the smooth luminosity of her skin, while shadows fall away cleanly into the black surround. The mood is creative, concentrated, and quietly electric."
# 12 · WeaverElderly Navajo woman, ~70s, traditional weaver — wooden weaving comb at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from red-tinged black to absolute black, dense and enveloping across the left half and center of the frame. The far right edge introduces a close-up profile of a Navajo elder in her mid-seventies, facing left — only the broad and majestic contour of her face, the deeply incised lines of a life outdoors, and thick silver-streaked hair parted in the center and pulled back are visible. Her expression carries the gravity of inherited knowledge. She holds a traditional wooden weaving comb — a flat, toothed tool carved from pale hardwood, worn smooth at its handle by years of use — pressed horizontally against her lips, the comb's edge resting at the center of her closed mouth, held lightly by both hands whose fingers interlace around it with natural ease. The pale wood catches the edge light differently from the dark surround. Studio low-key lighting traces her broad brow, the pronounced bridge of her nose, the strong line of her lips against the wood, and the carved edges of the comb, honoring the deep warmth of her complexion, while all shadow merges without seam into the pure black background. The mood is ancient, rooted, and quietly monumental."
# 13 · ViolinistYoung Colombian woman, ~mid 20s, concert violinist — bow tip at corner of lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep indigo-black to absolute black, filling the left side and center with uninterrupted dark. The far right edge reveals a close-up profile of a young Colombian woman in her mid-twenties, facing left — only the elegant line of her profile, the soft fullness of her lips, and the loose dark waves of her hair just visible at the edge are discernible. Her expression is that of someone suspended between two movements, the silence that is also music. She holds a full-length concert violin bow — pernambuco wood, the stick arching very slightly — with the tip of the bow, its ivory point, touching the right corner of her lips with featherlight precision, the rest of the bow disappearing into the darkness at the left of the frame. The ivory tip catches a single spot of edge light. Studio low-key lighting traces the curve of her forehead, the line of her nose, the soft bow of her upper lip and the pale ivory point resting there, and the faintest reflected luminosity on her warm brown cheek, while all shadow dissolves completely into pure black. The mood is suspended, lyrical, and breathlessly still."
# 14 · AcupuncturistMiddle-aged Chinese woman, ~45s, acupuncturist — silver acupuncture needle at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep neutral black to absolute black, massed without interruption across the left and center of the frame. The far right edge presents a close-up profile of a Chinese woman in her mid-forties, facing left — only the refined contour of her face, the clean geometry of her jaw, and dark hair pulled back at the nape of her neck are visible. Her expression is one of precise calm, the practiced stillness of someone whose hands must never tremble. She holds a single sterile acupuncture needle — its hair-thin silver shaft barely 0.25mm wide, the guide tube absent, the needle held with extraordinary delicacy between the very tips of her thumb and index finger — with the fine silver point resting perpendicularly against the center of her lower lip, perfectly still. The needle is almost invisible until it catches the edge light as a single luminous filament. Studio low-key lighting traces the high plane of her cheekbone, the sharp bridge of her nose, the fullness of her lips, and that single silver thread of highlight on the needle, while the smooth even tone of her skin absorbs and releases light with exceptional subtlety. All shadows fall into absolute black. The mood is surgical, serene, and tremblingly precise."
# 15 · Forensic ScientistYoung Scottish woman, ~early 30s, forensic scientist — stainless steel tweezers at upper lip
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep blue-gray to absolute black, pooling across the left two-thirds of the frame. The far right edge reveals a close-up profile of a young Scottish woman in her early thirties, facing left — only the strong and clean line of her profile, a faint scatter of freckles just visible on the lit edge of her cheek, and auburn hair pulled back tightly are discernible. Her expression is clinically focused, the look of someone reading evidence in invisible ink. She holds a pair of fine-tipped stainless steel laboratory tweezers — closed, the tips pinching together at a point — with the very end of the blades resting against the arch of her upper lip, held in a two-finger grip, the elbow of the tweezers pointing toward the camera. The stainless steel catches a long cold highlight along both blades. Studio low-key lighting traces the ridge of her brow, the fine line of her nose, the precise curve of her upper lip against the metal tips, and the pale warmth of her freckled skin, while the unlit side collapses into pure black without transition. The mood is analytical, cool-toned, and quietly relentless."
# 16 · Opera SingerElderly Italian woman, ~late 60s, opera singer — tuning fork at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space ranging from warm velvet black to absolute black, concentrated on the left and center with operatic weight. The far right edge reveals a close-up profile of an Italian woman in her late sixties, facing left — only the grand and expressive architecture of her face, the strong Roman nose, full lips, and silver hair arranged with theatrical elegance are visible. Her expression holds the complex gravity of someone who has sung grief and ecstasy in equal measure for forty years. She holds a steel tuning fork by its stem — the two tines of the fork just struck, still vibrating infinitesimally — with the rounded top of the stem pressed directly against the center of her closed lips, conducting the tone into her skull, the way singers do when testing pitch. Her fingers grip the stem with a performer's certainty. Studio low-key lighting traces the dramatic line of her brow, the bold bridge of her nose, the fullness of her lips closed against the fork, and the clean chrome of the instrument, while the warmth of Mediterranean skin glows in the edge light. All shadow falls into absolute black. The mood is magnificent, melancholic, and vibrating with memory."
# 17 · Fashion DesignerMiddle-aged Senegalese woman, ~40s, fashion designer — tailor's chalk at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep warm charcoal to absolute black, occupying the left side and center of the frame without break. The far right edge introduces a close-up profile of a Senegalese woman in her mid-forties, facing left — only the striking geometry of her profile, wide-set eyes, a sharply defined philtrum, and close-cropped natural hair are visible. Her expression is evaluative, the look of someone who sees a finished garment when others see raw cloth. She holds a flat triangular wedge of white tailor's chalk between two fingers, its sharp edge pressed sideways against her lower lip — the way a designer does when pausing mid-sketch, holding the chalk to their face while thinking. A faint powder ghost of white transfers at the point of contact. Studio low-key lighting traces the high arc of her forehead, the angular line of her nose, the clean definition of her lips, and the bright white triangle of chalk — a small brilliant shape against the darkness — while the deep richness of her skin catches the edge light with extraordinary luminosity. All shadow collapses into pure black. The mood is inventive, imperious, and visually acute."
# 18 · AstronomerYoung Iranian woman, ~late 20s, observational astronomer — red laser pointer at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep cool black to absolute black, filling the left side and center with uninterrupted void. The far right edge reveals a close-up profile of a young Iranian woman in her late twenties, facing left — only the thoughtful and precise line of her profile, a straight strong nose, and dark hair escaping loosely from behind her ear are visible. Her expression is navigational, as though she is plotting a path through something vast. She holds a cylindrical astronomy laser pointer — a black anodized aluminum pen-sized device used to trace constellations — with the blunt emitter end resting against the center of her upper lip, pointed inward, held loosely between two fingers while she thinks. There is no beam visible — just the cool matte black cylinder against her skin. Studio low-key lighting traces the smooth arc of her forehead, the clean bridge of her nose, the defined upper lip, and the matte surface of the pointer catching a faint edge reflection, while the warm olive tone of her skin glows at the edge against pure black shadow. The mood is searching, cosmically patient, and lit from within."
# 19 · LuthierMiddle-aged Argentinian woman, ~50s, violin maker — purfling tool at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep golden-brown black to absolute black, pooling across the left and center with the warmth of a workshop at dusk. The far right edge presents a close-up profile of an Argentinian woman in her early fifties, facing left — only the handsome and assured line of her profile, paint-flecked cheekbone, and dark hair threaded with silver tucked behind her ear are visible. Her expression is that of someone reconciling feel with theory, a craftsperson mid-decision. She holds a purfling cutter — a specialized lutherie hand tool with a short wooden handle and twin parallel steel blades used to inlay decorative channels around a violin top — the wooden handle cupped in her palm, the blade end resting with quiet weight against the side of her lower lip, her thumb along the spine of the tool. The pale wood of the handle catches the edge light warmly. Studio low-key lighting traces the strong line of her brow, the gentle convexity of her cheek in light, the parted lips against the tool handle, and the faint grain of the worn wood, while the shadow of her jaw and neck merge fluidly into pure black. The mood is tactile, devoted, and saturated with craft."
# 20 · NeuroscientistYoung Congolese woman, ~early 30s, neuroscientist — glass capillary tube at lips
"A dark-toned portrait photograph. The horizontal widescreen composition is highly dramatic and artistic, with at least 80% of the area being pure negative space from deep teal-tinged black to absolute black, massed across the left two-thirds of the frame. The far right edge reveals a close-up profile of a young Congolese woman in her early thirties, facing left — only the brilliant and composed line of her profile, high cheekbones, and densely coiled natural hair arranged in a loose crown are visible. Her expression holds a quality of suspended certainty, a hypothesis forming behind her eyes. She holds a borosilicate glass capillary tube — a thin transparent rod barely 1mm wide, used in electrophysiology and cell injection, gripped between her thumb and the side of her index finger — with the polished open end of the tube resting precisely against the center of her lower lip, parallel to the ground. The glass tube is nearly invisible in the darkness except for the single luminous line of edge light that runs its full length. Studio low-key lighting traces the arc of her forehead, the strong and sculpted line of her nose, the full lower lip against the glass tip, and the singular bright filament of the capillary's length, while the deep, velvety richness of her dark skin catches the edge light and gives back warmth. All shadow dissolves into pure black. The mood is extraordinary — precise, radiant, and on the edge of discovery."
	)
# ---- QUEUE JOBS ----
i=1
for prompt in "${prompts[@]}"; do
  printf "[QUEUE %02d] %s\n" "$i" "$prompt"
  json=$(jq -n \
    --arg prompt "$prompt" \
    --arg sampler "$SAMPLER" \
    --argjson steps $STEPS \
    --arg checkpoint "$MODEL" \
    --argjson cfg $CFG \
    --argjson ag $AG \
    --argjson w $WIDTH \
    --argjson h $HEIGHT \
    --argjson seed $SEED \
    '{
        sd_model_checkpoint: $checkpoint,
        prompt: $prompt,
        steps: $steps,
        cfg_scale: $cfg,
        pag_scale: $ag,
        width: $w,
        height: $h,
        sampler_name: $sampler,
        seed: $seed,
        batch_size: 1,
        n_iter: 1,
        save_images: true
    }')


  TASK_NAME="$(printf '%02d' $i) ${prompt:0:16}"
  ENCODED=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$TASK_NAME")

  curl -s -X POST "$SCHED?name=$ENCODED" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null


  ((i++))
done

echo "✅ All jobs queued in scheduler"
