#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Contemporary Couture from Gemini (global cultural fashion editorial)
# Source: https://wiki.liutyi.info/display/AI/Contemporary+Couture+from+Gemini
# Structure: 1 model (Gemini) × 40 prompts = 40 tasks total
# ---------------------------------------------------------------------------

# --- Gemini ---
queue_job  1 \
  "A ukrainian woman, slavic features, tall, athletic build, wears an oversized white linen blazer with deep-red cross-stitch embroidery on the sleeves over tech-fabric trousers, standing and looking off into the distance. Captured in a eye-level medium shot, with golden hour, soft illuminating the scene. The setting is a modern kyiv street with a brutalist concrete backdrop, rendered in a cinematic realism style with a color palette of crisp whites and deep madder red. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Kyiv Neo-Ethno"

queue_job  2 \
  "A nigerian man, deep mahogany skin, lean, muscular build, wears a silk bomber jacket featuring vibrant Yoruba adire patterns over tailored black joggers, leaning against a sleek car. Captured in a low-angle full body shot, with high-contrast sunlight illuminating the scene. The setting is the victoria island skyline among modern glass buildings, rendered in a editorial fashion style with a color palette of indigo, charcoal, and obsidian. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Lagos Street Luxe"

queue_job  3 \
  "A quechua woman, sun-kissed skin, petite, strong build, wears a cropped wool jacket with a neon-tinted geometric intarsia knit over high-waist denim, mid-stride, walking. Captured in a side-profile wide shot, with cool morning mist illuminating the scene. The setting is a cobbled street in cusco lined with modern cafes, rendered in a street photography style with a color palette of earthy ochre and neon fuchsia. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Andean Urbanist"

queue_job  4 \
  "A japanese man, sharp features, slender, graceful build, wears a technical rain-trench with a kimono-style wrap collar and minimalist obi-belt detail, adjusting a smartwatch. Captured in a close-up, chest up, with neon-diffused night light illuminating the scene. The setting is a shinjuku alleyway with wet pavement, rendered in a cyber-minimalism style with a color palette of slate gray and electric violet. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Tokyo Kimono-Core"

queue_job  5 \
  "A tuareg man, piercing eyes, wiry, tall build, wears an indigo-dyed denim duster coat with silver Berber-engraved buttons over slim cargo pants, one hand resting on his headwrap. Captured in a low-angle, heroic framing, with harsh desert noon shadows illuminating the scene. The setting is a modern solar farm in morocco, rendered in a national geographic chic style with a color palette of cobalt blue and sand beige. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Sahara Nomad"

queue_job  6 \
  "A indian woman, almond eyes, curvy, elegant build, wears a structured Nehru-collar vest in raw silk with gold zardosi piping over wide-leg linen pants, holding a transparent umbrella. Captured in a high-angle shot looking up, with soft, overcast rain light illuminating the scene. The setting is the sea-wall along marine drive, mumbai, rendered in a moody cinematic style with a color palette of teal, antique gold, and gray. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Mumbai Monsoon"

queue_job  7 \
  "A korean man, monolid eyes, lean, youthful build, wears a cropped jacket with jeogori-style ribbons and tech-mesh inserts over baggy tactical pants, sitting on a neon-lit bench. Captured in a three-quarter view, with cyberpunk pink and blue lighting illuminating the scene. The setting is the gangnam district at night, rendered in a k-fashion wave style with a color palette of pastel lavender and matte black. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Seoul Hanbok-Tech"

queue_job  8 \
  "A mexican woman, mestizo features, toned, expressive build, wears a leather biker jacket with intricate Huichol beadwork on the lapels over a pleated midi skirt, holding a confident power pose. Captured in a eye-level wide shot, with warm afternoon sun illuminating the scene. The setting is the courtyard of a contemporary art gallery, rendered in a vibrant realism style with a color palette of terracotta, turquoise, and black. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Mexico City Mural"

queue_job  9 \
  "A swedish man, fair skin, blonde, broad-shouldered build, wears a heavy knit sweater with subtle Viking knot-work textures under a charcoal wool overcoat, looking down at his phone. Captured in a candid medium shot, with flat, soft nordic winter light illuminating the scene. The setting is a stockholm subway station, rendered in a scandinavian minimalist style with a color palette of cream, navy, and steel. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Nordic Runes"

queue_job 10 \
  "A kenyan woman, shaved head, elegant, statuesque build, wears a red structural capelet with a beaded choker built into the collar over a slim-fit black bodysuit, standing tall with her chin up. Captured in a low-angle shot, with sunset backlighting illuminating the scene. The setting is a modern office balcony in nairobi, rendered in a high-end editorial style with a color palette of scarlet red, ebony, and gold. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Masai Modern"

queue_job 11 \
  "A brazilian man, indigenous features, athletic, tanned build, wears a utility vest with feather-patterned silk lining paired with recycled-plastic sneakers, crouched, looking directly at the camera. Captured in a ground-level wide angle, with dappled forest light illuminating the scene. The setting is a modern eco-resort in the jungle, rendered in a sustainable luxury style with a color palette of forest green and macaw orange. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Amazonian Pulse"

queue_job 12 \
  "A iranian woman, dark wavy hair, slender build, wears a long silk cardigan with paisley boteh motifs over a tailored white shirt and slim slacks, tucking her hair behind her ear. Captured in a close-up portrait, with soft window light illuminating the scene. The setting is a modern library in tehran, rendered in a sophisticated chic style with a color palette of rosewater pink, cream, and gold. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Persian Pattern"

queue_job 13 \
  "A maori man, facial moko details, burly, powerful build, wears a black wool peacoat with tonal charcoal ta moko embroidery on the shoulders, standing with arms crossed. Captured in a eye-level medium shot, with dramatic chiaroscuro lighting illuminating the scene. The setting is the auckland waterfront among metal docks, rendered in a gritty cinematic style with a color palette of monochrome tones and ink black. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Maori Edge"

queue_job 14 \
  "A thai woman, petite, graceful build, wears a one-shoulder modern top made of iridescent Thai silk over oversized trousers, caught mid-turn, graceful movement. Captured in a dynamic movement shot, with warm, studio-style sun illuminating the scene. The setting is the cloud 47 rooftop in bangkok, rendered in a glamour streetwear style with a color palette of magenta, copper, and bronze. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Thai Silk Street"

queue_job 15 \
  "A mongolian man, high cheekbones, robust build, wears a modern deel-cut leather trench with a fur-lined collar and heavy combat boots, leaning on a metal railing. Captured in a profile shot, with golden hour, side-lit illuminating the scene. The setting is a modern district in ulaanbaatar, rendered in a rugged luxury style with a color palette of burnt sienna and dark chocolate. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Mongolian Steppe"

queue_job 16 \
  "A algerian woman, curly hair, slim, stylish build, wears a modern burnous-inspired hooded wool coat with gold filigree jewelry over denim, walking through a crowd. Captured in a shallow depth of field, with soft city twilight illuminating the scene. The setting is a parisian cafe terrace, rendered in a european chic style with a color palette of emerald green and cream. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Parisian Maghreb"

queue_job 17 \
  "A tibetan man, weathered skin, lean build, wears a padded down jacket with traditional brocade panels and modern mountain boots, looking up at the sky. Captured in a low-angle wide shot, with bright, thin mountain light illuminating the scene. The setting is modern architecture in lhasa, rendered in a adventure fashion style with a color palette of saffron yellow and deep crimson. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Tibetan High"

queue_job 18 \
  "A vietnamese woman, straight hair, delicate build, wears a modernized ao dai slit-top worn over flared jeans with silk embroidery, biking on a scooter. Captured in a side profile with motion blur, with mid-day bright light illuminating the scene. The setting is ho chi minh city traffic, rendered in a urban vitality style with a color palette of lotus pink and denim blue. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Vietnamese Flow"

queue_job 19 \
  "A ethiopian woman, habesha features, tall, slim build, wears a white cotton dress with netela-style woven borders and modern leather sandals, sitting gracefully. Captured in a eye-level medium shot, with warm, diffused interior light illuminating the scene. The setting is a modern lounge in addis ababa, rendered in a ethnic minimalist style with a color palette of off-white with vibrant border accents. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Ethiopian Grace"

queue_job 20 \
  "A kazakh man, central asian features, athletic build, wears a suede bomber jacket with silver felted koshkar-muiz patterns over dark jeans, standing by a horse statue. Captured in a three-quarter view, with cold sunset light illuminating the scene. The setting is the glass architecture of astana, rendered in a neo-nomad style with a color palette of slate, silver, and tan. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Kazakh Nomad"

queue_job 21 \
  "A scottish man, red beard, stocky build, wears a tailored blazer in modern grey tartan with utility kilt-shorts and heavy boots, walking toward the camera. Captured in a eye-level full body shot, with moody, overcast sky illuminating the scene. The setting is edinburgh's royal mile, rendered in a heritage punk style with a color palette of heather purple and forest green. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Scottish Highland"

queue_job 22 \
  "A balinese woman, tan skin, lithe build, wears a batik-patterned silk wrap-around skirt with a structured white corset top, caught mid-dance. Captured in a dynamic low angle, with dappled sun filtering through leaves illuminating the scene. The setting is the garden of a modern bali villa, rendered in a tropical elegance style with a color palette of indigo and canary yellow. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Balinese Breeze"

queue_job 23 \
  "A native american man, long hair, strong build, wears a modern denim jacket with a woven southwestern geometric back panel and a turquoise ring, fixing a cufflink. Captured in a close-up on hands and torso, with warm sunset light illuminating the scene. The setting is a desert highway beside a modern truck, rendered in a americana neo-trad style with a color palette of sand, turquoise, and denim. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Navajo Weaver"

queue_job 24 \
  "A saudi woman, expressive eyes, slender build, wears an open-style silk abaya with metallic embroidery over high-waist trousers and sneakers, walking with confidence. Captured in a low-angle wide shot, with bright, harsh desert sun illuminating the scene. The setting is the king abdullah financial district, rendered in a futuristic modest style with a color palette of sand gold and pearl white. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Abaya Evolution"

queue_job 25 \
  "A greek man, olive skin, athletic build, wears a linen tunic-shirt with Greek key meander embroidery on the hem over white chinos, looking out to sea. Captured in a wide shot from behind, with harsh midday sun illuminating the scene. The setting is a blue-domed village in santorini, rendered in a mediterranean chic style with a color palette of aegean blue and crisp white. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Greek Odyssey"

queue_job 26 \
  "A south african man, dark skin, muscular build, wears a modern knit polo with geometric Zulu beadwork patterns over tailored shorts, sitting on a concrete wall. Captured in a medium shot, with vibrant afternoon sun illuminating the scene. The setting is the maboneng district of johannesburg, rendered in a afro-futurism style with a color palette of orange, black, and yellow. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Zulu Modernity"

queue_job 27 \
  "A inuit woman, round face, petite build, wears a high-tech parka with traditional sealskin-inspired patterns over thermal leggings, facing into the wind. Captured in a close-up with snowy lashes, with cold blue-hour light illuminating the scene. The setting is a modern arctic research station, rendered in a technical survival style with a color palette of ice blue, ivory, and grey. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Inuit Tech"

queue_job 28 \
  "A egyptian man, sharp jawline, lean build, wears a black linen suit with minimalist gold ankh-inspired hardware and sunglasses, walking down stairs. Captured in a high-angle shot, with golden hour illuminating the scene. The setting is the exterior of the cairo grand museum, rendered in a luxury noir style with a color palette of obsidian and metallic gold. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Egyptian Gold"

queue_job 29 \
  "A samoan man, tattooed arms, large, powerful build, wears a short-sleeve shirt with tribal tatau prints over cargo trousers and sandals, standing with hands in pockets. Captured in a eye-level full body shot, with soft tropical twilight illuminating the scene. The setting is a modern pacific resort, rendered in a island urban style with a color palette of brown, black, and cream. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Samoan Power"

queue_job 30 \
  "A filipina woman, glowing skin, slender build, wears a barong-inspired sheer organza jacket with floral embroidery over a black bralette, adjusting her earrings. Captured in a close-up portrait, with soft studio light illuminating the scene. The setting is a creative studio in manila, rendered in a ethereal modern style with a color palette of translucent cream and black. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Philippine Piña"

queue_job 31 \
  "A romanian woman, pale skin, athletic build, wears a cropped leather vest over a blouse with traditional puffed sleeves and black embroidery, standing in a field. Captured in a wide shot, with soft sunrise light illuminating the scene. The setting is a modern wooden cabin, rendered in a folk-fusion style with a color palette of black, white, and poppy red. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Romanian Folk"

queue_job 32 \
  "A jamaican man, dreadlocks, lean build, wears a vibrant linen shirt in madras check over tailored white trousers, leaning against a wall. Captured in a low-angle medium shot, with warm golden sunlight illuminating the scene. The setting is a street-art wall in kingston, rendered in a reggae sophisticate style with a color palette of red, gold, and green. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Caribbean Rhythm"

queue_job 33 \
  "A chinese man, refined features, slender build, wears a modern qipao-collar suit jacket in silk jacquard fabric with slim-fit trousers, holding a tablet. Captured in a three-quarter view, with cool office lighting illuminating the scene. The setting is a skyscraper office in shanghai, rendered in a corporate orientalism style with a color palette of jade green and charcoal. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Chinese Silk-Road"

queue_job 34 \
  "A finnish woman, icy blue eyes, tall, slender build, wears a heavy wool coat with bold Marimekko-style graphic prints and a chunky scarf, wrapped in her scarf. Captured in a close-up, with overcast, snowy light illuminating the scene. The setting is the helsinki design district, rendered in a graphic minimalism style with a color palette of black, white, and bold red. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Finnish Frost"

queue_job 35 \
  "A turkish woman, hazel eyes, curvy build, wears a velvet blazer with Ottoman-style gold bullion embroidery over wide-leg silk pants, sipping coffee. Captured in a eye-level medium shot, with warm cafe lighting illuminating the scene. The setting is a rooftop in istanbul's galata district, rendered in a opulent urban style with a color palette of deep burgundy and gold. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Turkish Velvet"

queue_job 36 \
  "A aboriginal man, dark skin, wiry, strong build, wears a modern duster coat with a subtle dot-art lining, a wide-brim hat, and denim, looking out at the horizon. Captured in a wide profile shot, with red sunset light illuminating the scene. The setting is a modern desert observatory, rendered in a rugged heritage style with a color palette of ochre and burnt orange. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Australian Outback"

queue_job 37 \
  "A portuguese woman, olive skin, slim build, wears a white denim jacket with a blue tile-print azulejo motif on the back over blue jeans, looking back over her shoulder. Captured in a back-view medium shot, with soft coastal light illuminating the scene. The setting is lisbon's alfama district, rendered in a mediterranean pop style with a color palette of cobalt blue and white. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Portuguese Azulejo"

queue_job 38 \
  "A jordanian man, bearded, tall build, wears a modernized shemagh scarf worn as a cowl over a technical windbreaker and black pants, standing atop a sand dune. Captured in a long shot, with sunset silhouette lighting illuminating the scene. The setting is a modern camp in wadi rum, rendered in a tech-nomad style with a color palette of khaki, black, and red. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Jordanian Desert"

queue_job 39 \
  "A aymara woman, braids, short, strong build, wears a modern structural bolero jacket with a tiered silk skirt and contemporary jewelry, standing with hands on her hips. Captured in a low-angle shot, with mid-day sun illuminating the scene. The setting is the cable car station in la paz, rendered in a high-altitude chic style with a color palette of violet, emerald, and gold. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Bolivian Bowler"

queue_job 40 \
  "A icelandic man, rugged, broad build, wears a lopapeysa-inspired modern fleece jacket with waterproof trousers and hiking boots, standing on black volcanic sand. Captured in a wide shot, with moody, dramatic grey sky illuminating the scene. The setting is reynisfjara black sand beach, rendered in a volcanic technical style with a color palette of charcoal, ash grey, and white. Aesthetically pleasing, highly detailed, professional contemporary fashion photography, sharp focus, sophisticated composition." \
  "Gemini" "Icelandic Lava"

echo "✅ All 40 jobs queued in scheduler"
