#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="Diffusers/Qwen/Qwen-Image-2512 [25468b98e3]"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

queue_job() {
  local index="$1"
  local prompt="$2"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:       $prompt,
      steps:        $steps,
      cfg_scale:    $cfg,
      pag_scale:    $ag,
      width:        $w,
      height:       $h,
      sampler_name: $sampler,
      seed:         $seed,
      batch_size:   1,
      n_iter:       1,
      save_images:  true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Source: https://wiki.liutyi.info/display/AI/Contemporary+Couture+with+Traditional+Motifs
# Structure: Women (6 rows × 7 countries = 42) + Men (5 rows × 7 countries = 35) = 77 total
# Order: row by row, left to right within each section
# Bold Confluence markers (**LABEL:**) normalised to plain LABEL: throughout
# ---------------------------------------------------------------------------
prompts=()

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 1
# ════════════════════════════════════════════════════════════════════════════

# 01 · Japan / Neo-Kimono Power — Shibuya Crossing (Full Body)
prompts+=( "Neo-Kimono Power — Shibuya Crossing (Full Body). SUBJECT: Japanese female model, sharp elegant facial features, porcelain skin, confident direct gaze, visible face, sleek straight black hair. BODY: Tall slender silhouette, poised upright stance. CLOTHING: Structured midnight-black tailored long coat inspired by kimono sleeve proportions, subtle wide sleeve opening reinterpretation, defined modern waist structure, deep crimson silk inner lining visible in movement, fitted high-neck charcoal base layer, sharply tailored ankle-length trousers with clean vertical crease, pointed black leather heels, minimal obi-inspired waist belt in matte leather, refined embroidery detail along inner seam inspired by traditional Japanese wave motifs, premium wool-silk blend fabric with visible texture, architectural contemporary tailoring. POSE: Walking forward mid-step, coat slightly flowing. CAMERA VIEW: Full body shot, slight low angle, 50mm lens. LIGHTING: Neon city reflections with cool evening glow. SCENE: Shibuya Crossing at dusk with blurred lights. STYLE: High-fashion urban Japanese couture editorial. COLOR-TONE: Midnight black, crimson accents, cool neon reflections." )

# 02 · Korean / Seoul Hanok District Modernized Hanbok Power Look
prompts+=( "Seoul Hanok District Modernized Hanbok Power Look. SUBJECT: South Korean woman in her late 20s with sharp jawline, porcelain skin, almond eyes, sleek black hair tied in a low architectural bun, confident gaze toward camera. BODY: Tall, lean runway proportions, elegant posture, refined hands, poised yet powerful stance. CLOTHING: Avant-garde reinterpretation of hanbok — structured cropped jeogori-inspired jacket in matte ivory neoprene with exaggerated angular shoulders, sheer organza long sleeves embroidered with subtle crane motifs in silver thread, high-waisted tailored black silk trousers with flowing asymmetrical overskirt panel mimicking traditional chima silhouette, wide obi-style belt in metallic gunmetal leather with minimalist knot detail, pointed satin ankle boots, delicate norigae charm reimagined as chrome sculptural accessory, modern minimalist silver ear cuffs. POSE: Standing upright mid-step on stone pavement, one hand lightly adjusting belt, chin slightly lifted, direct eye contact. CAMERA VIEW: Full body shot, slightly low angle for power effect. LIGHTING: Soft golden hour light with gentle side highlights. SCENE: Bukchon Hanok Village alley in Seoul, traditional tiled rooftops behind her, contrast between heritage architecture and modern couture. STYLE: High-fashion editorial, Korean couture reinterpretation, crisp details. COLOR-TONE: Neutral ivory, black, silver accents, warm golden highlights." )

# 03 · Philippines / Manila — Modern Terno Power Couture
prompts+=( "Manila — Modern Terno Power Couture. SUBJECT: Filipina woman late 20s, warm golden-brown skin, defined cheekbones, long sleek black hair, expressive dark brown eyes, confident direct gaze at camera. BODY: Tall, elegant runway posture, shoulders back. CLOTHING: Contemporary reinterpretation of the traditional terno — structured ivory silk gown with modern sculptural butterfly sleeves, sharply tailored bodice, high-waisted fitted silhouette, subtle embroidered floral patterns inspired by Filipino heritage motifs along sleeves and hem, wide satin belt in deep navy, minimalist pearl earrings, pointed metallic heels, structured clutch in matching silk. POSE: Standing upright with one hand resting lightly at waist, chin lifted. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright tropical daylight with soft architectural reflections. SCENE: Manila modern skyline with glass buildings and city energy. STYLE: Luxury Filipino couture editorial. COLOR-TONE: Ivory, navy accents, warm tropical light." )

# 04 · India / Crimson Heritage Power — Mumbai Skyline (Full Body)
prompts+=( "Crimson Heritage Power — Mumbai Skyline (Full Body). SUBJECT: Indian female model, warm brown skin tone, defined cheekbones, expressive dark eyes, visible face, sleek long black hair. BODY: Tall elegant silhouette, confident upright stance. CLOTHING: Structured deep crimson tailored long coat with subtle sari-inspired drape panel integrated along one side, sculpted shoulders, defined waistline, fitted high-neck black silk blouse underneath, sharply tailored ankle-length trousers with clean crease, pointed leather heels in deep maroon, minimal gold choker necklace, delicate embroidered border detail inspired by traditional zari work along coat hem, premium silk-wool blend fabric with rich texture, architectural couture tailoring blending heritage and modern power dressing. POSE: Standing facing camera, shoulders squared, one leg slightly forward. CAMERA VIEW: Full body shot, slight low angle, 50mm lens. LIGHTING: Warm golden sunset light with soft glow. SCENE: Mumbai skyline promenade with Arabian Sea in background. STYLE: High-fashion contemporary Indian couture editorial. COLOR-TONE: Crimson red, deep maroon, warm golden light." )

# 05 · Brazil / Rio de Janeiro — Modern Carnival Couture
prompts+=( "Rio de Janeiro — Modern Carnival Couture. SUBJECT: Brazilian woman late 20s, sun-kissed skin, high cheekbones, voluminous dark wavy hair, luminous brown eyes, confident radiant gaze directly at camera. BODY: Tall, sculpted runway proportions, strong yet feminine posture. CLOTHING: Contemporary couture reinterpretation of Carnival elements — structured emerald corset with subtle feather-textured embroidery, high-waisted flowing silk skirt with asymmetrical hem in vibrant turquoise and gold, sheer organza cape with delicate beadwork inspired by samba costumes but refined and minimal, wide metallic gold belt with sculptural curves, strappy metallic heels, statement ear cuffs shaped like abstract tropical leaves, subtle crystal detailing along neckline. POSE: Standing upright with shoulders back, one leg slightly forward, cape catching wind. CAMERA VIEW: Full body shot, slightly low angle for dramatic presence. LIGHTING: Golden sunset light with warm highlights and soft glow. SCENE: Overlook near Christ the Redeemer in Rio de Janeiro with city skyline and mountains behind. STYLE: High-fashion editorial, elevated Carnival couture. COLOR-TONE: Emerald, turquoise, gold, warm sunset tones." )

# 06 · Sweden / Stockholm Archipelago Minimalist Folk Couture
prompts+=( "Stockholm Archipelago Minimalist Folk Couture. SUBJECT: Swedish woman late 20s, pale skin with natural glow, light freckles, sharp cheekbones, icy blue eyes, long straight blonde hair flowing naturally, calm confident gaze directly at camera. BODY: Tall, lean Scandinavian proportions, elegant posture, relaxed shoulders. CLOTHING: Modern reinterpretation of traditional Swedish folk dress — structured deep navy wool coat inspired by folk bodice silhouette, tailored high-waisted ivory wide-leg trousers, crisp white high-neck blouse with subtle embroidered floral patterns in muted red and blue referencing traditional Dalarna motifs, wide leather belt with brushed silver buckle engraved with Nordic pattern, knee-high matte leather boots, minimalist silver drop earrings shaped like abstracted midsummer wreath leaves, small structured crossbody bag in soft tan leather. POSE: Standing firmly on rocky shoreline, one hand lightly holding coat lapel, chin slightly lifted. CAMERA VIEW: Full body shot, slightly low angle for strength. LIGHTING: Soft northern daylight with cool crisp highlights. SCENE: Stockholm archipelago rocky coast with Baltic Sea in background. STYLE: High-fashion Scandinavian editorial, clean minimal lines. COLOR-TONE: Cool navy, ivory, muted red accents, soft blue daylight." )

# 07 · Nigeria / Lagos — Modern Ankara Power Couture
prompts+=( "Lagos — Modern Ankara Power Couture. SUBJECT: Nigerian woman late 20s, deep brown skin glowing, high cheekbones, natural textured hair styled in a sculptural updo, bold confident gaze directly at camera. BODY: Tall, statuesque runway proportions, strong elegant posture. CLOTHING: Contemporary tailored power suit in vibrant Ankara fabric with geometric wax print in cobalt blue and burnt orange, sharply structured blazer with exaggerated shoulders, cinched waist with wide leather belt in deep brown, high-waisted wide-leg trousers with crisp pleats, silk high-neck blouse in ivory underneath, pointed leather heels, statement gold earrings inspired by traditional Benin motifs, structured mini handbag in matching Ankara pattern. POSE: Standing firmly with feet slightly apart, one hand resting on belt, chin lifted. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright Lagos daylight with soft urban reflections. SCENE: Modern Lagos business district with glass high-rises. STYLE: High-fashion urban couture editorial. COLOR-TONE: Cobalt blue, burnt orange, ivory accents, warm sunlight." )

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 2
# ════════════════════════════════════════════════════════════════════════════

# 08 · Japan / Sakura Minimal — Meguro River (Three-Quarter)
prompts+=( "Sakura Minimal — Meguro River (Three-Quarter). SUBJECT: Soft refined Japanese facial features, calm confident eyes, visible face, natural makeup. BODY: Slim graceful posture. CLOTHING: Structured pale blush tailored blazer with subtle curved lapel inspired by kimono overlap lines, lightweight ivory silk blouse with soft drape, high-waisted wide-leg trousers in soft beige, delicate obi-style waist ribbon detail in muted pink silk, pointed nude leather heels, refined breathable fabrics, subtle sakura petal embroidery detail near cuff, clean minimalist tailoring with heritage influence. POSE: Standing near railing, shoulders gently angled. CAMERA VIEW: Three-quarter shot, 85mm lens shallow depth. LIGHTING: Soft spring daylight, diffused natural glow. SCENE: Meguro River during cherry blossom season. STYLE: Elegant contemporary Japanese editorial. COLOR-TONE: Blush pink, ivory, soft beige, pastel atmosphere." )

# 09 · Korean / Seoul Subway Minimal Futurism
prompts+=( "Seoul Subway Minimal Futurism. SUBJECT: South Korean woman early 30s, sharp bob haircut, natural makeup, focused gaze, subtle intensity in eyes. BODY: Slim, athletic build, upright posture. CLOTHING: Modern monochrome hanbok-inspired ensemble — oversized charcoal structured coat with subtle jacquard cloud pattern, wide cropped trousers in structured wool, asymmetrical wrap top referencing jeogori closure in matte silk, sleek leather harness belt with engraved Hangul typography, knee-high leather boots, structured mini bag shaped like folded hanji paper, minimalistic geometric earrings. POSE: Standing on subway platform, one hand in coat pocket, other holding bag, looking directly at camera. CAMERA VIEW: Three-quarter body shot, eye-level. LIGHTING: Cool fluorescent subway lighting with slight cinematic contrast. SCENE: Seoul subway platform with clean architectural lines and platform screen doors. STYLE: Urban couture, futuristic minimalism, street editorial. COLOR-TONE: Charcoal gray, matte black, cool blue undertones." )

# 10 · Philippines / Vigan — Contemporary Baro't Saya Elegance
prompts+=( "Vigan — Contemporary Baro't Saya Elegance. SUBJECT: Filipina woman early 30s, smooth tan skin, soft wavy hair pinned back, calm poised gaze directly at camera. BODY: Graceful elongated silhouette. CLOTHING: Modern reinterpretation of baro't saya — sheer piña-inspired blouse with delicate hand-embroidered floral detailing, structured high-waisted satin skirt in muted gold, dramatic contemporary belt in deep burgundy leather, sheer layered overskirt panel for movement, minimalist gold drop earrings, pointed heels in dark wine tone. POSE: Standing confidently on cobblestone street, shoulders relaxed but upright. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Soft late afternoon sunlight casting warm glow. SCENE: Historic Vigan street with Spanish colonial architecture. STYLE: Romantic heritage couture editorial. COLOR-TONE: Muted gold, burgundy, warm stone neutrals." )

# 11 · India / Ivory Palace Modern — Jaipur City Palace (Three-Quarter)
prompts+=( "Ivory Palace Modern — Jaipur City Palace (Three-Quarter). SUBJECT: Indian woman with refined facial features, calm confident gaze, visible face, soft natural makeup. BODY: Slim graceful posture. CLOTHING: Structured ivory tailored jacket with subtle curved neckline inspired by lehenga choli silhouette, delicate gold thread embroidery detailing along cuffs and collar, fitted silk blouse in soft champagne tone, high-waisted wide-leg tailored trousers in sand color with fluid drape, pointed heels in metallic gold, refined silk-linen blend texture, elegant heritage reinterpretation with clean contemporary tailoring lines. POSE: Standing slightly angled, hands relaxed at sides. CAMERA VIEW: Three-quarter shot, eye-level. LIGHTING: Bright natural daylight with soft shadow contrast. SCENE: City Palace Jaipur courtyard. STYLE: Contemporary royal-inspired couture editorial. COLOR-TONE: Ivory, champagne gold, warm sandstone tones." )

# 12 · Brazil / Salvador — Afro-Brazilian Heritage Modern Elegance
prompts+=( "Salvador — Afro-Brazilian Heritage Modern Elegance. SUBJECT: Afro-Brazilian woman early 30s, deep brown skin glowing in sunlight, natural textured hair styled in sculptural updo, strong direct eye contact. BODY: Graceful yet powerful stance, elongated silhouette. CLOTHING: Modern reinterpretation of Bahian traditional attire — structured white silk blouse with exaggerated puff sleeves referencing baiana dress, high-waisted tailored wide-leg trousers in ivory satin, layered minimalist bead necklaces inspired by Candomblé jewelry but refined, wide gold waistpiece with engraved organic motifs, pointed white heels, subtle lace trim details along cuffs. POSE: Standing confidently with hands gently resting at sides, chin slightly lifted. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Bright tropical daylight with soft shadow definition. SCENE: Pelourinho historic district in Salvador with colorful colonial buildings. STYLE: Luxury cultural couture editorial. COLOR-TONE: Ivory, gold, warm pastel architectural backdrop." )

# 13 · Sweden / Gamla Stan Structured Nordic Elegance
prompts+=( "Gamla Stan Structured Nordic Elegance. SUBJECT: Swedish woman early 30s, sleek blonde bob, minimal makeup, piercing grey-blue eyes, composed expression looking at camera. BODY: Slim, elongated silhouette, refined stance. CLOTHING: Tailored charcoal structured blazer with subtle woven folk-inspired jacquard texture, high-waisted black wool trousers, silk blouse with delicate embroidered ribbon detail at collar inspired by Swedish folk costume neckties, slim leather gloves tucked into belt, pointed black ankle boots, minimalist gold ear cuffs, structured handbag in deep forest green leather. POSE: Walking mid-step on cobblestone street, coat slightly moving, confident stride. CAMERA VIEW: Three-quarter full body shot, eye-level. LIGHTING: Soft overcast Scandinavian light, diffused and flattering. SCENE: Gamla Stan cobblestone street in Stockholm with colorful historic buildings. STYLE: Modern Nordic couture editorial. COLOR-TONE: Charcoal, forest green, muted gold accents, cool neutral background." )

# 14 · Nigeria / Abuja — Regal Aso Oke Reinterpretation
prompts+=( "Abuja — Regal Aso Oke Reinterpretation. SUBJECT: Nigerian woman early 30s, rich dark skin tone, defined brows, elegant oval face, sleek pulled-back hair, steady direct gaze. BODY: Graceful elongated silhouette. CLOTHING: Luxury reinterpretation of Aso Oke — structured floor-length gown in deep emerald woven textile with subtle metallic thread, sculptural off-shoulder neckline, fitted corset bodice, dramatic pleated overskirt panel, wide metallic gold waistpiece, minimalist gold cuffs, refined pointed heels, small clutch in matching woven fabric. POSE: Standing upright with shoulders back, hands relaxed at sides. CAMERA VIEW: Full body centered composition. LIGHTING: Soft diffused daylight with subtle highlights on woven texture. SCENE: Abuja civic plaza with clean modern architecture. STYLE: Luxury heritage couture editorial. COLOR-TONE: Emerald green, gold accents, soft neutral stone background." )

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 3
# ════════════════════════════════════════════════════════════════════════════

# 15 · Japan / Kyoto Modern Grace — Gion District (Cowboy Shot)
prompts+=( "Kyoto Modern Grace — Gion District (Cowboy Shot). SUBJECT: Japanese woman with delicate features, composed gaze, visible face, smooth dark hair styled neatly. BODY: Straight elegant posture. CLOTHING: Deep indigo structured midi coat-dress inspired by traditional kimono silhouette, modernized clean neckline, wide statement sleeves with subtle lining contrast, defined waist with minimal fabric belt, smooth silk inner panel detail, tailored below-knee cut, pointed dark navy heels, fine woven textile texture referencing traditional Japanese dye techniques, precise seam construction. POSE: Standing calmly with hands relaxed at sides. CAMERA VIEW: Cowboy shot, eye-level. LIGHTING: Warm late afternoon light with soft shadow depth. SCENE: Gion historic street with wooden architecture. STYLE: Contemporary heritage couture photography. COLOR-TONE: Indigo blue, warm wood tones, soft golden highlights." )

# 16 · Korean / Busan Coastal Wind Couture
prompts+=( "Busan Coastal Wind Couture. SUBJECT: South Korean woman mid-20s, long flowing black hair moving in wind, radiant skin, expressive eyes looking confidently at camera. BODY: Graceful, elongated silhouette. CLOTHING: Flowing contemporary chima-inspired maxi skirt in deep navy silk chiffon layered over structured shorts, cropped structured white jacket with subtle traditional embroidery along cuffs, translucent silk inner blouse with delicate floral patterns, wide structured belt with lacquered finish, statement pearl drop earrings, minimalist strappy heels, silk ribbon hair accessory referencing traditional daenggi. POSE: Standing against ocean wind, skirt flowing dramatically, shoulders squared. CAMERA VIEW: Full body shot from slight side angle. LIGHTING: Natural seaside sunlight, soft but bright, wind-enhanced movement. SCENE: Busan coastline promenade with ocean waves and modern skyline in background. STYLE: Romantic couture editorial, wind-swept elegance. COLOR-TONE: Deep navy, white, pearl, fresh ocean blue." )

# 17 · Philippines / Cebu — Coastal Modern Filipiniana
prompts+=( "Cebu — Coastal Modern Filipiniana. SUBJECT: Filipina woman mid-20s, luminous bronze skin, long flowing black hair, radiant confident smile with direct eye contact. BODY: Tall, fluid posture with natural elegance. CLOTHING: Lightweight contemporary Filipiniana dress in soft seafoam green silk with sculpted butterfly sleeves subtly referencing terno structure, asymmetrical hemline, fitted bodice with delicate beadwork inspired by traditional embroidery, wide satin sash in soft coral, minimalist strappy heels, delicate pearl bracelet. POSE: Standing near shoreline with slight body turn, fabric moving in breeze. CAMERA VIEW: Full body shot, slight side angle. LIGHTING: Bright coastal sunlight with soft wind movement. SCENE: Cebu beachfront with ocean horizon and palm trees. STYLE: Ethereal tropical couture editorial. COLOR-TONE: Seafoam green, coral accents, bright tropical blue." )

# 18 · India / Midnight Delhi Edge — Connaught Place (Cowboy Shot)
prompts+=( "Midnight Delhi Edge — Connaught Place (Cowboy Shot). SUBJECT: Sharp expressive Indian features, intense confident gaze, visible face, sleek pulled-back hair. BODY: Straight poised posture. CLOTHING: Deep midnight-blue structured blazer-dress with subtle asymmetrical drape inspired by sari pleating, defined waist with minimalist metallic belt, high-neck silk underlayer in charcoal, tailored silhouette above knee length, pointed black patent leather heels, delicate silver ear jewelry, premium silk blend with subtle sheen, couture precision with modern urban energy. POSE: Standing confidently, shoulders slightly angled. CAMERA VIEW: Cowboy shot, 85mm lens shallow depth. LIGHTING: Evening city lights with cool highlights. SCENE: Connaught Place colonnade background. STYLE: Urban contemporary Indian fashion editorial. COLOR-TONE: Midnight blue, charcoal, cool city tones." )

# 19 · Brazil / São Paulo — Urban Tropical Power Suit
prompts+=( "São Paulo — Urban Tropical Power Suit. SUBJECT: Brazilian woman mid-20s, sleek straight dark hair, bold brows, sharp confident gaze at camera. BODY: Athletic, upright, modern posture. CLOTHING: High-fashion tailored suit in vibrant burnt orange wool with subtle jacquard pattern inspired by indigenous Brazilian geometric motifs, cropped structured blazer with defined shoulders, high-waisted wide trousers, silk bralette in deep forest green, wide leather belt in rich brown, pointed leather heels, statement earrings inspired by indigenous feather shapes but sculptural and metallic, structured handbag in caramel leather. POSE: Walking mid-stride on urban sidewalk, blazer slightly open, powerful stride. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Clean daylight with soft city reflections. SCENE: São Paulo modern business district with glass skyscrapers. STYLE: Urban couture editorial, bold tropical minimalism. COLOR-TONE: Burnt orange, forest green, caramel, warm city neutrals." )

# 20 · Sweden / Midsummer Field Contemporary Romance
prompts+=( "Midsummer Field Contemporary Romance. SUBJECT: Swedish woman mid-20s, long wavy light blonde hair, soft natural makeup, light green eyes, serene yet confident gaze at camera. BODY: Graceful, flowing posture. CLOTHING: Flowing ivory silk dress with structured bodice inspired by Swedish folk costume apron dress, delicate blue and yellow embroidery along hem referencing Swedish flag colors, sheer puff sleeves with subtle lace trim, wide structured waist belt in soft blue leather, delicate floral hairpiece inspired by midsummer wreath but modern and minimal, nude heeled sandals. POSE: Standing in tall meadow grass, slight turn of body, hands relaxed at sides. CAMERA VIEW: Full body shot with slight side angle. LIGHTING: Golden hour sunlight with soft glow and gentle breeze movement. SCENE: Open Swedish countryside meadow with wildflowers. STYLE: Romantic high-fashion editorial, Nordic pastoral reinterpretation. COLOR-TONE: Ivory, soft blue, muted yellow accents, warm golden highlights." )

# 21 · Nigeria / Benin City — Contemporary Coral Royalty
prompts+=( "Benin City — Contemporary Coral Royalty. SUBJECT: Nigerian woman late 20s, luminous skin, strong jawline, braided crown hairstyle, intense confident gaze. BODY: Tall, powerful stance. CLOTHING: Modern reinterpretation of Edo royal aesthetics — tailored fitted midi dress in deep coral red silk with subtle structured shoulders, delicate beaded detailing along neckline referencing traditional coral beads, wide structured belt in matching coral tone, high slit for movement, minimalist gold strappy heels, sculptural gold earrings inspired by Benin bronze art, structured leather clutch. POSE: Standing confidently with one leg slightly forward, shoulders squared. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Warm sunset light with rich skin highlights. SCENE: Benin City historic courtyard with textured walls. STYLE: Regal contemporary couture editorial. COLOR-TONE: Coral red, gold, warm earthy neutrals." )

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 4
# ════════════════════════════════════════════════════════════════════════════

# 22 · Japan / Urban Origami — Roppongi Hills (Full Body)
prompts+=( "Urban Origami — Roppongi Hills (Full Body). SUBJECT: Sharp modern Japanese facial structure, confident neutral expression, visible face, sleek pulled-back hair. BODY: Tall elongated silhouette, strong poised stance. CLOTHING: Pearl-white sculptural blazer with origami-inspired folded shoulder detailing, sharp geometric sleeve construction, fitted high-neck black base layer, sharply tailored cropped black trousers, minimalist structured heels in monochrome white, subtle obi-inspired waist shaping seam, clean architectural tailoring, premium structured cotton blend with crisp fabric texture, couture-level precision. POSE: Standing facing camera with shoulders squared. CAMERA VIEW: Full body portrait, slight low angle. LIGHTING: Bright daylight reflecting from glass architecture. SCENE: Roppongi Hills modern plaza. STYLE: Avant-garde Japanese modern couture editorial. COLOR-TONE: Pearl white, deep black, cool reflective tones." )

# 23 · Korean / Seoul Night Market Street Couture
prompts+=( "Seoul Night Market Street Couture. SUBJECT: South Korean woman late 20s, sleek high ponytail, bold eyeliner, confident smirk, strong eye contact. BODY: Slim yet strong posture, dynamic stance. CLOTHING: Avant-garde street couture — cropped structured leather jacket with subtle embroidered tiger motif referencing Minhwa art, fitted high-neck mesh top underneath, high-waisted tailored shorts layered over sheer long skirt panel in black tulle, chunky platform boots, metallic statement belt with engraved traditional patterns, layered silver chain necklaces mixed with small norigae-inspired charms. POSE: Leaning slightly against a street food stall counter, one leg bent, chin tilted down slightly. CAMERA VIEW: Three-quarter body shot, slightly low angle. LIGHTING: Neon street lights mixed with warm food stall lighting. SCENE: Seoul night market street with neon signs and street vendors. STYLE: Edgy couture streetwear, fashion editorial realism. COLOR-TONE: Black, deep red, neon accents, warm yellow highlights." )

# 24 · Philippines / Banaue — Highland Textile Fusion
prompts+=( "Banaue — Highland Textile Fusion. SUBJECT: Filipina woman late 20s, warm brown skin, strong cheekbones, hair braided elegantly, composed confident gaze. BODY: Lean, grounded posture. CLOTHING: Contemporary tailored ensemble incorporating indigenous woven textile motifs — structured cropped jacket in deep red with geometric Ifugao-inspired patterns, fitted ivory high-neck blouse, tailored black wide-leg trousers, wide leather belt in dark brown, pointed ankle boots, minimalist silver earrings inspired by traditional tribal forms, structured leather crossbody bag. POSE: Standing firmly with legs slightly apart, shoulders squared. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright highland daylight with clear crisp shadows. SCENE: Banaue rice terraces overlooking lush green landscape. STYLE: Modern indigenous-inspired couture editorial. COLOR-TONE: Deep red, ivory, black, vibrant green landscape." )

# 25 · India / Emerald Grace — Udaipur Lakefront (Full Body)
prompts+=( "Emerald Grace — Udaipur Lakefront (Full Body). SUBJECT: Indian female model with luminous skin, expressive eyes, visible face, long flowing hair. BODY: Tall elongated feminine silhouette. CLOTHING: Structured emerald green long tailored coat with subtle anarkali-inspired flare toward hem, fitted ivory silk high-neck blouse, tailored slim trousers in cream with crisp vertical line, gold-toned pointed heels, statement gold earrings inspired by traditional jhumka design, rich silk-wool blend fabric with soft movement, refined embroidery detail along inner lining, elegant fusion of regal tradition and modern tailoring. POSE: Standing near lake railing, facing camera. CAMERA VIEW: Full body portrait, eye-level. LIGHTING: Warm late afternoon sunlight reflecting off water. SCENE: Lakefront near Lake Pichola. STYLE: Luxury heritage-meets-modern couture editorial. COLOR-TONE: Emerald green, ivory, warm golden reflections." )

# 26 · Brazil / Amazon-Inspired Contemporary Flow
prompts+=( "Amazon-Inspired Contemporary Flow. SUBJECT: Brazilian woman late 20s, long flowing dark hair, bronzed skin, striking green eyes, serene but intense gaze at camera. BODY: Elegant elongated proportions, fluid posture. CLOTHING: Flowing couture gown in deep jungle green silk chiffon layered over structured bodice with subtle indigenous-inspired embroidery along neckline, asymmetrical draped skirt panels creating movement, wide leather waist belt in earthy brown, delicate gold arm cuff, minimalist strappy sandals, fine beadwork detail inspired by Amazonian craftsmanship but refined and understated. POSE: Standing still with slight body turn, fabric moving gently. CAMERA VIEW: Full body centered composition. LIGHTING: Soft filtered sunlight through foliage. SCENE: Amazon rainforest edge near riverbank. STYLE: Ethereal tropical couture editorial. COLOR-TONE: Deep green, earthy brown, soft gold highlights." )

# 27 · Sweden / Gothenburg Urban Industrial Folk Fusion
prompts+=( "Gothenburg Urban Industrial Folk Fusion. SUBJECT: Swedish woman late 20s, platinum blonde slicked-back hair, bold brows, intense direct gaze. BODY: Athletic, strong posture. CLOTHING: Structured oversized black leather jacket with embroidered red Dala horse motif on back panel, fitted high-neck knit top in deep burgundy, tailored wide-leg trousers in dark wool, heavy matte black platform boots, statement silver necklace inspired by traditional Swedish brooches (silver filigree reinterpretation), small structured leather clutch. POSE: Standing confidently with legs slightly apart, hands in jacket pockets. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Cool industrial lighting with subtle dramatic shadows. SCENE: Gothenburg harbor industrial docks with cranes and concrete textures. STYLE: Avant-garde Nordic street couture. COLOR-TONE: Black, burgundy, metallic silver, cool grey industrial background." )

# 28 · Nigeria / Kano — Northern Elegance Minimal Fusion
prompts+=( "Kano — Northern Elegance Minimal Fusion. SUBJECT: Nigerian woman early 30s, smooth dark skin, soft natural makeup, calm composed gaze directly at camera. BODY: Slim elegant posture. CLOTHING: Flowing contemporary kaftan-inspired silhouette in soft sand-colored silk with subtle tonal embroidery along cuffs and neckline, cinched with slim leather belt in caramel brown, tailored tapered trousers underneath for structure, minimalist leather heels, delicate gold pendant necklace, structured handbag in warm tan. POSE: Standing upright with hands gently resting at sides. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Bright Northern Nigerian daylight with soft shadows. SCENE: Kano old city walls with warm earth-toned architecture. STYLE: Minimalist luxury couture editorial. COLOR-TONE: Sand, caramel, warm gold highlights." )

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 5
# ════════════════════════════════════════════════════════════════════════════

# 29 · Japan / Vermilion Edge — Fushimi Inari (Three-Quarter)
prompts+=( "Vermilion Edge — Fushimi Inari (Three-Quarter). SUBJECT: Japanese female model with strong expressive eyes, visible face, composed confident look. BODY: Slim upright posture. CLOTHING: Structured vermilion-red long tailored coat inspired by shrine gate color palette, clean sharp collar, defined waist, layered over ivory silk high-collar blouse, fitted black tailored trousers with crisp line, sleek black pointed heels, subtle embroidered detail along hem referencing traditional Japanese motifs, premium wool-silk blend fabric with slight sheen, bold yet refined silhouette. POSE: Standing slightly angled, hands relaxed. CAMERA VIEW: Three-quarter framing. LIGHTING: Soft natural daylight filtering through torii gates. SCENE: Fushimi Inari Taisha pathway. STYLE: High-fashion reinterpretation of traditional Japanese elegance. COLOR-TONE: Vermilion red, ivory, black contrast, warm natural light." )

# 30 · Korean / Modern Palace Garden Editorial
prompts+=( "Modern Palace Garden Editorial. SUBJECT: South Korean woman early 30s, long sleek straight hair, serene yet commanding expression, soft confident gaze toward camera. BODY: Tall, statuesque proportions, elegant stance. CLOTHING: High couture reinterpretation of royal hanbok — structured floor-length gown in muted jade silk with architectural pleating inspired by traditional chima folds, high-collared minimalist top with delicate gold thread embroidery, dramatic oversized sculptural sleeves, structured metallic waistpiece, modern reinterpretation of traditional hairpin in brushed gold, pointed minimalist heels. POSE: Standing still in symmetrical posture, hands relaxed at sides, slight head tilt. CAMERA VIEW: Full body centered composition, symmetrical framing. LIGHTING: Soft diffused daylight with gentle highlights on fabric texture. SCENE: Gyeongbokgung Palace garden courtyard in Seoul. STYLE: Luxury couture editorial, modern royal aesthetic. COLOR-TONE: Muted jade, gold accents, soft neutral background tones." )

# 31 · Philippines / Davao — Urban Contemporary Mestiza Edge
prompts+=( "Davao — Urban Contemporary Mestiza Edge. SUBJECT: Filipina woman early 30s, smooth golden complexion, sleek straight hair, bold defined brows, intense confident gaze. BODY: Tall statuesque stance. CLOTHING: Tailored midnight blue structured blazer with subtle embroidery along lapels inspired by Mindanao patterns, fitted silk camisole in soft champagne, high-waisted tailored trousers in matching navy, wide leather belt with brushed gold buckle, pointed black heels, statement gold cuff bracelet, structured handbag in dark navy leather. POSE: Standing confidently with one hand in pocket, shoulders back. CAMERA VIEW: Full body centered composition. LIGHTING: Warm sunset light with soft urban glow. SCENE: Davao city urban plaza with modern architecture. STYLE: Urban Filipino couture editorial. COLOR-TONE: Midnight blue, champagne, warm sunset tones." )

# 32 · India / Saffron Contemporary Muse — Varanasi Ghats (Three-Quarter)
prompts+=( "Saffron Contemporary Muse — Varanasi Ghats (Three-Quarter). SUBJECT: Indian woman with strong expressive features, serene confident gaze, visible face, natural hair styling. BODY: Graceful upright posture. CLOTHING: Structured saffron-orange tailored midi coat with modern clean collar line, subtle pleated side panel inspired by sari draping, ivory silk blouse with minimalist neckline, tailored dark brown slim trousers with crisp crease, pointed suede heels in warm caramel, fine zari-inspired embroidery accent along hem, premium breathable fabric blend with visible texture, bold color statement balanced with refined couture tailoring. POSE: Standing still, hands gently resting near waist. CAMERA VIEW: Three-quarter framing. LIGHTING: Soft sunrise light with gentle warm glow. SCENE: Varanasi Ghats along the Ganges. STYLE: Modern spiritual elegance couture editorial. COLOR-TONE: Saffron orange, ivory, warm sunrise tones." )

# 33 · Brazil / Recife Coastal Modern Romance
prompts+=( "Recife Coastal Modern Romance. SUBJECT: Brazilian woman early 30s, light brown skin, shoulder-length wavy hair, luminous smile with confident direct gaze. BODY: Tall, statuesque stance. CLOTHING: Contemporary reinterpretation of Northeastern Brazilian lace traditions — fitted white lace midi dress with structured corset bodice, sheer long sleeves with intricate embroidery, asymmetrical slit, wide satin belt in vibrant cobalt blue, pointed nude heels, minimalist pearl earrings, small structured clutch in matching blue satin. POSE: Standing on coastal boardwalk, one hand lightly resting on hip. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Bright coastal daylight with soft breeze movement. SCENE: Recife beach promenade with ocean and palm trees in background. STYLE: Romantic modern couture editorial. COLOR-TONE: White lace, cobalt blue accent, soft ocean turquoise." )

# 34 · Sweden / Lapland Winter Couture Minimalism
prompts+=( "Lapland Winter Couture Minimalism. SUBJECT: Swedish woman early 30s, fair skin, light blue eyes, sleek braided blonde hair, composed expression facing camera. BODY: Tall, statuesque, grounded stance. CLOTHING: Contemporary winter couture inspired by Sámi traditional garments — long structured white wool coat with subtle red and blue trim along edges, high-neck cashmere sweater in soft grey, tailored wide-leg wool trousers, wide leather belt with minimal metallic detail, knee-high white leather boots, minimalist silver earrings shaped like abstract snowflakes, soft wool gloves in pale blue. POSE: Standing still in snow-covered landscape, shoulders squared, strong presence. CAMERA VIEW: Full body centered composition. LIGHTING: Soft diffused winter daylight, bright snow reflections. SCENE: Swedish Lapland snowy open landscape with pine trees. STYLE: Luxury winter couture editorial, Nordic minimalism. COLOR-TONE: White, pale grey, soft blue, subtle red accents." )

# 35 · Nigeria / Calabar — Coastal Contemporary Heritage
prompts+=( "Calabar — Coastal Contemporary Heritage. SUBJECT: Nigerian woman mid-20s, glowing deep brown skin, long natural curls, expressive confident gaze at camera. BODY: Graceful yet strong silhouette. CLOTHING: Contemporary reinterpretation of Efik-inspired lace traditions — fitted white lace jumpsuit with structured bodice, sheer embroidered sleeves, wide satin sash in vibrant indigo tied at waist, pointed heels in deep navy, layered pearl-inspired jewelry, structured clutch in indigo satin. POSE: Standing with one hand on hip, relaxed but confident stance. CAMERA VIEW: Full body shot, slight low angle. LIGHTING: Bright coastal daylight with soft breeze movement. SCENE: Calabar coastal promenade with palm trees and ocean backdrop. STYLE: Romantic modern African couture editorial. COLOR-TONE: White lace, indigo blue accents, tropical light." )

# ════════════════════════════════════════════════════════════════════════════
# WOMEN — Row 6 (repeats countries, different looks not specified — same structure)
# ════════════════════════════════════════════════════════════════════════════
# NOTE: The wiki page ends at Row 5 for women — no Row 6 entries found in source.
# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# MEN — Row 1
# ════════════════════════════════════════════════════════════════════════════

# 36 · Ukraine / Kyiv Golden Hour — Modern Vyshyvanka Power Suit
prompts+=( "Kyiv Golden Hour — Modern Vyshyvanka Power Suit. SUBJECT: Ukrainian man early 30s, sharp cheekbones, light stubble, deep-set blue eyes, short dark-blond hair neatly styled, confident direct gaze at camera. BODY: Tall, athletic build, upright commanding posture. CLOTHING: Tailored charcoal wool suit with subtle woven geometric vyshyvanka-inspired pattern integrated into fabric texture, structured blazer with slightly extended shoulders, crisp white high-collar shirt featuring minimalist black and red embroidery along placket and cuffs, slim tailored trousers with clean break, wide matte black leather belt with brushed steel buckle, polished black leather Chelsea boots, minimal silver signet ring engraved with traditional Ukrainian motif, structured leather briefcase in deep brown. POSE: Standing firmly with feet shoulder-width apart, one hand adjusting blazer cuff. CAMERA VIEW: Full body shot, slightly low angle for authority. LIGHTING: Warm golden hour sunlight with long city shadows. SCENE: Kyiv skyline view with Dnipro River and modern buildings in background. STYLE: High-fashion editorial, modern heritage tailoring. COLOR-TONE: Charcoal, white, deep red accents, warm sunset gold." )

# 37 · Italy / Milan — Modern Sartorial Renaissance
prompts+=( "Milan — Modern Sartorial Renaissance. SUBJECT: Italian man early 30s, sharp jawline, olive skin, neatly trimmed beard, dark wavy hair styled back, intense confident gaze directly at camera. BODY: Tall, lean athletic build, elegant upright posture. CLOTHING: Contemporary couture reinterpretation of classic Italian tailoring — deep burgundy double-breasted suit in fine wool with subtle jacquard pattern inspired by Renaissance fresco motifs, sharply structured shoulders, tapered high-waisted trousers with clean break, crisp ivory silk shirt with minimal hidden placket, wide black leather belt with brushed gold buckle, polished black leather loafers, silk pocket square in muted gold, minimalist gold signet ring, slim leather document case. POSE: Standing mid-step on city sidewalk, one hand adjusting cuff, chin slightly lifted. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Soft late afternoon Milan sunlight with warm reflections on fabric texture. SCENE: Milan city street near modern fashion district architecture. STYLE: Luxury high-fashion editorial, refined Italian tailoring. COLOR-TONE: Burgundy, ivory, black, warm golden highlights." )

# 38 · UK / London — Modern Savile Row Power
prompts+=( "London — Modern Savile Row Power. SUBJECT: British man early 30s, sharp cheekbones, light stubble, short neatly styled brown hair, piercing blue eyes, confident direct gaze at camera. BODY: Tall, lean build, upright commanding posture. CLOTHING: Contemporary reinterpretation of classic British tailoring — deep navy structured double-breasted suit in fine wool with subtle Prince of Wales check pattern, sharply defined shoulders, high-waisted tapered trousers, crisp white shirt with stiff collar, silk tie in deep burgundy, tailored overcoat in charcoal cashmere draped over shoulders, polished black Oxford shoes, silver tie bar, structured leather briefcase in dark brown. POSE: Standing firmly with one hand adjusting cuff, chin slightly raised. CAMERA VIEW: Full body shot, slightly low angle for authority. LIGHTING: Soft overcast London daylight with gentle contrast. SCENE: Savile Row street in London with classic tailoring shopfronts. STYLE: Luxury heritage couture editorial. COLOR-TONE: Navy, charcoal, burgundy accents, cool urban neutrals." )

# 39 · US / New York City — Modern Wall Street Power
prompts+=( "New York City — Modern Wall Street Power. SUBJECT: American man early 30s, sharp jawline, light stubble, neatly styled dark hair, intense focused gaze directly at camera. BODY: Tall, lean athletic build, upright commanding posture. CLOTHING: Contemporary reinterpretation of classic American business tailoring — charcoal double-breasted suit with subtle pinstripe, structured shoulders, high-waisted sharply tailored trousers, crisp white dress shirt with structured collar, deep navy silk tie, long camel cashmere overcoat draped over shoulders, polished black leather Oxfords, stainless steel watch, structured leather briefcase in dark brown. POSE: Standing firmly with one hand adjusting cuff, chin slightly lifted. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Cool Manhattan daylight reflecting off skyscrapers. SCENE: Wall Street area with glass and steel skyscrapers. STYLE: Luxury American power couture editorial. COLOR-TONE: Charcoal, camel, navy accents, cool urban neutrals." )

# 40 · Morocco / Marrakech — Modern Kasbah Elegance
prompts+=( "Marrakech — Modern Kasbah Elegance. SUBJECT: Moroccan man early 30s, olive skin, sharp cheekbones, dark wavy hair, groomed beard, deep brown eyes, confident gaze directly at camera. BODY: Tall, lean build, upright and poised posture. CLOTHING: Tailored contemporary djellaba-inspired long coat in deep burgundy wool with subtle geometric embroidery along collar and cuffs, structured shoulders, high-collar minimalist shirt in cream with fine embroidered threadwork, slim tailored trousers in charcoal, wide leather belt with brass buckle, polished leather boots, understated gold cuff bracelet. POSE: Standing with feet shoulder-width apart, one hand adjusting coat lapel. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Warm late-afternoon sunlight with soft shadows. SCENE: Historic Marrakech kasbah courtyard with ochre walls and traditional tilework. STYLE: Luxury Moroccan heritage couture editorial. COLOR-TONE: Burgundy, cream, charcoal, warm golden light." )

# 41 · Ethiopia / Addis Ababa — Modern Habesha Tailoring
prompts+=( "Addis Ababa — Modern Habesha Tailoring. SUBJECT: Ethiopian man early 30s, warm brown skin, sharp cheekbones, short textured black hair, neatly groomed beard, deep-set dark eyes, calm confident gaze directly at camera. BODY: Tall, lean athletic build, upright composed posture. CLOTHING: Contemporary reinterpretation of traditional Habesha kemis textile — tailored ivory suit in fine cotton with subtle woven tibeb border detailing along blazer lapels and cuffs in black and gold thread, structured but clean shoulders, high-collar minimalist shirt in crisp white with fine embroidery at neckline, tapered trousers with sharp crease, wide black leather belt with brushed brass buckle, polished black leather loafers, understated gold ring. POSE: Standing firmly with shoulders squared, one hand adjusting blazer cuff. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright highland daylight with soft contrast. SCENE: Modern Addis Ababa cityscape with contemporary buildings and distant hills. STYLE: Luxury heritage couture editorial. COLOR-TONE: Ivory, black, gold accents, soft natural light." )

# 42 · Cuba / Old Havana Elegance
prompts+=( "Old Havana Elegance. SUBJECT: Cuban man, 30s, sharp cheekbones, warm brown skin, confident gaze, neatly trimmed beard. BODY: Tall, lean athletic build, relaxed shoulders, expressive hands. CLOTHING: Modern couture reinterpretation of the guayabera: ivory structured linen jacket with elongated silhouette, vertical alforza pleats transformed into architectural seam panels, subtle tonal embroidery along collar and cuffs, four-pocket illusion detailing stitched into front panel, hidden gold buttons; high-waisted sand-colored pleated trousers in silk-linen blend with sharp crease; lightweight semi-sheer cotton shirt underneath with Mandarin-inspired collar; polished tobacco-brown leather loafers; thin gold chain visible at collarbone; classic Panama hat in off-white with dark band. POSE: Standing casually against pastel colonial wall, one hand adjusting cuff, direct eye contact. CAMERA VIEW: Three-quarter body shot, slightly low angle. LIGHTING: Warm late-afternoon Caribbean sunlight, soft shadows. SCENE: Street in Old Havana with vintage cars and textured colonial façades. STYLE: High-fashion editorial, natural realism, couture detailing focus. COLOR-TONE: Warm beige, ivory, pastel pink walls, sunlit gold accents." )

# ════════════════════════════════════════════════════════════════════════════
# MEN — Row 2
# ════════════════════════════════════════════════════════════════════════════

# 43 · Ukraine / Lviv Cobblestone — Romantic Neo-Folk Elegance
prompts+=( "Lviv Cobblestone — Romantic Neo-Folk Elegance. SUBJECT: Ukrainian man late 20s, wavy brown hair, light beard, expressive hazel eyes, calm confident gaze at camera. BODY: Lean, refined silhouette. CLOTHING: Cream linen structured jacket with subtle tonal embroidery along collar inspired by Western Ukrainian patterns, soft ivory embroidered shirt with delicate geometric red and black threadwork, tailored high-waisted dark trousers, wide leather belt in cognac brown, polished oxford shoes, minimalist silver chain necklace under collar, slim leather document pouch. POSE: Mid-walk on cobblestone street, coat slightly moving, relaxed yet confident. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Soft diffused daylight with gentle shadow definition. SCENE: Historic Lviv street with pastel facades and old lanterns. STYLE: Romantic European couture editorial. COLOR-TONE: Ivory, cognac, deep black, muted red accents." )

# 44 · Italy / Florence — Neo-Renaissance Elegance
prompts+=( "Florence — Neo-Renaissance Elegance. SUBJECT: Italian man late 20s, strong cheekbones, light stubble, deep brown eyes, medium-length dark hair, composed direct gaze. BODY: Slim elongated silhouette, relaxed but poised stance. CLOTHING: Structured cream linen blazer with subtle embroidered detailing along lapels inspired by Florentine Renaissance patterns, fitted sand-colored high-waisted trousers, soft white open-collar shirt with delicate tonal embroidery, wide cognac leather belt, suede loafers in warm brown, slim leather shoulder bag, understated gold chain bracelet. POSE: Standing confidently with one hand in pocket, shoulders relaxed. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Warm Tuscan daylight, soft and diffused. SCENE: Florence street with historic stone architecture and cathedral dome in background. STYLE: Romantic couture editorial, heritage refinement. COLOR-TONE: Cream, sand, cognac, warm stone neutrals." )

# 45 · UK / Edinburgh — Highland Modern Formality
prompts+=( "Edinburgh — Highland Modern Formality. SUBJECT: Scottish man late 20s, strong jawline, light beard, medium-length dark hair swept back, steady direct gaze. BODY: Athletic frame, grounded posture. CLOTHING: Modern reinterpretation of Highland elements — tailored black structured blazer with subtle tartan lining visible at cuffs, high-waisted charcoal trousers, minimalist white shirt with concealed placket, wide leather belt with brushed silver buckle, sleek black leather boots, tartan scarf in muted green and navy tones, minimalist silver signet ring. POSE: Standing confidently on cobblestone, coat slightly moving in wind. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Cool northern daylight with soft shadow depth. SCENE: Edinburgh historic street with stone architecture and castle silhouette. STYLE: Refined neo-heritage couture editorial. COLOR-TONE: Black, charcoal, deep green tartan accents, cool grey tones." )

# 46 · US / Texas — Contemporary Western Couture
prompts+=( "Texas — Contemporary Western Couture. SUBJECT: American man early 30s, sun-kissed skin, short sandy-brown hair, trimmed beard, confident direct gaze. BODY: Broad-shouldered athletic build, grounded stance. CLOTHING: Modern reinterpretation of Western heritage — tailored black denim jacket with subtle embroidered Western motifs along shoulders, fitted ivory shirt with minimal piping detail, high-waisted dark indigo tailored jeans with sharp crease, wide leather belt with brushed silver buckle, polished leather cowboy boots in deep brown, minimalist silver ring. POSE: Standing with feet apart, thumbs hooked in belt, relaxed but powerful posture. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Warm Texas sunset with golden highlights. SCENE: Open Texas landscape with ranch fencing and wide sky. STYLE: Contemporary Western couture editorial. COLOR-TONE: Black denim, indigo, ivory, warm sunset gold." )

# 47 · Morocco / Fes — Neo-Medina Structured Heritage
prompts+=( "Fes — Neo-Medina Structured Heritage. SUBJECT: Moroccan man late 20s, strong jawline, neatly trimmed beard, dark brown hair, intense gaze. BODY: Slim athletic build, elegant upright stance. CLOTHING: Modern tailored vest and jacket ensemble inspired by traditional Moroccan kaftan patterns — deep navy jacket with subtle gold embroidery along seams, fitted cream linen shirt with minimal mandarin collar, slim tailored trousers in soft taupe, leather sandals with metallic detailing, thin leather belt, small structured crossbody bag, minimalist silver ring. POSE: Walking along alleyway with one hand adjusting vest. CAMERA VIEW: Three-quarter full body shot, eye-level. LIGHTING: Soft diffused daylight filtering through narrow medina streets. SCENE: Fes medina alleyway with patterned tile walls and hanging lanterns. STYLE: Contemporary Moroccan couture editorial. COLOR-TONE: Navy, cream, taupe, subtle gold accents." )

# 48 · Ethiopia / Lalibela — Sacred Minimalism
prompts+=( "Lalibela — Sacred Minimalism. SUBJECT: Ethiopian man late 20s, defined jawline, short curls, light stubble, intense thoughtful gaze at camera. BODY: Slim elongated silhouette, grounded posture. CLOTHING: Flowing contemporary robe inspired by traditional netela — long structured off-white coat in lightweight woven cotton with subtle red and black tibeb patterns along edges, minimalist high-neck tunic underneath, tailored charcoal trousers, leather ankle boots in deep brown, simple leather bracelet. POSE: Standing upright with calm presence, hands relaxed at sides. CAMERA VIEW: Full body centered composition. LIGHTING: Soft diffused daylight with gentle shadow depth. SCENE: Lalibela rock-hewn church surroundings with carved stone architecture. STYLE: Spiritual minimal couture editorial. COLOR-TONE: Off-white, charcoal, muted red accents, soft stone neutrals." )

# 49 · Cuba / Havana Jazz Night
prompts+=( "Havana Jazz Night. SUBJECT: Cuban man, early 40s, salt-and-pepper beard, intense eyes. BODY: Broad shoulders, confident posture. CLOTHING: Midnight navy silk-linen blazer with subtle jacquard palm-leaf texture, tailored soft shoulders; reimagined guayabera shirt in matte black silk with tonal embroidery inspired by Afro-Cuban geometric motifs; slim high-waisted trousers in deep navy tropical wool; antique brass buttons; black suede loafers; slim leather belt with gold buckle; silk pocket square in coral red. POSE: Seated at outdoor café table, leaning forward slightly, hands clasped, face illuminated. CAMERA VIEW: Cowboy shot (mid-thigh up). LIGHTING: Low warm café lighting mixed with cool evening ambient street light. SCENE: Havana jazz bar terrace at night, musicians blurred in background. STYLE: Cinematic couture realism. COLOR-TONE: Deep navy, warm amber highlights, coral accents." )

# ════════════════════════════════════════════════════════════════════════════
# MEN — Row 3
# ════════════════════════════════════════════════════════════════════════════

# 50 · Ukraine / Odesa Seaside — Coastal Modern Cossack Energy
prompts+=( "Odesa Seaside — Coastal Modern Cossack Energy. SUBJECT: Ukrainian man early 30s, sharp jawline, shaved sides with longer textured top, piercing grey eyes, intense direct gaze. BODY: Strong, broad-shouldered build. CLOTHING: Structured navy long coat inspired by traditional Cossack outerwear silhouette, high-collar minimalist embroidered shirt in white with subtle tonal stitching, tailored black wide-leg trousers referencing sharovary proportions but modernized, wide leather waist belt with matte metal detailing, sleek black leather boots, subtle leather wrist cuff, minimalist crossbody bag in dark navy. POSE: Standing facing wind with coat flowing slightly, shoulders squared. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright seaside daylight with dynamic highlights. SCENE: Odesa seaside promenade with Black Sea horizon. STYLE: Avant-garde heritage reinterpretation, strong editorial presence. COLOR-TONE: Navy, white, black, cool sea blue." )

# 51 · Italy / Rome — Contemporary Gladiator Minimalism
prompts+=( "Rome — Contemporary Gladiator Minimalism. SUBJECT: Italian man early 30s, short dark hair, clean-shaven, piercing dark eyes, strong direct gaze at camera. BODY: Athletic muscular build, grounded powerful stance. CLOTHING: Modern reinterpretation of Roman heritage — structured charcoal long coat with subtle stitched panel lines referencing classical armor geometry, fitted black high-neck knit top, tailored slim black trousers, wide leather waist belt with brushed metal detailing, matte black leather boots, minimalist cuff bracelet in brushed silver, structured leather crossbody bag. POSE: Standing upright with feet firmly planted, shoulders squared. CAMERA VIEW: Full body shot, slightly low angle for dramatic effect. LIGHTING: Golden Roman sunset light casting defined shadows. SCENE: Near the Colosseum in Rome with ancient stone backdrop. STYLE: Avant-garde couture editorial, architectural minimalism. COLOR-TONE: Charcoal, black, muted bronze, warm sunset glow." )

# 52 · UK / Manchester — Industrial Tailored Edge
prompts+=( "Manchester — Industrial Tailored Edge. SUBJECT: British man early 30s, short textured dark hair, clean-shaven, intense focused gaze at camera. BODY: Slim athletic build, strong stance. CLOTHING: Oversized structured charcoal coat with subtle plaid pattern referencing classic British checks, fitted black turtleneck, tailored grey wide-leg trousers, heavy matte leather boots, slim leather crossbody bag, brushed steel cuff bracelet, minimal chain necklace. POSE: Standing with hands in coat pockets, shoulders squared. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Moody industrial daylight with soft shadows. SCENE: Manchester industrial brick warehouse district. STYLE: Urban couture editorial, modern British industrial aesthetic. COLOR-TONE: Charcoal, slate grey, muted steel tones." )

# 53 · US / Los Angeles — Coastal Minimal Luxury
prompts+=( "Los Angeles — Coastal Minimal Luxury. SUBJECT: American man late 20s, olive-tan skin, medium-length textured hair, clean-shaven, relaxed confident gaze at camera. BODY: Lean athletic silhouette, natural relaxed stance. CLOTHING: Lightweight ivory linen suit with soft unstructured blazer, pale sage silk open-collar shirt, tailored slim trousers with subtle pleats, brown suede loafers, slim leather belt, aviator sunglasses slightly lowered to reveal eyes, minimalist gold bracelet. POSE: Standing casually with one hand in pocket, shoulders relaxed. CAMERA VIEW: Full body shot, slight side angle. LIGHTING: Bright California sunlight with soft coastal glow. SCENE: Los Angeles coastal boardwalk with ocean horizon. STYLE: Modern West Coast couture editorial. COLOR-TONE: Ivory, sage green, tan suede, bright blue sky." )

# 54 · Morocco / Casablanca — Urban Modern Mashrabiya
prompts+=( "Casablanca — Urban Modern Mashrabiya. SUBJECT: Moroccan man early 30s, olive skin, slicked-back dark hair, clean-shaven, confident gaze. BODY: Athletic, grounded posture. CLOTHING: Structured modern jacket inspired by traditional Moroccan mashrabiya lattice patterns, deep charcoal with subtle geometric cutouts and embroidery, high-neck black cotton shirt, tailored grey trousers with sharp creases, matte leather boots, slim leather belt, minimalist metallic bracelet. POSE: Standing upright with shoulders squared, hands relaxed. CAMERA VIEW: Full body shot, slight low angle. LIGHTING: Bright daylight with crisp shadows from urban architecture. SCENE: Casablanca modern street with mashrabiya-inspired building facades. STYLE: Avant-garde Moroccan urban couture. COLOR-TONE: Charcoal, black, grey, cool urban neutrals." )

# 55 · Ethiopia / Gondar — Royal Heritage Reimagined
prompts+=( "Gondar — Royal Heritage Reimagined. SUBJECT: Ethiopian man early 30s, strong cheekbones, short cropped hair, groomed beard, steady commanding gaze. BODY: Tall, powerful stance. CLOTHING: Structured deep navy long coat inspired by historical Ethiopian royal garments, subtle gold embroidered detailing along collar and sleeve edges, fitted ivory silk shirt with minimalist neckline embroidery, tailored black wide-leg trousers, wide leather waist belt with metallic detailing, polished black boots, minimalist gold cuff. POSE: Standing confidently with one foot slightly forward, chin lifted. CAMERA VIEW: Three-quarter full body shot, slightly low angle. LIGHTING: Warm late-afternoon sunlight with golden highlights. SCENE: Gondar castle complex courtyard. STYLE: Regal contemporary couture editorial. COLOR-TONE: Navy, ivory, gold accents, warm sunset glow." )

# 56 · Cuba / Malecón Wind
prompts+=( "Malecón Wind. SUBJECT: Cuban man, late 20s, clean-shaven, sharp jawline, wind-swept hair. BODY: Athletic, defined frame. CLOTHING: Flowing long overcoat in pearl-white linen-silk blend, lightweight and wind-reactive; underneath a restructured guayabera shirt in soft turquoise with vertical pleat detailing exaggerated into bold stitched panels; wide-leg cream trousers cropped above ankle; minimalist leather sandals in tan; layered thin gold bracelets; narrow silk scarf loosely tied. POSE: Walking along seawall, coat flowing, face turned slightly toward camera. CAMERA VIEW: Full-body dynamic shot. LIGHTING: Natural coastal daylight, soft diffused sun. SCENE: Havana Malecón promenade with ocean waves behind. STYLE: Modern tropical couture, motion-focused editorial. COLOR-TONE: Ocean turquoise, pearl white, sand beige." )

# ════════════════════════════════════════════════════════════════════════════
# MEN — Row 4
# ════════════════════════════════════════════════════════════════════════════

# 57 · Ukraine / Kharkiv Industrial — Urban Embroidered Minimalism
prompts+=( "Kharkiv Industrial — Urban Embroidered Minimalism. SUBJECT: Ukrainian man mid-20s, short dark hair, clean-shaven, focused expression, intense eye contact with camera. BODY: Slim athletic frame, grounded stance. CLOTHING: Oversized matte black structured coat with subtle embroidered geometric panels in dark red thread along sleeves, fitted black turtleneck, tailored charcoal trousers, chunky matte leather boots, minimalist steel pendant referencing Trypillian spiral motif, structured crossbody leather bag. POSE: Standing confidently with hands in coat pockets, legs slightly apart. CAMERA VIEW: Full body shot, straight-on composition. LIGHTING: Cool industrial lighting with soft dramatic shadows. SCENE: Kharkiv industrial district with concrete architecture. STYLE: Urban couture editorial, dystopian minimal heritage. COLOR-TONE: Matte black, charcoal, deep red accents, cool grey background." )

# 58 · Italy / Venice — Baroque Fluid Modernity
prompts+=( "Venice — Baroque Fluid Modernity. SUBJECT: Italian man late 20s, olive skin, soft stubble, slicked-back dark hair, calm but magnetic gaze. BODY: Tall, graceful posture. CLOTHING: Deep navy velvet blazer with subtle baroque-inspired embroidery along cuffs and collar, ivory silk shirt with high collar, tailored black trousers with slight flare, velvet loafers in midnight blue, silk neck scarf in muted gold, slim leather gloves tucked in belt, small structured leather clutch. POSE: Standing on canal edge with slight turn of body, one hand lightly touching scarf. CAMERA VIEW: Full body shot with slight side angle. LIGHTING: Soft evening Venetian light with reflections from canal water. SCENE: Venice canal walkway with gondolas and historic buildings. STYLE: Romantic baroque couture editorial. COLOR-TONE: Midnight blue, ivory, gold accents, cool reflective highlights." )

# 59 · UK / Oxford — Academic Neo-Victorian Elegance
prompts+=( "Oxford — Academic Neo-Victorian Elegance. SUBJECT: British man late 20s, wavy brown hair, light stubble, thoughtful but confident gaze. BODY: Tall, refined posture. CLOTHING: Structured long camel wool coat inspired by Victorian silhouettes, tailored dark brown waistcoat with subtle jacquard pattern, crisp ivory shirt with high collar, tailored slim trousers in deep chocolate, polished brogue shoes, silk cravat in muted burgundy, structured leather satchel. POSE: Standing upright holding satchel strap, slight tilt of head. CAMERA VIEW: Three-quarter full body shot at eye level. LIGHTING: Soft diffused daylight filtering through clouds. SCENE: Oxford college courtyard with gothic stone arches. STYLE: Romantic academic couture editorial. COLOR-TONE: Camel, chocolate brown, burgundy accents, soft stone neutrals." )

# 60 · US / Chicago — Industrial Americana Edge
prompts+=( "Chicago — Industrial Americana Edge. SUBJECT: American man early 30s, short dark hair, light stubble, strong jawline, intense gaze. BODY: Athletic build, confident upright stance. CLOTHING: Structured oversized charcoal wool coat referencing classic American workwear silhouettes, fitted black turtleneck, tailored grey wide-leg trousers, matte leather boots, thick leather belt in dark brown, stainless steel chain bracelet, structured leather messenger bag. POSE: Standing firmly with hands in coat pockets, shoulders squared. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Cool industrial daylight with defined shadows. SCENE: Chicago riverwalk with steel bridges and city skyline. STYLE: Urban American couture editorial. COLOR-TONE: Charcoal, black, steel grey, cool city tones." )

# 61 · Morocco / Chefchaouen — Blue City Contemporary Heritage
prompts+=( "Chefchaouen — Blue City Contemporary Heritage. SUBJECT: Moroccan man late 20s, dark wavy hair, light stubble, warm brown eyes, serene confident gaze. BODY: Lean, elongated silhouette. CLOTHING: Flowing cobalt blue long-line coat with modern reinterpretation of traditional Moroccan embroidery along sleeves and collar, tailored cream linen shirt underneath, slim navy trousers, minimalist leather sandals, soft woven scarf draped casually, subtle silver jewelry inspired by Amazigh motifs. POSE: Leaning lightly against wall with one hand resting on coat, casual posture. CAMERA VIEW: Three-quarter body shot, eye-level. LIGHTING: Soft daylight reflecting off blue-painted city walls. SCENE: Chefchaouen alleyway with iconic blue walls and narrow winding streets. STYLE: Romantic contemporary Moroccan couture editorial. COLOR-TONE: Cobalt blue, cream, navy accents, soft natural light." )

# 62 · Ethiopia / Simien Mountains — Elevated Highland Winter Couture
prompts+=( "Simien Mountains — Elevated Highland Winter Couture. SUBJECT: Ethiopian man early 30s, warm brown skin, short textured hair, strong jawline, calm focused gaze. BODY: Athletic build, grounded stable posture. CLOTHING: Luxury winter reinterpretation of gabi textile — long structured wool coat in soft beige with subtle woven border detailing in dark brown and black, thick textured knit sweater underneath in cream, tailored dark wool trousers, wide leather belt in chestnut brown, rugged leather boots, minimalist woven scarf draped over shoulders. POSE: Standing firmly on rocky terrain, shoulders squared. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Bright high-altitude daylight with crisp air clarity. SCENE: Simien Mountains landscape with dramatic cliffs. STYLE: Luxury highland couture editorial. COLOR-TONE: Beige, cream, chestnut brown, cool mountain light." )

# 63 · Cuba / Tobacco Heritage Contemporary
prompts+=( "Tobacco Heritage Contemporary. SUBJECT: Cuban man, 35, intense stare, rugged charm. BODY: Muscular build, strong hands. CLOTHING: Structured tobacco-brown tailored jacket inspired by cigar culture tones, textured linen blend with subtle woven wave motifs; sharp ivory poplin shirt with minimal embroidery on placket; high-waisted dark chocolate trousers with relaxed taper; leather suspenders; polished oxblood loafers; slim gold ring; subtle patterned pocket lining referencing colonial baroque designs. POSE: Standing inside traditional cigar factory, holding cigar thoughtfully near face. CAMERA VIEW: Waist-up portrait. LIGHTING: Warm industrial window light with dramatic side shadow. SCENE: Historic Havana cigar workshop interior. STYLE: Editorial portrait, refined masculine couture. COLOR-TONE: Rich browns, ivory, warm sepia tones." )

# ════════════════════════════════════════════════════════════════════════════
# MEN — Row 5
# ════════════════════════════════════════════════════════════════════════════

# 64 · Ukraine / Carpathian Mountains — Elevated Folk Winter Couture
prompts+=( "Carpathian Mountains — Elevated Folk Winter Couture. SUBJECT: Ukrainian man early 30s, light brown hair, short beard, strong cheekbones, calm steady gaze at camera. BODY: Tall, sturdy build, grounded presence. CLOTHING: Luxury reinterpretation of traditional Hutsul elements — structured ivory wool coat with subtle colorful embroidery along lapels and cuffs, thick textured knit sweater in natural beige tones, tailored dark wool trousers, wide leather belt with engraved metal buckle, high leather boots, soft wool scarf in muted traditional color palette, leather gloves. POSE: Standing firmly on snowy terrain, shoulders relaxed but powerful. CAMERA VIEW: Full body centered composition. LIGHTING: Soft diffused winter daylight reflecting off snow. SCENE: Carpathian mountain landscape with pine trees and snow. STYLE: Luxury winter couture editorial, heritage elevation. COLOR-TONE: Ivory, beige, deep brown, muted traditional accent colors." )

# 65 · Italy / Amalfi Coast — Mediterranean Couture Relaxed Power
prompts+=( "Amalfi Coast — Mediterranean Couture Relaxed Power. SUBJECT: Italian man early 30s, sun-kissed skin, short textured dark hair, confident relaxed gaze toward camera. BODY: Lean athletic build, natural relaxed stance. CLOTHING: Lightweight ivory linen suit with subtle woven Mediterranean geometric pattern, unstructured blazer with soft shoulders, open-collar pale blue silk shirt, high-waisted tailored trousers, brown leather belt, suede loafers in warm tan, aviator sunglasses slightly lowered to reveal eyes, slim leather weekender bag. POSE: Standing casually overlooking coastal cliff, one hand resting on bag strap. CAMERA VIEW: Full body shot, eye-level. LIGHTING: Bright Mediterranean sunlight with crisp shadows. SCENE: Amalfi Coast cliffside with blue sea and pastel villas. STYLE: Luxury coastal couture editorial. COLOR-TONE: Ivory, pale blue, tan leather, vibrant Mediterranean blue." )

# 66 · UK / Cornwall Coast — Contemporary Maritime Heritage
prompts+=( "Cornwall Coast — Contemporary Maritime Heritage. SUBJECT: British man early 30s, windswept sandy-blond hair, light beard, calm confident gaze toward camera. BODY: Lean athletic build, relaxed grounded stance. CLOTHING: Modern maritime reinterpretation — structured navy peacoat with subtle embroidered anchor detail along inner lapel, cream ribbed knit sweater, tailored navy trousers, wide leather belt in dark tan, polished leather boots, wool scarf in muted coastal tones, minimal silver pendant inspired by nautical compass. POSE: Standing facing sea breeze, one hand in coat pocket. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Bright coastal daylight with dynamic wind movement. SCENE: Cornwall cliffside overlooking the Atlantic Ocean. STYLE: Luxury coastal couture editorial. COLOR-TONE: Navy, cream, tan leather, cool ocean blue." )

# 67 · US / Washington D.C. — Neo-Classic Formal Heritage
prompts+=( "Washington, D.C. — Neo-Classic Formal Heritage. SUBJECT: American man early 30s, clean-cut appearance, short dark hair, composed confident gaze directly at camera. BODY: Tall, refined posture. CLOTHING: Midnight blue tailored tuxedo with subtle textured weave, structured shoulders, crisp white formal shirt with sharp collar, slim black satin lapels, tailored trousers with satin side stripe, polished black patent leather shoes, minimalist black bow tie, sleek stainless steel watch, slim black leather portfolio. POSE: Standing upright with calm authority, hands relaxed at sides. CAMERA VIEW: Full body centered composition. LIGHTING: Soft evening light with subtle architectural illumination. SCENE: Washington, D.C. near neoclassical government architecture. STYLE: Elegant American formal couture editorial. COLOR-TONE: Midnight blue, black satin, crisp white, soft evening glow." )

# 68 · Morocco / Sahara Desert — Nomadic Minimal Couture
prompts+=( "Sahara Desert — Nomadic Minimal Couture. SUBJECT: Moroccan man early 30s, sun-kissed skin, short dark hair, groomed beard, calm confident gaze toward camera. BODY: Tall, strong, grounded posture. CLOTHING: Modern desert-inspired ensemble — long beige linen tunic with minimal embroidered motifs along collar and hem referencing Berber patterns, tailored sand-colored trousers, wide leather belt with metallic detail, soft leather desert boots, lightweight scarf draped over shoulders, minimalist leather pouch. POSE: Standing firmly on sand dune, shoulders squared, slight wind movement. CAMERA VIEW: Full body centered composition. LIGHTING: Golden desert sunlight with warm highlights. SCENE: Sahara desert dunes with clear sky and rolling sand in background. STYLE: Minimalist nomadic couture editorial. COLOR-TONE: Beige, sand, soft brown accents, warm golden light." )

# 69 · Ethiopia / Harar — Urban Heritage Fusion
prompts+=( "Harar — Urban Heritage Fusion. SUBJECT: Ethiopian man late 20s, short curly hair, trimmed beard, expressive dark eyes, confident direct gaze. BODY: Slim modern silhouette. CLOTHING: Tailored contemporary jacket in deep burgundy with subtle geometric embroidery inspired by Harari patterns, fitted black turtleneck underneath, tapered charcoal trousers, sleek black leather boots, structured crossbody leather bag, minimal silver pendant referencing traditional Ethiopian cross geometry. POSE: Standing relaxed with hands in jacket pockets. CAMERA VIEW: Full body shot, slightly low angle. LIGHTING: Warm evening light with soft urban glow. SCENE: Harar old town colorful alleyways. STYLE: Urban couture editorial with heritage fusion. COLOR-TONE: Burgundy, black, charcoal, warm earth highlights." )

# 70 · Cuba / Modern Cuban Minimalism
prompts+=( "Modern Cuban Minimalism. SUBJECT: Cuban man, early 30s, expressive eyes, subtle smile. BODY: Slim, relaxed stance. CLOTHING: Minimalist white tailored guayabera-inspired shirt with structured pleats running vertically across torso, hidden snap closure, slightly oversized silhouette; wide-leg sand trousers with pressed crease; white leather minimalist sneakers; fine gold cuff bracelet; small embroidered motif at collar referencing Afro-Cuban symbolism in tonal thread. POSE: Standing in Havana subway station entrance, hands in pockets, direct eye contact. CAMERA VIEW: Full body symmetrical composition. LIGHTING: Soft natural daylight from station entrance. SCENE: Modern Havana metro entrance with concrete and tiled textures. STYLE: Clean contemporary couture editorial. COLOR-TONE: Neutral whites, sand, subtle gold accents." )

# ---- QUEUE JOBS ------------------------------------------------------------
for (( i=0; i<${#prompts[@]}; i++ )); do
  queue_job $((i+1)) "${prompts[$i]}"
done

echo "✅ All ${#prompts[@]} jobs queued in scheduler"
