#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Biting lips — photo and illustration, hot or melancholy, playful or dramatic
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+18+-+biting+lips
# Structure: 10 models × 5 prompts = 50 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "Close-up portrait of a young woman biting her lower lip, caught mid-thought, eyes cast slightly downward with a glimmer of restrained emotion. Shot on medium format film, warm golden-hour backlight creating a soft rim glow around loose strands of dark hair falling across her cheek. Her lip gloss catches the light — deep cherry red against ivory skin. Shallow depth of field dissolves the background into warm amber bokeh. The composition is tight, cropped just above the brows to just below the chin, slightly off-center. Mood: longing with a quiet electricity. Analog grain, muted warm palette, editorial fashion photography aesthetic, Vogue Italia circa 2008 sensibility." \
  "Claude Sonnet 4.6" "Crimson Confession"

queue_job  2 \
  "High-contrast black and white fine-art photograph of lips mid-bite — teeth pressing into the full lower lip, caught at peak tension. Extreme macro crop, filling nearly the entire frame from corner to corner. Studio strobe lighting rakes across the surface of the skin at a sharp angle, carving deep shadows into every subtle contour. A single tear-like droplet of water on the lip surface catches pure specular highlight. No eyes visible, no context — just the gesture, raw and isolated. Hard shadows, graphic composition, silver gelatin darkroom aesthetic. Emotional register: suppressed pain blurring into desire." \
  "Claude Sonnet 4.6" "Salt & Violet"

queue_job  3 \
  "Pop-art digital illustration of a stylized face, eyes wide and mischievous, teeth playfully sinking into an oversized pastel pink bubble about to burst. Bold black ink outlines, flat graphic fills in a palette of bubblegum pink, lemon yellow, and electric mint. Background is a swirling halftone pattern in contrasting coral. Thick lashes, exaggerated lip proportions, retro comic-book anatomy. Small sparkle starburst accents scattered around the mouth area. The energy is cheeky and kinetic — right on the edge of chaos. Inspired by Roy Lichtenstein meets contemporary Instagram illustration. Square format with tight, centered symmetry broken only by the asymmetry of the bite." \
  "Claude Sonnet 4.6" "Bubblegum Spiral"

queue_job  4 \
  "Cinematic still — a woman stands alone under a single streetlamp in a rain-slicked alley at night, biting her lip as she stares at something just outside the frame. Long dark coat, wet hair plastered across her jaw. Neon reflections — deep magenta and cold teal — pool across the wet cobblestones at her feet. The lighting is theatrical and remorseless: one hard source, deep fill shadow, practical neon glow as secondary. Color grade: crushed blacks, lifted shadows, highly saturated neons against desaturated skin. The atmosphere is unmistakably noir. Mood: waiting for something that may never arrive. Anamorphic lens distortion, blue-hour color temperature, cinematic widescreen aesthetic adapted to square crop." \
  "Claude Sonnet 4.6" "Lacquer & Rain"

queue_job  5 \
  "Delicate fine-art illustration in the style of a hand-painted porcelain miniature — a face rendered in soft gouache washes of blush rose, porcelain white, and faded sage. The subject bites the corner of their lip in a private, unguarded moment, eyes half-closed, expression somewhere between dreaming and grieving. Brushwork is loose yet precise, with visible pigment texture and watercolor blooms softening the edges of shadow. A single sprig of dried lavender floats in the upper corner of the composition. The overall palette is hushed and antique — the kind of image that feels like it was found pressed inside a century-old letter. Melancholy, tender, achingly quiet." \
  "Claude Sonnet 4.6" "The Porcelain Habit"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A close-up cinematic photograph capturing a raw, emotional moment in a Cyber-Noir setting. The subject is a woman with a sharp jawline, her face partially obscured by shadows and rain streaks on a windowpane. She is biting her lower lip intensely in a moment of quiet anxiety or deep longing. The scene is illuminated by the harsh, high-contrast glow of an amber neon sign from the street below, casting deep shadows across her features and creating a stark contrast against the dark background. Vivid red lipstick is smeared slightly at the corner of her mouth, drawing focus to the sharp detail of her teeth pressing into her lip. The style mimics 35mm film with a moody, atmospheric grain, focusing heavily on textures, micro-expressions, and a dramatic, intense color palette that evokes a powerful sense of modern isolation and cinematic drama." \
  "Gemini 3.5 Flash" "Neon Melancholy: The Glass Reflection"

queue_job  7 \
  "A high-contrast digital illustration in a dramatic Sin City style, featuring a powerful composition focused entirely on an expressive face. A man with a brooding expression bites his lower lip, a subtle gesture conveying suppressed tension and high-stakes drama. The artwork relies on a stark monochromatic palette of deep blacks and crisp whites, abruptly broken by a singular, striking accent of intense amber light cutting across his lips and eyes. The lines are sharp and deliberate, resembling a detailed graphic novel or heavy pencil sketch. Raindrops fall vertically through the frame, catching the minimal light source and adding texture to the dark, atmospheric background. The entire focus is pulled toward the tight, sharp detail of the mouth and the raw, unrefined emotion of the bite, creating a gripping, eye-catching, and aesthetically pleasing visual narrative." \
  "Gemini 3.5 Flash" "Cyber-Noir: Midnight Confession"

queue_job  8 \
  "A minimalist yet highly detailed close-up shot capturing a playful and lighthearted moment. The camera focuses closely on the lower half of a face, where a subtle, flirtatious smile is paired with a gentle biting of the lower lip. The aesthetic is clean and modern, utilizing a soft-focus background that keeps the viewer's eye locked onto the intricate details of the skin texture and the gloss on the lips. A single, vibrant crimson color accent illuminates the lips, making them pop against an otherwise muted, desaturated, and high-contrast environment. The lighting is directional and crisp, defining the contours of the mouth and the slight indentation of the teeth perfectly. It is a striking blend of contemporary portrait photography and precise graphic design, balancing a light mood with an incredibly sharp, compelling, and beautifully balanced composition." \
  "Gemini 3.5 Flash" "Crimson Accent: The Hidden Smile"

queue_job  9 \
  "An atmospheric, moody photo capturing a moment of deep melancholy and introspection. A close-up profile view shows a person lost in thought, their teeth firmly but slowly biting down on their lower lip as if holding back a flood of words. The lighting is deeply cinematic, coming from a single, warm amber source that cuts through a dark, shadow-drenched background, highlighting the edge of the profile, the texture of the skin, and the gloss of the lip. The composition uses a strong chiaroscuro effect, creating an intense contrast between light and shadow. The grain is fine and filmic, giving the image a timeless, raw quality. Every detail, from the slight crease of the skin to the wetness of the lips, is rendered with absolute clarity, creating a striking, poignant, and visually arresting aesthetic." \
  "Gemini 3.5 Flash" "Amber Glow: Solitary Thought"

queue_job 10 \
  "A dramatic, theatrical illustration capturing a high-tension, cinematic pause. The subject is framed in a tight close-up, biting their lower lip with an expression of pure determination mixed with vulnerability. The style blends the texture of a traditional pencil sketch with sharp, modern digital rendering, featuring heavy contrast and deep black ink shadows. The entire scene is dark, except for a piercing beam of selective red light that illuminates the mouth and jawline, casting long, dramatic shadows. The focus is incredibly sharp on the interaction between the teeth and the lip, capturing the exact point of pressure with extreme detail. The background is a void of dark, textured gradients, ensuring that the eye-catching contrast and the vibrant red accent immediately command attention, delivering a powerful, aesthetically pleasing punch." \
  "Gemini 3.5 Flash" "The Stage Light: Intense Pause"

# --- ChatGPT ---
queue_job 11 \
  "A close-up portrait capturing a person gently biting their lower lip, framed in soft, diffused lighting that wraps the face in a cinematic glow. The mood is suspended between anticipation and restraint, with slightly parted lips and a subtle tension in the jawline. Skin texture is hyper-realistic, with fine details like pores and faint freckles visible. The background is blurred into creamy bokeh, with warm amber and muted rose tones creating an intimate atmosphere. Hair falls loosely, slightly tousled, catching highlights. The eyes are half-lidded, gaze unfocused as if lost in thought. The composition emphasizes the lips as the focal point, with a shallow depth of field and a painterly softness that evokes both vulnerability and quiet allure." \
  "ChatGPT" "Velvet Hesitation"

queue_job 12 \
  "An urban night scene drenched in neon reflections, where a figure stands under flickering signage, biting their lip in a moment of charged emotion. The lighting is bold — electric blues, magentas, and deep violets streak across the face, creating high-contrast shadows. The lips catch a sharp highlight, slightly glossy, drawing immediate attention. Raindrops cling to skin and hair, adding texture and atmosphere. The expression is ambiguous — somewhere between defiance and longing. The camera angle is slightly tilted for a dynamic, cinematic feel. Reflections ripple across puddles in the background, echoing the color palette. The overall aesthetic leans toward cyberpunk realism with a dramatic, almost film-noir intensity." \
  "ChatGPT" "Neon Pulse Bite"

queue_job 13 \
  "A delicate, sunlit scene of someone by a window, absentmindedly biting their lip while lost in thought. Golden morning light filters through sheer curtains, casting soft shadows across the face. The palette is warm and airy — creamy whites, pale golds, and gentle skin tones. The subject wears minimal makeup, emphasizing natural beauty and authenticity. Hair is loosely tied or falling naturally, catching the sunlight. The expression is introspective, almost melancholic, with eyes gazing outward beyond the frame. The lip bite is subtle, more unconscious than intentional. Fine dust particles float in the light beams, enhancing the dreamy atmosphere. The composition feels intimate and quiet, like a candid moment frozen in time." \
  "ChatGPT" "Soft Morning Reverie"

queue_job 14 \
  "An expressive illustration in oil-paint style, focusing on a dramatic lip-biting gesture rendered with thick, textured brushstrokes. The color palette is rich — deep reds, burgundy, and hints of gold leaf accents. The lips are the central element, painted with exaggerated detail and contrast, while the rest of the face dissolves into abstract strokes and blended shadows. The background is a moody gradient, transitioning from dark plum to near-black. Light appears to emanate from within the painting, highlighting the contours of the lips and fingers. The emotion is intense, bordering on theatrical, evoking themes of desire, tension, and inner conflict. The style merges classical portraiture with modern abstraction." \
  "ChatGPT" "Painterly Crimson Study"

queue_job 15 \
  "A vibrant, stylized illustration with a playful tone, featuring a character biting their lip in a teasing, lighthearted way. The art style is clean and graphic, inspired by pop art and modern digital illustration. Colors are bold — bubblegum pinks, bright corals, and crisp whites, contrasted with sharp black outlines. The lips are slightly exaggerated, glossy, and central to the composition. The character's expression is cheeky, with a raised eyebrow or a subtle smirk. Background elements include simple geometric shapes or comic-style halftone patterns. Lighting is flat but intentional, enhancing the graphic appeal. The overall vibe is energetic and eye-catching, balancing flirtation with a sense of humor." \
  "ChatGPT" "Playful Pop Bite"

# --- Grok ---
queue_job 16 \
  "A captivating close-up portrait of a beautiful young woman with glossy full lips gently biting her lower lip in a sensual expression, her eyes half-closed with intense desire, soft dramatic lighting highlighting her flawless skin with subtle freckles, strands of dark wavy hair falling across her face, wearing a delicate black lace choker, moody cinematic atmosphere with deep red and warm golden tones, shallow depth of field, ultra-realistic photography, highly detailed skin texture, glistening lips, seductive and confident mood, elegant composition, masterpiece, best quality, intricate details, photorealistic, 8k." \
  "Grok" "Seductive Crimson Lip Bite"

queue_job 17 \
  "Elegant illustration of a mysterious woman pressing her forehead against a rain-streaked window at dusk, softly biting her lower lip with a thoughtful and melancholic expression, soft blue and purple color palette, delicate watercolor and ink style mixed with digital painting, tear-like raindrops running down the glass reflecting city lights, long dark lashes, pale skin, flowing silk blouse slipping off one shoulder, dreamy and emotional atmosphere, gentle sorrow mixed with quiet beauty, soft volumetric lighting, intricate details, ethereal and hauntingly beautiful, high resolution art." \
  "Grok" "Melancholy Rainy Window"

queue_job 18 \
  "Vibrant photorealistic portrait of a joyful young woman with sun-kissed skin biting her lip playfully while smiling, bright natural daylight, golden hour lighting creating warm highlights, freckles across nose, messy beach waves in her light brown hair, wearing a white crop top, sparkling mischievous eyes looking directly at viewer, fresh and flirty summer vibe, cherry blossom petals gently floating around, soft bokeh background with green foliage, energetic and charming mood, crystal clear details, lively composition, ultra-detailed, vibrant colors." \
  "Grok" "Playful Summer Glow"

queue_job 19 \
  "Cinematic black and white dramatic portrait of a femme fatale biting her lip with intense gaze, strong chiaroscuro lighting with deep shadows and bright highlights, 1940s film noir style, elegant vintage dress with low neckline, cigarette smoke swirling around her face, sharp cheekbones, perfect glossy lips, mysterious and dangerous allure, high contrast, film grain texture, moody atmosphere, sophisticated and seductive, ultra-realistic photography, intricate facial details, masterpiece quality, atmospheric depth." \
  "Grok" "Dramatic Noir Shadow"

queue_job 20 \
  "Stunning digital illustration of an ethereal fantasy woman with flower crown biting her lip in dreamy ecstasy, surrounded by glowing fireflies and blooming night flowers in a magical forest, soft pastel and luminescent color scheme with glowing particles, delicate fantasy art style, flowing translucent dress, long silver hair floating in gentle breeze, soft moonlight filtering through trees, sensual yet innocent expression, enchanting and aesthetically breathtaking, intricate botanical details, magical atmosphere, highly detailed, whimsical beauty, masterpiece." \
  "Grok" "Ethereal Fantasy Bloom"

# --- Copilot ---
queue_job 21 \
  "A close-up of lips caught mid-bite, soft skin illuminated by warm golden light, the subtle tension between desire and restraint. The atmosphere feels intimate yet restrained, as if holding back words or emotions. Shadows play across the face, highlighting the curve of the mouth and the delicate pressure of teeth against lip. The mood is both alluring and contemplative, balancing sensuality with quiet melancholy. This image should evoke curiosity, leaving viewers wondering whether the bite is playful, nervous, or deeply passionate." \
  "Copilot" "Velvet Tension"

queue_job 22 \
  "A dreamy illustration of lips gently biting, surrounded by pastel tones and whimsical brush strokes. The style is lighthearted, almost cartoonish, with exaggerated softness and playful energy. The lips are central, glowing with a subtle blush, while abstract shapes swirl around them like floating thoughts. The bite feels teasing, mischievous, and fun, capturing the spirit of flirtation without heaviness. The overall vibe is airy and charming, inviting viewers into a moment of light affection and cheeky humor." \
  "Copilot" "Playful Whisper"

queue_job 23 \
  "A cinematic portrait of lips biting under dim, moody lighting, with rain streaks on a window in the background. The atmosphere is heavy, filled with longing and unresolved tension. The lips are slightly trembling, caught between vulnerability and strength, as if holding back tears or words. The bite becomes symbolic of inner conflict, a gesture of both control and surrender. The muted palette of blues and grays enhances the dramatic tone, making the image feel like a still from a poignant film." \
  "Copilot" "Silent Drama"

queue_job 24 \
  "A bold, neon-inspired artwork of lips biting, glowing under vibrant pinks and purples. The style is modern, edgy, and electrifying, with sharp contrasts and luminous highlights. The lips shimmer with gloss, reflecting the neon lights, while abstract geometric shapes pulse around them like energy waves. The bite is confident, unapologetic, and magnetic, radiating raw attraction. This image should feel powerful and captivating, a visual explosion of passion and intensity that grabs attention instantly." \
  "Copilot" "Electric Desire"

queue_job 25 \
  "An artistic black-and-white sketch of lips biting, rendered with delicate pencil strokes and subtle shading. The simplicity of monochrome emphasizes emotion rather than glamour, creating a timeless, melancholic aura. The bite feels hesitant, almost fragile, as if holding back words left unsaid. The texture of the drawing adds depth, with soft smudges suggesting fading memories. The overall mood is nostalgic and bittersweet, evoking the quiet ache of longing and the beauty of restraint." \
  "Copilot" "Bittersweet Echo"

# --- Mistral ---
queue_job 26 \
  "A close-up of a person playfully biting their lower lip, eyes sparkling with mischief, surrounded by floating pastel-colored bubbles and soft golden light. The scene is whimsical and dreamy, with a shallow depth of field that blurs the background into a soft, creamy bokeh. The subject wears a subtle, knowing smile, their expression a mix of innocence and flirtation. The lighting is warm and diffused, casting a gentle glow on their skin, while delicate cherry blossom petals drift lazily in the foreground, adding a touch of magic. The composition is balanced, with the subject slightly off-center, creating a sense of intimacy and connection with the viewer." \
  "Mistral" "Playful Temptation"

queue_job 27 \
  "A solitary figure sits by a rain-streaked window, biting their lip in quiet contemplation, their gaze lost in the distance. The mood is introspective and bittersweet, with cool, muted tones of deep blues and soft grays dominating the palette. A single shaft of pale light cuts through the scene, illuminating their face and the droplets of rain sliding down the glass. Their expression is a mix of longing and resignation, captured in a moment of raw vulnerability. The background is minimalist, with a faint outline of a cityscape blurred by the rain, emphasizing the emotional weight of the moment." \
  "Mistral" "Melancholic Reverie"

queue_job 28 \
  "A high-contrast, cinematic portrait of a person biting their lip, their face half-lit by a dramatic chiaroscuro effect. The lighting is bold and directional, casting sharp shadows that accentuate their cheekbones and the curve of their lips. Their eyes are intense and smoldering, locked onto the viewer with a magnetic pull. The background is dark and moody, with a hint of deep red or crimson, adding a sense of passion and mystery. The texture of their skin is hyper-detailed, with a slight sheen that catches the light, giving the image a tactile, almost three-dimensional quality." \
  "Mistral" "Dramatic Allure"

queue_job 29 \
  "A surreal, otherworldly depiction of a person biting their lip, their features glowing with an inner light. The scene is infused with a soft, ethereal glow, as if they are made of stardust and moonlight. Their hair and clothing seem to float weightlessly, as though submerged in water or a gentle breeze. The color palette is a mix of iridescent purples, blues, and silvers, creating a dreamlike atmosphere. Delicate, glowing particles swirl around them, adding a sense of magic and wonder. The composition is symmetrical, with the subject at the center, drawing the viewer into their enchanting gaze." \
  "Mistral" "Ethereal Fantasy"

queue_job 30 \
  "A striking, high-energy portrait of a person biting their lip, their expression bold and confident. The lighting is harsh and directional, creating strong contrasts and sharp lines that emphasize their features. Their makeup is dramatic, with dark, smoky eyes and a deep, matte lip color that pops against their skin. The background is a vibrant, neon-lit urban setting, with graffiti and geometric patterns adding a modern, edgy vibe. The colors are saturated and electric, with hot pinks, electric blues, and neon purples dominating the scene. The composition is dynamic, with the subject slightly tilted, giving the image a sense of movement and energy." \
  "Mistral" "Bold and Edgy"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A close-up portrait of a young woman with glossy, crimson-stained lips gently biting her lower lip in a moment of playful anticipation. Her skin glows with a warm, cinematic golden-hour backlight that highlights subtle freckles across her nose. She wears a delicate silk slip top that slips slightly off one shoulder, adding an effortless, sultry elegance. Soft bokeh background suggests an upscale urban balcony at dusk, with blurred city lights shimmering like scattered diamonds. The lighting wraps around her face, casting gentle shadows that accentuate her jawline and the subtle tension in her expression. Her eyes are partially closed, conveying a mix of quiet confidence and flirtatious curiosity. The composition is tightly framed, focusing entirely on the intimate gesture of her lips." \
  "Qwen 3.6 Plus" "Midnight Velvet Temptation"

queue_job 32 \
  "A delicate digital illustration portraying a solitary figure standing by a rain-streaked window, their fingers lightly pressed against the glass as they unconsciously bite their lower lip in quiet contemplation. The color palette leans into cool desaturated blues and muted grays, punctuated only by the soft warmth of a single amber streetlamp glowing through the condensation. Their hair falls in loose, wind-tousled waves, framing a face marked by subtle shadows and expressive, downcast eyes. The lip-biting gesture feels deeply introspective, capturing a fleeting moment of restrained emotion. Fine linework and painterly brush textures blend seamlessly, creating a mood of poetic melancholy." \
  "Qwen 3.6 Plus" "Echoes of Unspoken Longing"

queue_job 33 \
  "A striking studio photograph capturing a model mid-gesture as she bites her lower lip, exuding an intense, magnetic energy. High-contrast chiaroscuro lighting carves sharp shadows across her cheekbones and collarbone, while a bold rim light catches the moisture on her lips, making them appear irresistibly vivid and textured. She wears a minimalist black turtleneck that contrasts starkly against her porcelain complexion, drawing the viewer's gaze directly to the tension in her mouth. The backdrop is a seamless gradient of deep charcoal fading into obsidian. Her eyes lock directly with the camera, holding a gaze that balances defiance and vulnerability. The shallow depth of field blurs the edges slightly, creating a visually arresting, high-impact fashion portrait." \
  "Qwen 3.6 Plus" "Crimson Tension in Studio Light"

queue_job 34 \
  "A vibrant, stylized illustration featuring a cheerful young woman sitting on a sun-drenched park bench, casually biting her lower lip while glancing sideways with a mischievous smirk. She holds a half-eaten strawberry tart in one hand, leaving a smudge of powdered sugar on her thumb. The artwork uses a bright, pastel-heavy palette with clean cel-shaded rendering and soft gradient overlays that evoke a warm spring afternoon. Her oversized knit sweater slips playfully off her shoulders, and wind-swept bangs frame a face radiating lighthearted charm. Delicate highlight strokes catch the gloss on her lips and the sparkle in her wide, animated eyes. The background blooms with loosely painted cherry blossoms and dappled sunlight." \
  "Qwen 3.6 Plus" "Sunlit Daydreams and Cherry Gloss"

queue_job 35 \
  "A moody, atmospheric photograph of a woman reclining on a weathered velvet chaise, her head tilted back as she gently bites her lower lip in a gesture of restrained passion. Warm, directional window light spills across her bare shoulders and collarbones, casting long, elegant shadows that stretch across the dimly lit room. Her lips are naturally full, highlighted with a subtle sheen that catches the ambient glow, while her gaze remains softly unfocused, lost in thought. The surrounding environment features rich, textured fabrics and antique brass accents that evoke a sense of timeless romance. A shallow depth of field keeps the composition intimate, blurring the ornate wallpaper into painterly washes of burgundy and gold." \
  "Qwen 3.6 Plus" "Velvet Shadows and Quiet Fire"

# --- GLM 5.1 ---
queue_job 36 \
  "Cinematic close-up portrait of a gorgeous woman biting her lower lip, expressing intense desire and anticipation. Her eyes are smoldering, locking directly with the viewer. Dramatic chiaroscuro lighting with deep, moody shadows and a soft, warm rim light highlighting her cheekbone and jawline. Tiny droplets of sweat glisten on her skin. The background is an out-of-focus neon-lit rainy city street at night, casting subtle crimson and sapphire reflections on her face. High fashion makeup, slightly smudged eyeliner, voluminous messy hair clinging to her neck. Shot on 85mm lens, f/1.4, extreme detail, photorealistic, 8k resolution, raw emotion, highly aesthetic, captivating atmosphere." \
  "GLM 5.1" "Neon Desire"

queue_job 37 \
  "Breathtaking digital illustration of a melancholic young woman gently biting her lower lip, lost in deep thought. Her gaze is averted downward, a single tear tracing her cheek. Ethereal, soft lighting filters through a frosted window, casting a pale blue glow over her delicate features. She wears an oversized, knitted cream sweater, damp from the rain. The background features blurred, withering autumn botanicals in muted sepia and grey tones, creating a sorrowful yet beautiful atmosphere. Delicate brushstrokes, watercolor and ink style, anime-inspired semi-realism, profound emotional storytelling, cinematic composition, soft bokeh, muted color palette, expressive, evocative, intricate details, masterpiece." \
  "GLM 5.1" "Autumn Melancholy"

queue_job 38 \
  "Vibrant fashion photography of a playful young woman biting her lip with a mischievous smile. Bright, crisp studio lighting against a vivid pastel pink background. She is blowing a large, iridescent pink bubblegum bubble that has just popped, sticking to her lips and nose. Her makeup is glossy and flawless, with sparkling highlighter and vibrant eyeshadow. She wears a retro-futuristic metallic silver jacket. Confetti is falling around her in mid-air. Shot with a macro lens, hyper-detailed skin texture, wet lip gloss reflection, upbeat and energetic mood, pop-art aesthetic, high contrast, colorful, dynamic composition, magazine editorial style, ultra-crisp." \
  "GLM 5.1" "Bubblegum Pop"

queue_job 39 \
  "Classical baroque oil painting of a handsome nobleman biting his lower lip in a moment of intense inner conflict and dramatic tension. Rich, deep color palette dominated by velvet crimson, burnt sienna, and absolute black. Dramatic chiaroscuro lighting illuminates his sharp jawline, the tense muscles of his neck, and the subtle indent of his teeth on his lip. He wears an ornate, ruffled colonial shirt with a loose silk cravat. The background is a swirling, stormy sky barely visible through a heavy velvet curtain. Masterpiece, Rembrandt style, thick impasto brushstrokes, museum quality, intense emotional gravity, highly aesthetic." \
  "GLM 5.1" "Baroque Tension"

queue_job 40 \
  "Hyper-realistic 3D render of a stunning cyberpunk android biting her synthetic lip, revealing a glowing neon-blue circuitry underneath the torn silicone skin. She has intense, piercing holographic eyes that glow with fierce intelligence. The scene is bathed in dramatic magenta and cyan neon lights from a futuristic dystopian alleyway. Raindrops splash on her metallic collarbone, creating dynamic splashes. Intricate mechanical details, carbon fiber textures, and glossy wet reflections on her cybernetic enhancements. Cinematic depth of field, Unreal Engine 5 aesthetic, octane render, sharp focus, sci-fi masterpiece, edgy, alluring, dramatic rim lighting, visually striking, incredibly detailed, awe-inspiring." \
  "GLM 5.1" "Cybernetic Glitch"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A hyper-detailed close-up portrait capturing the moment of biting a soft lower lip, eyes half-lidded with restrained emotion. Dramatic chiaroscuro lighting carves sharp shadows across porcelain skin, illuminating the plush texture of the lip caught between teeth. Deep crimson and midnight blue color palette creates a cinematic noir atmosphere. Wisps of dark hair frame the face while a single tear glistens on the cheek, suggesting unspoken longing. The composition emphasizes raw vulnerability and smoldering intensity, with shallow depth of field blurring the background into velvety darkness. Every pore and lip crease rendered with photorealistic precision, evoking a tension between desire and melancholy that feels both intimate and universally human." \
  "Kimi K2.6 Thinking" "Velvet Tension"

queue_job 42 \
  "A vibrant editorial-style photograph of a young woman biting her lower lip while suppressing a playful laugh, golden afternoon sunlight streaming through her hair. She wears an oversized linen shirt with sleeves rolled up, standing in a sun-drenched field of wildflowers. Warm honey and amber tones dominate the palette, with lens flares creating dreamy halos around her silhouette. Her eyes crinkle with genuine joy, capturing a candid moment of flirtatious spontaneity. The breeze lifts stray strands of hair across her face, adding dynamic movement to the composition. Shallow depth of field renders the meadow into a soft impressionistic blur of yellows and greens, emphasizing the carefree, lighthearted energy of a perfect summer afternoon frozen in time." \
  "Kimi K2.6 Thinking" "Sun-Kissed Mischief"

queue_job 43 \
  "A hauntingly beautiful watercolor illustration of a figure biting their lower lip while gazing through rain-streaked glass, city lights bleeding into abstract washes of indigo and violet. The subject's pale skin appears almost translucent against the gloom, with droplets of water catching in their eyelashes like tiny diamonds. Muted teals and stormy grays swirl together in fluid, expressive brushstrokes that suggest both movement and stillness. The lip caught between teeth shows a hint of natural pink, the only warm color in a world of cool isolation. Reflections fragment the composition into overlapping layers of reality and mirror-image, creating a poetic visual metaphor for inner turmoil held silently behind a bitten lip and distant, unfocused eyes." \
  "Kimi K2.6 Thinking" "Rain-Stained Melancholy"

queue_job 44 \
  "A bold, high-fashion digital illustration featuring extreme close-up of glossy crimson lips biting down with deliberate intensity, surrounded by swirling ribbons of liquid gold and black silk. The skin appears airbrushed to porcelain perfection, with dramatic winged eyeliner and sharp cheekbones creating a powerful, dominant aesthetic. Neon red and deep burgundy tones pulse against a void-black background, while scattered rose petals and droplets of honey add tactile sensuality to the composition. The lighting is deliberately theatrical, with a single harsh spotlight creating stark highlights on the teeth indenting the plush lower lip. This image radiates unapologetic confidence and magnetic allure, blending hyper-stylized beauty with raw, palpable tension in every meticulously rendered detail." \
  "Kimi K2.6 Thinking" "Crimson Obsession"

queue_job 45 \
  "A dreamy soft-focus illustration of a girl biting her lower lip in shy contemplation, surrounded by floating pastel clouds and crystalline bubbles that catch prismatic light. Her hair drifts weightlessly in cotton-candy pink and lavender hues, blending seamlessly with the surreal candy-colored sky. The expression balances innocence and intrigue, with oversized luminous eyes and delicate freckles dusted across flushed cheeks. Ethereal lighting bathes everything in a gentle glow, creating soft rim-light around her profile. Whimsical elements like tiny paper airplanes and flower petals orbit around her head, adding playful movement. The aesthetic merges kawaii culture with fine art sensibilities, resulting in an enchanting, emotionally resonant image that feels both nostalgic and freshly modern." \
  "Kimi K2.6 Thinking" "Pastel Reverie"

# --- Deepseek ---
queue_job 46 \
  "A cinematic close-up portrait of a young woman with tear-streaked cheeks, her lower lip caught gently between her teeth as she looks away from the camera, dim streetlight bleeding through rain-speckled window behind her. Soft bokeh of neon signs in deep blues and bruised purples. Her hand half-raised as if to speak, then stopping. The lip bite is hesitant, aching — a mix of regret and longing. She wears a worn leather jacket, collar turned up. Slight motion blur on her fingers. Atmosphere heavy with unsaid words. Shot on 35mm film grain, shallow depth of field focusing on the tension in her jaw and the glossy, bitten lip. Melancholic, intimate, like a still from a Wong Kar-wai film." \
  "Deepseek" "Midnight Confession"

queue_job 47 \
  "Vibrant pop-art illustration of a playful, androgynous figure winking while biting their bright red lower lip, a glossy cherry perched between their teeth like a third lip. Comic book halftone dots and bold black outlines, background of exploding hearts and sparkles in hot pink, electric yellow, and cyan. Tongue slightly touching the cherry stem. The expression is mischievous, flirtatious, yet slightly unhinged. Sharp angular shading, retro 1960s pop art meets modern anime. Lip gloss shines like wet candy. No shadows — flat color blocks with dynamic contrast. Lighthearted, cheeky, and irresistibly eye-catching. The cherry juice drips just a little, staining the chin." \
  "Deepseek" "Cherry Pop Illustration"

queue_job 48 \
  "High-fashion black-and-white photograph of a model in a couture veil, biting her lower lip hard enough to leave a crescent imprint. Studio lighting from one side creates dramatic chiaroscuro, casting half her face in deep shadow. The lip bite is not playful but fierce — a controlled, angry tension. Her eyes are piercing, almost wet. A single pearl earring swings slightly out of focus. Veil fabric is silk tulle with tiny embroidered roses. Skin texture hyper-realistic, pores and fine hairs visible. Mood is dark romanticism with an edge of violence. The bitten lip is swollen, slightly darker. No smile. Elegance as a weapon. Gritty yet luxurious, like Helmut Newton meets Irving Penn." \
  "Deepseek" "Bitter Elegance"

queue_job 49 \
  "Soft, sun-drenched digital painting of a teenager lounging on a rumpled bed, absently biting their lower lip while scrolling a phone. Warm golden hour light through lace curtains casts striped shadows across bare legs and an oversized band t-shirt. The lip bite is idle, unconscious — a habit of boredom or mild frustration. Expressive brushstrokes, slightly impressionistic. Their other hand twists a strand of hair. A half-empty glass of orange juice sweats on the nightstand. Wrinkled sheets in pale lavender. The mood is languid, slightly sad, very human. Lips are chapped, bitten pink. No drama, just quiet inertia. Aesthetic of lazy Sundays and unspoken teenage yearning." \
  "Deepseek" "Afternoon Sulk"

queue_job 50 \
  "Fantasy illustration of a sea creature with iridescent scales, emerging from dark turquoise water, biting her full lower lip while holding a glowing pearl. Her eyes are hypnotic, vertical pupils like a snake's. The lip bite is seductive and predatory — drawing a tiny bead of blood that turns into a red coral gem. Bioluminescent jellyfish float in the background, casting cool blue light. Wet hair plastered to her temples, water droplets frozen mid-fall. Style is digital art with a painterly finish, like Art Nouveau meets dark fairy tale. The tension between her sharp teeth and soft lip creates a dangerous allure. Mysterious, hot, with a hint of threat. Deep teal and magenta color palette." \
  "Deepseek" "Siren's Sting"

echo "✅ All 50 jobs queued in scheduler"
