#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Award-winning professional street photography
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+19+-+street+photography
# Structure: 10 models × 5 prompts = 50 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A solitary figure in a hooded jacket stands at a rain-slicked intersection in a dense Asian metropolis, surrounded by cascading neon signage in Cantonese and English. Puddles mirror fragmented reflections of red and cyan light across the asphalt. Shot at eye level with a 35mm lens, wide aperture rendering background bokeh into soft luminous orbs. The subject occupies the left third of the frame, anonymous and contemplative. Color palette dominated by deep teals, electric reds, and cold blacks. Cinematic grain texture throughout. Ambient humidity visible in the air. Documentary-style composition with decisive-moment timing. No posed elements. Urban solitude theme. Shot in the style of a World Press Photo finalist, Magnum aesthetic, saturated shadows, rich midtone contrast." \
  "Claude Sonnet 4.6" "Midnight Neon Reflections"

queue_job  2 \
  "High-contrast monochrome street photograph taken inside a moving subway car during rush hour. Motion blur streaks commuters into ghost-like elongated forms while one sharp elderly woman seated center-frame stares directly into the lens with weathered dignity. Available light only — overhead fluorescent casting harsh top-down shadows under eyes and jaw. Film grain emulation at ISO 3200. Deep blacks and blown highlights intentional. Composition follows classical rule of thirds, foreground handrail framing subject. Emotional weight in stillness versus chaos. Documentary realism, no digital manipulation. Shot in the spirit of Daido Moriyama, Vivian Maier — stark, confrontational, unapologetically raw. Timeless metropolitan loneliness rendered in silver gelatin aesthetic." \
  "Claude Sonnet 4.6" "Ghost Train, Black and White"

queue_job  3 \
  "Monochromatic street scene of a crowded pedestrian crossing in a grey overcast European city, entirely desaturated except for a single vivid crimson umbrella held by a child walking hand-in-hand with an adult. The child faces away from the camera. Rain falls diagonally. Wet cobblestones reflect the isolated red. Surrounding crowd rendered as a sea of grey silhouettes in motion blur. Shallow depth of field isolates the pair without removing them from the crowd. Compositional tension between intimacy and anonymity. Shot angle slightly elevated, 50mm equivalent perspective. Mood is bittersweet and poetic. Color grading inspired by Schindler's List selective color technique. Award-winning editorial photography atmosphere with quiet emotional resonance." \
  "Claude Sonnet 4.6" "Selective Color — The Red Umbrella"

queue_job  4 \
  "Award-winning fine art street photography double exposure: a close-up portrait of a middle-aged man's profile, weathered face, strong jaw, looking left — layered seamlessly with a wide-angle skyline of a dense urban canyon at golden hour. Skyscrapers, fire escapes, and window grids map themselves across the skin texture, cheekbones becoming rooftops, wrinkles becoming streets. Warm amber and ochre tones dominate. Film-style double exposure technique, analog feel with subtle halation and soft grain. The city lives inside the man; the man contains the city. Inspired by conceptual editorial portraiture, National Geographic documentary style. Seamless tonal integration between both exposures. Dark vignette border. Quiet philosophical narrative about urban identity and belonging." \
  "Claude Sonnet 4.6" "Double Exposure — City and Portrait"

queue_job  5 \
  "Street-level wide shot of a chaotic Mumbai spice market at golden hour. Airborne turmeric and chili dust catches the raking low sunlight, creating volumetric god-rays cutting through the scene. Vendors in vivid saris and lungis mid-gesture, arguing over price, pouring grain. Foreground sacks of saffron, vermillion, and indigo frame the lower edge. Motion in the middle distance contrasts with sharp focus on a single vendor's expressive face in the right third. Color palette overwhelmingly warm — deep golds, burnt oranges, scarlet — with long shadow geometry striping the ground. Shot on a wide prime lens, f/2.8, handheld. Rich HDR tonal range without artificial look. Steve McCurry composition language, National Geographic color philosophy. Dust, sweat, light, life." \
  "Claude Sonnet 4.6" "Golden Hour Dust — Mumbai Street Market"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A masterpiece professional street photograph capturing a rain-slicked city avenue at midnight. In the foreground, a single figure carrying a glowing amber umbrella walks away, their silhouette sharp against the shimmering asphalt. The street is a vivid mirror, reflecting the neon kaleidoscope of towering skyscrapers — electric blues, hot pinks, and deep magentas bleeding into the dark wet concrete. Cinematic backlighting catches individual raindrops frozen mid-air like tiny crystals. Shot with a high-end 35mm lens at a low angle, achieving a shallow depth of field that subtly blurs the distant city traffic into soft, circular bokeh. The atmosphere is heavy with urban solitude, featuring high-contrast tones, rich shadow details, and an evocative, filmic mood that balances intense color saturation with the deep obsidian blacks of the night." \
  "Gemini 3.5 Flash" "Award-Winning Rainy Night Reflections"

queue_job  7 \
  "An award-winning monochrome street photograph capturing raw human emotion in an urban setting. An elderly cobbler with deeply lined hands and a weathered, expressive face sits by an open-air workshop window on a sunlit cobblestone alley. A powerful, dramatic beam of morning light cuts through the dusty air, illuminating him in sharp contrast against the dark, shadowed interior of his shop. Fine particles of leather dust drift lazily through the light ray. The texture of his worn apron, the grain of the wooden workbench, and the metallic sheen of his vintage tools are rendered with extreme crispness and micro-contrast. This classic black and white composition utilizes deep, velvety blacks and bright, clean highlights, evoking a timeless, journalistic feel reminiscent of mid-century documentary photography." \
  "Gemini 3.5 Flash" "The Quiet Artisan in Black and White"

queue_job  8 \
  "A brilliant, award-winning double exposure street photograph blending human presence with urban architecture. The primary silhouette is a side profile of a thoughtful woman looking out over a metropolis. Layered seamlessly within her form is the dizzying upward perspective of soaring brutalist skyscrapers and intersecting geometric concrete overpasses. Flocks of birds scatter across the negative space of her coat, transitioning into the sky. The color palette is muted and sophisticated, dominated by cool steel blues, concrete grays, and warm copper highlights from a setting sun. The overlapping textures create a surreal, dreamlike transparency where the boundaries between the individual and the city blur completely. Every detail is sharp, maintaining crisp edges on both the architectural lines and the human silhouette." \
  "Gemini 3.5 Flash" "Ethereal City Double Exposure"

queue_job  9 \
  "A breathtaking professional street photograph capturing the kinetic energy of a bustling grand central station during peak golden hour. Beams of intense, volumetric amber sunlight pierce through massive arched windows, cutting through a subtle haze to create dramatic shafts of light across the vast floor. Dozens of commuters are captured in motion; some are sharp and stationary, while others are artistic, ethereal motion blurs streaking through the light. The color tone is warm and luxurious, filled with rich golds, deep ochres, and dark bronze shadows. The composition uses strong leading lines from the architecture to draw the eye toward a central meeting point, perfectly balancing the chaotic movement of the crowd with the serene, monumental beauty of the sun-drenched architecture." \
  "Gemini 3.5 Flash" "The Golden Hour Rush Hour"

queue_job 10 \
  "An award-winning selective color street photograph set in a dense, fog-covered financial district. The entire scene is rendered in a desaturated, cool gray tone. The sole exception is a young woman standing completely still in the middle of a crosswalk, wearing a vibrant, richly textured crimson wool trench coat. The intense red pops dramatically against the lifeless, hazy backdrop. Swirling fog softens the distant shapes of skyscrapers, creating a sense of isolation and mystery. Shot from a straight-on, symmetrical perspective, the image captures a striking contrast between the rigid, gray conformity of the city and the bold, solitary spark of human individuality." \
  "Gemini 3.5 Flash" "The Lone Crimson Coat"

# --- ChatGPT ---
queue_job 11 \
  "A masterfully composed street photograph capturing a solitary figure crossing a vast intersection at golden hour, long shadows stretching dramatically across textured asphalt. The framing emphasizes negative space, with geometric lines from crosswalk markings and surrounding architecture guiding the viewer's eye. Shot from a slightly elevated angle, the scene feels both intimate and distant. Subtle motion blur in the subject contrasts with razor-sharp environmental details. Color grading leans toward warm amber highlights with cool desaturated shadows, creating emotional tension. Natural reflections in nearby windows add layered complexity. The image should evoke themes of isolation, rhythm, and urban poetry, with impeccable dynamic range and filmic grain." \
  "ChatGPT" "Last Light on Concrete Silence"

queue_job 12 \
  "A black-and-white street photograph frozen at the perfect decisive moment, where multiple subjects intersect in a visually complex yet balanced composition. A cyclist speeds through the foreground, slightly blurred, while behind them a sharply focused elderly man gazes into a storefront window. Reflections merge interior mannequins with real pedestrians, creating surreal visual ambiguity. High contrast lighting with deep blacks and crisp whites enhances texture — wrinkles, pavement cracks, fabric folds. Shot at eye level with a documentary feel, the image should carry emotional weight and layered narratives. Grain is intentional, reminiscent of classic analog photography, reinforcing authenticity and timelessness." \
  "ChatGPT" "Fragments of Passing Stories"

queue_job 13 \
  "A cinematic street photo taken at night during rainfall, where neon signs reflect vividly across wet pavement. The scene features a lone figure under an umbrella, partially silhouetted, walking through a glowing corridor of color. Selective color grading — dominant deep blues and vibrant reds — while keeping surrounding elements subdued. Raindrops frozen mid-air add texture, illuminated by streetlights. Shot with shallow depth of field, background signage softly blooms into bokeh, enhancing atmosphere. The composition feels immersive and slightly melancholic, blending realism with dreamlike abstraction. Reflections act as secondary subjects, doubling visual storytelling and depth." \
  "ChatGPT" "Neon Rain Reverie"

queue_job 14 \
  "A creative double exposure street photograph blending a portrait of a city dweller with architectural elements of the urban landscape. The subject's face, calm yet introspective, merges seamlessly with skyscrapers, staircases, and traffic lines, creating a layered narrative about identity and environment. The exposure balance is precise, allowing both layers to coexist without overpowering each other. Soft monochrome tones with slight sepia warmth for cohesion. Fine textures — skin pores, concrete surfaces — remain visible. The composition feels intentional and symbolic, evoking themes of belonging, anonymity, and modern life's complexity. Subtle vignetting draws focus inward." \
  "ChatGPT" "Urban Echoes in Double Exposure"

queue_job 15 \
  "A high-energy street photograph capturing synchronized movement of pedestrians crossing a busy intersection from a top-down perspective. The composition emphasizes repetition, pattern, and flow, with individuals spaced in visually pleasing intervals. Clothing variations create natural contrast — dark coats against light pavement. Motion blur is selectively applied to some figures while others remain sharp, creating dynamic tension. Lighting is neutral daylight with slight contrast enhancement to define shapes clearly. Shadows act as secondary graphic elements, extending the composition. The image feels alive and rhythmic, almost musical, showcasing the choreography of everyday urban life with precision and artistry." \
  "ChatGPT" "Rhythm of the Crosswalk"

# --- Grok ---
queue_job 16 \
  "Award winning professional street photo of a bustling Tokyo intersection at midnight, heavy rain creating glossy reflections on wet asphalt. A lone salaryman with umbrella walks through vibrant neon signs in pink, cyan and magenta casting dramatic glows. Cinematic composition with leading lines from crosswalk, shallow depth of field, selective color emphasizing the red umbrella against mostly desaturated background. Moody atmosphere, film grain, high contrast, captured with Leica M camera aesthetic, sharp details on water droplets, award winning composition, masterful use of light and shadow, emotional urban solitude." \
  "Grok" "Neon Nocturne"

queue_job 17 \
  "Award winning professional street photo during golden hour in New York City, crowded sidewalk filled with diverse pedestrians hurrying past iconic yellow taxis. Warm sunlight piercing between skyscrapers creating long dramatic shadows and beautiful rim lighting. Black and white with selective color on one bright red coat standing out powerfully. Dynamic energy, perfect timing, layers of depth with foreground, midground and background elements, impeccable composition following rule of thirds, cinematic feel, high dynamic range, professional street photography masterpiece with rich textures and authentic human moments." \
  "Grok" "Golden Hour Rush"

queue_job 18 \
  "Award winning professional street photo using double exposure technique in Paris, overlaying a crowded Montmartre street scene with ethereal reflections of passing faces and vintage architecture. Soft morning light, gentle fog adding mystery. Selective desaturation with preserved warm skin tones and deep blue sky. Dreamlike yet documentary style, intricate details in layered elements creating visual poetry, emotional depth, masterful blend of reality and abstraction, award winning composition with perfect balance of chaos and harmony, film-like grain and beautiful light leaks." \
  "Grok" "Double Exposure Reverie"

queue_job 19 \
  "Award winning professional street photo of an elderly woman sitting alone on a weathered wooden bench in a quiet Lisbon neighborhood at dusk. Warm orange streetlights beginning to glow against deep blue hour sky. Powerful eye contact with viewer, incredible character in her wrinkled face and thoughtful expression. High contrast black and white photography with rich tonal range, dramatic side lighting, impeccable framing, emotional storytelling, captured moment of quiet dignity, professional street portrait with extraordinary psychological depth and masterful use of negative space." \
  "Grok" "Silent Observer"

queue_job 20 \
  "Award winning professional street photo inside a vibrant Marrakech souk during late afternoon, golden sunlight streaming through woven roof creating beautiful god rays and patterned shadows. Crowded narrow alley filled with colorful spices, textiles and animated locals. Rich warm color tones with high saturation on reds and golds, dynamic movement, perfect decisive moment as merchant gestures to customer. Layers of depth, intricate details, award winning composition with strong diagonal lines, cultural authenticity, cinematic atmosphere, exceptional light management and visual storytelling." \
  "Grok" "Market Symphony"

# --- Copilot ---
queue_job 21 \
  "A deserted alleyway captured in stark black and white, where shadows stretch across cracked pavement and peeling walls. The composition emphasizes the geometry of light and darkness, with a single flickering streetlamp illuminating a lone figure in the distance. The mood is contemplative, evoking solitude and resilience in an urban environment. The photograph highlights textures — rough bricks, worn asphalt, and faint graffiti — while maintaining a timeless, award-winning aesthetic that feels both cinematic and raw." \
  "Copilot" "Silent Alley in Monochrome"

queue_job 22 \
  "A bustling city street under heavy rain, where umbrellas form a sea of muted tones except for one striking red umbrella in sharp focus. The selective color technique isolates this vibrant detail against the grayscale background, drawing attention to human individuality amid the crowd. Reflections shimmer on wet pavement, neon signs blur in the downpour, and pedestrians move hurriedly, creating a dynamic yet poetic atmosphere. The image feels alive, balancing chaos with artistry, embodying the essence of professional street photography." \
  "Copilot" "Selective Color Rainfall"

queue_job 23 \
  "A layered composition blending the silhouette of a walking commuter with towering skyscrapers and blurred traffic lights. The double exposure effect creates a surreal narrative, merging human presence with the pulse of the city. The photograph feels dreamlike yet grounded, with overlapping textures of glass, steel, and motion trails. The artistry lies in balancing clarity and abstraction, producing an award-worthy image that conveys both the anonymity and vibrancy of urban life." \
  "Copilot" "Double Exposure City Dreams"

queue_job 24 \
  "A street scene captured during golden hour, where warm sunlight bathes buildings and pedestrians in a soft glow. The focus is on reflections in shop windows and puddles, creating a layered visual story of people passing by. The photograph emphasizes natural light, long shadows, and subtle contrasts between illuminated and shaded areas. The mood is nostalgic yet modern, celebrating fleeting everyday moments with professional precision and artistic depth." \
  "Copilot" "Golden Hour Reflections"

queue_job 25 \
  "A crowded street market alive with vendors and customers, where candid portraits reveal emotion and character. The image captures expressive faces — smiles, concentration, fatigue — amid vibrant stalls filled with fruits, fabrics, and street food. The composition balances chaos with intimacy, highlighting human connection in public spaces. Rich colors, dynamic framing, and authentic storytelling elevate the scene into an award-winning professional street photograph that feels both universal and deeply personal." \
  "Copilot" "Faces of the Market"

# --- Mistral ---
queue_job 26 \
  "Award-winning black-and-white street photograph capturing the raw essence of city life. A bustling intersection at dusk, where the interplay of light and shadow creates a dramatic contrast. A lone musician plays a violin on a corner, their silhouette sharp against the glow of a nearby streetlamp. The scene is alive with movement: blurred pedestrians, a cyclist mid-motion, and the faint haze of car headlights streaking through the frame. The composition emphasizes depth, with leading lines from cobblestone streets drawing the eye toward the musician. Gritty textures of old buildings and wet pavement add a tactile quality. The image evokes emotion through its timeless, cinematic atmosphere, celebrating the unscripted beauty of urban existence." \
  "Mistral" "Urban Symphony in Monochrome"

queue_job 27 \
  "A vibrant, award-winning street photo blending neon lights with the raw texture of city architecture. A young woman in a bright red coat walks past a row of glowing shop signs in Chinatown, her figure sharply in focus while the background melts into a dreamy bokeh of pink, blue, and gold. The selective color technique highlights her coat and the neon hues, creating a striking contrast against the muted tones of the surrounding buildings. Rain-slicked streets reflect the lights, adding a layer of depth and surrealism. The image captures the energy of nightlife, where tradition and modernity collide in a visually stunning tableau." \
  "Mistral" "Neon Dreams and Concrete Realities"

queue_job 28 \
  "A double-exposure street photograph that layers two moments into one frame. In the foreground, an elderly man sits on a park bench, his hands clasped in quiet contemplation. Superimposed over him is the ghostly image of a child running with a kite, their laughter frozen in time. The blend of the two scenes creates a poignant narrative about the passage of time and the invisible bonds between generations. The background is a soft blur of trees and urban structures, allowing the subjects to remain the focal point. The image is rendered in warm, earthy tones with a hint of sepia, evoking nostalgia and introspection." \
  "Mistral" "The Invisible Threads of Connection"

queue_job 29 \
  "A bustling open-air market in Marrakech, where the chaos of daily life is distilled into a single, award-winning frame. The scene is mostly desaturated, with the exception of a vendor's stall overflowing with bright oranges and deep red spices, which pop against the muted backdrop. The vendor, an older woman with weathered hands, is caught mid-gesture, offering a sample to a customer. The composition is rich with textures: woven baskets, patterned fabrics, and the rough surfaces of fresh produce. The image balances the vibrancy of color with the timelessness of black-and-white, creating a visual feast that feels both immediate and eternal." \
  "Mistral" "Selective Color in the Chaos of the Market"

queue_job 30 \
  "A minimalist yet powerful street photograph capturing the paradox of urban solitude. A sea of people moves through a subway station, their faces blurred and anonymous, except for one individual — a man standing still, his gaze directed upward at an old, peeling advertisement on the wall. The image is shot in high contrast black-and-white, emphasizing the stark lines of the station's architecture and the interplay of light and shadow. The man's stillness amidst the motion of the crowd creates a sense of isolation and introspection. The composition is clean and deliberate, with negative space used to draw attention to the subject's quiet moment of reflection." \
  "Mistral" "The Solitude of the Crowd"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A striking black and white street photograph capturing the raw essence of urban life at a bustling intersection. A lone figure in a vintage trench coat walks against the flow of blurred commuters, their silhouette sharply contrasted against the geometric lines of towering concrete architecture. The wet pavement reflects neon signs from nearby storefronts, creating a dramatic interplay of light and shadow. Shot with a classic wide-angle lens to emphasize the vastness of the environment while keeping the subject centrally framed. The composition relies heavily on leading lines, drawing the viewer's eye directly to the solitary walker. Grainy texture and high contrast enhance the gritty, timeless atmosphere, evoking the golden era of documentary photography." \
  "Qwen 3.6 Plus" "Monochrome Crossroads"

queue_job 32 \
  "A masterfully composed street scene rendered entirely in desaturated grayscale, except for a vibrant crimson umbrella held by a young child standing near a weathered subway entrance. The background features a busy city sidewalk filled with hurried pedestrians, their motion captured with a slow shutter speed that creates a ghostly, ethereal blur around the sharply focused subject. Warm ambient light filters through a canopy of autumn leaves above, casting long, dramatic shadows across cracked cobblestones. The photograph utilizes a shallow depth of field to isolate the striking red object as the undeniable focal point. Subtle vignetting darkens the edges. The overall mood is contemplative and cinematic, perfectly balancing urban chaos with a singular, quiet moment of stillness." \
  "Qwen 3.6 Plus" "Crimson in the Crowd"

queue_job 33 \
  "An innovative double exposure street photograph seamlessly blending a candid portrait of an elderly violinist with the intricate architecture of a grand metropolitan train station. The musician's weathered face and hands holding a wooden bow align perfectly with the sweeping iron arches and converging railway tracks in the background. Soft, diffused natural light illuminates the scene, creating a dreamlike, translucent layering effect that emphasizes the intersection of human resilience and industrial grandeur. Faint geometric patterns of passing trains and overhead wires weave through the negative space of the subject's silhouette. This avant-garde composition tells a poetic story of time, travel, and enduring artistry." \
  "Qwen 3.6 Plus" "Urban Echoes"

queue_job 34 \
  "A breathtaking color-graded street photograph taken during the fleeting golden hour, capturing the rhythmic pulse of a metropolitan crosswalk. Warm, honey-toned sunlight streams between glass skyscrapers, illuminating the faces of diverse commuters as they pause under a massive red traffic signal. The composition employs dynamic diagonal lines formed by bicycle lanes and painted crosswalk markings. Rich teal and orange color grading enhances the cinematic atmosphere, with deep shadows contrasting against glowing highlights. Rain-slicked asphalt mirrors the vibrant storefront awnings and distant traffic lights, adding layers of visual depth. The scene feels authentically alive, frozen in a decisive moment that highlights the beautiful, unscripted poetry of everyday city living." \
  "Qwen 3.6 Plus" "Amber Transit"

queue_job 35 \
  "A minimalist yet profoundly evocative street photograph emphasizing bold geometric forms and extreme contrast within a dense urban canyon. A solitary figure wearing a wide-brimmed hat walks across an expansive, sunlit plaza, their elongated shadow stretching dramatically across pale limestone tiles. The surrounding architecture consists of stark, unadorned modernist facades that frame the subject like a living theater stage. Harsh midday lighting eliminates mid-tones, rendering the scene in near-monochrome blacks and blinding whites with only subtle hints of warm brick texture in the distant background. Negative space dominates the upper half of the frame, conveying a powerful sense of isolation and scale. The precise symmetry and deliberate framing transform a simple pedestrian commute into an award-winning visual narrative." \
  "Qwen 3.6 Plus" "Concrete Solitude"

# --- GLM 5.1 ---
queue_job 36 \
  "An award-winning professional black and white street photograph capturing a solitary figure walking through a torrential downpour in a narrow Tokyo alley. High contrast monochrome with deep, inky blacks and bright, specular highlights reflecting off the rain-slicked cobblestones. The subject holds a translucent umbrella, their face obscured by shadows, creating a profound sense of isolation and mystery. Puddles mirror the geometric shapes of overhead lanterns. Shot on Leica M10, 35mm lens, f/1.4, capturing the decisive moment with stunning sharpness on the subject while the background melts into a creamy bokeh. Raw emotion, cinematic lighting, masterful composition following the rule of thirds, a timeless documentary aesthetic." \
  "GLM 5.1" "Monsoon Solitude"

queue_job 37 \
  "An award-winning professional street photograph utilizing striking selective color technique. The scene depicts a bustling nocturnal market in Hong Kong, rendered entirely in moody, desaturated monochrome except for a solitary woman in a flowing crimson dress walking away from the camera. The vivid red of her outfit pierces through the gloomy blues and grays of the surrounding neon-lit alleyway, creating a mesmerizing focal point. Steam rises from street food vendors, partially obscuring the background pedestrians who remain entirely in black and white. Dramatic chiaroscuro lighting, cinematic depth of field. The wet pavement reflects the solitary red hue, amplifying the cinematic tension. Masterful composition, evocative mood, perfect blend of documentary realism and artistic expression." \
  "GLM 5.1" "Crimson Alleyway"

queue_job 38 \
  "An award-winning professional street photograph featuring a breathtaking double exposure. The base image is a stark, stoic portrait of an elderly bearded man standing at a bustling crosswalk, his eyes filled with decades of untold stories. Overlaid seamlessly is a secondary exposure of towering, blurred skyscrapers and streaking yellow taxi lights, as if the city itself is passing through his soul. The blending is ethereal, with the architectural lines perfectly aligning with the contours of his weathered face. Cool cyan and muted teal tones dominate the shadows, while warm amber highlights kiss his cheekbones. Shot on medium format film. A hauntingly poetic masterpiece that merges humanity with the relentless pulse of the metropolis." \
  "GLM 5.1" "Urban Ghost"

queue_job 39 \
  "An award-winning professional street photograph bathed in the warm, rich tones of golden hour. The scene captures the magical interplay of long, dramatic shadows cast by pedestrians hurrying across a grand European plaza. Sunlight filters through autumn leaves, casting dappled light on the cobblestones. A vintage Kodachrome color palette infuses the image with deep oranges, burnt siennas, and creamy yellows. In the foreground, a child reaches up to catch a floating leaf, frozen in mid-air with tack-sharp focus, while the background features beautifully blurred silhouettes of commuters. The composition masterfully uses leading lines from the architecture to draw the eye toward the radiant sunburst. Nostalgic, timeless, evocative storytelling." \
  "GLM 5.1" "Golden Hour Commute"

queue_job 40 \
  "An award-winning professional street photograph showcasing a masterful panning technique and intense motion blur. The subject is a bike messenger speeding through a rain-drenched Manhattan intersection, sharply in focus against a wildly streaked background of neon signs and yellow cabs. The color grading leans heavily into moody teal and orange, emphasizing the cold urban night and the warm glow of brake lights. Drops of water are frozen mid-air, suspended around the cyclist's dynamic posture. The sense of speed and urgency is palpable. The diagonal composition adds to the kinetic energy, creating a visceral, heart-pounding documentary moment. Exceptional timing, technical brilliance, and a raw, unfiltered glimpse into the chaotic rhythm of city life." \
  "GLM 5.1" "Velocity in Blue"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A lone businessman shelters beneath a transparent umbrella at a Tokyo intersection, neon signs reflected in puddles transformed into liquid mercury. Shot from a low angle through rain-streaked glass, the composition frames his silhouette against blinding white headlights and deep shadowed alleyways. Grain structure mimics Kodak Tri-X pushed to 1600, with crushed blacks and glowing highlights. Steam rises from a street vendor cart, creating ethereal layers of light diffusion. The wet asphalt mirrors the chaos of the district while isolating the subject in a bubble of quiet contemplation. Every raindrop catches a pinpoint of light, transforming the frame into a constellation of silver moments frozen in time. Award winning professional street photography." \
  "Kimi K2.6 Thinking" "Silver Rain on Ginza"

queue_job 42 \
  "A Moroccan marketplace rendered in desaturated charcoal tones except for a single crimson silk veil flowing behind a woman navigating ancient spice stalls. The selective color technique isolates the fabric's arterial red against oxidized bronze pots, weathered limestone walls, and baskets of muted saffron. Dust motes dance in shafts of hard afternoon light, catching the crimson edge like floating embers. The composition uses layered narrative depth: foreground hands exchanging weathered dirham, midground the floating fabric caught in motion, background labyrinthine archways fading to umber monochrome. The red becomes a visual heartbeat, drawing the eye through the chaos of the souk while the monochrome world provides timeless documentary weight and emotional gravity. Award winning professional street photography." \
  "Kimi K2.6 Thinking" "The Scarlet Veil"

queue_job 43 \
  "Double exposure technique fuses a weathered elderly man's profile with the skeletal architecture of a Bucharest tram station. His lined face, mapped with decades of stories, occupies the right third while the ironwork canopy and departing tram blur through his features on the left. The transparency creates a haunting symbiosis: the tram's vertical handrails become wrinkles, the station clock melts into his eye socket, departure boards fragment across his cheek. Muted industrial palette of rust, pale skin, and oxidized green patina unifies both exposures. Soft window light illuminates the composite from behind, creating a halo effect that suggests memory and place are inseparable. Award winning professional street photography with surreal layered storytelling." \
  "Kimi K2.6 Thinking" "Metropolis Ghost"

queue_job 44 \
  "Golden hour saturates a crumbling colonial street in Havana where a mechanic pushes a vintage turquoise Buick beneath a balcony of drying laundry. The entire frame bathes in honeyed amber and burnt sienna tones, emulating faded Kodachrome from 1972. Long shadows stretch across patched asphalt while cigar smoke catches the horizontal light, creating volumetric gold rays. Weathered peach and ochre facades peel to reveal layers of Caribbean history. The mechanic's white shirt glows incandescent against the shadowed undercarriage. A stray dog watches from a doorway framed by bougainvillea. The warmth suggests nostalgia without sentimentality, capturing the resilient dignity of daily labor in a city frozen by time and sunlight. Award winning professional street photography." \
  "Kimi K2.6 Thinking" "Havana Gold"

queue_job 45 \
  "A solitary figure in a transparent raincoat stands beneath a Seoul convenience store awning at 3 AM, bathed in conflicting cyan and magenta neon. The entire scene pulses with electric cobalt and hot pink reflections across slick pavement, creating recursive color pools that fragment the subject's silhouette. Shot through condensation on a phone booth window, the image layers urban texture: Hangul signage, vending machine glow, and distant traffic streaks. The cool palette dominates — ice blue shadows, surgical white highlights, and the occasional arterial red from a distant intersection. The figure's face remains obscured by mask and hood, becoming every insomniac citizen in the digital age. Award winning professional street photography with cyberpunk atmosphere." \
  "Kimi K2.6 Thinking" "Electric Solitude"

# --- Deepseek ---
queue_job 46 \
  "A haunting black and white street photograph capturing a lone figure in a trench coat sprinting through billowing steam from a vintage tram at the end of a rain-slicked cobblestone lane. The composition uses dramatic chiaroscuro, with the tram's headlights slicing diagonally through thick fog, illuminating thousands of suspended water droplets. In the midground, a newspaper stand's corrugated metal roof reflects the city's last sodium vapor lamp. The decisive moment freezes the man's left foot just above a puddle that mirrors the tram's glowing number in reverse. Award-winning qualities: perfect geometric layering of parallel tram tracks, leading lines of overhead wires converging toward a distant clock tower at 5:47 AM. The grain structure mimics pushed Tri-X 400 film. Existential isolation." \
  "Deepseek" "The Last Tram at Dawn"

queue_job 47 \
  "A selective color street photograph where the entire urban scene exists in desaturated slate blues and cool grays, except for three precise elements: a child's balloon, a fire hydrant, and a woman's umbrella, all in saturated crimson. Setting is a narrow Barcelona alley during a sudden summer downpour. The main subject is an elderly cobbler crouched in a doorway, his weathered hands hovering over a broken heel. The red balloon floats past his sightline, tied to a park bench where a young couple argues silently. Award-winning technical details: the reflection of the red umbrella in a curved car window creates a distorted heart shape. Falling raindrops catch the red glow like suspended rubies. The composition follows the golden ratio." \
  "Deepseek" "Summer of Selective Red"

queue_job 48 \
  "A masterful double exposure street photograph blending the Paris Métro's bustling platform with a cemetery's iron gate. First exposure: a commuter's silhouette waiting at the edge of a platform, his transparent body revealing the second exposure layered beneath — weeping angels from Père Lachaise Cemetery covered in morning frost. The commuter's briefcase overlaps perfectly with a tombstone's engraved dates. Award-winning elements: the train's arriving headlights become halos behind angel wings. A child's reflection in the tile wall shows her hugging an invisible figure. Overhead fluorescent tubes ghost through carved stone laurel leaves. The color palette shifts from sickly station green to sepulchral limestone gray at the double exposure's overlap zone." \
  "Deepseek" "Metro Ghosts Double Exposure"

queue_job 49 \
  "A vibrant color street photograph from a low worm's-eye angle, looking up through a forest of tangled neon signs in Hong Kong's Kowloon. The subject is an umbrella repairman perched on a wooden ladder, his face partially hidden by a half-repaired parasol. He reaches toward a broken spoke while forty-two umbrellas in every state of repair hang from overhead cables like surreal jellyfish. Award-winning composition: the repairman's body forms a perfect triangle with two drying tarps. A child below offers him a fish ball on a stick, their arms creating a diagonal that mirrors the broken spoke. Sunlight pierces through a single hole in a patched umbrella, creating a spotlight on the child's upturned face. Color palette dominated by oxidized copper greens, faded vermilions, and warm incandescent yellow." \
  "Deepseek" "Umbrella Repairman of Kowloon"

queue_job 50 \
  "A high-contrast black and white street photograph shot moments after a confetti parade on Fifth Avenue, focusing on a single trash can overflowing with shredded ticker tape that still glows with latent flashbulb reflections. The main subject is a sanitation worker taking a cigarette break, his broom leaning against a NO PARKING sign that casts an elongated shadow across a discarded top hat. Award-winning technical achievement: confetti caught mid-settling, individual pieces suspended in shafts of afternoon light cutting between buildings. In the background, a wedding party exits St. Patrick's Cathedral, the bride's veil paralleling the wispy smoke from the worker's cigarette. A pigeon stands on the hat's brim. The lower third is empty wet asphalt reflecting the worker's boots and the distant spire. Grain suggests pushed Ilford HP5." \
  "Deepseek" "Fifth Avenue After the Parade"

echo "✅ All 50 jobs queued in scheduler"
