#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string (CFG-based guidance may misuse negatives)
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Legs and book — elegant, alluring, SFW illustrations
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+16+-+Legs+and+book
# Structure: 9 models × 5 prompts = 45 tasks total
# queue_job INDEX "PROMPT" "GENERATOR MODEL" "TITLE"
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 "Stylized editorial illustration, woman reclining on ivory linen, bare legs crossed at ankle, open hardcover novel resting across her thighs, warm afternoon light raking across skin, red lacquered toenails catching sunlight, scattered loose pages, art nouveau linework, muted gold and blush palette, shallow depth of field impression, fashion magazine aesthetic, fine detail on fabric texture, confident languid pose, sophisticated visual tension." \
  "Claude Sonnet 4.6" "Legs & Literature"

queue_job  2 "Close-crop composition, long smooth legs draped over velvet armchair armrest, strappy heeled sandal dangling at toe, vintage leather-bound tome balanced open mid-air, ink-stained fingers gripping spine, dramatic chiaroscuro lighting, deep burgundy and charcoal tones, rendered in ink-wash illustration style, cinematic mood, bold shadows carving form, literary atmosphere charged with quiet electricity, composed and deliberate." \
  "Claude Sonnet 4.6" "The Reading Hour"

queue_job  3 "Overhead perspective, bistro marble table, espresso cup at edge, woman's crossed legs beneath sheer fabric hem, ankle chain glinting, thick paperback spread open spine-up, afternoon Paris window light, impressionist brushwork, warm honeyed tones, painted highlights on smooth skin, scattered bookmark ribbons, confident ownership of space, elegant sensory detail, editorial illustration weight, fashionable and intellectually charged atmosphere." \
  "Claude Sonnet 4.6" "Café Philosophe"

queue_job  4 "Sun-drenched outdoor scene, woman lying on stomach across wooden dock, bare legs lifted and crossed behind her, feet playfully raised, glossy magazine-thick novel open flat, golden hour haze softening background, illustrated in vector-brushwork hybrid style, peachy skin tones against bleached timber grain, shadow patterns from overhead foliage, carefree yet composed energy, saturated warmth, fashion-forward visual storytelling." \
  "Claude Sonnet 4.6" "Summer Page-Turner"

queue_job  5 "High-contrast noir illustration, seated woman in dark library alcove, long legs extended forward on ottoman, pointed kitten heels sharp in foreground, enormous antique book open across lap, single hanging filament bulb casting amber cone, deep ink blacks, dramatic foreshortening, smoke and mahogany atmosphere, art deco geometry in background shelving, bold graphic style, composed mystery, intellectually seductive visual narrative." \
  "Claude Sonnet 4.6" "Noir Bibliothèque"

# --- Gemini 3.5 Flash ---
queue_job  6 "An atmospheric close-up of smooth legs crossed elegantly in a plush, velvet armchair. One foot dangles a silk high heel carelessly from its toes. Resting on the lap is an open leather-bound vintage book, its pages glowing under soft, warm library lamplight. Shadows accentuating curves, creating a sophisticated, high-contrast aesthetic that feels intimate, intellectual, and deeply alluring. Textures of paper and skin are hyper-detailed." \
  "Gemini 3.5 Flash" "Literacy and Lace"

queue_job  7 "A sun-drenched afternoon setting where a woman relaxes on crisp white linen sheets. Her bare, shapely legs are arched slightly, framing an open hardcover novel resting against her thighs. Dust motes dance in golden sunbeams, casting a dreamy, warm glow over soft skin and weathered pages. The mood is effortlessly sensual, quiet, and evocative, focusing on the breathtaking elegance of simple relaxation and reading." \
  "Gemini 3.5 Flash" "Whispered Chapters"

queue_job  8 "A dramatic, moody illustration focusing on slender legs clad in sheer, dark fishnet stockings. The subject is seated on a mahogany desk, ankles crossed gracefully beside a stack of old textbooks. A single candle flickers nearby, casting long, sultry shadows and highlighting the soft contours of her skin. The atmosphere is mysterious, intellectually charged, and intensely captivating, blending academic focus with undeniable, sophisticated charm." \
  "Gemini 3.5 Flash" "Midnight Study"

queue_job  9 "An elegant, low-angle shot of a woman reclining on a dark emerald velvet sofa. Her long, bare legs extend upward, resting casually against the backrest while holding a minimalist poetry book open above her. Soft, ambient neon light from a window bleeds into the room, painting her silhouette in deep blues and magenta tones. The composition is modern, artistic, visually striking, and intensely atmospheric." \
  "Gemini 3.5 Flash" "Velvet Epilogue"

queue_job 10 "A cozy, intimate morning scene viewed from a bedside angle. A woman's smooth, sun-kissed legs are tucked loosely under a knit blanket, with one calf exposed. An open classic paperback rests face down on her thigh, next to a steaming ceramic mug. Soft, diffused morning light fills the space, emphasizing a gentle, warm, and highly inviting aesthetic that feels beautifully personal and quietly magnetic." \
  "Gemini 3.5 Flash" "Coffee and Classics"

# --- ChatGPT ---
queue_job 11 "Soft evening light spills across a quiet reading nook where a woman reclines, legs elegantly crossed on a velvet chair, stockings catching subtle highlights. A worn novel rests against her knee, pages slightly open, hinting at narrative intimacy. Composition focuses on graceful lines, tactile textures, and cinematic shadows, balancing sophistication and allure, emphasizing calm confidence, warmth, and contemplative mood within a refined, artful interior scene with subtle poetic rhythm." \
  "ChatGPT" "Velvet Quiet Reading"

queue_job 12 "Morning sun filters through sheer curtains, illuminating a minimalist room where a woman sits on a windowsill, legs extended, toes grazing light. A hardcover book balances loosely atop her thigh, suggesting paused curiosity. Emphasis on geometry, clean lines, and gentle contrast between skin, fabric, and paper textures, evoking quiet magnetism, introspection, and modern elegance in a serene, carefully composed visual narrative with understated tension and cinematic framing details subtly." \
  "ChatGPT" "Windowsill Pause"

queue_job 13 "Rainy night ambiance, reflections shimmering across polished floorboards as a woman lounges on a low sofa, legs angled toward a dim lamp. An open paperback rests along her shin, pages catching glints of amber light. The scene highlights contrast, mood, and storytelling through posture and composition, blending noir sensibility with refined intimacy, suggesting narrative depth without explicit detail, maintaining elegance and atmospheric allure in a carefully balanced cinematic study." \
  "ChatGPT" "Noir Reflection Study"

queue_job 14 "Library setting with towering shelves fading into soft blur, a woman perched on a wooden ladder, legs relaxed along a rung. A classic novel lies open across her lap, one hand loosely holding its spine. Focus on composition, perspective, and interplay of light and shadow, creating a poised, evocative image that balances intellect, grace, and subtle sensual tension within a timeless, cultured environment with painterly textures and restrained framing." \
  "ChatGPT" "Ladder Among Shelves"

queue_job 15 "Sunset glow washes over a balcony scene, a woman seated sideways on a chair, legs resting along the railing, silhouetted against a fading skyline. A small book rests delicately in her hands, pages fluttering slightly in the breeze. The composition emphasizes silhouette, rhythm, and negative space, creating a striking yet gentle visual that conveys confidence, curiosity, and understated allure within a tranquil urban moment with cinematic softness and balance." \
  "ChatGPT" "Balcony Sunset Stillness"

# --- Grok ---
queue_job 16 "Graceful female legs crossed elegantly in a sophisticated pose, delicate bare feet pointed gracefully, smooth skin glowing under soft warm light, an ancient leather-bound book resting open on her lap revealing intricate pages, artistic fashion illustration style with flowing lines, delicate shadows highlighting subtle curves, luxurious atmosphere, velvet textures in background, highly detailed, ethereal beauty, captivating composition, refined aesthetic appeal in square format illustration." \
  "Grok" "Elegant Legs with Open Book"

queue_job 17 "Beautiful woman legs extended elegantly on a chaise lounge, one knee slightly bent creating gentle curve, soft silk fabric draped lightly, vintage book held delicately near calves, warm golden hour lighting casting gentle highlights, masterful digital painting style with smooth gradients, artistic focus on form and elegance, intricate details on skin and paper, serene yet alluring atmosphere, refined artistic expression." \
  "Grok" "Whispers of Literature and Grace"

queue_job 18 "Stunning illustration of feminine legs in relaxed crossed position, toes delicately arched, smooth contours emphasized by subtle shading, hardcover novel balanced on thighs with pages fluttering softly, minimalist elegant setting with draped fabrics, soft diffused lighting creating depth and harmony, professional character design, exquisite line work, aesthetically captivating composition with perfect balance and graceful presence." \
  "Grok" "Timeless Allure in Reading Pose"

queue_job 19 "Artistic depiction of shapely woman legs positioned gracefully with one leg extended forward, book with ornate cover placed intimately against calf, gentle muscle definition and soft skin tones, dramatic yet soft chiaroscuro lighting, fashion editorial illustration style, rich textures and delicate details, sophisticated atmosphere, visually striking balance between literary element and elegant leg form, refined beauty." \
  "Grok" "Literary Seduction in Lines"

queue_job 20 "Captivating female legs in seated pose with knees together and ankles crossed, delicate ankles and calves highlighted, open illustrated book resting across lap, dreamy soft pastel color palette with warm accents, contemporary digital art style with intricate linework, subtle glow on skin, harmonious composition blending literature and graceful anatomy, aesthetically pleasing elegant atmosphere with refined sensual undertones." \
  "Grok" "Enchanted Pages and Silhouette"

# --- Copilot ---
queue_job 21 "An evocative illustration of crossed legs resting elegantly beside an open book, the smooth curves highlighted by warm ambient light, shadows dancing across polished skin, the book's pages fluttering as if stirred by a hidden breeze, a subtle aura of mystery and allure, blending intellectual charm with visual intensity, creating a composition that feels both intimate and captivating, inviting the viewer into a moment of poised temptation." \
  "Copilot" "Velvet Pages"

queue_job 22 "A refined depiction of slender legs reclining gracefully near a hardcover book, the glossy surface reflecting soft golden tones, fabric draped loosely to accentuate contours, the book's spine angled toward the viewer, suggesting secrets within, the atmosphere charged with quiet anticipation, balancing sophistication with allure, a scene that merges literary fascination with visual magnetism, leaving the impression of beauty intertwined with knowledge, poised between elegance and desire." \
  "Copilot" "Whispered Chapters"

queue_job 23 "An artistic portrayal of long legs extended beside a book, the smooth lines emphasized by gentle highlights, shadows cascading to create depth, the book open with text barely visible, hinting at untold stories, the composition blending sensual form with intellectual intrigue, a balance of restraint and allure, the atmosphere glowing with subtle warmth, inviting contemplation of both the written word and the graceful figure that frames it." \
  "Copilot" "Ink and Silhouette"

queue_job 24 "An illustration of crossed legs angled elegantly toward a book resting nearby, the skin luminous under soft light, fabric slipping slightly to reveal contours, the book's cover textured and inviting, pages half-open as though caught mid-thought, the scene radiating a quiet tension, merging allure with intellect, a visual dialogue between body and literature, creating an atmosphere that feels simultaneously refined, intimate, and provocatively magnetic." \
  "Copilot" "Bound Secrets"

queue_job 25 "A depiction of legs reclining gracefully beside a book, the smooth surface glowing under ambient tones, shadows accentuating curves, the book open with delicate pages catching light, suggesting hidden narratives, the composition balancing elegance with allure, a subtle tension between knowledge and beauty, the atmosphere charged yet refined, inviting the viewer to linger on the interplay of form and text, a moment suspended in aesthetic temptation." \
  "Copilot" "Pages of Desire"

# --- Qwen 3.6 Plus ---
queue_job 26 "Golden hour sunlight filters through sheer curtains, casting delicate shadows across a velvet chaise. A woman rests gracefully, one leg elegantly extended while the other bends softly, showcasing sleek stockings and pointed heels. An open classic hardcover novel lies casually across her thighs, its pages gently ruffled. Dust motes dance in the warm air. Amber tones highlight smooth skin textures, creating an intimate atmosphere with refined soft cinematic lighting." \
  "Qwen 3.6 Plus" "Velvet Chaise Reading"

queue_job 27 "Dim library ambiance glows with candlelight, illuminating polished mahogany shelves and velvet cushions. A figure lounges comfortably on a plush rug, wearing sheer silk stockings and delicate satin slippers. Her toned legs stretch outward with effortless grace, framing a vintage poetry collection resting lightly on her lap. Cool blue moonlight blends with golden wax drips, emphasizing elegant curves and quiet confidence through rich fabric textures and masterful chiaroscuro composition." \
  "Qwen 3.6 Plus" "Moonlit Library Lounge"

queue_job 28 "Retro art deco aesthetics define this elegant scene, featuring a sophisticated lounge chair draped in emerald silk. A poised woman crosses one slender leg over the other, highlighting sheer lace hosiery and strappy heels. A thick illustrated tome rests against her knee, pages slightly bent from reading. Soft peach gradients illuminate the composition, featuring subtle gold accents, balancing refined geometry with organic warmth for a very captivating visual narrative." \
  "Qwen 3.6 Plus" "Emerald Silk Reverie"

queue_job 29 "Minimalist studio photography inspires this striking digital painting, utilizing bold directional lighting and muted neutral backgrounds. Elegant limbs extend gracefully across polished marble floors, adorned with matte black pantyhose and sculptural stiletto shoes. A heavy philosophy volume leans casually against the calf, creating very dynamic diagonal lines. Rich charcoal shadows contrast with luminous surface highlights, delivering a refined modern editorial aesthetic that feels both softly polished and irresistibly magnetic." \
  "Qwen 3.6 Plus" "Marble Editorial Focus"

queue_job 30 "Dreamy summer afternoon light washes over a sunlit balcony, painting everything in soft pastel tones. A relaxed figure reclines on woven linen cushions, legs stretched naturally with bare feet and sheer anklets visible. A well loved paperback rests open on her shins, dog eared pages catching the gentle warm breeze. Delicate floral shadows softly dance across smooth skin, creating a romantic, breezy atmosphere full of quiet elegance and timeless charm." \
  "Qwen 3.6 Plus" "Balcony Breeze Study"

# --- GLM 5.1 ---
queue_job 31 "Alluring vintage illustration of a woman lounging on a plush velvet chaise. Her long, toned legs are elegantly crossed, catching the warm golden ambient light. A thick leather-bound book rests lightly against her bare thigh. Sheer black stockings and delicate garters accentuate her curves. Soft brushstrokes, rich burgundy and gold palette, intimate boudoir atmosphere. Sensual gaze directed at the viewer, evoking a timeless, provocative elegance and deeply heated sophistication." \
  "GLM 5.1" "Vintage Velvet Boudoir"

queue_job 32 "Sensual digital illustration of a woman sitting on a mahogany desk. Her slender, bare legs dangle provocatively, knees gently parted. An open vintage book balances on her lap. Dramatic chiaroscuro lighting casts deep shadows across her smooth skin, highlighting her calves. Stiletto heels point downward. Moody atmosphere, dark teal and amber hues, alluring pose. The composition emphasizes the captivating curve of her legs and the mystery of the story." \
  "GLM 5.1" "Noir Office Seduction"

queue_job 33 "Alluring watercolor illustration of a woman resting on silk sheets. Her beautifully sculpted legs are raised, knees bent, holding a heavy poetry book between her calves. Soft pastel light washes over her skin, creating a provocative yet graceful silhouette. Delicate ankle bracelet glints. Flowing paint splashes in rose and azure. Intimate and enchanting mood, capturing the gentle tension of her pose and the romantic allure of deeply passionate literature." \
  "GLM 5.1" "Silk Sheet Serenade"

queue_job 34 "Captivating anime style illustration of a woman perched on a high stool. Her long, flawless legs cross at the ankles, swinging slightly. A thick grimoire rests open on her knees. Warm sunset glow illuminates her thighs through a window, emphasizing smooth skin and a short hemline. Alluring look over her shoulder. Vibrant linework, cel shading, subtle blush. A provocative, steamy atmosphere blending intellectual charm with undeniable magnetic physical appeal." \
  "GLM 5.1" "Sunset Grimoire Glow"

queue_job 35 "Bold pop art illustration of a woman reclining on a mod sofa. Her shapely legs, adorned with polka dot stockings, are stretched out provocatively. A yellow book covers her face. Neon pink and cyan lighting highlights the curves of her calves and thighs. High contrast, graphic lines, halftone dots. A playful yet intensely alluring vibe, turning the simple act of reading into a stunning, heated visual statement of allure." \
  "GLM 5.1" "Pop Art Page Turner"

# --- Kimi K2.6 Thinking ---
queue_job 36 "A graceful figure reclines upon velvet cushions, bare legs elegantly crossed while holding an open leather-bound novel. Soft golden light caresses smooth skin and weathered pages. Her relaxed posture suggests quiet confidence. Rich burgundy fabric drapes nearby. Warm shadows dance across the scene. This artistic composition celebrates feminine beauty and intellectual passion through painterly brushstrokes and romantic Renaissance-inspired atmosphere. Pure aesthetic elegance with tasteful artistic sophistication and quiet charm." \
  "Kimi K2.6 Thinking" "Literary Allure"

queue_job 37 "Sunlight streams through sheer curtains onto a woman stretched across window seat, long legs bare and relaxed against embroidered pillows. She cradles a thick poetry collection against her chest. Dust motes swirl in warm afternoon beams. Soft skin glows naturally. The intimate domestic scene radiates quiet sensuality through masterful oil painting technique. Gentle shadows accentuate elegant form. Intellectual beauty captured with refined artistic sensitivity and timeless natural feminine grace." \
  "Kimi K2.6 Thinking" "Reading by Windowlight"

queue_job 38 "A sophisticated woman sits upon marble staircase in grand library, bare legs crossed at ankle while balancing an antique atlas upon her lap. Towering bookshelves frame the composition. Warm lamplight illuminates smooth skin and gilt-edged pages. Her contemplative gaze drifts toward distant shelves. The atmosphere blends scholarly reverence with alluring aesthetic appeal. Classical architecture surrounds her. Painted in rich Baroque style with dramatic chiaroscuro lighting effects and timeless elegance." \
  "Kimi K2.6 Thinking" "Library Muse"

queue_job 39 "Reclining upon Persian rug before crackling fireplace, a woman reads with bare legs extended toward warmth. Crimson silk partially covers her form. Leather volumes scatter nearby. Firelight flickers across smooth skin and open pages. Her relaxed pose suggests complete absorption in literature. The scene balances domestic comfort with striking visual allure. Rich textures dominate. Rendered in contemporary digital painting style with warm amber palette and soft atmospheric perspective depth." \
  "Kimi K2.6 Thinking" "Study in Scarlet"

queue_job 40 "Beneath blooming wisteria arbor, a woman lounges upon weathered bench with bare legs draped casually over carved armrest. She holds a journal open against her knees. Dappled sunlight filters through purple blossoms onto smooth skin and vellum pages. Her peaceful expression radiates confident serenity. The idyllic outdoor setting merges natural beauty with intellectual curiosity. Fresh spring atmosphere prevails. Executed in impressionistic watercolor with luminous pastel tones and soft highlights." \
  "Kimi K2.6 Thinking" "Garden Reader"

# --- Deepseek ---
queue_job 41 "Elegant woman's slightly crossed legs in sheer black stockings and polished stiletto heels, a worn leather-bound book resting on her upper thigh near a short silk skirt hem. Warm soft lamplight casts dramatic deep shadows along her smooth skin, highlighting the curve of her calf. The elegant composition intimate and alluring, with a vintage armchair background. Her delicate fingers lightly trace the book's spine, evoking a quietly sultry mood." \
  "Deepseek" "The Reading Pose"

queue_job 42 "A woman's bare legs stretched on a plush chaise lounge, crossed slightly at ankles wearing a gold anklet. An open book rests face down on her lower thigh, pages catching warm candlelight. The pose relaxed yet inviting, with a soft cashmere throw beneath her. Sheer curtains filter evening glow, highlighting the curve of her knees. Her toes curl slightly near the book's edge, creating a sultry intellectual sensuality atmosphere." \
  "Deepseek" "Literary Allure"

queue_job 43 "A woman sits sideways on a chair, one leg draped over the armrest with a high heel dangling from her toes. Her other leg bent, foot flat on the floor. A book rests open on her lap, pages riffled by a breeze. Warm light accentuates the silhouette of her thighs and the arch of her foot. Her fingertips brush the book's margin, creating a moment of poised, inviting tension." \
  "Deepseek" "Contours of Curiosity"

queue_job 44 "A woman reclines on a velvet ottoman, her legs extended and crossed at the knees. She wears sheer nude stockings and strappy silver heels. A thick poetry book lies open against her inner thigh, her hand resting on the page. Low side lighting creates dramatic shadows that trace the line from her ankle to hip. Her pose is thoughtful yet enticing, a quiet invitation to read between the lines." \
  "Deepseek" "Pages & Silhouettes"

queue_job 45 "A woman sits cross-legged on a plush rug, her bare legs folded gracefully. A thick novel rests in her lap, its pages fanned open by her thumb. She wears a flowing silk robe that slips off one shoulder, revealing the curve of her upper thigh. Warm firelight flickers across her skin, accentuating the dip of her knee. Her pose is absorbed and subtly alluring, a study in quiet passion." \
  "Deepseek" "The Captivated Reader"

# --- Mistral ---
queue_job 46 "A stylish woman with elegantly crossed legs, reading a vintage book in a dimly lit library, soft golden light highlighting her silhouette, intricate lace stockings, high heels, and a flowing dress, cinematic composition, warm tones, hyper-detailed, artistic illustration, evocative mood, sophisticated and alluring atmosphere." \
  "Mistral" "Elegance in the Library"

queue_job 47 "A confident woman lounging on a velvet chaise, legs gracefully extended, holding an open book, silk robe draping her form, soft shadows and highlights, rich textures, luxurious setting, intimate yet tasteful, painterly style, deep contrasts, timeless elegance, captivating and refined aesthetic." \
  "Mistral" "Velvet and Silk"

queue_job 48 "A woman sitting on a windowsill, legs crossed, absorbed in a book, sunlight streaming through sheer curtains, delicate fabric of her dress catching the light, subtle play of shadows on her skin, serene yet magnetic presence, artistic illustration, warm palette, dreamy ambiance." \
  "Mistral" "Sunlit Serenity"

queue_job 49 "A poised woman in a cozy reading nook, legs elegantly positioned, book in hand, soft cashmere sweater and a pleated skirt, gentle lighting accentuating her posture, inviting and sophisticated, detailed textures, harmonious composition, artistic and alluring, warm and intimate atmosphere." \
  "Mistral" "Cozy Sophistication"

queue_job 50 "A woman reclining on a plush rug, legs slightly bent, deeply engrossed in a book, flowing hair cascading over her shoulders, soft fabric of her outfit hugging her form, warm candlelight creating a sensual glow, artistic illustration, rich details, captivating and tasteful allure." \
  "Mistral" "Candlelit Allure"

echo "✅ All 50 jobs queued in scheduler"
