#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

queue_job() {
  local index="$1"
  local prompt="$2"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:       $prompt,
      steps:        $steps,
      cfg_scale:    $cfg,
      cfg_true:     $ag,
      guidance_name: $gnm,
      guidance_scale: $gsc,
      width:        $w,
      height:       $h,
      sampler_name: $sampler,
      seed:         $seed,
      batch_size:   1,
      n_iter:       1,
      save_images:  true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Industrial pipelines art
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+15+-+industrial+pipelines
# Structure: 8 models × 5 prompts = 40 tasks total
# ---------------------------------------------------------------------------
prompts=()

# --- Claude Sonnet 4.6 ---

# 01 — Chromatic Pressure
prompts+=( "Industrial pipeline network photographed with extreme close-up macro lens, massive steel tubes dominating the entire frame, diagonal composition cutting across the canvas corner to corner. Surfaces layered with rust oxidation gradients — deep burnt sienna bleeding into copper orange, mint verdigris crusting the bolt flanges. Welded seams catch hard directional lighting from upper left, casting sharp industrial shadows across threaded couplings and pressure gauges. Paint peels in curling flakes revealing zinc primer beneath. Condensation beads on cold pipe surfaces. Background fully obscured by overlapping pipe geometry. Color palette: desaturated industrial amber, tarnished steel grey, oxide red, emergency valve yellow. Photorealistic rendering with shallow depth of field, nearest pipes razor-sharp, distant pipes dissolving into bokeh. High contrast, cinematic color grading. Gritty texture detail on every surface — pitting, corrosion, stamped metal markings, stenciled warning labels. The composition creates a claustrophobic density, no sky or open space visible, pure pipe geometry filling every corner of the frame. Dramatic chiaroscuro lighting emphasizing the brutalist beauty of utilitarian infrastructure. Shot quality matching large-format industrial photography." )

# 02 — Subterranean Labyrinth
prompts+=( "Underground utility tunnel stretching into vanishing point perspective, symmetrical corridor of pipes lining both walls floor to ceiling. Fluorescent strip lighting mounted on ceiling casting cold blue-white illumination, creating rhythmic light pools fading into distant darkness. Pipes vary in diameter from massive 60cm main arteries to finger-width capillaries, color-coded with institutional paint — medical blue, safety red, warning yellow, neutral grey. Water stains streak vertically down concrete walls between pipe brackets. Moisture hangs in the air, slight fog visible in mid-distance. Floor wet and reflective, mirroring the overhead pipe geometry in distorted twin. Perspective lines of pipe runs, cable trays, and conduit converge at a single focal point dead center, deep black vanishing point. Color grading: cool cyan shadows, warm sodium yellow in distant glow, desaturated midtones. Photorealistic architectural render quality. Metal expansion joints at regular intervals catch the light. Stenciled alphanumeric codes on every pipe segment. Emergency shutoff valves interrupt the runs at intervals. The tunnel feels endless, ancient, and functional — a subterranean circulatory system for a buried industrial organism. Cinematic depth, ultra-sharp foreground detail." )

# 03 — Steam Cathedral
prompts+=( "Refinery pipe rack photographed from low ground angle looking upward, towering steel pipe bridges crossing overhead against heavy overcast sky. Steam venting from multiple pressure relief valves creates billowing white clouds that diffuse the harsh backlight into ethereal glow. Silhouette contrast: dark pipe geometry against luminous steam-filled sky. Structural steel I-beams support horizontal pipe runs at multiple elevation tiers, creating layered architectural complexity. Foreground: cracked asphalt apron, puddles reflecting the overhead pipe tangle. Morning light condition, sun positioned directly behind the central pipe cluster, creating lens flare artifacts across horizontal runs. Rust and weathering concentrated at weld points and flanges. Some pipes insulated with silver aluminum jacketing, others bare carbon steel, others wrapped in yellow fiberglass batting. Color temperature split: warm golden backlight cutting through cool industrial grey. Compositional chaos resolved by strong upward perspective thrust. Scale dwarfing — a single human figure implied by scale relationship with pipe diameters but not present. Photographic realism, high dynamic range tone mapping preserving shadow detail under pipes while retaining blown-out steam highlights. Atmosphere: awe-inspiring industrial sublime." )

# 04 — Flat Graphic Schematic
prompts+=( "Technical illustration style rendering of industrial pipe network, bold flat graphic design aesthetic. Isometric projection showing interlocking pipeline system with T-junctions, elbows, reducers, valves, pumps and flanged connections. Clean vector-art quality lines with deliberate graphic weight variation — thick outlines, medium wall lines, thin detail lines. Strict color palette: pure Pantone red pipes, cobalt blue pipes, industrial yellow accent elements, cool grey structural steel, white background. Infographic clarity — every component type uses consistent visual language. Pressure gauges drawn as clean circular dials, valves as standardized symbols. Pipe labels in clean sans-serif industrial stencil typeface. Isometric grid perfectly consistent throughout. Drop shadows rendered as flat geometric shapes, no gradients. Bold graphic quality evoking vintage engineering manuals and Soviet industrial posters simultaneously. Retro technical illustration meets contemporary flat design. Flow direction arrows on every pipe segment, clean chevron style. Section callouts with numbered leaders. Compositional balance: main header pipe runs diagonally across canvas from lower-left to upper-right, branching symmetrically. The overall image reads as both functional diagram and pure graphic art object. Print-quality precision." )

# 05 — Golden Hour Refinery
prompts+=( "Aerial oblique perspective of oil refinery pipe complex during golden hour, late afternoon sun at fifteen degrees above horizon casting extreme long shadows from every vertical pipe stack and vessel. Hundreds of parallel pipe runs stretch across the frame in organized industrial geometry, their shadows creating striped pattern across the ground plane. Atmospheric haze from refinery emissions catches warm golden light, creating volumetric beams between tall distillation columns. Color palette dominated by amber, bronze, deep shadow purple, chrome highlight. Pipes in foreground massive and sharp, scale decreasing geometrically toward horizon. Cooling towers emit white steam plumes catching backlight. Distillation columns rise vertically, breaking the horizontal pipe geometry with punctuation marks. Surface detail rich with insulation jacketing, scaffolding remnants, catwalks, ladder cages, instrument clusters. Color grading: golden highlights pushed warm orange, shadows crushed into deep cool blue-violet, midtones desaturated for cinematic industrial look. Photorealistic drone photography quality. Flare from direct sun partially blocked by pipe cluster edge. The image balances raw industrial complexity with the transcendent beauty of light, transforming utilitarian infrastructure into landscape painting of monumental scale and quiet grandeur." )

# --- Gemini 3.5 Flash ---

# 06 — Abstract Biomechanical Network
prompts+=( "A hyper-detailed macro close-up of an intricate industrial pipeline network, transformed into an abstract biomechanical art piece. Thick, heavy-duty steel conduits, weathered copper tubes, and transparent acrylic pipes intertwine like organic blood vessels and muscular fibers. Glossy black oil and glowing neon-cyan coolant fluid visibly pulse through the translucent sections. The metal surfaces are highly textured, showing patches of oxidation, fine rust, industrial grime, and microscopic scratches from years of heavy use. Brass pressure gauges with cracked glass faces and analog needles pinned to the red zone are clustered at junctions, while heavy iron wheel valves with peeling red paint anchor the composition. The lighting is dramatic, high-contrast chiaroscuro, with sharp volumetric beams cutting through a dense, hazy atmosphere of swirling steam and airborne dust motes. Moody amber underlighting reflects off the metallic surfaces, casting deep, complex shadows that accentuate the three-dimensional depth and industrial complexity." )

# 07 — Constructivist Geometry
prompts+=( "A bold, geometric constructivist art piece focused on massive industrial pipelines, emphasizing hard lines, sharp angles, and monumental scale. Colossal cylindrical pipes of varying diameters slice across the frame in rigid vertical, horizontal, and sharp diagonal axes, creating a complex, multilayered grid pattern. The color palette is strictly limited to deep industrial matte charcoal, striking cadmium red, stark safety yellow, and cold concrete gray. Every surface has a physical, tactile presence, detailed with heavy steel rivets, chunky flanged joints, bolted brackets, and stenciled alphanumeric serial codes wearing away at the edges. The composition relies on extreme perspective, looking up from a low angle to make the structural framework feel immense and imposing. The lighting is harsh, direct, and unyielding, mimicking a powerful overhead factory floodlight that casts crisp, hard-edged geometric shadows onto the background of corrugated metal panels and raw steel girders." )

# 08 — Steampunk Alchemy
prompts+=( "A warm, atmospheric vintage industrial artwork capturing a labyrinth of antique steam pipelines in an alchemical workshop setting. The scene is dominated by polished brass, weathered bronze, and dark, hammered cast iron pipes wrapped in frayed canvas insulation and secured with tarnished metal bands. Hissing steam escapes from tiny pinhole leaks near old-fashioned riveted seams, catching the light and creating a soft, ethereal fog. Intricate clockwork mechanisms, exposed copper gears, and delicate glass pressure tubes containing bubbling amber liquid are seamlessly integrated into the pipeline junctions. The overall mood is nostalgic and warm, illuminated by the soft, flickering orange glow of nearby smelting furnaces and exposed Edison filament bulbs. Rich reflections glimmer on the curved metallic surfaces, highlighting a fine patina, oil smudges, and hand-crafted imperfections. The background fades into a deep, velvety darkness, keeping the focus entirely on the beautiful, chaotic complexity of the piping network." )

# 09 — Cyberpunk Conduit
prompts+=( "A vibrant, futuristic cyberpunk take on industrial infrastructure, showcasing a dense nexus of high-tech pipelines running through an urban underbelly. Sleek, matte-black carbon-fiber conduits run parallel to weathered chrome pipes, creating a high-tech contrast. Brilliant pink, electric purple, and lime green LED strips are embedded into the pipe casings, casting a vivid, colorful neon wash over the entire structure. Some specialized pipes are transparent, revealing swirling streams of bioluminescent nano-fluids and sparkling data currents flowing inside. Rainwater drips from the ceiling, gathering into glossy puddles on the ground that mirror the chaotic light display, while wisps of synthetic purple vapor drift lazily between the gaps. The setting is gritty and rain-slicked, filled with tech-clutter like exposed wiring harnesses, optical data fibers, and digital holographic pressure readouts flickering in the damp air." )

# 10 — Surrealist Liquid Dream
prompts+=( "A dreamlike, surrealist interpretation of industrial architecture where rigid pipelines mimic fluid movement. Massive, heavy iron pipes seamlessly bend, twist, and melt around each other in impossible, organic curves, defying gravity and structural physics. The pipelines are painted in contrasting textures, seamlessly transitioning from matte, chalky terracotta to polished mirror-finish chrome that reflects a distorted, surreal environment. At several open junctions, the pipelines do not release smoke or steam, but instead pour out thick, ribbons of colorful satin fabric and molten metallic gold that float and suspended in mid-air. The background is a clean, minimalist space with soft, diffused twilight illuminating the scene from no visible source, creating a calm, gallery-like atmosphere. Soft, elongated shadows stretch across the floor, emphasizes the smooth, graceful contours of the warped metal structures." )

# --- ChatGPT ---

# 11 — Cathedral of Steel Veins
prompts+=( "A vast industrial landscape reimagined as a sacred architectural masterpiece, where endless pipelines form a towering cathedral of steel and shadow. Massive cylindrical pipes twist and intersect like gothic arches, stretching upward into a hazy, smoke-filled sky illuminated by diffused amber and cold blue industrial lighting. Surfaces are worn, oxidized, and layered with textures of rust, grease, and condensation, reflecting decades of use. Steam leaks gently from joints and valves, creating a soft atmospheric fog that diffuses light into painterly gradients. The composition emphasizes symmetry and vertical grandeur, with repeating pipe patterns guiding the eye toward a central vanishing point. Small human silhouettes in protective gear stand at the base, emphasizing scale and insignificance against the mechanical monolith. Incorporate intricate details such as bolts, pressure gauges, welded seams, and dripping moisture. The mood is both reverent and dystopian, blending industrial realism with surreal artistic interpretation. Style combines photorealistic rendering with subtle painterly abstraction, high dynamic range lighting, cinematic depth, and tactile material contrast between matte corrosion and reflective metal." )

# 12 — Neon Arteries of the Machine City
prompts+=( "A futuristic industrial environment where pipelines act as glowing arteries feeding an unseen mechanical organism beneath a sprawling megastructure. The pipes weave through the scene in complex layers, illuminated internally by vibrant neon fluids in hues of electric cyan, toxic green, and molten orange. Transparent sections reveal the movement of luminous liquid, creating dynamic flow and energy. The surrounding environment is dark and metallic, with reflective surfaces catching the neon glow and scattering it across wet floors and steel walls. The composition is dense and chaotic yet controlled, with pipes bending in organic, almost biological patterns, merging industrial design with anatomical inspiration. Vapor clouds drift through the scene, interacting with colored light to create volumetric effects. Small sparks, flickering panels, and distant machinery suggest constant activity. The aesthetic blends cyberpunk atmosphere with industrial realism, emphasizing contrast between cold metal and vibrant light. Highly detailed textures, cinematic lighting, and a sense of motion bring the scene to life, evoking a living, breathing infrastructure system." )

# 13 — Rust Ocean Pipeline Fields
prompts+=( "An expansive, surreal industrial seascape where massive pipelines stretch endlessly across a barren terrain resembling a dried ocean floor. The pipes run parallel and intersect at vast junctions, forming patterns reminiscent of waves frozen in time. The color palette is dominated by deep rust reds, burnt orange, and desaturated earth tones, contrasted by pale sky hues and occasional metallic highlights. Surfaces are heavily weathered, with peeling paint, corrosion, and layered sediment textures suggesting abandonment and age. Pools of reflective liquid gather between structures, mirroring the sky and adding visual depth. The horizon is distant and slightly obscured by atmospheric haze, enhancing scale and isolation. The composition focuses on repetition and rhythm, with pipelines guiding the viewer's eye across the landscape in sweeping lines. No visible humans, only traces of past activity — forgotten tools, broken valves, and silent machinery. The mood is melancholic and contemplative, blending industrial decay with natural erosion. Rendered in a hybrid style of photorealism and fine art painting, emphasizing texture, light diffusion, and environmental storytelling." )

# 14 — Subterranean Pressure Network
prompts+=( "A cross-sectional view of an underground industrial pipeline system, revealing a dense, layered network beneath the surface. The scene is divided between the earth above — minimal, calm, and natural — and the complex mechanical world below, filled with interlocking pipes, valves, and chambers. The pipelines vary in diameter and material, some polished and modern, others aged and corroded. Fluids of different colors flow through transparent segments, indicating separate systems operating simultaneously. Lighting is strategic and dramatic, with embedded industrial lamps casting warm highlights and deep shadows across the structure. The soil layers above are detailed with roots, rocks, and subtle geological textures, contrasting organic forms with engineered precision. The composition emphasizes depth and complexity, with overlapping elements creating a sense of claustrophobic density. Small maintenance drones or workers navigate the network, adding scale and narrative. The style blends technical illustration with cinematic realism, focusing on clarity, structure, and intricate detail while maintaining an atmospheric, slightly surreal tone." )

# 15 — Industrial Pipeline Symphony
prompts+=( "An artistic interpretation of pipelines as musical instruments, forming a grand mechanical orchestra. Pipes of varying sizes curve and align like brass and wind instruments, with valves resembling keys and joints acting as tuning mechanisms. Steam bursts and pressure releases are synchronized visually, suggesting rhythm and sound translated into motion. The environment is a large industrial hall with dramatic lighting — spotlights cutting through haze, illuminating sections of the orchestra while leaving others in shadow. Metallic surfaces reflect light in complex ways, creating visual harmony and contrast. The composition is dynamic and flowing, with pipes arranged in sweeping arcs that guide the viewer's eye like musical phrasing. Subtle vibrations and heat distortions in the air hint at energy and resonance. Color palette mixes warm industrial tones with occasional cool highlights, enhancing depth and mood. The aesthetic balances realism with conceptual abstraction, transforming utilitarian structures into expressive forms. Highly detailed textures, cinematic composition, and a sense of rhythm make the scene feel alive, as if the entire system is performing a silent mechanical symphony." )

# --- Grok ---

# 16 — Symphonic Industrial Pipelines
prompts+=( "A highly detailed cinematic masterpiece of intricate industrial pipelines weaving through a massive futuristic refinery complex at golden hour. Massive steel pipes of varying diameters intertwine like metallic veins and arteries, some wrapped in weathered insulation, others gleaming with polished chrome and brass fittings. Complex networks of valves, pressure gauges, flanges, and welding seams create rhythmic patterns. Warm industrial lighting casts dramatic highlights and deep shadows across the structures. Steam gently rises from joints, mixing with golden sunlight. Background shows towering distillation columns and catwalks. Moody atmospheric perspective, intricate mechanical details, hyper-realistic textures, industrial beauty, symmetrical composition, masterful engineering aesthetic, volumetric lighting, photorealistic yet artistic." )

# 17 — Neon Cybernetic Pipeline Rivers
prompts+=( "Futuristic cyberpunk industrial pipelines flowing like luminous rivers through a sprawling megacity refinery at night. Vibrant neon blues, electric purples, and toxic greens illuminate the dense network of interconnected pipes, valves, and junctions. Holographic data streams and digital overlays project onto metallic surfaces. Heavy rain creates reflective puddles showing neon glows. Dense fog and atmospheric haze add depth. Massive pipes curve dynamically across multiple layers, some suspended high above, others running underground. Detailed rust, condensation droplets, warning labels, and industrial graffiti. Blade Runner inspired mood, high contrast cinematic lighting, intricate mechanical complexity, cyber-industrial art style." )

# 18 — Steampunk Mechanical Pipeline Symphony
prompts+=( "Ornate steampunk industrial pipelines in a grand Victorian-era factory cathedral. Beautifully crafted brass, copper, and iron pipes with elaborate decorative rivets, gears, and pressure dials form an artistic labyrinth. Leather-wrapped sections and glass viewing ports reveal flowing colorful liquids. Giant flywheels and steam engines power the system. Warm gas lamp lighting creates rich golden tones and deep amber shadows. Intricate engravings and gothic architectural elements blend with industrial machinery. Dramatic low angle perspective emphasizing scale and complexity. Highly detailed textures, mechanical precision, romantic steampunk aesthetic, masterpiece composition." )

# 19 — Post-Apocalyptic Pipeline Ruins
prompts+=( "Dramatic post-apocalyptic industrial pipelines in an abandoned overgrown refinery complex. Weathered and rusted massive pipes cracked and broken in places, overtaken by lush vegetation and vines. Golden hour sunlight filters through dusty air illuminating beautiful decay. Pools of reflective water and scattered debris create melancholic atmosphere. Nature reclaiming technology with wildflowers growing from pipe joints. Atmospheric perspective with distant ruined towers. Detailed rust textures, peeling paint, exposed wiring, and structural damage. Haunting beauty in industrial decay, cinematic composition, emotional storytelling through visual details, masterful environmental art." )

# 20 — Abstract Geometric Pipeline Dreams
prompts+=( "Surreal abstract industrial pipelines as an artistic geometric symphony. Pipes transform into flowing mathematical patterns and impossible architectures floating in ethereal space. Clean metallic surfaces reflect fragmented colorful lights creating prismatic effects. Pipes bend in organic yet mechanical ways, intersecting at perfect angles with glowing energy flows. Minimalist yet incredibly detailed mechanical elements blend with dreamlike surrealism. Soft volumetric god rays and floating particles enhance the otherworldly mood. Balanced composition with strong visual rhythm, modern industrial abstract art, sophisticated color palette of deep teals, coppers, and crimsons, high-end conceptual art piece." )

# --- Qwen 3.6 Plus ---

# 21 — Veins of the Forge
prompts+=( "A sprawling network of weathered industrial pipelines dominates the composition, arranged in an intricate geometric web that stretches across a vast, misty landscape. The steel surfaces exhibit authentic patina, with layers of rust, peeling insulation cladding, and condensation droplets clinging to curved joints. Steam gently escapes from pressure relief valves, catching the warm, diffused light of a low-hanging sun. The lighting emphasizes deep shadows and metallic reflections, creating a dramatic chiaroscuro effect that highlights the structural complexity. In the background, faint silhouettes of support towers and distant refinery structures blend into a soft atmospheric haze. The foreground features a carefully balanced arrangement of flanged connections, bolted manifolds, and reinforced elbows, rendered with meticulous photorealistic detail. Subtle color grading introduces muted iron tones, oxidized copper accents, and desaturated slate grays, evoking a sense of enduring machinery and quiet industrial grandeur. The composition maintains perfect symmetry with deliberate asymmetrical elements, drawing the eye through converging lines and layered depth. Every weld seam and corrosion pattern is rendered with photographic precision, transforming utilitarian infrastructure into a compelling visual narrative of engineering resilience and timeless mechanical beauty." )

# 22 — Metallic Currents
prompts+=( "An abstract interpretation of industrial pipelines where rigid steel conduits seamlessly transition into flowing, organic ribbons of liquid metal. The composition features sweeping curves that intersect and diverge, creating a dynamic rhythm across the frame. Each pipe surface shimmers with iridescent patinas, shifting between deep oxidized teals, brushed brass, and pearlescent silver. Translucent glass-like segments reveal glowing inner currents that pulse with soft ambient light, suggesting energy moving through the system. The background dissolves into a gradient of smoky charcoal and warm amber, allowing the central network to float in a dreamlike spatial void. Welded seams appear as delicate gold filigree, while pressure gauges and valve wheels are reimagined as minimalist geometric ornaments. The lighting is soft yet directional, casting elongated, blurred shadows that merge with the surrounding atmosphere. Subtle motion blur along the pipe trajectories enhances the sensation of continuous flow. Textural contrast between polished reflective zones and matte weathered sections adds tactile depth. The overall aesthetic balances mechanical precision with fluid surrealism, transforming utilitarian infrastructure into a mesmerizing visual symphony of form, light, and imagined motion." )

# 23 — Neon Arteries
prompts+=( "A futuristic industrial pipeline system illuminated by vibrant neon accents, where high-tech conduits weave through a dense urban infrastructure grid. The primary pipes feature matte black carbon composite exteriors interlaced with glowing cyan and magenta data streams that pulse along embedded channels. Precision-engineered valves, smart sensors, and modular junction boxes are seamlessly integrated into the network, each component rendered with sharp geometric clarity. Rain-slicked surfaces reflect the ambient city lights, creating intricate mirror-like distortions that multiply the glowing elements. Overhead, suspended support cables and tension rings form a rhythmic architectural canopy, while the lower frame reveals layered drainage grates and maintenance platforms. The atmosphere is thick with cool mist, diffusing the harsh neon into soft volumetric beams that cut through the composition. Color grading emphasizes electric blues, deep violets, and metallic gunmetal grays, establishing a high-contrast cybernetic mood. Every joint, seam, and access hatch is meticulously detailed with brushed metal finishes and subtle weathering. The perspective uses leading lines that converge toward a luminous central nexus, transforming utilitarian utility networks into a striking vision of advanced mechanical infrastructure." )

# 24 — Structured Flow
prompts+=( "A minimalist architectural study of industrial pipelines rendered with clean lines, precise geometry, and deliberate negative space. The composition features a carefully balanced arrangement of straight conduits, sharp ninety-degree elbows, and symmetrical flange connections set against a smooth, untextured off-white backdrop. The pipes are finished in uniform matte slate gray, with subtle tonal variations created by soft, diffused overhead lighting that emphasizes form over surface detail. Welded joints appear as crisp, uninterrupted seams, while pressure indicators and valve handles are reduced to essential geometric shapes. The layout follows a strict grid-like rhythm, with parallel lines intersecting at calculated intervals to create a sense of measured harmony. Shadows are restrained and uniformly cast, avoiding harsh contrast in favor of gentle gradations that enhance spatial depth. Minimalist typography-style labeling plates are discreetly mounted on select junctions, adding subtle visual anchors without cluttering the composition. The overall aesthetic prioritizes structural clarity, mathematical precision, and quiet elegance. Every element serves a compositional purpose, transforming functional industrial infrastructure into a refined visual meditation on order, balance, and engineered simplicity." )

# 25 — Rust and Reverie
prompts+=( "An impressionistic interpretation of industrial pipelines where heavy steel conduits dissolve into expressive brushwork and rich atmospheric color. The composition features overlapping pipe networks rendered with visible impasto strokes, capturing the raw texture of corroded iron, layered insulation, and weathered support brackets. Warm ochre, burnt sienna, and oxidized green dominate the palette, with subtle highlights of pale gold catching the edges of flanged connections and bolted manifolds. The background blends into a soft wash of muted blues and grays, allowing the central pipeline forms to emerge through layered glazing and loose directional marks. Steam and ambient haze are suggested through translucent paint application, creating a dreamlike diffusion of light and shadow. Valve wheels and pressure gauges are hinted at with quick, gestural strokes rather than precise rendering, emphasizing movement and tactile energy over mechanical accuracy. The composition balances chaotic overlapping lines with deliberate negative spaces, guiding the viewer through a rhythmic flow of color and form. Every surface tells a story of exposure and endurance, transforming utilitarian infrastructure into a lyrical celebration of industrial heritage and artistic abstraction." )

# --- GLM 5.1 ---

# 26 — Chrono-Plumbing: A Steampunk Symphony
prompts+=( "Intricate steampunk industrial pipeline art, a mesmerizing labyrinth of interwoven brass and copper pipes dominating the canvas. Polished metallic surfaces reflect warm, amber gaslight, contrasting with areas of deep verdigris and soot-stained tarnish. Complex valve wheels and pressure gauges with cracked glass faces punctuate the cylindrical network, emitting gentle wisps of white steam that catch the glowing light. The aesthetic blends Victorian engineering with artistic fantasy, featuring ornate filigree joints, heavy riveted iron plates, and delicate clockwork mechanisms integrated into the plumbing. The composition creates a sense of infinite depth, drawing the viewer's eye through winding metallic tunnels that seem to breathe with pressurized energy. Surrounding the central network are scattered blueprints and mechanical tools, adding narrative depth. Cinematic volumetric lighting pierces through the gaps, creating dramatic chiaroscuro shadows that emphasize the three-dimensionality of the tubes. Every pipe tells a story of industrial revolution, transforming cold machinery into a beautiful, organic metallic sculpture. Hyper-detailed textures, photorealistic rendering, rich warm color palette of gold, bronze, and deep brown, symmetrical balance, masterpiece." )

# 27 — Neon Conduit: Cyberpunk Circulatory System
prompts+=( "Futuristic cyberpunk industrial pipeline art, a dense network of high-tech conduits and hydraulic tubes forming a sprawling mechanical circulatory system. The pipes are constructed from brushed titanium and matte black carbon fiber, accentuated by glowing neon strips of electric blue and magenta. Translucent sections of tubing reveal pulsing, luminescent fluids coursing through the infrastructure, casting vibrant reflections on the slick metallic surfaces. Digital readouts and holographic pressure monitors float near intricate junction blocks, adding a layer of advanced technology. Raindrops condense on the cold metal, occasionally dripping into the shadows below. The intricate weaving of massive sewer mains and delicate fiber-optic cables creates a visual paradox of brute strength and delicate data streams. Fog rolls through the lower sections, diffusing the neon glow and adding profound depth to the industrial maze. Ray-traced reflections, hyper-realistic, cinematic lighting, dark moody atmosphere with vivid color pops, sharp focus, intricate mechanical details, masterpiece." )

# 28 — Bio-Forge: The Living Pipework
prompts+=( "Surreal bioluminescent industrial pipeline art, an otherworldly fusion of heavy rusted machinery and thriving organic life. Massive corroded iron pipes twist and turn like the roots of an ancient tree, heavily encrusted with barnacle-like mechanical growths and blooming bioluminescent flora. Glowing cyan and emerald mosses cling to the damp, decaying metal, casting an ethereal light across the scene. Translucent, vein-like tubes carry a luminous, sap-like fluid that pulses with a slow, rhythmic heartbeat, intertwining with the rigid steel valves and flanges. The atmosphere is humid and misty, with floating spores catching the bioluminescent glow like tiny stars. The junctions where metal meets flesh are seamless, suggesting a forgotten factory that has evolved into a living, breathing entity. Water droplets fall from rusted bolts, glowing briefly as they pass through the radiant light. The color palette is dominated by deep oxide oranges, contrasting sharply with the neon greens and electric blues of the plant life. Dreamlike atmosphere, cinematic volumetric fog, macro-level detail, magical realism, dark fantasy art, masterpiece." )

# 29 — Iron Veins: The Macro Geometry of Decay
prompts+=( "Abstract macro industrial pipeline art, an extreme close-up of interconnected metal pipes focusing on the breathtaking geometry of decay. The composition highlights the intricate textures of peeling lead paint in shades of faded turquoise and mustard yellow, revealing the raw, heavily oxidized rust beneath. Rivets and welded seams create strict, repetitive linear patterns that contrast with the organic, flaking deterioration of the surfaces. A single drop of condensation clings to a corroded flange, refracting the ambient light. The lighting is harsh and directional, casting deep, sharp shadows that emphasize the raised edges of chipped paint and the pitted surface of the iron. The depth of field is shallow, blurring the background pipes into a soft bokeh of industrial grays and browns, forcing the viewer's attention onto the microscopic imperfections of the foreground. Tiny spiderwebs stretch between a pressure gauge and a rusted valve, adding a delicate touch to the heavy metal. The play of light across the curved surfaces transforms functional engineering into a poignant study of entropy. Photorealistic, extreme detail, fine art photography, dramatic chiaroscuro, rich earthy color palette, raw industrial aesthetic, masterpiece." )

# 30 — Chrome Labyrinth: Constructivist Pipeline Dream
prompts+=( "Abstract constructivist industrial pipeline art, a surreal and highly geometric composition featuring a complex, overlapping maze of polished chrome and brushed steel tubes. The pipes intersect at impossible angles, forming a dynamic visual puzzle of circles, cylinders, and sharp diagonal lines. The metallic surfaces are flawless and mirror-like, reflecting a fragmented sky with scattered clouds and abstract shapes. The lighting is bright, crisp, and studio-quality, eliminating shadows and enhancing the sheer brilliance of the metallic sheen. Bold primary colors, vivid red, bright yellow, and deep blue, mark specific functional zones on the pipes, such as valve handles and warning stripes, adding a De Stijl aesthetic to the industrial theme. The perspective is isometric, giving the tangled network an architectural, blueprint-like clarity. There is no rust, no decay, only the pristine perfection of manufactured forms intersecting in a vacuum of pure design. Spherical joints and perfectly toroidal bends elevate the functional to the sculptural. Crisp edges, minimalist environment, surrealism, hyper-clean rendering, 3D render style, vibrant color blocking, architectural precision, masterpiece." )

# --- Kimi K2.6 Thinking ---

# 31 — Rusted Arteries of the City
prompts+=( "A monumental network of weathered industrial pipelines stretching across an abandoned factory complex, their corroded steel surfaces painted in layers of burnt orange rust and faded industrial blue. Massive cylindrical conduits intersect at impossible angles, bolted flanges and pressure valves creating geometric rhythm against crumbling brick walls. Steam vents release ethereal white plumes that catch golden hour sunlight, casting long dramatic shadows across oil-stained concrete floors. Riveted joints and welded seams tell stories of decades of heavy use, while patches of peeling lead paint reveal chromatic history beneath. In the foreground, a complex manifold of copper and iron pipes descends from shadowy ceiling heights, connected by vintage pressure gauges with cracked glass faces. The composition emphasizes the brutalist beauty of functional architecture, where utilitarian engineering becomes unintended sculpture. Moss and small ferns colonize lower pipe runs, nature's quiet reclamation of human industry. Atmospheric perspective pushes distant pipeline towers into hazy blue-gray silhouettes. Photorealistic textures highlight every pit in the oxidized metal, every drip of condensed moisture, every reflection in standing puddles of rainwater on the factory floor." )

# 32 — Pipeline Cathedral at Midnight
prompts+=( "An awe-inspiring interior view of a vast pipeline junction chamber illuminated by sparse amber safety lights, creating chiaroscuro drama across endless rows of parallel steel tubes. The massive cylindrical structures recede into absolute darkness, their polished aluminum and stainless steel surfaces reflecting the sparse lighting like industrial stained glass. Catwalks and grated walkways spiral between vertical pipe arrays at multiple levels, tiny human-scale railings emphasizing the cathedral-like scale of the infrastructure. Condensation beads on cold metal surfaces, catching light like scattered diamonds. The architecture references both Gothic ribbed vaulting and modern brutalism, with arched support beams framing the repetitive vertical lines of process piping. A single distant figure in hard hat and reflective vest provides scale, silhouetted against a glowing red valve wheel. Color palette restricted to deep blacks, molten golds, and steel grays with occasional emergency red accents. Steam rises in volumetric shafts through overhead grating. The mood is solemn and reverent, transforming mechanical infrastructure into sacred space. Hyper-detailed metalwork shows machining marks, stamped identification numbers, and heat discoloration from welding." )

# 33 — Chromatic Refinery Dreams
prompts+=( "A surreal artistic interpretation of industrial pipelines transformed into an abstract color field composition, where miles of interconnected pipes become flowing ribbons of saturated color against a stark white background. Petroleum-distillation inspired gradients shift from deep crimson through tangerine, sulfur yellow, emerald green, to cobalt blue and violet, each pipe carrying a different hue like liquid light. The network forms an intricate mandala pattern viewed from directly above, symmetrical yet organically complex, with smaller capillary-like tubes branching from major arterial conduits. Translucent sections reveal bubbling fluids within, creating internal glow and caustic light patterns on adjacent surfaces. Some pipes terminate in artistic rather than functional joints — welded curves that serve no engineering purpose except visual harmony. The industrial aesthetic is preserved through visible flanges, valve handles, and pressure sensors, but recontextualized as decorative elements. Shadows are soft and pastel-tinted, defying the harsh lighting typical of real facilities. The overall effect balances technical precision with psychedelic imagination, honoring both the mathematical beauty of pipe routing and the expressive potential of color theory. Clean, gallery-worthy presentation with museum lighting." )

# 34 — Subterranean Pipeline Nexus
prompts+=( "A claustrophobic yet mesmerizing view inside an underground utility tunnel where water mains, gas lines, electrical conduits, and fiber optic cables compete for space in organized chaos. The concrete vault ceiling drips with calcite deposits and mineral stains, while LED work lights mounted on temporary stands cast harsh white illumination across the scene. Ancient cast-iron pipes with ornate bell joints dating to the 1920s parallel modern HDPE plastic tubing in electric blue, creating temporal dialogue between industrial eras. Every surface carries information — stenciled identification codes, directional arrows, corrosion monitoring patches, and cathodic protection wires wrapping around older steel like metallic vines. At the composition's center, a massive butterfly valve with wheel handle stands open, its brass components gleaming with maintenance oil. The floor is a dangerous maze of standing water reflecting the overhead pipe maze in rippled mirror images. Atmospheric humidity creates visible light rays and lens flare effects. The image captures the hidden heroic infrastructure of modern civilization, the buried vascular system of the metropolis, rendered with documentary photography authenticity and slight cinematic color grading that enhances the yellows of aged brass and the oranges of rust." )

# 35 — Pipeline Terminus at Dusk
prompts+=( "An exterior landscape where a coastal industrial pipeline complex meets the ocean at twilight, massive diameter pipes emerging from cliff-side processing facilities to stretch across tidal flats like mechanical tentacles. The sky burns with industrial sunset colors — fuchsia, burnt orange, and particulate haze purple — reflected in the wet surfaces of weatherproof coatings and marine-grade stainless steel. Barnacles and corrosion-resistant paint create textural contrast on submerged sections, while above-water portions show heat-shimmer from operational contents. Pump stations and compressor buildings with corrugated metal siding dot the pipeline route, their small square windows glowing with warm interior light against the cooling exterior. The pipes themselves become leading lines drawing the eye toward a distant offshore loading buoy silhouetted against the luminous horizon. Seagulls perch on expansion joints and relief valves, adding organic life to the mechanical scene. Long exposure effects smooth the ocean surface to milky stillness while maintaining sharp detail in the industrial architecture. The mood evokes melancholic grandeur, humanity's ambition to transport resources across natural boundaries, rendered in the painterly style of contemporary industrial landscape photography with rich dynamic range and subtle HDR tonality." )

# --- Deepseek ---

# 36 — Steampunk Serpentine
prompts+=( "A mesmerizing labyrinth of oxidized copper and brass pipelines winding through a dim, steampunk factory. Steam hisses from pressure valves while warm amber light spills from small glass portholes, illuminating droplets of condensation on the metal surfaces. The pipes twist into intricate knots, some adorned with antique gauges and riveted joints. In the background, softer, blurred pipes fade into misty shadows, creating a sense of depth. The mood is both mechanical and mysterious, like the innards of a living machine. Colors range from verdigris green to burnished gold, with hints of rust at the seams. Sharp focus on the central pipeline cluster, with gentle bokeh on the periphery. No humans or overtly digital elements. The composition emphasizes spirals and curves, transforming cold industrial material into organic, flowing art." )

# 37 — Neon Flux Arteries
prompts+=( "A futuristic vision of industrial pipelines as glowing cybernetic arteries. The pipes are sleek, white ceramic-coated metal, but pulsing neon cyan and magenta energy courses through translucent sections. The scene is set in a clean, minimalist facility with polished floors reflecting the vibrant light. Pipelines branch like a circulatory system, some intersecting in circular junctions that emit soft holographic rings. Small robotic maintenance drones hover nearby, adding scale without distracting. The atmosphere is silent yet electric, blending sterile industry with bioluminescent life. Fine details include etched circuit patterns on pipe surfaces and subtle vapor trails near exhaust vents. Color palette dominated by deep charcoal, electric blue, and hot pink. The overall effect is both high-tech and artistic, suggesting a futuristic fusion of machine and organism." )

# 38 — Rust Cathedral
prompts+=( "An evocative composition of massive, abandoned pipelines rising like Gothic cathedral pillars. Thick layers of rust in burnt orange, deep brown, and faint purple create a textured, painterly surface. Weeping patches of moss and mineral stains trickle down the vertical pipes. Soft, dusty light beams from a high unseen source, cutting through floating particles in the air. The pipelines are arranged asymmetrically, with some curved arches and broken flanges suggesting a ruined sanctuary. A shallow puddle on the ground reflects a distorted upside-down pipe, doubling the visual interest. No vegetation or animals; the art lies in decay itself. The mood is solemn, majestic, and melancholic. High contrast between shadowed crevices and glowing highlights, evoking a religious silence within industrial ruins." )

# 39 — Kinetic Harmony
prompts+=( "A dynamic abstract composition where colorful industrial pipelines dance in rhythmic motion. Pipes in vivid safety yellow, fire engine red, and deep blue loop and cross each other against a neutral gray background. Some sections are transparent, revealing swirling fluids inside. The arrangement suggests a musical score or ballet choreography, with curved tubes forming parabolic arcs. Soft, diffuse overhead lighting eliminates harsh shadows, giving the scene a studio-lit, almost surreal clarity. Small pressure gauges act like musical notes on the staff of pipes. Every joint is perfectly seamless, blending function with fluid art. The background fades to a gentle gradient, keeping focus on the interlocking loops. This image celebrates order, color, and movement, turning utility into visual poetry. No human presence, only the joyful interplay of form and hue." )

# 40 — Frost Forge
prompts+=( "A chilling scene of industrial pipelines in a subzero environment. Thick white frost and icicles encrust the dark steel pipes, creating a stark contrast between raw metal and crystalline ice. The main pipe cluster forms a massive spiral, like a frozen cyclone. Pale blue winter light filters through a high frosted window, casting cool shadows. Tiny ice particles float in the air, catching light like diamonds. Some pipes have burst open, revealing jagged frozen edges that resemble ice flowers. The composition is tightly cropped on the central spiral, with frost patterns spreading outward. No warmth or color except icy blues, grays, and hints of oxidized iron. The mood is desolate yet beautiful, transforming industrial failure into an elegant frozen sculpture." )

# ---- QUEUE JOBS ------------------------------------------------------------
for (( i=0; i<${#prompts[@]}; i++ )); do
  queue_job $((i+1)) "${prompts[$i]}"
done

echo "✅ All ${#prompts[@]} jobs queued in scheduler"
