#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Artistic abstract art of face and flowers
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+17+-+faces+and+flowers
# Structure: 9 models × 5 prompts = 45 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A woman's face dissolves into cascading peonies, rendered in loose oil ink washes — indigo bleeding into ivory, carmine pooling where cheekbone meets blossom. Her left eye remains sharply defined, heavy-lidded and watchful, while the right side of her face scatters into falling petals, each one catching a ghost of her expression. The background holds a deep prussian blue, textured with dry-brush strokes suggesting rain or breath. Ink bleeds freely past drawn boundaries. The transition between flesh and flower is deliberate but tender — not destruction, not transformation, but a quiet negotiation between identity and nature. Mood: melancholic and intimate. Style references: Japanese sumi-e meets European expressionism, wet media on rough paper." \
  "Claude Sonnet 4.6" "Dissolution at Petal's Edge"

queue_job  2 \
  "Torn magazine paper, botanical press prints, and smudged graphite construct a woman's portrait from the inside out. Rose stems form the spine of her nose; stamens cluster where eyelashes should be. Her skin is assembled from overlapping scraps — old newspaper, amber tissue, gold leaf fragments — each layer slightly misaligned, suggesting a self still being assembled. Wildflowers in cadmium orange and chrome yellow burst outward from her temples like externalised thought. Hard pencil lines anchor the collage, giving structure to the chaos. The background is raw cream paper, unstretched, imperfect. Mood: restless, searching, layered. The face is legible but not comfortable — something is being built, something is being let go, simultaneously." \
  "Claude Sonnet 4.6" "Collage of the Unnamed"

queue_job  3 \
  "A close portrait rendered in encaustic wax and pressed botanicals — the face emerging from layers of translucent beeswax tinted in ochre, ash rose, and pale sage. Dried lavender and chamomile are embedded directly into the wax surface, their stems tracing the contours of jaw and brow. The eyes are painted in raw umber with a single streak of cobalt, gazing slightly downward. Wax is scraped back in areas to reveal ghost-layers beneath — earlier versions of the face, half-erased decisions. The entire surface holds a warm amber glow, like candlelight frozen mid-flicker. Flowers and face share the same material reality, neither decorating the other. Mood: ancient, meditative, slow. Technique suggests ritual — something preserved, something honoured." \
  "Claude Sonnet 4.6" "Wax and Wildflower"

queue_job  4 \
  "A geometric abstraction of a female face, fragmented into angular planes like shattered stained glass or a Cubist fever dream. Each faceted plane holds a different texture: one filled with dense watercolor cherry blossoms on wet paper, another with dry pencil cross-hatching, another with flat ink in viridian, another with scraped impasto. The eye is a single perfect circle — untouched, watching from within the fragmentation. Flowers don't decorate this face; they occupy it, growing through the cracks between planes, pushing outward. The palette moves from cold violet through warm rust to sharp acid green. Mood: fractured and fierce, beautiful under pressure. Style: analytical Cubism colliding with botanical illustration." \
  "Claude Sonnet 4.6" "Fracture Garden"

queue_job  5 \
  "A minimalist graphite portrait in which the face is defined almost entirely by what surrounds it — dense clusters of hand-drawn ink flowers, obsessively detailed, fill every centimetre of the background while the face itself remains white paper, bare and luminous. The flowers press close — cosmos, anemone, clematis, all interlocking — but stop precisely at the silhouette's edge, as if held back by an invisible field. Within the face: just two soft graphite eyes and the faint suggestion of a mouth. The contrast is stark and deliberate. Mood: vulnerable, exposed, quietly powerful. The face holds its emptiness like a statement. Technique: ultra-fine ink linework for flora, minimal graphite for the figure. Printed on uncoated paper. Feels like silence in a crowded room." \
  "Claude Sonnet 4.6" "Negative Space, Full Bloom"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "An evocative collage and mixed media portrait where a fragmented, pencil-sketched face of a woman emerges from a textured background of distressed vintage paper. The left side of her face dissolves into an explosion of deep crimson peonies and withered black roses, painted with thick, tactile oil ink splatters. High-contrast charcoal shading defines her melancholic expression, juxtaposed against vibrant, chaotic drips of watercolor that bleed into the canvas. Gold leaf accents trace the cracks in the paper, catching the light. The composition balances deep emotional weight with breathtaking aesthetic beauty, symbolizing the delicate line between growth and decay." \
  "Gemini 3.5 Flash" "Echoes of Silence"

queue_job  7 \
  "A striking, thought-provoking oil painting of a surreal, abstract face entirely composed of shifting floral arrangements. The silhouette of a profile is defined by sharp, palette-knife strokes of deep indigo and obsidian ink. From the open crown of the head, a surreal garden of hyper-realistic scarlet poppies and stark white lilies erupts violently upward, casting long, dramatic shadows. One piercing, beautifully detailed eye peers through a veil of cascading petals. The background is a minimalist, textured concrete grey, creating a powerful contrast that forces a visceral emotional reaction to themes of mental rebirth and raw, untamed beauty." \
  "Gemini 3.5 Flash" "Crimson Metamorphosis"

queue_job  8 \
  "An ethereal watercolor and fine-line ink illustration depicting the fluid fusion of human emotion and botanical life. A minimalist, continuous-line drawing of a serene face is overlaid with translucent, bleeding washes of cerulean blue, violet, and soft amber. Wild lavender, delicate cherry blossoms, and tangled vines grow seamlessly from the cheekbones and eyelids, blurring the boundary between flesh and flora. Splatters of ink and water droplets create a dreamy, atmospheric depth, evoking a profound sense of nostalgia and quiet introspection. The delicate textures and soft color transitions make the abstract form mesmerizing and deeply comforting to look at." \
  "Gemini 3.5 Flash" "Ephemeral Whispers"

queue_job  9 \
  "A bold, modern-abstract acrylic and digital-hybrid portrait that captures psychological complexity. A stylized face is fractured into geometric planes, rendered in contrasting shades of muted graphite and explosive, neon-tinted wildflowers. Sunflowers, distorted blue hydrangeas, and thorny stems burst out from the cracks in the skin, wrapping around the features like a living tapestry. The brushwork is aggressive yet precise, with heavy impasto textures that invite the viewer to touch. The intense gaze of the subject combined with the chaotic botanical elements creates a powerful, arresting visual narrative about internal struggle and resilience." \
  "Gemini 3.5 Flash" "Shattered Harmony"

queue_job 10 \
  "A hauntingly beautiful film noir-inspired charcoal sketch integrated with rich, saturated gouache accents. The deep, heavy blacks and stark white highlights form a dramatic chiaroscuro portrait of a face looking upward in contemplation. Breaking the monochromatic solemnity, a brilliant cascade of fiery orange marigolds and midnight-blue orchids erupts from the neck and jawline, their vivid colors bleeding into the dark shadows. The contrast between the cold, stark realism of the charcoal face and the warm, surreal explosion of the abstract flowers evokes a strong poignant feeling of hope emerging from absolute darkness." \
  "Gemini 3.5 Flash" "Nocturne in Bloom"

# --- ChatGPT ---
queue_job 11 \
  "An evocative abstract composition where a human face emerges and dissolves within a storm of blooming flowers, as if memory itself is made of petals. The facial features are partially obscured, fragmented into layered brushstrokes and translucent textures, blending seamlessly with roses, lilies, and imaginary flora. Use a mixed media approach — soft watercolor washes merging into bold ink lines and delicate pencil shading. Colors transition from muted pastels to deep, emotional tones like crimson, indigo, and gold accents. The background feels atmospheric and undefined, like fog or faded paper. Emphasize emotional ambiguity — melancholy, nostalgia, and quiet introspection — through asymmetry, negative space, and subtle distortions in the face." \
  "ChatGPT" "Petals of Silence"

queue_job 12 \
  "Create a striking abstract portrait where the face is constructed entirely from floral structures, petals forming eyes, stems suggesting contours, and blossoms replacing hair. The composition should feel both organic and surreal, as if nature is reclaiming human identity. Use oil painting textures with thick, expressive strokes combined with delicate collage elements — pressed flowers, torn paper, and fabric fragments. Color palette should contrast warm floral tones with cool shadows, enhancing depth and emotional tension. The expression of the face should be ambiguous, neither fully visible nor entirely hidden. Incorporate flowing movement, as if the flowers are growing and shifting in real time, symbolizing transformation and inner complexity." \
  "ChatGPT" "Blooming Identity"

queue_job 13 \
  "Design an abstract artwork where a face appears shattered into geometric fragments, each piece filled with intricate floral patterns. The composition should feel like a stained-glass window or broken mirror reflecting different emotional states. Use a combination of sharp digital collage, ink outlines, and watercolor textures. Each fragment carries its own color mood — some vibrant and alive, others faded and decaying. The flowers range from detailed botanical realism to abstract shapes, blending structure with chaos. The background should be minimal but textured, allowing the fragmented face to dominate. Convey a sense of psychological depth, inner conflict, and layered identity through contrast, fragmentation, and symbolic floral elements." \
  "ChatGPT" "Fractured Garden Mind"

queue_job 14 \
  "An ethereal abstract piece where a soft, almost ghostly face emerges from a field of flowing, dreamlike flowers. The lines of the face are barely defined, dissolving into swirling botanical forms that resemble smoke or water currents. Use a delicate combination of ink wash, watercolor gradients, and fine pencil detailing. The color palette leans toward soft neutrals — ivory, blush pink, sage green — with occasional deeper accents for emotional resonance. The flowers should feel weightless, almost floating, blending seamlessly into the contours of the face. Focus on creating a calming yet slightly haunting atmosphere, evoking introspection, fragility, and the quiet connection between human emotion and nature." \
  "ChatGPT" "Whispering Flora"

queue_job 15 \
  "Craft a bold and dynamic abstract artwork where a face and flowers collide in an explosion of color and motion. The face is expressive but partially distorted, with features stretched and intertwined with vibrant floral forms. Use acrylic or digital painting techniques with energetic brushstrokes, splashes, and layered textures. Colors should be intense — electric blues, fiery reds, neon pinks — contrasted with darker undertones to ground the composition. Flowers appear almost alive, pulsing and radiating energy from the face, symbolizing emotion as a living force. The background should enhance the sense of movement, with swirling patterns or abstract gradients. The overall feeling should be powerful, passionate, and slightly chaotic, capturing raw emotional intensity." \
  "ChatGPT" "Floral Pulse"

# --- Grok ---
queue_job 16 \
  "A captivating abstract artistic portrait where a serene female face emerges from swirling layers of delicate flowers, rendered in soft watercolor and ink washes. The face is partially veiled by translucent petals of roses, lilies, and cherry blossoms that dissolve into ethereal mists, evoking melancholy beauty and rebirth. Gentle tears of dew cascade from closed eyes while vibrant floral elements intertwine with subtle geometric fractures across the composition. Dreamlike color palette of deep indigos, blush pinks, and golden ochres creates emotional depth and mystery. Thought-provoking juxtaposition of fragility and resilience, highly detailed textures, intricate line work, masterful negative space, emotionally resonant and visually stunning abstract art." \
  "Grok" "Ethereal Bloom of Forgotten Dreams"

queue_job 17 \
  "Striking abstract mixed media artwork featuring a fragmented male face intertwined with explosive floral forms in oil and pencil technique. Shattered porcelain-like skin reveals inner glowing flowers blooming from within, symbolizing hidden emotions and inner growth. Bold brushstrokes meet delicate botanical details, with crimson poppies, white orchids, and twisting vines creating dynamic movement. Dramatic lighting with strong contrast between darkness and luminous floral highlights generates powerful emotional tension. Thought-provoking exploration of identity and transformation, rich textures, sophisticated color harmony in teal, burgundy, and cream tones, aesthetically powerful and mesmerizing." \
  "Grok" "Whispers of Petal and Soul"

queue_job 18 \
  "Mesmerizing abstract collage and watercolor fusion showing a mysterious feminine face emerging through layers of pressed dried flowers and torn paper textures. Eyes filled with cosmic galaxies peek through overlapping lotus and peony blooms, suggesting spiritual awakening and hidden depths. Subtle golden ink details accentuate emotional vulnerability and quiet strength. Delicate yet bold composition balances chaos and harmony, with flowing organic shapes contrasting sharp geometric floral patterns. Evocative color scheme of muted lavenders, warm corals, and deep emerald creates profound emotional resonance. Intricate, visually hypnotic abstract art that invites contemplation." \
  "Grok" "Veiled Garden of Echoes"

queue_job 19 \
  "Dramatic abstract oil painting depicting a passionate face consumed by fiery yet graceful flowers in a surreal dreamscape. Burning roses and flaming tulips merge with facial features, symbolizing intense emotions, love, and transformation through pain. Expressive brushwork with visible texture and impasto details creates raw emotional power. Rich palette of fiery reds, molten oranges, and cool ash grays produces breathtaking contrast and depth. Thought-provoking narrative of destruction and renewal, masterful composition with flowing energy, highly aesthetic and emotionally charged abstract portrait." \
  "Grok" "Flames of Silent Petals"

queue_job 20 \
  "Hauntingly beautiful abstract ink and acrylic artwork of an androgynous face gently dissolving into a garden of wilting and blooming flowers simultaneously. Elegant line work combined with soft color washes creates poetic tension between life and decay. Cherry blossoms, jasmine, and ivy weave through facial contours, exploring themes of time, memory, and impermanence. Sophisticated minimal yet detailed approach with negative space mastery. Serene yet emotionally stirring color story of soft pastels meeting deep charcoal tones. Captivating, thought-provoking, and visually exquisite abstract composition." \
  "Grok" "Symmetry of Fading Blossoms"

# --- Copilot ---
queue_job 21 \
  "An abstract composition where a human face emerges from a cascade of blooming flowers, their petals dissolving into brushstrokes of watercolor and ink. The contours of the face are fragmented, almost collaged, with delicate lines suggesting vulnerability and resilience. Flowers intertwine with facial features, replacing eyes with blossoms and lips with petals, creating a surreal yet emotionally charged fusion. The palette shifts between soft pastels and bold contrasts, evoking both serenity and intensity. This artwork should provoke reflection on identity, growth, and the fragile beauty of existence, leaving viewers captivated by its dreamlike harmony." \
  "Copilot" "Blossoming Visage"

queue_job 22 \
  "Imagine a face rendered in oil and pencil, fractured into geometric shards, each piece overlaid with vibrant floral motifs. Roses, lilies, and wildflowers seep into the cracks, symbolizing memory and renewal. The eyes are obscured by blossoms, suggesting hidden emotions, while the mouth dissolves into abstract strokes of color. The interplay of sharp lines and fluid petals creates tension between structure and chaos. This piece should feel haunting yet hopeful, inviting viewers to contemplate the relationship between human fragility and nature's resilience, leaving them with a lingering sense of poetic melancholy." \
  "Copilot" "Petals of Memory"

queue_job 23 \
  "A surreal watercolor portrait where a face dissolves into a garden of flowers, the boundaries between skin and petals blurred into flowing washes of color. The cheeks bloom into roses, while the forehead unfurls into delicate orchids. The absence of a mouth suggests silence, yet the flowers speak through their vivid hues. The composition balances softness with intensity, using layered textures to evoke both peace and longing. This artwork should feel meditative, encouraging viewers to reflect on the quiet power of transformation and the unspoken emotions that blossom within us." \
  "Copilot" "Silent Bloom"

queue_job 24 \
  "A collage-inspired abstract where torn paper textures form the outline of a face, interwoven with pressed flowers and ink splatters. The fragmented features suggest disconnection, while the flowers act as bridges, stitching together identity through nature's embrace. Bold contrasts of black ink and vibrant petals create a striking visual rhythm, simultaneously chaotic and harmonious. The piece should feel raw yet beautiful, provoking thoughts about the fractured nature of selfhood and the healing force of growth. It invites viewers to see beauty in imperfection and resilience in fragility." \
  "Copilot" "Fragmented Garden"

queue_job 25 \
  "An abstract oil painting where a face emerges from swirling layers of color, half-hidden beneath a storm of blossoms. The flowers are painted with exaggerated textures, almost sculptural, while the face remains ghostly, fading into the background. The eyes are luminous yet distant, framed by petals that seem to whisper secrets. The composition is both haunting and mesmerizing, evoking themes of memory, identity, and the passage of time. This artwork should stir emotions of nostalgia and wonder, leaving viewers entranced by its mysterious interplay of human presence and floral abundance." \
  "Copilot" "Echoes in Bloom"

# --- Mistral ---
queue_job 26 \
  "A delicate watercolor painting of a face merging seamlessly with blooming flowers, where petals form the contours of a serene, androgynous visage. Soft pastel hues of lavender, peach, and mint green bleed into one another, creating an ethereal, dreamlike quality. The background is a subtle gradient of misty whites and pale blues, evoking a sense of tranquility and introspection. The flowers — roses, lilies, and cherry blossoms — are semi-transparent, their edges blurring into the skin of the face, symbolizing the harmony between humanity and nature. Gold leaf accents highlight the tear-like dew on the petals, adding a touch of divine elegance. The composition is balanced, with a focal point at the eyes, which are closed in peaceful meditation, inviting the viewer to pause and reflect." \
  "Mistral" "Ethereal Fusion: Watercolor Dreams"

queue_job 27 \
  "A bold, mixed-media collage where a fragmented face is reconstructed using overlapping layers of pressed flowers, torn magazine cutouts, and hand-painted strokes. The face is split into geometric shards, each piece filled with vibrant floral patterns — sunflowers, orchids, and poppies — clashing and complementing the sharp angles of the facial structure. The color palette is rich and contrasting: deep crimsons, electric blues, and metallic golds create a dynamic tension. The background is a textured, grungy canvas, with splatters of black ink and scribbled poetry faintly visible beneath the layers. The overall effect is raw and provocative, challenging the viewer to find beauty in imperfection and unity in diversity." \
  "Mistral" "Fractured Identity: Collage of Chaos"

queue_job 28 \
  "A high-contrast ink drawing on aged paper, where the intricate lines of a face dissolve into a swirling garden of wildflowers. The face, half in shadow, half in light, is rendered with meticulous cross-hatching, while the flowers — daisies, irises, and thistles — emerge from the darkness like whispers of the subconscious. The composition plays with negative space, allowing the viewer's mind to fill in the gaps between the inked lines. Splashes of diluted ink create a sense of movement, as if the flowers are growing in real-time. The mood is introspective and mysterious, with a touch of melancholy, evoking the fleeting nature of life and memory." \
  "Mistral" "Ink and Soul: Monochrome Whispers"

queue_job 29 \
  "A thick, textured oil painting where a face is partially obscured by a cascade of oversized, wilting flowers — tulips, peonies, and hydrangeas — dripping with glossy, almost liquid paint. The color palette is moody and dramatic: deep burgundies, forest greens, and inky blacks dominate, with flecks of cadmium yellow and titanium white adding depth and luminosity. The brushstrokes are visible and expressive, conveying raw emotion — grief, longing, and resilience. The flowers seem to grow from the face itself, their stems intertwining with the strands of hair, symbolizing the inseparable bond between human emotion and the natural world. The lighting is dramatic, with a single source casting long shadows, enhancing the painting's emotional intensity." \
  "Mistral" "Oil and Emotion: The Bloom of Sorrow"

queue_job 30 \
  "A digital art piece where a cyberpunk-inspired face is intertwined with bioluminescent flowers, glowing in neon hues of electric purple, cyan, and hot pink. The face is androgynous, with sharp, angular features softened by the organic curves of the flowers — lotuses, jasmine, and digitalis — that seem to pulse with their own inner light. The background is a dark, starry void, with faint grid lines and floating geometric shapes, creating a sense of otherworldly depth. The flowers emit a soft glow, illuminating the face in a way that feels both futuristic and ancient. The composition is symmetrical yet chaotic, inviting the viewer to lose themselves in a surreal, technicolor dreamscape." \
  "Mistral" "Digital Surrealism: Neon Reverie"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A striking abstract portrait where a fragmented human face emerges from a swirling cascade of watercolor blossoms. Soft washes of indigo and rose bleed into delicate charcoal sketch lines, forming half-visible eyes and lips that seem to dissolve into the surrounding floral chaos. The composition balances negative space with dense clusters of peony and lily petals, creating a dreamlike tension between presence and absence. Subtle gold leaf accents catch the light, adding warmth to the cool undertones. The artwork evokes a quiet melancholy, suggesting memories that bloom and fade with time. Textures vary from smooth, translucent washes to rough, expressive brushstrokes, guiding the viewer's eye across the layered surface. Every element merges seamlessly, inviting contemplation on identity, beauty, and the fleeting nature of human connection." \
  "Qwen 3.6 Plus" "Whispering Petals, Silent Gaze"

queue_job 32 \
  "An evocative abstract composition blending a stylized human visage with explosive botanical forms rendered in rich sumi ink and heavy acrylic textures. Jagged black strokes carve out the silhouette of a face, while vibrant crimson and saffron flower petals erupt from the cheekbones like emotional fractures. The background features layered washes of pale ivory, allowing the central figure to float in a contemplative void. Delicate rice paper fragments are embedded into the surface, creating a tactile collage effect that enhances the organic rhythm. The interplay of sharp, angular lines and soft, bleeding floral washes generates a profound sense of inner turmoil and rebirth. Viewers are drawn into the psychological depth of the piece, reflecting on resilience, transformation, and the quiet beauty of emotional release." \
  "Qwen 3.6 Plus" "Ink and Ivory Reverie"

queue_job 33 \
  "A mesmerizing abstract portrait where geometric facets of a human face dissolve into a vibrant garden of oil-ink florals. The composition uses overlapping translucent layers of cyan, magenta, and amber to construct cheekbones and a jawline that gradually fragment into swirling marigold and orchid forms. Dynamic brushwork creates a sense of motion, as if the subject is exhaling a breath of color. Deep charcoal outlines anchor the floating elements, preventing the piece from becoming visually chaotic. The lighting feels atmospheric, casting subtle shadows that give depth to the flat planes of pigment. This artwork stirs a quiet wonder, prompting reflection on how inner landscapes shape our outward expressions. The harmonious balance between structured portraiture and wild botanical abstraction invites prolonged, meditative observation." \
  "Qwen 3.6 Plus" "Chromatic Bloom of the Mind"

queue_job 34 \
  "A compelling abstract artwork where a deconstructed human face interweaves with delicate pencil-drawn roses and wild jasmine vines. Graphite shading creates soft gradients across the forehead and nose, while fine crosshatching dissolves into intricate floral linework that wraps around the empty eye sockets. The monochromatic base is interrupted by sudden splashes of muted teal and dusty rose pigment, bleeding outward like watercolor on rough canvas. Negative space plays a crucial role, leaving portions of the face deliberately unfinished to emphasize vulnerability. The composition feels both intimate and distant, evoking a gentle sorrow paired with quiet hope. Viewers are encouraged to trace the overlapping lines, discovering how human fragility and natural resilience mirror one another in this thoughtfully layered visual poem." \
  "Qwen 3.6 Plus" "Fractured Petals, Hidden Eyes"

queue_job 35 \
  "An emotionally charged abstract portrait where a sculpted clay-like face merges with heavy impasto blooms of poppy and thorny vine. The medium blends mixed-media collage techniques with expressive oil painting, creating a tactile surface of cracked pigment and embedded dried flower petals. Warm terracotta and deep burgundy tones dominate the facial structure, while sudden bursts of luminous yellow and silver leaf draw attention to the mouth and brow. The abstraction deliberately obscures full features, leaving only suggestive contours that emerge from the floral mass. This visual tension provokes introspection about aging, passion, and the cyclical nature of growth and decay. The piece resonates with raw, unpolished beauty, inviting the observer to find comfort in imperfection and the enduring power of natural forms." \
  "Qwen 3.6 Plus" "Echoes in Crimson Clay"

# --- GLM 5.1 ---
queue_job 36 \
  "A breathtaking abstract watercolor and ink portrayal of a melancholic feminine face dissolving into a storm of vibrant bleeding flowers. The eyes are expressive and realistic, gazing outward, while the cheeks and jaw fragment into loose, flowing washes of cerulean blue and magenta. Swirling orchids and bleeding hearts bloom from the void where her mind should be, their petals morphing into erratic, jagged black ink splatters. The background is a textured, damp cold-pressed paper, allowing the pigments to bloom organically. A deeply emotional piece exploring memory and loss, where the boundary between human vulnerability and wild nature vanishes into a mesmerizing, tear-stained kaleidoscope of watery colors and haunting beauty." \
  "GLM 5.1" "Dissolving Echoes"

queue_job 37 \
  "A striking mixed-media collage of an abstract face intertwined with explosive floral elements. The silhouette of a face is constructed from torn pages of vintage botanical encyclopedias, layered with translucent tracing paper and delicate gold leaf. From the parted lips, a chaotic eruption of pressed crimson roses and jagged thistles bursts forward, created from thick, textured handmade paper and vibrant acrylic paint slashes. Deep-set eyes are cut from midnight blue velvet, creating a startling contrast against the muted ecru and olive tones of the paper skin. This thought-provoking artwork captures the silent scream of repressed thoughts blooming into a chaotic, beautiful reality, exuding a raw, tactile energy that demands contemplation." \
  "GLM 5.1" "Botanical Fragments"

queue_job 38 \
  "An intense abstract oil impasto painting featuring a face consumed by a vibrant tornado of flowers. Thick, aggressive palette knife strokes sculpt a distorted, anguished face in muted grays and fleshy ochres, creating deep, shadowed hollows for the eyes. Bursting from the crown and cascading down, a riotous explosion of sunflowers and crimson poppies dominates the canvas, painted in thick, sculptural swirls of cadmium yellow, vermilion, and emerald green. The flowers act as both a crown and a shroud, overwhelming the fragile humanity beneath. The raw, textured paint catches dramatic side-lighting, creating an aesthetically powerful and emotionally turbulent visual that speaks to the overwhelming force of passion and the fleeting nature of identity." \
  "GLM 5.1" "Resilient Bloom"

queue_job 39 \
  "A hauntingly poetic abstract charcoal and graphite sketch of an ethereal face giving birth to a delicate floral ecosystem. The face is rendered in meticulous, smudged chiaroscuro, with hollowed cheekbones and closed eyes that evoke a sense of peaceful surrender. From the tear ducts and parted lips, intricate, spiraling vines of morning glories and weeping willows sprout, drawn with razor-sharp precision that contrasts the soft, atmospheric blending of the skin. Faint eraser marks and ghostly white highlights create a luminescent, dreamlike quality against the stark charcoal background. This deeply evocative drawing blurs the line between decay and growth, evoking a profound sense of quiet sorrow and the bittersweet beauty of letting go." \
  "GLM 5.1" "Whispers of Ash"

queue_job 40 \
  "A mesmerizing abstract ink and acrylic piece depicting a face as a living vessel for a glowing floral nervous system. The face is outlined in swift, expressive, and minimal sumi-e brushstrokes, leaving the features purposely ambiguous and fluid. Inside the silhouette, an intricate network of glowing crimson and magenta lotus flowers and neural pathways pulses with life, painted with luminous acrylics. The flowers seem to ignite from the brain, trailing down the neck like glowing veins. Splatters of black ink radiate outward, suggesting a sudden explosion of thought or epiphany. The stark contrast between the monochromatic, gestural lines and the vivid, internal floral illumination creates a thought-provoking masterpiece about the genesis of consciousness and the blooming of an inner world." \
  "GLM 5.1" "Crimson Synapses"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A haunting abstract portrait where a woman's face dissolves into cascading peonies and bleeding heart vines. Rendered in thick oil ink strokes and translucent watercolor washes, her closed eyes become the center of a floral eclipse. Vermillion and ultramarine pigments bleed across the canvas, creating organic textures that suggest both growth and decay. Layers of impasto petals emerge from her cheekbones, while delicate graphite lines trace the architecture of her skull beneath translucent skin. The composition balances explosive emotional intensity with meditative negative space, inviting the viewer to contemplate the fragile boundary between human identity and botanical metamorphosis. Golden ochre highlights catch the light like pollen suspended in sunbeams, adding ethereal warmth to the melancholic atmosphere." \
  "Kimi K2.6 Thinking" "Veins of Petal and Memory"

queue_job 42 \
  "A fragmented mixed-media collage presenting a masculine face deconstructed into pressed wildflowers, torn rice paper, and oxidized copper leaf. His profile fractures horizontally like sedimentary rock, each layer revealing different botanical specimens — dried lavender, crushed poppies, and fern spores embedded in encaustic wax. The aesthetic merges Victorian mourning portraiture with contemporary abstract expressionism, creating a thought-provoking meditation on masculinity and vulnerability. Charcoal scribbles and gold thread stitches bind the fragments together, suggesting both wound and repair. Deep emerald and burnt sienna tones dominate the palette, while unexpected flashes of neon pink interrupt the organic harmony, injecting raw emotional tension into the contemplative silence of the composition." \
  "Kimi K2.6 Thinking" "The Garden Reclaims Her Silence"

queue_job 43 \
  "An intricate graphite and charcoal drawing where a serene face emerges from a tangle of chrysanthemum roots and lily stamens. The monochrome palette emphasizes dramatic chiaroscuro, with deep carbon blacks swallowing the background while silver-gray highlights define every vein and petal edge. The subject's lips are slightly parted, as if exhaling seeds into the void, creating an unsettling yet beautiful tension between life and surrender. Delicate cross-hatching builds texture across the forehead, gradually transforming into the fibrous patterns of root systems. This pencil work explores the intimate connection between human consciousness and subterranean growth, evoking profound contemplation about what nourishes us beneath the surface of our constructed identities." \
  "Kimi K2.6 Thinking" "Roots Beneath the Skin"

queue_job 44 \
  "A dreamlike watercolor abstraction capturing a youthful face partially submerged in a swirling vortex of cherry blossoms and lotus flowers. Wet-on-wet techniques create bleeding edges where skin becomes petals and tears become dewdrops, blurring the line between portraiture and pure emotion. Indigo and magenta washes pool in the negative spaces, while sharp ink splatters suggest sudden moments of clarity within the dreamy haze. The eyes gaze upward beyond the frame, conveying longing and quiet resilience. This piece balances delicate transparency with bold gestural marks, creating an aesthetically pleasing tension that invites prolonged viewing. The overall effect is both melancholic and hopeful — a visual poem about beauty emerging from internal chaos." \
  "Kimi K2.6 Thinking" "Bloom Where the Mind Wanders"

queue_job 45 \
  "A bold abstract oil painting executed with heavy palette knife work, depicting an elderly face interwoven with dried protea and thistle blooms. Thick impasto strokes of titanium white, raw umber, and cadmium yellow build a sculptural surface where wrinkles become flower stems and age spots transform into seed pods. The composition employs dramatic diagonal movement, pulling the viewer's eye from the weathered forehead down through a cascade of spiky botanical forms. Subtle glazes of viridian and alizarin crimson create depth within the heavy texture, evoking wisdom, resilience, and the inevitable cycle of return to earth. This emotionally charged work celebrates the profound beauty found in impermanence and natural decay." \
  "Kimi K2.6 Thinking" "Flora of the Forgotten Self"

# --- Deepseek ---
queue_job 46 \
  "A semi-abstract portrait where a woman's face emerges from shattered ceramic planes, each shard revealing a different flower petal — rose, orchid, marigold. Her closed eye is a spiral of ink, weeping tiny daisies. The composition splits diagonally: left side muted charcoal pencil, right side explosive watercolor blooms in coral and indigo. Fine liner traces neural pathways across her cheek, transforming into creeping vine thorns. The lips are two overlapping poppy heads, slightly parted as if exhaling pollen. Soft bokeh suggests morning dew on the entire scene, blending melancholy with rebirth. The background remains raw paper texture with faint cyanotype prints of fern leaves. Collage elements include vintage sheet music cut into the shape of a jawline. Overall mood: introspective yet defiant." \
  "Deepseek" "Fragmented Blossom Gaze"

queue_job 47 \
  "Loose oil pastel and gouache fusion: a face dissolves into a swarm of abstract flower heads. The forehead is a pale lily cup, the nose bridge a curved stem, and one eye is a sunflower center while the other spirals into a forget-me-not vortex. Thick, expressive strokes in magenta, ochre, and teal overlap with translucent layers of tissue paper. Swirling pollen particles form a translucent veil over the mouth, which is slightly ajar, revealing a tongue shaped like a poppy petal. The chin splits into two jasmine vines curling outward. Use sgraffito technique to scratch fine lines of hair that transform into bluebell tendrils. Emotional tone: serene mystery, as if the subject is breathing spring storms. The sides fade into raw linen texture with subtle coffee stains." \
  "Deepseek" "Veiled in Pollen Dreams"

queue_job 48 \
  "Digital brushwork mimicking torn paper collage: a face cracked vertically, the left half built from crimson hibiscus petals, the right half from charcoal sketches of wilted tulips. The eyes are two different species — a violet eye holds a tiny daisy pupil; the other is a hollow aster center with light bleeding through. Wild strokes of ink wash create hair that morphs into a monsoon of peony leaves and bramble. A single tear rolling down the cheek is actually a crystal-clear water drop containing a miniature lotus bloom. The background is a patchwork of crumpled craft paper and cyanotype patterns of ferns. Metallic gold leaf accents trace the jawline and collarbone. Emotion: bittersweet resilience, with a hint of surreal fragility. The entire piece feels both violent and tender." \
  "Deepseek" "Floral Fracture Portrait"

queue_job 49 \
  "A neo-abstract composition where a human skull is reassembled from pressed flowers and twisted roots. The eye sockets are deep purple iris blooms; the nasal cavity is a rolled rose petal tunnel. Over this skeletal base, translucent skin layers of watercolor wash reveal a serene face smiling faintly — two faces in one: life and decay. From the crown erupts an explosion of loose, gestural brushwork forming snapdragons, larkspur, and wild grasses. The cheekbones are shaded with crushed charcoal mixed with dried lavender. Small collage elements: handwritten letters on the forehead, map fragments along the jaw. The mouth sewn shut with a thin, thorny vine that ends in a single blooming jasmine. Lighting suggests twilight, with deep teal shadows and warm orange highlights. Emotional resonance: acceptance of mortality, beauty in transience." \
  "Deepseek" "Whispering Petal Skull"

queue_job 50 \
  "Acrylic pour and fine liner hybrid: a face profile formed entirely by flowing ribbons of color that separate into distinct flower species. The forehead is a cascade of wisteria in violet ombré; the nose contour is a yellow calla lily; the lips are two overlapping camellia petals in fuchsia. The eye is a spiral galaxy of tiny daisy dots, while the eyelashes are spiderwort stamens. Thick, glossy paint ridges create texture like embossed velvet. Behind the face, abstract splatters represent a garden in wind — dandelion seeds, cherry blossom fragments, and scattered marigold petals. Minimal linework defines a second, ghost face kissing the main one from the negative space. Medium: mixed media with alcohol ink and white gel pen highlights. Mood: euphoric disorientation, as if colors and scents merged into a single emotional chord. The composition radiates outward like a blooming firework." \
  "Deepseek" "Chromatic Echoes of Bloom"

echo "✅ All 50 jobs queued in scheduler"
