#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Urban expressionist oil painting, heavy impasto
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+28+-+Urban+oil+painting
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "Expressionist oil painting, heavy impasto technique, rain-slicked urban alley at night, neon signs reflecting fractured crimson and gold light across wet cobblestones, thick gestural brushstrokes defining crumbling brick walls, a solitary figure hunched beneath a glowing doorway, steam rising from iron grates, deep cobalt shadows slashed with violent orange, distorted perspective amplifying isolation, paint applied with palette knife, raw emotional tension, city decay atmosphere" \
  "Claude Sonnet 4.6" "Neon Alley After Rain"

queue_job  2 \
  "Expressionist oil painting, heavy impasto technique, underground subway platform, dense crowd of commuters rendered in bold distorted forms, fluorescent light flickering yellow-green across fragmented faces, thick impasto strokes capturing motion blur, claustrophobic tunneling perspective, charcoal-black shadows against sickly institutional tile, figures merging into anonymous mass of gray and ochre, urgent gestural marks suggesting noise and speed, urban alienation mood, industrial steel columns receding into darkness" \
  "Claude Sonnet 4.6" "Subway Station Rush Hour"

queue_job  3 \
  "Expressionist oil painting, heavy impasto technique, urban construction site bathed in dying amber light, skeletal steel framework against bruised violet-purple sky, thick palette knife strokes rendering concrete rubble and machinery, workers silhouetted as elongated dark forms, dramatic diagonal scaffolding lines creating tension, raw umber earth gouged open below, dust clouds built from layered impasto texture, industrial power and human fragility contrasted, burning orange horizon behind city skyline" \
  "Claude Sonnet 4.6" "Construction Site at Dusk"

queue_job  4 \
  "Expressionist oil painting, heavy impasto technique, street-corner urban market before approaching thunderstorm, vendor stalls draped in frantic color bursts of red and yellow, thickly textured awnings whipping in rising wind, dark slate-green storm clouds pressing down from above, distorted merchant faces frozen in urgency, cobblestone street churned with shadow and reflected electric signage, agitated short violent brushstrokes conveying atmospheric chaos, paint surface heavily built up, dense oppressive urban energy" \
  "Claude Sonnet 4.6" "Corner Market Under Storm"

queue_job  5 \
  "Expressionist oil painting, heavy impasto technique, New York-style rooftop panorama at early sunrise, weathered wooden water towers clustered against blazing cadmium-orange sky, thick gestural impasto strokes defining corrugated metal and rotting timber planks, distant skyscrapers dissolving into haze of pale gold and rose, rusted iron tank hoops rendered with palette knife, pigeons as dark dashes against luminous sky, urban industrial poetry, solitude above the waking city, rich textured paint surface" \
  "Claude Sonnet 4.6" "Rooftop Water Towers Sunrise"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A heavy impasto expressionist oil painting of a lonely figure walking down a rainy neon-lit city street at night. Thick, palette-knife strokes of crimson, Prussian blue, and electric yellow create deep texture. Distant skyscrapers blur into distorted, towering shapes against a turbulent sky. Glowing streetlamps reflect heavily in fragmented, muddy puddles on the asphalt. The mood is melancholic and chaotic, capturing the raw emotional energy of modern urban isolation." \
  "Gemini 3.5 Flash" "Urban Solitude"

queue_job  7 \
  "An expressionist oil painting capturing the frantic energy of a crowded subway station, executed with thick impasto technique. Violent strokes of ochre, charcoal grey, and stark white depict blurred human figures rushing past a stationary train. The textures are heavily raised, with layers of paint creating a sense of physical motion and claustrophobia. Harsh overhead fluorescent lights cast dramatic, distorted shadows across the concrete platform, emphasizing a chaotic urban rhythm." \
  "Gemini 3.5 Flash" "Subway Rush"

queue_job  8 \
  "A dramatic expressionist oil painting of towering city skyscrapers flanking a narrow street, rendered in heavy impasto. Thick, visible palette-knife layers of slate grey, industrial rust, and sudden bursts of cadmium orange dominate the canvas. The buildings lean inward unnaturally, creating a tense, overwhelming perspective. The sky above is a thick, textured mass of dark, swirling clouds, reflecting the intense, suffocating grandeur of a dense metropolitan environment." \
  "Gemini 3.5 Flash" "Concrete Canyons"

queue_job  9 \
  "An expressionist oil painting of a narrow urban alleyway behind a nightlife district, featuring heavy impasto brushwork. Rich, deep layers of violet, emerald green, and amber paint are aggressively applied to the canvas. A glowing neon sign casts a harsh, vibrant glare onto brick walls and metal fire escapes, which are sculpted with thick paint. The entire scene vibrates with tactile texture, capturing the gritty, hidden nocturnal soul of the city." \
  "Gemini 3.5 Flash" "Alleyway Jazz"

queue_job 10 \
  "A powerful expressionist oil painting depicting a massive suspension bridge cutting through city smog, painted with thick impasto layers. Billowing white steam rises from a street grate in the foreground, rendered with heavy, sculpted palette-knife textures. The color palette is dominated by cold steel blues, deep blacks, and contrasting flashes of brake-light red. The heavy buildup of paint emphasizes the raw, industrial weight and weathered texture of the urban landscape." \
  "Gemini 3.5 Flash" "Bridges and Steaming Grates"

# --- ChatGPT ---
queue_job 11 \
  "A dense urban street at night soaked in rain, neon signs bleeding crimson and electric blue into slick asphalt, figures distorted into elongated silhouettes by motion and reflection. Heavy impasto brushstrokes carve thick ridges of paint, emphasizing chaotic light and shadow. Buildings lean inward with emotional weight, windows glowing like restless eyes. The sky churns in bruised purples and greens, capturing tension and movement, raw expressionist energy, tactile oil texture, aggressive palette knife work throughout composition." \
  "ChatGPT" "Neon Rain on Cracked Asphalt"

queue_job 12 \
  "An overcrowded city intersection at sunset, cars melting into streaks of orange, red, and toxic yellow, their forms nearly abstract under thick, violent impasto strokes. Pedestrians blur into ghostlike masses, faces indistinct yet emotionally charged. Skyscrapers loom like jagged cliffs, reflecting fractured light. The sky burns in exaggerated hues, swirling with intensity. Oil paint piled heavily, sculptural texture dominates, each stroke conveying urgency, noise, heat, and suffocating urban momentum in an expressionist vision of chaos." \
  "ChatGPT" "Rush Hour Inferno"

queue_job 13 \
  "Towering brutalist buildings rise against a pale, sickly dawn, their rigid forms warped by expressive distortion. Thick layers of oil paint exaggerate shadows and surfaces, creating a tactile sense of weight and decay. Streets below lie empty, brushed in cold greys and muted blues, with occasional violent streaks of orange light. The sky churns softly but uneasily, hinting at unrest. Heavy impasto technique emphasizes raw materiality, urban isolation, and emotional heaviness within the silent cityscape." \
  "ChatGPT" "Concrete Giants at Dawn"

queue_job 14 \
  "An underground subway platform throbbing with motion, figures blending into each other in thick, smeared strokes of oil paint. Fluorescent lights flicker above, rendered in harsh yellows and greens, clashing against deep shadows. The train appears as a distorted metallic beast, emerging with force and noise. Walls drip with layered textures, posters dissolving into abstraction. Heavy impasto creates depth and rhythm, every stroke vibrating with movement, anxiety, and the relentless pulse of urban life beneath the surface." \
  "ChatGPT" "Subway Pulse"

queue_job 15 \
  "A lone figure stands atop a city rooftop, overlooking a sprawling urban expanse rendered in turbulent, exaggerated forms. Buildings twist and bend under heavy impasto strokes, painted in deep blues, violent reds, and glowing yellows. The sky churns with emotional intensity, thick paint creating swirling motion. Below, the city pulses chaotically, yet the figure remains still, almost carved from paint. Texture dominates, palette knife marks visible, capturing isolation and introspection amid overwhelming metropolitan energy." \
  "ChatGPT" "Rooftop Solitude Over Chaos"

# --- Grok 4.3 ---
queue_job 16 \
  "Expressionist oil painting of a chaotic nocturnal metropolis, distorted towering skyscrapers leaning under a swirling stormy sky, heavy impasto brushstrokes in vivid electric blues, fiery reds and deep umbers, blurred frantic figures rushing through rain-slicked streets with glowing neon reflections, raw emotional energy, thick textured paint layers capturing urban alienation and vibrant intensity, dramatic angular perspective." \
  "Grok 4.3" "Neon Shadows Over Crowded Streets"

queue_job 17 \
  "Expressionist oil painting of decaying urban factory district at first light, warped rusted smokestacks and crumbling brick walls bathed in blood-orange sunrise, heavy impasto with bold aggressive strokes in ochres, viridian and crimson, ghostly silhouettes of workers amid fog, thick palpable paint texture conveying melancholy and resilience of the forgotten city edges." \
  "Grok 4.3" "Forgotten Industrial Ruins at Dawn"

queue_job 18 \
  "Expressionist oil painting of a packed underground subway station, distorted anxious faces and elongated figures pressed together under harsh flickering lights, heavy impasto in acidic yellows, moody purples and steel grays, swirling motion blur and emotional tension, thick layered brushwork capturing the claustrophobic pulse and raw humanity of daily urban commute." \
  "Grok 4.3" "Crowded Subway Platform Frenzy"

queue_job 19 \
  "Expressionist oil painting of a lone figure on a rain-drenched rooftop overlooking endless glowing city grid, dramatically tilted skyscrapers melting into turbulent purple storm clouds, heavy impasto texture with vibrant cobalt, emerald and fiery highlights, thick expressive strokes evoking isolation, longing and the overwhelming beauty of the sleepless urban night." \
  "Grok 4.3" "Rainy Rooftop Cityscape Overlook"

queue_job 20 \
  "Expressionist oil painting of vibrant chaotic street market square at dusk, twisted vendor stalls and swirling crowds under strings of lanterns, heavy impasto in warm golds, deep crimsons and shadowy indigos, distorted energetic forms and bold angular composition, thick tactile paint layers radiating the noisy colorful life force and sensory overload of the living city." \
  "Grok 4.3" "Bustling Market Square Chaos"

# --- Copilot ---
queue_job 21 \
  "An expressionist oil painting of a bustling city skyline at night, rendered with heavy impasto strokes that exaggerate glowing neon lights and distorted architectural forms. The brushwork should feel chaotic yet vibrant, with thick textures capturing the pulse of urban energy. Shadows and highlights clash dramatically, creating a surreal atmosphere where the city seems alive, breathing with color and movement. The mood is intense, evoking both wonder and unease in the urban sprawl." \
  "Copilot" "Neon Skyline Pulse"

queue_job 22 \
  "A dynamic urban crosswalk scene painted in bold impasto, where figures blur into abstract shapes of motion and emotion. Thick oil strokes emphasize the clash of umbrellas, coats, and hurried footsteps, while streetlights smear into glowing halos. The composition should feel overwhelming yet captivating, capturing the raw rhythm of city life. Expressionist distortion heightens the tension, making the ordinary act of crossing the street a dramatic spectacle of human energy." \
  "Copilot" "Crowded Crosswalk Chaos"

queue_job 23 \
  "An urban alley dominated by a massive graffiti mural, painted in heavy impasto strokes that exaggerate color and texture. The wall becomes a living canvas, blending abstract human figures with surreal symbols. Thick oil layers create depth, while shadows of passing pedestrians dissolve into expressive smears. The mood is rebellious yet contemplative, capturing the raw artistry of the streets. The painting should feel alive, chaotic, and deeply emotional, embodying urban creativity." \
  "Copilot" "Graffiti Wall Reverie"

queue_job 24 \
  "An industrial urban bridge painted with thick impasto strokes, looming over a hazy cityscape filled with smoke and distorted lights. The brushwork should exaggerate steel beams, cables, and shadows, creating a surreal tension between structure and chaos. Expressionist oil textures capture the grit of urban life, while glowing highlights suggest resilience amid decay. The mood is heavy yet strangely poetic, transforming a utilitarian structure into a dramatic symbol of endurance." \
  "Copilot" "Bridge Over Smoke"

queue_job 25 \
  "A crowded urban marketplace rendered in bold impasto, where figures blur into expressive smears of color and texture. Stalls overflow with exaggerated shapes of fruits, fabrics, and neon signs, while shadows stretch across the scene in distorted forms. The brushwork should feel raw and chaotic, emphasizing human presence through abstract gestures. The mood is vibrant yet unsettling, capturing the intensity of urban commerce in a surreal, expressionist oil painting style." \
  "Copilot" "Market of Shadows"

# --- Mistral Think ---
queue_job 26 \
  "Vibrant urban street market at twilight, neon signs flickering above crowded stalls, vendors shouting over colorful produce spilling from wooden tables. Shadowy alleys stretch into distance, warm golden light mixing with cool blues from dusk sky. Expressionist oil painting, heavy impasto technique, thick textured brushstrokes, bold vibrant colors, emotional intensity, raw urban energy, dynamic movement, atmospheric depth, swirling crowds, bustling life, city pulse, human connection, dramatic lighting, evocative, powerful expression." \
  "Mistral Think" "Twilight Market Chaos"

queue_job 27 \
  "A rain-soaked back alley at night, neon signs reflecting in deep puddles, silhouettes of pedestrians under black umbrellas, wet cobblestones glistening under streetlights, moody blue and purple tones dominating. Expressionist oil painting, heavy impasto, thick textured strokes, dramatic lighting, urban melancholy, emotional depth, raw texture, vibrant contrasts, city nightlife, atmospheric tension, dynamic brushwork, solitary figures, fleeting moments, urban poetry, flickering reflections." \
  "Mistral Think" "Rain-Soaked Neon Alley"

queue_job 28 \
  "Decaying industrial district at sunset, rusted factories with broken windows, smokestacks against fiery orange sky, workers heading home, shadows stretching long across cracked pavement. Expressionist oil painting, heavy impasto, thick textured brushstrokes, warm and cool color clash, emotional weight, urban decay, raw energy, dramatic composition, atmospheric depth, powerful strokes, fading light, sense of time, rust, metal, grit, city history." \
  "Mistral Think" "Industrial Sunset"

queue_job 29 \
  "Crowded subway station at rush hour, blurred faces of commuters, bright platform lights, train arriving with motion blur, steam rising from tracks, sense of urgency and movement. Expressionist oil painting, heavy impasto, thick textured brushstrokes, vibrant urban palette, emotional intensity, raw human energy, dynamic composition, atmospheric tension, bold colors, urban chaos, powerful expression, fleeting moments, city rhythm, human movement, daily struggle." \
  "Mistral Think" "Subway Rush Hour"

queue_job 30 \
  "City rooftops at night, water towers and chimneys silhouetted against starry sky, distant glowing windows, smokestacks belching steam, cool blues and deep purples with warm yellow light accents. Expressionist oil painting, heavy impasto, thick textured brushstrokes, dramatic lighting, urban solitude, emotional depth, raw texture, atmospheric mood, cityscape, dynamic contrasts, quiet city, night atmosphere, lonely figures, urban silence." \
  "Mistral Think" "Rooftop Nocturne"

# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "An expressionist oil painting of a bustling urban street at night, heavy impasto technique. Thick, textured strokes of vibrant neon pinks, electric blues, and deep blacks depict rain-slicked asphalt reflecting glowing storefronts. Distorted, emotive silhouettes of pedestrians with umbrellas hurry through the downpour. The city architecture looms with jagged, exaggerated perspectives, conveying a sense of chaotic energy and modern isolation. Swirling brushstrokes capture the dynamic movement of wind and light, creating a visceral, tactile masterpiece." \
  "Qwen 3.7 Plus" "Neon Rain Reflections"

queue_job 32 \
  "An expressionist oil painting of a dense urban skyline, rendered with heavy impasto. Thick, sculptural layers of ochre, slate gray, and burnt sienna build towering, claustrophobic skyscrapers that twist toward a turbulent, swirling sky. Abstracted, frantic brushwork defines the chaotic rhythm of city traffic below, where streaks of crimson and gold suggest speeding vehicles. The tactile paint application emphasizes the raw, gritty emotion of metropolitan existence, blending architectural rigidity with wild, untamed human vital energy." \
  "Qwen 3.7 Plus" "Concrete Canopy Dreams"

queue_job 33 \
  "An expressionist oil painting of a dimly lit urban subway station, executed with heavy impasto. Thick, aggressive strokes of murky greens, deep purples, and stark whites construct the tiled walls and descending stairs. A solitary, abstracted figure stands on the platform, their form built from chaotic, swirling daubs of paint that convey profound isolation. The heavy texture of the oil captures the damp, echoing atmosphere of the underground, transforming a mundane commute into visceral art." \
  "Qwen 3.7 Plus" "Subway Solitude"

queue_job 34 \
  "An expressionist oil painting of a crowded urban rooftop at twilight, featuring heavy impasto. Thick, dynamic layers of violet, magenta, and charcoal black depict a skyline fractured by jagged, emotional brushstrokes. Silhouettes of people gather near the edge, their forms melting into the textured, swirling sky. The tactile application of paint creates a sense of urgent movement and psychological tension. Glowing windows pierce the gloom like fractured jewels, emphasizing the raw, untamed spirit of cityscapes." \
  "Qwen 3.7 Plus" "Rooftop Twilight Chaos"

queue_job 35 \
  "An expressionist oil painting of an abandoned urban industrial zone, rendered with heavy impasto. Thick, sculptural globs of rust orange, slate gray, and muted olive green build crumbling brick factories and twisted metal scaffolding. Aggressive, chaotic brushwork conveys the violent decay of the city, while stark highlights of cadmium yellow suggest fleeting, hopeful sunlight breaking through smog. The intense physical texture of the paint evokes a profound sense of melancholy, transforming urban ruin into poetry." \
  "Qwen 3.7 Plus" "Industrial Decay Reverie"

# --- GLM 5.1 Think ---
queue_job 36 \
  "Expressionist oil painting of a bustling urban street at night, heavy impasto technique with thick, swirling brushstrokes. Neon signs bleed vibrant reds and yellows onto wet asphalt, creating distorted, chaotic reflections. Towering, slightly leaning buildings loom overhead, sculpted with aggressive palette knife strokes and thick globs of paint. Blurred figures hurry through the rain, glowing streetlamps casting dramatic, elongated shadows. Intense emotional atmosphere, raw city energy, textured paint layers, vivid colors." \
  "GLM 5.1 Think" "Neon Metropolis"

queue_job 37 \
  "Expressionist oil painting of a crowded urban subway station, heavy impasto style with thick, raised paint textures. A speeding train blurs into a chaotic streak of electric blue and stark white, slicing through the dark, cavernous tunnel. Anxious commuters are distorted figures with elongated limbs, painted with frantic, aggressive brushstrokes. Harsh fluorescent lights cast sickly green and yellow hues over the rough, textured architecture. Raw emotion, urban alienation, thick palette knife marks, vibrant, clashing colors." \
  "GLM 5.1 Think" "Subway Rush"

queue_job 38 \
  "Expressionist oil painting of a narrow, gritty urban alleyway, heavy impasto technique with thickly applied, sculptural paint. Dumpsters and fire escapes twist in distorted, angular shapes, rendered with aggressive, jagged brushstrokes. A single, harsh streetlight casts deep, moody purple and stark orange shadows on the brick walls. A solitary figure huddles in the gloom, painted with rough, emotional intensity. Rain-slicked cobblestones glisten with thick, swirling daubs of color. Intense urban isolation, raw texture, heavy paint layers." \
  "GLM 5.1 Think" "Alleyway Shadows"

queue_job 39 \
  "Expressionist oil painting of towering urban skyscrapers at dawn, heavy impasto style featuring massive, thick globs of paint. The glass buildings sway and distort, reflecting furious streaks of crimson, magenta, and gold across the sky, applied with a palette knife. Dark, angular streets slice through the concrete canyons below, choking on thick, painted fog. Tiny, distorted cars crawl through the urban abyss. Overwhelming scale, dramatic emotional intensity, rough sculptural texture, vivid, swirling oil colors." \
  "GLM 5.1 Think" "Dawn Over Steel"

queue_job 40 \
  "Expressionist oil painting of a massive urban bridge in gridlock, heavy impasto technique with thick, swirling, chaotic brushstrokes. Cars and taxis are smears of vibrant yellow and red, trapped in a distorted, endless traffic jam. Steel cables twist like angry serpents against a stormy, turbulent sky of dark grey and bruised purple. Thick layers of paint create a rough, tactile surface, emphasizing the raw, suffocating energy and frustration of the modern city. Intense, textured masterpiece." \
  "GLM 5.1 Think" "Bridge Gridlock"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "Expressionist oil painting, heavy impasto, urban street at midnight, rain-slicked asphalt reflecting neon signs in electric blues and magentas, solitary figure with umbrella crossing the road, thick palette knife strokes creating tactile surface texture, wet cobblestones glistening, steam rising from subway grates, towering glass buildings distorted by rain, bold impasto highlights catching artificial light, melancholic atmosphere, visceral paint texture dominating the canvas" \
  "Kimi K2.6 Thinking" "Midnight Rain on Neon Avenue"

queue_job 42 \
  "Expressionist oil painting, heavy impasto, lone figure standing on concrete rooftop overlooking endless cityscape, thick sculptural paint layers forming storm clouds above skyscrapers, wind-whipped coat rendered in aggressive palette knife strokes, warm amber windows contrasting cool slate blues, dramatic chiaroscuro between shadowed alleys and glowing towers, textured brushwork emphasizing isolation, urban geometry dissolving into expressive paint handling, emotional tension in every impasto ridge" \
  "Kimi K2.6 Thinking" "Rooftop Solitude Above the Metropolis"

queue_job 43 \
  "Expressionist oil painting, heavy impasto, underground subway platform at rush hour, faceless commuters as blurred gestural figures, thick paint application creating vibrating energy, fluorescent tubes casting sickly green-white light, concrete walls with peeling posters rendered in heavy texture, motion blur through impasto direction, metallic train streaking through station, urban anxiety palpable in raised paint surface, claustrophobic composition with bold diagonal strokes, raw emotional intensity" \
  "Kimi K2.6 Thinking" "Subway Ghosts in Fluorescent Haze"

queue_job 44 \
  "Expressionist oil painting, heavy impasto, towering construction cranes silhouetted against bruised purple dawn sky, steel girders and scaffolding forming abstract geometric patterns, thick impasto concrete and rust textures, worker figures dwarfed by industrial scale, welding sparks as flickering orange impasto dots, unfinished building rising like modern cathedral, palette knife scraping revealing underlayers, urban transformation frozen in heavy paint, monumental scale through exaggerated texture, reverent mood in industrial decay" \
  "Kimi K2.6 Thinking" "Construction Site Cathedral at Dawn"

queue_job 45 \
  "Expressionist oil painting, heavy impasto, cyclist weaving between glass towers, motion trails carved through thick wet paint, reflective building facades fractured into angular color patches, autumn leaves swirling in turbulent brushstrokes, messenger bag slung across body in bold diagonal thrust, street-level perspective looking upward at crushing architecture, warm figure against cool corporate blues, urgent energy in every stroke, urban velocity captured in sculptural paint surface, fleeting moment immortalized in texture" \
  "Kimi K2.6 Thinking" "Bicycle Messenger Through Financial District"

# --- Deepseek Expert ---
queue_job 46 \
  "A deafening subway train blurs through a station, its motion rendered in thick, jagged smears of crimson and deep blue oil paint. Heavy impasto strokes of yellow ochre and white construct tunnel lights streaking past. Commuters are faceless, melting figures of black and grey, their forms distorted by speed. The platform tiles dissolve into churning, turbulent vertical strokes, creating a claustrophobic, violent urban energy." \
  "Deepseek Expert" "Street Chorus at Midnight"

queue_job 47 \
  "An elevated railway bridge dominates the canvas, its rusted iron girders slathered in impasto rust orange, umber, and lead grey. Below, a compressed cityscape of tilted tenement rooftops writhes in thick, aggressive strokes of toxic green and muddy yellow. A lone water tower, bulbous and heavy with white lead paint, tilts precariously. The sky is a churned, low ceiling of bruised purple and charcoal." \
  "Deepseek Expert" "Roof of the Iron City"

queue_job 48 \
  "Viewed from a rain-streaked street, a corner bakery glows with violent yellow and cadmium orange impasto. The hot window pane is a shattered mosaic of thick paint, warping pastries inside into blurry, swelling forms. Wet pavement below is a slab of deep violet and black, reflecting the light in heavy, dragging strokes. A solitary umbrella, a slash of crimson red, hovers near the entrance." \
  "Deepseek Expert" "Midnight Bakery Window"

queue_job 49 \
  "Concrete pillars support a roaring elevated road, their surfaces a tortured geology of thick grey, raw umber, and flaking white paint. Beyond the pillars, a compressed vista of chain-link fences and graffiti tags, rendered in drips of impasto magenta and emerald. A single figure in a hoodie is a ghostly block of charcoal black, shrinking against the massive, crushing weight of infrastructure." \
  "Deepseek Expert" "Under the Expressway"

queue_job 50 \
  "A canyon of high-rises, their walls slathered in aggressive impasto strokes of neon blue, violet, and acid yellow spilling from lit windows. The street is a compressed wedge of churning taxi cabs, each a frantic dab of cadmium red and chrome orange. Pedestrians are elongated, distorted shadows bleeding into the wet asphalt. The sky between buildings is a narrow, searing strip of electric crimson." \
  "Deepseek Expert" "Electric Evening on 5th Avenue"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A massively towering ancient urban skyline under dark stormy skies rendered in thick expressive impasto oil paint with heavy palette knife strokes creating raw texture, neon lights bleeding through rain-soaked streets, dark moody atmosphere with vibrant splashes of electric blue and crimson, distorted buildings leaning dramatically, wet asphalt reflecting fractured city lights, raw emotional intensity, deeply powerful turbulent overwhelming expressionist urban nightscape with bold chaotic brushwork and thick vividly layered paint heavy raw energy truly." \
  "ERNIE 5.1 Thinking" "Neon Rain in the Concrete Jungle"

queue_job 52 \
  "A bustling city intersection at sunset painted in bold expressionist impasto oil style, thick paint layers showing rushing crowds and yellow taxis, heavy textured brushstrokes capturing motion blur, warm orange and cool gray tones colliding dramatically, towering glass buildings distorting in thick paint, street vendors and traffic merged into abstract shapes, raw urban energy, palette knife technique, vibrant chaotic city life rendered with heavy impasto and deeply powerful overwhelming emotional intensity truly vividly and raw." \
  "ERNIE 5.1 Thinking" "Rush Hour Chaos"

queue_job 53 \
  "A crowded subway station rendered in heavy impasto expressionist oil painting, thick textured paint creating claustrophobic depth, commuters pressed together in abstract forms, flickering fluorescent lights casting sickly green and yellow tones, wet tiled walls reflecting distorted figures, heavy palette knife work building raw urban tension, dark underground atmosphere with splashes of vivid color, emotional anguish of city life, bold chaotic strokes, thick layered oil paint, expressionist urban underground scene deeply powerful truly raw vividly." \
  "ERNIE 5.1 Thinking" "Underground Pulse"

queue_job 54 \
  "An industrial waterfront district painted in aggressive expressionist impasto oil, thick paint slabs depicting smokestacks belching dark clouds, heavy palette knife strokes building raw texture, rusted cranes and cargo ships in muddy browns and fiery oranges, turbulent water reflecting pollution in sickly greens, workers as dark silhouettes against blazing furnaces, urban decay and power colliding, bold chaotic energy, heavy layered impasto technique, expressionist industrial urban landscape with thick raw paint deeply emotional powerfully truly vividly." \
  "ERNIE 5.1 Thinking" "Steel and Smoke"

queue_job 55 \
  "A lone figure standing on a crumbling rooftop overlooking a sprawling megacity at dusk, painted in thick expressionist impasto oil with heavy palette knife application, the city below a swirling mass of warm ambers and cold steel blues, thick paint ridges creating dramatic depth, wind-swept atmosphere with abstracted buildings stretching endlessly, isolation amid urban chaos, bold emotional brushwork, raw texture building tension, heavy layered oil paint, expressionist urban rooftop solitude scene with vivid impasto truly." \
  "ERNIE 5.1 Thinking" "Rooftop Solitude"

# --- LongCat Deep Search ---
queue_job 56 \
  "A rain-slicked city street at night, towering buildings with distorted reflections in oily puddles, heavy impasto brushstrokes creating texture in cobalt blue and burnt sienna, expressionist interpretation of urban isolation under glowing streetlights, thickly layered oil paint capturing the emotional weight of metropolitan solitude, visible palette knife marks, vibrant yet melancholic color palette." \
  "LongCat" "Rainy Downtown Nocturne"

queue_job 57 \
  "Bustling urban marketplace scene with exaggerated perspective, vendors and crowds rendered in thick expressive strokes, heavy impasto technique building dimensional forms in cadmium red and golden yellow, chaotic energy of city commerce through distorted angular shapes, oil paint applied generously creating tactile surface, vibrant complementary colors clashing dynamically." \
  "LongCat" "Metropolitan Market Chaos"

queue_job 58 \
  "Narrow urban alley with dramatic chiaroscuro lighting, expressionist oil painting style using heavy impasto to create deep shadows and sharp highlights, thickly textured walls in umbers and slate gray, single figure silhouetted against distant light, emotional tension through distorted perspective and vigorous brushwork, palette knife techniques visible." \
  "LongCat" "Alleyway Shadows"

queue_job 59 \
  "Electric nighttime cityscape with glowing neon signs bleeding color, expressionist interpretation using thick impasto layers in magenta and electric blue, distorted reflections on wet asphalt, heavy oil paint creating three-dimensional quality, visible brushstrokes conveying urban energy, vibrant unnatural colors expressing metropolitan excitement." \
  "LongCat" "Neon District Reverie"

queue_job 60 \
  "Urban renewal scene with cranes and scaffolding, expressionist oil painting using aggressive impasto technique in steel gray and safety orange, dynamic diagonal compositions creating movement, thickly applied paint forming architectural textures, distorted perspective emphasizing scale and power, raw energetic brushwork capturing construction chaos." \
  "LongCat" "Construction Site Dynamism"

echo "✅ All 60 jobs queued in scheduler"
