#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Stunning drone photo of beautiful scenery
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+20+-+drone+photo
# Structure: 10 models × 5 prompts = 50 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "Aerial drone photograph shot directly overhead, looking straight down at a sprawling metropolitan grid at night. City blocks form a perfect geometric mosaic of glowing amber streetlights, electric-blue LED highways, and warm golden towers. Cars trace long white and red light trails across intersections. Dark rooftops punctuate the luminous web like islands. The overall composition reads as pure abstract geometry — a circuit board of human civilization. Atmosphere is clear with slight urban haze softening distant blocks. Exposure balanced to preserve deep shadow blacks against vivid light bloom. Colors: amber, gold, electric blue, crimson. Hyper-detailed, ultra-sharp, commercial drone photography aesthetic, professional color grading, cinematic mood." \
  "Claude Sonnet 4.6" "Neon Veins — City Grid at Night"

queue_job  2 \
  "Drone aerial photograph captured from high altitude looking straight down over a shallow Maldivian atoll reef system. Intricate coral formations create organic branching patterns beneath crystal-clear water ranging from pale mint near sandbars to rich turquoise over deep channels and near-black in the abyssal drop-offs beyond the reef edge. A single white crescent sandbar cuts diagonally across the frame, foam-edged by gentle surf. No structures, no people — pure nature. Water gradients shift across ten distinct tonal bands of blue-green. Sunlight refracts through the surface creating caustic shimmer patterns across the reef floor. Shot during midday for maximum water clarity and color saturation. Hyper-sharp, commercial aerial photography, vivid natural color palette." \
  "Claude Sonnet 4.6" "Turquoise Labyrinth — Maldivian Sandbar Reef"

queue_job  3 \
  "Low-altitude drone photograph taken at a dramatic oblique angle flying parallel to an active volcanic ridge at the moment of dusk. The jagged lava spine runs diagonally from lower-left to upper-right, its black basalt surface split by glowing orange-red lava fissures. Steam vents billow white clouds that catch the last violet and rose light of the setting sun on their upper edges while their bases glow amber from the heat below. The surrounding landscape is entirely black solidified lava fields, deeply textured and cracked. Sky transitions from burnt orange at the horizon through violet to deep indigo overhead. Composition emphasizes the diagonal tension of the ridge against the gradient sky. Ultra-detailed, cinematic aerial photography, raw geological drama." \
  "Claude Sonnet 4.6" "Ember Spine — Volcanic Ridge at Dusk"

queue_job  4 \
  "High-altitude drone photograph at a wide oblique angle overlooking a vast river delta emptying into the sea at golden hour. The main river channel and its dozens of silver braided tributaries catch direct low sunlight and reflect it back as luminous molten-gold threads weaving across dark green wetland plains. Shallow oxbow lakes mirror patches of warm peach sky. The coastline dissolves into a hazy horizon where river silt turns the sea a milky jade. Long shadows from sparse treelines stripe the marshland. The image reads as an abstract painting of intersecting silver and gold lines on a dark emerald canvas. Atmosphere: warm, hazy, painterly. Shot with telephoto compression to flatten and emphasize the pattern density. Cinematic color grade, professional aerial photography." \
  "Claude Sonnet 4.6" "Silver Serpent — River Delta at Golden Hour"

queue_job  5 \
  "Medium-altitude drone photograph at a steep oblique angle overlooking a high-altitude alpine lake in deep winter. The lake surface is frozen in irregular fractured ice plates ranging from opaque white snow-covered sections to translucent dark teal where ice is thin. Surrounding peaks are draped in pristine snow with exposed charcoal granite ridgelines cutting through. A frozen waterfall on the far shore is suspended mid-cascade in milky white ice. Long blue shadows from the peaks sweep across the snow in strong diagonal lines, adding graphic structure to the composition. Dawn light tints the highest snowfields in soft rose and apricot while the valley floor remains in cool blue shadow. Atmosphere is razor-sharp, cold, crystalline. Hyper-detailed, cinematic aerial photography, dramatic natural light." \
  "Claude Sonnet 4.6" "Frozen Crown — Mountain Lake Winter Aerial"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A breathtaking high-altitude drone photograph capturing the dramatic intersection where a rugged, dark basalt coastline meets a powerful, churning turquoise ocean. The camera is angled at a steep seventy-degree pitch, looking down at the swirling white sea foam as crashing waves fracture against jagged rock formations. A single, narrow ribbon of a coastal highway hugs the edge of the cliffside, with one silver sports car caught in motion, its headlights cutting through the ambient mist. The lighting is dialed into the golden hour, casting long, deep shadows across the landscape and illuminating the sea spray with a brilliant, shimmering orange glow. The composition balances the raw, chaotic energy of the ocean on the right with the dark, stable texture of the volcanic rock on the left, creating an incredibly eye-catching and harmonious contrast." \
  "Gemini 3.5 Flash" "Coastal Convergence"

queue_job  7 \
  "An immersive, top-down orthogonal drone shot capturing a massive metropolitan core at midnight. The camera looks completely straight down, transforming towering skyscrapers into a mesmerizing geometric grid of glass and light. Veins of neon blue and violet lines glow from the street levels, with long-exposure light trails from moving traffic forming smooth, kinetic streams of amber and ruby red through the concrete canyons. One prominent central tower features a rooftop garden with an illuminated, circular infinity pool that reflects the surrounding cityscape like a mirror. The atmosphere is crystal clear, emphasizing the sharp, hyper-detailed architectural edges and the sheer depth of the urban canyons below. The overall aesthetic is ultra-modern and cinematic, presenting a vibrant, pulsating electronic ecosystem frozen in time from a perfect celestial vantage point." \
  "Gemini 3.5 Flash" "Neon Metropolis"

queue_job  8 \
  "A striking, minimalist drone photograph looking down at a vast, wind-swept desert landscape during twilight. The camera captures a series of sharp, undulating sand dunes that form elegant, serpentine s-curves across the entire frame. The low-angle, fading sun casts one side of every dune in a deep, cool indigo shadow while the opposing slopes glow with a warm, rich terracotta orange. A tiny, isolated oasis with three solitary emerald-green palm trees and a small, glassy pool of water rests in a deep depression between the ridges, serving as a powerful focal point of life against the barren sands. The texture of the wind-rippled sand is impeccably defined, creating a soothing yet visually compelling pattern. The composition relies on pure geometric form, color contrast, and sweeping lines to create an incredibly elegant, artistic view." \
  "Gemini 3.5 Flash" "Sinuous Desert Ridge"

queue_job  9 \
  "A magnificent wide-angle drone shot hovering just above a pristine, mirror-like alpine lake nestled deep within a jagged mountain range at sunrise. The camera is positioned at a low forty-five-degree angle, perfectly capturing both the immense scale of the snow-capped peaks and their flawless reflection in the dark, still water below. A dense forest of deep green pine trees blankets the lower slopes, frosted with a light layer of morning mist that catches the first golden rays of sunlight breaking over the crests. A solitary wooden pier extends out into the glass-like water from the bottom corner, leading the viewer's eye into the expansive wilderness. The color palette transitions beautifully from the cool blues of the water and shadows to the brilliant pinks and golds illuminating the mountain peaks, delivering an exceptionally serene and high-impact visual landscape." \
  "Gemini 3.5 Flash" "Alpine Mirror"

queue_job 10 \
  "A vibrant, high-altitude drone photograph capturing a dense, ancient forest completely transformed by peak autumn foliage. The camera shoots from a top-down perspective, revealing an intricate tapestry of intense crimson, fiery orange, and brilliant golden yellow tree canopies packed tightly together. Cutting directly through the center of this vivid color explosion is a winding, crystal-clear river, its deep sapphire blue water creating a stark, breathtaking color contrast against the warm forest floor. The natural curves of the riverbank shape the composition, drawing a clean line through the organic chaos of the trees. Soft, diffused morning light eliminates harsh shadows, allowing the saturation of the leaves and the gentle ripples of the water to appear incredibly rich, detailed, and aesthetically captivating." \
  "Gemini 3.5 Flash" "Autumnal Ribbon"

# --- ChatGPT ---
queue_job 11 \
  "A breathtaking drone photograph capturing a pristine coastline at golden hour, where turquoise waves gently fold into a long stretch of pale sand. The camera hovers at a high oblique angle, revealing intricate patterns formed by receding tides, wet sand reflecting warm sunlight like liquid gold. A few scattered rocks break the symmetry, casting long soft shadows, while tiny figures of people walking create a sense of scale. The horizon is slightly hazy, blending sky and sea into a dreamy gradient. The composition emphasizes natural geometry and calming repetition, with soft contrast, high dynamic range, and cinematic lighting that enhances textures and depth, creating an inviting, tranquil yet visually striking scene." \
  "ChatGPT" "Golden Tides from Above"

queue_job 12 \
  "A dramatic aerial drone shot taken directly above a sprawling metropolis at night, where glowing highways twist like luminous veins through a dense grid of skyscrapers. The perspective is perfectly vertical, showcasing a mesmerizing symmetry of moving car lights in red and white streaks. Buildings radiate cool blue and purple tones, punctuated by warm neon signs and illuminated windows. The scene feels alive with motion, long exposure enhancing the dynamic energy of urban life. Reflections on glass surfaces add complexity and depth, while subtle fog diffuses light, giving a cinematic glow. The composition is both chaotic and harmonious, capturing the pulse of a futuristic cityscape in stunning clarity." \
  "ChatGPT" "Neon Veins of the Night City"

queue_job 13 \
  "A majestic drone image of a winding emerald-green river cutting through a dramatic mountain valley, captured from a high angled perspective. Steep cliffs covered in dense forest rise on both sides, their textures enhanced by soft morning light filtering through mist. The river glows vividly against darker terrain, forming elegant curves that guide the viewer's eye across the frame. Low-hanging clouds drift between peaks, adding depth and a sense of scale. The color palette is rich with greens, deep shadows, and subtle highlights, creating a painterly yet realistic atmosphere. The composition balances grandeur and serenity, showcasing untouched wilderness in a visually captivating way." \
  "ChatGPT" "Emerald River Through the Mountains"

queue_job 14 \
  "An abstract and visually striking drone shot of snow-covered farmland, viewed from a perfectly top-down perspective. The landscape forms a patchwork of geometric fields divided by thin lines of fences and roads, all softened under a blanket of fresh snow. Subtle variations in texture and tone create delicate contrasts between sections, while long shadows from trees and structures stretch across the white surface. Occasional dark elements like barns or clusters of trees punctuate the composition, adding focal points. The minimalistic palette of whites, grays, and muted blues enhances the graphic quality of the scene, transforming a rural setting into a mesmerizing piece of natural abstract art." \
  "ChatGPT" "Frozen Geometry of Winter Fields"

queue_job 15 \
  "A stunning drone photograph of a volcanic island surrounded by deep blue ocean, captured at a cinematic angle during sunset. The rugged terrain glows with warm orange and red tones as the sun dips below the horizon, casting dramatic light across cliffs and lava formations. Waves crash against the rocky shoreline, creating white foam patterns that contrast beautifully with dark volcanic rock. A plume of light smoke rises subtly from the crater, adding a sense of raw natural power. The sky transitions from fiery hues to soft purples, reflecting on the water's surface. The composition combines intensity and beauty, delivering a powerful, unforgettable visual narrative." \
  "ChatGPT" "Island of Fire at Sunset"

# --- Grok ---
queue_job 16 \
  "A breathtaking drone shot captured from high above a pristine tropical coastline at golden hour, where crystal turquoise waters meet powdery white sand beaches in gentle curving patterns. Dramatic cliffs covered in lush green vegetation plunge into the sea, creating intricate rock formations and natural pools. Warm sunlight bathes the scene in rich amber and rose hues, with long shadows enhancing depth and texture. Gentle waves create delicate foam lines along the shore, while scattered small islands and coral reefs are visible beneath the transparent water. Vibrant, cinematic lighting with high contrast, ultra-detailed textures, majestic composition, ethereal atmosphere, perfect symmetry in natural elements, awe-inspiring natural beauty, hyper-realistic, National Geographic level photography." \
  "Grok" "Golden Hour Coastal Majesty"

queue_job 17 \
  "Stunning aerial drone photograph of a sprawling futuristic metropolis at night, viewed from a dramatic diagonal angle high above the skyscrapers. Countless glowing neon lights and illuminated windows create rivers of light across the urban grid, with flying vehicles leaving light trails in the sky. Reflective glass towers mirror the vibrant city glow against a deep indigo night sky dotted with stars. A wide river snakes through the center reflecting all the lights like liquid diamonds. Atmospheric haze adds depth and mystery, volumetric lighting from billboards and street lamps, ultra-sharp details, cinematic color grading with electric blues, magentas and golds, mesmerizing and energetic urban beauty." \
  "Grok" "Neon City Nights"

queue_job 18 \
  "Epic drone view from directly overhead of a pristine alpine lake nestled between snow-capped mountain peaks during early morning light. The perfectly still turquoise water acts as a mirror reflecting the dramatic jagged mountains and fiery orange sunrise clouds. Lush evergreen forests carpet the slopes leading down to rocky shores. Mist gently rises from the water surface creating ethereal layers. Crystal clear reflections, rich color palette of deep blues, emerald greens and warm golden tones, majestic scale, incredible depth and detail, serene yet powerful natural landscape, National Geographic quality aerial photography with perfect composition." \
  "Grok" "Mountain Lake Symphony"

queue_job 19 \
  "Magnificent drone photograph taken at a dynamic low-angle approach over a vast desert canyon system at sunset. Layered red rock formations stretch endlessly with intricate erosion patterns and deep winding gorges. A narrow river snakes through the bottom of the canyon catching the last golden rays of sunlight. Dramatic shadows play across the textured rock faces creating incredible depth and dimension. Sparse desert vegetation and distant mesas complete the scene. Warm terracotta, burnt orange and purple color palette, cinematic lighting, ultra-realistic geological details, breathtaking scale and natural artistry." \
  "Grok" "Ancient Canyon Wonder"

queue_job 20 \
  "Breathtaking high-angle drone shot of a remote tropical island surrounded by vibrant turquoise and deep blue ocean waters. The island features lush dense jungle vegetation, pristine white sand beaches, and dramatic volcanic rock formations. A hidden waterfall cascades into a natural lagoon visible from above. Soft morning light creates gentle highlights on the waves and palm trees swaying in the breeze. Coral reefs visible through the crystal clear water create mesmerizing underwater patterns. Vibrant greens, aquamarine blues, and golden sand tones, perfect composition, dreamy paradise atmosphere, hyper-detailed, National Geographic level stunning aerial photography." \
  "Grok" "Tropical Island Paradise"

# --- Copilot ---
queue_job 21 \
  "A breathtaking drone shot capturing a golden coastline at sunset, where the waves gently kiss the sandy shore and the light reflects in shimmering patterns across the water. The perspective highlights the contrast between the deep blue sea and the warm tones of the land, with winding paths and scattered greenery adding texture to the scene. The aerial view emphasizes the vastness of the ocean meeting the delicate curves of the beach, creating an atmosphere of serenity and grandeur. The composition balances natural beauty with geometric harmony, making the scenery both peaceful and awe-inspiring." \
  "Copilot" "Golden Coastline from Above"

queue_job 22 \
  "An enchanting drone photograph of a bustling city at night, illuminated by thousands of glowing lights that form intricate patterns across streets and skyscrapers. The aerial perspective reveals the rhythm of urban life, with cars streaming like rivers of light and towering buildings standing as luminous beacons. The shot captures the vibrancy of nightlife, blending modern architecture with the timeless beauty of a starry sky above. The symmetry of the city grid contrasts with the organic flow of movement, creating a mesmerizing balance between order and chaos. The result is a dazzling, eye-catching panorama of urban brilliance." \
  "Copilot" "City Lights at Midnight"

queue_job 23 \
  "A stunning drone image showcasing the lush expanse of an emerald-green forest canopy, where treetops stretch endlessly in every direction. The aerial view highlights the intricate textures of leaves and branches, forming a natural mosaic of vibrant shades. Sunlight filters through the foliage, casting golden highlights that dance across the greenery. Hidden clearings and winding rivers peek through the dense forest, adding depth and mystery to the composition. The perspective conveys both the immensity of nature and its delicate details, creating a captivating balance of grandeur and intimacy in this breathtaking scenery." \
  "Copilot" "Emerald Forest Canopy"

queue_job 24 \
  "A dramatic drone shot of towering mountain peaks rising above a sea of mist, their jagged silhouettes piercing the clouds. The aerial perspective captures the ethereal beauty of nature, where the interplay of light and shadow creates a dreamlike atmosphere. The mist swirls gently around the slopes, partially revealing valleys and ridges below, while the sun casts a golden glow on the highest summits. The composition emphasizes the majesty of the mountains, blending rugged strength with delicate softness. This breathtaking scenery evokes awe and tranquility, presenting nature as both powerful and serene." \
  "Copilot" "Mountain Peaks in Mist"

queue_job 25 \
  "A captivating drone photograph of a crystal-clear lagoon, where turquoise waters shimmer under the sunlight and coral reefs form intricate patterns beneath the surface. The aerial view reveals the lagoon's natural geometry, with sandbars and shallow pools creating a mosaic of colors ranging from deep blue to pale aqua. Surrounding greenery frames the water, adding contrast and vibrancy to the scene. Gentle waves ripple across the lagoon, reflecting the sky in dazzling hues. The composition highlights the harmony between land and sea, offering a serene yet striking vision of paradise from above." \
  "Copilot" "Crystal Blue Lagoon"

# --- Mistral ---
queue_job 26 \
  "A breathtaking drone shot of a pristine coastline at golden hour, where the sun casts a warm, golden glow over the turquoise waters and soft, white sand. The perspective is directly overhead, capturing the gentle curves of the shoreline, the rhythmic patterns of small waves lapping at the beach, and the scattered shadows of palm trees swaying in the breeze. The horizon line is perfectly balanced, with the sun just touching the water, creating a stunning reflection that blends seamlessly with the sky. The colors are vibrant yet natural, with deep blues transitioning into soft oranges and pinks. The composition is symmetrical, with leading lines from the shoreline drawing the eye toward the center of the frame." \
  "Mistral" "Serene Coastal Sunset from Above"

queue_job 27 \
  "A mesmerizing aerial view of a bustling city at night, illuminated by a sea of colorful lights. The drone captures the intricate grid of streets, with glowing headlights and taillights creating dynamic trails of red and white. Skyscrapers tower above, their windows twinkling like stars, while neon signs and billboards add splashes of vivid color. The cityscape is framed by a dark, velvety sky, with a subtle hint of moonlight adding depth. The perspective is slightly angled, emphasizing the height of the buildings and the density of the urban layout. The image is sharp, with high contrast between the bright lights and the dark shadows, creating a dramatic and futuristic atmosphere." \
  "Mistral" "Urban Symphony at Night"

queue_job 28 \
  "A stunning top-down drone shot of a dense forest in the peak of autumn, revealing a vibrant mosaic of red, orange, yellow, and green foliage. The trees form a natural, organic pattern, with their crowns creating a textured carpet of color. A winding river or stream cuts through the center, its crystal-clear waters reflecting the kaleidoscope of leaves above. The sunlight filters through the canopy, casting dappled light and shadow across the forest floor. The composition is balanced, with the river acting as a leading line that guides the viewer's eye through the scene. The image is rich in detail, with crisp, sharp edges and a depth of field that keeps every leaf and branch in focus." \
  "Mistral" "Autumn Forest Tapestry"

queue_job 29 \
  "A dramatic drone photograph of a mountain range at dawn, with the first light of day illuminating the jagged peaks and casting long shadows across the valleys below. A layer of soft, white mist fills the lower elevations, creating a dreamy, ethereal effect as it spills over the edges of cliffs and ridges. The mountains are a mix of dark, rugged rock and patches of evergreen forest, providing a stark contrast to the smooth, flowing mist. The perspective is slightly angled, capturing both the grandeur of the peaks and the depth of the valleys. The colors are cool and muted, with blues and grays dominating the scene, punctuated by the warm glow of the rising sun." \
  "Mistral" "Mountain Peaks and Misty Valleys"

queue_job 30 \
  "A captivating aerial view of endless rows of lavender fields in full bloom, stretching out like a purple quilt across the rolling countryside. The drone captures the perfect symmetry of the rows, with the vibrant purple flowers creating a striking contrast against the lush green of the surrounding landscape. A narrow dirt path or a small farmhouse nestled among the fields adds a touch of rustic charm. The image is taken during the golden hour, with the low sun casting a warm, soft light over the scene, enhancing the richness of the colors. The perspective is directly overhead, emphasizing the geometric patterns of the fields and the natural beauty of the rural setting." \
  "Mistral" "Lavender Fields in Full Bloom"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A stunning drone photo captured from a high aerial perspective reveals dramatic coastal cliffs crashing into vibrant turquoise waters. Sunlight filters through scattered clouds, casting dynamic shadows across the jagged rock formations and highlighting the sparkling foam where waves meet the shore. Lush green vegetation clings to the cliff edges, providing a striking contrast against the deep blue ocean and pale sandy beaches below. The composition emphasizes the vastness of the landscape, with winding coastal roads hugging the mountainside in the distance. The clarity and lighting create an immersive, cinematic atmosphere. The shot captures the serene yet powerful energy of the coastline, showcasing intricate textures of stone, water, and foliage with remarkable detail and vivid coloration." \
  "Qwen 3.6 Plus" "Coastal Cliffs and Turquoise Waters"

queue_job 32 \
  "A breathtaking aerial view of a bustling metropolis illuminated by millions of glowing city lights after dusk. The camera hovers directly above a grid of radiant streets, capturing the mesmerizing flow of traffic that creates streaks of gold and crimson along major thoroughfares. Skyscrapers reflect the ambient light from the setting sun, casting long geometric shadows across the urban landscape. A winding river cuts through the city center, mirroring the neon reflections of bridges and waterfront buildings. The composition balances architectural density with pockets of dark green parks, adding depth and contrast. The high-altitude perspective emphasizes the scale and complexity of modern urban planning while the warm lighting evokes a sense of wonder and dynamic energy." \
  "Qwen 3.6 Plus" "Illuminated Urban Skyline"

queue_job 33 \
  "An awe-inspiring drone shot glides over a dense emerald forest nestled within a majestic alpine valley. Soft morning mist clings to the treetops, creating a dreamlike layer of white that gradually dissipates to reveal the rolling hills below. A serpentine river winds through the center of the landscape, its silver surface catching the golden rays of the rising sun. In the background, snow-capped mountain peaks rise dramatically against a gradient sky transitioning from deep blue to soft orange. The aerial perspective highlights the intricate patterns of the forest canopy and the geological textures of the surrounding slopes. The image radiates tranquility and grandeur, offering a pristine glimpse into untouched wilderness bathed in warm, ethereal lighting." \
  "Qwen 3.6 Plus" "Misty Alpine Valley"

queue_job 34 \
  "A spectacular overhead drone photograph captures an endless expanse of sweeping sand dunes bathed in warm afternoon sunlight. The undulating terrain creates mesmerizing patterns of light and shadow, with sharp ridges casting long, dark silhouettes across the smooth, wind-sculpted valleys. Hues of amber, terracotta, and pale gold blend seamlessly across the canvas, emphasizing the natural artistry of the desert landscape. A dry, cracked riverbed cuts through the foreground, adding intricate texture and guiding the eye toward the horizon. The high vantage point reveals the vast, uninhabited wilderness, while the interplay of directional light enhances the three-dimensional quality of the dunes. The overall atmosphere is serene and otherworldly, celebrating the raw beauty of arid environments." \
  "Qwen 3.6 Plus" "Golden Desert Dunes"

queue_job 35 \
  "A captivating aerial drone image showcases a pristine tropical island surrounded by a vibrant coral reef and crystal-clear lagoon. From directly above, the shot reveals a perfect crescent of white sandy beaches encircling dense clusters of swaying palm trees. The shallow waters transition from translucent white near the shore to brilliant turquoise, then deep sapphire as the seabed drops off into the open ocean. Small wooden boats anchor in the calm bay, adding subtle scale to the expansive seascape. Sunlight penetrates the surface, illuminating underwater formations and casting shimmering reflections on the gentle waves. The composition is meticulously balanced, highlighting the harmony between land and sea with vivid, saturated colors and crisp, high-definition detail." \
  "Qwen 3.6 Plus" "Tropical Island Paradise"

# --- GLM 5.1 ---
queue_job 36 \
  "Breathtaking aerial drone photograph of a pristine tropical shoreline, capturing the mesmerizing gradient of turquoise ocean water meeting powdery white sand beaches. Shot from a direct top-down perspective, the intricate patterns of vibrant coral reefs and gentle ocean waves create a stunning abstract composition. A lone luxury yacht anchors in the crystal-clear shallows, casting a perfect dark shadow on the sandy seabed below. The vibrant contrast between the deep azure sea, bright cyan shallows, and blindingly white sand is visually striking and aesthetically pleasing. Brilliant sunlight sparkles across the rippling water surface, adding a magical and dynamic touch to the scene. Ultra-high resolution, photorealistic, vivid colors, professional drone photography, masterpiece, awe-inspiring nature, tranquil paradise, cinematic lighting." \
  "GLM 5.1" "Tropical Turquoise Coastline"

queue_job 37 \
  "Spectacular nighttime drone photograph soaring above a futuristic metropolis, showcasing a dazzling cityscape illuminated by millions of glowing neon lights. Captured from a sweeping oblique angle, the towering skyscrapers pierce the dark sky, their glass facades reflecting the vibrant luminescence of magenta, cyan, and gold city lights below. Long exposure light trails from busy highways weave through the concrete canyons like flowing rivers of fire, creating an eye-catching geometric pattern of illumination. The atmosphere is thick with cinematic urban energy and dramatic contrast between the deep shadows and radiant light sources. The distant horizon reveals a faint purple dusk. Ultra-detailed, 8k resolution, award-winning drone photography, cyberpunk aesthetic, visually stunning, breathtaking metropolis, architectural marvels, glowing city night." \
  "GLM 5.1" "Neon Metropolis at Night"

queue_job 38 \
  "Stunning top-down drone photograph of a winding river snaking through a dense autumn forest, showcasing nature's incredible and vibrant color palette. The direct overhead perspective transforms the meandering water into a shiny silver ribbon contrasting sharply against the fiery canopy of crimson, burnt orange, and golden yellow leaves. Early morning mist gently rises from the cold water, weaving through the majestic trees and adding an ethereal, mystical quality to the breathtaking scenery. The intricate branching patterns of the bare treetops mix with the dense vibrant foliage, creating a mesmerizing textured mosaic that is incredibly aesthetically pleasing. Perfect natural lighting, rich saturated colors, hyper-realistic detail, majestic landscape, peaceful wilderness, spectacular aerial view." \
  "GLM 5.1" "Autumn River Mosaic"

queue_job 39 \
  "Awe-inspiring drone photography of ancient terraced rice fields carved into lush green mountains, captured from a high oblique angle that emphasizes the vast scale. The intricate geometric steps cascade down the valley like a grand staircase, filled with shimmering water that perfectly reflects the pastel colors of a breathtaking dawn. The layered landscape creates a mesmerizing visual rhythm, with the varying shades of emerald green and golden yellow crops contrasting beautifully against the reflective silver water. Low-hanging morning clouds drift through the deep valley, partially obscuring the distant peaks and adding a dramatic, ethereal depth to the stunning scenery. Masterful composition, rich textures, breathtaking agricultural landscape, vivid detail, serene atmosphere, National Geographic style." \
  "GLM 5.1" "Terraced Rice Fields at Dawn"

queue_job 40 \
  "Epic drone shot of a majestic glacial lake nestled among towering snow-capped mountains, captured from a dramatic sweeping angle that showcases the incredible terrain. The intensely turquoise water, fed by ancient glaciers, stands out vividly against the rugged dark grey rock and pristine white snow. Small fragmented icebergs float serenely on the milky, mineral-rich surface, creating a striking focal point that draws the eye. The golden hour sunlight casts long, dramatic shadows across the jagged peaks, while simultaneously illuminating the icy edges with a brilliant warm glow. The sheer scale and untouched beauty of this alpine paradise are humbling and visually arresting. Crisp mountain air, hyper-detailed landscape, majestic wilderness, awe-inspiring natural wonder, cinematic drone photography, striking contrast, pristine environment, ultra-high definition, masterpiece." \
  "GLM 5.1" "Glacial Lake Golden Hour"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A breathtaking drone photograph capturing a pristine coastline from directly above, where crystal-clear turquoise waters gently lap against powdery white sand beaches. The image reveals intricate patterns of underwater sandbars creating natural abstract art in varying shades of azure and emerald. A lone wooden pier extends into the water, casting a long shadow that stretches across the shallows. Gentle waves create foamy white lines that contrast beautifully with the deep blue ocean. The shoreline curves gracefully, forming a perfect natural bay framed by lush green tropical vegetation. Golden sunlight bathes the scene, creating subtle reflections on the wet sand and highlighting the transparency of the shallow water. The composition emphasizes the mesmerizing geometric patterns formed by the meeting of land and sea." \
  "Kimi K2.6 Thinking" "Aerial Drone View of Turquoise Coastal Waters"

queue_job 42 \
  "A stunning drone photograph capturing a sprawling modern metropolis illuminated at twilight from a dramatic high-angle perspective. Countless golden lights from skyscrapers and streets create a dazzling constellation below, forming intricate geometric patterns of glowing avenues and illuminated bridges. The deep blue-purple sky transitions to warm amber near the horizon, reflecting off the glass facades of towering buildings. A winding river cuts through the urban landscape, mirroring the city lights like a ribbon of liquid gold. Traffic trails create streaks of red and white light along the highways, suggesting vibrant energy and movement. The composition balances the organic flow of the water with the rigid grid of city blocks, creating a captivating juxtaposition of nature and human engineering bathed in ethereal nocturnal beauty." \
  "Kimi K2.6 Thinking" "Metropolitan Nightscape from Above"

queue_job 43 \
  "A mesmerizing drone photograph taken from directly above, showcasing a serpentine river carving through an ancient dense forest in brilliant autumn colors. The waterway creates elegant S-curves of deep sapphire blue, bordered by trees displaying vibrant hues of crimson, burnt orange, and golden yellow. Morning mist hovers gently above the canopy, adding ethereal softness to the scene. A small wooden footbridge crosses the river, providing scale and human interest. The interplay of light and shadow creates rich textures across the treetops, while the river's surface reflects patches of sky and surrounding foliage. Fallen leaves float on the water, creating natural patterns of red and gold against the dark current. The overall composition feels like an abstract painting woven by nature." \
  "Kimi K2.6 Thinking" "Verdant Forest River Bend"

queue_job 44 \
  "A spectacular drone photograph capturing an isolated desert oasis from a striking oblique angle, revealing mesmerizing natural geometry. Golden sand dunes stretch endlessly, their wind-sculpted ridges forming perfect parallel lines and crescent shapes that catch the warm late-afternoon light. At the center, a vibrant emerald lagoon contrasts shockingly with the surrounding amber terrain, surrounded by date palms creating a dense circular canopy of deep green. The long shadows of the palm trees stretch across the sand, creating dramatic striped patterns. A caravan trail winds toward the water, telling a silent story of ancient journeys. The color palette ranges from warm ochre and burnt sienna to cool turquoise and forest green, creating a visually arresting study of life thriving amid stark desolation." \
  "Kimi K2.6 Thinking" "Desert Oasis Geometric Patterns"

queue_job 45 \
  "A dramatic drone photograph capturing a perfectly circular volcanic crater lake from a high oblique angle during golden hour. The caldera holds deep sapphire water so clear it reveals submerged geological formations near the edges, while the center remains mysteriously dark. Steep rocky walls display striking mineral striations in rust red, sulfur yellow, and charcoal gray, creating natural geological artwork. Wispy clouds drift across the crater rim, partially obscuring the jagged peaks beyond. The rising sun illuminates one side of the crater wall, creating a stark contrast between warm golden light and cool shadowed crevices. A thin hiking trail spirals down the inner wall, emphasizing the immense scale. Steam rises gently from geothermal vents, adding atmospheric mystique to this raw, primordial landscape." \
  "Kimi K2.6 Thinking" "Volcanic Crater Lake at Dawn"

# --- Deepseek ---
queue_job 46 \
  "A stunning drone photo capturing a winding river delta slicing through a dense mangrove forest at twilight. The camera hovers directly overhead, revealing the intricate, vein-like patterns of water channels reflecting the fading orange and purple sky. The treetops form a textured, dark green carpet, punctuated by small patches of exposed mudflats glistening with moisture. Near the coast, the river widens into a serene lagoon where the water transitions from deep blue to shimmering gold. No people or buildings are visible, emphasizing pure natural geometry. The low-angle sunlight casts long shadows from the mangroves, highlighting every ridge and furrow. The composition balances symmetry and chaos, with the main channel curving gracefully toward the horizon." \
  "Deepseek" "Twilight Over the Mangrove Delta"

queue_job 47 \
  "A breathtaking drone shot of a sprawling Asian megacity after rainfall, taken from a slightly oblique high angle. The main river cuts diagonally across the frame, its dark surface reflecting streaks of neon pink, cyan, and amber from towering skyscrapers lining both banks. Highway overpasses coil like glowing serpents, with streams of car light trails creating long, smooth lines. Rooftop gardens and illuminated pedestrian bridges add layers of green and white light. A light mist hangs just above the streets, softening the edges of the city lights while keeping the skyscrapers' spires sharp. The river carries the reflection of a crescent moon, surrounded by floating lanterns from a hidden festival. The composition leads the eye from the glowing financial district in the distance to the quieter residential towers in the foreground." \
  "Deepseek" "Neon Rivers of the Night Metropolis"

queue_job 48 \
  "An awe-inspiring drone photograph of a shallow tropical atoll, shot from a perfectly vertical angle to flatten the seascape into abstract art. Turquoise and deep navy waters separate into distinct bands around rings of living coral in electric orange, soft lavender, and bright yellow. Small white sandbars form crescent shapes near the center, partially submerged and dotted with resting sea turtles barely visible through the crystal-clear water. Gentle wave patterns radiate outward from the reef crest, creating concentric circles that fade into deeper ocean. No boats or swimmers disturb the scene, preserving an untouched paradise. The sunlight hits the water at noon, making the coral formations pop like jewels against the sandy lagoon floor. A single ribbon of seagrass meanders from the reef to a tiny uninhabited islet covered in palm trees." \
  "Deepseek" "Coral Gardens from a Bird's Eye"

queue_job 49 \
  "A spectacular low-altitude drone capture of endless wheat fields rolling across a temperate plain during golden hour. The camera tilts at a dramatic oblique angle, emphasizing the rhythmic curves of the terrain as it rises and falls like ocean swells. Ripe wheat glows in warm amber and honey tones, while patches of harvested land reveal rich dark brown soil. A narrow dirt road threads through the center, its edges lined with wild sunflowers and poppies adding splashes of yellow and red. In the distance, a solitary windmill stands atop a gentle hill. The western sky blazes with layers of gold, rose, and soft lavender, mirrored faintly in a small kidney-shaped pond nestled among the crop rows. The low sun stretches every shadow eastward, creating long dark lines that accentuate the land's contours. The overall feeling is one of profound peace and agricultural beauty." \
  "Deepseek" "Golden Hour Over the Wheat Steppe"

queue_job 50 \
  "A mesmerizing drone photo of a tidewater glacier's snout where it meets a calm arctic sea, shot from an elevated but angled perspective. The glacier's surface is a maze of deep electric-blue crevasses and towering seracs, their sharp edges softened by a dusting of fresh snow. Below, the ocean water is a milky turquoise due to suspended glacial silt, dotted with dozens of small icebergs in surreal shapes — some angular, some smooth like sculptures. A thin layer of sea smoke rises where the frigid air meets the slightly warmer water, creating a misty veil at the transition line. The composition places the jagged glacier on the left two-thirds and the open water on the right, with a single arctic tern flying just above the center divide. The overcast sky diffuses light perfectly, making every ice crystal sparkle. No human activity appears, only the immense, quiet power of nature's frozen architecture." \
  "Deepseek" "Frozen Labyrinth of the Glacier's Tongue"

echo "✅ All 50 jobs queued in scheduler"
