#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Original illustrative style — each model invented its own style
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+25+-+original+illustrative+style
# Structure: 10 models × 5 prompts = 50 tasks total
#
# Style names per model:
#   Claude Sonnet 4.6  → Burnt Paper Cartography
#   Gemini 3.5 Flash   → Stained-Glass Woodcut Expressionism
#   ChatGPT            → Chromatic Echo Engraving
#   Grok               → Lyrical Etherink
#   Copilot            → Chromaflow Etching
#   Mistral            → (no style name given; prompts use inline style descriptions)
#   Qwen 3.6 Plus      → Moiré Stipple-Vellum Weave
#   GLM 5.1            → Glowing Epoxy Linocut
#   Kimi K2.6 Thinking → Chromatic Meridian Etching
#   Deepseek           → mixed per-prompt styles
#   ERNIE 5.1 Thinking → Pressed Lightning Herbarium
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 — Burnt Paper Cartography ---
queue_job  1 \
  "Topographic map illustration rendered on scorched and tea-stained paper with singed edges, ink lines depicting impossible city districts with ornate compass rose, hand-lettered district names in faded sepia calligraphy, elevation contours suggesting underground caverns, tiny marginalia sketches of mythical landmarks, wax seal impressions bleeding rust-red, torn paper revealing layered older maps beneath, foxing and water damage adding authentic age patina, thread-thin streets converging at a central void, illegible annotations crowding every margin, cartouche border with baroque illustration elements, isolated warm amber and charcoal palette, highly detailed archival document aesthetic." \
  "Claude Sonnet 4.6" "Map of a City That Never Was"

queue_job  2 \
  "Scientific illustration cross-section of a thunderstorm rendered on scorched and foxed archival paper, vertical atmospheric diagram with hand-labeled cloud strata in faded ink, lightning channels traced in cracked gilt, barometric pressure annotations crowding margins, tiny inset diagrams of ice crystal formation, compass wind indicators with baroque detailing, burn marks from heat obscuring peripheral data, sepia watercolor washes bleeding into torn paper fibers, Victorian meteorological chart aesthetic, numbered callouts in copper-tinted ink, central cumulonimbus rising through scorched layers like an excavated fossil, aged document warmth throughout." \
  "Claude Sonnet 4.6" "Anatomy of a Storm"

queue_job  3 \
  "Ornithological migration chart on scorched tea-stained parchment, dotted flight-path arcs crossing imaginary continents in oxidized copper ink, silhouetted bird species rendered in precise field-guide style with hand-lettered Latin names bleeding at edges, burnt perimeter framing nested inset range maps, wax seal impressions marking seasonal waypoints, marginalia of feather studies and egg cross-sections, foxed paper grain visible through thin sepia wash, compass rose partially consumed by char, layered older route markings visible beneath peeling surface, archival warmth of amber and deep umber, Victorian natural history document aesthetic." \
  "Claude Sonnet 4.6" "Migration Routes of Imaginary Birds"

queue_job  4 \
  "Oceanographic depth chart on scorched and brine-stained archival paper, concentric bathymetric contours descending in darkening sepia ink toward an abyssal central void, hand-lettered depth measurements in faded Victorian script, marginal creature sketches in precise naturalist style with partial char obscuring limbs, pressure notations crowding column edges, torn paper corners revealing older survey data beneath, rust-red wax seal impressions marking trench boundaries, delicate gilt lines tracing thermal vent clusters, barometric and salinity annotation tables half-burned, aged document atmosphere of discovery and decay, amber warmth throughout with cool charcoal shadows deepening toward center." \
  "Claude Sonnet 4.6" "Deep Sea Pressure Zones"

queue_job  5 \
  "Botanical underground cross-section illustration on scorched field-survey parchment, detailed ink rendering of root networks radiating from six ancient trunks above soil horizon line, mycelium web traced in hair-thin oxidized copper lines connecting all systems, hand-labeled species annotations with partial char obscuring text, soil strata layers labeled in faded Victorian taxonomy script, earthworm and stone silhouettes embedded in amber watercolor wash, burnt document edges framing the composition, foxing clusters mimicking fungal colonies, marginalia of isolated root-tip magnification studies, cracked surface patina resembling dry earth fissures, warm umber and charcoal palette, archival natural history document aesthetic." \
  "Claude Sonnet 4.6" "Root Systems of an Ancient Forest"

# --- Gemini 3.5 Flash — Stained-Glass Woodcut Expressionism ---
queue_job  6 \
  "An intricate illustrative composition depicting an antique aviary filled with mechanical birds, rendered in a bold Stained-Glass Woodcut Expressionism style. Every element is defined by thick, dark, hand-chiseled ink outlines that separate vibrant, glowing panes of color. A mechanical owl with brass gears and glowing amber glass eyes perches on a wrought-iron branch, surrounded by smaller clockwork hummingbirds with ruby-red and sapphire-blue translucent wings. The background features a complex lattice of interlocking geometric window panes filtering a warm, golden sunset light. The textures mimic deeply grained weathered oak wood and smooth, polished glass panels. High-contrast lighting with deep, heavy shadows pooling in the corners creates a dramatic, tactile, and handcrafted feel. The color palette relies heavily on rich cerulean, deep crimson, burnt orange, and metallic bronze accents, avoiding any photorealism." \
  "Gemini 3.5 Flash" "The Clockwork Aviary"

queue_job  7 \
  "An illustrative study of an enchanting botanical greenhouse, executed in a striking Stained-Glass Woodcut Expressionism aesthetic. The entire scene is constructed from heavy, block-printed black outlines enclosing luminous, saturated colors. In the center, a colossal, stylized lotus flower blooms with petals made of iridescent violet and emerald-green glass fragments, glowing from within. Coiling vines with sharp, wood-carved leaves wrap around a towering glass terrarium filled with swirling, neon-blue mist. The atmosphere is dense and mysterious, with thick beams of fractured, multi-colored light piercing through the heavy iron frame of the roof. Deep, ink-heavy shadows cut across the floor tiles, contrasting sharply with the radiant, glowing plant life. The overall texture is a blend of rough, chiseled wood grain and perfectly smooth, reflective glass, creating a rich, illustrative visual tapestry." \
  "Gemini 3.5 Flash" "The Alchemist's Greenhouse"

queue_job  8 \
  "A powerful illustrative representation of a lonely lighthouse standing against a cosmic storm, stylized in Stained-Glass Woodcut Expressionism. The lighthouse is a monolith of dark, blocky stone textures bounded by heavy, hand-inked black lines. From its beacon, a brilliant, fractured beam of pure lemon-yellow and stark white light pierces through a turbulent sky made of swirling, interlocking ribbons of indigo, deep magenta, and midnight-blue glass. Crashing waves below are rendered as sharp, jagged shards of turquoise and seafoam glass exploding against the dark cliffs. The composition is defined by its stark contrast, where heavy, impenetrable shadows meet intense, radiant panes of color. The visual rhythm feels handcrafted and ancient, combining the raw, graphic energy of a traditional woodblock print with the luminous, spiritual glow of cathedral stained glass." \
  "Gemini 3.5 Flash" "The Celestial Lighthouse"

queue_job  9 \
  "A dramatic illustrative scene inside a mythical cavernous forge, depicted in a unique Stained-Glass Woodcut Expressionism style. A colossal stone anvil sits in the center, surrounded by rivers of molten, incandescent orange and brilliant yellow magma that flow through deep channels in the rock. The entire environment is constructed from thick, deliberate black ink borders that compartmentalize the glowing liquid stone from the cold, dark obsidian walls. Tendrils of thick gray smoke rise in geometric spirals toward the cavern ceiling, catching the fierce under-lighting. A massive, stylized hammer rests against the anvil, its surface showing deep, woodcut-style grain and metallic gold glass inlay. The lighting is intensely theatrical, with deep, heavy shadows filling the recesses of the cave, contrasted sharply against the blinding, radiant warmth of the molten glass rivers." \
  "Gemini 3.5 Flash" "The Forge of the Mountain King"

queue_job 10 \
  "A breathtaking underwater landscape showcasing an ancient coral reef, envisioned in a vivid Stained-Glass Woodcut Expressionism manner. Gigantic, stylized fan corals and anemones are rendered as intricate networks of glowing pink, electric teal, and deep amethyst glass panes, each section sharply divided by heavy, chiseled black outlines. A school of abstract, angular fish with scales made of golden glass fragments glides through the water, leaving a trail of tiny, glowing bubbles. The deep ocean background is a mosaic of shifting blues, from translucent aquamarine to deep, opaque navy, creating a sense of immense depth. Light filters down from the surface in sharp, defined geometric shafts, illuminating the hand-carved textures of the reef. The composition balances the heavy weight of dark, block-printed shadows with the ethereal, glowing brilliance of the neon marine life." \
  "Gemini 3.5 Flash" "The Deep Sea Coral Cathedral"

# --- ChatGPT — Chromatic Echo Engraving ---
queue_job 11 \
  "An original illustrative style defined by ultra-fine engraved linework fused with translucent glass-like color fields, where every object appears carved and illuminated from within. A dense forest composed of towering crystalline trees, each trunk etched with intricate topographic lines that ripple like memory patterns. Leaves resemble layered stained-glass shards, refracting soft prismatic light across the scene. The ground is a mosaic of reflective surfaces, capturing fragmented reflections of the sky and trees. Subtle glowing droplets hang midair, as if time has paused rainfall. Color palette blends muted emerald, pale amber, and hints of iridescent cyan. Lighting is diffused and internal, creating a luminous depth. Highly detailed, surreal yet natural, with a tactile etched-glass aesthetic that feels both ancient and futuristic." \
  "ChatGPT" "Glass Forest That Remembers Rain"

queue_job 12 \
  "An original illustrative style defined by ultra-fine engraved linework fused with translucent glass-like color fields, where every surface appears delicately carved and softly illuminated. A solitary astronomer sits inside a vast observatory shaped like a hollow crystal sphere, surrounded by floating celestial instruments. Instead of stars, the sky is filled with faint glowing symbols and delicate waveforms, representing silence rather than sound. The figure's robes are etched with flowing patterns resembling star maps. Glass-like panels drift around, each containing fragments of constellations rendered in refracted light. The palette uses deep indigo, violet gradients, and subtle gold accents. Light behaves as if passing through layered crystal, bending and echoing across surfaces. Atmosphere is contemplative, abstract, and poetic, with extreme detail and a sense of quiet infinity." \
  "ChatGPT" "The Astronomer Who Catalogued Silence"

queue_job 13 \
  "An original illustrative style defined by ultra-fine engraved linework fused with translucent glass-like color fields, giving everything a carved, luminous quality. A massive floating water droplet contains an entire miniature city suspended within it. Buildings are sculpted like delicate glass structures, etched with architectural patterns and fine ornamental lines. Streets curve organically, following the internal flow of the droplet. Light refracts through the outer surface, bending and distorting the city inside into layered reflections. Tiny airborne particles shimmer like dust caught in sunlight. The palette includes soft aquamarine, pale gold, and subtle pink highlights. The outer environment is minimal and dark, emphasizing the glowing droplet. The style creates a surreal balance between fragility and complexity, with hyper-detailed textures and fluid geometry." \
  "ChatGPT" "City Built Inside a Droplet"

queue_job 14 \
  "An original illustrative style defined by ultra-fine engraved linework fused with translucent glass-like color fields, where surfaces appear both carved and delicately glazed. A colossal humanoid figure lies beneath a stylized ocean, visible through semi-transparent porcelain-like waves. The waves are composed of layered, etched patterns resembling ceramic cracks and flowing motifs. The giant's body is covered in intricate engraved symbols and faint glowing veins, as if made from luminous stone or glass. Light filters from above, refracting through the water layers and creating soft distortions. The palette features milky whites, soft blues, and subtle opalescent hues. The entire composition feels calm yet monumental, with a strong contrast between the delicate wave textures and the massive figure below." \
  "ChatGPT" "The Sleeping Giant Beneath Porcelain Waves"

queue_job 15 \
  "An original illustrative style defined by ultra-fine engraved linework fused with translucent glass-like color fields, combining organic elegance with intricate craftsmanship. A surreal garden filled with flowers that resemble layered glass sculptures, each petal etched with microscopic patterns. Swarms of mechanical butterflies hover above, their wings made of segmented translucent panels with fine engraved circuitry-like designs. Their movement creates soft trails of refracted light. Stems and vines intertwine in complex, ornamental loops, blending botanical and mechanical aesthetics. The palette mixes soft rose tones, pale greens, and shimmering metallic accents. Light behaves as if traveling through crystal, creating glowing edges and subtle internal reflections. The scene is rich with detail, whimsical yet precise, evoking a fusion of nature, machinery, and delicate artistry." \
  "ChatGPT" "Garden of Mechanical Butterflies"

# --- Grok — Lyrical Etherink ---
queue_job 16 \
  "In the distinctive Lyrical Etherink illustrative style, delicate flowing ink lines shimmer with ethereal inner light, interwoven with soft pastel gradients and intricate symbolic motifs that feel both hand-crafted and luminous. Create a square composition of an enchanted garden where ancient roses bloom with translucent petals revealing tiny galaxies inside, vines twist into poetic runes that glow softly, fireflies trace golden calligraphy in the air. Layered transparency and whimsical details give dreamlike depth, luminous edges on every leaf and petal, masterful balance of fine linework and watercolor-like washes in teal, rose gold, lavender and warm ivory tones, highly detailed yet airy and magical, masterpiece quality illustration." \
  "Grok" "Whispers of the Veil Garden"

queue_job 17 \
  "In the distinctive Lyrical Etherink illustrative style, delicate flowing ink lines shimmer with ethereal inner light, interwoven with soft pastel gradients and intricate symbolic motifs that feel both hand-crafted and luminous. Depict a mechanical orrery floating in a star-filled void, brass gears and cogs formed from constellation lines, planets as glowing crystal orbs with tiny civilizations visible inside, delicate chains of ink turning into comet trails. Use layered transparency, luminous edges, and whimsical narrative details in deep indigo, copper, pearl white and aurora accents, intricate linework blending with soft ethereal washes, captivating and original square illustration." \
  "Grok" "The Clockwork Constellation"

queue_job 18 \
  "In the distinctive Lyrical Etherink illustrative style, delicate flowing ink lines shimmer with ethereal inner light, interwoven with soft pastel gradients and intricate symbolic motifs that feel both hand-crafted and luminous. Illustrate an underwater kelp cathedral with towering translucent arches made of woven seaweed and coral, ancient merfolk silhouettes in prayer, shafts of bioluminescent light piercing through like divine calligraphy. Bubbles form floating runes, fish schools create living patterns, use soft aquamarine, pearl, violet and gold palette with masterful transparency layers and glowing ink edges, dreamy and highly detailed square scene." \
  "Grok" "Echoes Beneath the Kelp Cathedral"

queue_job 19 \
  "In the distinctive Lyrical Etherink illustrative style, delicate flowing ink lines shimmer with ethereal inner light, interwoven with soft pastel gradients and intricate symbolic motifs that feel both hand-crafted and luminous. Show a lone figure on a misty mountain peak weaving giant glowing lanterns that float upward carrying stories, surrounded by cloud islands with miniature temples, birds with ribbon tails, delicate ink threads connecting everything. Soft misty palette of sage, peach, sky blue and warm amber, luminous edges, layered transparency and poetic atmosphere in this original square illustration." \
  "Grok" "The Lantern Weaver of Floating Peaks"

queue_job 20 \
  "In the distinctive Lyrical Etherink illustrative style, delicate flowing ink lines shimmer with ethereal inner light, interwoven with soft pastel gradients and intricate symbolic motifs that feel both hand-crafted and luminous. Create an abstract composition of a dissolving grand library where books transform into flocks of glowing paper birds, pages become floating islands of text and illustration, ink rivers flow between shelves suspended in twilight space. Use intricate symbolic details, masterful transparency, luminous edges in muted sepia, teal, rose and golden highlights for a whimsical, contemplative and visually striking square artwork." \
  "Grok" "Memory Fragments of the Forgotten Library"

# --- Copilot — Chromaflow Etching ---
queue_job 21 \
  "A surreal forest scene where trees bend like flowing ribbons, their bark shimmering in gradients of teal, magenta, and gold. Ethereal spirits drift between trunks, glowing softly with translucent wings. The ground is covered in luminous moss that pulses like veins of light, while the sky above swirls with abstract geometric clouds. The illustrative style emphasizes fluid outlines, layered textures, and bold color contrasts, creating a dreamlike atmosphere that feels alive yet otherworldly. Chromaflow Etching style." \
  "Copilot" "Whispering Forest Spirits"

queue_job 22 \
  "An imaginative marketplace floating among stars, with stalls built from crystalline shards and fabrics woven from nebula dust. Merchants are depicted as whimsical beings with elongated forms, their faces hidden behind ornate masks. The scene bursts with jewel-toned colors, each object outlined in sharp mosaic-like fragments. The illustrative style blends stained-glass geometry with cosmic surrealism, making every detail shimmer as though lit from within. Chromaflow Etching style." \
  "Copilot" "Celestial Market Bazaar"

queue_job 23 \
  "A fantastical garden where flowers sprout gears instead of petals, and vines coil around copper pipes. Butterflies with stained-glass wings hover above, their bodies made of clockwork. The illustrative style uses bold ink outlines with radiant bursts of watercolor-like flares, merging mechanical precision with organic chaos. The composition balances symmetry and spontaneity, creating a vibrant fusion of nature and invention. Chromaflow Etching style." \
  "Copilot" "Mechanical Garden Bloom"

queue_job 24 \
  "A vast ocean painted in sweeping strokes of indigo and silver, with waves shaped like cascading calligraphy. Strange dreamlike creatures rise from the depths — fish with lantern eyes, whales carrying floating islands on their backs. The illustrative style emphasizes sketch-like fluidity, glowing highlights, and layered translucence, evoking a sense of drifting through memory and imagination. Chromaflow Etching style." \
  "Copilot" "Ocean of Forgotten Dreams"

queue_job 25 \
  "An endless desert where dunes ripple like fabric folds, each grain of sand illustrated with delicate shading. Towering monoliths emerge, carved with abstract symbols that glow faintly. Nomadic figures wander with cloaks billowing, their shadows stretching into surreal patterns across the ground. The illustrative style combines soft velum-like shading with sharp mirage distortions, creating a hauntingly beautiful landscape of mystery and silence. Chromaflow Etching style." \
  "Copilot" "Desert of Shifting Echoes"

# --- Mistral — (inline style descriptions per prompt) ---
queue_job 26 \
  "A cosmic jellyfish floats in a void of deep indigo, its translucent tendrils glowing with bioluminescent neon ink — vibrant pinks, electric blues, and lime greens — dripping and swirling as if suspended in liquid space. The style mimics traditional East Asian ink wash painting, but the ink is alive with neon energy, bleeding into the darkness like a galaxy of watercolors. Delicate brushstrokes create a sense of movement, while the jellyfish's bell pulses with a soft, ethereal light, casting ripples of color across the abyss. The background is a gradient of midnight blue to black, speckled with tiny, distant stars that resemble splattered ink." \
  "Mistral" "Cosmic Jellyfish"

queue_job 27 \
  "A human figure, half-translucent and half-opaque, is composed entirely of fractured glass shards in a kaleidoscope of colors — cobalt, ruby, emerald, and gold. The shards refract light in impossible ways, creating a surreal, dreamlike effect where the figure's form shifts between solid and liquid. The background is a misty, soft-focus landscape of rolling hills, but the hills are also made of glass, catching and bending light into prismatic rainbows. The style blends the precision of stained glass with the fluidity of a fever dream, every edge sharp yet every form fluid." \
  "Mistral" "The Shattered Dreamer"

queue_job 28 \
  "A stormy sky where clouds, lightning, and rain are not painted but stitched — thick, textured threads of silver, navy, and violet weave in and out of the canvas, creating a tactile, almost 3D effect. The lightning bolts are embroidered in metallic gold thread, glowing against the dark fabric of the sky, while raindrops are tiny, raised French knots. The horizon is a jagged edge of embroidered mountains, their peaks stitched in deep crimson and forest green. The style feels like a living tapestry, where every element has weight and texture, as if you could reach out and unravel the storm." \
  "Mistral" "Threaded Storm"

queue_job 29 \
  "Ancient Greek statues, but instead of stone, they are carved from liquid marble — smooth, flowing, and semi-transparent, as if the material is in the process of melting or reforming. The figures are caught in a moment of transformation, their limbs stretching and dripping like wax, yet retaining their classical beauty. The background is a polished obsidian surface, reflecting the statues in a mirror-like sheen. The style blends the solidity of sculpture with the fluidity of liquid, creating a paradoxical sense of permanence and motion." \
  "Mistral" "Melting Monuments"

queue_job 30 \
  "A phoenix, mid-flight, is sketched in bold, expressive charcoal lines on a textured paper background. But the charcoal is not static — it glows with embers, as if the lines themselves are burning, leaving trails of orange and red sparks in their wake. The wings are a flurry of feathered strokes, some smudged and blurred by the heat, while the tail is a cascade of fiery charcoal dust. The background is a dark, ashy gray, but cracks of golden light break through, suggesting the rebirth within the destruction. The style is raw, dynamic, and alive, as if the drawing is both the artist and the art." \
  "Mistral" "Phoenix in Flight"

# --- Qwen 3.6 Plus — Moiré Stipple-Vellum Weave ---
queue_job 31 \
  "An illustrative masterpiece executed in the Moiré Stipple-Vellum Weave style, depicting a single, fully bloomed lotus flower. The artwork is constructed entirely from thousands of microscopic, overlapping geometric stipple marks on a textured, translucent ivory vellum background. The petals emerge not from solid fills, but from the varying density and color layering of these tiny dots, creating a luminous, vibrating moiré effect. The color palette features deep indigo shadows transitioning into vibrant magenta and soft peach highlights. The tactile, grainy texture of the vellum is highly visible, contrasting with the sharp, mathematical precision of the stippling. Stark white negative space defines the crisp edges of the leaves, giving the organic floral form a structured, almost architectural quality that stands out dramatically from typical smooth AI-generated illustrations." \
  "Qwen 3.6 Plus" "Blooming Lotus Floral Study"

queue_job 32 \
  "An intricate illustration of a disassembled vintage pocket watch, rendered exclusively in the Moiré Stipple-Vellum Weave style. Every gear, spring, and delicate cog is formed by thousands of microscopic, overlapping geometric stipple marks set against a heavily textured, translucent ivory vellum background. The metallic surfaces are simulated through dense clusters of oxidized copper and brushed brass dots, while the glass face is suggested by sparse, shimmering silver specks that create a subtle, vibrating moiré effect. The intricate mechanical details rely on stark white negative space to define their crisp, sharp edges. The tactile, fibrous grain of the vellum paper remains prominently visible, contrasting beautifully with the rigid, mathematical precision of the stippled mechanics, transforming a mundane object into a vibrant, textured, and highly original illustrative study." \
  "Qwen 3.6 Plus" "Vintage Pocket Watch Mechanics"

queue_job 33 \
  "A sweeping mountain landscape illustration crafted entirely in the Moiré Stipple-Vellum Weave style. The jagged peaks and rolling valleys are not drawn with continuous lines but are built from thousands of microscopic, overlapping geometric stipple marks on a textured, translucent ivory vellum background. The distant misty mountains use sparse, pale cerulean dots to create a luminous, vibrating moiré effect, while the foreground forest is densely packed with deep emerald and charcoal specks. The tactile, fibrous grain of the vellum is highly pronounced, grounding the ethereal dot-work in a physical, tactile reality. Stark white negative space carves out the sharp, crystalline edges of the snowy peaks, merging the organic beauty of nature with a rigid, mathematical illustration technique that feels entirely unique and visually striking." \
  "Qwen 3.6 Plus" "Misty Mountain Landscape"

queue_job 34 \
  "A hyper-detailed close-up of a human eye, illustrated strictly in the Moiré Stipple-Vellum Weave style. The complex iris is a mesmerizing vortex of thousands of microscopic, overlapping geometric stipple marks, radiating outward in vibrant amber and burnt sienna. The translucent vellum background provides a textured, ivory canvas, allowing the dense clusters of dots to create a luminous, vibrating moiré effect around the pupil. The eyelashes and skin contours are defined purely by the strategic absence of ink, utilizing stark white negative space to carve crisp, sharp edges against the stippled shadows. The visible, fibrous grain of the vellum paper adds a raw, tactile quality, contrasting with the precise, mathematical dot-work to produce a deeply original, visually arresting portrait that completely defies standard illustrative conventions." \
  "Qwen 3.6 Plus" "Human Eye Portrait"

queue_job 35 \
  "A bustling nocturnal city skyline, conceptualized entirely through the Moiré Stipple-Vellum Weave style. The towering skyscrapers and illuminated windows are constructed from thousands of microscopic, overlapping geometric stipple marks on a heavily textured, translucent ivory vellum background. The night sky is a deep, vibrating moiré of indigo and violet dots, while the glowing city lights emerge as dense, luminous clusters of cyan and gold specks. The architectural edges are razor-sharp, defined by stark white negative space cutting through the stippled shadows. The prominent, fibrous grain of the vellum grounds the urban geometry in a tactile, physical medium. This unique fusion of mathematical precision and organic paper texture transforms a standard cityscape into a highly original, visually explosive illustrative artwork." \
  "Qwen 3.6 Plus" "Nocturnal City Skyline"

# --- GLM 5.1 — Glowing Epoxy Linocut ---
queue_job 36 \
  "Art created in the style of Glowing Epoxy Linocut. A crashing ocean wave frozen in time, rendered with deep, bold, matte-black carved linocut grooves defining the shape and foam. The negative spaces between the carved lines are filled with thick, hyper-glossy, translucent epoxy resin in vibrant shades of glowing cyan, deep ocean blue, and bioluminescent turquoise. The resin has a 3D depth effect, with swirling micro-bubbles catching the light from within. The carved black lines resemble rich, inky woodgrain with a velvety matte texture, creating a striking contrast against the glass-like, luminous resin. The overall composition feels like a traditional woodcut print fused with modern glowing resin art, emphasizing texture, depth, and brilliant luminescence against stark carved shadows." \
  "GLM 5.1" "Tidal Resonance"

queue_job 37 \
  "Art created in the style of Glowing Epoxy Linocut. An intricate composition of interlocking celestial gears and astronomical instruments, designed using thick, dramatic, matte-black carved linocut lines. The bold grooves cut through the surface like dense charred wood. The open spaces within the gears and arcs are filled with lustrous, translucent epoxy resin in glowing amber, cosmic magenta, and stellar gold. The resin appears to have immense physical depth, with a hyper-glossy, glass-like finish that reveals tiny swirling stardust and internal reflections suspended inside. The stark contrast between the flat, velvety black carved texture of the lines and the luminous, three-dimensional resin pools creates a mesmerizing optical illusion, merging the rustic nature of traditional block printing with the sleek, radiant quality of modern resin craftsmanship." \
  "GLM 5.1" "Celestial Gears"

queue_job 38 \
  "Art created in the style of Glowing Epoxy Linocut. A coiled serpent wrapped around a barren branch, rendered with aggressive, thick, matte-black carved linocut strokes. The scales and branch are defined by deep, textured grooves resembling rough-hewn woodcut carvings. The voids between the black lines are filled with vibrant, translucent epoxy resin in neon green, radioactive lime, and molten orange. The resin features a hyper-glossy, wet-looking surface that magnifies the internal depth, showing swirling pigment and trapped air bubbles that seem to glow with an inner light source. The intense juxtaposition of the ancient, tactile woodcut aesthetic against the futuristic, liquid-glass resin fill makes the serpent appear both ancient and digitally enhanced, creating an unforgettable visual texture." \
  "GLM 5.1" "Neon Serpent"

queue_job 39 \
  "Art created in the style of Glowing Epoxy Linocut. A towering cyberpunk cityscape at night, structured by heavy, expressive, matte-black carved linocut lines forming skyscrapers, windows, and flying vehicles. The carved lines possess a rough, gouged wood texture that absorbs light. The architectural negative spaces are injected with glowing, translucent epoxy resin in electric pink, ultraviolet purple, and neon blue. The resin pours feature an incredibly glossy, thick finish that simulates a 3D relief, with luminous reflections and swirling nebulous clouds suspended deep within the resin layers. The visual tension between the primal, raw carved black matrix and the sleek, high-gloss, luminescent resin generates a stunning, atmospheric urban landscape that feels like a futuristic relief sculpture." \
  "GLM 5.1" "Midnight Metropolis"

queue_job 40 \
  "Art created in the style of Glowing Epoxy Linocut. An enigmatic female portrait surrounded by intricate, flowing vines and floral motifs, executed with bold, sweeping, matte-black carved linocut outlines. The deep, velvety grooves of the carving mimic traditional woodblock printing, providing a rugged, textured foundation. The hollows of the eyes, lips, and surrounding botanical elements are filled with deep, translucent epoxy resin in rich ruby red, glowing sapphire, and ethereal violet. The resin boasts a thick, glassy, domed surface that creates a profound sense of 3D depth, revealing internal light refractions and delicate swirling patterns beneath the glossy coat. The dramatic interplay between the flat, light-absorbing carved lines and the vibrant, light-emitting resin pools transforms the portrait into a captivating, tactile masterpiece." \
  "GLM 5.1" "Oracle of the Woods"

# --- Kimi K2.6 Thinking — Chromatic Meridian Etching ---
queue_job 41 \
  "An abstract composition of flowing organic forms and geometric voids, rendered in Chromatic Meridian Etching style. Fine prismatic lines arc and intersect across the surface, shifting from deep indigo through violet to amber and crimson based on their directional flow. Dense cross-hatching creates zones of visual gravity while open areas breathe with soft watercolor washes in muted teal and rose. The lines follow invisible energy currents, pooling into luminous nodes that pulse with concentrated pigment. Aged cream paper texture provides warmth beneath the intricate network. Subtle gold flecks scatter across the lower quadrant like fallen stardust. The overall composition balances mathematical precision with organic spontaneity, creating a meditative visual rhythm that invites prolonged contemplation of light and line interplay." \
  "Kimi K2.6 Thinking" "Resonance of Silence"

queue_job 42 \
  "A towering ancient forest scene rendered in Chromatic Meridian Etching style. Massive tree trunks rise as vertical pillars of intersecting prismatic lines, their bark etched in directional strokes that shift from umber at the base through moss-green to sky-blue at the canopy. Root systems spread across the forest floor as dense networks of fine crimson and gold threads penetrating dark earth. Ferns and undergrowth emerge through delicate stippling and soft viridian watercolor washes that bleed slightly beyond their etched boundaries. Shafts of light filter through branches as pale amber washes with suspended gold flecks. The background dissolves into atmospheric blue-gray haze. Every line follows the natural growth energy of the forest, creating a living diagram that feels both scientifically observed and spiritually awakened." \
  "Kimi K2.6 Thinking" "Ancient Forest Memory"

queue_job 43 \
  "A contemplative figure seated at a desk covered in scrolls, rendered in Chromatic Meridian Etching style. The person's form is constructed from flowing prismatic lines that map muscle and bone like luminous anatomy, shifting from warm coral through violet to cool teal along the body's natural meridians. Their face emerges from delicate cross-hatching with eyes as pools of concentrated indigo wash. The desk and scattered maps dissolve into networks of fine gold and silver threads representing dream pathways. Soft watercolor shadows in dusty mauve and sage pool beneath the figure. The background is aged parchment with faint grid lines. Gold flecks drift in the upper air like captured thoughts. The overall mood balances scholarly precision with ethereal mystery." \
  "Kimi K2.6 Thinking" "The Cartographer of Dreams"

queue_job 44 \
  "A fantastical observatory dome perched on a craggy cliff, rendered in Chromatic Meridian Etching style. The building's stone and metal surfaces are defined by sweeping prismatic lines that follow architectural stress and celestial alignment, shifting from iron-gray through copper to celestial blue. The dome's aperture reveals a star field rendered as dense constellations of fine gold and white etched points connected by luminous threads. Telescope mechanisms emerge as intricate mechanical filigree in brass and silver tones. The cliff face below is mapped with topographic lines in deep umber and forest green with soft watercolor mist. Aged paper texture grounds the composition while scattered gold flecks suggest cosmic dust. The scene merges scientific architecture with mystical astronomy." \
  "Kimi K2.6 Thinking" "Observatory of Forgotten Stars"

queue_job 45 \
  "A giant luna moth resting upon an open book in a moonlit library, rendered in Chromatic Meridian Etching style. The moth's wings spread as vast planes of delicate prismatic lines radiating from its body in waves of emerald, sapphire, and pearl, each vein a precise etched channel. The book's pages dissolve into flowing text rendered as abstract calligraphic threads in sepia and ink-black. Moonlight streams through a window as pale silver-blue washes with suspended gold flecks dancing in the beam. Bookshelves recede into shadow through layered cross-hatching in deep plum and indigo. The moth's antennae arc as fine gold filaments. Soft watercolor blooms at wing edges suggest bioluminescence. Aged paper texture unifies the scene with quiet nocturnal intimacy." \
  "Kimi K2.6 Thinking" "Moth Reading by Moonlight"

# --- Deepseek — mixed per-prompt styles ---
queue_job 46 \
  "A dimensional papercraft illustrative style with layered cut-paper shapes casting soft shadows, each leaf and branch meticulously folded from textured handmade paper in muted emerald, ochre, and dusty rose. The scene shows a secret forest clearing where a deer made of concentric paper spirals stands beside a stream represented by rippled blue strips. Tiny paper flowers punch-cut from vintage book pages dot the mossy floor. Backlighting creates rim light on the paper edges, revealing fibrous details. The composition is flat yet deep, like a pop-up book spread. No digital gradients, only paper textures and cutout silhouettes with slight curling at the corners. The mood is quiet and magical, emphasizing craftsmanship and physical materiality." \
  "Deepseek" "Dimensional Papercraft — Whispering Forest"

queue_job 47 \
  "A neon etch scratchboard illustrative style where black scratchboard grounds are violently etched with glowing neon lines in electric purple, toxic green, and hot pink. The image depicts a nocturnal garden where flowers are made of cracked lightning bolts and vines twist like circuit traces. A central orchid blooms with three glowing filaments that arc electricity between petals. The scratch marks vary from fine hairlines to deep gouges, creating contrast between pure black voids and blinding neon halos. No fills, only contours and cross-hatched energy lines that seem to vibrate. The style mimics hand-scratched copperplate but with futuristic signage glow. The subject is both botanical and cybernetic, existing in a dark room where the garden illuminates nothing but itself." \
  "Deepseek" "Neon Etch Scratchboard — Electric Garden at Midnight"

queue_job 48 \
  "A watercolor bleed abstraction illustrative style using wet-on-wet blooms and gravity-driven pigment runs. The composition shows a surreal landscape where mountains are soft-edged puddles of ultramarine and burnt sienna that bleed into each other without boundaries. Rivers form from uncontrolled drips traveling downward, carrying concentrated magenta sediment. A sky of pale lemon yellow washes into a horizon that dissolves completely. Salt crystals added during drying create starburst textures resembling distant cities. The paper is heavily buckled, with backruns and cauliflowers embraced as features. No hard lines or masking — everything is fluid and accidental-seeming. The subject is a map of a place that cannot exist, where elevation is measured by pigment density and time stopped mid-bleed." \
  "Deepseek" "Watercolor Bleed Abstraction — Melting Topography"

queue_job 49 \
  "A threaded line art illustrative style where continuous single lines loop and weave like embroidery thread on burlap. The image shows an abstract human figure composed entirely of tangled threads that form a portrait from a single unbroken strand. The thread loops into spirals for eyes, cross-stitches for teeth, and French knots for freckles. The line varies in thickness — thick woolen sections for shadows, fine silk strands for highlights. Loose ends curl away into tiny loops that suggest hair or breath. The background is raw linen texture with thread tension lines pulling the fabric slightly. No fills, no shading — only the topology of a continuous line that never lifts from the surface. The subject is memory as a knot you cannot untie, beautiful and frustrating." \
  "Deepseek" "Threaded Line Art — Knot of Ancestors"

queue_job 50 \
  "A chalk pastel smudge illustrative style with heavy finger-blending and deliberate over-smudging on toothy paper. The scene shows a corner where a violinist once played — only their instrument remains, drawn in sharp vivid turquoise and cadmium red, but the musician has been reduced to colorful dust clouds in violet and peach that trail off the edge of the frame. The cobblestones are rough hatchings smeared horizontally to suggest rain. A hat lies upside down, filled with pastel crumbs that form tiny abstract portraits. The style embraces accidental transfer marks, ghost prints from previous drawings, and fixative spray droplets. Colors are high-chroma but muted by smudging into the paper grain. The subject is presence and absence, the act of creating dissolving into atmosphere." \
  "Deepseek" "Chalk Pastel Smudge — Street Musician's Ghost"

# --- ERNIE 5.1 Thinking — Pressed Lightning Herbarium ---
queue_job 51 \
  "A majestic mountain range rendered in the Pressed Lightning Herbarium style, where every ridge and valley is composed of solidified lightning bolts pressed between ancient glass plates. Electric veins of amber, violet, and teal pulse through crystallized rock formations, while the sky above crackles with frozen thunder rendered as delicate filament patterns. Snow caps glow with iridescent metallic sheen like polished bismuth. The entire composition sits on aged parchment with visible herbarium press marks, botanical labels in elegant script framing the edges. Thick impasto edges define each element, creating a tactile three-dimensional quality as if the landscape could be peeled from the page." \
  "ERNIE 5.1 Thinking" "Thunderpeak Silentium"

queue_job 52 \
  "An underwater coral reef rendered in the Pressed Lightning Herbarium style, where coral formations are made of solidified electrical discharges frozen mid-explosion between ancient glass plates. Branching staghorn corals pulse with deep magenta, electric cyan, and molten gold, their surfaces etched with bioluminescent vein patterns resembling capillary maps. Schools of tiny fish appear as delicate filament traces of captured electricity weaving between coral spires. The surrounding water is rendered as translucent amber resin with suspended particles of frozen light. Ocean floor sediment becomes crushed metallic leaf pressed into aged parchment. Botanical labels in Latin frame the composition with elegant copperplate script." \
  "ERNIE 5.1 Thinking" "Abyssal Coral Litanies"

queue_job 53 \
  "A human face portrait in the Pressed Lightning Herbarium style, where skin texture is rendered as layers of solidified electrical currents pressed between glass. Facial features emerge from branching lightning patterns in warm copper, rose gold, and deep plum tones. Eyes contain swirling storm systems of captured light, irises like frozen nebulae with electric filament details. Hair flows as cascading tendrils of amber and violet electricity frozen mid-motion. The background is aged parchment with faint botanical grid lines. Delicate pressed-flower borders frame the portrait. Every wrinkle and contour is defined by luminous veins, giving the face an otherworldly sacred quality as if this person is a specimen of beautiful catastrophic energy." \
  "ERNIE 5.1 Thinking" "The Cartographer's Dream"

queue_job 54 \
  "An abstract geometric composition in the Pressed Lightning Herbarium style, featuring interlocking sacred geometry patterns made entirely of solidified lightning frozen between glass plates. Triangles, hexagons, and spirals radiate in copper, teal, and molten silver, their edges defined by thick luminous veins like kintsugi repaired with electricity. The central mandala pulses with concentric rings of pressed metallic leaf, each layer a different color temperature from warm amber to cool violet. Negative space becomes translucent aged parchment with faint grid lines. Botanical specimen labels mark each geometric form with elegant Latin taxonomy. The overall effect is a mystical scientific diagram of impossible mathematics rendered as a precious pressed herbarium artifact." \
  "ERNIE 5.1 Thinking" "Sacred Geometry Fossil"

queue_job 55 \
  "A dense ancient forest rendered in the Pressed Lightning Herbarium style, where towering trees are composed of solidified lightning bolts pressed between glass, their trunks crackling with frozen electrical veins in deep emerald, burnt sienna, and gold. The canopy above is a web of captured aurora light filtering through branches made of crystallized thunder. Forest floor moss glows as pressed metallic leaf in teal and copper. Ferns unfurl as delicate electric filament traces. Mist between trees appears as translucent resin with suspended light particles. The ground is aged parchment with visible press marks. Botanical labels in elegant script identify each species. The entire scene feels like a sacred specimen of a forest that once burned with holy fire." \
  "ERNIE 5.1 Thinking" "Old Growth Cathedral"

echo "✅ All 55 jobs queued in scheduler"
