#!/usr/bin/env bash
set -euo pipefail


# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Reflections (water, glass, shiny metal objects)
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+29+-+reflections
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5.0 ---
queue_job  1 \
  "Cinematic street photography at night, a lone figure in a trench coat crossing a rain-soaked intersection, neon signs bleeding into the wet asphalt as a near-perfect mirrored reflection beneath their feet. Shot in the style of Wong Kar-wai's color palette and Todd Hido's atmospheric mood, shallow depth of field, 50mm lens compression, amber and cyan neon glow, fine mist in the air, glossy puddle texture catching streaks of passing headlights, moody chiaroscuro lighting, aesthetically pleasing, painterly bokeh, subtle film grain." \
  "Claude Sonnet 5.0" "Rainpuddle Neon Crossing"

queue_job  2 \
  "Serene photographic portrait of a woman sitting at the edge of a calm lake at golden hour, her reflection rendered with glass-like clarity on the water's surface, symmetrical composition splitting the frame. Inspired by the natural light mastery of Annie Leibovitz and the tranquil framing of Gregory Crewdson, soft warm backlight, gentle ripples breaking the mirror image at the edges, fine hair detail, dewy skin tones, misty background, muted earth palette, aesthetically pleasing, high dynamic range, quiet contemplative atmosphere." \
  "Claude Sonnet 5.0" "Still Water Portrait Study"

queue_job  3 \
  "Anime illustration of a silver-haired girl standing before a shattered mirror, each fragment reflecting a different fractured version of her expression, styled after Makoto Shinkai's luminous backgrounds and Studio Ghibli character warmth. Soft cel-shaded lighting, glowing lavender and teal color scheme, delicate linework, sparkling particle effects drifting through the air, detailed school uniform with reflective fabric sheen, dreamy bokeh background, expressive large eyes, gentle wind motion in her hair, aesthetically pleasing, clean vector-like edges, emotional cinematic framing." \
  "Claude Sonnet 5.0" "Mirror Shard Spirit"

queue_job  4 \
  "Oil painting still life of a polished copper kettle and brass candlesticks on a wooden table, their curved surfaces bending warm window light into distorted miniature reflections of the room. Rendered in the rich impasto texture of Chardin and the luminous realism of Johannes Vermeer, thick visible brushstrokes, warm ochre and burnt sienna palette, soft diffused daylight from the left, dust motes suspended in a sunbeam, deep shadow pooling beneath the objects, aesthetically pleasing, classical composition, varnished canvas finish." \
  "Claude Sonnet 5.0" "Chrome Kettle Reverie"

queue_job  5 \
  "Graphite pencil illustration of a hand holding a wine glass against a city skyline, the distorted reflection of skyscrapers curving across the glass's rounded surface. Detailed cross-hatching in the style of architectural sketch artists, fine tonal gradients capturing the transparency and refraction of the glass, soft smudged shading for ambient haze, crisp contour lines defining the hand and fingers, subtle highlights left as untouched paper, aesthetically pleasing, monochrome value study, delicate texture on the tablecloth beneath." \
  "Claude Sonnet 5.0" "Glass Skyline Sketch"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A detailed, crisp macro photograph of a single, pristine raindrop resting on a vivid green leaf. Within the perfect sphere of the droplet, a clear, inverted reflection of a bustling city skyline under a twilight sky is visible, complete with glowing neon lights and skyscrapers. The background shows soft, creamy bokeh of distant streetlights. The lighting is natural and cinematic, capturing the subtle sheen on the leaf surface and the crystal-clear clarity of the water mirror, creating a breathtaking contrast." \
  "Gemini 3.5 Flash" "Mirror of the Soul"

queue_job  7 \
  "A cinematic, wide-angle street photograph taken at night immediately after a heavy downpour. The black asphalt of the deserted city avenue is completely slicked with water, acting as a perfect, smooth mirror. It flawlessly reflects the vibrant pink, electric blue, and warm amber neon signs of the flanking storefronts. A lone figure in a dark trench coat walks away in the distance, their silhouette slightly distorted in the shimmering wet surface. Captured with a shallow depth of field and sharp, realistic lens-flare effects." \
  "Gemini 3.5 Flash" "Rain-Slicked Neon"

queue_job  8 \
  "Vibrant anime style illustration capturing a serene lakeside scene during a dramatic sunset. A young woman stands on a wooden pier, looking down at the perfectly still, glass-like water. The reflection in the lake is incredibly clear, mirroring the brilliant orange and deep purple clouds, along with her own detailed silhouette and long, flowing hair. The colors are highly saturated with radiant backlighting and classic anime celestial aesthetics, featuring tiny, shimmering light particles dancing gently across the mirror-like surface of the quiet, tranquil water." \
  "Gemini 3.5 Flash" "Crimson Sky Reflection"

queue_job  9 \
  "A rich oil painting with thick, textured impasto brushstrokes depicting a polished antique silver chalice sitting on a dark oak table. The shiny, metallic surface of the chalice gleams intensely, catching the warm, soft light from a nearby, unseen fireplace. In the curved, warped reflection of the silver object, the distorted image of a cozy, dimly lit room with bookshelves and a plush armchair is intricately detailed. The color palette is warm, featuring deep ambers, rich browns, and brilliant, bright metallic highlights." \
  "Gemini 3.5 Flash" "The Silver Chalice"

queue_job 10 \
  "A detailed pencil sketch focusing on a pair of classic aviator sunglasses resting on a weathered wooden surface. The metallic wire frames are meticulously shaded with sharp graphite gradients to indicate a reflective sheen. The dark, polished lenses act as a smooth mirror, revealing a highly detailed, hand-drawn reflection of a quiet, sun-drenched beach with distant palm trees and soft, rolling ocean waves. The texture of the wood grain contrasts beautifully with the clean lines and smooth, reflective precision of the glasses." \
  "Gemini 3.5 Flash" "Graphite Mirage"

# --- ChatGPT ---
queue_job 11 \
  "A tranquil lakeside at blue hour, mirror-still water reflecting snow-capped mountains, towering pine forests, and a sky filled with soft violet, indigo, and pale gold clouds. A weathered wooden pier extends into the perfectly calm surface, where subtle ripples gently distort the reflection without breaking its harmony. Tiny lanterns cast warm amber light that doubles across the water. Ultra-realistic photography, cinematic natural lighting, crisp atmospheric depth, rich textures, balanced composition, high dynamic range, elegant color grading, serene mood, aesthetically pleasing." \
  "ChatGPT" "Liquid Mirror at Blue Hour"

queue_job 12 \
  "A close-up view through a rain-covered café window overlooking a lively evening city street. Crystal-clear droplets cling to the glass, each refracting glowing neon signs, colorful umbrellas, passing headlights, and blurred pedestrians into tiny distorted reflections. Warm interior lighting softly illuminates the window frame while cool blues and magentas dominate outside. Photorealistic street photography, shallow depth of field, natural lens characteristics, subtle bokeh, cinematic realism, intricate reflections, highly detailed textures, sophisticated urban atmosphere, aesthetically pleasing, premium editorial quality." \
  "ChatGPT" "Rain on Glass, City Beyond"

queue_job 13 \
  "A graceful anime-style girl stands beside a quiet pond surrounded by blooming cherry blossom trees during sunset. The calm water reflects her flowing outfit, pink petals, lanterns, distant temple roofs, and a sky painted with peach, lavender, and soft turquoise gradients. Gentle ripples create dreamy distortions while floating blossoms connect reality with reflection. Vibrant anime illustration, expressive eyes, delicate linework, luminous lighting, cinematic composition, elegant color harmony, magical atmosphere, highly detailed environment, peaceful mood, aesthetically pleasing." \
  "ChatGPT" "Reflections Beneath the Cherry Blossoms"

queue_job 14 \
  "An elegant oil painting depicting an antique brass violin resting beside a polished silver vase on a dark wooden table. Their gleaming metallic surfaces capture reflections of a nearby stained-glass window, flickering candlelight, and rich velvet drapery, creating complex layers of color and light. Thick expressive brushstrokes, luminous glazing, classical realism blended with impressionistic texture, warm golden highlights contrasting deep shadows, timeless still-life composition, museum-quality craftsmanship, refined atmosphere, visually captivating, aesthetically pleasing." \
  "ChatGPT" "The Brass Violin's Silent Reflection"

queue_job 15 \
  "A finely detailed graphite pencil drawing of an old mechanical pocket watch placed beside a polished steel fountain pen on a smooth reflective desk. Careful shading reveals subtle reflections of both objects across the glossy surface, while soft window light creates gentle gradients, crisp highlights, and realistic metallic sheen. Intricate cross-hatching, controlled pencil textures, exceptional tonal range, masterful perspective, delicate reflections, classical sketchbook craftsmanship, clean composition, quiet contemplative mood, highly refined, aesthetically pleasing." \
  "ChatGPT" "Reflections in Graphite Silence"

# --- Grok 4.3 ---
queue_job 16 \
  "A hyper-realistic photograph of a perfectly still alpine lake at dawn, crystal-clear water mirroring snow-capped mountains, pine forests, and golden sunrise sky with exquisite symmetry. Gentle mist rising, subtle water ripples distorting edges beautifully. Sharp details on wet rocks and foreground dew-covered grass. Professional photography, 8k resolution, cinematic lighting, moody atmosphere, breathtaking natural beauty, highly detailed reflections." \
  "Grok 4.3" "Tranquil Mountain Lake Reflection"

queue_job 17 \
  "Photorealistic close-up of rain-streaked modern glass skyscraper windows at night, vibrant neon city lights and wet streets reflecting in distorted colorful patterns. Water droplets catching light, deep bokeh background with glowing traffic trails. Moody cyberpunk aesthetic, intricate reflections on polished surfaces, dramatic volumetric lighting, ultra-detailed, cinematic color grading, atmospheric urban elegance." \
  "Grok 4.3" "Glass City Rain Reflection"

queue_job 18 \
  "Beautiful anime girl with flowing silver hair standing before an ornate antique mirror in a moonlit cherry blossom garden, her reflection revealing a magical parallel world with floating lanterns and glowing spirits. Shiny metallic hair accessories and glass-like water pond nearby creating layered reflections. Soft pastel colors, intricate details, ethereal atmosphere, Studio Ghibli inspired, dreamy and enchanting composition." \
  "Grok 4.3" "Anime Mirror Realm"

queue_job 19 \
  "Masterful oil painting of a luxurious antique silver teapot and crystal glassware on polished mahogany table, dramatic reflections capturing window light, scattered rose petals and velvet fabric. Rich impasto texture, warm golden hour lighting creating complex metallic and glass reflections. Classical still life composition, exquisite detail, vibrant yet harmonious colors, museum quality masterpiece, timeless elegance." \
  "Grok 4.3" "Oil Paint Still Life Reflections"

queue_job 20 \
  "Highly detailed pencil drawing of a bustling harbor at twilight, sailboats and old warehouses perfectly reflected in calm harbor water. Intricate cross-hatching on shiny metal buoys and glass lighthouse windows, subtle graphite shading creating depth. Foreground wooden pier with ropes and gentle ripples. Atmospheric perspective, masterful realism in monochrome tones, artistic pencil texture, serene maritime beauty." \
  "Grok 4.3" "Pencil Sketch Harbor Reflections"

# --- Copilot ---
queue_job 21 \
  "A tranquil photograph of a mountain lake at dawn, where the water's surface is perfectly still, reflecting the surrounding pine trees and snow-capped peaks like a flawless mirror. Mist drifts across the horizon, softening the edges of the reflection, while the sky transitions from pale lavender to golden hues. The composition emphasizes symmetry, with the natural world duplicated in shimmering clarity. The mood is peaceful and contemplative, inviting viewers to lose themselves in the quiet beauty of nature's reflective harmony." \
  "Copilot" "Mirror Lake Serenity"

queue_job 22 \
  "A nighttime urban scene captured through a rain-speckled window, where neon signs and car headlights blur into dazzling streaks of color. The glass becomes a canvas of reflections, distorting the city's energy into abstract patterns of light. Pedestrians move in shadowy silhouettes, their forms doubled and refracted by the pane. The photograph should highlight contrasts between sharp details and soft glows, creating a cinematic atmosphere that feels alive, vibrant, and slightly melancholic, embodying the essence of modern city reflections." \
  "Copilot" "City Lights on Glass"

queue_job 23 \
  "An anime-style illustration of a young character gazing into a shimmering pond under a starry sky. The water reflects not only their figure but also fantastical elements—floating lanterns, glowing koi fish, and celestial patterns that blur reality and imagination. The scene is vibrant, with rich blues, purples, and golden highlights, evoking wonder and introspection. The reflection becomes a metaphor for inner thoughts and hidden worlds, blending delicate linework with luminous effects to create a magical, aesthetically pleasing anime composition." \
  "Copilot" "Anime Reflections of Dreams"

queue_job 24 \
  "An oil painting of a rustic table adorned with polished silverware and a gleaming brass teapot, where reflections dance across the metallic surfaces. The brushstrokes emphasize texture and depth, capturing warm candlelight flickering in distorted patterns on curved metal. Rich tones of gold, copper, and deep shadows create a dramatic yet intimate atmosphere. The composition celebrates the interplay of light and reflection, transforming everyday objects into a timeless, painterly study of beauty and craftsmanship." \
  "Copilot" "Oil Paint Shimmer on Metal"

queue_job 25 \
  "A detailed pencil drawing of a crystal glass filled with water, placed on a wooden table. The sketch highlights the intricate play of light and shadow, with reflections bending and refracting through the glass's facets. Fine shading captures the subtle distortions of the table's grain and the faint outlines of nearby objects mirrored in the water. The monochrome style emphasizes precision and artistry, turning a simple subject into an elegant study of reflection, balance, and delicate realism." \
  "Copilot" "Pencil Sketch of Glass Reflections"

# --- Mistral ---
queue_job 26 \
  "A crystal-clear alpine lake at dawn, its glassy surface mirroring the snow-capped peaks and the soft pastel hues of the rising sun, with a lone wooden pier extending into the water, creating a perfect symmetrical reflection. The scene is surrounded by lush green meadows dotted with wildflowers, while a gentle mist hovers above the water. Ultra-realistic, cinematic composition, 8K resolution, natural lighting with golden hour glow, depth of field focusing on the pier, photorealistic textures, tranquil and ethereal mood, hyper-detailed foreground and background, subtle ripples on the water surface." \
  "Mistral" "Serene Alpine Lake Reflection"

queue_job 27 \
  "A towering glass skyscraper in a bustling metropolis at twilight, its reflective surface capturing the vibrant neon lights, the deep indigo sky, and the glow of the setting sun. The building's sleek, angular design creates a mesmerizing kaleidoscope of urban reflections, with passing cars and streetlights adding dynamic streaks of light across its facade. Ultra-realistic, cinematic low-angle perspective, 8K resolution, dramatic lighting with high contrast, depth of field, photorealistic textures, metropolitan atmosphere, hyper-detailed glass reflections, sharp contrasts between light and shadow." \
  "Mistral" "Modern Glass Skyscraper Reflection"

queue_job 28 \
  "A neon-lit cyberpunk alley at night, rain-slicked cobblestone streets reflecting the glow of holographic billboards, vibrant storefront signs, and flying cars streaking across the sky in vivid pinks, blues, and purples. A lone mysterious figure in a flowing futuristic coat walks through the scene, their silhouette perfectly mirrored in the puddles below, creating a dreamlike duality. Anime style, dynamic low-angle camera perspective, cel-shaded lighting with high contrast, intricate detailed line art, vibrant saturated color palette, cinematic composition, hyper-detailed urban environment, atmospheric fog." \
  "Mistral" "Cyberpunk Alley Reflection"

queue_job 29 \
  "A classic oil painting of a silver teapot, a delicate glass vase filled with fresh roses, and a polished copper tray arranged on a dark wooden table, their surfaces reflecting the soft golden afternoon light streaming through a nearby window. The scene is rendered in thick, textured brushstrokes, with a warm, earthy color palette and subtle impasto technique creating a tactile depth. Impressionist style, soft natural side lighting, rich layered textures, vibrant yet muted colors, artistic balanced composition, visible expressive brushwork, traditional canvas feel." \
  "Mistral" "Impressionist Still Life with Reflections"

queue_job 30 \
  "A highly detailed pencil sketch of a quiet rainy street at dusk, with cobblestone pavements glistening under the dim golden glow of vintage streetlamps casting long, dramatic shadows. The wet surfaces reflect the flickering light and the silhouettes of old brick buildings, creating a symphony of shadows and highlights across the scene. A lone figure with an umbrella adds a sense of scale and life. Pencil style, intricate cross-hatching, fine meticulous line work, rich monochrome palette, high contrast, textured paper feel, atmospheric moody ambiance, hyper-detailed shading." \
  "Mistral" "Detailed Pencil Sketch of a Rainy Street"

# --- Qwen 3.7 Plus ---
queue_job 31 \
  "A tranquil mountain lake at dawn, perfectly still water reflecting snow-capped peaks and golden sunrise sky in mirror-like clarity. Soft mist rises from the surface, creating ethereal layers between reality and reflection. Pine trees frame the composition on both sides, their dark silhouettes doubled in the glassy water below. Warm amber light bathes the scene, casting long gentle shadows. Photorealistic, ultra-detailed, natural lighting, high dynamic range, serene atmosphere, professional landscape photography, sharp focus throughout, vivid colors, peaceful mood, 8k quality, award-winning composition." \
  "Qwen 3.7 Plus" "Serene Lake at Dawn"

queue_job 32 \
  "Rain-soaked window of a Tokyo café at night, neon signs in pink and cyan reflecting through wet glass droplets. Blurred city lights create bokeh patterns behind the glass surface, each raindrop acting as a tiny lens distorting the urban landscape. Warm interior light contrasts with cool exterior glow. A coffee cup sits on the windowsill, its chrome surface catching reflected neon colors. Moody cinematic atmosphere, shallow depth of field, photorealistic, vibrant color palette, urban nightscape, detailed water droplets, professional photography, atmospheric lighting, contemporary aesthetic." \
  "Qwen 3.7 Plus" "Neon City Through Rain Glass"

queue_job 33 \
  "Anime illustration of a mystical forest pond under full moonlight, crystalline water reflecting a starry sky and ancient twisted trees with glowing silver bark. A young girl in flowing white robes kneels at the water's edge, her reflection showing a spirit version of herself with luminous wings. Fireflies dance above the surface, their golden lights mirrored perfectly below. Soft pastel colors, dreamy atmosphere, Studio Ghibli inspired art style, detailed background, magical ambiance, ethereal lighting, beautiful composition, hand-painted aesthetic, fantasy scene, delicate linework, vibrant yet gentle color harmony." \
  "Qwen 3.7 Plus" "Spirit Pond Under Moonlight"

queue_job 34 \
  "Classical oil painting of an ornate silver vase on a dark wooden table, its polished surface reflecting a window with draped curtains and a bowl of ripe fruit. Rich impasto brushstrokes capture the metallic sheen and subtle color variations across the curved surface. A cracked glass orb beside the vase fragments the reflected light into prismatic colors. Warm chiaroscuro lighting, deep shadows, Dutch Golden Age inspired composition, masterful rendering of textures, luxurious atmosphere, museum quality fine art, dramatic lighting, timeless elegance, detailed still life." \
  "Qwen 3.7 Plus" "Still Life with Silver Vase"

queue_job 35 \
  "Detailed graphite pencil drawing of a crystal glass prism on a windowsill, refracting and reflecting sunlight into intricate rainbow patterns across a wooden surface. Precise crosshatching and smooth gradients render the transparent facets and sharp reflections. A single rose behind the prism appears distorted and multiplied through the glass. Fine architectural lines, photorealistic rendering in pencil, masterful shading, dramatic contrast between light and shadow, delicate details, white paper background, technical drawing precision, beautiful light study, contemplative mood, stunning craftsmanship, hyper-detailed graphite artwork." \
  "Qwen 3.7 Plus" "Prism of Light"

# --- GLM 5.2 ---
queue_job 36 \
  "A breathtaking photorealistic landscape featuring a modern glass cabin sitting at the edge of a perfectly still mountain lake. The cabin's large glass windows reflect the vibrant orange and purple hues of the breathtaking sunset sky. The calm water below mirrors the entire structure and the surrounding pine forest, creating a flawless symmetrical reflection. Golden hour lighting casts warm rays through the trees, highlighting the water's edge and the sleek metallic framing of the cabin. Ultra-detailed nature photography, 8k resolution, stunning cinematic lighting." \
  "GLM 5.2" "Golden Hour Glass Cabin"

queue_job 37 \
  "A stunning macro photography shot of a vintage silver pocket watch resting on a rain-spotted glass table. The highly polished, shiny metal surface of the watch reflects the surrounding neon city lights in a beautiful bokeh effect. Beneath the transparent glass table, blurred colorful streetlights create an abstract reflection. Tiny water droplets on the glass and metal refract the light, adding intricate details. The composition is aesthetically pleasing, with a shallow depth of field, sharp focus on the watch hands, and rich contrast." \
  "GLM 5.2" "Vintage Pocket Watch"

queue_job 38 \
  "A beautiful anime style illustration of a young girl standing in a futuristic cyberpunk alleyway, gazing down at a puddle of water. The puddle perfectly reflects her determined face and the glowing neon signs above. Surrounding her are shiny metallic pipes and floating glass shards that mirror the vibrant blue and pink lights. The water ripples slightly, beautifully distorting the reflection. Highly detailed anime art, cel shaded, studio Ghibli inspired aesthetics, dramatic lighting, vivid colors, and a melancholic yet aesthetically pleasing atmosphere." \
  "GLM 5.2" "Cyberpunk Puddle Reflection"

queue_job 39 \
  "A classic oil painting of a crystal glass vase filled with fresh water resting on a highly polished silver tray. The clear vase and the shiny metal tray cast complex, distorted reflections of a nearby window and a bouquet of vivid red roses. Thick impasto brushstrokes capture the beautiful interplay of light on the wet glass and the metallic surface. The soft ambient light creates a warm, aesthetically pleasing chiaroscuro effect. Rich textures, masterful oil paint blending, and a timeless still life composition." \
  "GLM 5.2" "Crystal Vase Still Life"

queue_job 40 \
  "A highly detailed pencil sketch drawing of an antique brass bell resting on a wet stone slab beside a calm pond. The shiny metal bell clearly reflects the surrounding bare trees, while the still water mirrors the bell and stone perfectly. Intricate graphite shading techniques, precise cross-hatching, and soft smudging create realistic reflections on the glassy water surface and the curved metallic body. Aesthetically pleasing monochrome composition, fine art drawing, delicate lines, and a peaceful, serene atmosphere with subtle paper texture." \
  "GLM 5.2" "Antique Brass Bell"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "Twilight metropolitan skyline mirrored perfectly in a still canal surface, towering glass skyscrapers reflecting warm golden sunset hues and ambient neon glow, ornate shiny metal bridge rails gleaming with chromatic highlights, gentle water ripples distorting city lights into painterly streaks, cinematic street photography, ultra realistic textures, pristine 8k detail, atmospheric mist rolling between buildings, moody volumetric lighting, balanced rule of thirds composition, shot on medium format digital camera, shallow depth of field, photojournalistic aesthetic, crisp reflections, serene captivating urban atmosphere." \
  "Kimi K2.6 Thinking" "Twilight Canal Reflections"

queue_job 42 \
  "Macro studio photograph of vintage perfume bottles arranged on a polished mirrored surface, intricate crystal glass facets catching warm prismatic light, polished silver metal caps reflecting soft natural window illumination, delicate water droplets beading on curved glass creating tiny mesmerizing lens reflections, shallow depth of field isolating elegant translucent forms, pristine 8k detail, soft diffused studio lighting, neutral cream fabric backdrop, luxury product photography aesthetic, hyper realistic material textures, subtle chromatic aberration, pristine mirror reflections, sophisticated still life composition, serene contemplative mood, timeless understated beauty." \
  "Kimi K2.6 Thinking" "Vintage Glass and Metal Still Life"

queue_job 43 \
  "Anime style magical girl standing at the tranquil edge of a vast moonlit lake, her flowing silhouette reflected perfectly in crystal clear still water, glassy surface rippling with ethereal bioluminescent blue light, ornate shiny metal hair ornaments catching bright starlight, surrounding cherry blossom petals gently mirrored below, dreamy cel shaded colors with soft gradients, soft glowing ambient moonlight, intricate symmetrical reflection details, enchanting fantasy atmosphere, aesthetically pleasing centered composition, luminous magical water effects, soft pastel color palette, serene mystical night scene, highly detailed digital illustration, captivating whimsical magical mood." \
  "Kimi K2.6 Thinking" "Moonlit Lake Magical Girl"

queue_job 44 \
  "Masterful oil painting of a grand baroque hall with towering gilded mirrors and massive crystal chandeliers, highly polished marble floor reflecting warm golden candlelight, ornate antique silver metal candelabras gleaming brightly, tall glass window panes casting prismatic rainbows onto reflective still water fountains, rich thick impasto brushstrokes visible, deep warm amber and ultramarine blue palette, classical dramatic chiaroscuro lighting, luxurious velvety textures, masterful balanced composition, museum quality fine art, elegant luminous reflective surfaces, timeless opulent atmosphere, highly detailed traditional painterly rendering, aesthetic monumental grandeur." \
  "Kimi K2.6 Thinking" "Baroque Hall of Mirrors"

queue_job 45 \
  "Detailed pencil sketch of a rain soaked European cobblestone street at dawn, scattered puddles reflecting old ornate shop windows and vintage brass metal lanterns, delicate precise graphite lines capturing complex glass reflections and wet shiny pavement surfaces, fine cross hatching technique for rippling water texture, soft smooth tonal gradations, deep atmospheric perspective, authentic hand drawn aesthetic, monochromatic silver gray palette with subtle highlights, intricate architectural facade details, moody quiet ambiance, masterful draftsmanship, realistic light behavior and shadows, serene reflective moments, beautifully composed urban street scene, timeless nostalgic melancholic feeling." \
  "Kimi K2.6 Thinking" "Rainy Cobblestone Street at Dawn"

# --- Deepseek ---
queue_job 46 \
  "Ultra-detailed photograph of a pristine alpine lake reflecting jagged granite peaks and a lush pine forest, water surface like a flawless mirror with gentle concentric ripples from a distant trout, warm sunset alpenglow painting the snow-capped summits in soft pink and radiant gold, foreground mossy boulders exhibiting sharp granular textures, shallow depth of field artfully blurring the distant shoreline, vibrant yet natural color palette, peaceful contemplative mood, professional nature photography with crisp focus on reflected cloud patterns and floating pine needles." \
  "Deepseek" "Crystal Lake Serenity"

queue_job 47 \
  "Photorealistic image of a polished chrome sphere resting on a reflective black granite surface, mirroring a dramatic cloudy sky and an abstract urban skyline upside down within its curved surface, intricate distortions of light and shadow across the metallic finish, tiny specular highlights creating star-shaped flares, background softly out of focus with muted grays and deep blues, foreground showing the sphere's crisp edge and its own reflection on the glossy stone, hyper-detailed texture of brushed metal base, aesthetically minimalist and strikingly modern." \
  "Deepseek" "Chrome Dreamscape"

queue_job 48 \
  "Anime style illustration of a melancholic young girl with flowing silver hair pressing her palm against a rain-streaked glass window, her transparent reflection superimposed on the gloomy city nightscape outside, glowing neon signs and distant headlights blurring into soft bokeh circles, water droplets tracing tiny paths down the cold pane, delicate line art with vibrant cel-shaded colors, soft lavender and teal tones, large expressive eyes reflecting inner sadness, shiny wet pavement reflections visible through the glass, aesthetically poignant and deeply dreamlike." \
  "Deepseek" "Rainy Window Gaze"

queue_job 49 \
  "Oil painting style of a serene Venetian canal at dusk, historic palazzos and arched bridges reflected perfectly in still emerald water, golden lantern light spilling from windows onto the rippled surface, a lone gondola with a striped pole creating gentle wakes that distort mirrored architecture, evening sky with soft pink clouds and distant campanile, rich impasto brushstrokes with thick paint texture, warm amber and cool ultramarine palette, dramatic chiaroscuro, aesthetically romantic, masterful rendering of glassy water and weathered stone facades with reflections on wet steps." \
  "Deepseek" "Venetian Canal Glow"

queue_job 50 \
  "Pencil sketch drawing of a vintage silver teapot resting on a wooden table, its highly polished convex surface reflecting a distorted window pane and a bowl of fruit beside it, intricate cross-hatching and fine graphite lines capturing specular highlights and deep shadows, soft smudging for gradient transitions on the graceful curved metal, detailed wood grain texture, minimalist composition, realistic shading with a full tonal range, aesthetically classic and elegantly simple, hyper-detailed pencil work with crisp edges and a soft atmospheric background." \
  "Deepseek" "Graphite Teapot Still Life"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A photorealistic close-up of a calm lake at golden hour reflecting a vibrant sunset, the water surface acting as a perfect mirror for the sky, soft ripples distorting the reflection of pine trees, highly detailed water texture, cinematic lighting, serene atmosphere, 8k resolution, sharp focus, masterpiece photography, golden light reflecting on every ripple." \
  "ERNIE 5.1 Thinking" "Still Waters Mirror"

queue_job 52 \
  "A photorealistic macro shot of a polished chrome sphere reflecting a busy city street, distorted urban lights and neon signs visible on the metallic surface, hyper-realistic reflections, studio lighting, bokeh background, high contrast, sharp details, professional product photography, 8k, ray tracing, volumetric lighting, glossy metal texture." \
  "ERNIE 5.1 Thinking" "Chrome Heart Reflection"

queue_job 53 \
  "Anime style illustration of a girl sitting by a glass window in a rain-soaked garden, reflections of colorful flowers and raindrops overlapping on the glass pane, soft pastel colors, lo-fi aesthetic, detailed eyes, emotional atmosphere, Makoto Shinkai inspired lighting, high quality animation art, vibrant yet melancholic mood, 4k." \
  "ERNIE 5.1 Thinking" "Glass Garden Dream"

queue_job 54 \
  "Thick impasto oil painting of a mercury pool reflecting candlelight, swirling brushstrokes creating a liquid metal effect, rich textures, chiaroscuro lighting, baroque style, deep shadows and bright highlights, expressive artistic technique, canvas texture visible, museum quality art, masterpiece, detailed oil paint layers, dramatic composition." \
  "ERNIE 5.1 Thinking" "Mercury and Light"

queue_job 55 \
  "Intricate graphite pencil drawing of an antique silver mirror lying on a wooden table, reflecting a vase of wilting flowers, high contrast shading, cross-hatching technique, detailed paper texture, monochrome, realistic pencil art, fine lines, sketchbook style, artistic composition, soft shading, hyper-detailed drawing, graphite on paper." \
  "ERNIE 5.1 Thinking" "Pencil Sketch of Silence"

# --- LongCat ---
queue_job 56 \
  "A breathtaking photograph of a crystal-clear mountain lake at golden hour, mirror-smooth water perfectly reflecting towering snow-capped peaks and soft cirrus clouds. A lone wooden rowboat sits still in the foreground, its reflection undisturbed. Sunlight glints off the water surface creating delicate sparkles. Shot on a professional DSLR with shallow depth of field, natural colors, National Geographic quality, serene atmosphere, hyper-detailed, cinematic composition. Aesthetically pleasing landscape." \
  "LongCat" "Serene Waterscape Photo"

queue_job 57 \
  "A hyper-realistic photograph of a modern cityscape at blue hour, skyscrapers with mirrored glass facades reflecting soft gradient sunset hues and passing clouds. Wet pavement doubles the glowing neon signs and warm window lights, creating infinite depth. A chrome sculpture in the foreground displays distorted reflections of traffic and pedestrians. Shallow focus, bokeh effects, photorealistic textures, vivid colors, symmetrical composition. Architectural photography style, visually striking and dramatic." \
  "LongCat" "Urban Glass Reflections Photo"

queue_job 58 \
  "A stunning anime artwork of a koi pond at night under a full moon, perfectly still water glowing with silver moonlight reflecting cherry blossom petals floating on the surface. A wooden bridge arches gracefully over the pond, its reflection forming a complete circle. Shimmering water ripples catch the light softly. Beautiful color palette with teal, violet, and gold accents. Studio Ghibli inspired, serene fantasy atmosphere, detailed background, cel-shaded style, aesthetically pleasing composition." \
  "LongCat" "Moonlit Pond Anime Scene"

queue_job 59 \
  "A vibrant oil painting of a winding river at sunset, smooth water reflecting swirling orange, pink, and lavender skies with expressive visible brushstrokes. Tall reeds in the foreground, their silhouettes mirrored perfectly. A small wooden dock extends into the canvas, reflecting soft warm light. Palette knife texture, rich impasto details, glowing atmospheric light, impressionist style reminiscent of Monet. Aesthetically pleasing harmonious color balance and movement." \
  "LongCat" "Riverside Impressionist Oil Painting"

queue_job 60 \
  "An intricate pencil drawing of a futuristic city intersection at twilight, polished chrome buildings and streets reflecting neon lights with incredible precision. Every window, light source, and architectural detail is meticulously captured with cross-hatching and stippling techniques. Rain-slicked surfaces amplify reflections, creating a moody cyberpunk atmosphere. High contrast, dramatic shadows, photorealistic pencil rendering style. Monochromatic with selective color accents, visually stunning and highly detailed." \
  "LongCat" "Mirrored Metropolis Pencil Art"

echo "✅ All 60 jobs queued in scheduler"

