#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: 3 random words → story → illustration
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+26+-+3+random+words+story+illustration
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A giant deep-sea octopus gracefully plays an ornate wooden violin, its eight arms gripping the bow and strings with delicate precision, tentacles glowing faintly with soft blue bioluminescence. Above it floats a large brass lantern emitting warm golden light that ripples through the dark water, illuminating drifting particles and tiny luminous plankton. The octopus is centered, surrounded by swaying kelp and coral silhouettes fading into deep navy darkness. Faint ghostly translucent figures of old sailors drift in the background, listening. The composition balances warm lantern light against cool deep-sea blues, creating dramatic contrast. Highly detailed textures on the violin and octopus skin, painterly brushstrokes, atmospheric haze, cinematic underwater lighting, melancholic yet magical mood, rich color depth, intricate small details throughout the scene." \
  "Claude Sonnet 4.6" "The Cellist of the Abyss"

queue_job  2 \
  "An elderly woman sits at a wooden desk by an open window, typing on a vintage typewriter, papers scattered with handwritten letters. Beside her, a jar of marmalade sits open with a butter knife resting on a slice of toast on a chipped ceramic plate. Through the window, a glowing comet streaks across a deep purple night sky filled with stars, its tail shimmering gold and orange. Warm candlelight illuminates the room, casting soft shadows on floral wallpaper and shelves of books. The woman wears a knitted shawl, her expression peaceful and hopeful. Soft watercolor textures, gentle pastel palette mixed with warm oranges, whimsical storybook illustration style, cozy intimate atmosphere, fine linework, charming hand-drawn details, nostalgic and tender mood throughout the composition." \
  "Claude Sonnet 4.6" "Letters to the Night Sky"

queue_job  3 \
  "A tall anthropomorphic fox dressed in a tailored trench coat and fedora stands alone on an empty subway platform, holding an open bright red umbrella even though he is indoors, water dripping steadily from its edges onto cracked tile floors. Fluorescent lights flicker overhead, casting harsh cyan and white reflections across wet surfaces and rain-streaked windows. In the distance, a subway train's headlights glow faintly through a dark tunnel. The fox's fur is sleek and detailed, eyes sharp and contemplative, posture calm yet mysterious. Steam rises from grates nearby. Color palette dominated by deep blacks, electric blues, and the umbrella's vivid red as the focal accent. Moody cinematic lighting, high contrast shadows, detailed realistic textures, noir illustration style, atmospheric." \
  "Claude Sonnet 4.6" "Platform Nine, Rainy Midnight"

queue_job  4 \
  "A massive translucent jellyfish drifts slowly above golden desert dunes, its gelatinous body glowing softly with internal light, revealing dozens of intricate antique clocks ticking inside its bell and trailing tentacles instead of organs. The clocks vary in size and style, brass gears visibly turning, hands moving at different speeds. Below, rippling sand dunes stretch toward the horizon under a warm orange and pink sunset sky. Long shadows stretch across the sand, emphasizing scale and stillness. The jellyfish casts a faint glow onto the dunes beneath it. Hyperrealistic rendering combined with surreal fantasy elements, soft volumetric lighting, intricate clockwork details, dreamlike atmosphere, vast empty landscape evoking solitude and the passage of time, painterly digital art finish." \
  "Claude Sonnet 4.6" "Timekeeper of the Dunes"

queue_job  5 \
  "An astronaut in a vintage white spacesuit pedals an old rusty bicycle along a winding stone path through a lush overgrown garden built inside a series of interconnected glass domes on the lunar surface. Bright sunflowers, ferns, and climbing vines spill over wooden trellises, contrasting against the gray cratered moonscape visible through the dome's curved glass walls. Earth hangs large and blue in the dark starry sky above. Warm interior lighting from hanging lanterns illuminates the greenery, while the astronaut's helmet reflects sunlight and flowers. Bold flat colors, retro 1970s science fiction poster style, clean linework, optimistic atmosphere, nostalgic charm blending nature and space exploration, vibrant complementary color scheme of green, yellow, and deep space blue." \
  "Claude Sonnet 4.6" "Sunflowers on the Moon"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A lone wanderer in a high-tech cyberpunk cityscape stands under the glowing neon signage of a bustling night market. Clutched in his weathered hand is an ancient, intricate compass, its brass casing clashing with the digital environment. Above him, a massive, holographic umbrella floats lazily in the air, casting a vibrant blue and magenta glow over the wet asphalt streets. Raindrops shimmer as they catch the ambient light, creating a stark contrast between old-world relics and futuristic technology. Cinematic lighting with deep shadows and intense saturation highlights the textures of leather, wet pavement, and polished metal. The composition is a tight medium shot, focusing on the character's reflective expression and the detailed artifacts, captured with a moody, high-contrast digital photography aesthetic." \
  "Gemini 3.5 Flash" "The Neon Nomad"

queue_job  7 \
  "An antique submarine, covered in moss and intricate brass filigree, floats gracefully through a surreal forest of towering, luminous mushrooms. The ocean floor is covered in a soft carpet of glowing spores, illuminating the scene in soft hues of emerald green and violet. Schools of tiny, translucent fish swim among the massive fungal caps, acting like living lanterns in the deep woodland abyss. The water is crystalline, blurring the line between sea and sky, creating a whimsical, dreamlike atmosphere. The art style draws from classic fantasy illustrations with soft, blended textures, rich gradients, and an ethereal glow that covers every surface. A wide shot captures the immense scale of the fungi relative to the small, exploring vessel, emphasizing a sense of quiet wonder and magical discovery." \
  "Gemini 3.5 Flash" "The Silent Voyager"

queue_job  8 \
  "A sun-drenched, mid-century modern living room features a sleek, minimalist wooden table at its center. Perched perfectly on the polished surface is an elegant origami crane, meticulously folded from a textured sheet of bright yellow paper. In the background, a large glass window reveals a vintage, pastel-blue helicopter resting on a private concrete helipad under a clear, bright afternoon sky. The scene is captured in a distinct 1970s Kodachrome film style, characterized by rich, warm color saturation, subtle grain, and high-contrast shadows. Natural sunlight streams through the window, casting long, sharp geometric shadows across the room and highlighting the fine textures of the wood grain and paper folds, creating a nostalgic, cinematic atmosphere." \
  "Gemini 3.5 Flash" "The Mid-Century Modern Escape"

queue_job  9 \
  "A crumbling, medieval stone tower stands precariously on the edge of a jagged cliff, battered by a raging ocean storm below. Perched atop the highest iron spire is a massive, dark raven, its feathers glistening with raindrops as it looks down with piercing, intelligent eyes. In the background, a dramatic lightning strike splits the dark, stormy sky, illuminating a colossal, glowing clock tower built directly into the mountain face, its gears turning slowly against the elements. The style is an aggressive, high-contrast charcoal sketch blended with digital painting, featuring heavy, textured strokes, deep ink blacks, and stark white highlights. The composition is dynamic and tense, capturing the raw power of nature and the dark, moody atmosphere of a gothic fantasy landscape." \
  "Gemini 3.5 Flash" "The Raven's Keep"

queue_job 10 \
  "A sleek, chrome-plated robotic hand gently holds a perfectly preserved, vibrant red rose, creating a striking contrast between cold machinery and delicate nature. Tiny, glowing blue fiber-optic wires weave seamlessly through the flower's petals, pulsating with a soft, digital light as if supplying life to the organic plant. In the background, a large, matte-black billboard displays a glowing, minimalist crescent moon made entirely of white dot-matrix LED lights. The aesthetic is clean cybernetic pop art, characterized by sharp lines, smooth metallic reflections, and a bold, high-contrast color palette of deep black, bright red, and electric blue. The shot is a macro close-up, emphasizing the intricate textures of the polished metal, the soft velvet petals, and the precise geometric layout of the digital background." \
  "Gemini 3.5 Flash" "The Binary Blossom"

# --- ChatGPT ---
queue_job 11 \
  "A forgotten umbrella, a restless lighthouse, and a jar of whispers collided one storm-heavy evening. The umbrella remembered every lightning strike it had ever tasted, glowing faintly with electric veins. Highly detailed surreal coastal scene at night, bioluminescent umbrella absorbing lightning, glowing veins of electricity, ancient lighthouse with organic breathing textures, stormy ocean waves reflecting neon constellations, cinematic lighting, volumetric fog, dramatic clouds splitting with lightning, painterly realism, ultra-detailed textures, moody color grading, fantasy realism, dynamic composition, magical realism atmosphere, subtle particle effects, high dynamic range, sharp focus, intricate details, immersive storytelling." \
  "ChatGPT" "The Umbrella That Remembered Lightning"

queue_job 12 \
  "In a dusty attic, a typewriter, a flock of feathers, and a broken clock conspired to rewrite time. Every keystroke released feathers instead of letters, drifting slowly as the clock ticked backward. Retro-futuristic attic scene, vintage typewriter transforming into feathered mechanical bird, floating feathers forming glowing sentences, broken clock ticking backward with luminous gears, warm nostalgic lighting mixed with neon accents, surreal airborne typography, cinematic perspective, soft depth of field, detailed textures, whimsical sci-fi aesthetic, dreamlike atmosphere, volumetric light rays, intricate mechanical details, high resolution, imaginative storytelling composition, layered visual narrative." \
  "ChatGPT" "The Typewriter That Grew Feathers"

queue_job 13 \
  "Deep within a forest, a mirror, a shadow, and a thorn grew into something unnatural. The mirror devoured shadows cast by twisted trees, growing darker and deeper with each consumed silhouette. Dark fantasy forest scene, eerie mirror with liquid shadow surface, twisted thorny vines, missing shadow effect, glowing contrast between light and darkness, haunting atmosphere, cinematic composition, hyper-detailed textures, gothic aesthetic, fog drifting through ancient trees, subtle horror elements, dramatic lighting, high contrast shadows, intricate environment design, immersive and unsettling mood, fine detail rendering, mysterious storytelling visuals." \
  "ChatGPT" "The Mirror That Ate Shadows"

queue_job 14 \
  "On a quiet afternoon, a teacup, a spoon, and a tiny planet formed an unlikely system. The teacup began to orbit the planet gently, guided by the rhythmic tapping of the spoon like a cosmic metronome. Whimsical storybook illustration, floating teacup orbiting miniature planet, spoon acting as cosmic conductor, suspended droplets of tea forming spheres, soft pastel color palette, dreamy lighting, gentle glow effects, playful surreal physics, cozy interior blending into outer space, hand-painted textures, magical realism, charming and imaginative composition, soft focus edges, high detail, childlike wonder atmosphere, delicate visual storytelling elements." \
  "ChatGPT" "The Teacup That Learned to Orbit"

queue_job 15 \
  "In a towering city, an elevator, a flickering hologram, and a silent crowd shared a strange fate. The elevator no longer stopped — it drifted endlessly between floors that no longer existed. Cyberpunk elevator interior, endless vertical motion, glitching holographic interface, silent futuristic crowd, neon city reflections through transparent walls, abstract architecture bending reality, high contrast lighting, vibrant cyberpunk color palette, ultra-detailed textures, cinematic perspective, immersive sci-fi atmosphere, subtle motion blur, layered reflections, high dynamic range, intricate environment design, surreal vertical infinity." \
  "ChatGPT" "The Elevator That Forgot the Ground"

# --- Grok ---
queue_job 16 \
  "In a surreal nocturnal forest where ancient towering trees with bioluminescent leaves twist under a total solar eclipse sky painted in deep indigos and fiery crimson rims, a solitary hooded wanderer holds aloft an ornate antique brass lantern emitting ethereal golden light beams that pierce the darkness. Soft glowing whispers manifest as visible swirling misty ethereal forms carrying faint ancient runes and forgotten memories floating around the lantern. The scene blends hyper-detailed fantasy realism with dreamlike symbolism, dramatic volumetric god rays cutting through mist, subtle particle effects of floating embers and dew drops, intricate bark textures and moss details on trees, mysterious fog rolling across the forest floor, cinematic lighting with high contrast between the lantern's warm glow and the cool eclipse shadows, magical atmosphere full of wonder and hidden secrets." \
  "Grok" "Lantern Eclipse Whisper"

queue_job 17 \
  "A majestic velvet-textured giant butterfly with iridescent wings shimmering in deep purples and golds hovers gracefully in the center of a dramatic thunderstorm over a stormy mountain peak. Powerful thunderbolts crackle around its delicate form illuminating the scene in electric blues and silvers while the butterfly's wings create swirling protective veils of soft fabric-like energy that deflect rain and wind. Dark ominous clouds swirl dynamically with lightning veins, rain streaks, and mist, the butterfly's antennae glowing like conductors of electricity. Epic fantasy composition with intricate wing patterns resembling ornate velvet tapestries, highly detailed scales and fur textures, cinematic dramatic lighting, moody atmosphere of power and grace, symbolic harmony between delicate beauty and raw natural force, photorealistic yet magical rendering." \
  "Grok" "Thunder Butterfly Veil"

queue_job 18 \
  "A luminous crystal ship with translucent hull carved from gigantic glowing quartz sails through a cosmic sea of stars and nebulae during a shadowy interstellar voyage. Ethereal shadow figures crew the deck, their forms blending into the void as they navigate between floating asteroid crystals and distant glowing galaxies. The ship's sails billow with captured starlight, casting rainbow refractions across the dark expanse. Dramatic perspective from below showing the vessel's intricate engravings and pulsing energy core, deep space background with swirling purple and teal nebulae, shooting stars, and mysterious shadow portals opening in the distance. Hyper-detailed sci-fi fantasy fusion, intricate light refractions, volumetric lighting, epic sense of adventure and mystery." \
  "Grok" "Shadow Voyage Crystal"

queue_job 19 \
  "In a vast golden horizon at sunset, a mystical forge built into a floating island mountain glows with intense ember sparks flying like fireflies. A melodic female bard plays a glowing harp whose strings create visible sound waves that shape and control the molten metal embers into beautiful swirling patterns and musical runes in the air. Dramatic warm orange and red lighting contrasts with cool blue twilight sky, intricate details on the forge anvil, tools, and bard's flowing robes, distant floating islands connected by glowing bridges, rich fantasy atmosphere blending craftsmanship and music, highly detailed textures of molten lava flows, sparks, and musical notation made of light, cinematic masterpiece." \
  "Grok" "Forge Ember Serenade"

queue_job 20 \
  "Within a colossal celestial forge orbiting inside a vibrant nebula cloud of pinks, blues and purples, a giant ethereal blacksmith hammers a mysterious riddle-etched glowing sword on an anvil made of stardust. The hammer strikes send bursts of cosmic energy and question mark shaped sparks that form temporary holographic riddles floating around. Intricate details on the blacksmith's armored form with constellation patterns, the sword blade reflecting entire galaxies, background of swirling nebula gases, distant planets and stars visible through massive forge windows. Epic space fantasy style with dramatic volumetric lighting, god rays piercing nebula dust, ultra-realistic metallic textures and magical energy effects, sense of ancient cosmic mystery and creation." \
  "Grok" "Enigma Nebula Hammer"

# --- Copilot ---
queue_job 21 \
  "A curious fox carrying a glowing lantern wanders through a misty forest at twilight, its amber eyes reflecting the light as shadows dance among ancient trees. The fox pauses near a moss-covered stone, where fireflies swirl like tiny stars, illuminating the path ahead. The lantern glows with an ethereal warmth, guiding the fox deeper into the woods, as if searching for a hidden secret. The atmosphere is magical, blending mystery and serenity, with soft fog curling around roots and branches. The scene feels timeless, a moment suspended between reality and dream, where nature whispers forgotten tales and the fox becomes both guardian and wanderer, embodying the spirit of light in darkness. Mystic Whimsy style, richly detailed fantasy illustration." \
  "Copilot" "The Lantern Fox"

queue_job 22 \
  "A majestic swan made of gleaming brass and silver gears glides across a tranquil lake under a moonlit sky, its mechanical wings unfolding with delicate precision. Ripples shimmer as reflections of stars dance upon the water, blending the organic beauty of nature with the intricate artistry of invention. The swan's eyes glow faintly, hinting at a hidden intelligence, while reeds sway gently in the night breeze. The scene evokes a surreal harmony between machine and life, where time itself seems to pause, and the swan becomes a symbol of elegance, resilience, and the merging of imagination with reality. Dreamlike Surrealism style, painterly digital art, rich tonal depth." \
  "Copilot" "The Clockwork Swan"

queue_job 23 \
  "A colossal tree rises from a crystalline meadow, its branches stretching into the cosmos, adorned with glowing constellations instead of leaves. Beneath its roots, shimmering streams of stardust flow, illuminating the ground with radiant patterns. A lone traveler gazes upward, awestruck by the celestial canopy, where galaxies swirl and comets streak across the sky. The tree pulses with cosmic energy, bridging earth and universe, embodying the eternal connection between life and stars. The atmosphere is serene yet powerful, filled with wonder, as if the tree itself is the heart of creation, breathing light into the infinite night. Celestial Fantasy style, epic scale, volumetric cosmic lighting." \
  "Copilot" "The Starborn Tree"

queue_job 24 \
  "A raven with obsidian feathers perches upon a cracked mirror in a candlelit chamber, its gaze piercing through shadows. The mirror reflects distorted visions of forgotten memories, glowing faintly with spectral light. Gothic arches loom overhead, draped in velvet and cobwebs, while flickering candles cast eerie patterns across the walls. The raven's wings shimmer with hints of midnight blue, as if holding secrets of the unseen. The atmosphere is haunting yet mesmerizing, blending mystery, elegance, and darkness, where the raven becomes both messenger and guardian of hidden truths, embodying the fragile line between reality and illusion. Neo-Gothic Dream style, high contrast shadows, intricate baroque detail." \
  "Copilot" "The Mirror Raven"

queue_job 25 \
  "A gentle elephant floats above a vibrant cityscape, carried by dozens of colorful balloons tied to its back. Children point in awe from rooftops as the elephant drifts gracefully across the sky, casting playful shadows on cobblestone streets below. The balloons shimmer in the sunlight, creating a kaleidoscope of hues against the azure sky. Birds accompany the elephant in joyful flight, weaving patterns around its massive form. The scene radiates whimsy and delight, capturing the spirit of imagination, freedom, and childlike wonder, where the impossible becomes real and the sky itself transforms into a playground of dreams. Whimsical Adventure style, bright saturated palette, storybook charm." \
  "Copilot" "The Balloon Elephant"

# --- Mistral ---
queue_job 26 \
  "A lone hacker in a neon-lit alley, wearing a glowing cybernetic mask, extracts a shimmering data crystal from a floating holographic vault, while a rogue AI dragon made of liquid code watches from the shadows, its eyes flickering with electric blue light. Neon Cyberpunk style, vibrant electric palette, rain-slicked ground, volumetric neon fog, ultra-detailed cybernetic textures, cinematic composition." \
  "Mistral" "Midnight Data Heist"

queue_job 27 \
  "A tiny cottage floats among cotton candy clouds, where a plump baker with flour-dusted wings pulls golden loaves of bread from an oven, as a mischievous fox in a top hat steals a levitating pie, and a river of honey flows beneath the floating islands. Whimsical Fantasy style, pastel sky palette, soft warm lighting, storybook illustration charm, playful character design." \
  "Mistral" "The Cloud Baker's Secret"

queue_job 28 \
  "In a crumbling cathedral, a pale woman in a tattered black dress winds an ancient clockwork heart, its gears dripping with blood, while shadowy figures with hollow eyes emerge from the stained-glass windows, their whispers echoing through the stone halls. Dark Gothic style, dramatic chiaroscuro, deep crimson and charcoal palette, atmospheric decay, highly detailed gothic architecture." \
  "Mistral" "The Clockwork Curse"

queue_job 29 \
  "A giant, translucent jellyfish drifts through a sky filled with musical notes, its tentacles playing invisible harps, as a child with a lantern made of stars dances on a floating island, and the horizon glows with colors that shift like a symphony. Vibrant Surrealism style, dreamlike pastel and vivid color interplay, soft volumetric light, magical realism composition." \
  "Mistral" "Melody of the Spheres"

queue_job 30 \
  "A brass-plated airship, its sails patched with old maps, soars above a stormy ocean, captained by a one-eyed woman in a leather aviatrix cap, while a mechanical parrot squawks warnings of a sea monster made of gears and steam rising from the depths. Steampunk Adventure style, warm bronze and teal palette, dramatic storm lighting, intricate mechanical details, cinematic wide angle." \
  "Mistral" "The Airship's Last Voyage"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A cinematic fantasy realism scene of an ancient, glowing brass lantern resting on wet, uneven cobblestone streets in a quiet, misty village at twilight. The lantern emits a warm, golden light that illuminates the surrounding fog, creating an atmosphere of mystery and nostalgia. Faint, ethereal wisps of light swirl around the lantern, visually representing a forgotten whisper from the past. The background features blurred, silhouetted medieval houses with faintly lit windows. Highly detailed textures on the stones and metal, volumetric lighting, soft shadows, photorealistic rendering, masterpiece, evocative and moody atmosphere, rich color palette of deep blues and warm ambers." \
  "Qwen 3.6 Plus" "The Whispering Lantern"

queue_job 32 \
  "A surreal digital painting of a vast, tranquil desert landscape under a breathtaking, star-filled night sky. In the foreground, a tall, majestic saguaro cactus stands beside an antique, rusted brass telescope pointing directly towards the cosmos. The scene is imbued with a magical realism aesthetic, where the falling stars leave behind faint, glowing musical notes and staves, beautifully visualizing a silent, celestial melody. The desert sand reflects the soft, silvery moonlight, creating a serene and deeply dreamlike atmosphere. Rich, vibrant colors contrast the deep indigo sky with the warm, earthy tones of the desert. Highly detailed, smooth gradients, masterpiece, evocative, ethereal lighting, intricate textures." \
  "Qwen 3.6 Plus" "Desert Starlight Symphony"

queue_job 33 \
  "A macro photographic fantasy scene capturing a delicate, intricately folded paper origami boat floating in a rain puddle on a dark wooden deck. Outside, a fierce, dramatic storm rages with heavy rain and flashes of distant lightning. Resting beside the tiny boat is an antique, glowing magical compass, its needle pointing the way forward with a soft, ethereal blue luminescence. The contrast between the fragile paper and the powerful storm creates a profound sense of brave adventure. Highly detailed water droplets, realistic reflections on the wet wood, volumetric storm lighting, shallow depth of field, masterpiece, moody and atmospheric, cinematic composition." \
  "Qwen 3.6 Plus" "The Storm Navigator"

queue_job 34 \
  "A detailed steampunk illustration set deep within the grand, towering halls of an ancient, dusty library. Sunbeams pierce through high, arched stained-glass windows, illuminating floating dust motes in the quiet air. At the center, a magnificent mechanical clockwork butterfly, crafted from polished brass, copper gears, and delicate glass wings, flutters gracefully between towering wooden bookshelves overflowing with old leather-bound tomes. The intricate gears of the butterfly catch the warm light, creating tiny glints and reflections. The atmosphere is one of quiet wonder and forgotten knowledge. Rich, warm color palette, highly detailed textures, masterpiece, evocative lighting, intricate mechanical details, classic fantasy art style." \
  "Qwen 3.6 Plus" "The Archive Seeker"

queue_job 35 \
  "An ethereal watercolor concept art piece depicting a majestic lighthouse constructed entirely from translucent, glowing crystal, perched on a rugged cliff at the edge of the world. Below, the turbulent, deep blue ocean crashes against the rocks, but as the waves hit the crystal base, the water refracts into a dazzling, vibrant spectrum of rainbow light that illuminates the surrounding mist. The sky is a soft blend of pastel dawn colors. The scene exudes a profound sense of magical tranquility and awe. Soft, flowing brushstrokes, luminous color transitions, highly detailed light refraction, masterpiece, dreamy atmosphere, fantasy landscape, beautiful composition." \
  "Qwen 3.6 Plus" "The Prism Beacon"

# --- GLM 5.1 ---
queue_job 36 \
  "A highly detailed macro shot of a tiny clockwork crab made of polished brass gears, intricate cogs, and slender copper legs, scuttling across a damp, mossy forest floor. On its metallic back, it carefully carries a large, bioluminescent glowing blue mushroom that radiates a vivid ethereal light, illuminating the surrounding emerald ferns and casting long shadows. In the beautifully blurred background, an abandoned, ancient stone lighthouse stands tall among the dense, dark pine trees, its broken beacon seemingly powered by the mushroom's magical glow. Cinematic lighting, volumetric fog, magical realism, intricate mechanical details, glowing spores floating in the night air, hyper-realistic textures, shallow depth of field." \
  "GLM 5.1" "The Clockwork Carrier"

queue_job 37 \
  "A vast, sweeping golden desert under a breathtaking, ultra-detailed starry night sky. In the center, an elderly astronomer wearing a flowing, wind-swept robe stands beside an enormous, ornate brass telescope pointed upwards toward the cosmos. High above the towering sand dunes, a colossal, translucent celestial dragon made of swirling purple nebulae, glowing blue starlight, and cosmic dust soars gracefully across the vibrant Milky Way. The dragon's magical scales shimmer with intense stardust, casting an ethereal cosmic glow over the perfectly rippled sand below. Epic fantasy, magical astronomy, highly detailed, dramatic lighting, cosmic colors beautifully blending with warm desert tones, intricate engravings on the telescope, cinematic composition." \
  "GLM 5.1" "The Celestial Observer"

queue_job 38 \
  "A hauntingly beautiful underwater scene at the bottom of a deep, tranquil ocean. A grand, weathered wooden piano rests on the powdery sandy seabed, heavily encrusted with vibrant, colorful corals and gently swaying anemones. Seated elegantly on the piano bench is an ethereal, ghostly queen wearing a tarnished, ornate golden crown and a flowing, tattered silk gown that drifts gracefully in the gentle current. Her translucent, pale fingers rest on the barnacle-covered keys. Schools of tiny, bioluminescent silver fish swim around her like glowing musical notes. Golden sunbeams pierce through the deep blue water, creating dramatic god rays. Dreamy, melancholic atmosphere, hyper-detailed, underwater photography, magical realism." \
  "GLM 5.1" "The Sunken Symphony"

queue_job 39 \
  "A striking sci-fi historical mashup set on a frozen, desolate exoplanet. A fierce Viking warrior wearing intricately carved wooden and metal armor, alongside a heavy fur cloak, stands defiantly atop a massive, jagged, cracked glacier. He is raising a glowing, runic battle axe toward the sky in challenge. Above him, a colossal, sleek silver alien spaceship with pulsating blue neon engines hovers silently, casting a bright, cold, futuristic light over the icy, wind-swept landscape. Snow flurries swirl violently in the air around the warrior. Dramatic low-angle perspective, intense cinematic contrast between warm organic fur and cold metallic surfaces, hyper-realistic ice textures, epic confrontation, concept art." \
  "GLM 5.1" "The Glacier Encounter"

queue_job 40 \
  "A mystical, seemingly endless library filled with towering wooden bookshelves that reach far into the shadowy ceiling. In the center, a large, ancient, glowing grimoire lies open on an ornately carved wooden reading stand. Curled up peacefully inside the hollowed-out, glowing pages of the book is a magical cat whose fur is made entirely of a swirling, vibrant cosmic galaxy, complete with brilliant twinkling stars and deep purple nebulae. The cat's ethereal tail wraps around its body, emitting a soft, shimmering cosmic dust that floats upward into the dim library air. Warm, golden candlelight from nearby chandeliers contrasts beautifully with the cool, magical starlight of the cat. Whimsical, highly detailed, enchanting atmosphere." \
  "GLM 5.1" "The Astral Feline"

# --- Kimi K2.6 Instant ---
queue_job 41 \
  "A lone juniper tree grows from a floating island of cobalt rock, its roots weaving through crystalline formations. Above, a vibrant nebula swirls in magenta and teal, casting ethereal light across the scene. The tree's gnarled branches reach toward the cosmic clouds, with tiny bioluminescent spores drifting from its needles into the starfield. Deep space backdrop with distant galaxies, volumetric fog around the roots, hyper-detailed bark texture, dreamlike atmosphere, cinematic lighting. Cosmic Botany style." \
  "Kimi K2.6 Instant" "Juniper Nebula"

queue_job 42 \
  "An ancient willow tree stands at the center of a forgotten courtyard, its drooping branches transformed into delicate marionette strings. A weathered wooden puppet with a porcelain face dangles from the lowest branch, dressed in tattered velvet, while the tree's trunk rises like a cathedral spire into a storm-gray sky. Moss-covered stone walls surround the scene, with fireflies illuminating the puppet's empty eye sockets. Atmospheric depth, melancholic mood, intricate wood grain, soft volumetric light filtering through leaves, painterly texture. Gothic Whimsy style." \
  "Kimi K2.6 Instant" "The Willow Marionette"

queue_job 43 \
  "A solitary lighthouse keeper in a wool coat stands on a cliff edge, holding a brass compass that glows with inner moonlight. Behind him, a twisted willow tree leans toward the sea, its branches framing the lighthouse beam cutting through fog. The compass needle points not north, but toward the lighthouse itself, suggesting magic. Waves crash below, bioluminescent plankton in the water, starry night sky with a crescent moon, dramatic chiaroscuro lighting, romantic realism style. Nocturnal Navigation style." \
  "Kimi K2.6 Instant" "The Compass Keeper"

queue_job 44 \
  "A cloaked silhouette stands on the balcony of an ancient observatory dome, looking through a brass telescope. Below, a massive willow tree encircles the building, its branches having grown through broken windows and wrapped around stone columns. The observatory's copper dome is partially collapsed, revealing gears and star charts within. Twilight purple sky with emerging stars, the silhouette backlit by warm lantern light from inside, mysterious and contemplative mood, detailed architectural decay, soft focus background. Silent Observation style." \
  "Kimi K2.6 Instant" "The Watcher's Grove"

queue_job 45 \
  "At the center of a grassy meadow at dawn, a miniature vortex of wind spirals upward from a single dewdrop on a blade of grass. Above, dark thunder clouds gather with visible lightning veins, yet the vortex remains gentle and luminous, capturing the dew within its transparent funnel. Macro perspective with enormous scale contrast, the dewdrop reflecting the storm sky like a lens, surrounding wildflowers bending away from the wind, dramatic dynamic lighting, hyper-realistic nature photography style with fantasy elements. Elemental Convergence style." \
  "Kimi K2.6 Instant" "Storm's First Breath"

# --- Deepseek ---
queue_job 46 \
  "A solitary saguaro cactus stands under a starry desert night sky, its spiny arms reaching upward. From a small crack in its green flesh, a faint glowing whisper materializes as translucent, swirling letters that drift toward a vintage brass lantern resting on the sandy ground. The lantern's glass panels are fogged inside, but a warm amber flame flickers to life, casting long shadows across rippled dunes. The whisper forms ethereal words in an ancient script, weaving around the lantern's handle. In the background, distant mountains are silhouetted against the Milky Way. Shallow depth of field, soft moonlit highlights on the cactus spines, atmospheric haze near the horizon. Surreal Night Photography style." \
  "Deepseek" "Desert Whispers"

queue_job 47 \
  "A massive meteor made of polished brass and copper crashes diagonally into a mechanized garden, shattering the ground into gears and springs. The meteor's surface is covered in ticking clock faces and rivets, with glowing blue energy leaking from its cracks. Surrounding it, giant sunflowers with clockwork stems and golden petal-dials tilt their flower heads, each face displaying a different time. Sparks fly from broken gears on the ground, illuminating a cloudy sky with hints of sunset. Cross-hatching line art, sepia tones with blue highlights, mechanical details, dramatic diagonal composition with falling debris frozen mid-air. Steampunk Illustration style." \
  "Deepseek" "Clockwork Meteor"

queue_job 48 \
  "A single white feather, impossibly large, floats in the center of a dark cosmic void. At its tip, a vintage brass telescope points upward, its lens reflecting a nebula. The feather's barbs are just touching the telescope's eyepiece, and from that contact, an avalanche of miniature stars and crystalline snow cascades downward, creating a shimmering waterfall of light that fills the lower half of the frame. In the background, a quiet mountain range made of frozen constellations sits under a deep purple sky. The feather has delicate, glowing veins. Ethereal, dreamlike lighting with soft focus on the avalanche's leading edge, subtle lens flare around the telescope. Cosmic Surrealism style." \
  "Deepseek" "Feather Trigger"

queue_job 49 \
  "Thick, rolling fog fills a dark forest clearing. In the center, a full-length ornate mirror with a tarnished silver frame stands on twisted roots. The mirror's surface does not show the forest but instead reveals a ghostly violin floating in mid-air, its bow drawn across strings, yet no sound is visible. The fog swirls into the shape of musical notes that drift toward the mirror and disappear into its glass. The violin's wood grain glows faintly green, and four strings vibrate, creating tiny ripples in the fog. Around the mirror, broken music stands lie half-buried in moss. A single beam of moonlight pierces through the trees, hitting the mirror's top edge. Etching-style linework with cross-hatched shadows, monochromatic with a hint of emerald green, eerie silent atmosphere. Mysterious Etching style." \
  "Deepseek" "Foggy Concerto"

queue_job 50 \
  "A translucent dragon-shaped kite soars through a vast floating library under a soft pastel sky. The kite's body is made of rice paper painted with scales that shimmer in gold and teal, and its long tail of ribbons trails behind, brushing against floating bookshelves. The library consists of dozens of wooden shelves suspended by thin chains from nowhere, each shelf packed with colorful books that flutter their pages like birds. Some books have sprouted tiny wings and flutter alongside the kite. A child's hand is visible at the bottom edge, holding the kite string. The background shows distant cloud castles and warm sunlight filtering through the shelves. Watercolor style with visible brushstrokes, bleeding edges, soft gradients, whimsical light-filled composition. Fantasy Watercolor style." \
  "Deepseek" "Dragon Kite Library"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A dramatic cinematic scene of an elderly lighthouse keeper standing at the top of a weathered stone lighthouse at twilight. He wears a rich dark velvet cloak that billows dramatically in the ocean wind. The vast ocean stretches endlessly below, glowing with ethereal bioluminescent waves that pulse like living light. Soft golden light from the lighthouse beam cuts through thick misty air, illuminating swirling fog. The atmosphere is deeply mysterious and melancholic. A starry sky with a crescent moon hangs above. Hyper-detailed painterly style with deep navy blues and warm amber tones. The keeper's weathered face shows profound contemplation as he gazes at the distant horizon, listening to the ocean's eternal whisper. Dark Romantic Cinema style." \
  "ERNIE 5.1 Thinking" "The Keeper's Whisper"

queue_job 52 \
  "An enchanted forgotten garden at midnight where mechanical clockwork flowers bloom with intricate brass and copper petals that open and close rhythmically. Each flower has tiny visible gears and springs glowing with soft amber light from within. Long dramatic shadows stretch across cracked stone pathways, moving as if alive though there is no wind. Ancient stone walls covered in thick moss surround the scene. Fireflies mix with the mechanical glow creating magical light orbs. The style is steampunk fantasy with rich details, warm metallic tones against cool moonlight blue. The atmosphere is surreal and dreamlike, blending organic decay with precise mechanical beauty in a hauntingly gorgeous composition." \
  "ERNIE 5.1 Thinking" "The Clockwork Garden"

queue_job 53 \
  "A majestic lone gray wolf standing on a snowy mountain peak howling at the sky. Above, a breathtaking aurora borealis dances in vivid green, purple, and blue ribbons of light. The wolf's breath crystallizes into tiny diamond-like ice particles that scatter across the pristine white snow, glittering like fallen stars. Crystal formations grow from the ground around the wolf's paws. The scene is captured in a hyper-realistic fantasy style with vivid colors, deep contrasts between the dark wolf silhouette and the luminous sky. Snowflakes drift gently through the air. The composition is epic and awe-inspiring, evoking a sense of ancient wild magic and solitude in the frozen wilderness. Epic Fantasy Realism style." \
  "ERNIE 5.1 Thinking" "The Wolf Beneath the Aurora"

queue_job 54 \
  "A young woman pressing her palm against a rain-streaked mirror in a dimly lit vintage bathroom. Her reflection shows a different version of herself surrounded by floating translucent memory fragments. Behind the glass, vivid scenes from her past appear like ghostly projections: childhood moments, lost lovers, golden afternoons. Rain streams down the window beside the mirror, blurring the city lights outside into bokeh. The style is moody neo-noir with cool blue and warm sepia tones blending together. Water droplets on the mirror create prismatic light effects. Her expression is one of bittersweet recognition. The atmosphere is deeply emotional and cinematic, capturing the fragile boundary between present and past." \
  "ERNIE 5.1 Thinking" "Fragments Behind Glass"

queue_job 55 \
  "A weathered explorer in tattered clothing kneeling in vast golden desert sand, holding a broken compass that spins wildly. Before them, the desert sand ignites with supernatural flames, and from the burning dunes a magnificent phoenix rises with wings of pure fire and golden light. The sky turns deep crimson and orange as embers swirl upward. Heat distortion ripples through the air. The style is epic fantasy illustration with rich saturated warm colors, dramatic lighting, and highly detailed textures on the phoenix feathers and sand grains. The composition is grand and mythological, evoking a sense of divine destiny and ancient power awakening from the earth." \
  "ERNIE 5.1 Thinking" "The Phoenix Compass"

# --- LongCat ---
queue_job 56 \
  "A mesmerizing underwater scene where a scuba diver discovers an ornate golden key embedded in vibrant coral on the ocean floor. The key emits a soft, radiant glow that opens a shimmering portal to a surreal dream dimension. Beyond the portal, floating islands with cascading waterfalls, bioluminescent jellyfish, and fantastical flora are visible. The deep blue ocean is pierced by sun rays, creating a mystical atmosphere. The diver, in awe, reaches toward the key as ethereal light illuminates the scene. Surreal fantasy style, highly detailed, vibrant colors with cinematic lighting, evokes wonder, magic, and the thrill of discovery in an unexplored realm. Ethereal Subaquatic Vision style." \
  "LongCat" "Dream Portal Key"

queue_job 57 \
  "In a dense, ancient forest shrouded in magical mist, a traveler encounters a mystical mirror hanging from a gnarled oak tree. The mirror's surface shimmers, reflecting shadowy visions of possible futures — glimpses of alternate paths and destinies. Tall trees with glowing mushrooms surround the scene, and the traveler, cloaked in curiosity, peers into the glass, seeing silhouettes of what could be. Dark fantasy style, atmospheric, with intricate textures and moody lighting. Colors blend emerald greens, deep shadows, and ethereal glows. Captures mystery, introspection, and the haunting beauty of choices unmade. Enchanted Forest Reflections style." \
  "LongCat" "Mirror of Future Shadows"

queue_job 58 \
  "During a fierce thunderstorm in a neon-lit city, a vibrant peacock feather dances wildly through rain-slicked streets, guided by the wind. It glides past reflective puddles and glowing signs, leading a hopeful child to a hidden doorway emitting warm light. Lightning flashes illuminate the dramatic urban landscape, with blurred buildings and wet asphalt adding dynamism. The child follows the feather with wonder. Cinematic style, high-contrast, photorealistic with magical elements. Colors feature dark blues, electric yellows, and neon accents. Evokes emotion, adventure, and the serendipity of finding magic in chaos. Urban Storm Drama style." \
  "LongCat" "Feather in the Tempest"

queue_job 59 \
  "In a cozy, book-filled attic, an ancient tome lies open, illuminated by a brass lantern's soft amber glow. The pages reveal a detailed map pointing to a majestic, cloud-shrouded mountain peak where dreams are said to manifest. As light hits the parchment, the mountain seems to come alive with ethereal lights and subtle movements. Old artifacts and dusty shelves surround the scene. Warm fantasy style, intricate details, soft lighting, nostalgic ambiance. Colors include amber, brown, white, and magical highlights. Inspires wonder, exploration, and the allure of hidden worlds. Mystical Cartography style." \
  "LongCat" "Lantern-Lit Mountain Revelation"

queue_job 60 \
  "Inside a dilapidated clock tower, a unique rose grows from the intricate gears of a stopped clock, its petals whispering historical secrets. Moonlight filters through broken windows, illuminating the rose's faint glow and detailed petals that show miniature scenes from the past. Ivy covers the silent clock hands, adding to the melancholy charm. Steampunk fantasy style, highly detailed, with a blend of mechanical and botanical elements. Colors are sepia tones, silver, red, and soft glows. Conveys timelessness, mystery, and the poetic intersection of nature and time. Temporal Botanical Whispers style." \
  "LongCat" "Clockwork Rose Secrets"

echo "✅ All 60 jobs queued in scheduler"
