#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt (harmless to generation)
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Fog — photorealistic, aesthetically pleasing fog scenes
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+21+-+fog
# Structure: 10 models × 5 prompts = 50 tasks total
# Note: Grok row was empty on the wiki; ERNIE 5.1 Thinking fills slot 10
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A rain-slicked urban street at dawn, dense silver fog rolling between towering glass skyscrapers, neon signs bleeding soft amber and cyan into wet asphalt below, lone figure with umbrella silhouetted at a crosswalk, steam rising from grated manholes, fog diffusing every light source into luminous halos, photorealistic rendering with sharp foreground detail softening into ethereal blur toward upper distance, dramatic depth of field, desaturated blue-gray palette punctuated by warm sodium streetlamp glow, shallow puddles mirroring ghostly building facades, cinematic atmosphere, ultra-detailed surface textures on concrete and glass, natural bokeh on background elements, early morning stillness, hyperrealistic photography style, volumetric light scattering through suspended moisture particles, muted color grading with selective warm accent tones." \
  "Claude Sonnet 4.6" "Fog City Reflection"

queue_job  2 \
  "Ancient temperate forest at first light, thick white ground fog blanketing the forest floor knee-deep between massive moss-covered oak trunks, golden hour sunbeams piercing forest canopy at steep diagonal angles creating defined volumetric light shafts, dust and spores floating visibly in illuminated columns, fern fronds emerging from fog surface catching backlit dew drops, deep green and gold color palette, extreme photorealistic detail on bark texture and leaf translucency, atmospheric perspective dissolving distant trees into pale gray-white mist, absolute stillness, no wind, mirror-calm forest interior, bokeh clusters of light through dense upper canopy, highly detailed moss and lichen on every surface, cinematic nature photography aesthetic, soft diffused shadows on fog surface, sense of ancient primordial depth, rich earthy tones anchoring composition, hyperrealistic environmental rendering." \
  "Claude Sonnet 4.6" "Forest Morning Fog"

queue_job  3 \
  "Night mountain switchback road, two vehicles descending with bright xenon headlights punching twin conical beams into dense cold fog, headlight cones rendered with full volumetric scattering showing every particle of moisture, road surface wet and reflective catching headlight white and faint taillight red, steep rocky cliff face visible left, sheer drop invisible in fog right, guardrail glistening with condensation, total darkness beyond the lit fog volumes, dramatic high-contrast chiaroscuro, no ambient light except vehicle lights, photorealistic road surface detail with painted lane markings dissolving into fog mid-frame, cinematic tension, cool blue-white light temperature, isolated and desolate atmosphere, hyperrealistic automotive photography quality, subtle lens flare on fog particles nearest camera, rich black shadows with zero detail outside illuminated zones." \
  "Claude Sonnet 4.6" "Mountain Road Headlights Fog"

queue_job  4 \
  "Pre-dawn fishing harbor completely enveloped in flat calm sea fog, weathered wooden and steel fishing vessels moored in rows barely visible as dark silhouettes through dense white mist, single orange dock lantern casting a warm diffused sphere of light in the foreground, ropes and net buoys glistening with condensation droplets, absolute water stillness creating perfect dark mirror reflections of fog and lantern glow below hull waterlines, muted palette of steel blue, ash gray and singular warm amber, photorealistic nautical detail on vessel hulls, rust staining, chipped paint textures, extreme atmospheric depth compression flattening background boats to pure silhouette, documentary maritime photography style, intimate quiet scale, no people present, sense of suspended time before working day begins, hyperrealistic fog density rendering." \
  "Claude Sonnet 4.6" "Harbor Fishing Boats Fog"

queue_job  5 \
  "Solitary weathered wooden park bench on a leaf-strewn path cutting through a mature urban park in mid-autumn, dense morning fog reducing visibility to roughly fifteen meters, fallen leaves in saturated amber orange and deep burgundy carpeting ground in foreground with crisp photorealistic detail, path and bench sharp in foreground gradually dissolving into pure white fog midground, bare black tree trunks fading to gray silhouettes then vanishing completely into mist beyond, single bare branch catching fine water droplet condensation rendered in precise macro detail, desaturated cool background contrasting warm fallen leaf tones, no people, absolute stillness, soft diffused shadowless foggy light with no defined light source, intimate melancholic atmosphere, hyperrealistic autumn leaf texture and vein detail, cinematic fine art photography mood, square compositional balance with bench slightly off-center." \
  "Claude Sonnet 4.6" "Autumn Park Bench Fog"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A dramatic, high-contrast cinematic photograph of a dense, atmospheric fog swallowing a bustling cyberpunk metropolis at twilight. Looming skyscrapers fade into a heavy, charcoal-grey mist, their sharp architectural lines blurred by the thick vapor. Penetrating the deep haze, vibrant neon signs cast intense crimson and electric blue reflections across the wet, reflective asphalt streets below. In the foreground, the glowing red taillights of a sleek, modern vehicle cut sharp streaks through the swirling moisture, creating a luminous, painterly glow. The air is visibly thick with condensation, catching the scattered light to form a rich, layered depth. Shot on a 35mm lens with a shallow depth of field, the image captures a moody, noir-inspired urban landscape, balancing deep shadows with brilliant, localized color accents to deliver an exceptionally clean, photorealistic, and visually striking composition." \
  "Gemini 3.5 Flash" "City Lights in Crimson and Charcoal"

queue_job  7 \
  "An enchanting, photorealistic masterpiece capturing the ethereal beauty of a sun-drenched morning inside a dense, ancient woodland. Thick, milky white fog blankets the forest floor, weaving gracefully between the moss-covered trunks of towering oak and pine trees. Brilliant, golden sun rays pierce through the heavy canopy above, creating sharp, dramatic volumetric light beams that illuminate the swirling vapor. The atmosphere is crisp and tranquil, with individual droplets of moisture glistening in the warm, radiant light. A soft, natural color palette dominated by deep forest greens, rich earthy browns, and luminous amber tones defines the scene. The composition utilizes a low-angle perspective, drawing the viewer into a serene, high-contrast landscape where the powerful interplay of light and heavy mist creates a mesmerizing, deeply atmospheric, and aesthetically pristine visual experience." \
  "Gemini 3.5 Flash" "Golden Hour Forest Radiance"

queue_job  8 \
  "A cinematic, evocative photograph of a solitary stone lighthouse standing resilient against a heavy, rolling sea fog at dusk. The dense, cool-toned mist engulfs the rugged, craggy cliffs, completely obscuring the horizon and blending the turbulent ocean seamlessly into the overcast sky. From the top of the tower, a powerful, warm amber beacon cuts a stark, defined path through the thick, swirling vapor, casting a dramatic cone of light into the darkness. The damp surfaces of the stone structure and surrounding rocks glisten with condensation, reflecting the faint, atmospheric illumination. Capturing a moody, high-contrast aesthetic, the shot balances the deep, dark silhouettes of the coastal terrain with the brilliant, focused glow of the lighthouse lamp, creating a profound sense of isolation, quiet strength, and photorealistic environmental grandeur." \
  "Gemini 3.5 Flash" "Coastal Beacon in the Mist"

queue_job  9 \
  "A sleek, noir-inspired cinematic shot of a massive, industrial suspension bridge enveloped in a dense, heavy midnight fog. The far side of the structure completely vanishes into a deep, dark mist, creating an infinite, mysterious perspective. A single, dark retro-futuristic sports car drives across the wet, glistening steel deck, its sharp halogen headlights projecting long, piercing beams of bright white light that illuminate the swirling moisture ahead. Overhead, subtle, selective blue and purple neon accent lights tracing the bridge's cables bleed softly into the thick vapor, creating a beautiful, diffused glow against the dark, high-contrast shadows. The composition focuses heavily on clean lines and atmospheric depth, delivering an intensely moody, photo-realistic aesthetic that perfectly blends high-tech urban isolation with the natural, softening elements of a heavy nighttime fog." \
  "Gemini 3.5 Flash" "Lone Traveler on the Neon Bridge"

queue_job 10 \
  "A breathtaking, photorealistic landscape photograph capturing the serene isolation of a winding asphalt road cutting through the Scottish highlands during a heavy autumn mist. A dense, low-hanging fog hugs the rolling green and burnt-orange hills, partially veiling the distant mountain peaks in a soft, monochromatic white shroud. A lone, minimalist black modern vehicle is parked on the shoulder of the empty road, its bright red taillights providing a stark, vibrant contrast against the cool, muted tones of the surrounding environment. The air is thick with palpable dampness, with delicate morning dew visible on the roadside ferns and heather. Shot with a wide-angle lens, the composition emphasizes vast, quiet space, utilizing the sharp contrast between the geometric road, the vivid selective color of the lights, and the soft, enveloping texture of the natural fog." \
  "Gemini 3.5 Flash" "Solitude in the Misty Highlands"

# --- ChatGPT ---
queue_job 11 \
  "A photorealistic early morning cityscape wrapped in dense, low-hanging fog, where tall buildings fade into soft gradients of gray and blue. Streetlights glow warmly, their halos diffused into the mist, creating a cinematic atmosphere. A lone pedestrian crosses an empty street, their silhouette partially obscured, adding a sense of quiet isolation. Reflections shimmer on slightly wet asphalt, capturing blurred light streaks from distant traffic. Subtle sun rays attempt to pierce through the fog, forming delicate beams between skyscrapers. The composition balances depth and mystery, with foreground details crisp and background dissolving into haze. Natural color grading with cool tones and warm highlights enhances realism. Captured as if with a full-frame camera, shallow depth of field, ultra-detailed textures, atmospheric perspective, and soft contrast, evoking calm, introspective urban solitude." \
  "ChatGPT" "Silent City Awakening"

queue_job 12 \
  "A serene forest scene enveloped in thick morning fog, where towering trees stretch upward and vanish into the misty canopy. Gentle beams of sunlight filter through gaps in the foliage, creating visible shafts of golden light that illuminate floating particles in the air. The forest floor is rich with moss, fallen leaves, and damp earth, all rendered with intricate photorealistic detail. A narrow path winds softly through the scene, inviting exploration while disappearing into the fog ahead. The atmosphere feels quiet and untouched, with subtle variations in light and shadow enhancing depth. Colors are natural and earthy — greens, browns, and soft golds — blended with the cool gray of fog. Captured with a cinematic lens, soft focus transitions, volumetric lighting, and realistic textures, emphasizing tranquility and the ethereal beauty of nature." \
  "ChatGPT" "Forest Light Through Mist"

queue_job 13 \
  "A dramatic nighttime highway scene cloaked in thick fog, where rows of cars move slowly, their headlights and taillights creating glowing streaks of white and red that dissolve into the mist. The road surface is slightly wet, reflecting light in elongated patterns that add visual rhythm and depth. Street signs and barriers appear faint and ghostly, partially hidden by the dense atmosphere. The perspective is low and slightly angled, enhancing the cinematic feel and guiding the viewer's eye into the distance where visibility fades completely. Light diffusion is key, with each source softly blooming through the fog. The color palette leans toward cool blues and deep blacks, contrasted by warm artificial lighting. Ultra-realistic rendering, motion blur subtly applied, shallow depth of field, and high dynamic range lighting create a moody, immersive atmosphere." \
  "ChatGPT" "Highway Lights in Heavy Fog"

queue_job 14 \
  "A peaceful lakeside setting at dawn, blanketed in soft rolling fog that hovers just above the water's surface. The lake is perfectly still, mirroring faint silhouettes of distant trees that fade gradually into the haze. A small wooden dock extends into the water, slightly damp and textured with realistic details, leading the viewer's gaze into the scene. Early sunlight gently breaks through the fog, casting pastel hues of pink, orange, and gold across the sky and reflecting subtly in the water. The atmosphere is calm and quiet, with a sense of stillness and fresh morning air. Light diffusion softens all edges, creating a dreamlike quality while maintaining photorealistic precision. Captured with a wide-angle lens, soft gradients, natural color transitions, and delicate lighting balance to evoke serenity and quiet beauty." \
  "ChatGPT" "Lakeside Dawn in Mist"

queue_job 15 \
  "A winding mountain road cutting through dense fog at high altitude, where the mist shifts and reveals glimpses of rugged cliffs and distant peaks. The scene is captured during golden hour, with warm sunlight breaking through layers of fog, casting dramatic highlights and long shadows across the terrain. A single car navigates the road, its headlights faintly visible, adding scale and narrative. The fog moves organically, forming soft waves and pockets of visibility that create depth and dimension. The road surface is textured and slightly reflective, enhancing realism. The sky above transitions from warm golden tones to cooler blues, blending seamlessly with the fog below. Shot with a cinematic perspective, high detail, realistic atmospheric scattering, and dynamic lighting, this composition conveys both isolation and awe-inspiring natural beauty." \
  "ChatGPT" "Mountain Road Above the Clouds"

# --- Grok ---
queue_job 16 \
  "A breathtaking photo-realistic landscape of majestic snow-capped mountains partially veiled in thick, swirling morning fog at dawn. Soft golden sun rays pierce through the dense mist creating dramatic god rays and glowing atmospheric haze. Dew-covered pine trees emerge from the fog in the foreground with delicate frost on branches. Cool blue and warm orange tones blend harmoniously in the ethereal light. Ultra-detailed mist particles floating in air, subtle volumetric lighting, peaceful and serene atmosphere, high dynamic range, cinematic composition, intricate fog layers rolling over rocky cliffs, distant peaks fading into white mist, professionally photographed with sharp focus on foreground elements and soft bokeh in background, masterpiece quality, aesthetically pleasing natural beauty." \
  "Grok" "Ethereal Foggy Mountain Sunrise"

queue_job 17 \
  "Photo-realistic nighttime urban scene of a historic European city street enveloped in dense glowing fog. Warm yellow streetlamps and neon signs cast soft diffused light through the thick mist creating beautiful light beams and halos. Vintage cobblestone road with reflections from car headlights cutting through the fog. Silhouettes of pedestrians holding umbrellas walking in the distance. Elegant old buildings with glowing windows lining the street. Moody and atmospheric with high contrast between warm lights and cool blue fog tones. Intricate details of water droplets on surfaces, subtle steam rising from manholes, cinematic depth of field, ultra-realistic textures, aesthetically pleasing harmonious composition, professional photography standards." \
  "Grok" "Mysterious Foggy City Street at Night"

queue_job 18 \
  "Stunning photo-realistic image of a calm forest lake completely shrouded in soft white morning fog. Ancient tall trees with moss-covered trunks standing in shallow water emerging mysteriously from the mist. Gentle sun rays filtering through the canopy creating magical light shafts on the still water surface with perfect reflections. Delicate lily pads and reeds along the misty shoreline. Subtle ripples disturbing the glassy water. Rich green and earthy brown palette with soft diffused lighting. Highly detailed fog density variations, atmospheric perspective, serene and meditative mood, ultra sharp foreground details with gradual fade into white fog, breathtaking natural beauty, cinematic wide shot composition." \
  "Grok" "Tranquil Foggy Forest Lake"

queue_job 19 \
  "Photo-realistic seascape of rugged coastal cliffs dramatically wrapped in thick rolling sea fog at sunset. Powerful waves crashing against rocky formations with mist mixing with ocean spray. Golden hour sunlight barely penetrating the dense fog creating warm glowing edges on the cliffs. Lone lighthouse visible in the distance with its beam cutting through the haze. Seabirds flying through the atmospheric mist. Moody yet beautiful color palette of deep blues, grays and warm oranges. Ultra-detailed rock textures, water movement, and fog layers. Aesthetically pleasing composition with strong leading lines, professional landscape photography quality, high dynamic range, serene yet powerful atmosphere." \
  "Grok" "Dramatic Coastal Cliff Fog"

queue_job 20 \
  "Beautiful photo-realistic autumn country road disappearing into dense golden fog. Vibrant red, orange and yellow fallen leaves covering the asphalt and surrounding trees. Soft diffused sunlight creating a warm glow through the thick mist. Vintage wooden fence along the winding road with an old lantern post. Gentle fog swirling around tree trunks and covering distant hills. Rich autumn color palette with soft atmospheric lighting. Highly detailed leaf textures, intricate fog movement, peaceful rural scene, perfect composition with strong vanishing point perspective, ultra-realistic depth and atmosphere, aesthetically pleasing harmonious tones, masterpiece quality photography." \
  "Grok" "Dreamy Foggy Autumn Road"

# --- Copilot ---
queue_job 21 \
  "A bustling city street enveloped in thick morning fog, where skyscrapers fade into the mist and traffic lights glow faintly through the haze. Pedestrians move like silhouettes, their outlines softened by the atmospheric veil. Car headlights pierce the fog, casting long beams across wet pavement, while neon signs struggle to shine through the muted air. The scene should feel cinematic, blending realism with mystery, as if the city itself is holding secrets within the fog. Reflections shimmer on the ground, and the overall mood is contemplative yet alive, capturing the beauty of urban life hidden beneath a foggy curtain. Photorealistic rendering, deep atmospheric perspective, natural color grading, ultra-detailed textures." \
  "Copilot" "City Streets in Morning Fog"

queue_job 22 \
  "A serene forest landscape where dense fog blankets the ground, and golden sun rays break through the canopy of tall trees. The beams of light scatter across the mist, creating ethereal shafts that illuminate patches of moss and fallen leaves. The atmosphere is tranquil, with soft contrasts between shadow and glow, evoking a sense of peace and wonder. The fog should feel thick yet delicate, wrapping the forest in a dreamlike embrace. The composition emphasizes depth, with layers of trees fading into the mist, while the sunlight adds warmth and hope to the otherwise muted scene. Photorealistic detail, volumetric light, natural color palette, cinematic composition." \
  "Copilot" "Sun Rays Breaking Through Fog"

queue_job 23 \
  "A lonely highway at night, swallowed by dense fog, where the only visible elements are the glowing headlights and taillights of passing cars. The beams cut through the mist, creating streaks of light that dissolve into the darkness. Roadside signs and guardrails barely emerge from the haze, adding to the sense of isolation. The atmosphere is cinematic and dramatic, with the fog transforming ordinary traffic into a mysterious, almost surreal spectacle. The composition should highlight the contrast between artificial light and natural obscurity, capturing the haunting beauty of a foggy night drive. High dynamic range, photorealistic rendering, cool color palette, deep atmospheric shadows." \
  "Copilot" "Car Lights in Heavy Fog"

queue_job 24 \
  "A grand suspension bridge stretching across a river, partially hidden by thick evening fog. The structure's cables and towers fade into the mist, while faint city lights glow in the distance. The water below reflects the muted colors of dusk, blending blues, purples, and silvers into a soft palette. The fog creates a sense of scale and mystery, as if the bridge leads into the unknown. The composition should emphasize symmetry and depth, with the vanishing point disappearing into the haze. The mood is contemplative, evoking both solitude and quiet grandeur. Photorealistic bridge textures, atmospheric perspective, cinematic lighting, cool desaturated tones." \
  "Copilot" "Foggy Bridge at Dusk"

queue_job 25 \
  "A winding dirt path cutting through open countryside, shrouded in early morning fog. Wooden fences and scattered trees fade into the mist, while dew glistens on tall grass. The atmosphere is calm and nostalgic, evoking the quiet beauty of rural life. The fog softens the horizon, creating a seamless blend between earth and sky. A lone figure walking in the distance adds a human touch, their silhouette barely visible through the haze. The composition should highlight natural textures — grass, soil, wood — while the fog transforms the scene into a timeless, poetic landscape. Photorealistic detail, soft diffused morning light, natural earthy tones, cinematic rural mood." \
  "Copilot" "Countryside Path in Fog"

# --- Mistral ---
queue_job 26 \
  "A hyper-detailed, photo-realistic scene of a dense, ancient forest shrouded in thick, ethereal fog at the break of dawn. Golden sun rays pierce through the mist, creating a surreal, dreamlike atmosphere. Towering trees with moss-covered trunks and sprawling roots emerge from the fog, their leaves glistening with dew. The forest floor is carpeted with ferns and wildflowers, partially obscured by the swirling mist. Soft, diffused light filters through the canopy, casting long, dramatic shadows. The fog has a silvery-blue tint, adding depth and mystery. The image is ultra-sharp, with cinematic composition, vibrant yet natural colors, and a sense of tranquility and wonder. Shot on a high-end DSLR camera with a 50mm lens, f/1.8, ISO 100, 1/125s exposure." \
  "Mistral" "Mystical Foggy Forest at Dawn"

queue_job 27 \
  "A breathtaking, photo-realistic view of a modern city skyline enveloped in a thick, golden-hour fog. Skyscrapers and architectural marvels rise like ghosts from the mist, their glass facades reflecting the warm, ambient light of the setting sun. Streetlights and car headlights create glowing orbs that cut through the fog, adding a magical, cinematic quality. The fog is dense but dynamic, swirling around the buildings and streets below. The image captures the contrast between the sharp, geometric lines of the city and the soft, organic flow of the fog. Ultra-high resolution, with rich textures, deep shadows, and a moody, atmospheric color palette. Shot with a wide-angle lens, f/2.8, ISO 200." \
  "Mistral" "Luminous Cityscape in Fog"

queue_job 28 \
  "A stunning, photo-realistic landscape of a tranquil lake surrounded by misty mountains at sunrise. The fog blankets the water's surface, creating a mirror-like reflection of the golden sunbeams breaking through the clouds. The mountains in the background are partially veiled by the mist, their peaks glowing with warm light. A lone wooden dock extends into the lake, its weathered planks leading the viewer's eye into the serene scene. The water is calm, with subtle ripples disturbing the reflection. The fog has a soft, white-blue hue, adding a sense of depth and mystery. The image is ultra-detailed, with vibrant yet natural colors, and a peaceful, almost otherworldly atmosphere. Shot on a full-frame camera, 35mm lens, f/4, ISO 50." \
  "Mistral" "Serene Lake with Fog and Sunbeams"

queue_job 29 \
  "A hyper-realistic, awe-inspiring view of a vast meadow blanketed in a thick, golden fog at sunrise. Wildflowers in full bloom dot the landscape, their colors vibrant against the misty backdrop. A winding dirt path cuts through the meadow, disappearing into the fog, inviting the viewer to imagine where it leads. The sun is low on the horizon, casting long, dramatic shadows and bathing everything in a warm, golden light. The fog is dense but translucent, with a soft, silvery glow that adds a magical touch. The image is ultra-sharp, with rich textures, deep contrast, and a dreamy, cinematic quality. Shot with a telephoto lens, f/2.4, ISO 100." \
  "Mistral" "Enchanted Foggy Meadow"

queue_job 30 \
  "A mesmerizing, photo-realistic scene of rugged coastal cliffs shrouded in a thick, moody fog at dusk. The cliffs are jagged and dramatic, their dark silhouettes contrasting against the pale, swirling mist. The ocean below is turbulent, with waves crashing against the rocks, their white foam visible through the fog. The sky is a deep, gradient blue, with the last light of the setting sun creating a soft, golden glow on the horizon. The fog has a cool, bluish tint, adding a sense of mystery and isolation. The image is ultra-detailed, with rich textures, deep shadows, and a cinematic, almost painterly quality. Shot on a high-end camera, 24mm lens, f/1.4, ISO 200." \
  "Mistral" "Foggy Coastal Cliffs at Dusk"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A serene urban street at dawn shrouded in a thick, luminous morning fog that softly diffuses the ambient light. Warm orange streetlamps cast gentle halos through the mist, illuminating damp asphalt where subtle puddle reflections mirror the glowing fixtures. Historic brick buildings fade gracefully into the white haze, their architectural details softened yet distinctly visible in the midground. A solitary figure in a long coat walks away from the viewer, leaving faint footsteps on the wet cobblestones. The atmosphere is deeply tranquil, with photorealistic rendering capturing the delicate interplay of moisture in the air, subtle light scattering, and natural color grading. High resolution photography style emphasizes texture, depth of field, and cinematic lighting to create an immersive, atmospheric urban landscape. The cool blue tones of the early morning sky blend seamlessly with the warm artificial illumination, creating a harmonious color palette that feels both grounded and dreamlike." \
  "Qwen 3.6 Plus" "Dawn City Veil"

queue_job 32 \
  "Towering pine trees rise from a carpet of damp moss as thick, silver-tinted fog weaves slowly through the ancient woodland. Brilliant shafts of golden sunlight pierce the dense canopy, creating volumetric god rays that illuminate swirling mist particles suspended in the cool morning air. The forest floor is scattered with fallen leaves and weathered tree roots, each detail captured with crisp photographic clarity. A gentle breeze lifts the fog into soft, rolling waves that partially obscure the distant trunks, enhancing the sense of depth and mystery. The image maintains a strictly photorealistic aesthetic, utilizing natural lighting physics, accurate color temperature transitions, and precise lens-like bokeh to render an immersive woodland scene. The composition balances dramatic light contrast with serene atmospheric tranquility." \
  "Qwen 3.6 Plus" "Sunlit Pine Canopy"

queue_job 33 \
  "A rugged coastal cliff edge overlooks a restless ocean where heavy sea fog rolls inward, wrapping around the jagged rocks and weathered wooden posts. A classic white lighthouse stands resolute at the shoreline, its powerful beacon cutting through the dense gray mist with soft, diffused beams that scatter across the damp air. Drifting kelp and sea spray coat the dark stone surfaces, adding tactile realism to the foreground. The overcast sky blends seamlessly into the fog bank, creating a smooth gradient that emphasizes the lighthouse as a focal point. Photographed with high-end landscape photography techniques, the scene features accurate atmospheric perspective, natural moisture rendering, and subtle chromatic contrasts between the cool ocean tones and the warm lantern glow. Every element is meticulously detailed to achieve a lifelike, immersive maritime atmosphere." \
  "Qwen 3.6 Plus" "Coastal Beacon Mist"

queue_job 34 \
  "A winding mountain highway disappears into a dense, rolling blanket of night fog, illuminated only by the glowing red taillights and bright white headlights of distant vehicles. The asphalt is slick with recent rain, creating mirror-like reflections that stretch the vehicle lights into elongated, luminous streaks across the wet pavement. Guardrails fade progressively into the mist, establishing a strong sense of depth and perspective. The fog diffuses the artificial lighting into soft, cinematic halos that contrast beautifully with the cool blue-black tones of the surrounding forest and sky. Captured with professional automotive photography standards, the image emphasizes realistic light scattering, precise lens flares, and accurate moisture physics. The composition balances motion and stillness, delivering a highly atmospheric, photorealistic nighttime driving scene." \
  "Qwen 3.6 Plus" "Highway Night Drift"

queue_job 35 \
  "A vast alpine valley cradles a slow-moving river of low-lying morning fog that pools between jagged, snow-dusted mountain peaks. The rising sun casts a soft peach and lavender glow across the sky, gently illuminating the upper slopes while the valley floor remains wrapped in cool, silvery mist. Pine forests emerge from the fog like dark green islands, their branches dusted with dew that catches the early light. The foreground features a rocky riverbank with smooth, water-worn stones and shallow streams reflecting the muted sky tones. Rendered with ultra-high fidelity landscape photography, the image showcases accurate atmospheric haze layering, natural color grading, and precise depth-of-field transitions. The overall composition balances grand scale with intimate textural details, creating a serene, photorealistic mountain panorama." \
  "Qwen 3.6 Plus" "Alpine Valley Dawn"

# --- GLM 5.1 ---
queue_job 36 \
  "A highly detailed photo-realistic image of a bustling city street enveloped in dense, atmospheric fog at night. The headlights of a sleek black sedan cut through the thick mist, creating bright, glowing beams of light that illuminate the damp asphalt ahead. Tall skyscrapers fade into the opaque white fog above, their architectural silhouettes barely visible in the distance. Warm, neon streetlights and glowing red taillights cast colorful, vibrant reflections on the wet pavement, creating a cinematic, moody ambiance. The fog acts as a soft diffuser, giving the artificial lights an ethereal, blooming effect that fills the air. Captured with an 85mm lens, the composition focuses on the striking interplay between the sharp, crisp details of the car and the soft, obscured background, emphasizing the mysterious and aesthetically pleasing nature of the urban fog." \
  "GLM 5.1" "Urban Night Fog"

queue_job 37 \
  "A breathtaking photo-realistic depiction of an ancient forest shrouded in thick morning fog, illuminated by stunning crepuscular sun rays. Towering redwood trees stretch upward, their textured bark and lush green canopies fading into the dense white mist. Brilliant golden beams of sunlight pierce through the canopy gaps, creating dramatic god rays that spotlight patches of vibrant green ferns and moss-covered rocks on the forest floor. The volumetric fog adds immense depth and atmosphere, beautifully softening the light and creating a serene, mystical environment. Dust motes and tiny water droplets float in the illuminated shafts, adding a magical touch to the scene. The overall aesthetic is tranquil and awe-inspiring, with a perfect balance of deep forest shadows and radiant, warm morning light filtering through the rolling fog." \
  "GLM 5.1" "Golden Forest God Rays"

queue_job 38 \
  "A stunning photo-realistic image of a winding mountain road swallowed by thick, rolling fog at dawn. A vintage copper-colored Mustang drives along the narrow asphalt, its warm yellow headlights cutting sharp beams through the dense, white mist. The surrounding mountain landscape is entirely hidden by the heavy fog, creating an isolated, surreal atmosphere. Only the immediate road, dotted with glowing yellow center lines, and the sleek silhouette of the classic car are visible. The soft, pastel hues of the dawn sky subtly bleed through the top of the fog, adding a delicate touch of pink and lavender to the otherwise monochromatic scene. The moist air clings to the car's polished surface, creating subtle reflections. The composition evokes a sense of peaceful solitude and cinematic beauty, capturing the mesmerizing essence of traveling through a heavy morning fog." \
  "GLM 5.1" "Mountain Road Solitude"

queue_job 39 \
  "An aesthetically pleasing photo-realistic image of a historic stone bridge spanning a quiet river, completely enveloped in thick, atmospheric fog. Vintage wrought-iron streetlamps line the bridge, casting warm, glowing halos of amber light that struggle against the dense mist. The fog rolls heavily over the stone arches and clings to the dark, still water below, obscuring the distant riverbanks and creating an ethereal, timeless landscape. The intricate textures of the wet cobblestones on the bridge gleam under the soft lamplight, contrasting beautifully with the diffused, shadowy surroundings. The interplay of light and fog creates a moody, romantic atmosphere, with the warm light sources gently illuminating the air around them. Captured in high resolution, the scene emphasizes the quiet elegance and mysterious allure of a foggy night in a historic European city." \
  "GLM 5.1" "Lampposts on the Gothic Bridge"

queue_job 40 \
  "A captivating photo-realistic image of a peaceful rural landscape submerged in a sea of thick morning fog at sunrise. A rustic wooden cabin sits on a small hill, its warm interior lights glowing softly through the windows, creating a welcoming contrast against the cool, blue tones of the dawn. Low-lying mist blankets the surrounding meadows and weaves through the silhouettes of bare winter trees. The rising sun paints the upper sky in soft pastel shades of peach, pink, and gold, with the colors gently diffusing through the upper layers of the fog. The atmosphere is deeply serene and aesthetically pleasing, showcasing the quiet beauty of nature waking up. The fine details of the frost-kissed grass in the foreground blend seamlessly into the dreamy, fog-filled background, highlighting the tranquil and cinematic mood of the morning." \
  "GLM 5.1" "Rustic Cabin at Sunrise"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A photorealistic aerial perspective of a modern metropolitan street at dawn completely engulfed in thick, ethereal white fog. Soft golden sun rays pierce vertically through the dense atmospheric mist, creating dramatic volumetric god rays between towering contemporary glass skyscrapers. Vintage street lamps emit warm amber halos that diffuse beautifully into the surrounding fog. Wet asphalt reflects the muted city lights, creating mirror-like puddles on the pavement. A single red traffic light glows mysteriously in the far distance. The atmosphere is profoundly serene and cinematic, with multiple layers of drifting fog creating deep atmospheric perspective and depth. Shot on 35mm lens, f/2.8, shallow depth of field, hyper-detailed textures, 8k resolution, moody cinematic color grading with teal and orange tones, professional architectural photography style, award-winning composition." \
  "Kimi K2.6 Thinking" "City Street at Dawn in Thick Fog"

queue_job 42 \
  "A breathtaking photorealistic landscape photograph of a pristine alpine mountain lake at sunrise, partially obscured by thick rolling morning fog drifting across the water surface. Brilliant golden sunbeams filter through towering ancient pine trees on the rocky shoreline, illuminating the suspended mist particles with warm amber volumetric light. The perfectly calm dark water creates mirror-like reflections of distant snow-capped peaks dramatically emerging above the dense fog layer. A weathered wooden dock extends mysteriously into the lake, partially hidden by swirling white mist. Dew drops glisten on purple wildflowers in the immediate foreground. The scene evokes profound tranquility and untouched natural beauty. Cinematic lighting, deep atmospheric perspective, shot on medium format camera, f/8, hyper-detailed, 8k resolution, rich natural colors, National Geographic wilderness photography style, award-winning composition." \
  "Kimi K2.6 Thinking" "Mountain Lake Sunrise Through Morning Mist"

queue_job 43 \
  "A photorealistic cinematic night scene featuring a vintage 1960s convertible car parked on an empty winding country road, its warm yellow halogen headlights cutting dramatically through extremely dense fog. The powerful light beams create striking volumetric cones that illuminate millions of suspended water droplets in the air. A lone flickering street lamp in the distant background casts a soft sodium-vapor orange glow through the mist. The wet cobblestone road surface reflects the scattered lights subtly. Dark silhouettes of bare winter oak trees frame the composition on both sides. Moody noir atmosphere with deep shadows and selective dramatic lighting. Shot on 50mm lens, f/1.4, shallow depth of field, subtle film grain texture, hyper-detailed metal and leather textures, 8k resolution, cinematic color grading, professional automotive photography style, mysterious and deeply nostalgic mood." \
  "Kimi K2.6 Thinking" "Vintage Car Headlights in Dense Night Fog"

queue_job 44 \
  "A photorealistic enchanted temperate forest scene where brilliant morning sunbeams pierce through a dense canopy of towering ancient oak and redwood trees, illuminating thick golden fog that completely fills the woodland floor. The volumetric light creates dramatic crepuscular rays between moss-covered massive tree trunks. A narrow winding dirt path covered in vibrant fallen autumn leaves disappears mysteriously into the luminous white mist. Lush green ferns and colorful wild mushrooms grow on decaying fallen logs in the immediate foreground. Tiny dust particles and floating pollen sparkle like magical diamonds suspended in the light beams. The atmosphere is magical yet scientifically realistic, with deep emerald greens and warm honey golds. Shot on macro wide-angle lens, f/5.6, extensive depth of field, hyper-detailed bark and moss textures, 8k resolution, BBC nature documentary photography style, serene and mystical woodland ambiance." \
  "Kimi K2.6 Thinking" "Sunbeams Through Forest Canopy Mist"

queue_job 45 \
  "A photorealistic dramatic coastal seascape featuring a historic white stone lighthouse perched on jagged dark volcanic cliffs, half-engulfed by thick rolling sea fog moving inland from the ocean. The powerful lighthouse beam cuts through the dense mist creating a dramatic volumetric cone of bright yellow light over the turbulent dark ocean waves crashing below. Warm sunset colors of burnt orange and deep purple peek through the upper fog layer on the distant horizon. Several seagulls fly through the illuminated mist near the tower. Wet black rocks glisten with salt water and dark green seaweed in the foreground. Long exposure photography captures the silky motion of white crashing waves. The atmosphere is powerfully isolating yet profoundly beautiful. Shot on telephoto lens, f/11, razor-sharp architectural details, hyper-detailed stone and water textures, 8k resolution, professional seascape photography style, cinematic moody maritime atmosphere." \
  "Kimi K2.6 Thinking" "Coastal Cliff Lighthouse in Sea Fog"

# --- Deepseek ---
queue_job 46 \
  "A photorealistic view of a wide city boulevard enveloped in a dense, milky fog just after dawn. The street surface is wet from previous rain, reflecting the blurred, warm orange halos of distant traffic lights and the dim glow of street lamps that fade into the white void. In the middle distance, the silhouettes of classic vintage cars — their headlights cutting soft, diffused beams through the mist — move slowly. Towering Art Deco skyscrapers loom as ghostly shapes on both sides, their upper floors completely erased by the fog. A lone person in a long coat crosses the street, their umbrella creating a sharp dark contrast against the pale, ethereal atmosphere. The overall mood is cinematic, melancholic yet serene, with subtle teal and amber tones enhancing the depth and realism." \
  "Deepseek" "Misty Morning Boulevard"

queue_job 47 \
  "A breathtaking photorealistic landscape of a quiet, misty forest at early morning. Towering ancient pine trees with dark, textured bark stand like silent guardians, their upper branches lost in a thick, rolling fog that hangs just above the forest floor. Powerful, golden sunbeams break through a gap in the canopy, illuminating floating particles of mist and pollen, creating visible rays that slant dramatically across the scene. The ground is covered in a soft carpet of emerald moss and fallen amber needles, with a small, still puddle reflecting the hazy light. Dewdrops cling to spiderwebs between ferns. The atmosphere is calm, sacred, and deeply peaceful, with a palette of muted greens, soft grays, and warm gold light piercing the fog." \
  "Deepseek" "Sunbeams Through Ancient Pines"

queue_job 48 \
  "A photorealistic nighttime scene on a suspension bridge shrouded in thick, drifting fog. The road stretches toward the vanishing point, where the bridge towers fade into a luminous grey haze. On the near side, two cars approach from opposite directions: one's red taillights smear into long, glowing ribbons across the wet asphalt, while the other's white headlights cast a soft, volumetric beam through the fog particles. Droplets of rain cling to an invisible camera lens effect, blurring the background slightly. Steel cables and railings are slick with moisture, reflecting the surrounding amber streetlights. In the distance, the city skyline is a faint, ghostly silhouette. The composition is dynamic yet melancholic, with deep blacks, rich reds, and pale, diffused whites creating a moody, cinematic atmosphere." \
  "Deepseek" "Car Lights on a Rainy Bridge"

queue_job 49 \
  "A photorealistic coastal scene of a solitary white and red lighthouse perched on a rugged cliff, surrounded by a dense, slow-moving fog bank rolling in from the sea. The powerful lighthouse beam rotates, cutting a soft, conical swath of light through the mist, illuminating swirling fog tendrils and a few circling seagulls. Below, dark jagged rocks are kissed by gentle, foamy waves that fade into the grey-white nothingness. The foreground features wet, salt-sprayed grass and a broken wooden fence post. The sky is overcast but with a subtle, lighter patch where the hidden sun tries to break through. The atmosphere is isolated, mysterious, and poetic, with a palette of muted whites, deep slate blues, hints of red, and the warm yellow glow of the lantern room." \
  "Deepseek" "Lighthouse in a Blanket of Fog"

queue_job 50 \
  "A photorealistic image of a narrow, winding country lane at golden hour, heavily veiled in a gentle, low-lying fog that hugs the ground. The dirt path is lined with ancient oak trees, their gnarled branches reaching overhead to form a natural tunnel, with moss and ivy clinging to their trunks. Wisps of white mist float just above the grass, separating the visible world from a dreamy blur. A rusty iron gate sits ajar on the left, leading to an unseen field. Through a gap in the fog, a distant farmhouse with a smoking chimney is barely visible. Sunlight filters through the leaves and fog, creating soft, volumetric rays and casting dappled shadows on the path. Fallen autumn leaves — amber, rust, and gold — are scattered on the wet earth. The mood is nostalgic, tranquil, and slightly surreal, evoking a sense of peaceful solitude." \
  "Deepseek" "Fog Over a Quiet Country Lane"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A stunning photorealistic capture of a sprawling metropolitan cityscape completely engulfed in dense morning fog during the magical golden hour. Brilliant sunbeams break dramatically through the thick white mist, creating spectacular volumetric god rays that pierce between the glass facades of towering modern skyscrapers. The wet asphalt streets below act as perfect mirrors, reflecting the warm golden and amber hues from streetlamps and traffic signals that glow softly through the pervasive haze. Pedestrian silhouettes drift through the fog like ethereal ghosts, their forms beautifully blurred and dreamlike. The entire scene exudes a deeply mysterious cinematic atmosphere with incredible depth created by multiple layered fog banks stretching into the distance. Ultra-detailed, professional wide-angle lens, 8K resolution, atmospheric lighting, moody ethereal tone." \
  "ERNIE 5.1 Thinking" "Dawn Over the Foggy Metropolis"

queue_job 52 \
  "A breathtaking photorealistic scene of ancient towering redwood trees disappearing into a thick blanket of low-hanging fog within a mystical old-growth forest. Golden morning sunlight streams dramatically through the dense canopy above, creating stunning volumetric light beams that cut through the misty air like divine spotlights illuminating sacred ground. The forest floor is carpeted in lush green moss and delicate ferns, every surface glistening with fresh dewdrops that catch and scatter the warm light. Wisps of ethereal fog curl and dance between the massive tree trunks, adding layers of mystery and enchantment to the scene. Rays of warm golden light illuminate patches of the ground, creating a magical contrast with the cool blue-grey fog. Ultra-sharp detail, cinematic composition, 8K quality, natural atmospheric perspective, ethereal and serene mood." \
  "ERNIE 5.1 Thinking" "Sun Rays Through Ancient Forest Fog"

queue_job 53 \
  "A photorealistic night scene on a deserted highway where thick heavy fog blankets the road completely, reducing visibility to almost nothing. Powerful car headlights cut dramatically through the dense mist, creating brilliant cones of white and yellow light that illuminate millions of swirling fog particles suspended in the air. The taillights of vehicles ahead glow as soft diffused red orbs slowly fading into the white void of the fog. The wet asphalt road surface acts as a dark mirror, reflecting all the lights and creating a stunning doubling of the visual impact. Fog rolls and undulates around the vehicles like living breathing clouds. The scene is deeply moody and atmospheric with a strong sense of isolation and quiet tension. Ultra-detailed, shallow depth of field, cinematic noir atmosphere, 8K resolution, dramatic volumetric lighting." \
  "ERNIE 5.1 Thinking" "Headlights Through Highway Fog"

queue_job 54 \
  "A stunning photorealistic landscape of a perfectly still mountain lake at sunrise, completely covered in a thin layer of ethereal fog that floats just above the water surface. The first golden rays of the rising sun paint the sky in soft pinks, warm oranges, and gentle purples, and these beautiful colors are perfectly reflected in the glassy mirror-like water below. The fog hovers delicately above the lake, creating a dreamlike separation between the real world and its flawless reflection. Distant mountain peaks emerge softly from the mist like floating islands in a sea of white clouds. A single weathered wooden dock extends silently into the fog, its far end disappearing into the white void. The atmosphere is profoundly peaceful and meditative. 8K quality, ultra-sharp detail, soft natural lighting, atmospheric perspective, tranquil mood." \
  "ERNIE 5.1 Thinking" "Fog Over a Lake at Sunrise"

queue_job 55 \
  "A photorealistic scene of a narrow urban alley at night, heavily saturated with colorful neon signs from shops and bars, all their light reflected and diffused through thick rolling fog. Vivid pink, electric blue, and deep purple neon lights create a stunning cyberpunk atmosphere as the dense fog transforms every light source into soft glowing halos of colored mist. The wet cobblestone street below acts as a canvas, reflecting the neon colors in long beautiful streaked patterns of light. Steam rises from a manhole cover, mixing with the fog and catching the colored light like floating fireflies. A lone figure with an umbrella walks away from the camera, their silhouette perfectly framed by the glowing mist. The scene is vibrant yet deeply mysterious. 8K resolution, cinematic composition, dramatic volumetric fog lighting, ultra-detailed." \
  "ERNIE 5.1 Thinking" "Neon Lights in Foggy Urban Alley"

echo "✅ All 55 jobs queued in scheduler"
