#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Spectacular sunset
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+23+-+sunset
# Structure: 11 models × 5 prompts = 55 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A towering volcanic coastline at golden hour, molten lava-red sky bleeding into deep magenta and burnt sienna, the sun a blazing white-gold disc half-submerged behind jagged obsidian cliffs. Ocean surface fractures into shards of reflected copper and amber light. Foreground: black volcanic rock formations with tide pools catching fire-orange sky reflections. Atmosphere dense with heat haze and distant smoke plumes. Ultra-detailed, cinematic color grading, high dynamic range, painterly texture, dramatic chiaroscuro lighting. Style: contemporary fine-art photography meets oil painting. Colors: crimson, cadmium orange, raw sienna, ivory, charcoal black. No people, no text." \
  "Claude Sonnet 4.6" "Volcanic Horizon Inferno"

queue_job  2 \
  "Vast undulating sand dunes of the Sahara desert at sunset, sculpted ridges casting razor-sharp violet shadows across warm apricot sand faces. Sky transitions from deep cobalt zenith through burning tangerine to a compressed gold horizon band. A lone withered acacia tree silhouetted at left-third compositional placement. Sand surface texture hyper-detailed, wind ripple micropatterns visible. Atmosphere dry, luminous, crystalline. Style: large-format documentary photography, National Geographic quality. Colors: cobalt blue, cadmium yellow, burnt orange, violet shadow, pale gold. Long shadows stretch diagonally across frame. No people, no text, no animals." \
  "Claude Sonnet 4.6" "Saharan Dune Twilight"

queue_job  3 \
  "High-altitude alpine lake perfectly still, reflecting an explosive sunset sky with surgical precision. Twin images — actual sky and water mirror — bisected by a hairline horizon. Jagged snow-capped peaks frame both sides. Sky: stacked bands of vermillion, hot pink, lavender, and deep prussian blue with scattered cirrus clouds catching fire. Foreground: smooth granite boulders and sparse alpine grass. Crystal-clear mountain air. Style: fine-art landscape photography, ansel adams precision with saturated color. Ultra-sharp throughout, infinite depth of field. Colors: prussian blue, hot pink, vermillion, snow white, slate grey, deep forest green. No people, no text." \
  "Claude Sonnet 4.6" "Alpine Lake Mirror"

queue_job  4 \
  "Colossal monsoon cumulonimbus towers backlit by a setting sun, internal lightning illuminating cloud chambers from within like stained glass. Base of storm system draped in deep purple-grey rain curtains. Foreground: flat wet rice paddies reflecting sky fire in fragmented patches. Horizon glows amber-gold beneath the storm's anvil. Atmosphere electric, charged, monumental. Scale overwhelming — clouds dwarf everything beneath. Style: epic landscape photography, dramatic storm chasing aesthetic. Colors: sulfur yellow, deep purple, electric white, amber gold, cool grey, ochre. Hyper-detailed cloud texture, visible water droplet density. No people, no text." \
  "Claude Sonnet 4.6" "Monsoon Cloud Cathedral"

queue_job  5 \
  "Broken polar ice floes scattered across dark Arctic water at sunset, each ice shard catching warm ember-orange and rose-gold light against a sky painted in bruised violet and molten copper. The low arctic sun skims the horizon, stretching long amber caustic light across the water between ice chunks. Mist rising from water surface. Horizon impossibly vivid, compressed atmospheric color bands. Style: fine-art nature photography, hyper-real. Colors: rose gold, deep violet, molten copper, ivory white, midnight teal, ember orange. Ice surfaces show translucent blue-green inner glow contrasting warm exterior light. No people, no text." \
  "Claude Sonnet 4.6" "Arctic Ice Floe Ember"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A breathtaking cinematic sunset over a futuristic cyberpunk metropolis. Towering skyscrapers with glowing neon signs in cyan and magenta cast long, deep reflections onto wet asphalt streets below. The sky is a dramatic gradient of fiery crimson, deep violet, and burning orange, with dense, dramatic clouds catching the last vibrant rays of light. Holographic advertisements shimmer in the twilight haze. A lone figure in a dark trench coat stands on a high rooftop ledge, looking out over the sprawling, glowing city grid. The lighting is high-contrast, rich with ink-like shadows and brilliant, intense highlights, capturing a hardboiled graphic novel atmosphere. The overall composition is grand, panoramic, and filled with atmospheric depth, emphasizing the scale of the futuristic urban canyon under a blazing evening sky." \
  "Gemini 3.5 Flash" "Spectacular Sunset Over Cyberpunk Neo-Tokyo"

queue_job  7 \
  "A spectacular sunset blazing over a vast, majestic desert mesa landscape. The sky is an intense explosion of amber, gold, and deep scarlet, with wispy cirrus clouds painted in brilliant orange streaks. Massive sandstone rock formations and towering bluffs cast long, dramatic shadows across the cracked earth and scattered desert sagebrush. In the foreground, a single weathered acacia tree stands silhouetted against the blinding, radiant sun as it dips below the distant horizon. The atmosphere is filled with a warm, golden haze and floating dust motes catching the final, brilliant rays of daylight. The artistic style features rich, saturated textures, extreme tonal contrast, and a powerful sense of vast, quiet isolation under a magnificent, burning sky." \
  "Gemini 3.5 Flash" "Vibrant Desert Mesa Solitude"

queue_job  8 \
  "A magnificent and chaotic sunset over a turbulent, stormy ocean. The sky is a dramatic battleground of dark, heavy charcoal storm clouds torn apart by a brilliant, fierce explosion of blood red, fiery orange, and intense gold light from the setting sun. Massive, churning waves with translucent emerald crests crash violently, scattering sea spray that catches the radiant evening glow. A solitary, historic stone lighthouse stands resilient on a jagged cliff side, its bright beacon just starting to cut through the gathering twilight. The composition is dynamic and full of motion, utilizing extreme high-contrast lighting to emphasize the raw power of nature. Ink-dark shadows contrast sharply with the brilliant, luminous water and sky, creating a breathtaking, theatrical scene of maritime drama." \
  "Gemini 3.5 Flash" "Stormy Ocean Horizon Inferno"

queue_job  9 \
  "A spectacular, radiant sunset filtering through the dense canopy of an ancient autumn forest. Brilliant rays of golden and crimson light pierce through the misty air, creating dramatic volumetric light beams that illuminate falling orange and red leaves. A crystal-clear winding stream flows through the center of the frame, perfectly reflecting the fiery, vibrant colors of the burning sky above. The forest floor is covered in a rich carpet of moss and fallen foliage, with deep, dark shadows stretching between the massive, twisted tree trunks. The atmosphere is mystical and serene, filled with a soft, glowing twilight haze. High-contrast graphic elements blend with rich, organic textures, capturing a breathtaking moment where nature's colors are amplified to a spectacular, near-magical intensity." \
  "Gemini 3.5 Flash" "Enchanted Autumn Forest Twilight"

queue_job 10 \
  "An extraordinary, spectacular sunset over a vast, perfectly still mirror lake. The entire sky is a breathtaking canvas of deep violet, magenta, and brilliant golden-yellow, with sweeping, stylized cloud formations that create a powerful sense of movement. The glass-like surface of the water creates a flawless, symmetrical reflection of the vibrant sky, making the horizon line almost blur into a seamless visual continuum. A minimalist, dark silhouette of a single wooden pier extends into the center of the lake, guiding the eye toward the burning sun. The lighting is intensely vibrant with deep, ink-black silhouettes contrasting against the luminous, glowing water and sky. The composition leverages a unique visual metaphor of infinite space, delivering a clean, high-contrast, and deeply captivating artistic image." \
  "Gemini 3.5 Flash" "Surreal Mirror Lake Reflections"

# --- ChatGPT ---
queue_job 11 \
  "A breathtaking, hyper-realistic sunset over a vast, calm ocean where the horizon seems infinite, painted in layers of molten gold, fiery orange, and deep crimson fading into soft violet skies. Gentle waves reflect the sky like liquid glass, creating a mirror of glowing colors. The sun sits half-submerged, casting long radiant beams across the water, while distant clouds catch the light with dramatic highlights and shadows. A lone silhouette of a small boat drifts peacefully, adding scale and emotion. Ultra-detailed lighting, cinematic composition, volumetric sun rays, soft atmospheric haze, and subtle reflections enhance realism. Shot as if with a high-end DSLR, sharp focus, rich dynamic range, and a serene yet powerful mood." \
  "ChatGPT" "Golden Horizon Over Endless Ocean"

queue_job 12 \
  "An epic sunset over a vast desert landscape, where rolling dunes glow in warm amber and burnt orange tones under a sky exploding with color. The sun dips low, casting long, dramatic shadows that sculpt the sand into waves of texture. The sky transitions from blazing orange near the horizon to deep magenta and indigo above, streaked with wispy clouds catching the last light. Heat haze subtly distorts the distance, adding realism. A solitary figure stands atop a dune, silhouetted against the radiant sky, evoking scale and solitude. Ultra-detailed textures, cinematic lighting, atmospheric depth, soft gradients, and sharp clarity, captured in a photorealistic style with a wide-angle perspective." \
  "ChatGPT" "Desert Flames Beneath a Painted Sky"

queue_job 13 \
  "A spectacular alpine sunset with jagged mountain peaks rising above a sea of clouds, illuminated by intense golden and crimson light. The sun is just below the horizon, casting a fiery glow that reflects off snow-capped summits and creates glowing edges along the ridgelines. Clouds below appear like a soft ocean, tinted pink and orange, with light piercing through in dramatic rays. The sky transitions into deep purples and blues, dotted with early stars. Crisp air, extreme detail, and high contrast lighting emphasize the rugged textures of rock and snow. Cinematic composition, ultra-wide lens perspective, and HDR-style rendering create a powerful, awe-inspiring atmosphere." \
  "ChatGPT" "Mountain Peaks in a Sea of Firelight"

queue_job 14 \
  "A modern city skyline at sunset, where glass skyscrapers reflect a sky ablaze with intense orange, red, and violet hues. The sun sets behind the buildings, creating silhouettes with glowing edges and reflections that cascade across windows like fire. Streets below begin to light up with early evening illumination, adding contrast between warm sunlight and cool artificial lights. Clouds are dramatic and layered, catching highlights that amplify the spectacle. The scene is highly detailed, with realistic reflections, depth, and perspective. Shot in a cinematic urban photography style, with balanced exposure, rich colors, and a dynamic, energetic yet serene atmosphere." \
  "ChatGPT" "City Skyline Ignited by Sunset Glow"

queue_job 15 \
  "A vivid tropical beach at sunset with palm trees gently swaying against a sky bursting with saturated oranges, pinks, and purples. The sun sits low over the horizon, casting shimmering golden light across turquoise water that transitions into deep blue. Soft waves roll onto white sand, reflecting the sky's colors like a natural painting. Silhouetted palm trees frame the scene, adding depth and a sense of paradise. Subtle clouds catch glowing highlights, enhancing the drama of the sky. Ultra-realistic lighting, high detail textures, cinematic color grading, and a peaceful, dreamy atmosphere create a perfect balance between beauty and tranquility." \
  "ChatGPT" "Tropical Paradise Under a Radiant Sunset"

# --- Grok ---
queue_job 16 \
  "A breathtaking spectacular sunset over snow-capped mountain peaks, golden and crimson light piercing through dramatic clouds, vibrant orange, pink, and purple hues blending in the sky, rays of sunlight breaking through, reflecting on a pristine alpine lake in the foreground, rocky cliffs and pine trees silhouetted against the glowing horizon, atmospheric mist rising from the valley, highly detailed, cinematic lighting, epic composition, masterpiece, ultra-realistic textures, volumetric god rays, serene yet powerful natural beauty, rich color palette, perfect balance of warm and cool tones, 8k resolution quality." \
  "Grok" "Majestic Mountain Sunset Panorama"

queue_job 17 \
  "Spectacular sunset on a tropical paradise beach, fiery orange sun sinking into the calm turquoise ocean, vibrant reflections dancing on gentle waves, palm trees silhouetted on white sand, dramatic clouds painted in magenta, gold, and deep purple, seashells and soft foam at the shoreline, warm golden hour glow illuminating the scene, distant sailboats on the horizon, heavenly atmosphere, intricate details in water ripples and cloud formations, photorealistic, emotional and peaceful mood, stunning color gradients, masterpiece, ultra-detailed, cinematic masterpiece." \
  "Grok" "Tropical Ocean Sunset Serenity"

queue_job 18 \
  "Spectacular sunset over a modern bustling city skyline, towering skyscrapers reflecting fiery orange and pink sunset light in their glass windows, dramatic clouds swirling above, busy streets with glowing car lights creating light trails, rooftop gardens and bridges in silhouette, vibrant purple and gold sky dominating the scene, atmospheric perspective, epic urban beauty mixed with natural wonder, highly detailed architecture, volumetric lighting, cinematic composition, rich textures, masterpiece quality, breathtaking view from high vantage point." \
  "Grok" "Urban Cityscape Golden Hour Drama"

queue_job 19 \
  "Spectacular sunset illuminating an enchanted ancient forest beside a mirror-like lake, warm golden sunlight filtering through tall trees with autumn foliage, vibrant reds, oranges, and purples in the sky reflecting perfectly on the water surface, mystical fog hovering above the lake, deer and birds in the distance, glowing fireflies emerging, rich detailed leaves and bark textures, magical yet realistic atmosphere, epic natural wonder, intricate light rays piercing the canopy, masterpiece, ultra-realistic, serene and awe-inspiring." \
  "Grok" "Enchanted Forest Lake Sunset"

queue_job 20 \
  "Spectacular sunset across endless golden sand dunes in the desert, massive sun dipping behind the horizon casting long dramatic shadows, intense orange, red, and purple sky with scattered dramatic clouds, wind-sculpted dunes creating beautiful patterns, a lone camel caravan in the distance, warm glowing atmosphere, intricate sand textures and ripples, cinematic wide view, rich color contrasts, volumetric light beams, ultra-detailed, masterpiece, breathtaking scale and natural beauty." \
  "Grok" "Desert Dunes Epic Sunset"

# --- Copilot ---
queue_job 21 \
  "A breathtaking sunset scene where the horizon blazes with radiant hues of gold, orange, and crimson, casting a warm glow across the tranquil landscape. The sky is painted with streaks of fiery clouds, their edges illuminated by the fading sun. Below, a calm body of water reflects the dazzling colors, creating a mirror-like effect that doubles the beauty of the spectacle. Silhouettes of distant mountains or trees add depth and contrast, standing dark against the vibrant sky. The atmosphere is serene yet dramatic, capturing the fleeting magic of twilight as day transitions into night." \
  "Copilot" "Golden Horizon Glow"

queue_job 22 \
  "A spectacular sunset where the sky transforms into a symphony of crimson, magenta, and violet tones. Wisps of clouds stretch across the heavens, glowing as if lit from within, while the sun dips low, radiating brilliance across the horizon. The scene is framed by silhouettes of rolling hills or a quiet coastline, their outlines sharp against the vivid backdrop. The reflection of the fiery sky dances across rippling waters, adding movement and texture to the composition. The overall mood is both powerful and poetic, evoking awe at the grandeur of nature's evening performance." \
  "Copilot" "Crimson Sky Symphony"

queue_job 23 \
  "A mesmerizing sunset over the ocean, where the sun sinks into the horizon, casting golden and pink reflections across the rolling waves. The sky is alive with gradients of orange, purple, and soft blue, blending seamlessly into one another. Gentle waves shimmer with the last light of day, their crests catching the glow like liquid fire. Seagulls glide gracefully across the scene, silhouetted against the radiant backdrop. The atmosphere is tranquil yet majestic, capturing the eternal rhythm of sea and sky as they unite in a breathtaking twilight display." \
  "Copilot" "Twilight Over Ocean Waves"

queue_job 24 \
  "A dramatic sunset over towering mountain peaks, where the summits glow with amber light as the sun descends behind them. The sky is ablaze with fiery tones of orange, red, and violet, casting long shadows across rugged slopes and valleys. Wisps of mist curl around the ridges, catching the fading light in ethereal patterns. The composition emphasizes the grandeur of the mountains, their silhouettes sharp against the radiant sky. The mood is both powerful and serene, a moment of natural magnificence that feels timeless and awe-inspiring." \
  "Copilot" "Amber Peaks at Dusk"

queue_job 25 \
  "A spectacular sunset where the sky becomes a canvas of vivid colors — deep purples, radiant oranges, and soft pinks blending in harmony. Clouds scatter across the horizon, glowing like brushstrokes of fire and light. Below, a tranquil lake reflects the kaleidoscope of hues, doubling the intensity of the scene. Silhouettes of trees or a distant village add grounding elements, contrasting with the vibrant sky. The atmosphere is peaceful yet enchanting, evoking a sense of wonder and serenity as the day concludes with nature's most dazzling performance." \
  "Copilot" "Serenade of Colors"

# --- Mistral ---
queue_job 26 \
  "A breathtaking sunset over a calm ocean, golden light reflecting on the water, vibrant orange and pink hues painting the sky, silhouettes of distant sailboats, dramatic clouds with a soft glow, ultra-detailed, cinematic lighting, photorealistic, 8K resolution, HDR, hyperrealistic textures, serene and majestic atmosphere." \
  "Mistral" "Golden Hour Over the Ocean"

queue_job 27 \
  "A spectacular sunset behind a rugged mountain range, fiery red and orange colors blending into deep purples, snow-capped peaks glowing in the last light, dramatic shadows and highlights, ultra-sharp details, cinematic composition, photorealistic, 8K, HDR, breathtaking natural beauty." \
  "Mistral" "Fiery Sunset in the Mountains"

queue_job 28 \
  "A tranquil beach at sunset, palm trees swaying in the foreground, silhouettes of people walking along the shore, warm golden and pink tones in the sky, gentle waves lapping at the sand, ultra-detailed, cinematic mood, photorealistic, 8K, HDR, peaceful and dreamy ambiance." \
  "Mistral" "Silhouettes at Sunset Beach"

queue_job 29 \
  "A vibrant sunset over a modern city skyline, skyscrapers reflecting the warm colors of the sky, golden hour light casting long shadows, bustling streets below, ultra-detailed architecture, cinematic lighting, photorealistic, 8K, HDR, urban beauty with a touch of magic." \
  "Mistral" "Sunset Over a City Skyline"

queue_job 30 \
  "A stunning sunset over endless lavender fields, soft purple and gold hues in the sky, rows of lavender glowing in the fading light, a lone windmill in the distance, ultra-detailed textures, cinematic atmosphere, photorealistic, 8K, HDR, serene and picturesque landscape." \
  "Mistral" "Lavender Fields at Dusk"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A breathtaking panoramic view of a spectacular sunset unfolding across a tranquil coastal bay. The sky features vibrant gradients of deep magenta, fiery orange, and rich golden yellow, seamlessly blending into soft lavender twilight near the horizon. Wispy cumulus clouds catch the dying sunlight, glowing with intense amber highlights while casting delicate shadows across the atmosphere. Below, the glassy ocean surface acts as a flawless mirror, perfectly reflecting the celestial display with gentle concentric ripples. Silhouettes of jagged sea stacks and weathered driftwood frame the foreground, adding depth and texture. The overall lighting is dramatic yet serene, emphasizing high contrast between the brilliant sky and darkened coastal elements. The scene evokes profound peace, capturing the ephemeral beauty of twilight with photorealistic detail, ultra-high resolution, and cinematic color grading." \
  "Qwen 3.6 Plus" "Crimson Horizon Over Still Waters"

queue_job 32 \
  "An awe-inspiring mountain landscape bathed in the radiant warmth of a spectacular sunset. The towering snow-capped peaks pierce the sky, their sharp ridges illuminated by brilliant rays of tangerine and rose-gold light that pierce through scattered clouds. Valleys below are gradually swallowed by cool indigo shadows, creating a striking contrast against the fiery celestial display. A winding alpine river snakes through rocky terrain, its crystalline waters catching scattered flecks of sunlight. Wild meadow grasses in the foreground sway gently, rendered in sharp detail with subtle backlighting that creates a glowing halo effect around each blade. The atmosphere is crisp and clear, allowing distant ranges to fade into soft atmospheric blue. The composition balances grand scale with intimate foreground details, delivering a highly realistic masterpiece." \
  "Qwen 3.6 Plus" "Alpine Sunset Glow"

queue_job 33 \
  "A mesmerizing desert vista captured at the peak of a spectacular sunset, where the arid landscape transforms into a sea of molten copper and deep crimson. Vast rolling sand dunes stretch endlessly toward the horizon, their sweeping curves sculpted by relentless winds and accentuated by sharp directional lighting. The sky above is a breathtaking canvas of swirling clouds, transitioning from electric violet at the zenith to blazing peach near the horizon line. A solitary ancient Joshua tree stands in stark silhouette against the luminous backdrop, its twisted branches reaching upward like delicate calligraphy. Tiny desert wildflowers dot the immediate foreground, their textures crisp despite the fading light. The air is filled with a subtle golden haze that softens distant details. The image radiates intense warmth, featuring flawless photorealism and dramatic lighting." \
  "Qwen 3.6 Plus" "Desert Mirage at Dusk"

queue_job 34 \
  "A striking cityscape skyline silhouetted against a spectacular sunset that sets the entire urban panorama ablaze with radiant colors. Towering glass skyscrapers dominate the midground, their reflective facades mirroring the intense hues of scarlet, burnt sienna, and luminous yellow that flood the evening sky. Massive cloud formations drift lazily overhead, catching the final rays to create a dramatic lighting effect that spills over the architectural structures. Below, a calm metropolitan harbor stretches into the distance, its dark waters punctuated by gentle wakes and streaks of reflected amber light. A modern pedestrian bridge spans the foreground, its steel cables and geometric patterns rendered in sharp focus. Streetlamps begin to flicker on, introducing tiny points of warm artificial light. The composition balances modern geometry with organic atmospheric phenomena." \
  "Qwen 3.6 Plus" "Urban Twilight Reflections"

queue_job 35 \
  "A lush tropical rainforest canopy bathed in the ethereal glow of a spectacular sunset filtering through layers of dense foliage. Massive emerald-green leaves and hanging vines create a natural frame around a brilliant opening in the sky where the sun dips below the horizon. Rays of golden light pierce through the misty atmosphere, creating volumetric beams that illuminate floating pollen in the humid air. The sky reveals a gradient of deep teal fading into vibrant coral pink and soft apricot tones, partially visible through intricate interlocking branches. Exotic orchids cling to ancient tree trunks in the foreground, their delicate petals catching subtle highlights. A tranquil canopy pool reflects the fragmented sky, surrounded by moss-covered rocks. The image captures a magical balance of shadow and light with photorealistic rendering." \
  "Qwen 3.6 Plus" "Tropical Canopy at Dusk"

# --- GLM 5.1 ---
queue_job 36 \
  "A spectacular sunset over a rugged coastal cliff scene where the sky is an explosive canvas of deep crimson, vibrant tangerine, and soft lavender clouds reflecting perfectly on the churning ocean waves. Brilliant golden light pierces through dramatic cloud breaks, casting glowing god rays across the vast water. Dark silhouettes of jagged sea stacks and a distant lighthouse stand stark against the fiery horizon. The wet sand and shallow tide pools mirror the brilliant colors above, creating a seamless blend of sky and sea. Cinematic lighting, ultra-detailed, photorealistic landscape, breathtaking natural beauty, serene yet powerful energy, volumetric lighting, highly textured, masterpiece composition." \
  "GLM 5.1" "Coastal Sunset Spectacle"

queue_job 37 \
  "A spectacular sunset illuminating a majestic mountain range with sharp, snow-capped peaks glowing in intense warm alpenglow. The sky transitions smoothly from a deep indigo zenith to a fiery orange and rich magenta horizon. A pristine alpine lake sits in the quiet foreground, acting as a flawless glass mirror to the dramatic sky and towering dark pine trees. Delicate wispy cirrus clouds catch the very last rays of sunlight, turning into brilliant streaks of spun gold. The air feels crisp and cold, with a subtle mist rolling off the calm water surface. High altitude atmosphere, ultra-realistic, dramatic lighting, majestic wilderness, stunning reflections, intricate detail, breathtaking masterpiece." \
  "GLM 5.1" "Alpine Golden Hour"

queue_job 38 \
  "A spectacular sunset casting a breathtaking warm glow over a sprawling modern metropolis. The city skyline is defined by towering skyscrapers that cast long, dramatic silhouettes against the vibrant evening sky. The sleek glass facades of the buildings perfectly reflect the stunning clouds, which are painted in vivid shades of burning amber, deep purple, and rose gold. The sun sits just above the horizon, a brilliant white-hot sphere diffused by atmospheric haze. Rivers of busy traffic create golden light trails far below, while the very first evening stars begin to twinkle in the darkening upper sky. Urban landscape, cinematic atmosphere, hyper-detailed architecture, glowing reflections, vibrant color contrast, photorealistic, masterpiece." \
  "GLM 5.1" "Metropolis at Dusk"

queue_job 39 \
  "A spectacular sunset across the vast African savanna, bathing the endless golden grasslands in an incredibly rich, warm light. The sky is a dramatic display of fiery red, burnt orange, and deep violet, with massive towering anvil-shaped clouds stacked impressively on the horizon. Iconic flat-topped acacia trees stand as striking dark silhouettes against the brilliant, glowing backdrop. A distant herd of elephants is silhouetted as they walk slowly towards a watering hole, kicking up a faint trail of illuminated red dust. The atmosphere feels thick with heat and tranquil beauty, capturing the raw essence of the wild. Photorealistic, cinematic, majestic wildlife, breathtaking scenery, ultra-detailed, vivid color palette, masterpiece." \
  "GLM 5.1" "Savanna Twilight"

queue_job 40 \
  "A spectacular sunset in a magical fantasy realm, where enormous floating islands drift gracefully across a sky ablaze with luminous fuchsia, shimmering gold, and celestial teal. Cascading waterfalls pour from the edges of the airborne landmasses, catching the dying sunlight and turning into sparkling veils of golden mist. Ancient, twisted trees with glowing bioluminescent leaves frame the dark foreground, their gnarled roots clinging to mossy stones. The central sun is enormous and radiating ethereal rings of light. A distant crystal castle perched on a peak catches the final rays. Epic fantasy, magical atmosphere, hyper-detailed, volumetric lighting, breathtaking majestic scenery, digital art, masterpiece, vibrant colors." \
  "GLM 5.1" "Ethereal Fantasy Dusk"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A breathtaking spectacular sunset casting golden amber rays across jagged snow-capped mountain peaks, with the sky ablaze in vibrant gradients of crimson, tangerine, and deep violet. Wispy cirrus clouds catch fire like burning silk threads stretching across the horizon. A serene alpine lake in the foreground mirrors the celestial spectacle with perfect crystalline reflection. Soft mist rises from the valley below, catching the last warm light. The atmosphere is ethereal and majestic, with every detail rendered in ultra-high definition. Rich textures of rock, water, and atmospheric haze create depth and immersion. Cinematic lighting emphasizes the dramatic contrast between illuminated peaks and shadowed valleys. Photorealistic quality with painterly composition, evoking awe and tranquility in equal measure." \
  "Kimi K2.6 Thinking" "Golden Hour Over Mountain Peaks"

queue_job 42 \
  "A spectacular sunset over a vast rolling ocean, where the horizon bleeds into molten gold and burning copper. Towering cumulonimbus clouds explode with internal lightning, their edges rimmed with brilliant coral and magenta. The sea transforms into liquid fire, with each wave crest catching ember-like reflections. A weathered wooden pier extends into the water, its silhouette stark against the inferno sky. Seabirds wheel overhead as dark silhouettes. The air thickens with salt spray and golden atmospheric particles. Hyper-detailed water surface shows individual droplets and foam patterns. The mood is both apocalyptic and sublime, capturing nature's raw power. Volumetric god rays pierce through cloud gaps, creating dramatic chiaroscuro. Masterful color grading with deep shadows and luminous highlights, photorealistic rendering." \
  "Kimi K2.6 Thinking" "Ocean Sunset with Dramatic Clouds"

queue_job 43 \
  "An awe-inspiring spectacular sunset engulfing an endless desert landscape, where massive sandstone mesas glow from within like heated iron. The sky becomes a cathedral of color, with layers of stratocumulus painted in rose gold, burnt sienna, and royal purple. Long shadows stretch across rippled sand dunes, revealing intricate wind-sculpted patterns. Ancient saguaro cacti stand as dark sentinels against the radiant backdrop. A lone dirt road snakes toward the vanishing point, kicking up golden dust motes that catch the fading light. The temperature seems visible as heat shimmer rising from the earth. Every grain of sand sparkles with microscopic brilliance. The composition balances vast negative space with precise foreground detail. Cinematic atmosphere, hyperrealistic textures, and emotionally resonant golden hour lighting create an unforgettable vision of wilderness grandeur." \
  "Kimi K2.6 Thinking" "Desert Sunset with Silhouetted Cacti"

queue_job 44 \
  "A spectacular sunset transforming a modern metropolis into a realm of glass and fire. Skyscrapers become prismatic towers, reflecting cascading bands of tangerine, fuchsia, and indigo across their facades. The sky is a turbulent canvas of altocumulus clouds, backlit into glowing embers. Below, the city awakens with warm artificial lights that compete with the dying natural radiance. A river cuts through the urban grid, carrying streaks of reflected sunset like molten lava between concrete canyons. Pedestrians and vehicles become anonymous silhouettes in the golden haze. Atmospheric perspective softens distant architecture into pastel dreams. The image balances geometric human construction with organic celestial drama. Lens flare and bokeh effects enhance the dreamy quality. Ultra-sharp architectural details contrast with soft ethereal sky, creating a powerful juxtaposition of civilization and cosmos." \
  "Kimi K2.6 Thinking" "City Skyline at Dusk"

queue_job 45 \
  "A spectacular sunset descending upon a pristine tropical paradise, where the sky erupts in a symphony of mango, coral, and lavender hues. Majestic coconut palms lean over powder-white sand, their fronds etched as delicate black lace against the radiant firmament. The calm turquoise lagoon mirrors the heavens with such clarity that sky and water become indistinguishable. A traditional wooden outrigger canoe rests on the shore, its hull painted with reflected fire. Scattered seashells and smooth volcanic stones catch the last amber light along the tide line. Soft trade winds stir the palm crowns, suggesting motion in the stillness. The horizon glows with an almost supernatural intensity, as if the sun bleeds its final essence into the waiting ocean. Every element is rendered with breathtaking precision, from individual palm fibers to rippling water caustics. The mood is paradisiacal yet profoundly moving." \
  "Kimi K2.6 Thinking" "Tropical Beach Sunset with Palm Trees"

# --- Deepseek ---
queue_job 46 \
  "A breathtaking sunset over winding wetlands, where the sky ignites in layered bands of molten gold, fiery orange, deep magenta, and soft violet. The sun, a perfect radiant sphere, sits just above a distant tree line, casting long reflections across narrow, meandering water channels. Silhouettes of egrets and herons stand motionless in the shallows. The wetlands are lush with cattails and water lilies, their edges rimmed with warm backlight. Above, thin, wispy clouds catch the last light, resembling brushstrokes of fire. The atmosphere is calm yet electric, with a gentle mist rising from the warm water. Overall mood is serene and majestic, emphasizing the rich color gradient and the mirror-like quality of the still water." \
  "Deepseek" "A Glowing Horizon Over Serpentine Wetlands"

queue_job 47 \
  "A spectacular sunset viewed from rugged sea cliffs, with the sky exploding in shades of blood orange, rose pink, and deep purple. The sun, half-submerged on the horizon, paints a shimmering golden path across the churning ocean below. Crashing waves throw spray into the air, illuminated like liquid amber. On the cliffs, jagged rocks and hardy windswept pines are reduced to stark black silhouettes. A few seagulls glide effortlessly in the warm updraft. The clouds are dramatic and heavy, underlit in vivid reds and yellows, with streaks of rain visible in the distance. The transition from bright horizon to darkening sky is flawless. The overall feeling is wild, powerful, and awe-inspiring, capturing nature's raw beauty at the edge of day." \
  "Deepseek" "Dramatic Sea Cliffs in Crimson Twilight"

queue_job 48 \
  "A magnificent sunset spreading across a vast savanna dotted with ancient, sprawling oak trees. The sky is a masterful blend of honeyed yellow, apricot, lavender, and dusky blue. The sun, low and brilliant, casts long, soft shadows across tall golden grass that sways gently in the evening breeze. Each oak tree is a complex silhouette of twisted branches and full canopies, with tiny gaps of light peeking through. In the distance, a herd of deer grazes quietly, their forms backlit and glowing. The foreground features wildflowers — black-eyed Susans and purple asters — edged in warm light. Thin, horizontal clouds near the horizon glow like molten metal. The mood is peaceful, nostalgic, and deeply warm, with a rich tonal range from bright highlights to velvety shadows." \
  "Deepseek" "Golden Hour Over an Ancient Oak Savanna"

queue_job 49 \
  "A spectacular sunset over a calm alpine lake surrounded by towering, snow-capped peaks. The sky transitions smoothly from pale lemon yellow near the horizon to soft peach, dusty rose, and finally a gentle periwinkle blue at the zenith. The sun has just dipped below the ridgeline, leaving a glowing golden crown on the mountaintops. The lake is a perfect mirror, reflecting every cloud and color with stunning clarity, doubling the visual impact. Small clusters of white and purple wildflowers line the rocky shore. A single wooden rowboat is beached on a small gravel bar, adding a human touch. The air is crisp and clean, with a hint of alpenglow on the highest peaks. Overall, the scene is ethereal, quiet, and perfectly symmetrical, evoking a sense of wonder and stillness." \
  "Deepseek" "Alpine Lake Reflecting a Pastel Sunset"

queue_job 50 \
  "A dramatic sunset over sweeping desert dunes, where the sky is a riot of vermilion, tangerine, magenta, and indigo. The setting sun sits low behind the highest dune crest, casting a brilliant fan of light rays upward and sideways. The dunes themselves have sharp, sinuous ridgelines, with warm light kissing the windward slopes while the leeward sides fall into deep shadow. In the foreground, a lone saguaro cactus and scattered desert rocks form stark silhouettes. As the light fades, the first bright stars and a crescent moon appear in the darkening upper sky, creating a stunning juxtaposition of sunset and night sky. Tiny dust particles in the air catch the red light, creating a faint glowing haze. The mood is exotic, expansive, and slightly mystical, with rich contrast and vibrant, saturated hues." \
  "Deepseek" "Desert Dunes Under a Star-Spangled Sunset"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A breathtaking sunset over the Pacific Ocean with towering cumulonimbus clouds illuminated in deep crimson, burnt orange, and molten gold. The sun sits low on the horizon casting an intense reflection across the calm water surface. Waves gently roll toward the shore catching the warm light. Silhouettes of distant cargo ships line the horizon. The sky transitions from electric violet at the top to fiery red near the waterline. Dramatic god rays pierce through gaps in the cloud formations. The entire scene evokes a sense of awe and tranquility. Photorealistic, ultra detailed, cinematic lighting, 8k quality, masterpiece composition with rich color saturation." \
  "ERNIE 5.1 Thinking" "Crimson Horizon Over the Pacific"

queue_job 52 \
  "A magnificent sunset over an alpine lake with snow-capped mountain peaks reflected perfectly in the still water. The sky is painted in layers of warm amber, soft peach, and deep magenta. Golden light bathes the rocky shoreline and scattered wildflowers. A few wispy clouds catch the last rays of sunlight glowing in brilliant orange. The mountains cast long purple shadows across the valley below. The water surface acts as a perfect mirror doubling the spectacular colors above. Thin mist rises gently from the lake adding ethereal atmosphere throughout the entire scene. Ultra realistic landscape photography, sharp focus, vivid colors, golden hour magic." \
  "ERNIE 5.1 Thinking" "Alpine Lake Golden Hour"

queue_job 53 \
  "A stunning sunset viewed from a rooftop overlooking a massive city skyline. The sun hangs just above the horizon painting the sky in intense shades of tangerine, coral pink, and deep purple. Skyscrapers stand as dark silhouettes against the blazing backdrop. Glass windows on buildings reflect the warm sunset colors creating a dazzling effect. Below, busy streets begin to glow with artificial city lights mixing with the fading natural light. A few high-altitude clouds streak across the sky in brilliant gold. The atmosphere is hazy adding depth and warmth to the urban panorama. Photorealistic, dramatic contrast, high dynamic range, cinematic urban landscape." \
  "ERNIE 5.1 Thinking" "City Skyline Ablaze"

queue_job 54 \
  "An extraordinary sunset over vast rolling sand dunes in the Sahara desert. The sky explodes with colors ranging from deep crimson to bright tangerine and soft lavender. The sun is a perfect glowing orb sinking behind the highest dune ridge casting dramatic elongated shadows across the golden sand. Wind-sculpted dune patterns create mesmerizing textures highlighted by the low-angle light. The horizon glows with an intense band of fiery orange while the upper sky fades into deep indigo. A lone camel caravan silhouette crosses a distant ridge adding scale and narrative. The sand glows warm amber under the fading light. Hyper realistic, fine detail, National Geographic style, stunning natural beauty." \
  "ERNIE 5.1 Thinking" "Desert Dunes at Dusk"

queue_job 55 \
  "A glorious sunset over a tropical beach with tall coconut palm trees swaying gently in the warm breeze. The sun dips below the ocean horizon creating a spectacular display of fiery orange, hot pink, and golden yellow. The ocean waves are calm and glassy reflecting the vivid sky like a painted canvas. Tropical clouds are scattered across the sky glowing in shades of coral and magenta. A wooden pier extends into the water with a hammock strung between two posts silhouetted against the glowing sky. Seagulls fly across the frame adding dynamic movement. The beach sand is wet and mirror-like from the receding tide. Lush green vegetation frames the scene. Vibrant colors, ultra detailed, paradise atmosphere, award-winning photography." \
  "ERNIE 5.1 Thinking" "Tropical Paradise Twilight"

echo "✅ All 55 jobs queued in scheduler"
