#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Office — stock-style corporate photography, diverse people working
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+24+-+Office
# Structure: 11 models × 5 prompts = 55 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A young Black woman in her late 20s sits at a modern office desk, focused on a dual-monitor workstation. She wears a navy blue blazer over a white blouse, hair pulled back neatly. The desk is organized with a notebook, coffee mug, and scattered papers. Soft natural light streams through large windows behind her. The office background shows open-plan workspace with blurred colleagues and plants. Realistic corporate photography style, sharp focus on subject, shallow depth of field, professional color grading, warm neutral tones, natural daylight mixed with overhead fluorescent, photorealistic, stock photo quality, no text, no logos." \
  "Claude Sonnet 4.6" "Office Worker at Desk – Focused Solo Shot"

queue_job  2 \
  "Five colleagues gathered around a glass conference table in a bright modern boardroom. Mixed group: a middle-aged Hispanic man standing and presenting at a whiteboard, two Asian women taking notes, a bearded white man in his 30s leaning forward attentively, and an older Black woman reviewing printed documents. Laptops, water bottles, and notepads on the table. Floor-to-ceiling windows with city view behind. Professional corporate photography, candid natural poses, even diffused lighting, photorealistic, stock photo quality, sharp focus, neutral warm tones, no text overlays." \
  "Claude Sonnet 4.6" "Team Meeting Around Conference Table"

queue_job  3 \
  "Two coworkers on a casual coffee break in a modern office kitchen area. A tall white man in his 40s in business casual attire laughs while holding a ceramic mug. Beside him stands a young South Asian woman in a colorful blazer, smiling and gesturing mid-conversation. Bright kitchen with white cabinets, coffee machine, fruit bowl, and potted herbs on the counter. Candid lifestyle corporate photography, natural soft light from nearby window, warm tones, shallow depth of field, photorealistic, clean stock photo aesthetic, no text, no logos." \
  "Claude Sonnet 4.6" "Coffee Break in Office Kitchen"

queue_job  4 \
  "A woman in her early 30s of Middle Eastern appearance works intently on a laptop at a standing desk in a contemporary open-plan office. She wears a light grey turtleneck and small gold earrings, expression concentrated. Behind her, blurred coworkers at desks, exposed concrete ceiling, hanging pendant lights, indoor plants in large pots. Warm afternoon light, professional editorial photography style, sharp subject against soft bokeh background, realistic skin tones, neutral color palette, photorealistic, stock photo quality, no text." \
  "Claude Sonnet 4.6" "Focused Woman Working on Laptop in Open Office"

queue_job  5 \
  "Three colleagues in an informal brainstorm huddle beside a glass wall covered in sticky notes and handwritten diagrams. A young Black man in a hoodie and jeans holds a marker and gestures toward the wall. Next to him, a red-haired white woman in her 30s with glasses holds a tablet, and a stocky Latino man in a plaid shirt reviews a printed sheet. Casual collaborative energy, candid shot, bright open office, diffused daylight from skylights, photorealistic, stock photography style, natural expressions, no text visible on notes, clean corporate aesthetic." \
  "Claude Sonnet 4.6" "Small Group Casual Brainstorm Session"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A bright, modern corporate office during midday. A diverse creative team of three people — a Black woman with curly hair wearing a vibrant blazer, an Asian man in a smart-casual sweater, and a Caucasian man with a beard — are gathered around a wooden table. They are deeply engaged in a collaborative brainstorming session, smiling and looking at colorful sticky notes spread across the desk. Sunlight streams through massive floor-to-ceiling windows, illuminating the contemporary workplace. In the background, other glass-walled meeting rooms and subtle indoor plants are softly blurred. The shot is a professional, high-quality stock photo taken from a medium angle with natural lighting, sharp focus, clean composition, and a warm, inviting corporate atmosphere that emphasizes teamwork and workplace productivity." \
  "Gemini 3.5 Flash" "Creative Brainstorming in a Sunny Workspace"

queue_job  7 \
  "A focused South Asian female software engineer sits alone at her clean, minimalist desk in a sleek corporate office environment. She is wearing professional neutral attire and modern glasses, looking intently at a sleek dual-monitor setup displaying lines of clean code and data charts. Her hands rest naturally on a mechanical keyboard. A ceramic mug with subtle steam rising from it and a neat notebook sit beside her. The background shows a beautifully defocused open-plan office with soft, ambient overhead lighting and geometric architecture. This is a crisp, commercial stock photograph featuring a shallow depth of field, realistic textures, cinematic office lighting, and an authentic corporate professional vibe highlighting individual concentration and daily dedication." \
  "Gemini 3.5 Flash" "Productive Solo Focus at a Modern Desk"

queue_job  8 \
  "A realistic, professional stock photo capturing an ongoing business meeting inside a sophisticated glass boardroom. A diverse group of four corporate professionals, including a Hispanic man in a tailored grey suit gesturing during a presentation, a Middle Eastern woman taking notes on a digital tablet, and two other colleagues listening intently, are seated around a polished mahogany conference table. A high-tech presentation screen displays colorful quarterly growth charts on the wall behind them. The room is bright, blending clean overhead linear LED lights with natural daylight. The image features a wide-angle perspective, balanced color grading, sharp textures on fabrics and surfaces, and a genuine, high-end corporate culture aesthetic." \
  "Gemini 3.5 Flash" "Informal Collaborative Meeting in the Boardroom"

queue_job  9 \
  "A candid corporate stock photograph of a relaxed coffee break in a stylish, open-concept office cafeteria lounge. A Caucasian woman with blonde hair in a business-casual blouse and an East Asian man in a crisp white button-down shirt are standing near a modern espresso machine. They are holding ceramic coffee mugs, laughing and sharing a genuine friendly conversation. The background features a stylish breakout zone with comfortable contemporary armchairs, wooden accents, and a blurred view of a bustling office floor in the distance. The lighting is soft and warm, casting a welcoming glow. The composition uses a medium close-up shot with a beautiful bokeh effect, sharp details on the foreground subjects, and an authentic workplace wellness atmosphere." \
  "Gemini 3.5 Flash" "Relaxed Coffee Break Conversation in the Lounge"

queue_job 10 \
  "A powerful close-up stock portrait of an elegant Black male executive standing confidently in a brightly lit, high-end corporate hallway. He is dressed in a sharp, impeccably tailored navy blue suit with a white shirt and a silk tie, holding a premium leather folder in his arm. He has a determined, professional expression, looking slightly off-camera with purpose. The background is a beautifully blurred corridor of a contemporary skyscraper, featuring reflective glass panels, steel structures, and soft architectural lighting that creates a sophisticated depth. The photograph is shot with premium cinematic quality, rich color depth, perfect contrast, and razor-sharp detail on his features, perfectly embodying corporate leadership, ambition, and modern business excellence." \
  "Gemini 3.5 Flash" "Anxious Determination Before the Big Presentation"

# --- ChatGPT ---
queue_job 11 \
  "A bright, modern office with floor-to-ceiling glass walls overlooking a city skyline. A diverse group of professionals of different genders and ethnic backgrounds sits around a large wooden conference table, engaged in a collaborative meeting. Some are taking notes on laptops, others gesturing while speaking. Natural daylight floods the space, reflecting softly on polished surfaces. Subtle details like coffee cups, notebooks, and digital tablets enhance realism. Business attire varies from formal suits to smart casual. Expressions are focused yet relaxed, conveying productivity and teamwork. Depth of field emphasizes the speaker while others are slightly blurred. Clean composition, realistic lighting, and authentic corporate atmosphere, styled like a high-end stock photo." \
  "ChatGPT" "Corporate Team Meeting in Modern Glass Office"

queue_job 12 \
  "An open-plan office environment where several coworkers gather around a small coffee station. The scene captures a candid moment: people chatting, laughing, and holding coffee mugs. The group is diverse in gender, age, and ethnicity, dressed in relaxed business casual attire. Background elements include desks with computers, indoor plants, and soft ambient lighting. A large window allows natural light to illuminate the scene, creating soft shadows. One person leans against the counter, another checks their phone, while others engage in conversation. The mood is friendly and informal, emphasizing workplace culture and human connection. Photorealistic style with attention to everyday office details, like paper cups, sugar packets, and subtle reflections." \
  "ChatGPT" "Casual Coffee Break in Open Workspace"

queue_job 13 \
  "A single professional sits at a minimalist desk in a quiet office corner, deeply focused on their work. The person, gender-neutral and ethnically ambiguous, types on a laptop with a concentrated expression. The workspace includes a monitor, a desk lamp, a notebook, and a cup of coffee. Soft natural light streams in from a nearby window, casting gentle highlights and shadows. The background is slightly blurred, suggesting a larger office space without distraction. The atmosphere conveys calm productivity and concentration. Clean composition with a centered subject, neutral tones, and realistic textures. Subtle imperfections like slightly messy papers or a tilted chair add authenticity to this stock-style corporate image." \
  "ChatGPT" "Focused Individual Working at Desk"

queue_job 14 \
  "A dynamic office setting where a small team collaborates around a whiteboard filled with notes, sketches, and diagrams. The group is diverse in gender and ethnicity, dressed in semi-casual work attire. One person stands and writes on the board while others sit or stand nearby, discussing ideas. Expressions are animated and engaged, capturing a moment of creative energy. The room features modern office furniture, sticky notes, markers, and a mix of digital and analog tools. Lighting is bright and even, with a slightly warm tone to enhance approachability. Composition balances all subjects while maintaining a natural candid feel. Photorealistic, resembling a professional stock photo used for business and innovation themes." \
  "ChatGPT" "Brainstorming Session with Creative Team"

queue_job 15 \
  "Two coworkers sit side by side at a shared desk, collaborating on a project. One points at a laptop screen while the other listens attentively, creating a natural interaction. Both individuals represent different genders and ethnic backgrounds, dressed in modern office attire. The desk is organized with documents, a tablet, and a coffee mug. The surrounding office space includes other desks and blurred figures working in the background. Lighting combines natural daylight and soft indoor illumination, producing a balanced and realistic tone. The mood is cooperative and focused, highlighting teamwork and communication. The composition is slightly angled for depth, with sharp detail on the main subjects and a gentle background blur." \
  "ChatGPT" "Office Collaboration at Shared Desk"

# --- Grok ---
queue_job 16 \
  "A diverse group of professionals in a bright modern office conference room, three women and two men of different ethnic backgrounds including Asian, Black, Caucasian, and Hispanic, sitting around a large wooden table discussing ideas, one woman presenting at a whiteboard with charts, others taking notes on laptops, casual business attire, natural daylight from large windows, potted plants, professional yet relaxed atmosphere, high detail, realistic stock photo style, sharp focus, 8k quality." \
  "Grok" "Modern Office Meeting in Progress"

queue_job 17 \
  "A young East Asian woman in her 30s working concentrated at her ergonomic desk in a contemporary open-plan office, wearing glasses and a white blouse, multiple computer monitors displaying data and graphs, notebook and coffee mug nearby, soft natural lighting, blurred busy office background with colleagues working, tidy and organized workspace, realistic corporate stock photography, highly detailed, photorealistic." \
  "Grok" "Focused Professional at Workspace"

queue_job 18 \
  "Diverse colleagues enjoying coffee break in a sunny office kitchen lounge area, a Black man and a Caucasian woman laughing while standing near the coffee machine, another Hispanic man checking his phone, casual business clothes, fresh pastries on the counter, modern kitchen with large windows, relaxed and friendly atmosphere, natural interaction, realistic office stock photo style, vibrant colors, sharp details." \
  "Grok" "Office Coffee Break Conversation"

queue_job 19 \
  "Multi-ethnic team of six professionals collaborating in an open office creative space, mixed genders including two men and four women from various backgrounds, standing around a large whiteboard covered with colorful sticky notes and diagrams, pointing and discussing actively, laptops open on nearby tables, energetic and engaged expressions, bright modern office environment with plants and big windows, photorealistic stock image." \
  "Grok" "Collaborative Team Brainstorming Session"

queue_job 20 \
  "A middle-aged South Asian man working diligently at his desk in a bustling open-plan office, wearing a blue shirt with rolled sleeves, focused on coding on dual monitors, headphones on, coffee cup and family photo on desk, other diverse colleagues visible working in background, soft overhead lighting mixed with daylight, professional and productive atmosphere, realistic corporate photography, high resolution details." \
  "Grok" "Individual Work Focus in Open Office"

# --- Copilot ---
queue_job 21 \
  "A diverse group of colleagues gathered around a modern office table, engaged in an energetic brainstorming session. Laptops, notebooks, and coffee cups are scattered across the table. Some participants are speaking passionately, while others listen attentively, nodding and taking notes. The office has large windows with natural light streaming in, creating a professional yet collaborative atmosphere. The scene conveys teamwork, creativity, and inclusivity, with men and women of different ethnic backgrounds contributing ideas in a dynamic corporate environment." \
  "Copilot" "Team Brainstorming Session"

queue_job 22 \
  "Two coworkers, one male and one female of different ethnicities, standing near a sleek office coffee machine, chatting casually while holding mugs. The atmosphere is relaxed, with smiles and friendly gestures. Behind them, shelves with office supplies and a bulletin board add realism. The lighting is warm, suggesting a mid-morning break. Their business casual attire reflects a professional yet approachable environment, emphasizing camaraderie and workplace balance." \
  "Copilot" "Casual Coffee Break"

queue_job 23 \
  "A young professional woman seated at her desk in a modern office, deeply focused on her computer screen. Papers, a smartphone, and a cup of tea are neatly arranged beside her. The background shows bookshelves and a potted plant, adding a touch of personality to the workspace. Her posture is upright, with an expression of concentration, highlighting productivity and dedication. The scene conveys determination and individual effort in a corporate setting." \
  "Copilot" "Focused Solo Work"

queue_job 24 \
  "A male manager of Asian descent standing at the front of a conference room, presenting slides on a large screen to a mixed-gender, multicultural team seated around the table. The audience is engaged, some taking notes, others asking questions. The room is bright, with glass walls and modern furniture. The presenter gestures confidently, emphasizing key points, while the team collaborates and discusses strategies. The atmosphere is professional, dynamic, and inclusive." \
  "Copilot" "Team Meeting Presentation"

queue_job 25 \
  "Two female colleagues, one Black and one White, working side by side at a shared desk. They are reviewing documents together, pointing at charts and graphs displayed on a laptop. Their expressions show focus and cooperation. The office background includes filing cabinets, plants, and motivational posters. The scene conveys teamwork, problem-solving, and diversity in a professional environment, highlighting the importance of collaboration in achieving goals." \
  "Copilot" "Collaborative Desk Work"

# --- Mistral ---
queue_job 26 \
  "A professional, high-resolution stock photo of a diverse team of 5 office workers (mixed genders, ethnicities, and ages) collaborating around a modern glass-top meeting table in a bright, open-plan office. The scene captures natural, candid moments: one person gesturing while explaining an idea, another taking notes on a laptop, and a third pointing at a whiteboard with colorful diagrams. The office has large windows with soft daylight streaming in, potted plants, and neutral-toned furniture. The atmosphere is energetic yet focused, with subtle details like coffee cups, notepads, and a digital tablet on the table. The lighting is warm and even, with no harsh shadows, and the image has a shallow depth of field to emphasize the team while softly blurring the background." \
  "Mistral" "Office Team Collaboration"

queue_job 27 \
  "A lively, candid stock photo of 3 colleagues (a woman in her 30s, a man in his 40s, and a non-binary person in their 20s) enjoying a coffee break in a sleek office kitchenette. They are standing around a high counter, holding mugs and laughing naturally, with one person gesturing animatedly while the others listen attentively. The kitchenette has a coffee machine, a microwave, and a fridge in the background, with warm overhead lighting and a cozy, inviting atmosphere. The image is sharp, with vibrant yet natural colors, and captures the genuine camaraderie and relaxed energy of a workplace break." \
  "Mistral" "Coffee Break Conversation"

queue_job 28 \
  "A clean, minimalist stock photo of a single professional (a Black woman in her late 20s) deeply focused on her work at a tidy desk in a modern office. She is wearing business casual attire and typing on a laptop, with a second monitor displaying a spreadsheet. The desk has a small potted plant, a wireless mouse, a notebook, and a stylish desk lamp providing soft, warm light. The background features a blurred view of cubicles and other workers, emphasizing her concentration. The image is well-lit, with balanced exposure and a neutral color palette, conveying productivity and calm." \
  "Mistral" "Focused Solo Work"

queue_job 29 \
  "A dynamic stock photo of a diverse group of 4 office workers (2 men, 1 woman, and 1 non-binary individual) engaged in a brainstorming session in a creative meeting room. They are standing around a large whiteboard covered in colorful sticky notes, diagrams, and handwritten ideas. One person is holding a marker, mid-writing, while the others discuss animatedly, with one pointing at the board. The room has a modern design with a glass wall, natural light, and ergonomic chairs. The image is bright, with high contrast and sharp details, capturing the energy and collaboration of the moment." \
  "Mistral" "Brainstorming Session"

queue_job 30 \
  "A warm, candid stock photo of two colleagues (a man in his 50s and a woman in her 30s) having a casual one-on-one discussion in a cozy corner of an office. They are seated on comfortable armchairs with a small round table between them, holding tablets and coffee cups. The background features a bookshelf with professional books and decorative items, and a large window with soft daylight. The image has a shallow depth of field, with the subjects in sharp focus and the background slightly blurred, creating a professional yet approachable atmosphere. The lighting is natural, and the colors are balanced and inviting." \
  "Mistral" "Casual Office Discussion"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A photorealistic stock-style image of a diverse group of five professionals gathered around a sleek white conference table in a bright, modern open-plan office. Two women of South Asian descent and three men of varying ages and ethnic backgrounds lean in, actively pointing at a large digital monitor displaying colorful bar charts and growth projections. Natural sunlight streams through floor-to-ceiling windows, softly illuminating their focused expressions and smart casual business attire. Lush potted indoor plants and minimalist wooden furniture accent the clean corporate aesthetic, capturing a highly authentic moment of productive teamwork and strategic corporate discussion. High-quality cinematic lighting, sharp focus on the participants, professional workplace atmosphere." \
  "Qwen 3.6 Plus" "Collaborative Team Meeting"

queue_job 32 \
  "A high-quality corporate stock photograph featuring a young Hispanic woman sitting alone at an ergonomic standing desk in a contemporary tech startup office. She wears a light blue button-down shirt and stylish rectangular glasses while typing intently on a wireless keyboard connected to dual flat-screen monitors showing complex spreadsheet data. A steaming ceramic mug of black coffee and a neatly organized stack of printed reports rest beside her silver laptop. Soft diffused overhead lighting and subtly blurred background elements of walking colleagues create a strong sense of depth and professional isolation. The balanced composition emphasizes deep concentration and modern workplace productivity." \
  "Qwen 3.6 Plus" "Focused Individual at Work"

queue_job 33 \
  "A vibrant and highly realistic stock image capturing a relaxed morning coffee break scenario in a spacious, well-lit corporate breakroom. Three colleagues — an older Black male executive in a tailored charcoal suit, a middle-aged White woman holding a digital tablet, and a young East Asian man in a casual polo shirt — stand comfortably near a sleek stainless-steel espresso machine. They are genuinely laughing and chatting casually while holding white ceramic mugs of hot cappuccino. Warm ambient lighting highlights the rich textures of the polished wooden countertop, the glossy marble floor tiles, and a wall-mounted television displaying company announcements. The scene radiates a friendly, inclusive corporate culture." \
  "Qwen 3.6 Plus" "Casual Coffee Break Conversation"

queue_job 34 \
  "A crisp professional stock photograph depicting a highly dynamic brainstorming session inside a modern glass-walled conference room. A diverse team of four creative professionals stands closely together facing a large magnetic whiteboard completely covered in colorful sticky notes, detailed flowcharts, and handwritten quarterly strategy goals. A mixed-race female facilitator wearing a vibrant emerald blouse confidently uses a black dry-erase marker to draw an innovative architectural concept while her attentive peers observe closely. The stylish room features polished concrete floors, comfortable gray lounge chairs, and expansive windows overlooking a sunny city skyline. The composition perfectly balances energetic action with visual clarity." \
  "Qwen 3.6 Plus" "Brainstorming at the Whiteboard"

queue_job 35 \
  "A polished corporate stock photo showing an intimate one-on-one mentorship meeting between two dedicated professionals in a quiet corner of a contemporary office library space. An experienced South Asian male manager in a crisp navy blazer leans forward across a round mahogany table, actively offering career guidance to a younger non-binary employee with short blonde hair and a smart gray wool cardigan. Both individuals hold open leather-bound notebooks and silver pens, deeply engaging in a constructive and thoughtful discussion. Soft natural light filters through nearby wooden bookshelves densely filled with industry journals and binders, creating a calm academic corporate environment focused on continuous professional growth." \
  "Qwen 3.6 Plus" "One-on-One Mentorship Session"

# --- GLM 5.1 ---
queue_job 36 \
  "High-quality professional stock photography of a diverse team actively participating in a business meeting inside a modern, sunlit glass-walled conference room. A Black woman in a smart navy blazer is standing and presenting ideas using a digital whiteboard, gesturing confidently. Seated around a sleek oval wooden table, her colleagues are engaged: an Asian man in a crisp white shirt taking notes on a tablet, a Hispanic woman nodding and smiling warmly while holding a pen, and a White man in a business-casual polo listening attentively with his arms resting on the table. Coffee cups, notepads, and a small potted plant are neatly arranged on the table. Bright, natural morning light filters through the floor-to-ceiling windows, creating a welcoming and productive corporate atmosphere. Sharp focus, photorealistic, highly detailed." \
  "GLM 5.1" "Diverse Team Brainstorming Meeting"

queue_job 37 \
  "Authentic stock photo of a young South Asian woman working focused at her modern standing desk in a contemporary open-plan office. She is wearing a stylish yet comfortable knit sweater and glasses, intently looking at her dual computer monitors while typing on a wireless keyboard. A steaming mug of tea, a small succulent plant, and neatly organized folders sit beside her. Soft, warm ambient lighting from a desk lamp blends with the cool daylight from nearby windows. The background features a slightly blurred office space with lush green office plants and warm wooden accents, conveying a calm and productive work environment. Cinematic lighting, ultra-realistic, 85mm lens, shallow depth of field." \
  "GLM 5.1" "Focused Professional at Desk"

queue_job 38 \
  "Candid lifestyle stock photograph of diverse colleagues enjoying a casual coffee break in a bright, modern office breakroom. A Middle Eastern man in a rolled-up sleeves shirt is pouring coffee from a high-end espresso machine, laughing at a joke. Next to him, an East Asian woman leaning against the marble countertop holds a ceramic mug, smiling warmly. Across from them, a Black woman in a stylish cardigan and a Latino man in a polo shirt are engaged in a friendly conversation. The kitchen features white cabinets, a stainless steel refrigerator, and vibrant indoor plants. Natural light floods the room, highlighting the relaxed, sociable, and inclusive corporate culture. Crisp details, photorealistic, natural color palette." \
  "GLM 5.1" "Casual Coffee Break Chat"

queue_job 39 \
  "Professional corporate stock photo of two colleagues collaborating closely at a modern office workstation. A White man in a crisp button-down shirt and a Black woman in a tailored burgundy blazer are standing together, reviewing a printed document laid out on the wide desk. The woman is pointing at a specific data graph on the paper with a silver pen, explaining a detail, while the man looks on thoughtfully, his chin resting on his hand. The desk features a large ultrawide monitor, a sleek keyboard, and colorful scattered sticky notes. The background is a softly blurred modern office interior with glass partitions, contemporary art, and warm ambient lighting. The atmosphere conveys teamwork, focus, and professional synergy. Ultra-detailed, photorealistic, natural lighting." \
  "GLM 5.1" "Collaborative Document Review"

queue_job 40 \
  "Lifestyle stock photograph of a confident mature Latina woman taking a business call in a stylish, modern office lounge area. She is seated on a comfortable mid-century modern armchair, wearing a professional beige turtleneck and tailored trousers. She holds a smartphone to her ear with one hand and has a small notebook in her lap. Her expression is focused and agreeable, showing active listening. Beside her is a small side table with a laptop and a glass of water. The background features a beautifully designed office lounge with bookshelves, wooden slats, and lush hanging plants. Soft diffused daylight creates a warm and inviting atmosphere. Highly realistic, sharp focus, professional corporate photography." \
  "GLM 5.1" "Business Call in Office Lounge"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A diverse group of five professionals gathered around a large whiteboard in a bright modern office space, actively brainstorming creative ideas with colorful sticky notes arranged in clusters. The collaborative team includes an Asian woman in a navy blazer pointing at the board, a Black man in glasses taking notes on a digital tablet, a Hispanic woman with curly hair holding a coffee cup, a Caucasian man with a beard sketching diagrams with a marker, and a Middle Eastern woman smiling while contributing innovative ideas. Natural sunlight streams through large floor-to-ceiling windows. Clean minimalist interior design with green plants, ergonomic furniture, and soft neutral tones. Professional corporate atmosphere, sharp focus, photorealistic, high detail, 8k quality, stock photography style, balanced composition." \
  "Kimi K2.6 Thinking" "Diverse Team Brainstorming in Modern Office"

queue_job 42 \
  "A confident Black businesswoman working at a modern standing desk in a contemporary open-plan office, typing on a sleek silver laptop while reviewing printed documents spread neatly beside her. She wears a professional burgundy blouse and delicate pearl earrings, her hair styled in neat braids. Behind her, glass meeting rooms and diverse colleagues working diligently at their stations are softly blurred. Warm ambient lighting illuminates the clean minimalist workspace featuring a wireless keyboard, small potted succulent, and ceramic coffee mug. The scene conveys productivity, determination, and professional focus. Sharp photorealistic details, natural skin tones, corporate lifestyle photography, soft bokeh background, neutral color palette with warm accents, high resolution, professional stock photo aesthetic." \
  "Kimi K2.6 Thinking" "Professional Woman Working at Standing Desk"

queue_job 43 \
  "Three coworkers of different ethnicities laughing together during a relaxed coffee break in a stylish office kitchenette and lounge area. A South Asian man in a light gray sweater holds a ceramic coffee mug, a Caucasian woman with auburn hair carries a small plate of fresh pastries, and an East Asian man in a blue button-down shirt leans casually against a white marble countertop. Modern stainless steel appliances, wooden open shelves with trailing green plants, and warm copper pendant lighting create an inviting contemporary atmosphere. Genuine expressions of friendship and authentic workplace camaraderie. Soft natural light streams from a nearby large window. Photorealistic corporate lifestyle shot, shallow depth of field, authentic emotions, neutral and warm tones, high detail, professional stock photography quality." \
  "Kimi K2.6 Thinking" "Colleagues Enjoying Coffee Break Together"

queue_job 44 \
  "A professional head-and-shoulders portrait of a mixed-race young man with warm brown skin and short dark hair, wearing a crisp white dress shirt and a subtle silver wristwatch. He stands confidently in a modern office corridor with blurred glass walls and soft ambient lighting in the background. His expression is friendly and approachable with a slight genuine smile, looking directly at the camera with confident relaxed posture. Clean architectural lines and neutral gray tones complement the subject perfectly. Sharp focus on facial features with beautiful natural skin texture and catchlights in his eyes. Photorealistic corporate portrait photography, soft diffused lighting, minimal retouching, authentic professional appearance, high resolution stock photo aesthetic." \
  "Kimi K2.6 Thinking" "Mixed Race Professional Portrait in Office"

queue_job 45 \
  "A multicultural team of six professionals engaged in a productive meeting around a large oak conference table in an executive boardroom with panoramic city views. Participants include a Caucasian woman with blonde hair presenting data on a large screen, a Black man in a charcoal suit listening intently with arms crossed, an Asian man in glasses reviewing printed papers, a Hispanic woman taking detailed notes on a digital tablet, a Middle Eastern man with a neat beard asking thoughtful questions, and a senior Caucasian man with gray hair moderating the discussion. Floor-to-ceiling windows reveal an impressive city skyline at midday. Professional lighting, sharp business suits, attentive body language. Photorealistic, high detail, corporate stock photography, balanced composition, neutral sophisticated color palette, 8k quality." \
  "Kimi K2.6 Thinking" "Multicultural Team Meeting Around Conference Table"

# --- Deepseek ---
queue_job 46 \
  "Bright, airy modern office with large windows letting in natural light. A diverse team of four professionals gathered around a glass conference table: a Black woman in her 30s presenting on a laptop, a white man in his 40s taking notes, a South Asian man in his 20s pointing at a whiteboard, and a Latina woman in her 50s smiling and nodding. Casual business attire, smart casual. The room has potted plants, a whiteboard with charts, and digital screens. Warm, inviting atmosphere. Natural expressions, engaged conversation. High resolution, stock photo style, commercial quality, well-lit, no shadows on faces." \
  "Deepseek" "Collaborative Meeting in Modern Office"

queue_job 47 \
  "A young East Asian woman in her late 20s sits at a clean, ergonomic desk in a contemporary open-plan office. She wears headphones and smiles slightly while typing on a sleek keyboard, dual monitors showing spreadsheets and creative software. Her desk has a coffee mug, notebook, and a small succulent. Behind her, blurred background of other cubicles with diverse colleagues working. Soft overhead lighting combined with desk lamp. She looks productive and content. Neutral color palette: gray, white, teal accents. Photorealistic, candid moment, like a stock photo for workplace well-being. No clutter, professional environment." \
  "Deepseek" "Focused Individual Work at Desk"

queue_job 48 \
  "Spacious office breakroom with stainless steel appliances and a wooden communal table. Three colleagues enjoying a coffee break: a Middle Eastern man in his 30s pouring coffee from a French press, a Black woman in her 40s laughing while holding a mug, and a white woman in her 20s leaning on the counter with a pastry. Another person entering frame carrying a reusable water bottle. Natural smiles, relaxed poses. Bright LED lighting, plants on windowsill, a bulletin board with sticky notes. Casual clothes: sweaters, button-downs, jeans. Inclusive and friendly vibe. High quality, sharp focus, stock photography aesthetic, warm color temperature." \
  "Deepseek" "Casual Coffee Break in Office Kitchen"

queue_job 49 \
  "A mixed-gender, multi-ethnic team of five standing around a large whiteboard in a well-equipped conference room. A Black man in his 30s writes with a marker, explaining a diagram. A white woman in her 50s leans forward, pointing. A South Asian woman in her 20s holds a tablet, looking interested. Two others observing: a Hispanic man and an East Asian man. Post-it notes cover the board, colorful markers on the tray. Laptops and coffee cups on the table. Bright overhead light, gray rolling chairs. Dynamic, collaborative energy. Photorealistic, editorial style, diverse ages and ethnicities, professional setting." \
  "Deepseek" "Brainstorming Session with Whiteboard"

queue_job 50 \
  "A senior white man with gray hair in his 60s works on a laptop while sitting on a modern sofa in a casual lounge area of an office. Next to him, a young Black man in his 20s reads a document on a tablet. Across from them, a Hispanic woman in her 30s takes a phone call while walking past. The open office has colorful acoustic panels, standing desks, and large windows showing city skyline. Natural light, soft shadows. People in background: blurred activity. The man on the sofa wears a casual blazer and glasses, typing with concentration. Stock photo feel, authentic workplace diversity, no extreme poses, professional but relaxed atmosphere." \
  "Deepseek" "Working on Laptop in Open Office"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A professional stock photo of a diverse group of five colleagues sitting around a sleek modern conference table in a bright boardroom. The team includes two women and three men of different ethnic backgrounds. One woman is presenting data on a large screen while others take notes attentively. Natural daylight streams through floor-to-ceiling windows. Everyone is dressed in smart casual business attire. Laptops, notebooks, and coffee cups are scattered on the table. The atmosphere is collaborative and focused. Shot with a wide-angle lens, sharp focus, corporate photography style, neutral color palette, clean and polished look." \
  "ERNIE 5.1 Thinking" "Diverse Team in a Modern Boardroom Meeting"

queue_job 52 \
  "A stock photograph of a young Black woman sitting at her modern office desk, deeply focused on her computer screen while typing. She wears a navy blazer over a white blouse and has wireless earbuds in. The desk is neatly organized with a laptop, a small succulent plant, a leather notebook, a pen, and a reusable water bottle. Soft natural light fills the open-plan office background with blurred coworkers going about their day. The mood is calm, quiet, and productive. Shot at eye level with shallow depth of field, professional corporate aesthetic, warm neutral tones, clean minimal composition, realistic studio-quality lighting, high-resolution stock photography style." \
  "ERNIE 5.1 Thinking" "Focused Professional Working at Desk"

queue_job 53 \
  "A candid stock photo of four diverse coworkers standing near the office kitchen area during a coffee break, laughing and chatting casually in a relaxed manner. The group includes two men and two women of mixed ethnicities including Asian, Black, and Caucasian backgrounds. One holds a ceramic coffee mug, another pours fresh coffee from a glass pot. They wear comfortable business casual clothing like rolled-up sleeves and smart trousers. The background shows a modern break room with a small fridge, microwave, and potted plants. Warm overhead lighting, natural authentic body language, friendly welcoming atmosphere. Shot with a 35mm lens, slightly shallow depth of field, lifestyle corporate photography, bright and inviting mood." \
  "ERNIE 5.1 Thinking" "Colleagues Enjoying a Coffee Break Together"

queue_job 54 \
  "A stock photo of a middle-aged South Asian man wearing a dress shirt and tie, sitting at a tidy home office desk on a video conference call. He smiles warmly while looking at his laptop screen, which shows blurred faces of colleagues. The room behind him is a clean, well-lit space with a bookshelf and a window with blinds. A desk lamp provides warm supplementary light. His expression is engaged and professional. Shot from a slightly angled perspective, corporate lifestyle photography, sharp focus on the subject, soft bokeh background, natural color grading, realistic and relatable workplace scene." \
  "ERNIE 5.1 Thinking" "Professional on a Video Call in Home Office Setup"

queue_job 55 \
  "A vibrant stock photograph of three young professionals, one man and two women of different racial backgrounds including Latino, East Asian, and African American, standing around a high table in a modern open-plan office, actively collaborating on a project together. They point at a large printed chart pinned to a nearby whiteboard while discussing ideas passionately. One holds a dry-erase marker, another gestures enthusiastically with both hands. Everyone wears stylish business casual outfits with smart sneakers and casual blazers. The office features exposed brick walls, hanging green plants, and contemporary furniture. Bright and airy natural lighting, dynamic composition, energetic and creative mood, professional stock photography, sharp details throughout, clean modern aesthetic." \
  "ERNIE 5.1 Thinking" "Diverse Group Collaborating Around a Standing Desk"

echo "✅ All 55 jobs queued in scheduler"
