#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}
# ---- PROMPTS ---------------------------------------------------------------
# Theme: Minimalist line drawing woman
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+27+-+minimalistic+woman+art
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------


# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "minimalist line drawing portrait woman, single continuous ink line, profile view, flowing hair dissolving into abstract gestural strokes, negative space composition, sparse elegant curves define cheekbone jaw collarbone, ultra-thin brush marks, Japanese sumi-e influence, muted ivory background, faint ochre watercolor wash beneath ink lines, open white areas balanced against deliberate mark-making, expressive yet restrained, no shading crosshatching or fill, pure contour draftsmanship, contemplative mood, high contrast minimal palette ivory black gold accent, artisan sketch quality, fine art print aesthetic, masterful economy of line" \
  "Claude Sonnet 4.6" "Wandering Soul"

queue_job  2 \
  "minimalist continuous line woman silhouette, full body standing pose arms loosely at sides, single unbroken graphite pencil stroke loops and returns forming shoulders waist hips, background pure white, subtle indigo watercolor ink bloom at waist dissolving outward, no interior detail, outer contour only, gestural confidence, slight imperfection in line suggesting hand-drawn authenticity, negative space as compositional element, zen minimalism, sparse poetic mark-making, gallery-quality fine art illustration, meditative stillness, monochrome with single cool blue accent wash" \
  "Claude Sonnet 4.6" "Still Water"

queue_job  3 \
  "minimalist ink brush woman portrait three-quarter view, bold single calligraphic brushstroke defines face neck shoulder in one motion, wet ink varying pressure creates thick-thin line dynamics, sparse amber and pale rose watercolor tints bleed softly behind ink outline, closed eyes serene expression suggested by three minimal marks, hair implied by two sweeping strokes trailing off canvas edge, generous white negative space, sumi ink on textured paper aesthetic, wabi-sabi imperfection, expressive gestural mark, contemporary fine art minimalism, intimate quiet mood" \
  "Claude Sonnet 4.6" "First Light"

queue_job  4 \
  "minimalist line art seated woman, loose cross-legged pose knees drawn up chin resting on hand, multiple thin confident pencil lines slightly overlapping suggest form without filling it, scattered loose hatching only at shadow beneath chin, warm sepia ink tones, small delicate watercolor drops accent shoulder and knee in muted terracotta, botanical single leaf element floating upper corner drawn in same minimal style, off-white textured ground, unhurried contemplative atmosphere, handcrafted sketchbook aesthetic, fine art editorial illustration quality, quiet narrative without detail" \
  "Claude Sonnet 4.6" "Reverie"

queue_job  5 \
  "minimalist woman silhouette half-dissolved into abstract negative space, left side of figure rendered in precise single ink contour line, right side fragmenting into loose scattered ink droplets and trailing gestural marks that fade toward canvas edge, standing upright dignified posture, ink black on cream, minimal soft lavender watercolor mist where figure dissolves, portrait crop from mid-thigh upward, hair loose flowing upward as if weightless, no facial detail, pure shape and suggestion, contemporary conceptual fine art, poetic impermanence theme, masterwork economy of means" \
  "Claude Sonnet 4.6" "Dissolution"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A minimalist single-line drawing of a woman's profile, capturing her serene expression with effortless grace. The continuous black ink line flows smoothly across a stark white background, forming the delicate contours of her face, neck, and flowing hair. A single, soft wash of pale blush watercolor accents her cheek, adding subtle depth and a touch of warmth. The composition relies on negative space, emphasizing simplicity and artistic restraint. Every curve is deliberate, creating a timeless and sophisticated portrait. The overall aesthetic is clean, modern, and profoundly elegant, echoing a gallery-grade masterpiece where less is infinitely more." \
  "Gemini 3.5 Flash" "Abstract Elegance"

queue_job  7 \
  "A striking minimalist ink illustration featuring the silhouette of a woman seated in a contemplative pose. The artwork uses bold, confident brush strokes combined with thin, precise pen lines to outline her form against a textured cream paper backdrop. Her posture is expressive yet understated, conveying a deep sense of quiet introspection. A vibrant splash of crimson red ink bleeds organically into the lower corner of the canvas, providing a dramatic contrast to the otherwise monochrome palette. The balance between the stark black lines, the vivid color accent, and the expansive negative space creates a powerful, visually arresting artistic statement." \
  "Gemini 3.5 Flash" "Crimson Solitude"

queue_job  8 \
  "An artistic multi-line marker drawing of a woman's upper torso and face, beautifully intertwined with delicate botanical elements. Fine, clean black lines delineate her features and the elegant curve of her shoulder, while whimsical leaves and slender stems sprout gracefully from her hair. Minimalist accents of muted olive green and soft terracotta ink are strategically applied to the foliage, breathing life into the sketch without overwhelming its simplistic essence. The style is fresh, contemporary, and deeply poetic, celebrating the harmony between human form and nature. The composition remains airy and uncluttered, leaving ample room for the imagination." \
  "Gemini 3.5 Flash" "Whispering Flora"

queue_job  9 \
  "A bold minimalist brush painting depicting the fluid silhouette of a moving woman. Using a dry-brush technique with dark indigo ink, the strokes capture the essence of motion and grace in just a few sweeping gestures. The texture of the bristles is visible on the canvas, adding a raw, authentic texture to the minimalist form. A faint, watery wash of midnight blue hovers gently behind the figure, suggesting a subtle atmospheric depth. This piece masterfully balances the energy of the brushwork with the stillness of the surrounding negative space, resulting in a captivating, high-contrast visual that feels both modern and traditional." \
  "Gemini 3.5 Flash" "Midnight Silhouette"

queue_job 10 \
  "A sophisticated multi-media minimalist sketch of a woman facing forward, her eyes gently closed. The portrait is executed using a combination of fine-tip black marker and delicate metallic gold ink lines that trace the highlights of her face and collarbone. The lines are sparse but highly descriptive, capturing a mood of absolute peace and tranquility. A small, singular geometric circle of soft ochre watercolor sits off-center in the background, anchoring the composition. The interplay between the sharp black lines, the shimmering gold accents, and the fluid watercolor shape creates a luxurious yet profoundly simple artistic masterpiece." \
  "Gemini 3.5 Flash" "Golden Contours"

# --- ChatGPT ---
queue_job 11 \
  "A refined minimalist line drawing of a woman's face captured in a single continuous flowing line, slightly abstract yet emotionally expressive. The composition focuses on elegant simplicity, with delicate curvature suggesting closed eyes, a calm expression, and softly defined lips. The line appears as if drawn with a fine ink pen on textured off-white paper, with subtle variations in thickness adding a sense of rhythm and motion. A faint wash of pale watercolor blush gently accents the cheek area, blending organically into the background. Negative space plays a crucial role, allowing the form to breathe and feel weightless. The style evokes modern gallery art, balancing precision and spontaneity, with a poetic, intimate mood." \
  "ChatGPT" "Whispering Contour"

queue_job 12 \
  "A minimalist side profile of a woman rendered with a few confident, clean lines, emphasizing silhouette over detail. The drawing uses a brush pen technique, where strokes taper naturally, creating a dynamic interplay between bold and delicate marks. The woman's neck is elongated, posture graceful, and hair suggested with loose, gestural curves rather than explicit detail. A subtle monochrome palette dominates, with a single accent of diluted indigo watercolor bleeding gently around the outline, giving a soft atmospheric depth. The composition is centered yet asymmetrical, enhancing visual interest while maintaining calm balance. The artwork feels contemporary, meditative, and effortlessly elegant, like a quiet moment frozen in time." \
  "ChatGPT" "Silent Profile in Ink"

queue_job 13 \
  "An artistic minimalist depiction of a seated woman drawn entirely in one uninterrupted line, capturing both figure and emotion through fluid motion. The pose is relaxed yet expressive, with abstract curves forming limbs and torso in a harmonious flow. The line appears slightly imperfect, as if sketched by hand with a fine liner, giving authenticity and warmth. The background remains mostly untouched, but a light watercolor wash in soft beige and dusty rose tones subtly anchors the figure without overwhelming it. The composition emphasizes negative space and movement, inviting interpretation rather than definition. The overall aesthetic is modern, poetic, and intimate, resembling a gallery-ready illustration that celebrates simplicity and feminine grace." \
  "ChatGPT" "Ethereal One-Line Muse"

queue_job 14 \
  "A contemporary minimalist portrait of a woman using sparse, deliberate strokes that suggest rather than define facial features. The eyes are indicated by two gentle arcs, the nose by a single contour, and lips by a soft broken line, leaving much to imagination. The medium mimics charcoal or soft graphite, with slight smudging adding texture and depth. A minimal splash of muted terracotta ink sits asymmetrically behind the face, creating contrast and grounding the composition. The drawing embraces imperfection, with visible hand-drawn qualities and slight asymmetry enhancing its artistic charm. The overall style is sophisticated and understated, focusing on emotional presence rather than realistic detail." \
  "ChatGPT" "Minimal Gesture Portrait"

queue_job 15 \
  "A minimalist full-body silhouette of a woman standing gracefully, created with a combination of continuous and broken lines that feel organic and rhythmic. The figure is elongated and stylized, with gentle curves suggesting motion and elegance. The lines resemble a fine brush dipped in black ink, with subtle pressure changes giving life to the strokes. Around the figure, faint translucent watercolor shapes in cool gray and soft lavender tones create a dreamy, airy environment without distracting from the subject. The composition is balanced with generous negative space, enhancing the sense of calm and refinement. The artwork feels like a modern minimalist masterpiece, blending simplicity with expressive artistry." \
  "ChatGPT" "Flowing Silhouette Harmony"

# --- Grok 4.3 fast ---
queue_job 16 \
  "Minimalist single-line drawing of a graceful young woman in profile, her elegant neck and flowing long hair captured in one continuous delicate black ink line on white background, soft facial features with closed eyes and peaceful expression, subtle contours suggesting inner calm, artistic pen and ink style with faint watercolor washes in soft blush tones on lips and cheeks, clean negative space emphasizing purity and simplicity, highly artistic minimalist masterpiece, refined elegant lines, emotional depth through minimal strokes, sophisticated composition, timeless beauty." \
  "Grok 4.3" "Serene Minimalist Portrait"

queue_job 17 \
  "Minimalist continuous line art silhouette of a woman dancing freely, arms gracefully raised and body in fluid motion, elegant curves and dynamic pose drawn with bold yet delicate marker strokes, abstract flowing dress suggested through sparse lines, pure black ink on pristine white canvas with minimal soft gray shading for depth, artistic brushwork evoking movement and joy, negative space masterpiece, expressive minimalist female form, harmonious balance of form and emptiness, contemporary elegant line drawing." \
  "Grok 4.3" "Dancing Silhouette"

queue_job 18 \
  "Minimalist pencil line drawing portrait of a thoughtful woman facing forward, intricate yet sparse lines defining her gentle eyes looking directly at viewer, soft wavy hair framing face, subtle collarbone and shoulders, delicate hatching for texture and light shadows, touch of watercolor ink in muted teal and sepia tones, exquisite artistic simplicity, emotional introspection captured through masterful minimalism, clean white background, refined pen and ink details, serene and captivating female portrait masterpiece." \
  "Grok 4.3" "Contemplative Gaze"

queue_job 19 \
  "Minimalist brush and ink drawing of a woman in lotus position meditating amidst faint outline of leaves and flowers, elegant elongated form with flowing robes suggested by few graceful lines, serene closed eyes and peaceful posture, single continuous line technique blending figure with nature elements, subtle watercolor accents in soft sage green and lavender, artistic minimalist style emphasizing connection and tranquility, masterful use of negative space, elegant feminine energy, poetic composition." \
  "Grok 4.3" "Nature Harmony"

queue_job 20 \
  "Minimalist marker line art profile of a mysterious woman with intricate updo hairstyle, delicate earrings and necklace hinted through sparse elegant strokes, soft lips slightly parted as if whispering, strong yet gentle facial contours, artistic pen drawing with light ink wash in warm beige and gold tones for subtle highlights, sophisticated minimalist silhouette against pure white, timeless graceful beauty, highly detailed fine lines creating depth, exquisite artistic female portrait with emotional resonance and refined simplicity." \
  "Grok 4.3" "Elegant Profile Whisper"

# --- Copilot ---
queue_job 21 \
  "A minimalist, elegant portrait of a woman drawn in a single continuous line across a square canvas, delicate and confident; emphasize graceful contour of face, neck, and shoulder with varied line weight — thin hairline strokes and a slightly bolder jawline; incorporate subtle graphite texture and faint pencil shading to suggest volume without breaking the line; add a whisper of muted ochre watercolor wash behind the head and a tiny ink splatter for organic imperfection; keep abundant negative space, soft paper grain, and a calm, gallery-ready composition; aim for refined, modern aesthetic, high artistic intent, balanced asymmetry, and a timeless, contemplative mood suitable for print." \
  "Copilot" "Single Line Portrait"

queue_job 22 \
  "A minimalist silhouette of a woman in profile, composed of a single confident brushstroke for the outline and a second delicate line for facial features; use sumi ink for the silhouette with intentional ink bleed and feathering at edges; introduce a restrained watercolor accent — one translucent blush or teal wash across the shoulder and collarbone that pools slightly and creates a soft halo; maintain generous negative space and visible paper texture; include subtle pencil gesture marks and a faint signature line at the bottom right; prioritize poetic simplicity, elegant posture, and a meditative, modern-art gallery feel." \
  "Copilot" "Silhouette with Watercolor Accent"

queue_job 23 \
  "A minimalist reclining female figure rendered with a few decisive, flowing lines — one for the spine and hip curve, another for the arm and hand resting near the face; combine fine pen strokes and a soft brush marker to vary rhythm and weight; add a barely-there wash of diluted indigo watercolor under the torso to anchor the composition and suggest shadow; preserve large empty margins and tactile paper grain; include tiny intentional imperfections: a hairline scratch, a light eraser ghost, and a single ink droplet; evoke quiet introspection, refined restraint, and contemporary elegance suitable for a framed minimalist masterpiece." \
  "Copilot" "Contemplative Recline"

queue_job 24 \
  "A dynamic minimalist gesture study of a standing woman captured in three to five expressive lines that convey motion and balance; use rapid brush-pen strokes with controlled splatter and occasional dry-brush texture to reveal energy; layer a faint graphite underdrawing visible through the ink to suggest construction; introduce a whisper of warm sienna watercolor along the torso and a cool gray wash for shadow contrast, both soft and translucent; keep composition centered with ample negative space and visible paper fibers; emphasize rhythm, economy of mark-making, and an artful, modern simplicity that reads as both study and finished artwork." \
  "Copilot" "Gesture Study in Ink"

queue_job 25 \
  "An abstract minimalist depiction of a woman using interlocking continuous lines and geometric negative shapes to imply face, shoulder, and hand; employ a mix of ink pen, brush marker, and a single muted color — sage or terracotta — applied as a soft watercolor stain that interacts with the lines; allow intentional gaps where the line dissolves into the wash, creating breath and ambiguity; include subtle paper texture, light pencil construction marks, and a small, elegant artist monogram; favor balanced asymmetry, refined restraint, and a contemplative, gallery-ready composition that reads as a modern minimalist masterpiece." \
  "Copilot" "Abstract Minimal Muse"

# --- Mistral ---
queue_job 26 \
  "Minimalist single-line portrait of a woman, elegance captured in one unbroken, smooth flowing stroke, black ink on pristine white paper, delicate facial features and subtle neck curves, artistic simplicity at its finest, refined minimalism with no shading or color, pure line art, serene and timeless expression, ultra-clean high-contrast composition, professional line drawing inspired by Picasso's iconic single-line sketches, ultra-detailed line precision, sophisticated and graceful form, monochrome masterpiece, smooth paper texture, no background distractions, focus on purity of form, flow, and emotional depth, delicate balance, harmonious proportions, meditative atmosphere, subtle elegance, confident yet gentle presence, ultra-minimalist aesthetic, bold yet delicate line weight variation, masterful simplicity." \
  "Mistral" "Elegance in a Single Stroke"

queue_job 27 \
  "Minimalist silhouette of a woman in profile, soft watercolor ink washes in muted pastel tones, delicate single continuous line defining her elegant form, subtle gradients of color bleeding into the paper, artistic fusion of line and wash, refined simplicity, serene atmosphere, ultra-clean composition, professional watercolor line art, inspired by traditional Chinese ink paintings, ultra-detailed yet soft edges, sophisticated graceful silhouette, monochromatic with hints of color, smooth textured paper, no background distractions, focus on purity of shape and flow, emotional depth in minimalism, delicate balance, harmonious proportions, meditative calm, subtle elegance, confident gentle presence, ultra-minimalist aesthetic, ethereal and dreamy mood." \
  "Mistral" "Silhouette with Watercolor Whispers"

queue_job 28 \
  "Minimalist pencil sketch of a woman's portrait, delicate fine lines and subtle shading, soft graphite on textured paper, artistic simplicity with refined minimalism, pure line art with gentle cross-hatching, serene and timeless expression, ultra-clean composition, professional pencil drawing inspired by classical sketches, ultra-detailed yet soft line precision, sophisticated graceful form, monochrome masterpiece, smooth paper texture, no background distractions, focus on purity of form and subtle details, emotional depth in minimalism, delicate balance, harmonious proportions, meditative atmosphere, subtle elegance, confident gentle presence, ultra-minimalist aesthetic, raw and authentic artistic feel." \
  "Mistral" "Pencil Sketch Minimalism"

queue_job 29 \
  "Minimalist portrait of a woman using bold black marker lines, strong confident strokes defining her features, artistic simplicity with high contrast, refined minimalism, pure line art with varying line weights, serene and powerful expression, ultra-clean composition, professional marker drawing inspired by modern graphic design, ultra-detailed line precision, sophisticated and bold form, monochrome masterpiece, smooth paper texture, no background distractions, focus on purity of form and boldness, emotional depth in minimalism, delicate balance, harmonious proportions, dynamic energy, subtle elegance, confident presence, ultra-minimalist aesthetic, striking and impactful visual." \
  "Mistral" "Bold Marker Minimalism"

queue_job 30 \
  "Minimalist line drawing of a woman with subtle watercolor ink accents, delicate continuous lines and soft color washes, artistic fusion of pen and watercolor, refined simplicity with a touch of color, serene and elegant expression, ultra-clean composition, professional mixed media art inspired by contemporary minimalism, ultra-detailed line precision with soft color gradients, sophisticated graceful form, subtle color palette, smooth textured paper, no background distractions, focus on purity of form and subtle color interplay, emotional depth in minimalism, delicate balance, harmonious proportions, meditative calm, subtle elegance, confident gentle presence, ultra-minimalist aesthetic, ethereal and artistic mood." \
  "Mistral" "Ink and Watercolor Fusion"

# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "A minimalist continuous single-line drawing of a woman's face in profile, capturing delicate features with elegant, unbroken fluid strokes. The line is drawn in deep charcoal black ink on a pristine, warm off-white textured paper background. Subtle, almost imperceptible hints of pale watercolor blush in soft peach tones accentuate the cheekbone, adding a touch of warmth without breaking the minimalist aesthetic. The composition focuses entirely on the serene expression, closed eyes, and graceful neck, evoking a sense of calm and timeless beauty. The artistic style is highly refined, balancing negative space and precise, confident linework to create a sophisticated, modern masterpiece that feels both intimate and profoundly artistic." \
  "Qwen 3.7 Plus" "Continuous Line Elegance"

queue_job 32 \
  "An abstract minimalist silhouette of a woman seated gracefully, rendered with sparse, deliberate brushstrokes of diluted black India ink. The form is suggested rather than fully defined, utilizing generous negative space to imply the curve of her shoulders and the gentle tilt of her head. A single, striking stroke of muted cobalt blue watercolor washes over the lower portion of the silhouette, grounding the composition with a subtle pop of cool color. The artwork is executed on heavy, cold-pressed watercolor paper, showcasing the natural bleed and texture of the ink. This piece embodies quiet contemplation, merging traditional calligraphic techniques with contemporary minimalist art principles to achieve a serene, gallery-worthy aesthetic." \
  "Qwen 3.7 Plus" "Silhouette in Soft Ink"

queue_job 33 \
  "A striking minimalist portrait of a woman combining organic flowing lines with subtle geometric elements. The face is outlined in fine, crisp black marker, while the hair dissolves into a few sweeping, expressive graphite pencil strokes that suggest dynamic movement and soft volume. A faint, translucent wash of golden yellow watercolor delicately highlights the jawline, adding a subtle luminous quality to the piece. The background remains a clean, stark white, heavily emphasizing the purity and confidence of the linework. The composition intentionally plays with asymmetry, leaving one side of the face beautifully undefined to invite viewer interpretation. This artistic approach creates a harmonious balance between structured precision and freeform creativity, resulting in a captivating, modern minimalist illustration." \
  "Qwen 3.7 Plus" "Geometric Organic Harmony"

queue_job 34 \
  "A beautiful blind contour style line drawing of a woman looking upward, executed with a fine-tipped black pen. The lines are intentionally imperfect, overlapping, and sketchy, capturing the raw essence and emotion of the subject rather than photographic realism. The drawing focuses on the elegant curve of the neck, the delicate structure of the nose, and the soft parting of the lips. Minimal splashes of diluted crimson ink are strategically placed near the collarbone, providing a subtle, artistic contrast against the monochromatic lines. The artwork is presented on a slightly textured, cream-colored canvas, enhancing the hand-drawn, authentic feel. This piece celebrates the beauty of imperfection and the expressive power of minimalist, spontaneous line art." \
  "Qwen 3.7 Plus" "Blind Contour Serenity"

queue_job 35 \
  "A minimalist line art portrait of a woman where her flowing hair seamlessly transforms into delicate, abstract botanical elements. Drawn with a smooth, consistent black brush pen, the lines vary subtly in thickness to create depth and rhythm. The woman's face is depicted in a serene three-quarter view, with closed eyes and a peaceful expression. A very light, airy wash of sage green watercolor is applied only to the leaf-like extensions of her hair, introducing a gentle, natural color palette without overwhelming the minimalist design. The composition is centered on a pure white background, utilizing ample negative space to draw the eye directly to the intricate, harmonious blend of human form and nature." \
  "Qwen 3.7 Plus" "Botanical Line Fusion"

# --- GLM 5.1 Think Search ---
queue_job 36 \
  "Minimalist continuous line drawing of a woman's side profile, elegant and fluid, drawn with a single unbroken black ink stroke reminiscent of Picasso's light drawings. Her hair flows organically into the sweeping line, capturing a serene and contemplative expression with just a few deft curves. Subtle, minimal watercolor wash in pale cerulean blue accents the edge of her jawline and a few stray strands of hair, adding gentle depth without disrupting the stark minimalism. Clean, heavily textured off-white handmade paper background emphasizing the raw canvas. Masterful balance of negative space and expressive, confident linework. Delicate, poetic, modern minimalist masterpiece, fine art pen and brush style, evoking quiet sophistication and timeless grace." \
  "GLM 5.1" "Ephemeral Cerulean Profile"

queue_job 37 \
  "Minimalist abstract silhouette of a woman, crafted with bold, sweeping black marker strokes on pure white smooth paper. The form is suggested rather than explicitly detailed, with thick, confident brush pen lines outlining the graceful curve of her neck, bare shoulder, and the gentle slope of her cheek. A delicate, tiny splash of metallic gold ink subtly highlights the area where an earring would be, providing a striking yet minimal contrast against the stark black. The composition relies heavily on vast, undisturbed negative space to convey elegance, solitude, and freedom. Artistic, modern, sophisticated minimalist masterpiece, using expressive gestural drawing techniques, high contrast, fine art aesthetic, evocative and deeply poetic." \
  "GLM 5.1" "Gilded Silhouette"

queue_job 38 \
  "Minimalist pencil drawing of a woman's face, utilizing delicate, feathery graphite strokes that gently map out her tranquil, closed-eye expression. The linework is exceptionally sparse, consisting of only a few carefully placed curves to define her brow, nose, and cascading hair. A single, vivid drop of crimson red watercolor ink bleeds perfectly over her lips, creating a breathtaking focal point and a dramatic pop of color against the monochromatic graphite. The background is a clean, unblemished white, emphasizing the sheer simplicity and emotional weight of the composition. Masterpiece of contemporary minimalist portraiture, raw emotion, beautiful chiaroscuro interplay between light and shadow, poetic subtlety." \
  "GLM 5.1" "Crimson Lip Study"

queue_job 39 \
  "Minimalist brush and ink silhouette of a woman, inspired by traditional sumi-e aesthetics but executed with a modern twist. Flowing, expressive black ink strokes define the sweeping contour of her back and the elegant updo of her hair. The lines taper beautifully from thick to thin, showcasing the natural flexibility of the calligraphy brush. A single, ethereal minimal watercolor bloom in soft blush pink emerges organically from the dark ink of her hair, seamlessly integrating the female form with a delicate floral motif. Crisp, bright white background preserving the purity of the composition. Sublime minimalist masterpiece, harmonious, graceful, evoking a sense of tranquil beauty and natural elegance." \
  "GLM 5.1" "Sumi-e Bloom"

queue_job 40 \
  "Minimalist fine pen drawing of a woman's portrait, characterized by precise, architectural linework and geometric simplification of her facial features. Executed with a fine-tipped micron pen in crisp, unyielding black ink, the drawing reduces her elegant visage to its most essential intersecting lines and graceful curves. A soft, atmospheric watercolor wash in muted lavender and pale peach gently blooms behind her head, providing a delicate, dreamlike backdrop that beautifully contrasts with the strict, analytical pen strokes. The interplay of rigid line and soft color creates a captivating visual tension. Striking contemporary minimalist masterpiece, modern art gallery aesthetic, refined, perfectly balanced composition, incredibly chic and effortlessly beautiful." \
  "GLM 5.1" "Geometric Lavender Reverie"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "Minimalist single continuous line drawing of a woman in profile, her gaze directed downward in quiet contemplation, delicate flowing hair merging seamlessly into the curve of her shoulder and neck, soft watercolor ink wash in muted sage green and dusty rose bleeding gently at the edges, hand-drawn with a fine fountain pen on textured cream paper, negative space dominating the square composition, elegant simplicity with no facial features except the silhouette of her nose and lips, ethereal and meditative atmosphere, artistic masterwork of restraint and grace, subtle ink splatter accents near the hairline, contemporary fine art aesthetic." \
  "Kimi K2.6 Thinking" "Serene Contemplation"

queue_job 42 \
  "Continuous one-line minimalist illustration of a woman captured mid-dance, her body forming an elegant arabesque pose with arms extended upward in fluid motion, the single unbroken line creating both her figure and the flowing fabric of her dress simultaneously, delicate brush pen strokes with varying pressure creating organic thickness transitions, sparse watercolor accents in deep indigo and burnt sienna on the dress hem only, stark white background emphasizing the dynamic negative space around her form, no facial details maintaining universal anonymity, graceful spiral composition drawing the eye inward, modern gallery-quality line art with intentional imperfections and natural hand tremor beauty, ink pooling at the feet suggesting movement." \
  "Kimi K2.6 Thinking" "Dancing Silhouette"

queue_job 43 \
  "Minimalist multi-line drawing of a woman facing forward with eyes gently closed, her hair adorned with an abstract wreath of wildflowers drawn in the same continuous stroke technique, fine liner pen work in archival black ink with selective use of diluted watercolor in pale lavender and soft gold on the flower petals only, sparse cross-hatching defining the jawline and collarbone with artistic economy, square format balanced with generous breathing room on all sides, the line occasionally breaking and reconnecting to suggest sketchbook authenticity, delicate freckles suggested by tiny ink dots across the nose bridge, bohemian elegance meets contemporary Scandinavian design aesthetic, museum-quality minimalist portraiture with emotional depth through simplicity." \
  "Kimi K2.6 Thinking" "Floral Crown Portrait"

queue_job 44 \
  "Minimalist line drawing of a woman seated cross-legged absorbed in a book, her body formed by three elegant continuous lines that never intersect, one line defining her curved spine and bent knee, another her arm and the open book merging together, the third her flowing hair cascading down to meet the floor, subtle ink wash in warm sepia and faded teal applied only to the book pages and hair ends, drawn with a Japanese brush pen on handmade paper texture visible in the negative space, contemplative mood conveyed through posture alone without facial features, geometric harmony between the square canvas and organic human curves, architectural balance of line weight variation, sophisticated literary art piece with wabi-sabi imperfections and intentional empty space storytelling." \
  "Kimi K2.6 Thinking" "Reading in Repose"

queue_job 45 \
  "Minimalist single-line silhouette of a woman standing against an imaginary wind, her hair and dress flowing horizontally to the right in one continuous ribbon-like stroke, the line beginning at her toes and ending at the tip of her wind-whipped hair, delicate fountain pen ink in waterproof carbon black with minimal watercolor bleeding in ocean turquoise and sand beige along the hair stream only, profile view showing just the suggestion of a straight nose and determined chin, vast empty space surrounding the figure emphasizing isolation and freedom, hand-drawn quality with slight wavering lines adding human warmth, contemporary coastal art aesthetic, the square composition allowing the horizontal flow to breathe, gallery wall worthy minimalist masterpiece capturing motion through stillness and silence through line." \
  "Kimi K2.6 Thinking" "Ocean Breeze Profile"

# --- Deepseek Expert ---
queue_job 46 \
  "A minimalist line drawing of a woman in profile, executed in a single continuous unbroken black ink line on a soft cream paper texture. The line flows from the nape of her neck down her back, curving gently to form her shoulder, then looping up to trace her serene face, closed eye, delicate nose, and slightly parted lips, continuing to outline her hair cascading like a waterfall of simplicity. The line weight varies subtly, suggesting shadow and volume. A tiny watercolor wash of pale cerulean blue barely touches her hair, a whisper of color. The composition is spacious, with the figure positioned slightly off-center, leaving room for contemplation. The overall aesthetic is Zen-like, poetic, and deeply calming, evoking a sense of inner peace and timeless elegance in the economy of a single stroke." \
  "Deepseek" "Contemplative Woman in Single Unbroken Line"

queue_job 47 \
  "An artistic minimalist gesture drawing of a female dancer captured mid-pirouette, rendered with swift, expressive charcoal lines on textured canvas. Multiple sketchy strokes define the movement: a sweeping curve for the spine, fluid arcs for the outstretched arms, and a few decisive marks for the tutu-like skirt flaring out. The charcoal is smudged in places to create a soft, smoky shadow that suggests motion and depth without detail. A single watercolor drip of deep crimson bleeds subtly from the dancer's raised fingertips, like a drop of passion escaping the line. The background is raw and untouched, heightening the raw energy. The style is reminiscent of Degas sketches distilled to pure kinetic essence, where less is more and the figure nearly dissolves into the air, a masterpiece of movement and restraint." \
  "Deepseek" "Dancer in Gestural Charcoal Curves"

queue_job 48 \
  "A delicate minimalist line portrait of a woman whose profile is composed entirely of intricate botanical elements, drawn with a fine-tipped sepia pen on aged parchment. The line work is precise and airy: her hair becomes a cascade of thin stems, tiny leaves, and unopened buds, while her facial contour is a single clean stroke. Inside her silhouette, scattered watercolor ink splatters in shades of blush pink, sage green, and faded ochre bloom like a secret garden. The woman gazes downward, as if admiring the flowers within herself. The negative space is vast, amplifying the fragility of the lines. This piece merges human form with nature in a poetic, almost scientific illustration style, evoking a Victorian herbarium pressed into minimalist art, both elegant and soulful." \
  "Deepseek" "Floral Silhouette in Fine Pen and Ink"

queue_job 49 \
  "A minimalist brush painting of a woman stretching her arms overhead, captured in a few fluid sumi-e ink strokes on absorbent rice paper. The brushwork is bold yet controlled: a thick, confident curve outlines the arch of her back, thinner flicks of the brush suggest her fingers reaching toward the sky, and a soft grey wash bleeds into the contour of her hips. The black ink ranges from deep ebony to pale mist, creating a monochrome symphony. A single drop of diluted vermilion ink colors her lips, a striking focal point. The composition is profoundly simple, with the figure dissolving into emptiness at the edges. The style evokes Japanese Zen calligraphy, where the spirit of the pose is captured in the fewest possible brushstrokes, resulting in a serene, meditative masterpiece." \
  "Deepseek" "Morning Stretch in Brush and Sumi Ink"

queue_job 50 \
  "A minimalist line drawing of a woman engrossed in a book, seated cross-legged, rendered with a bold black graphic marker line on bright white paper. The lines are clean, continuous, and confident, defining the oval of her face, the slope of her shoulders, and the open pages with no extraneous detail. A soft, minimal watercolor wash of warm Naples yellow gently illuminates the space around her, as if catching the light of an unseen window. A single crimson ink line traces the spine of the book, drawing the eye. Her posture is relaxed yet absorbed. The style merges mid-century modern illustration with contemporary minimalism, where every line earns its place. The simplicity of the form against the vast white void emphasizes the quiet joy of reading, transforming an everyday moment into a timeless artistic statement." \
  "Deepseek" "Woman Reading in Minimalist Marker and Wash"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A stunning minimalist portrait of a woman created with a single continuous black line on pure white background, the line flows effortlessly from her closed eyes down her neck across her bare shoulders and traces the curve of her collarbone, her hair suggested by a few loose sweeping strokes, one small accent of soft blush pink on her lips, the composition breathes with negative space, ultra clean aesthetic, fine art quality, gallery worthy, delicate and feminine, no shading just pure line work with one touch of color." \
  "ERNIE 5.1 Thinking" "Whispered Grace"

queue_job 52 \
  "A breathtaking minimalist silhouette of a woman standing in profile against a deep midnight blue background, her entire form defined by a single bold black ink line, her hair flowing backward as if caught in wind, one hand gently touching her face, a single accent of warm gold leaf color on her heart area, the rest is pure negative space and darkness, zen-like simplicity, artistic masterpiece quality, elegant pose with long neck, ultra minimalist fine art illustration, no details inside the silhouette just pure shape and one color accent." \
  "ERNIE 5.1 Thinking" "Midnight Contour"

queue_job 53 \
  "A modern minimalist line art portrait of a woman composed of multiple thin geometric lines in black on white, her face is abstracted into angular shapes and arcs, her eyes are two simple dots, her lips a single curved stroke, her body suggested by three clean parallel lines, one bold red circle placed where her heart would be, the style merges Picasso minimalism with contemporary graphic design, sharp and precise, museum quality fine art, negative space dominant, sophisticated and avant-garde, square composition perfect for gallery wall." \
  "ERNIE 5.1 Thinking" "Fractured Beauty"

queue_job 54 \
  "An artistic minimalist woman portrait drawn with flowing ink lines that gradually dissolve into soft watercolor washes of pale lavender and dusty rose, her face is turned three quarters with eyes gently closed, her hair is a cascade of loose expressive strokes that fade into nothing, one continuous line defines her jaw and neck, the background is pure white with faint color bleeding, the mood is dreamlike and ethereal, Japanese minimalism meets Western line art, delicate paper texture feel, ultra refined and poetic, fine art print quality." \
  "ERNIE 5.1 Thinking" "Soft Dissolve"

queue_job 55 \
  "A striking minimalist artwork of a woman rendered in just two colors black and deep emerald green on a cream white canvas, her figure is a graceful silhouette made of one flowing line that loops to suggest her hair and arms raised above her head, her body is filled with a solid emerald green tone while the line work remains black, the pose is dance-like and free, negative space plays a major role, the style echoes Matisse cutouts but with line drawing precision, artistic and bold yet serene, gallery masterpiece, clean composition square format." \
  "ERNIE 5.1 Thinking" "Her Secret Garden"

# --- LongCat Deep Research ---
queue_job 56 \
  "A single continuous flowing line drawing of an elegant woman's profile, minimalist masterpiece, one unbroken stroke forming her face, hair, and neck, delicate line weight variation, pure black ink on pristine white background, negative space mastery, zen simplicity, sophisticated feminine essence, gallery quality fine art, timeless beauty captured in a single breath, no shading, no color, just the purest line." \
  "LongCat" "The Eternal Profile"

queue_job 57 \
  "Minimalist silhouette portrait of a graceful woman, stark black figure against soft gradient sunset background, clean elegant outline, mysterious and contemplative mood, backlit rim light, simple geometric shapes, powerful negative space, emotional depth through absence, dramatic contrast, fine art photography aesthetic, ethereal and haunting beauty, masterful restraint." \
  "LongCat" "Whispering Silhouette"

queue_job 58 \
  "Expressive ink brush portrait of a woman, dynamic gestural strokes, visible brush texture, controlled splatter and bleeding edges, sumi-e inspired, minimalist zen art, black ink on textured rice paper, spontaneous yet deliberate marks, capturing spirit over form, raw emotional power, traditional meets contemporary, museum quality abstract expression." \
  "LongCat" "Ink Dance Portrait"

queue_job 59 \
  "Low poly portrait of a woman's face, geometric abstraction, angular triangular facets, flat matte colors in muted earth tones, modern digital art aesthetic, clean sharp edges, architectural structure, contemporary minimalism, 3D rendered appearance, sophisticated color palette, gallery wall worthy, bold yet feminine, mathematical beauty." \
  "LongCat" "Geometric Goddess"

queue_job 60 \
  "Delicate watercolor portrait of a woman, soft bleeding edges, translucent layered washes, pastel pink and lavender tones, minimalist feminine art, wet-on-wet technique, dreamy ethereal atmosphere, subtle facial features suggested not defined, white space poetry, gentle color gradients, fine art illustration, fragile beauty, emotional subtlety." \
  "LongCat" "Watercolor Dream"

echo "✅ All 60 jobs queued in scheduler"

