#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Memes, jokes, comics — funny 2-3 panel caricature illustrations
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+22+-+jokes
# Structure: 11 models × 5 prompts = 55 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 4.6 ---
queue_job  1 \
  "A 3-panel horizontal comic strip, flat cartoon illustration style, bold black ink outlines, bright saturated colors. Panel 1: cheerful alarm clock on nightstand showing 6:00 AM, glowing sunrise through window, small sleeping human lump under blanket with \"ZZZ\" floating above. Panel 2: alarm clock ringing with angry red face and vibrating lines, human arm reaches out from blanket and smashes it flat with a WHAM effect. Panel 3: same alarm clock now showing 8:45 AM, cracked and dented, human figure rushing out door wearing mismatched clothes with sweat drops flying, speech bubble \"I'm fine!!\". White background, comic book halftone dots texture, expressive exaggerated faces." \
  "Claude Sonnet 4.6" "The Monday Alarm"

queue_job  2 \
  "A 2-panel vertical comic strip, bold cartoon illustration style, thick black outlines, vivid flat colors. Panel 1: round chubby cartoon character sitting at a table with a tiny sad salad on a plate, thought bubble showing a massive juicy burger, fries and milkshake, character's eyes are dreamy and sparkling, label on thought bubble \"The Plan\". Panel 2: same character at same table now with the giant burger, fries and shake in real life, empty salad plate tossed aside, huge grin, speech bubble \"Starting Monday\", crumbs flying everywhere. Bright kitchen background, exaggerated proportions, cheerful comic book style." \
  "Claude Sonnet 4.6" "The Diet Plan"

queue_job  3 \
  "A 3-panel comic strip, flat digital cartoon style, bold outlines, clean bright colors. Panel 1: cartoon person sitting comfortably on couch with laptop, smug face, giant \"WiFi: CONNECTED\" icon floating above with halo and angelic glow. Panel 2: WiFi icon suddenly shown with X through it, disconnected, person's face melting in horror, dramatic cracks forming around them, jagged speech bubble \"NOOOOO!!\". Panel 3: person now crouched on all fours pressing ear against the router on the floor, eyes wild and desperate, whisper bubble \"Please... I'll be good\". White comic background, heavy black borders per panel, exaggerated expressions." \
  "Claude Sonnet 4.6" "WiFi Emergency"

queue_job  4 \
  "A 2-panel comic strip, loose sketchy cartoon illustration style, colored with flat tones and bold ink lines. Panel 1: serious-looking cartoon cat in tiny glasses and a miniature tie sitting behind a tiny desk with stacks of papers, confident expression, speech bubble \"I am a professional\". Panel 2: exact same cat now fully sprawled upside-down on keyboard, all four paws in the air, tongue out, laptop screen showing \"kkkkkkkkkkkkkkkk\", small speech bubble \"nap time\". Warm cream background, expressive cartoony anatomy, office setting details, humorous contrast between panels." \
  "Claude Sonnet 4.6" "The Expert Cat"

queue_job  5 \
  "A 3-panel comic strip, bold cartoon caricature style, thick black outlines, bright flat colors. Panel 1: cartoon human standing in front of gym door flexing with determination, heroic pose, speech bubble \"Today I transform!!\". Panel 2: the same character now standing in front of a couch holding a bag of chips, same heroic pose, same determined face, speech bubble \"Tomorrow I transform!!\". Panel 3: character sunk deep into couch, nearly absorbed by cushions, chips everywhere, TV remote in hand, tiny thought bubble showing a tiny flexing stick figure with a cross through it, sleepy half-closed eyes. Clean white comic background, exaggerated muscle definition on character, very expressive face across all panels." \
  "Claude Sonnet 4.6" "Gym vs. Couch"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A 2-panel comic in a colorful caricature style. Panel 1: A stressed developer is typing frantically on a laptop in front of a massive server rack labeled \"PRODUCTION.\" Above his head is a text speech bubble that reads, \"Fixed the bug in prod-jenkins-03!\" Panel 2: The developer turns around with a proud smile, but behind him, the entire server rack is engulfed in comical, bright orange cartoon flames. A thinking bubble above his head reads, \"...Wait, why is it so warm?\"" \
  "Gemini 3.5 Flash" "The Developer's Setup"

queue_job  7 \
  "A 3-panel comic strip with a vibrant, high-contrast graphic novel style. Panel 1: An artist sits at a desk typing intensely into a computer, a giant glowing brain hovering over them. Panel 2: The artist stares blankly at a blank canvas on the screen, looking completely exhausted. Panel 3: A massive, detailed text speech bubble appears above the artist, containing an absurdly long, hyper-detailed prompt matrix full of technical tokens and brackets, while the artist has a look of absolute desperation." \
  "Gemini 3.5 Flash" "The Prompt Engineer's Dilemma"

queue_job  8 \
  "A 2-panel cartoon meme style illustration. Panel 1: A happy QA tester hands a small, cute, smiling cartoon bug to a DevOps engineer. The speech bubble from the tester says, \"Found a minor issue!\" Panel 2: The DevOps engineer opens a door labeled \"Server Room,\" and a colossal, terrifying Godzilla-sized monster bug is standing inside destroying the infrastructure. The DevOps engineer's speech bubble simply reads, \"Define minor.\"" \
  "Gemini 3.5 Flash" "The Bug Report"

queue_job  9 \
  "A 3-panel comic in a humorous, expressive caricature style. Panel 1: A user with a confused face is typing a single word, \"Cat,\" into a prompt box. Panel 2: An advanced AI robot wearing a wizard hat is sweating profusely, surrounded by complex floating equations and data streams, trying to decipher the intent. Panel 3: The robot proudly presents a masterpiece painting of a hyper-detailed cyberpunk cat riding a monocycle on Mars. The user's speech bubble reads, \"I meant a normal cat.\"" \
  "Gemini 3.5 Flash" "AI Telepathy"

queue_job 10 \
  "A 2-panel comic strip with bold lines and expressive cartoon character design. Panel 1: A system administrator cheerfully clicks a button labeled \"Run Container\" on a laptop. Panel 2: The laptop instantly expands into a massive, overflowing stack of shipping containers that crushes the desk, leaving only the administrator's hands peeking out from underneath. A small speech bubble from under the containers reads, \"Maybe I should have cleared the cache.\"" \
  "Gemini 3.5 Flash" "The Docker Overload"

# --- ChatGPT ---
queue_job 11 \
  "A 3-panel comic illustration in a colorful caricature style. Panel 1: A nervous fluffy cat staring at a simple message on a phone: \"ok.\" The cat is sweating, eyes wide. Thought bubble: \"What does 'ok' mean?? Is it angry ok? Sad ok? Secretly hates me ok??\" Panel 2: The cat surrounded by conspiracy board-style notes, red strings, multiple versions of \"ok???\" written everywhere. Panel 3: A relaxed dog lying on a couch, looking at the same message and smiling. Speech bubble: \"ok 👍\". Clean line art, expressive faces, humorous exaggeration, vibrant colors." \
  "ChatGPT" "Overthinking Cat vs Chill Dog"

queue_job 12 \
  "A 2-panel comic in a bold, exaggerated cartoon style. Panel 1: A super muscular character dramatically lifting weights in a glowing gym with sparkles, shouting: \"NO PAIN NO GAIN!!\" Panel 2: Same character at home trying to do one push-up, collapsing instantly on the floor. Speech bubble: \"ok maybe small pain… very small gain.\" Slightly messy room, comedic contrast, dynamic poses, bright and playful palette." \
  "ChatGPT" "Gym Motivation Reality"

queue_job 13 \
  "A 3-panel comic with soft pastel colors and cute expressive characters. Panel 1: A person confidently setting an alarm at 7:00 AM. Speech bubble: \"Tomorrow I fix my life.\" Panel 2: Night scene, same person wide awake at 3:27 AM scrolling phone. Thought bubble: \"Just one more video…\" Panel 3: Alarm ringing, person is a chaotic blanket burrito screaming. Speech bubble: \"WHO SET THIS???\" Cozy but chaotic vibe, exaggerated emotions, simple clean comic layout." \
  "ChatGPT" "Sleep Schedule Logic"

queue_job 14 \
  "A 2-panel comic in a modern digital illustration style. Panel 1: A robot at a computer instantly generating a beautiful masterpiece image. Speech bubble: \"Done in 2 seconds.\" Panel 2: A human artist surrounded by crumpled papers, coffee cups, and chaos, staring at a blank canvas. Thought bubble: \"maybe I move this pixel 1px left…\" Light satire, expressive frustration, stylized contrast between clean tech and messy human environment." \
  "ChatGPT" "AI vs Human Creativity"

queue_job 15 \
  "A 3-panel comic in a playful meme-like illustration style. Panel 1: A character buying healthy food: vegetables, fruits, labeled \"new life.\" Big smile. Panel 2: Fridge full of healthy food untouched, character eating pizza instead. Speech bubble: \"I start tomorrow.\" Panel 3: Same groceries now sad and slightly wilted with tiny faces. One broccoli says in a small speech bubble: \"we believed in you…\" Bright colors, humorous anthropomorphic food, clean comic framing." \
  "ChatGPT" "Healthy Lifestyle Starter Pack"

# --- Grok ---
queue_job 16 \
  "A funny 2-panel comic in caricature style: Panel 1 shows a confused cat sitting on a Schrödinger's box thinking \"Am I alive or dead?\"; Panel 2 the box opens with the cat jumping out happily saying \"Both! But mostly hungry\", vibrant colors, exaggerated expressions, meme style illustration." \
  "Grok" "Cat's Quantum Dilemma"

queue_job 17 \
  "3-panel comic caricature: Panel 1 man wakes up and checks phone \"Good morning world\"; Panel 2 phone replies in bubble \"No, check your notifications first\"; Panel 3 man exhausted at night still scrolling while phone says \"Goodnight? Not yet\", humorous exaggerated faces, clean comic style." \
  "Grok" "Smartphone Overlord"

queue_job 18 \
  "Funny 2-panel illustration in comic caricature style: Panel 1 chubby character proudly says \"Today I start my diet!\" while holding salad; Panel 2 same character surrounded by pizza boxes thinking \"Tomorrow is a better day\", bold lines, vibrant colors, meme vibe." \
  "Grok" "Diet Starts Tomorrow"

queue_job 19 \
  "3-panel comic in funny caricature style: Panel 1 human brain says \"I need coffee\"; Panel 2 AI brain glowing \"I calculated 5000 possibilities\"; Panel 3 both exhausted with human saying \"We still can't decide what to eat\", exaggerated cartoon features." \
  "Grok" "AI vs Human Brain"

queue_job 20 \
  "2-panel humorous comic illustration: Panel 1 person at desk says \"Time to work!\"; Panel 2 same person 5 hours later surrounded by snacks and tabs thinking \"Just one more video...\", big expressive faces, bright meme comic style with speech bubbles." \
  "Grok" "Procrastination Champion"

# --- Copilot ---
queue_job 21 \
  "Comic strip illustration of a cat sitting on a laptop, owner in next panel yelling \"Not again!\", cat thinking bubble \"I'm updating your software…\", caricature style, 2-3 panels, funny meme vibe." \
  "Copilot" "Cat vs Laptop"

queue_job 22 \
  "Comic strip illustration of a sleepy person holding coffee mug, second panel shows them suddenly energized, speech bubble \"Now I can pretend to be productive!\", caricature style, 2-3 panels, humorous meme tone." \
  "Copilot" "Coffee Before Work"

queue_job 23 \
  "Comic strip illustration of a dog running wildly in living room, second panel shows knocked over lamp, owner speech bubble \"Why do you do this?!\", dog thinking bubble \"Because speed is life!\", caricature style, 2-3 panels, funny meme." \
  "Copilot" "Dog Zoomies Disaster"

queue_job 24 \
  "Comic strip illustration of person staring at router, second panel shows them raising hands dramatically, speech bubble \"Oh mighty WiFi, return!\", caricature style, 2-3 panels, humorous meme style." \
  "Copilot" "WiFi Struggles"

queue_job 25 \
  "Comic strip illustration of person imagining themselves muscular in first panel, second panel shows them struggling with tiny dumbbell, speech bubble \"Almost there…\", caricature style, 2-3 panels, funny meme comic." \
  "Copilot" "Gym Expectations vs Reality"

# --- Mistral ---
queue_job 26 \
  "A 3-panel comic in a vibrant, cartoonish style: Panel 1: A squirrel in a tiny suit, holding a clipboard, standing in front of a tree with a single acorn. The squirrel's thought bubble: \"Winter is coming...\" Panel 2: The squirrel now has a team of 10 squirrels in hard hats, building a massive underground bunker filled with acorns, nuts, and canned goods. Panel 3: Winter arrives, and the squirrel sits alone in the bunker, surrounded by untouched supplies, looking bored. Speech bubble: \"Well, this is underwhelming.\"" \
  "Mistral" "The Overprepared Squirrel"

queue_job 27 \
  "A 2-panel comic in a minimalist, bold-line illustration style: Panel 1: A cat sitting on a couch, staring intently at a goldfish bowl. Thought bubble: \"Step 1: Distract the human.\" Panel 2: The same cat now wearing a tiny chef's hat, serving the goldfish a gourmet meal on a tiny plate. The goldfish looks shocked. Speech bubble: \"Step 2: Befriend the snack.\"" \
  "Mistral" "The Cat's Master Plan"

queue_job 28 \
  "A 3-panel comic in a dynamic, exaggerated caricature style: Panel 1: A person in workout clothes, flexing in front of a mirror, looking determined. Thought bubble: \"Today is the day!\" Panel 2: The same person lying on the couch, eating chips, watching TV. Speech bubble: \"But first, a 5-minute break.\" Panel 3: The person is now asleep on the couch, chips scattered everywhere. Thought bubble: \"Tomorrow, for sure.\"" \
  "Mistral" "The Gym Motivation Struggle"

queue_job 29 \
  "A 2-panel comic in a playful, hand-drawn style: Panel 1: A dog sitting at a desk with a laptop, a coffee cup, and a stack of papers. Speech bubble: \"Time to work!\" Panel 2: The dog is now napping on the keyboard, drooling on the laptop. Thought bubble: \"Productivity level: 100%.\"" \
  "Mistral" "The Dog's Guide to Productivity"

queue_job 30 \
  "A 3-panel comic in a retro, 90s cartoon style: Panel 1: A tired-looking person holding a coffee cup, staring at a coffee machine. Thought bubble: \"Just one more cup...\" Panel 2: The person is now shaking, with wide eyes, holding 5 coffee cups. Speech bubble: \"I can stop anytime I want.\" Panel 3: The person is now a jittery, caffeine-fueled blur, zooming around the room. Thought bubble: \"Maybe I'll stop tomorrow.\"" \
  "Mistral" "The Coffee Addict's Dilemma"

# --- Qwen 3.6 Plus ---
queue_job 31 \
  "A funny 2-panel comic illustration in a vibrant caricature style. Panel 1 shows a sleepy cartoon character in bed looking peacefully at an alarm clock reading 7:00 AM, with a neat thought bubble saying \"I will just rest my eyes.\" Panel 2 shows the same character frantically flying out of bed completely tangled in blankets, while the clock now reads 9:45 AM, with a large jagged speech bubble exclaiming \"TIME IS A LIE!\" White comic panel borders, bold ink outlines, exaggerated expressive faces, clean vector illustration, humorous tone, square composition." \
  "Qwen 3.6 Plus" "The Monday Morning Alarm"

queue_job 32 \
  "A humorous 3-panel comic strip in a modern webtoon caricature style. Panel 1 features a nerdy cartoon programmer sitting at a desk, looking confident while typing code on a laptop, with a speech bubble saying \"It works on my machine!\" Panel 2 shows a cartoon server rack in a dark room suddenly catching fire with small stylized flames, a thought bubble above it reads \"Hold my beer.\" Panel 3 depicts the programmer staring wide-eyed in panic as a giant cartoon beetle crawls out of the laptop screen, speech bubble reading \"WHY ARE YOU HERE?!\" Clean line art, bright flat colors, clear panel dividers, funny tech meme vibe." \
  "Qwen 3.6 Plus" "Debugging Reality"

queue_job 33 \
  "A funny 2-panel comic illustration in a cute caricature drawing style. Panel 1 shows a chubby round cartoon dog sitting proudly next to a full bowl of broccoli, with a speech bubble saying \"New diet starts now!\" Panel 2 shows the exact same dog sitting next to the knocked-over vegetable bowl, with a trail of muddy paw prints leading to an empty pizza box, the dog has a guilty but satisfied grin with a thought bubble saying \"Diet starts tomorrow.\" Hand-drawn comic aesthetic, bold outlines, pastel background, humorous animal meme composition." \
  "Qwen 3.6 Plus" "The Diet Plan"

queue_job 34 \
  "A witty 3-panel comic in a clean expressive caricature illustration style. Panel 1 shows an office worker staring at a blank monitor, sweating nervously, with a thought bubble reading \"Just say per my last email...\" Panel 2 shows the character aggressively typing, eyes wide with fake enthusiasm, speech bubble says \"I hope this email finds you well!!\" Panel 3 shows the worker hitting send then instantly collapsing face-first onto the keyboard in dramatic exhaustion, with a tiny speech bubble saying \"Send.\" Comic book shading, exaggerated body language, crisp panel layout, lighthearted workplace humor." \
  "Qwen 3.6 Plus" "The Email Paradox"

queue_job 35 \
  "A hilarious 2-panel comic illustration in a retro cartoon style. Panel 1 shows a person lying comfortably on a couch scrolling on a smartphone, looking totally relaxed, a floating battery icon above shows 15%, thought bubble says \"Plenty of battery left...\" Panel 2 shows the exact same person in a dramatic horror pose, holding the phone up like a sacred artifact as it hits 4% battery, sweating profusely with a huge speech bubble reading \"WHERE IS THE CHARGER?!\" Bold outlines, dynamic poses, bright comic book colors, funny modern life meme layout." \
  "Qwen 3.6 Plus" "Battery Anxiety"

# --- GLM 5.1 ---
queue_job 36 \
  "A 2-panel comic strip illustration in a humorous caricature style. Panel 1: A chubby man looking sadly at a tiny plate with a single lettuce leaf. A speech bubble above him says \"I am on a strict diet!\". Panel 2: The same man joyfully devouring an enormous entire pepperoni pizza. A speech bubble says \"A strict diet of pure denial!\". Bold comic outlines, vibrant colors, exaggerated facial expressions." \
  "GLM 5.1" "Diet Denial"

queue_job 37 \
  "A 2-panel funny comic illustration in a cartoonish caricature style. Panel 1: A dog wearing glasses and a business tie is working at a laptop, looking very serious. A thought bubble says \"They'll never know\". Panel 2: The dog is happily chewing on the laptop keyboard with a goofy expression. A speech bubble says \"I have no idea what I'm doing!\". Clean lines, comic book shading, expressive." \
  "GLM 5.1" "Imposter Syndrome Dog"

queue_job 38 \
  "A 3-panel comic illustration in a funny caricature style. Panel 1: A tired man in bed looking at an alarm clock showing 6:00 AM. A speech bubble says \"Just five more minutes\". Panel 2: The man sleeping deeply, the clock now shows 10:00 AM. Panel 3: The man is rushing in a panic, putting on his pants. A speech bubble says \"Time is a social construct!\". Comic book style, dynamic, humorous." \
  "GLM 5.1" "Time Is A Construct"

queue_job 39 \
  "A 2-panel comic strip in a caricature illustration style. Panel 1: A confused cat looking at an expensive, luxurious fluffy cat bed. The owner has a speech bubble saying \"It cost me 100 dollars!\". Panel 2: The cat is sleeping comfortably inside the cheap cardboard box the bed was packaged in. The cat has a thought bubble saying \"I prefer the box\". Exaggerated comic style, bold lines, funny." \
  "GLM 5.1" "Expensive Cat Bed"

queue_job 40 \
  "A 2-panel humorous comic illustration in a caricature style. Panel 1: A stressed person holding a coffee mug, talking to a smart speaker on a desk. A speech bubble says \"Smart speaker, motivate me!\". Panel 2: The smart speaker with a smug, cartoonish face on its screen. A speech bubble says \"You paid 200 bucks for me to tell you to work?\". Vibrant comic colors, funny expressions, clear text." \
  "GLM 5.1" "Sassy Smart Speaker"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A funny 2-panel comic illustration in bold caricature style with thick black outlines and vibrant colors. Panel 1: A disheveled person with wild messy hair sits in bed staring at a ringing alarm clock, speech bubble says \"5 more minutes\". Panel 2: The same person suddenly jolts awake with huge panicked eyes looking at a phone showing 9:00 AM, speech bubble says \"I AM DOOMED\". Exaggerated facial expressions, meme humor, comic book art style." \
  "Kimi K2.6 Thinking" "Monday Morning Tragedy"

queue_job 42 \
  "A humorous 2-panel comic illustration in cartoon style with bright flat colors and bold outlines. Panel 1: A fluffy unimpressed cat ignoring a luxurious fancy cat bed, speech bubble says \"Trash\". Panel 2: The same cat joyfully squeezed inside a tiny torn cardboard box looking like royalty, speech bubble says \"Palace\". Exaggerated expressions, speech bubbles with short text, meme comic format." \
  "Kimi K2.6 Thinking" "Cat Logic Explained"

queue_job 43 \
  "A funny 3-panel developer comic in caricature style with bold comic outlines and bright colors. Panel 1: A smiling programmer at a computer with green working code, speech bubble says \"It works!\". Panel 2: The programmer calmly adding a comment to the code, speech bubble says \"// nice\". Panel 3: The programmer staring at a screen full of red error messages in absolute horror, speech bubble says \"HOW?!\". Exaggerated reactions, speech bubbles, meme humor." \
  "Kimi K2.6 Thinking" "Coding Reality"

queue_job 44 \
  "A humorous 2-panel comic illustration in cartoon style with vibrant colors and thick outlines. Panel 1: A golden retriever lying dramatically on a vet examination table with one paw over its forehead looking half-dead, speech bubble says \"Final hour\". Panel 2: The exact same dog at the park sprinting at full speed with tongue flying and ears back chasing a tennis ball, speech bubble says \"IMMORTAL\". Exaggerated poses, speech bubbles, meme comic art." \
  "Kimi K2.6 Thinking" "Dog Acting Academy"

queue_job 45 \
  "A funny 3-panel comic illustration in caricature style with dynamic bold outlines and bright colors. Panel 1: A zombie-like office worker slumped over a desk looking lifeless, speech bubble says \"Empty shell\". Panel 2: The worker holding a giant steaming coffee cup surrounded by magical sparkles, speech bubble says \"The elixir\". Panel 3: The same worker typing furiously with multiple arms and lightning speed effects, speech bubble says \"GOD MODE\". Exaggerated expressions, speech bubbles with short text." \
  "Kimi K2.6 Thinking" "Coffee Magic"

# --- Deepseek ---
queue_job 46 \
  "A 2-panel comic in caricature style. Panel 1: A chubby orange cat sitting on a couch, looking at a closed laptop. Speech bubble: \"If I fits...\" Panel 2: The same cat now squeezed on top of the closed laptop, looking proud. Speech bubble: \"...I sits on your work\". Bold outlines, bright colors, meme comic style." \
  "Deepseek" "Cat Logic"

queue_job 47 \
  "A 3-panel comic, cartoon illustration. Panel 1: A person in pajamas looking at a fridge at midnight, with a thought bubble showing a salad. Panel 2: Person reaching for a huge chocolate cake instead, sweat drop on forehead. Panel 3: Person eating cake happily, thought bubble showing a sad salad saying \"Tomorrow.\"" \
  "Deepseek" "The Diet Trap"

queue_job 48 \
  "A 2-panel comic in funny caricature style. Panel 1: A programmer at a computer desk, screaming at the screen. Speech bubble: \"WHERE IS THE BUG?!\" Panel 2: The programmer holding a tiny literal bug (a beetle) wearing a tiny hoodie and sunglasses. The bug has a speech bubble: \"I'm right here, bro.\"" \
  "Deepseek" "Programmer vs. Bug"

queue_job 49 \
  "A 3-panel comic, cartoon style with thick outlines. Panel 1: Owner holding a leash, saying \"Let's go for a walk!\" Dog's eyes wide with excitement. Panel 2: Owner adds \"But first, let me finish my email.\" Dog now has a flat expression. Panel 3: Dog holding a smartphone showing a meme of a sad dog, with text bubble: \"Me waiting. Forever.\"" \
  "Deepseek" "Dog's Priorities"

queue_job 50 \
  "A 2-panel comic, caricature illustration. Panel 1: A person in the shower with shampoo on head, having a lightbulb above head. Thought bubble: \"I should solve world hunger.\" Panel 2: Same person now dried and dressed, sitting on a couch staring at a phone. Thought bubble: \"Anyway...\" and a tiny tumbleweed rolling by." \
  "Deepseek" "Shower Thoughts"

# --- ERNIE 5.1 Thinking ---
queue_job 51 \
  "A funny 3-panel comic in bold caricature cartoon style, panel 1: a chubby orange cat sitting innocently on a kitchen table with a smug face, panel 2: the cat slowly pushing a glass of water to the edge with one paw looking straight at the viewer, panel 3: the glass shattered on the floor, the cat looking away pretending nothing happened, speech bubble in panel 1 says \"I would never\", speech bubble in panel 3 says \"gravity did it\", exaggerated expressions, bright colors, thick black outlines, meme comic style." \
  "ERNIE 5.1 Thinking" "Cat Knocking Things Off Table"

queue_job 52 \
  "A hilarious 2-panel comic in exaggerated caricature style, panel 1: a disheveled programmer at a messy desk at 3AM surrounded by energy drink cans, staring at code on the screen with wild eyes, thinking bubble says \"it's just a missing semicolon\", panel 2: the same programmer now head-down asleep on the keyboard, the screen shows 47 errors, a small speech bubble from the monitor says \"lol no\", comic book style, bold lines, vibrant colors, meme humor." \
  "ERNIE 5.1 Thinking" "Programmer Debugging at 3AM"

queue_job 53 \
  "A funny 3-panel comic in chunky caricature illustration style, panel 1: an alarm clock screaming at 6AM, panel 2: a zombie-like person shuffling toward the kitchen with dead eyes and messy hair, thought bubble says \"just 5 more minutes\", panel 3: the same person now fully alive and smiling holding a giant coffee mug, speech bubble says \"I can do anything now\", bold comic outlines, bright pop colors, meme comic format." \
  "ERNIE 5.1 Thinking" "Monday Morning Coffee"

queue_job 54 \
  "A hilarious 2-panel comic in exaggerated cartoon caricature style, panel 1: a small fluffy dog standing heroically in front of a vacuum cleaner like a warrior, dramatic wind blowing, speech bubble says \"you shall not pass\", panel 2: the same dog now hiding behind the owner's legs trembling comically while the vacuum is off, speech bubble says \"ok it won\", bold black outlines, vibrant saturated colors, funny meme comic aesthetic." \
  "ERNIE 5.1 Thinking" "Dog vs Vacuum Cleaner"

queue_job 55 \
  "A funny 3-panel comic in bold caricature comic style, panel 1: a person typing a super long WiFi password on their phone with a proud face, speech bubble says \"nobody will ever guess this\", panel 2: the neighbor casually knocking on the door holding a beer, panel 3: both sitting together on the couch, the neighbor's phone connected to the WiFi, speech bubble from neighbor says \"it was your dog's name bro\", exaggerated funny expressions, thick comic outlines, bright meme colors." \
  "ERNIE 5.1 Thinking" "WiFi Password Neighbor"

echo "✅ All 55 jobs queued in scheduler"
