#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Retro-modern glamour photo shoot — 1950s pinup character in a rural
#        golden-hour setting, consistent look across all prompts
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+39+-+Retro-modern+glamour+photo+shoot
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------
# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A 1950s-inspired pinup model with voluminous curled auburn hair and crimson lips reclines atop a large round wheat roll bale in a golden wheat field, one leg extended to show off glossy leather pumps, fitted red polka-dot dress hem lifted slightly by the breeze. She gazes over her shoulder with a confident, seductive expression, sunset light raking low across the field and casting long amber shadows. Loose wheat chaff and dust drift through the warm air, catching the light like glowing particles. Filmic color grading, rich warm tones, cinematic depth of field, ultra-detailed leather texture and fabric weave, wind-blown hair strands, golden hour glow, rural countryside backdrop with a distant old barn silhouette." \
  "Claude Sonnet 5 medium" "Wheat Roll Recline"

queue_job  2 \
  "The same 1950s pinup model, wavy auburn hair tousled by wind, leans back against the weathered wooden door of a rustic red barn, ankles crossed to display sleek leather pumps, her fitted vintage dress catching the breeze against her hips. Her seductive gaze meets the camera directly, lips parted in a knowing smile, golden hour sunlight streaming sideways through gaps in the barn wood, illuminating drifting dust motes in the air. Cinematic filmic grain, warm saturated color grading, deep shadows and glowing highlights, hyper-detailed cracked wood and leather texture, fabric rippling in the wind, wheat field stretching softly out of focus behind her." \
  "Claude Sonnet 5 medium" "Barn Door Lean"

queue_job  3 \
  "The same 1950s pinup model perches on the curved hood of a vintage chrome-trimmed car parked at the edge of a golden wheat field, one leather-pumped foot propped on the bumper, dress fabric clinging and fluttering in the evening wind. She leans back on braced arms, chin tilted, eyes half-lidded with a confident seductive stare toward the lens. Low sunset light gleams off the polished chrome and her wind-tossed curls, dust and pollen drifting through glowing amber light. Rich filmic color grading, deep cinematic contrast, intricate leather stitching and fabric folds rendered in fine detail, old barn and wind turbine faintly visible in the hazy distance." \
  "Claude Sonnet 5 medium" "Classic Car Hood Pose"

queue_job  4 \
  "Standing beside a weathered wooden split-rail fence bordering a rippling wheat field, the same 1950s pinup model rests one arm along the top rail, hip cocked, leather pumps planted firmly in the golden grass, dress hem swept sideways by the wind. Her expression is bold and seductive, a sideways glance carrying quiet confidence beneath sunset-flushed skin. Warm dust particles drift and sparkle in the low slanting light, wind lifting loose strands of her curled hair. Cinematic filmic tone, saturated golden-hour palette, richly detailed leather sheen and woven fabric texture, an antique multiblade wind turbine turning slowly in the softly blurred background." \
  "Claude Sonnet 5 medium" "Wooden Fence Stance"

queue_job  5 \
  "Seated casually on a stack of hay bales beside an old rusted tractor parked in the wheat field, the same 1950s pinup model crosses her legs to showcase her leather pumps, dress fabric bunched and wind-rippled at her thighs. She leans one hand on the tractor's fender, gazing back over bare shoulder with a sultry, self-assured smile, golden hour light bathing her in warm amber tones. Fine dust and straw particles float through the glowing air, her curls catching stray light. Filmic cinematic color grading, deep warm shadows, intricately rendered leather and fabric textures, distant barn roofline glowing at the field's edge." \
  "Claude Sonnet 5 medium" "Hay Bale and Tractor"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A stunning 1950s-inspired pinup model with a confident, seductive gaze is sitting gracefully on the rusted fender of a vintage red tractor. She wears a vibrant emerald-green swing dress and glossy black leather pumps. The scene is set in a vast rural field during golden hour, with a warm sunset casting long shadows and a rich orange glow. Wind-blown hair and fabric flutter gently. In the background, an old multiblade wind turbine stands against the sky. Drifting dust particles and golden pollen shimmer in the air. The cinematic photo features deep textures on the leather, fabric folds, and a beautifully graded, filmic look." \
  "Gemini 3.5 Flash" "Golden Hour Tractor Pose"

queue_job  7 \
  "A gorgeous 1950s-inspired pinup model with a confident, seductive gaze leans back against a weathered wooden fence in a rural countryside. She wears a classic navy-blue polka-dot A-line dress and matching dark leather pumps. The setting sun of golden hour bathes her in a warm, rich amber light, creating a cinematic atmosphere. A gentle breeze whips her styled hair and the hem of her dress. Swirling dust particles and light specks drift through the air. In the background, large wheat rolls dot the landscape under a hazy sky, captured with incredible material detail on the leather, wood grain, and soft fabric." \
  "Gemini 3.5 Flash" "Rustic Fence Solitude"

queue_job  8 \
  "A captivating 1950s-inspired pinup model with a confident, seductive gaze is elegantly reclining on a large hay bale. She is dressed in a cherry-red sweetheart-neckline dress and sleek, polished cherry-red leather pumps. The rural scene is illuminated by the intense, warm glow of golden hour sunset. A soft wind rustles her styled hair and the flowing fabric of her dress. In the distance, an weathered old barn stands under the cinematic sky. Fine dust particles and golden chaff drift lazily in the warm air. The photo showcases exceptional textures of rough straw, smooth leather, and delicate fabric with rich color grading." \
  "Gemini 3.5 Flash" "Sunset Hay Bale Recline"

queue_job  9 \
  "An alluring 1950s-inspired pinup model with a confident, seductive gaze is perched playfully on the hood of a classic cream-colored car. She wears a pastel yellow halter dress and elegant brown leather pumps. The rural backdrop features a sweeping wheat field during golden hour, with the setting sun casting a warm, rich honey-colored light over the entire scene. Breezes gently ruffle her hair and dress. Glistening dust particles float in the cinematic air. This filmic shot emphasizes sharp material details, from the reflective chrome and leather shoes to the soft fabric folds, captured with gorgeous, warm color grading." \
  "Gemini 3.5 Flash" "Vintage Hood Glamour"

queue_job 10 \
  "A striking 1950s-inspired pinup model with a confident, seductive gaze stands close to a massive, weathered barn door. She wears a deep plum-colored retro wrap dress and matching high-heeled leather pumps. The rural sunset at golden hour wraps the scene in a warm, cinematic orange light. A sudden gust of wind blows her styled hair and the light fabric of her dress. Tiny dust motes and drifting straw particles shimmer in the dramatic sunbeams. The composition highlights incredible texture contrasts between the rough, aged wood, polished leather, and soft textile, rendered in a rich, beautifully graded filmic style." \
  "Gemini 3.5 Flash" "Weathered Barn Door Portrait"

# --- ChatGPT ---
queue_job 11 \
  "A glamorous 1950s-inspired pinup woman with softly curled auburn hair appears consistently as the same character, wearing an elegant fitted emerald-green vintage dress and polished dark brown leather pumps. She leans confidently against the hood of a beautifully restored cream-colored classic automobile parked beside endless wheat fields at golden hour. A gentle breeze lifts her hair and flowing skirt while her confident, seductive gaze meets the camera. Warm sunset light creates cinematic highlights across smooth leather shoes, textured fabric, and polished chrome. Dust motes float through the glowing air, producing a nostalgic rural atmosphere with rich color grading, subtle film grain, exceptional material realism, dramatic depth, and timeless retro-modern glamour photography." \
  "ChatGPT" "Golden Hour by the Classic Car"

queue_job 12 \
  "The same glamorous 1950s-inspired pinup woman with softly curled auburn hair wears the identical emerald-green vintage dress and polished dark brown leather pumps, maintaining her unmistakable appearance. She casually leans one shoulder against a weathered wooden barn door, one foot crossed gracefully before the other, smiling with a confident, seductive gaze. Golden-hour sunlight washes across aged timber, worn paint, supple leather, and flowing fabric, revealing extraordinary surface detail. Wind catches loose strands of hair and the hem of her dress while tiny drifting dust particles sparkle in the warm rural air. An old wheat field and rustic farm surroundings create a nostalgic cinematic composition with luxurious color grading and authentic filmic atmosphere." \
  "ChatGPT" "Barn Door Sunset Elegance"

queue_job 13 \
  "The same recognizable 1950s-inspired pinup model, with softly curled auburn hair, elegant emerald-green vintage dress, and polished dark brown leather pumps, sits gracefully atop stacked hay bales in a harvested wheat field during golden hour. She rests one hand behind her while the other lightly touches her knee, turning toward the camera with a confident, seductive expression. Warm sunset rays illuminate every woven straw texture, every fold of fabric, and the smooth sheen of fine leather shoes. Gentle wind animates her dress and hair while floating chaff and glowing dust create magical depth. Rich cinematic color grading, subtle analog film character, incredible material realism, and peaceful rural scenery complete this retro-modern glamour editorial photograph." \
  "ChatGPT" "Hay Bale Evening Portrait"

queue_job 14 \
  "The same elegant 1950s-inspired pinup woman with softly curled auburn hair continues wearing her emerald-green vintage dress and polished dark brown leather pumps. She stands beside an old multiblade farm windmill, one hand resting on its weathered support while the other gathers her wind-blown skirt. Her confident, seductive gaze faces the viewer as golden-hour sunlight silhouettes the iconic windmill against glowing wheat fields. Warm cinematic light enhances aged galvanized metal, soft fabric folds, glossy leather footwear, and naturally sunlit skin. Tiny drifting dust particles shimmer in the air, adding atmosphere and depth. Rich filmic color grading, nostalgic rural styling, extraordinary texture rendering, and timeless editorial glamour define the entire composition." \
  "ChatGPT" "Windmill Horizon Fashion"

queue_job 15 \
  "The same glamorous 1950s-inspired pinup character with softly curled auburn hair, wearing her signature emerald-green vintage dress and polished dark brown leather pumps, stands beside a massive round wheat roll in an open countryside field at golden hour. One hand rests gently on the straw bale while she turns slightly over her shoulder, offering a confident, seductive gaze toward the camera. Warm sunset light pours across golden straw, flowing fabric, smooth leather, and sunlit skin with remarkable material detail. Wind ripples through her dress and hair as glowing dust and tiny floating particles enrich the tranquil atmosphere. Cinematic framing, luxurious color grading, subtle film texture, and nostalgic retro-modern fashion photography create an unforgettable rural glamour scene." \
  "ChatGPT" "Among the Wheat Rolls"

# --- Grok fast ---
queue_job 16 \
  "A stunning 1950s-inspired pinup model with hourglass figure, voluminous wavy auburn hair, flawless porcelain skin, and bold red lips, wearing a form-fitting polka-dot vintage dress and glossy black leather pumps. She leans seductively against the hood of a vintage classic car in a golden wheat field at sunset, one leg bent, hand on hip, wind dramatically blowing her hair and dress fabric. Confident seductive gaze directly at viewer. Warm golden hour sunlight, rich cinematic color grading, filmic look, incredible detailed textures on leather pumps and dress fabric, floating dust particles and glowing sun flares in the air, retro-modern glamour photoshoot style." \
  "Grok fast" "Golden Hour Pinup on Classic Car"

queue_job 17 \
  "A stunning 1950s-inspired pinup model with hourglass figure, voluminous wavy auburn hair, flawless porcelain skin, and bold red lips, wearing a form-fitting polka-dot vintage dress and glossy black leather pumps. She poses confidently leaning back against a weathered old barn door, body slightly arched, one hand running through her wind-swept hair, in rural golden wheat fields at sunset. Seductive direct gaze. Warm golden hour lighting casting long shadows, rich vibrant color grading, filmic cinematic atmosphere, exquisite material details on dress and shiny leather, drifting golden dust particles in the breeze, retro-modern glamour style." \
  "Grok fast" "Barn Door Seduction"

queue_job 18 \
  "A stunning 1950s-inspired pinup model with hourglass figure, voluminous wavy auburn hair, flawless porcelain skin, and bold red lips, wearing a form-fitting polka-dot vintage dress and glossy black leather pumps. She sits playfully on stacked golden hay bales in a vast wheat field during golden hour, legs crossed elegantly, wind tousling her hair and dress. Confident seductive expression with sultry eyes. Beautiful warm sunset glow, rich cinematic color grading, filmic look, hyper-detailed fabric and leather textures, soft drifting particles in the air, retro-modern glamour photoshoot aesthetic." \
  "Grok fast" "Hay Bale Pinup Dream"

queue_job 19 \
  "A stunning 1950s-inspired pinup model with hourglass figure, voluminous wavy auburn hair, flawless porcelain skin, and bold red lips, wearing a form-fitting polka-dot vintage dress and glossy black leather pumps. She stands leaning against a rustic wooden fence bordering endless rolling wheat fields at golden hour, body angled gracefully, wind-blown hair and fluttering dress fabric. Intense confident seductive gaze. Lush warm sunset lighting, rich filmic color grading, cinematic composition, outstanding detail on leather and dress materials, floating dust motes in golden light, retro-modern glamour style." \
  "Grok fast" "Wheat Field Fence Pose"

queue_job 20 \
  "A stunning 1950s-inspired pinup model with hourglass figure, voluminous wavy auburn hair, flawless porcelain skin, and bold red lips, wearing a form-fitting polka-dot vintage dress and glossy black leather pumps. She poses dynamically standing near an old multiblade wind turbine in rural wheat fields at sunset, one hand resting on the structure, wind dramatically catching her hair and dress. Seductive confident stare at viewer. Magical golden hour illumination, rich cinematic color grading, filmic aesthetic, intricate material details on fabric and leather, drifting particles in the warm air, retro-modern glamour photoshoot." \
  "Grok fast" "Wind Turbine Vintage Glamour"

# --- Copilot Smart ---
queue_job 21 \
  "A 1950s-inspired pinup model in a flowing dress and leather pumps leans seductively against the hood of a polished classic car parked in a rural wheat field at golden hour. Her wind-blown hair and fabric catch the warm sunset light, while drifting dust particles shimmer in the air. The confident gaze and cinematic color grading emphasize retro-modern glamour. The car's chrome reflects the golden hues, and the wheat rolls in the background add rustic charm. Rich material detail on leather and fabric enhances the filmic look, blending nostalgia with modern aesthetics in a striking, seductive pose." \
  "Copilot Smart" "Golden Hour on Classic Car Hood"

queue_job 22 \
  "The same pinup model poses confidently against the weathered wooden door of an old barn, her dress flowing in the warm breeze. Golden hour light bathes her in radiant tones, highlighting the texture of leather pumps and fabric. Dust particles drift through the air, adding cinematic atmosphere. Her seductive gaze contrasts with the rustic backdrop, while the barn's aged wood and iron hinges frame her figure. The filmic color grading and rich detail create a timeless glamour shot, blending rural authenticity with retro-modern allure in a captivating composition." \
  "Copilot Smart" "Barn Door Elegance"

queue_job 23 \
  "The pinup model sits gracefully atop stacked hay bales in a wheat field, her dress draping elegantly as the sunset casts golden light across the scene. Wind tousles her hair and fabric, while drifting particles shimmer in the cinematic glow. Her confident, seductive gaze draws focus, with leather pumps catching subtle highlights. The rustic hay texture contrasts with the polished glamour of her styling. Rich color grading and filmic atmosphere enhance the retro-modern aesthetic, creating a striking balance between rural simplicity and timeless elegance." \
  "Copilot Smart" "Hay Bale Seduction"

queue_job 24 \
  "The model leans against a weathered wooden fence, her dress flowing in the breeze as golden hour light illuminates her figure. Dust and drifting particles add cinematic depth to the rural setting. Her confident gaze and wind-blown hair embody retro-modern glamour, while the leather pumps and fabric textures are rendered with incredible detail. The fence stretches into the wheat field, guiding the eye through the composition. Rich color grading and filmic atmosphere merge rustic authenticity with seductive elegance, creating a captivating portrait of timeless allure." \
  "Copilot Smart" "Fence Line Glamour"

queue_job 25 \
  "The pinup model stands near an old multiblade wind turbine, her dress and hair caught dramatically in the golden hour breeze. Dust particles drift through the air, enhancing the cinematic atmosphere. Her confident gaze and poised stance exude retro-modern glamour, while leather pumps and fabric textures shine with rich detail. The rustic turbine blades frame her figure against the glowing wheat field backdrop. Filmic color grading and warm sunset tones merge industrial heritage with seductive elegance, creating a strikingly glamorous rural portrait." \
  "Copilot Smart" "Wind Turbine Radiance"

# --- Mistral Think ---
queue_job 26 \
  "A 1950s-inspired pinup model in a flowing red dress and glossy black leather pumps, leaning seductively against the hood of a vintage chrome-finished classic car, golden hour sunlight casting long shadows, wind tousling her hair and the fabric of her dress, confident and alluring gaze, cinematic film grain, rich warm color grading, hyper-detailed leather and fabric textures, dust particles dancing in the air, rural wheat field backdrop, ultra-realistic, 8K resolution." \
  "Mistral Think" "Retro Pinup by the Classic Car"

queue_job 27 \
  "A 1950s-inspired pinup model in a fitted polka-dot dress and patent leather pumps, posing with one hand on her hip and the other resting on a weathered wooden barn door, golden hour glow illuminating her figure, wind-swept hair and flowing dress, smoldering gaze, cinematic depth of field, vibrant sunset tones, intricate wood and leather textures, floating dust motes, rustic barn and wheat field setting, photorealistic, ultra-HD." \
  "Mistral Think" "Glamour on the Barn Door"

queue_job 28 \
  "A 1950s-inspired pinup model in a form-fitting emerald green dress and high-shine leather pumps, sitting gracefully on a stack of golden hay bales, golden hour light enhancing her curves, wind playing with her hair and dress, confident and inviting expression, filmic color grading with warm hues, hyper-detailed fabric and leather, dust and chaff floating in the air, rural farmland background, ultra-sharp, cinematic quality." \
  "Mistral Think" "Elegance Among Hay Bales"

queue_job 29 \
  "A 1950s-inspired pinup model in a sleek black dress and glossy leather pumps, standing near an old multiblade wind turbine, golden hour sunlight creating a dramatic silhouette, wind blowing her hair and dress, bold and captivating gaze, rich cinematic tones, meticulous leather and fabric details, dust particles suspended in the air, open rural landscape, ultra-realistic, 8K clarity." \
  "Mistral Think" "Sophistication by the Wind Turbine"

queue_job 30 \
  "A 1950s-inspired pinup model in a vibrant floral dress and polished leather pumps, leaning back against a rustic wooden fence, golden hour light bathing her in warmth, wind animating her hair and dress, playful yet confident gaze, film-like color saturation, exquisite leather and fabric textures, dust and pollen drifting in the air, wheat field and old barn in the distance, photorealistic, ultra-detailed." \
  "Mistral Think" "Allure on the Wooden Fence"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "A stunning 1950s-inspired pinup model sitting gracefully on the hood of a vintage classic car, legs elegantly crossed. She wears a fitted retro dress and glossy leather pumps. Golden hour warm sunset lighting illuminates her confident seductive gaze. Wind-blown hair and flowing fabric dance in the breeze. Background features golden wheat rolls in a sprawling wheat field. Rich color grading, filmic cinematic look, incredible material detail on the leather shoes and dress fabric. Dust and drifting particles float in the warm air. Retro-modern glamour photo shoot, highly detailed, photorealistic, 8k resolution, shot on 35mm lens, beautiful and serene rural countryside aesthetic." \
  "Qwen 3.7 Plus Tinking" "Golden Hour Glamour on the Classic Car"

queue_job 32 \
  "A beautiful 1950s-inspired pinup model leaning casually against a weathered wooden barn door, one leg bent very elegantly. She wears a vintage sweetheart dress and polished leather pumps. Warm sunset golden hour lighting highlights her confident seductive gaze. Her hair and dress fabric are beautifully wind-blown. Background shows an old rustic barn and a tall old multiblade wind turbine against the sky. Rich color grading, filmic cinematic look, incredible material detail on the leather and fabric. Dust and drifting particles catch the warm light. Retro-modern glamour photo shoot, photorealistic, highly detailed, shot on medium format camera, stunning and peaceful rural aesthetic." \
  "Qwen 3.7 Plus Tinking" "Leaning Against the Weathered Barn Door"

queue_job 33 \
  "A gorgeous 1950s-inspired pinup model standing near some stacked golden hay bales, hand resting gently on the top bale. She wears a classic retro dress and sleek leather pumps. Warm sunset lighting creates a beautiful glowing golden hour effect, emphasizing her confident seductive gaze. Wind-blown hair and dress fabric add beautiful dynamic movement. Background reveals a vast wheat field and distant wheat rolls. Rich color grading, filmic cinematic look, incredible material detail on the leather and fabric textures. Dust and drifting particles float in the warm air. Retro-modern glamour photo shoot, photorealistic, highly detailed, 8k resolution, beautiful and serene rural setting." \
  "Qwen 3.7 Plus Tinking" "Resting by the Golden Hay Bales"

queue_job 34 \
  "A striking 1950s-inspired pinup model sitting on a small vintage wooden crate, leaning forward just slightly with crossed ankles. She wears a form-fitting retro dress and high-quality leather pumps. Warm sunset golden hour lighting enhances her confident seductive gaze. Her hair and dress fabric are gracefully wind-blown. Background features a rustic old multiblade wind turbine and rolling golden wheat fields. Rich color grading, filmic cinematic look, incredible material detail on the leather and fabric. Dust and drifting particles illuminate beautifully in the background. Retro-modern glamour photo shoot, photorealistic, highly detailed, shot on beautiful 35mm film, stunning and peaceful rural aesthetic." \
  "Qwen 3.7 Plus Tinking" "Sitting on the Vintage Wooden Crate"

queue_job 35 \
  "A captivating 1950s-inspired pinup model standing near an old rusty tractor, leaning very gracefully against the rusted metal fender. She wears a beautiful vintage dress and glossy leather pumps. Warm sunset lighting provides a perfect and warm golden hour glow, highlighting her confident seductive gaze. Wind-blown hair and flowing fabric create a deeply romantic atmosphere. Background shows an old barn and golden harvested wheat rolls. Rich color grading, filmic cinematic look, incredible material detail on the leather and fabric. Dust and drifting particles dance in the warm air. Retro-modern glamour photo shoot, photorealistic, highly detailed, 8k resolution, gorgeous and serene rural countryside." \
  "Qwen 3.7 Plus Tinking" "Posing by the Vintage Tractor Fender"

# --- GLM 5.2 Think max ---
queue_job 36 \
  "Retro-modern glamour photo shoot of a beautiful 1950s-inspired pinup model leaning casually against the polished hood of a classic vintage car. She wears a stylish retro dress and glossy leather pumps. Golden hour sunset lighting bathes the rural wheat field background, perfectly highlighting her wind-blown hair and gracefully flowing fabric. She casts a confident seductive gaze directly at the camera lens. Rich color grading, filmic cinematic look, and incredible material detail on leather and fabric. Dust and drifting particles float in the warm evening air, adding deep atmosphere. A large wheat roll sits in the distant background. High resolution, photorealistic, cinematic photography, perfectly capturing a nostalgic yet modern rural aesthetic with stunning, warm textures." \
  "GLM 5.2 Think max" "Classic Car Hood"

queue_job 37 \
  "Retro-modern glamour photo shoot featuring a stunning 1950s-inspired pinup model resting her back against a weathered old wooden barn door. She is dressed in a classic vintage dress and polished leather pumps. Golden hour sunset lighting casts long shadows across the rural setting, beautifully illuminating her wind-blown hair and dynamic fabric. She fixes a confident seductive gaze upon the lens. Rich color grading, filmic cinematic look, and incredible material detail on leather and fabric. Dust and drifting particles dance in the sunbeams cutting through the barn cracks. The old barn wood shows rich grain. Photorealistic, high resolution, cinematic photography, exuding a nostalgic rural aesthetic with deep, warm tones and striking textures." \
  "GLM 5.2 Think max" "Barn Door"

queue_job 38 \
  "Retro-modern glamour photo shoot of a gorgeous 1950s-inspired pinup model sitting sideways on a large golden hay bale. She wears a fitted vintage dress and sleek leather pumps. In the background, an old multiblade wind turbine stands tall against a rural sky. Golden hour sunset lighting envelops the scene, emphasizing her wind-blown hair and flowing fabric. She delivers a confident seductive gaze to the camera. Rich color grading, filmic cinematic look, and incredible material detail on leather and fabric. Dust and drifting particles linger in the warm air. The rusty metal of the turbine glows. Photorealistic, high resolution, cinematic photography, capturing a perfect blend of retro beauty and rustic rural aesthetics." \
  "GLM 5.2 Think max" "Hay Bale"

queue_job 39 \
  "Retro-modern glamour photo shoot showcasing a stunning 1950s-inspired pinup model leaning elegantly against a massive rolled wheat bale in a vast rural wheat field. She is wearing a chic vintage dress and textured leather pumps. Golden hour sunset lighting floods the landscape, catching her wind-blown hair and rippling fabric. She offers a confident seductive gaze toward the viewer. Rich color grading, filmic cinematic look, and incredible material detail on leather and fabric. Dust and drifting particles float beautifully in the glowing golden backlight. Several other wheat rolls dot the distant horizon. Photorealistic, ultra high resolution, cinematic photography, merging retro-modern glamour with agricultural charm, highlighting exquisite details and warm sunset tones." \
  "GLM 5.2 Think max" "Wheat Roll"

queue_job 40 \
  "Retro-modern glamour photo shoot capturing a beautiful 1950s-inspired pinup model casually sitting on a rustic wooden fence. She is adorned in a flowing vintage dress and classic leather pumps. Golden hour sunset lighting creates a warm glow over the rural landscape, highlighting her wind-blown hair and fabric. She holds a confident seductive gaze directly at the camera. Rich color grading, filmic cinematic look, and incredible material detail on leather and fabric. Dust and drifting particles are visible in the radiant sunset air. An old wind turbine silhouette rests in the far background. Photorealistic, high resolution, cinematic photography, blending timeless pinup allure with a rustic rural atmosphere and stunning, beautiful warm light." \
  "GLM 5.2 Think max" "Wooden Fence"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "1950s-inspired pinup model with voluminous wind-blown auburn waves, wearing a fitted cherry red polka dot swing dress and glossy black leather pumps, sitting seductively on the curved hood of a rusted teal vintage classic car. Golden hour sunset bathes the expansive rural wheat field in warm amber light. She holds a confident seductive gaze toward the camera lens. Wind catches her dress fabric and loose hair strands dramatically. Rich cinematic color grading with authentic filmic grain texture. Incredible material detail on glossy leather pumps and flowing cotton dress fabric. Dust and drifting pollen particles shimmer in the heavy amber backlight. Old multiblade wind turbine visible on the distant horizon." \
  "Kimi K2.6 Thinking" "Golden Hour Pinup on Vintage Car Hood"

queue_job 42 \
  "1950s-inspired pinup model with voluminous wind-blown auburn waves, wearing a fitted cherry red polka dot swing dress and glossy black leather pumps, leaning seductively against weathered wooden barn doors. Golden hour sunset bathes the rural countryside in warm amber light. She holds a confident seductive gaze toward the camera lens. Wind catches her dress fabric and loose hair strands dramatically. Rich cinematic color grading with authentic filmic grain texture. Incredible material detail on glossy leather pumps and flowing cotton dress fabric. Dust and drifting hay particles shimmer in the heavy amber backlight. Rolling wheat fields stretch behind the rustic red barn structure." \
  "Kimi K2.6 Thinking" "Sunset Pinup at the Old Barn Door"

queue_job 43 \
  "1950s-inspired pinup model with voluminous wind-blown auburn waves, wearing a fitted cherry red polka dot swing dress and glossy black leather pumps, sitting gracefully atop stacked golden hay bales. Golden hour sunset bathes the rural farm in warm amber light. She holds a confident seductive gaze toward the camera lens. Wind catches her dress fabric and loose hair strands dramatically. Rich cinematic color grading with authentic filmic grain texture. Incredible material detail on glossy leather pumps and flowing cotton dress fabric. Dust and drifting chaff particles shimmer in the heavy amber backlight. An old multiblade wind turbine turns slowly beyond the wheat rolls." \
  "Kimi K2.6 Thinking" "Pinup Beauty Resting on Golden Hay Bales"

queue_job 44 \
  "1950s-inspired pinup model with voluminous wind-blown auburn waves, wearing a fitted cherry red polka dot swing dress and glossy black leather pumps, standing near a weathered wooden fence line. Golden hour sunset bathes the rural wheat field in warm amber light. She holds a confident seductive gaze toward the camera lens. Wind catches her dress fabric and loose hair strands dramatically. Rich cinematic color grading with authentic filmic grain texture. Incredible material detail on glossy leather pumps and flowing cotton dress fabric. Dust and drifting pollen particles shimmer in the heavy amber backlight. An old barn stands silhouetted against the burning orange sky." \
  "Kimi K2.6 Thinking" "Glamour Pinup by the Rustic Fence Line"

queue_job 45 \
  "1950s-inspired pinup model with voluminous wind-blown auburn waves, wearing a fitted cherry red polka dot swing dress and glossy black leather pumps, sitting elegantly on a massive cylindrical wheat roll in the field. Golden hour sunset bathes the rural landscape in warm amber light. She holds a confident seductive gaze toward the camera lens. Wind catches her dress fabric and loose hair strands dramatically. Rich cinematic color grading with authentic filmic grain texture. Incredible material detail on glossy leather pumps and flowing cotton dress fabric. Dust and drifting harvest particles shimmer in the heavy amber backlight. Old multiblade wind turbine creaks on the distant ridge." \
  "Kimi K2.6 Thinking" "Pinup Goddess Perched on a Wheat Roll"

# --- Deepseek Instant ---
queue_job 46 \
  "A 1950s-inspired pinup model with victory-rolled hair, wearing a vintage floral tea dress and glossy cherry-red leather pumps, sits gracefully on the broad front wheel arch of a rusty red vintage tractor. She leans back on her palms, one leg elegantly crossed over the other, casting a confident seductive gaze over her shoulder toward the camera. Golden hour sunlight bathes the rural wheat field in molten amber, while a gentle breeze tugs at her skirt and loose curls. Dust motes and pollen drift through the warm air. Rich filmic color grading with deep oranges and teal shadows, cinematic shallow depth of field, and exquisite material detail on the dress's cotton texture and the pump's high-shine leather finish." \
  "Deepseek Instant" "Tractor Glamour"

queue_job 47 \
  "The same retro pinup model, clad in a curve-hugging polka-dot dress and gleaming patent leather pumps, reclines sideways across the sleek hood of a classic turquoise coupe. Propped on one elbow, she trails a hand through her wind-tossed hair while fixing the lens with a smoldering, knowing stare. The low golden sun casts long shadows across the dusty farmyard, with an old wooden barn and spinning multiblade wind turbine in the soft background. Warm light catches every fold of her dress and the reflective gloss of her shoes. Atmospheric dust particles shimmer in the air. Cinematic grading evokes 1950s Kodachrome, with rich contrasts and a dreamy, nostalgic haze." \
  "Deepseek Instant" "Hood Allure"

queue_job 48 \
  "Our pinup model in a bold red swing dress and black leather pumps leans casually against a sun-bleached wooden fence post, one heel hooked on the lower rail. She crosses her arms just below her chest, offering a playful yet intense confident gaze as the setting sun outlines her silhouette. Golden hour rays filter through distant wheat rolls, illuminating floating chaff and dust. Her hair and the flared skirt are caught in a persistent warm breeze. The rural backdrop includes a weathered barn and a slow-turning wind turbine. Film-like grain, rich amber highlights, and deep shadows emphasize the luxurious sheen of the patent leather and the fabric's fluid movement." \
  "Deepseek Instant" "Fence Post Charm"

queue_job 49 \
  "Perched atop a large round hay bale in a sun-drenched wheat field, the same brunette pinup beauty wears a gingham-print dress and shiny caramel leather pumps. She sits with knees together and ankles crossed, holding a woven straw hat loosely in her lap, while her other hand brushes back wind-blown strands. Her seductive gaze is confident and direct, inviting the viewer. The warm golden-hour glow paints the scene in honeyed tones, with an old barn and a wind turbine in the distance. Tiny dust particles and dried grass fragments dance in the slanting light. Cinematic color grading with warm oranges and cool teal highlights enhances the leather's texture and the dress's crisp patterns." \
  "Deepseek Instant" "Hay Bale Delight"

queue_job 50 \
  "The same charismatic pinup model, dressed in a sleeveless navy-blue dress with white piping and matching leather pumps, stands near the sturdy metal base of an old multiblade wind turbine. She leans her shoulder against one strut, one hand gripping the cool steel, the other resting confidently on her hip. Her head tilts slightly, offering a sultry, challenging gaze as the sunset wind violently whips her hair and dress hem. Golden light flares through the turbine blades, casting dynamic shadows across the dry grass and wheat rolls. Rich filmic contrast, floating dust motes, and exquisite detail on the pump's glossy surface and the dress's tailored seams complete the retro-modern glamour aesthetic." \
  "Deepseek Instant" "Windmill Whisper"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Retro-modern glamour photo of a 1950s pinup model with wind-blown auburn hair wearing a fitted emerald satin dress and black leather pumps, leaning against a vintage multiblade wind turbine in a golden wheat field at sunset. Warm cinematic lighting, dust particles drifting in air, confident seductive gaze toward camera, rich amber color grading, filmic look, incredible detail on leather texture and fabric folds, wind catching her dress hem, rural farmland backdrop, shallow depth of field, 35mm film aesthetic, square composition." \
  "ERNIE 5.1" "Golden Hour on the Windmill"

queue_job 52 \
  "Retro-modern glamour photo of a 1950s pinup model with wind-blown auburn hair wearing a fitted cherry red polka dot dress and black leather pumps, sitting atop stacked vintage wooden crates beside an old weathered barn door at golden hour. Warm sunset light casting long shadows, dust motes floating in air, confident seductive gaze toward camera, rich warm color grading, cinematic film look, exquisite leather and fabric material detail, wind tousling her hair and dress, rural countryside setting, shallow depth of field, 35mm film grain aesthetic." \
  "ERNIE 5.1" "Barn Door Siren"

queue_job 53 \
  "Retro-modern glamour photo of a 1950s pinup model with wind-blown auburn hair wearing a fitted ivory lace dress and black leather pumps, standing confidently on the fender of a rusty vintage red tractor in a wheat field at golden hour. Warm cinematic sunset lighting, drifting dust particles in air, confident seductive gaze toward camera, rich golden amber color grading, filmic look, incredible leather pump and fabric lace detail, wind sweeping her dress and hair, rural farmland background, shallow depth of field, 35mm analog film aesthetic." \
  "ERNIE 5.1" "Tractor Queen"

queue_job 54 \
  "Retro-modern glamour photo of a 1950s pinup model with wind-blown auburn hair wearing a fitted sapphire blue satin dress and black leather pumps, reclining seductively across a large round wheat bale in an open field at golden hour. Warm sunset backlight, dust and chaff drifting through air, confident seductive gaze toward camera, rich warm color grading, cinematic filmic look, exceptional leather and satin material detail, wind catching her hair and dress fabric, rural wheat landscape, shallow depth of field, 35mm film grain texture." \
  "ERNIE 5.1" "Wheat Bale Glamour"

queue_job 55 \
  "Retro-modern glamour photo of a 1950s pinup model with wind-blown auburn hair wearing a fitted burgundy velvet dress and black leather pumps, leaning against a split-rail wooden fence beside a towering old water tower at golden hour. Warm cinematic sunset glow, floating dust particles in air, confident seductive gaze toward camera, rich amber and burgundy color grading, filmic look, stunning leather and velvet texture detail, wind sweeping her hair and dress hem, rural open countryside, shallow depth of field, 35mm analog film aesthetic." \
  "ERNIE 5.1" "Fence Line Diva"

# --- LongCat Deep search ---
queue_job 56 \
  "A stunning 1950s-inspired pinup model with victory rolls and cherry red lips sits gracefully on the hood of a classic turquoise Chevrolet, her fitted emerald dress catching the golden hour light while leather pumps dangle from her toes. Her confident seductive gaze meets the camera as wind sweeps her hair and fabric dramatically across the frame. Dust particles dance in the warm amber sunlight streaming through the wheat field behind her. The filmic cinematic look features rich teal and orange color grading with incredible material detail on the glossy car paint, supple leather shoes, and flowing dress fabric. Rural setting with wheat rolls scattered in the background and an old barn visible in the distance." \
  "LongCat Deep search" "Vintage Chrome Dreams"

queue_job 57 \
  "The same 1950s pinup model reclines against weathered barn doors, one shoulder dipped seductively while her emerald dress hugs her curves and leather pumps accentuate her legs. Golden hour backlighting creates a halo around her wind-blown hair as she gazes confidently at the lens. Her pose is relaxed yet alluring, with one hand resting on the rustic wood grain. Captured with filmic cinematic quality, the image showcases rich amber and crimson color grading, incredible texture detail on the worn barn wood, leather fabric, and flowing dress material. Drifting dust particles fill the warm air around wheat rolls and a distant wind turbine silhouette in the rural landscape." \
  "LongCat Deep search" "Rustic Rendezvous"

queue_job 58 \
  "This retro-modern glamour shot features the 1950s pinup model perched atop stacked hay bales, leaning back on her hands with legs crossed elegantly, her emerald dress pooling around her while leather pumps catch the last sunlight. Her seductive confident expression and wind-swept hair create dynamic movement frozen in time. The golden hour lighting bathes the rural scene in warm honey tones, with rich cinematic color grading emphasizing the supple leather texture and delicate fabric details. Dust motes float through the air around wheat rolls and an old multiblade wind turbine standing sentinel in the wheat field background." \
  "LongCat Deep search" "Golden Hour Glamour"

queue_job 59 \
  "The model stands beside a weathered wooden fence, one hand resting casually on a post while her body angles sensuously toward the camera. Her emerald dress ripples in the breeze and leather pumps anchor her to the golden field. With a confident seductive gaze and wind-blown hair, she embodies retro pinup perfection. The filmic cinematic composition features rich sunset color grading with incredible detail on the wood grain, leather material, and flowing fabric. Warm amber light illuminates drifting dust particles as wheat rolls and an old barn complete the rural backdrop." \
  "LongCat Deep search" "Pastoral Pinup"

queue_job 60 \
  "Standing near the base of an old multiblade wind turbine, the 1950s pinup model glances over her shoulder with a confident seductive smile, her emerald dress and hair caught in the golden hour breeze. Leather pumps stand firm on the dusty ground as her body turns elegantly. The filmic cinematic look delivers rich color grading with exceptional material detail on the rusted turbine metal, supple leather shoes, and flowing fabric. Warm sunset light creates dramatic shadows while dust particles drift through the air around wheat rolls and a classic car parked in the rural distance." \
  "LongCat Deep search" "Windmill Whispers"

echo "✅ All 60 jobs queued in scheduler"

