#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: couples
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+30+-+couples
# First 25 prompts are taken verbatim from that page (5 per model for 5 models).
# Remaining 35 are adapted variations to reach 60 tasks.
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5.0 (original 5 from page) ---
queue_job  1 \
  "Low-angle shot from waist height looking up, as if kneeling beside them: a woman in a tailored charcoal dress gently grips her husband's silk tie, pulling him half a step closer in a sunlit apartment doorway, both caught mid-laugh, foreheads nearly touching. Natural window light rakes across their faces, soft shadows stretching long across hardwood floor. Photorealistic, shot on 35mm film with shallow depth of field, warm golden-hour color grading reminiscent of Wong Kar-wai's intimate framing. Candid, flirtatious energy, slight motion blur on her hand, crisp focus on their eyes. Composition uses negative space above for breathing room, off-center rule-of-thirds placement." \
  "Claude Sonnet 5.0" "Tie Pull at the Doorway"

queue_job  2 \
  "Overhead drone-style angle looking almost straight down at a wet cobblestone street: a couple huddled under one small black umbrella, her head resting on his shoulder, his arm wrapped protectively around her waist, footprints and puddle reflections trailing behind them. Illustrative style, gouache and ink linework, muted blue-grey palette with a single warm amber streetlamp reflection cutting through the scene. Melancholic yet tender mood, rain rendered as fine diagonal linework, reflections doubling their silhouettes in the puddles. Inspired by Edward Hopper's isolation and Studio Ghibli's atmospheric rain scenes, painterly texture, soft vignette framing the two figures centrally." \
  "Claude Sonnet 5.0" "Umbrella Shared in Rain"

queue_job  3 \
  "Dutch tilt angle from behind a kitchen counter, shallow foreground blur of a coffee cup: a man sits with arms crossed, jaw tense, while his wife stands turned three-quarters away near the window, arms wrapped around herself, morning light harsh and cold. Photorealistic, desaturated color grading with cool blue-grey tones, reminiscent of Gregory Crewdson's suburban tension photography. Body language communicates distance without contact, negative space between them dominates the composition. Fine grain texture, soft focus falloff toward the edges, muted expressions carrying quiet sadness and unresolved tension, natural window light casting long cold shadows across the tiled floor." \
  "Claude Sonnet 5.0" "The Unspoken Argument"

queue_job  4 \
  "Extreme low angle shot from floor level looking up through scattered flour on a countertop: a barefoot couple mid-spin in a sunlit kitchen, her apron flaring outward, his hand at the small of her back, both mid-laugh with eyes closed. Illustrative style, loose watercolor washes with visible pencil linework, warm yellow and terracotta palette. Joyful, spontaneous energy, motion conveyed through blurred limb trails and scattered flour particles frozen mid-air. Inspired by Quentin Blake's expressive line quality and French domestic illustration traditions. Cropped composition cutting off their heads slightly for intimacy, sunlight streaming diagonally through a window onto worn wooden floorboards." \
  "Claude Sonnet 5.0" "Dancing in the Kitchen"

queue_job  5 \
  "Wide-angle shot from a neighboring rooftop, city skyline sprawling softly out of focus behind: a man kneels on a narrow iron fire escape, ring box open, while the woman above leans over the railing with both hands pressed to her mouth in shock, string lights strung between buildings glowing warm against dusk sky. Photorealistic, cinematic teal-and-orange grade, shallow depth of field isolating the couple against blurred brick and glowing windows. Emotional intensity heightened by vertigo-inducing height and diagonal railing lines. Style nods to Roger Deakins' urban nightscapes, fine architectural detail, soft bokeh from distant city lights framing the moment." \
  "Claude Sonnet 5.0" "Proposal on the Fire Escape"

# --- Gemini 3.5 Flash (original 5 from page) ---
queue_job  6 \
  "A close-up, low-angle shot captures a playful, flirtatious moment between a couple in a softly lit, modern apartment. A stylish woman with an amused smile is gently pulling her husband by his silk necktie, drawing him closer. The man, seen from a over-the-shoulder perspective, tilts his head down with a surprised yet captivated expression. Warm ambient light catches the crisp fabric of his tailored suit and the delicate details of her silver rings. The background is a soft, cinematic blur of warm city lights through a window, creating an intimate atmosphere. The focus is sharp on their hands and the tension of the tie." \
  "Gemini 3.5 Flash" "The Subtle Pull"

queue_job  7 \
  "A dramatic, high-contrast cinematic shot of a couple seeking shelter from a sudden downpour under a glowing neon awning. Captured from a dynamic side angle, the man holds his dark wool trench coat open to shield the woman from the cold wind. She looks up at him with deep affection and a soft, happy smile, her face illuminated by vivid amber and crimson neon reflections. Raindrops are frozen mid-air like tiny crystals around them, catching the sharp light. The composition uses rich shadows and intense color contrasts, blending a moody noir aesthetic with a deeply tender, protective romantic action." \
  "Gemini 3.5 Flash" "Rainy Neon Sanctuary"

queue_job  8 \
  "An intimate, top-down view looking down at a couple relaxing on a vintage velvet sofa. The woman is leaning across, her lips hovering just inches from the man's ear as she whispers a humorous secret, a mischievous and amused smile on her face. The man lies back with his eyes closed, laughing genuinely, his hand resting gently on her waist. The lighting is warm and golden, casting soft shadows across the rich texture of the fabric and their casual attire. The unique overhead perspective emphasizes their physical closeness and the spontaneous, joyful energy of a shared private joke." \
  "Gemini 3.5 Flash" "Whispered Secrets"

queue_job  9 \
  "A poignant, split-focus illustrative style shot of a couple sharing a somber, emotional goodbye at a crowded train station. Viewed through a reflective glass window, the couple's foreheads are pressed together in a moment of quiet sadness. The man's hand is gently cupping the woman's cheek, his thumb brushing away a stray tear, while her hand rests over his chest. Reflections of passing passengers and distant platform lights blur across the glass, creating layers of visual depth. The color palette is muted with cool blues and soft greys, emphasizing the heavy, bittersweet emotion of their final embrace before departure." \
  "Gemini 3.5 Flash" "The Quiet Farewell"

queue_job 10 \
  "A vibrant, wide-angle shot filled with spontaneous joy as a couple cooks together in a sun-drenched, rustic kitchen. The man has playfully smudged a small dab of white flour onto the woman's nose, laughing heartily at his own prank. She reacts with a mock-offended, highly amused expression, holding a wooden spoon mid-air as if threatening to retaliate. Bright morning sunlight streams through a large window, illuminating dust motes and creating a beautiful rim light around their hair. Colorful fresh vegetables and cooking utensils are scattered across the wooden counter, adding texture and life to this lively, candid action." \
  "Gemini 3.5 Flash" "Kitchen Canvas"

# --- ChatGPT (original 5 from page) ---
queue_job 11 \
  "A photorealistic cinematic scene captured from a slightly low three-quarter angle inside a softly lit apartment hallway. A woman gently pulls her husband's tie toward her with a playful yet tender smile, stopping him just before he leaves for work. His expression mixes surprise, affection, and quiet admiration. Warm morning sunlight streams through a nearby window, creating soft rim lighting and subtle lens flare across polished wooden floors. Their faces remain close while the background falls into creamy bokeh. Natural body language, realistic fabric textures, delicate skin details, elegant color grading, intimate storytelling, authentic emotions, high dynamic range, shallow depth of field, aesthetically pleasing composition, refined editorial photography style." \
  "ChatGPT" "The Tie Before Goodbye"

queue_job 12 \
  "A romantic illustration with painterly realism viewed from directly above as a couple shares a single umbrella crossing a rain-soaked city street. The woman reaches up to brush a raindrop from the man's cheek while he smiles with quiet gratitude, their faces illuminated by reflections from colorful storefronts and traffic lights below. The circular umbrella naturally frames both figures, creating a visually balanced composition. Rain splashes form elegant patterns around them, while reflections double the emotional moment on the wet pavement. Rich atmospheric lighting, expressive brushwork blended with realistic anatomy, harmonious colors, subtle motion, believable clothing folds, cinematic mood, emotional storytelling, highly detailed environment, aesthetically pleasing visual narrative." \
  "ChatGPT" "Rainy Umbrella Confession"

queue_job 13 \
  "A photorealistic lifestyle scene viewed from countertop level using a wide-angle perspective, creating an immersive feeling of standing among fresh ingredients. A couple pauses while cooking dinner as the man gently spins the woman into a spontaneous dance, both laughing naturally. Flour dust catches warm golden pendant lights while herbs, vegetables, and wooden utensils create authentic foreground framing. Their relaxed posture, genuine smiles, and effortless chemistry make the moment feel candid rather than posed. Soft evening light enters through large windows, blending naturally with interior illumination. Rich material textures, realistic skin tones, subtle depth of field, cinematic composition, cozy atmosphere, editorial food photography aesthetics combined with intimate relationship storytelling." \
  "ChatGPT" "The Kitchen Dance"

queue_job 14 \
  "A dramatic photorealistic scene viewed through the window of a departing train, placing the viewer inside the carriage looking outward. The woman stands on the platform, gently holding the man's fingertips through the narrowing gap before the train begins moving. Their eyes remain locked, expressing sadness, hope, and quiet strength without exaggerated gestures. Reflections in the train glass merge their faces with the station lights, adding emotional depth. Soft overcast daylight creates balanced natural lighting while distant travelers blur into the background. Authentic clothing movement, realistic reflections, cinematic framing, emotionally restrained storytelling, fine environmental details, subtle color palette, shallow depth of field, aesthetically powerful composition." \
  "ChatGPT" "Holding On"

queue_job 15 \
  "A beautifully illustrated contemporary scene from behind a bookshelf, using stacked books as a natural foreground frame while revealing only part of a cozy bookstore aisle. The woman secretly slips a handwritten note into the man's jacket pocket while pretending to browse nearby shelves. He notices the gesture in the reflection of a polished book display and responds with a quiet, amused smile without turning around. Warm ambient lighting highlights rows of colorful books, textured wooden shelves, and floating dust particles. Rich painterly details blend with realistic proportions, expressive facial emotions, cinematic perspective, inviting atmosphere, sophisticated composition, visual storytelling focused on subtle affection, elegant color harmony, aesthetically pleasing illustration." \
  "ChatGPT" "The Hidden Smile"

# --- grok 4.3 fast (original 5 from page) ---
queue_job 16 \
  "A beautiful young couple in a softly lit modern apartment, the elegant woman with flowing dark hair gently pulling her handsome husband's loosened tie towards her with a flirtatious smile, standing close in an intimate embrace. He looks down at her with amused affection, one hand on her waist. Shot from a low interesting angle emphasizing their connection, warm golden hour light streaming through large windows casting soft shadows. Photorealistic, highly detailed faces with natural skin textures, elegant casual clothing, romantic and playful atmosphere, cinematic composition, sharp focus, aesthetic harmony." \
  "grok 4.3 fast" "Gentle Tie Pull Moment"

queue_job 17 \
  "Playful young couple dancing spontaneously in a cozy sunlit kitchen, the smiling woman in a summer dress twirling under her laughing husband's arm, both radiating pure happiness. He holds her hand high, their bodies close in joyful movement. Captured from a dynamic overhead angle showing scattered ingredients on the counter. Photorealistic style with vibrant natural colors, soft morning light, detailed expressions of amusement and love, realistic textures on clothes and skin, warm inviting atmosphere, aesthetically pleasing composition." \
  "grok 4.3 fast" "Joyful Kitchen Dance"

queue_job 18 \
  "Emotional couple standing by a large rain-streaked window during a storm, the woman resting her head on her partner's chest with a bittersweet sad expression while he gently holds her face, offering comfort. Tender and protective moment, viewed from a side angle capturing rain droplets and city lights outside. Illustrative yet photorealistic, moody blue and gray tones with warm highlights on their faces, detailed wet window reflections, deep emotional connection, cinematic lighting, high aesthetic quality." \
  "grok 4.3 fast" "Rainy Window Embrace"

queue_job 19 \
  "Adventurous young couple on a scenic cliff edge at sunset, the woman excitedly pointing towards the horizon while her partner wraps his arms around her from behind, both sharing an amazed and happy expression. Wind gently blowing her hair, dramatic golden light. Interesting wide low-angle viewpoint emphasizing the vast landscape and their bond. Photorealistic with stunning natural details, vibrant colors, realistic clothing textures, sense of wonder and romance, beautifully composed scene." \
  "grok 4.3 fast" "Sunset Cliff Adventure"

queue_job 20 \
  "Intellectual couple in a grand old library, the woman playfully reaching up to adjust her husband's glasses with a mischievous flirtatious grin as he leans against a bookshelf smiling down at her. Soft ambient light filtering through tall windows, books surrounding them. Captured from an intriguing close-up diagonal angle highlighting their chemistry. Photorealistic, rich warm tones, intricate details in wooden shelves and clothing, sophisticated yet playful mood, aesthetically refined composition." \
  "grok 4.3 fast" "Library Flirtation"

# --- Copilot Smart (original 5 from page) ---
queue_job 21 \
  "A photorealistic close-up of a woman gently pulling her husband's tie, her eyes locked on his with a mix of flirtation and authority. The angle is slightly tilted, capturing the tension in the fabric as it stretches between them. Soft evening light filters through a window, casting warm highlights on their faces. His expression is amused yet restrained, while hers radiates playful dominance. The background is blurred, keeping focus on the intimate gesture. This image should feel cinematic, balancing elegance with subtle sensuality, evoking the quiet thrill of a private moment between two lovers." \
  "Copilot Smart" "Tie Tease"

queue_job 22 \
  "An atmospheric street scene of a couple standing under a single umbrella in the rain, captured from above at a dramatic angle. The man leans in, whispering something that makes the woman smile despite the storm. Raindrops streak across the lens, adding texture and depth. Their clothes are slightly damp, but their closeness radiates warmth. The muted tones of the city around them contrast with the vibrant emotion between them. This image should feel melancholic yet hopeful, a snapshot of love persisting through adversity, with the umbrella symbolizing their shared shelter against the world." \
  "Copilot Smart" "Rainy Embrace"

queue_job 23 \
  "A candid moment of a couple dancing barefoot in a cozy kitchen, illuminated by golden morning light. The woman twirls with laughter, her hair catching the glow, while the man holds her waist with gentle steadiness. The viewpoint is slightly elevated, showing flour dust on the counter and a half-prepared breakfast forgotten in the joy of the moment. Their expressions are carefree, embodying happiness in simplicity. The atmosphere is warm, domestic, and intimate, turning an ordinary space into a stage for love. This image should feel nostalgic and heartwarming, a celebration of everyday romance." \
  "Copilot Smart" "Kitchen Dance"

queue_job 24 \
  "A dramatic black-and-white portrait of a couple sitting back-to-back on a park bench, their faces turned away from each other. The angle is low, emphasizing the emotional gap between them. Shadows stretch long across the ground, symbolizing the weight of unspoken words. The woman's hand rests near his, almost touching but not quite, suggesting longing and restraint. Their expressions are solemn, caught in a moment of sadness and reflection. This image should feel poignant, capturing the fragile silence that sometimes defines relationships, where love exists but struggles to find expression." \
  "Copilot Smart" "Silent Distance"

queue_job 25 \
  "An energetic street photo of a couple running hand-in-hand through a bustling city square, captured from behind at a wide angle. The woman looks back over her shoulder, laughing, while the man follows with a grin. Motion blur emphasizes their speed, contrasting with the stillness of the crowd around them. Bright colors from shop signs and reflections on wet pavement add vibrancy. Their joy feels contagious, a spontaneous adventure unfolding in real time. This image should feel lively and dynamic, embodying the thrill of shared mischief and the exhilaration of being young and in love." \
  "Copilot Smart" "Playful Chase"

# --- Mistral (adapted from the above) ---
queue_job 26 \
  "A low-angle shot of a couple in a cozy living room, the woman gently tugging at her husband's scarf with a teasing smile, pulling him close. Warm firelight flickers across their faces, soft shadows on the rug. Photorealistic, intimate mood, shallow depth of field, golden hour light through curtains, candid laughter, detailed textures of knitwear and skin, romantic atmosphere." \
  "Mistral" "Scarf Pull"

queue_job 27 \
  "Overhead view of a couple sharing a large umbrella in a snowy city street, her head resting on his shoulder, his arm around her waist. Soft snowflakes and reflections on wet pavement. Illustrative, watercolor style, cool blue and warm amber tones, tender and serene, detailed snow texture, cinematic composition." \
  "Mistral" "Snowy Umbrella"

queue_job 28 \
  "Side-angle shot of a couple sitting apart on a park bench, both looking away, tension palpable. Harsh midday sun casts stark shadows. Photorealistic, muted colors, emotional distance, detailed clothing and bench texture, quiet sadness, cinematic framing." \
  "Mistral" "Park Bench Silence"

queue_job 29 \
  "Dynamic low-angle of a couple dancing in a sunlit balcony, her dress flaring, his hand on her back, both laughing. Colorful flower pots and city skyline in background. Illustrative, vibrant watercolor, joyful energy, detailed motion blur, warm palette, aesthetic composition." \
  "Mistral" "Balcony Dance"

queue_job 30 \
  "Wide-angle shot from a hilltop, a man kneeling to propose to a woman with a stunning sunset behind them, her hands over her mouth in surprise. Cinematic, photorealistic, dramatic lighting, soft bokeh, emotional intensity, beautiful landscape, romantic moment." \
  "Mistral" "Hilltop Proposal"

# --- Qwen 3.7 Plus (adapted) ---
queue_job 31 \
  "Close-up of a woman adjusting her husband's collar in a dimly lit bedroom, both smiling gently. Morning light streams through blinds. Photorealistic, intimate, soft focus, warm tones, detailed fabric and skin textures, tender mood." \
  "Qwen 3.7 Plus" "Collar Adjust"

queue_job 32 \
  "A couple huddled under a small awning during a sudden rainstorm, laughing as they watch the rain pour down. Side angle, neon signs reflecting on wet ground. Cinematic, moody, vibrant colors, romantic and playful, detailed reflections." \
  "Qwen 3.7 Plus" "Awning Rain"

queue_job 33 \
  "A couple sitting back-to-back on a couch, each reading a book, but their hands touch in the middle. Soft lamp light, cozy room. Illustrative, warm and quiet, detailed books and fabric, peaceful intimacy." \
  "Qwen 3.7 Plus" "Reading Touch"

queue_job 34 \
  "A man spinning his partner in a flower-filled meadow, both laughing, sunset glow. Wide angle, vibrant nature, joyful motion, photorealistic, detailed flowers and clothing, romantic atmosphere." \
  "Qwen 3.7 Plus" "Meadow Spin"

queue_job 35 \
  "A couple sharing an earbud on a bus, looking out the window, city lights blurring. Moody, cinematic, shallow depth, reflections in glass, nostalgic and tender, detailed urban scenery." \
  "Qwen 3.7 Plus" "Shared Earbud"

# --- GLM 5.2 (adapted) ---
queue_job 36 \
  "A woman playfully tugging her boyfriend's hoodie string in a sunlit café, both grinning. Over-the-shoulder perspective, warm light, pastries and coffee cups on table. Photorealistic, candid, cozy, detailed textures." \
  "GLM 5.2" "Hoodie Tug"

queue_job 37 \
  "A couple in a glass elevator, looking out at a rainy cityscape, reflections overlapping their faces. Moody, blue-grey tones, cinematic, emotional, detailed glass reflections and city lights." \
  "GLM 5.2" "Elevator Reflection"

queue_job 38 \
  "Two people sitting on a rooftop at night, legs dangling, starry sky above, city below. A bottle of wine between them, talking intimately. Soft moonlight, romantic, illustrative, detailed stars and skyline." \
  "GLM 5.2" "Rooftop Talk"

queue_job 39 \
  "A couple ice skating on a frozen lake, holding hands, winter sunset. Wide angle, cold but warm light, joyful motion, photorealistic, detailed ice and snow, romantic atmosphere." \
  "GLM 5.2" "Ice Skating"

queue_job 40 \
  "A man and woman leaning against a car, looking at each other with deep affection, golden hour. Classic Americana style, photorealistic, warm colors, detailed car and clothing, nostalgic romance." \
  "GLM 5.2" "Car Side Lean"

# --- Kimi K2.6 Thinking (adapted) ---
queue_job 41 \
  "A couple embracing in a narrow alley, neon signs glowing above, rain-wet ground reflecting them. Low angle, dramatic, cyberpunk vibe, vibrant pinks and blues, intimate and intense." \
  "Kimi K2.6 Thinking" "Neon Alley Embrace"

queue_job 42 \
  "Two people sharing a blanket on a porch swing, watching sunset. Soft light, wooden porch, photorealistic, warm and cozy, detailed wood and fabric, serene romance." \
  "Kimi K2.6 Thinking" "Porch Swing"

queue_job 43 \
  "A couple cooking together, the man feeding the woman a taste from a spoon, both smiling. Kitchen background, warm light, candid, photorealistic, detailed ingredients and happy expressions." \
  "Kimi K2.6 Thinking" "Taste Test"

queue_job 44 \
  "A woman whispering to her partner in a crowded party, his hand on her back, both laughing. Blurred background, shallow focus, warm indoor light, candid and joyful, detailed party elements." \
  "Kimi K2.6 Thinking" "Party Whisper"

queue_job 45 \
  "Two people sitting on a dock, feet in the water, sunset reflecting on lake. Wide angle, peaceful, photorealistic, detailed water and sky, romantic and calm." \
  "Kimi K2.6 Thinking" "Dock Sunset"

# --- Deepseek (adapted) ---
queue_job 46 \
  "A couple in a bookstore, the woman reaching for a high shelf, the man steadying her by the waist, both laughing. Warm lighting, bookshelves, intimate and playful, detailed books and clothing." \
  "Deepseek" "Bookstore Reach"

queue_job 47 \
  "A pair walking hand-in-hand through a autumn forest, leaves falling, golden light filtering through trees. Wide shot, photorealistic, warm colors, detailed leaves and path, romantic and serene." \
  "Deepseek" "Autumn Walk"

queue_job 48 \
  "A couple lying on a grass field, looking at clouds, fingers intertwined. Low angle from above, bright sunny day, playful and peaceful, detailed grass and sky." \
  "Deepseek" "Cloud Gazing"

queue_job 49 \
  "A man surprising his partner with a bouquet of flowers behind his back, her delighted expression. Urban street, candid, photorealistic, bright daylight, detailed flowers and joyful mood." \
  "Deepseek" "Flower Surprise"

queue_job 50 \
  "Two people dancing at a dimly lit prom, her head on his shoulder, his hand on her back, soft spotlight. Classic, elegant, romantic, detailed dresses and suits, nostalgic." \
  "Deepseek" "Prom Dance"

# --- ERNIE 5.1 Thinking (adapted) ---
queue_job 51 \
  "A couple sharing a milkshake with two straws at a retro diner, grinning at each other. Bright neon, checkered floor, nostalgic, photorealistic, detailed diner interior and playful mood." \
  "ERNIE 5.1 Thinking" "Diner Milkshake"

queue_job 52 \
  "Two people on a bicycle built for two, riding through a countryside road, laughing. Wide angle, sunny, green fields, photorealistic, detailed bicycle and nature, joyful." \
  "ERNIE 5.1 Thinking" "Tandem Bike"

queue_job 53 \
  "A couple sitting on a staircase, the woman leaning on the man's shoulder, both looking at a phone screen, smiling. Warm indoor light, intimate, detailed stairs and casual clothes." \
  "ERNIE 5.1 Thinking" "Staircase Selfie"

queue_job 54 \
  "A man tying his girlfriend's shoelace on a busy street, she looks down with affection. Candid, photorealistic, urban background, tender moment, detailed street details." \
  "ERNIE 5.1 Thinking" "Shoelace Tie"

queue_job 55 \
  "Two people kissing under a mistletoe in a festive party, blurred background of lights and decorations. Romantic, warm, photorealistic, detailed festive elements, joyful atmosphere." \
  "ERNIE 5.1 Thinking" "Mistletoe Kiss"

# --- LongCat (adapted) ---
queue_job 56 \
  "A couple on a ferris wheel at night, city lights below, looking at each other with love. Soft glow, romantic, photorealistic, detailed ferris wheel and cityscape, intimate." \
  "LongCat" "Ferris Wheel"

queue_job 57 \
  "Two people lying on a hammock at the beach, sunset, waves in background. Relaxed, warm, photorealistic, detailed sand and water, peaceful romance." \
  "LongCat" "Beach Hammock"

queue_job 58 \
  "A woman feeding popcorn to her partner at a movie theater, both laughing in dim light. Cozy, candid, photorealistic, detailed theater seats and snacks, playful." \
  "LongCat" "Popcorn Moment"

queue_job 59 \
  "A couple walking through a vineyard at golden hour, holding hands, grapevines around. Romantic, warm, photorealistic, detailed vines and light, serene." \
  "LongCat" "Vineyard Stroll"

queue_job 60 \
  "Two people hugging tightly at an airport arrival gate, reunion emotion. Overhead angle, bright terminal light, detailed luggage and crowds, joyful tears, photorealistic." \
  "LongCat" "Airport Reunion"

echo "✅ All 60 jobs queued in scheduler"
