#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Art meets reality — drawn/sculpted characters interacting with a
#        photorealistic real world (pencil/ink/wire mixed with photorealism)
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+33+-+Art+meets+reality
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A delicate graphite pencil sketch of a sparrow lifts off the torn edge of a notebook page and flies into a sunlit real kitchen, its wings still rendered in loose crosshatched pencil strokes and visible paper grain, while the surrounding kitchen is fully photorealistic with warm morning light, steam rising from a ceramic mug, and soft bokeh in the background. The contrast between the flat monochrome sketch texture and the richly detailed photographic environment creates a striking, dreamlike juxtaposition. Shallow depth of field, cinematic lighting, dust motes floating in a sunbeam, high detail, gallery-quality composition, the pencil lines slightly smudged at the edges as if freshly drawn, evoking motion and wonder." \
  "Claude Sonnet 5 medium" "Pencil Bird Taking Flight"

queue_job  2 \
  "A bold black ink illustration of a wolf, drawn with expressive brush strokes and visible ink splatter, prowls silently down a rain-soaked, photorealistic city street at night. Neon signs reflect in wet asphalt, streetlights glow amber through mist, and parked cars sit in crisp photographic detail, while the wolf itself remains pure two-dimensional ink linework with dripping edges and bleeding texture, casting an unexpectedly three-dimensional shadow on the pavement. The scene feels cinematic and moody, blending gritty urban realism with raw expressive illustration. Eye-catching contrast, dramatic lighting, shallow depth of field, subtle color grading, a sense of quiet tension between the drawn creature and the real world it walks through." \
  "Claude Sonnet 5 medium" "Ink Wolf on City Street"

queue_job  3 \
  "A butterfly sculpted entirely from thin bent copper wire, its wings formed by delicate looping strands catching the light, lands gently on a real, dew-covered pink peony in a photorealistic garden at golden hour. The wire glints with warm reflections, casting intricate thread-like shadows across the petals, while the flower, leaves, and soft blurred greenery behind remain fully lifelike and richly textured. The juxtaposition of cold industrial metal against soft organic nature feels poetic and eye-catching. Macro-style close-up framing, shallow depth of field, warm backlighting, tiny dew droplets in sharp focus, a serene, artistic mood blending sculptural craft with photographic realism in perfect harmony." \
  "Claude Sonnet 5 medium" "Wire Sculpture Butterfly on Flower"

queue_job  4 \
  "A charcoal-drawn human hand, rendered in loose expressive smudged strokes with visible paper texture and fingerprints of graphite dust, emerges from the flat surface of a sketchbook page lying on a real wooden cafe table, reaching toward a photorealistic steaming cup of coffee beside it. The charcoal shading is rough and monochrome, contrasting sharply against the warm, detailed realism of the porcelain cup, wood grain, and soft natural window light. The image feels surreal yet intimate, mixing tactile illustration with photographic warmth. Shallow depth of field, cozy morning atmosphere, subtle steam wisps, high detail, an eye-catching blend of two-dimensional art and three-dimensional reality colliding gently." \
  "Claude Sonnet 5 medium" "Charcoal Hand Reaching for Coffee"

queue_job  5 \
  "A slender ink-brush dragon, drawn in flowing traditional linework with dynamic calligraphic strokes and subtle ink-wash shading, coils playfully around a real vintage iron lamppost on a cobblestone street at dusk. The lamppost, cobblestones, and softly glowing streetlamp are rendered in full photorealistic detail, while the dragon remains stylized black ink with visible brushstroke texture and faint bleeding edges, its form glowing faintly where it wraps the warm light source. The scene feels magical and cinematic, balancing illustrative fantasy with grounded urban realism. Twilight sky, warm rim lighting, shallow depth of field, atmospheric haze, a striking fusion of ink artistry and tangible photographic environment." \
  "Claude Sonnet 5 medium" "Ink Dragon Around Lamppost"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A hyper-realistic photograph of a cozy sunlit cafe table, where a mischievous charcoal pencil sketch of a calico cat is springing to life. The drawing's graphite lines blur at the edges, transitioning seamlessly into the realistic texture of the wooden tabletop. The cat is mid-leap, paws swiping at a floating, illustrative ink-drawn butterfly. Surrounding the scene, depth-of-field captures a blurred espresso cup and open book, anchoring the surreal illustration in a tangible, photorealistic environment. Sharp contrast between the rough, monochromatic graphite texture and the soft, warm ambient lighting of the cafe creates a mesmerizing visual tension, highlighting the magical emergence of 2D art into the physical three-dimensional world." \
  "Gemini 3.5 Flash" "The Leaping Calico"

queue_job  7 \
  "Close-up shot of a dusty wooden bookshelf in a quiet, dimly lit library. Perched on a leather-bound volume is an intricate, hand-inked pen drawing of a miniature astronaut exploring the surface of the book. The astronaut's suit features fine cross-hatching details, while their footprint in the paper is rendered with realistic, tactile shadows. Beside the astronaut, an illustrative, swirling nebulous gas cloud, rendered in delicate blue ink lines, drifts into the photorealistic air of the library. Dust motes dance in the soft, golden light streaming from a nearby window, grounding the whimsical, monochromatic illustration within the sharp, high-resolution textures of the aged library shelves." \
  "Gemini 3.5 Flash" "The Librarian Astronaut"

queue_job  8 \
  "A wide, cinematic shot of a bustling, gritty subway station. On the textured concrete floor, a delicate copper wire sculpture of a ballerina is performing a graceful grand jete. The sculpture catches the harsh, fluorescent overhead lighting, casting sharp, realistic shadows across the station tiles. The wire twists and coils in intricate patterns, blending metallic realism with a stylized, skeletal aesthetic. Passengers walk past, slightly blurred, emphasizing the stillness of the wire figure amidst the motion of the real world. The contrast between the cold, industrial environment of the subway and the ephemeral, intricate metallic form of the ballerina creates a striking, poignant visual narrative." \
  "Gemini 3.5 Flash" "The Subway Ballerina"

queue_job  9 \
  "A serene corner of a sun-drenched city park. A vintage 1950s typewriter sits on a rustic park bench, but instead of paper, it is feeding out a long, intricate black ink drawing of a blooming wildflower meadow. The illustration spills off the carriage, curling and winding its way onto the wooden slats of the bench, blending the two-dimensional ink strokes with the realistic grain and texture of the wood. Bright sunlight casts sharp shadows, enhancing the 3D depth. A few real petals from a nearby tree have fallen onto the paper, blurring the line between the illustrated floral landscape and the physical garden setting." \
  "Gemini 3.5 Flash" "The Typewriter Meadow"

queue_job 10 \
  "A rainy, cobblestone street scene at night, illuminated by the glowing neon sign of a nearby bistro. Sitting on the wet stones is a rough, high-contrast charcoal sketch of a blues guitarist. The drawing is bold, with thick, smudged strokes defining the musician's silhouette, yet the guitar he plays is rendered with startling photorealistic clarity, showing polished wood grain and steel strings. Raindrops falling on the charcoal drawing appear to smudge the ink, creating a sense of movement and decay. The interplay between the vivid, blurred neon reflections on the wet pavement and the raw, monochromatic sketch creates a moody, atmospheric, and deeply immersive visual experience." \
  "Gemini 3.5 Flash" "The Midnight Busker"

# --- ChatGPT ---
queue_job 11 \
  "A lively city park at golden hour where a finely rendered graphite sketchbird has stepped out of a notebook and into reality. Its body is composed of delicate pencil hatching, soft shading, visible construction lines, and expressive cross-hatched wings, while the surrounding trees, grass, benches, and people are photorealistic. The illustrated bird flutters excitedly, scattering tiny graphite feathers that dissolve into drifting pencil dust. Curious children watch in amazement while a real sparrow flies alongside its drawn companion. The blend between traditional pencil illustration and tangible reality is seamless, cinematic, whimsical, emotionally uplifting, highly detailed, elegant composition, soft natural lighting, subtle depth of field." \
  "ChatGPT" "The Sketchbird's First Flight"

queue_job 12 \
  "A charming ink-drawn adventurer made entirely from flowing black fountain-pen lines confidently walks across a rain-soaked city street after a spring shower. Every fold of the explorer's clothing is illustrated with expressive ink strokes, stippling, and flowing contour lines, contrasting beautifully against the photorealistic reflections on wet pavement, glowing traffic lights, storefronts, and umbrellas. Tiny droplets splash through the illustrated boots without washing away the artwork. Passing pedestrians barely notice the impossible traveler as sketched birds perch on real lamp posts. Dramatic reflections, cinematic atmosphere, harmonious balance between illustration and reality, highly detailed textures, elegant perspective, visually captivating, warm evening ambiance." \
  "ChatGPT" "The Ink Explorer Crossing the Rain"

queue_job 13 \
  "Inside a lush botanical greenhouse, an elegant human figure sculpted entirely from polished copper wire carefully tends vibrant living flowers. The wire sculpture is handcrafted from graceful loops, twisted strands, delicate spirals, and open geometric forms that reveal empty space while maintaining expressive anatomy. Every surrounding plant, flower, watering can, glass wall, and sunbeam is rendered in rich photorealism, emphasizing the contrast between crafted art and nature. Tiny butterflies land gently on the metallic framework as sunlight creates intricate shadows across the greenhouse floor. Peaceful atmosphere, artistic realism, sophisticated craftsmanship, beautiful color harmony, cinematic composition, extraordinary fine detail." \
  "ChatGPT" "The Copper Wire Gardener"

queue_job 14 \
  "A magnificent whale illustrated with colorful sidewalk chalk emerges from a massive seaside mural and gracefully swims through the real sky above a photorealistic harbor. Its body retains soft pastel textures, visible chalk grain, smudged edges, and layered hand-drawn shading while interacting naturally with realistic clouds, seagulls, fishing boats, and shimmering ocean water. Fragments of colored chalk sparkle behind its tail like magical dust without losing the authentic hand-crafted appearance. People along the pier stop to admire the surreal spectacle reflected across calm water. Dreamlike realism, uplifting mood, stunning lighting, artistic elegance, intricate textures, unforgettable visual storytelling." \
  "ChatGPT" "The Chalk Whale Above the Harbor"

queue_job 15 \
  "A courageous medieval knight drawn with blue ballpoint pen on lined notebook paper has climbed out of the page and now rides a real bicycle through a quiet European street to deliver an important letter. The knight retains visible notebook lines across polished armor, energetic pen strokes, cross-hatching, scribbled corrections, and hand-drawn texture, while every surrounding building, cobblestone, cafe, bicycle basket, flowers, and afternoon sunlight appears completely photorealistic. Curious pigeons follow the illustrated rider as ink curls transform into fluttering ribbons behind the moving wheels. Seamless blend of illustration and reality, imaginative storytelling, cinematic depth, highly detailed, aesthetically pleasing, visually striking." \
  "ChatGPT" "The Notebook Knight Delivers the Letter"

# --- Grok fast ---
queue_job 16 \
  "A captivating mix of photorealism and delicate pencil illustration shows a finely detailed hand-drawn young woman sketched with soft graphite lines and cross-hatching, wearing a flowing coat and scarf, walking gracefully along a wet cobblestone street in real-world Paris at dusk. Raindrops glisten on realistic pavement reflections while the Eiffel Tower looms in the misty background. Her monochrome pencil-shaded figure contrasts beautifully with the vibrant, photorealistic city lights and golden hour glow, creating an eye-catching surreal blend where the sketched character feels alive in the living world. Cinematic atmosphere, intricate line work, aesthetically pleasing composition." \
  "Grok fast" "Pencil Sketch Wanderer in Rainy Paris"

queue_job 17 \
  "Highly detailed pen and ink character illustration of a fierce samurai warrior rendered with bold black lines, delicate hatching, and dynamic ink washes, standing powerfully in a lush photorealistic ancient forest. Sunbeams pierce through realistic towering trees and moss-covered rocks as he holds his katana ready. The monochrome ink-drawn warrior seamlessly merges with the vibrant green and golden natural environment, creating a striking visual contrast and magical realism. Ultra-detailed foliage, atmospheric mist, eye-catching composition with perfect balance between illustration and photorealistic surroundings." \
  "Grok fast" "Ink Warrior in Ancient Forest"

queue_job 18 \
  "A mesmerizing wire sculpture of a majestic eagle crafted from twisted metal wires, realistically sculpted with intricate bends and shadows, perched on a park bench in a vibrant photorealistic city park during golden hour. Cherry blossoms fall gently around the metallic bird while real people stroll in the background. The industrial wire art piece contrasts beautifully with soft natural lighting, green grass, and realistic urban architecture, blending sculpture and reality into an aesthetically pleasing, eye-catching scene full of wonder and delicate detail." \
  "Grok fast" "Wire Sculpture Bird in Urban Park"

queue_job 19 \
  "Atmospheric charcoal sketch of a mysterious detective with rich black tones, smudged shading, and expressive lines, standing under pouring rain on a bustling photorealistic neon-lit cyberpunk street at night. His trench coat and fedora rendered in classic illustration style while vibrant reflections from glowing signs illuminate realistic puddles and towering buildings. The hand-drawn character comes alive within the hyper-detailed urban environment, creating a perfect fusion of noir illustration and photorealistic cyberpunk aesthetics that is both moody and visually stunning." \
  "Grok fast" "Charcoal Drawn Detective in Neon City"

queue_job 20 \
  "Delicate pen and ink drawing of a graceful fox spirit with intricate linework, flowing tails, and elegant traditional patterns, standing elegantly in a vast photorealistic snowy mountain landscape at sunrise. Soft pastel winter light illuminates realistic snow-covered pines and distant peaks while the illustrated creature blends seamlessly with the cold, crystalline environment. The warm ink tones of the character create beautiful contrast against the cool realistic blues and whites, resulting in an enchanting, aesthetically pleasing, and eye-catching fantasy illustration meets reality masterpiece." \
  "Grok fast" "Pen Illustrated Fox Spirit in Snowy Mountain"

# --- Copilot Smart ---
queue_job 21 \
  "A pencil-drawn woman, sketched with delicate graphite lines, sits at a bustling cafe table in the real world. Her illustrated form contrasts with the photorealistic background of steaming coffee cups, polished wooden surfaces, and blurred figures passing by. The interplay of hand-drawn simplicity and vivid realism creates a surreal yet harmonious scene, as if the sketch has stepped off the page to sip espresso among everyday people. Shadows and light enhance the illusion, making her presence both fragile and striking." \
  "Copilot Smart" "Pencil Woman at Cafe"

queue_job 22 \
  "An ink-drawn cat, composed of bold strokes and fluid curves, prowls through a photorealistic urban alley. The cobblestones glisten with rain, neon signs flicker above, and trash bins cast long shadows. The illustrated feline seems alive, its ink lines shimmering against the tangible textures of the real world. The contrast between the hand-drawn simplicity and the gritty realism of the alley creates a captivating tension, as if imagination itself has wandered into reality." \
  "Copilot Smart" "Ink Cat in Alley"

queue_job 23 \
  "A wire-sculpted figure of a cyclist, minimalist yet expressive, rides through a photorealistic city street. Cars blur past, pedestrians glance curiously, and sunlight reflects off glass buildings. The wiry form bends and twists with motion, its metallic lines catching the light as it pedals forward. The juxtaposition of sculptural abstraction against the vivid realism of the bustling street makes the scene eye-catching, surreal, and strangely believable." \
  "Copilot Smart" "Wire Sculpture Cyclist"

queue_job 24 \
  "A bird drawn in whimsical pen doodles perches on a real-world park bench. The photorealistic setting shows lush green trees, children playing in the distance, and sunlight filtering through leaves. The doodled bird, with playful swirls and exaggerated features, interacts with the environment—its ink lines casting faint shadows on the wooden bench. The blending of sketchy illustration with natural realism creates a charming and imaginative spectacle." \
  "Copilot Smart" "Pen-Doodle Bird in Park"

queue_job 25 \
  "A graphite-drawn robot, shaded with pencil textures, stands in a photorealistic modern kitchen. Stainless steel appliances gleam, fruit bowls sit on counters, and sunlight streams through a window. The robot's sketched form contrasts with the sharp realism of its surroundings, as if a blueprint has come alive to prepare breakfast. The surreal mix of drawn simplicity and tangible detail makes the scene both humorous and thought-provoking." \
  "Copilot Smart" "Graphite Robot in Kitchen"

# --- Mistral Think ---
queue_job 26 \
  "A hyper-detailed, photorealistic scene of a cozy Parisian cafe table, with a black pencil sketch of a playful cat mid-leap, drawn directly on the wooden surface, its lines sharp and expressive. The cat's fur is rendered with fine, textured hatching, blending seamlessly into the real-world setting: a steaming cup of coffee, a croissant, and a scattered set of colored pencils. The background is softly blurred, emphasizing the contrast between the illustrated cat and the tangible objects. The lighting is warm and golden, casting gentle shadows that make the drawing appear as if it's part of the scene. The style is a harmonious mix of photorealism and hand-drawn illustration, with a touch of whimsy." \
  "Mistral Think" "A Pencil-Drawn Cat on a Cafe Table"

queue_job 27 \
  "A striking, photorealistic image of a lush city park, where a life-sized wire sculpture of a majestic dragon is intricately woven around a tree trunk. The dragon's metallic frame gleams subtly in the sunlight, its delicate wire details catching the light and creating a sense of movement. Children play nearby, their shadows mingling with the sculpture's intricate patterns. The background features vibrant green grass, dappled sunlight through leaves, and a clear blue sky. The composition balances the raw, industrial texture of the wire with the organic beauty of the park, creating a visually captivating fusion of art and nature." \
  "Mistral Think" "A Wire Sculpture of a Dragon in a City Park"

queue_job 28 \
  "A dynamic, photorealistic street scene featuring a large, expressive pen-and-ink portrait of a thoughtful old man, drawn directly onto a weathered brick wall. The portrait's lines are bold and fluid, with intricate cross-hatching that adds depth and emotion to the man's wrinkled face. The wall's texture and cracks are visible, enhancing the contrast between the flat illustration and the 3D world around it: a bicycle leaning against the wall, a potted plant, and a stray cat walking by. The lighting is natural, with soft shadows that make the drawing appear almost alive. The image blends urban realism with the raw charm of street art." \
  "Mistral Think" "A Pen-and-Ink Portrait on a Street Wall"

queue_job 29 \
  "A vibrant, photorealistic sidewalk scene where a colorful chalk drawing of a friendly, vintage-style robot is sprawled across the pavement. The robot's metallic body is rendered with precise, chalky lines and vibrant hues, standing out against the gray concrete. A child's hand holding a piece of chalk is visible in the corner, mid-drawing. The background includes a bustling street with blurred pedestrians, a fire hydrant, and a bright red balloon floating away. The image captures the joy of childhood creativity, blending the ephemeral nature of chalk art with the tangibility of the cityscape." \
  "Mistral Think" "A Chalk Drawing of a Robot on a Sidewalk"

queue_job 30 \
  "A dreamy, photorealistic garden scene with a delicate pencil sketch of a tiny, ethereal fairy perched on a sunflower. The fairy's wings and gown are drawn with fine, feathery strokes, her features soft and enchanting. The sunflower's petals and the garden's lush greenery are in sharp focus, creating a striking contrast between the illustrated fairy and the real-world flora. Sunlight filters through the leaves, casting dappled shadows on the sketch and the surrounding flowers. The composition is a magical blend of nature's beauty and the charm of hand-drawn art." \
  "Mistral Think" "A Pencil Sketch of a Fairy in a Garden"

# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "A photorealistic coffee cup resting on a rustic wooden cafe table, steam rising gently. Sitting across from it is a fully realized 2D pencil sketch of a young woman reading a newspaper. The sketch is drawn with intricate graphite shading and crosshatching, existing as a flat 2D illustration interacting with the 3D real world. Sunlight streams through a nearby window, casting realistic shadows from the coffee cup while the sketch remains flat. Cinematic lighting, shallow depth of field, highly detailed background, beautiful contrast between the hyper-realistic environment and the delicate hand-drawn ink illustration, making it aesthetically pleasing, eye-catching, and a stunning visual masterpiece." \
  "Qwen 3.7 Plus Thinking" "The Morning Sketch"

queue_job 32 \
  "A hyper-realistic urban park scene during golden hour, with blurred pedestrians and lush green trees in the background. In the foreground, a delicate wire sculpture of a man walking a small wire-sculpted dog on a leash. The wire figures are intricately twisted from shiny copper and steel, catching the warm sunlight, existing as 3D line art in the physical world. The ground shows realistic shadows and fallen autumn leaves. Mixed media style combining photorealism and sculptural illustration. Vibrant colors, sharp focus on the wire characters, cinematic composition, aesthetically pleasing, eye-catching, highly detailed, eye-catching visual contrast between the solid real world and the transparent wire figures." \
  "Qwen 3.7 Plus Thinking" "The Wire Walker"

queue_job 33 \
  "A vibrant, photorealistic street corner at night, illuminated by glowing neon signs and wet pavement reflecting colorful lights. Standing on the sidewalk is a dynamic 2D ink drawing of a musician passionately playing an acoustic guitar. The character is drawn with bold, expressive black ink strokes and splatters, looking like a comic book illustration brought into reality. The guitar has realistic wood textures, blending the mediums. Raindrops fall around them. High contrast, moody atmosphere, stunning mix of real-world photography and traditional pen illustration. Aesthetically pleasing, eye-catching, sharp details, beautiful lighting, creating a truly breathtaking and highly detailed visual masterpiece." \
  "Qwen 3.7 Plus Thinking" "The Ink Musician"

queue_job 34 \
  "A brightly lit, photorealistic art studio filled with scattered paint tubes and wooden easels. In the center, a 2D pen sketch of an artist stands before a blank canvas, holding a realistic wooden palette and brush. The sketch is created with fine black fineliner lines and subtle stippling, existing as a flat illustration within the 3D space. Dust motes dance in the realistic sunbeams coming from a large window. The contrast between the hyper-detailed real-world studio and the minimalist line-art character is striking. Mixed media, aesthetically pleasing, eye-catching, beautiful composition, sharp focus, cinematic lighting, resulting in a highly detailed masterpiece." \
  "Qwen 3.7 Plus Thinking" "The Canvas Creator"

queue_job 35 \
  "A bustling, photorealistic city crosswalk during a rainy afternoon, with realistic yellow cabs and blurred umbrellas in the background. Riding through the puddles is a 2D charcoal sketch of a cyclist pedaling a vintage bicycle. The sketch features rich, smudged charcoal textures and bold black strokes, looking like a classic drawing placed directly into the real environment. Splashes of realistic water interact with the flat illustrated wheels. Moody lighting, high dynamic range, stunning mix of photography and traditional illustration. Aesthetically pleasing, eye-catching, highly detailed textures, beautiful contrast, cinematic masterpiece, creating a truly breathtaking and immersive visual experience." \
  "Qwen 3.7 Plus Thinking" "The Charcoal Commute"

# --- GLM 5.2 High ---
queue_job 36 \
  "A striking blend of photorealism and illustration featuring a little girl drawn entirely in vibrant blue ink, walking playfully through a sunlit, photorealistic green park. The ink-drawn girl, complete with sketchy outlines and watercolor-style shading, holds a real, physical red leash attached to a highly detailed, photorealistic Golden Retriever. The dog is sniffing actual fallen autumn leaves on a damp, textured concrete path. Sunlight casts realistic shadows from the trees onto the grass, while the ink girl casts a subtle, stylized blue shadow. The contrast between the 2D ink character and the 3D realistic environment is eye-catching and aesthetically pleasing, capturing a magical moment where art seamlessly interacts with everyday reality." \
  "GLM 5.2 High" "Blue Ink Girl Walking Real Dog"

queue_job 37 \
  "A breathtaking urban scene blending realistic photography with intricate wire sculpture art. A delicate bird crafted entirely from thin, twisted metallic wire flies gracefully over a photorealistic, bustling city skyline at golden hour. The wire bird features complex, intertwining lines forming its feathers and hollow body, catching the warm orange sunlight. Below, the city features sharp, highly detailed glass skyscrapers reflecting the vibrant sunset sky. The wire bird casts a faint, realistic shadow on a nearby stone ledge. The juxtaposition of the rigid, metallic wire art against the soft, glowing, photorealistic atmosphere creates an aesthetically pleasing and surreal visual experience, perfectly merging tangible sculpture with the living, breathing modern world." \
  "GLM 5.2 High" "Metallic Wire Bird Over City Skyline"

queue_job 38 \
  "A creative juxtaposition of a 2D pencil sketch and a 3D photorealistic setting on a wooden office desk. A medieval knight, meticulously drawn in graphite pencil with detailed cross-hatching and shading, stands vigilantly beside a steaming, highly realistic white ceramic mug of dark coffee. Real, wispy steam rises from the mug, gently curling around the pencil-drawn knight's armored helmet. The desk surface features rich, photorealistic wood grain, scattered with real sunlight filtering through a window, creating true shadows. The pencil lines of the knight remain raw and textured, seamlessly integrating into the physical environment. This eye-catching image beautifully captures the imagination of doodling brought to life in a mundane reality." \
  "GLM 5.2 High" "Graphite Knight Guarding Steaming Coffee"

queue_job 39 \
  "An incredible mix of pen and ink illustration with photorealistic environment. A stylized mechanic, drawn with bold black ink lines and expressive comic-style shading, is actively fixing a real, highly detailed flat tire on a muddy dirt road. The ink-drawn character holds a photorealistic, metallic lug wrench, turning the bolts on a realistic, mud-splattered black rubber tire. Raindrops are falling, creating realistic splashes in the muddy puddles around them, while the ink character remains completely dry and 2D. The background features a blurred, photorealistic pine forest under a moody, overcast sky. This aesthetically pleasing image perfectly captures the dynamic interaction between imaginative ink art and the gritty, physical world." \
  "GLM 5.2 High" "Ink Sketch Mechanic Fixing Flat Tire"

queue_job 40 \
  "A visually striking image blending expressive charcoal drawing with photorealistic kitchen scenery. A chef, illustrated entirely in smudged black charcoal with dynamic, rough strokes, is passionately stirring a real, steaming pot of tomato soup on a modern, photorealistic gas stove. The charcoal chef holds a highly detailed, wooden cooking spoon, dipping it into the thick, bubbling red soup. Realistic steam rises, blurring the edges of the drawn character. The kitchen counter features gleaming marble textures and real scattered fresh basil leaves. The contrast between the messy, artistic charcoal lines of the chef and the crisp, hyper-realistic culinary ingredients creates an eye-catching, beautiful composition where sketch art meets everyday domestic life." \
  "GLM 5.2 High" "Charcoal Chef Stirring Real Soup"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A finely detailed ink drawing of a Victorian gentleman architect, sketched with meticulous crosshatching and delicate fine pen strokes, standing confidently on a sunlit modern concrete plaza. His wireframe spectacles and measured scroll contrast against photorealistic glass skyscrapers reflecting azure sky. Loose graphite shading defines his frock coat while real-world pedestrians blur past in soft motion. Sharp architectural ink lines merge seamlessly with photographic depth of field, warm golden afternoon light casting actual shadows across his two-dimensional illustrated form. Aesthetically pleasing fusion of hand-drawn illustration and photorealistic urban environment, cinematic composition, intricate linework, volumetric lighting, hyper-detailed, award-winning visual art, stunning clarity." \
  "Kimi K2.6 Thinking" "The Ink Sketch Architect"

queue_job 42 \
  "A wire-sculpted ballerina figure crafted from twisted metal lines and delicate steel mesh, posed gracefully mid-pirouette on a photorealistic polished wooden stage. Her intricate wireframe tutu and slender limbs catch real theatrical spotlights creating dramatic intricate shadows on deep red velvet curtains. Hand-drawn pencil textures overlay her metallic joints suggesting fluid sketched movement. The ornate auditorium seats and blurred audience exist in photographic realism while she remains an elegant line-art sculpture frozen in dance. Aesthetically pleasing blend of three-dimensional wire art and photographic theater environment, dramatic spotlighting, shallow depth of field, cinematic atmosphere, hyper-detailed, visually striking composition, masterpiece, beautiful rendering." \
  "Kimi K2.6 Thinking" "The Wire Sculpted Ballerina"

queue_job 43 \
  "A graphite pencil sketch of a curious botanist with wild hair and ink-stained fingers, drawn with rough hatching and smudged shading, kneeling in a photorealistic lush tropical greenhouse. Her sketchbook and hand-drawn magnifying glass contrast against real dewy orchids and photographic sunlight streaming through vintage glass panels. Loose pencil strokes define her linen coat while photorealistic butterflies hover near her drawn face. The weathered concrete path and active misting system exist in sharp photographic detail. Aesthetically pleasing fusion of rough illustration and vivid natural realism, botanical accuracy, soft volumetric lighting, cinematic framing, intricate pencil work, hyper-detailed environment, visually captivating scene, stunning." \
  "Kimi K2.6 Thinking" "The Pencil Sketch Botanist"

queue_job 44 \
  "A bold ink pen drawing of a vintage cyclist with wireframe bicycle, sketched with confident strokes and crosshatched shadows, riding through a photorealistic rainy European street at dusk. His hand-drawn leather cap and ink-washed cape contrast against real wet cobblestones and photographic neon reflections. Loose pen lines define his wire-spoke wheels while photorealistic raindrops splash around him. The brick buildings and colorful cafe umbrellas exist in sharp photographic detail. Aesthetically pleasing blend of bold illustration and atmospheric urban realism, dynamic motion, moody cinematic lighting, intricate pen work, hyper-detailed wet surfaces, visually compelling composition, dramatic perspective, stunning artwork, beautiful contrast, masterpiece." \
  "Kimi K2.6 Thinking" "The Ink Pen Cyclist"

queue_job 45 \
  "An expressive charcoal sketch of a passionate chef with flour-dusted apron, drawn with bold smudges and dynamic strokes, working in a photorealistic modern restaurant kitchen. His hand-drawn whisk and sketched copper pots contrast against real stainless steel counters and photographic steam rising from sizzling pans. Loose charcoal lines define his tall toque while photorealistic flames flicker beneath him. The tiled walls and fresh hanging herbs exist in sharp photographic detail. Aesthetically pleasing fusion of rough illustration and culinary realism, warm ambient lighting, cinematic depth, intricate charcoal work, hyper-detailed food preparation, visually striking scene, professional composition, beautiful rendering, stunning clarity, masterpiece." \
  "Kimi K2.6 Thinking" "The Charcoal Sketch Chef"

# --- Deepseek Instant ---
queue_job 46 \
  "A charming hand-drawn pencil sketch character, a young woman with flowing hair and wide eyes, holding a translucent polka-dot umbrella, stands in the middle of a bustling photorealistic city street at dusk. The pencil strokes are visible, with cross-hatching shadows and loose, energetic lines defining her dress and posture, while the surrounding wet asphalt, glowing neon signs, and reflective puddles are rendered in crisp, high-definition photorealism with cinematic lighting. Raindrops fall, interacting with her sketched form, blending the two-dimensional illustrative feel with the three-dimensional environment, creating a magical, eye-catching contrast between flat art and deep reality." \
  "Deepseek Instant" "Sketch in the Rain"

queue_job 47 \
  "A magnificent ink-drawn fox, featuring bold, flowing black lines and intricate stippling details on its fur, sits perched elegantly on a weathered, photorealistic wooden park bench surrounded by golden autumn leaves. The fox's expressive eyes and bushy tail are pure illustration, with visible ink splatters and hatching, while the bench, the distant trees, and the soft bokeh background are captured with stunning photographic realism, including texture of the wood grain and falling leaves. Soft afternoon sunlight filters through the canopy, casting realistic shadows that interact with the drawn fox, blending handcrafted art seamlessly into a vivid, aesthetically pleasing natural scene." \
  "Deepseek Instant" "Ink Fox on a Bench"

queue_job 48 \
  "A delicate wireframe and sculpted pencil-drawn butterfly, composed of intricate, looping metallic-like lines and subtle graphite shading, rests gently on the vibrant, photorealistic petal of a bright pink peony flower. The butterfly's wings have a translucent, sketched quality with visible construction lines and geometric guides, while the peony, dewdrops, and the surrounding lush green garden are rendered in hyper-realistic detail with soft natural lighting and shallow depth of field. The contrast between the airy, illustrative insect and the solid, textured botanical world makes an eye-catching, harmonious composition that feels both whimsical and grounded in reality." \
  "Deepseek Instant" "Wireframe Butterfly Garden"

queue_job 49 \
  "A photorealistic, rugged mountain landscape at sunset serves as the backdrop for a central, pen-and-ink drawn astronaut figure, rendered with meticulous cross-hatching and contour lines, standing on a rocky outcrop. The astronaut's helmet and suit feature heavy ink shadows and white highlights, contrasting sharply with the vibrant, realistic orange and purple sky, the detailed craggy peaks, and the soft mist in the valleys below. The illustration style of the character feels like it leaped from a sketchbook, yet it casts a realistic shadow onto the stones, creating a stunning, surreal fusion of two-dimensional artistry and three-dimensional photographic grandeur." \
  "Deepseek Instant" "Pen Astronaut at Sunset"

queue_job 50 \
  "An endearing charcoal-drawn kitten, with smudged black and grey shading, soft furry texture created by rapid pencil strokes, and bright white highlights, playfully bats at a single, photorealistic crimson maple leaf that has fallen onto a textured concrete pathway. The kitten's expressive face and dynamic pose are pure illustration, with visible eraser marks and sketchy lines, while the leaf, the rough concrete, and the blurred background of a photorealistic city park are sharp and lifelike with warm golden hour light. The interplay of the soft, dusty charcoal figure against the crisp real-world elements creates a captivating, heartwarming, and aesthetically pleasing moment." \
  "Deepseek Instant" "Charcoal Kitten and Leaf"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A photorealistic city street at dusk with rain-slicked cobblestones reflecting warm streetlight glow, where a medieval knight drawn in fine graphite pencil lines stands guard holding a detailed ink-sketched sword, the knight's armor rendered with delicate crosshatching and wire-sculpture texture blending seamlessly into the real environment, puddles mirroring the illustrated figure, volumetric fog, cinematic lighting, shallow depth of field, hyperdetailed background with wet asphalt and neon signs, mixing hand-drawn illustration aesthetic with photographic realism, striking visual contrast, aesthetic composition." \
  "ERNIE 5.1" "The Pencil Knight on a Rainy Street"

queue_job 52 \
  "A vibrant real-world flower market bursting with colorful blooms under soft natural daylight, where a large whimsical cat drawn in flowing black ink and fine pen strokes sits atop a wooden crate curiously sniffing a bouquet, the cat's fur rendered with intricate stippling and wire-like contour lines that seem to emerge from the photograph, realistic petals and dewdrops surrounding the illustrated creature, bokeh background with market stalls, warm golden hour lighting, photorealistic textures blending with sketch artistry, enchanting and eye-catching scene, balanced composition." \
  "ERNIE 5.1" "The Ink Cat Exploring a Flower Market"

queue_job 53 \
  "A majestic real-world baroque concert hall with ornate golden ceilings and marble columns photographed in rich natural light, where an elegant ballerina figure is drawn in delicate silver wire sculpture and soft pencil shading mid-pirouette on the polished floor, the illustrated dancer's tutu flowing with fine ink lines that contrast against the photorealistic architectural details, reflections on the glossy floor, dust particles in sunbeams, dramatic chiaroscuro lighting, seamless blend of handcrafted wire art aesthetic and photographic grandeur, mesmerizing visual harmony." \
  "ERNIE 5.1" "The Wire Sculpture Ballerina in a Grand Hall"

queue_job 54 \
  "A breathtaking real-world mountain trail at sunrise with dramatic clouds and rocky terrain captured in vivid photographic detail, where a fierce small dragon is drawn in colored pencil and ink wash perched on a mossy boulder breathing illustrated fire that swirls with visible graphite texture, the creature's scales detailed with precise pen crosshatching against the majestic landscape, wildflowers and fog in the valley below, warm amber light rays, depth and atmosphere, photorealistic nature blending with charming hand-drawn fantasy illustration, captivating and dynamic composition." \
  "ERNIE 5.1" "The Sketchbook Dragon on a Mountain Trail"

queue_job 55 \
  "A cozy real-world vintage cafe interior with warm ambient lighting and rustic brick walls photographed in soft tones, where a charming character portrait of a young woman is drawn in exquisite pencil and fine-tip pen on a napkin resting on a wooden table beside a real ceramic coffee cup, the illustrated face showing lifelike shading and delicate linework that appears almost three-dimensional against the textured tabletop, steam rising from the cup, bokeh lights in background, intimate atmosphere, seamless fusion of hand-drawn portraiture and photographic cafe ambiance, visually stunning." \
  "ERNIE 5.1" "The Pencil Portrait on a Vintage Cafe Table"

# --- LongCat Deep search ---
queue_job 56 \
  "A photorealistic close-up of a vintage wooden workbench covered in scattered pencil shavings and graphite dust, where an intricate wire sculpture of a ballet dancer is caught mid-pirouette, one delicate metallic foot lifting off the edge of a leather-bound sketchbook, the dancer's twisted copper and silver limbs catching golden morning light streaming through a nearby window, ultra-detailed photorealistic rendering mixed with illustrative pencil marks and smudges on the paper background, shallow depth of field, dramatic chiaroscuro lighting, 8k resolution aesthetic." \
  "LongCat Deep search" "The Sculptor's Hand"

queue_job 57 \
  "A hyper-detailed close-up view of an artist's rough handmade paper where an ink-drawn arctic wolf is half-transformed into photorealistic reality, its front snout and one piercing amber eye rendered in stunning photorealism while the rest remains expressive charcoal and sumi sketch lines, water droplets beading on the snout from the ink apparently still wet, the paper's fiber texture visible where it meets fur, a real spatter of indigo ink drops frozen in mid-air beside the muzzle, studio lighting, dramatic contrast, mixed media photorealism and illustration." \
  "LongCat Deep search" "Ink Wolf Emergence"

queue_job 58 \
  "A magnificent wide shot of a bustling modern city street at golden hour, where a colossal yellow carpenter pencil held by a human hand in the foreground sketches towering skyscrapers into existence, the graphite strokes glowing with amber light before solidifying into photorealistic glass and steel structures, half-finished buildings showing pencil grid lines and construction marks alongside completed reflective windows, photorealistic urban environment blending seamlessly with illustrative concept art elements, dust motes dancing in volumetric light rays, 8K cinematic composition." \
  "LongCat Deep search" "The Pencil Architect"

queue_job 59 \
  "An intimate macro photorealistic view of an open vintage leather journal on an oak desk, where exquisite pen-drawn vines with detailed leaf venations are erupting from the aged paper into full three-dimensional reality, the ink lines still wet with sepia and emerald ink transforming into living botanical matter with visible dewdrops and pollen, a real vintage fountain pen resting in the fold continuing to draw, ultra-detailed macro photography blending with illustrative scientific botanical drawing, soft natural window light, extremely detailed textures." \
  "LongCat Deep search" "Botanical Pen Work"

queue_job 60 \
  "A dimly lit underground jazz club scene, where an intricate wire-frame sculpture figure sits on a glowing stool, its body made of twisted copper and brass wires catching amber stage light, one wire hand pressing valves on a real vintage saxophone producing visible swirling colored smoke made of ink wash, the floor scattered with real musical notation and ink splatters, photorealistic smoke and brass contrasting with the illustrative wire form, cinematic atmospheric lighting, shallow depth of field, detailed textures." \
  "LongCat Deep search" "Wire Musician in Smoke"

echo "✅ All 60 jobs queued in scheduler"
