#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Reality meets art — photorealistic subject inside an illustrated
#        world (pencil/pen/ink/watercolor/wire-sculpture surroundings)
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+34+-+reality+meats+art
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A real astronaut in a fully photorealistic spacesuit, visible fabric weave, scuffed metal joints, reflective visor catching authentic light, stands motionless on a hand-painted watercolor moon. The lunar surface is loose washes of grey and lavender pigment, bleeding edges, visible paper texture, craters sketched in soft graphite outline. Behind them, planets are rendered as flat gouache circles with dripping paint halos, stars are scattered ink splatters. The astronaut's boot leaves a crisp photographic shadow on the painted ground, grounding the real figure inside the fluid, dreamlike illustrated universe. Lighting on the suit is cinematic and hyper-detailed, every seam and scratch visible, contrasting sharply with the flat, textured watercolor world surrounding them." \
  "Claude Sonnet 5 medium" "Photorealistic Astronaut in Watercolor Cosmos"

queue_job  2 \
  "A photorealistic violinist, real skin texture, real linen shirt creased naturally, real glossy wood grain on the violin, stands mid-performance on a street built entirely from cross-hatched pen-and-ink illustration. Buildings rise in scratchy black ink lines, uneven perspective, exaggerated architectural sketch strokes, windows filled with loose scribbled shading. Cobblestones are drawn with quick confident pen marks, puddles rendered as glossy ink pools. The violinist's hands, bow, and instrument show authentic photographic detail, catching warm directional light, while the illustrated cityscape stays flat monochrome except for a single hand-inked wash of sepia. The contrast makes the real musician feel startlingly present inside the sketched, paper-textured world." \
  "Claude Sonnet 5 medium" "Real Violinist in Pen-and-Ink City"

queue_job  3 \
  "A real taxidermied fox figurine, photorealistic fur texture, glass eyes reflecting studio light, real dust particles visible on its coat, sits perched on a tree branch inside a forest drawn entirely in waxy crayon strokes. Tree trunks are thick uneven crayon lines, leaves are scribbled green clusters, sunlight is drawn as yellow crosshatched rays breaking through. The ground is a childlike crayon texture of brown and green smudges. The fox's fur, whiskers, and glossy nose remain crisp, photographic, and richly detailed, casting a real soft shadow across the waxy illustrated bark, creating a striking collision between tactile realism and playful, textured crayon-drawn wilderness." \
  "Claude Sonnet 5 medium" "Photoreal Fox Item in Crayon Forest"

queue_job  4 \
  "A photorealistic scuba diver, wetsuit with authentic rubber sheen, real bubbles rising from the regulator, real skin visible around the mask seal, floats suspended inside an ocean built from twisted wire-sculpture forms. Coral is bent copper wire shaped into jagged branches, fish are simple wireframe silhouettes with empty negative space bodies, waves above are looping wire curls suggesting motion. Light rays are thin taut wire strands catching studio highlights. The diver's equipment and body remain fully rendered with realistic texture and depth, floating impossibly among the skeletal, three-dimensional wire ocean, producing a striking sculptural contrast between organic photographic realism and abstract, structural illustrated form." \
  "Claude Sonnet 5 medium" "Real Diver Inside Wired-Sculpture Ocean"

queue_job  5 \
  "A real chef, photorealistic hands dusted with flour, authentic fabric folds in the apron, real steam rising visibly from a pan, stands cooking inside a kitchen rendered entirely in loose charcoal sketch strokes. Countertops are smudged grey charcoal blocks, pots and pans are quick gestural outlines, shelves fade into rough unfinished linework. Smoke and steam from the illustrated stove are soft charcoal smears, while the chef's face, hands, and utensils remain crisp and photographically lit, catching warm kitchen light. The dramatic tonal contrast between the tactile, real subject and the raw, unfinished charcoal-drawn kitchen creates an eye-catching, painterly yet startlingly lifelike composition." \
  "Claude Sonnet 5 medium" "Photoreal Chef in Charcoal Kitchen Sketch"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A crisp, photorealistic astronaut in a pristine white spacesuit stands on a stark lunar surface. Every fabric wrinkle, metallic reflection on the visor, and speck of dust on the boots is captured with sharp, high-fidelity photographic detail. However, the entire background is a loose, whimsical ink and watercolor illustration. The craters are rough pencil crosshatches, the distant Earth is a vibrant watercolor splash with bleeding edges, and stars are simple ink dots. The contrast is stark and deliberate, as if a real astronaut stepped directly onto the pages of a hand-drawn children's adventure book, lit by a single, realistic studio light source that casts sharp shadows onto the illustrated ground." \
  "Gemini 3.5 Flash" "The Astronaut's Sketchbook"

queue_job  7 \
  "A photorealistic woman sits at a table, captured in stunning photographic detail. Her knitted sweater shows individual yarn fibers, her skin has visible pores and subtle textures, and her eyes reflect sharp, realistic ambient light. She holds a steaming white ceramic mug, completely real. In striking contrast, the entire cafe around her is a fluid watercolor and pen sketch. The wooden table, the chair she sits on, the background windows, and other patrons are loose ink lines and soft, translucent color washes that bleed into the canvas. The hyper-realistic woman perfectly anchors the center of this beautiful, living, hand-painted art piece." \
  "Gemini 3.5 Flash" "The Watercolor Cafe"

queue_job  8 \
  "A photorealistic, highly detailed mechanical drone hovers in mid-air. The drone features flawless metallic textures, glossy carbon fiber panels, tiny real glass camera lenses, and glowing blue LED status lights, all rendered with absolute photographic precision. The environment surrounding the drone, however, is a chaotic, dense cyberpunk cityscape drawn entirely in dark graphite pencil and charcoal. The towering skyscrapers, tangled power lines, and neon signs are represented by smudged shading, sharp architectural line work, and dramatic crosshatching. The sleek, tangible reality of the high-tech drone contrasts beautifully against the raw, hand-sketched, textured monochrome world it explores." \
  "Gemini 3.5 Flash" "Cyberpunk Graphite"

queue_job  9 \
  "A photorealistic red fox crouches low, ready to pounce. Every single strand of its vibrant orange fur, the moisture on its black nose, and the sharp focus in its glassy eyes are rendered with breathtaking photographic realism. The forest environment around the fox is completely constructed from minimalist line art and colored paper illustration style. The trees are sharp, angular geometric sketches, the forest floor is a pattern of stylized ink strokes, and falling leaves are simple vector-like drawings. The highly detailed, breathing, organic animal stands out in powerful, intentional contrast against the flat, highly stylized, hand-drawn natural habitat." \
  "Gemini 3.5 Flash" "The Origami Forest"

queue_job 10 \
  "A photorealistic man in a modern black leather jacket stands looking forward. The jacket has realistic leather grain, metallic zipper glints, and true-to-life creases, while his face shows authentic skin texture, stubble, and natural highlights. He is completely real. The background behind him, and even the air around him, dissolves into an intricate, flowing fountain pen and ink illustration. Swirling baroque patterns, crosshatched shadows, and fine line art filigree wrap around his form without touching him. The striking juxtaposition makes it appear as though a real person is breaking through a complex, beautiful, two-dimensional black and white line drawing." \
  "Gemini 3.5 Flash" "A Portrait in Ink"

# --- ChatGPT ---
queue_job 11 \
  "A fully photorealistic young woman in a vivid crimson trench coat stands at a quiet illustrated tram stop, her skin, hair, clothing, and lighting captured with authentic photographic realism. Every surrounding element exists only as expressive black ink line art with soft watercolor washes: sketchbook buildings, loosely painted trees, hand-drawn overhead wires, scribbled street signs, and lightly textured clouds. She calmly holds a folded umbrella while watching an ink-drawn tram arrive from a perspective-filled avenue. Pencil construction lines remain visible beneath the artwork, emphasizing the creative process. The dramatic contrast between the living subject and the handcrafted illustrated city creates an elegant, imaginative, gallery-worthy visual narrative with refined composition." \
  "ChatGPT" "The Last Stop Before Color"

queue_job 12 \
  "A completely photorealistic elderly botanist wearing a weathered linen apron carefully examines a luminous flower growing inside a beautifully illustrated greenhouse. His realistic face, hands, clothing, glass spectacles, and subtle natural lighting exhibit authentic photographic detail, while everything else appears as delicate colored-pencil drawings enhanced with watercolor textures and fine ink outlines. Illustrated vines climb sketched iron frames, butterflies become ink doodles, and rows of flowers resemble pages from a vintage botanical journal. Pencil shading, erased guidelines, and paper grain remain intentionally visible throughout the environment. The harmonious collision of reality and illustration creates an enchanting atmosphere where scientific curiosity meets handcrafted artistic imagination." \
  "ChatGPT" "The Botanist Inside the Sketchbook"

queue_job 13 \
  "A photorealistic porcelain teacup filled with steaming tea rests naturally on a small wooden table, displaying authentic ceramic reflections, realistic steam, and detailed surface imperfections under soft afternoon light. Everything surrounding the cup belongs to an illustrated universe made from expressive pen drawings, watercolor splashes, and textured sketchbook paper. Hand-drawn paper cranes appear to fly through ink-painted trees, a sketched river winds across the landscape, whimsical cottages emerge from loose pencil strokes, and mountains dissolve into watercolor gradients. Tiny handwritten notes decorate the borders like an artist's journal. The striking contrast transforms an ordinary everyday object into the central anchor of a magical illustrated world." \
  "ChatGPT" "Tea With Paper Cranes"

queue_job 14 \
  "A fully photorealistic violinist performs passionately beneath a vintage streetlamp, with lifelike skin, realistic wood grain on the violin, authentic fabric textures, and cinematic evening illumination captured as true professional photography. Every surrounding feature becomes an elaborate monochrome pen-and-ink city enhanced with watercolor accents: sketched cobblestone streets, crosshatched buildings, illustrated cafe terraces, whimsical bicycles, and loosely drawn balconies overflowing with painted flowers. Musical notes flow outward as elegant ink calligraphy weaving through the illustrated architecture. Visible pencil guidelines and textured paper reinforce the handcrafted aesthetic, while the realistic musician becomes the emotional centerpiece inside an expressive hand-drawn European streetscape." \
  "ChatGPT" "The Violinist Among Ink Streets"

queue_job 15 \
  "A photorealistic female explorer wearing practical outdoor clothing and carrying authentic climbing equipment walks confidently through an extraordinary forest constructed entirely from elegant wire sculptures, graphite sketches, and watercolor accents. Her realistic skin, weathered boots, woven backpack, metallic compass, and warm sunlight are rendered with impeccable photographic fidelity, standing in deliberate contrast against illustrated trees formed from looping metal lines, sketched wildlife, penciled mountains, and translucent watercolor skies. Fine construction marks, ink annotations, and textured drawing paper remain visible across the environment, celebrating the artistic process. The scene blends realism with imaginative illustration into a sophisticated, visually unforgettable adventure filled with curiosity and wonder." \
  "ChatGPT" "Explorer of the Wireframe Forest"

# --- Grok fast ---
queue_job 16 \
  "A highly detailed photorealistic young female explorer with realistic sun-kissed skin, detailed facial features, messy ponytail hair with individual strands, wearing authentic khaki adventure outfit with real fabric textures and leather straps, holding a vintage lantern, standing curiously inside a vast hand-drawn pencil and ink illustrated ancient temple ruin filled with intricate line-art vines, sketched stone carvings, watercolor-washed hieroglyph walls and floating illustrated dust particles, dramatic chiaroscuro lighting creating striking contrast between her lifelike photographic presence and the textured non-photorealistic sketched environment, cinematic composition, aesthetically pleasing, eye-catching." \
  "Grok fast" "A Photorealistic Explorer in a Sketched Ancient Temple"

queue_job 17 \
  "Photorealistic young male guitarist with realistic skin pores, expressive face, detailed denim jacket and jeans with real fabric folds and wear, strumming an acoustic guitar under warm streetlamp glow, positioned in the center of a vibrant pen-and-ink illustrated bustling city street at dusk with loose watercolor buildings, sketched pedestrians as line drawings, dynamic cross-hatched shadows and swirling illustrated clouds, intentional photoreal subject contrasting beautifully with the artistic sketched surroundings, captivating atmosphere, high visual impact." \
  "Grok fast" "A Photorealistic Street Musician in an Illustrated Cityscape"

queue_job 18 \
  "Fully photorealistic middle-aged male chef with realistic sweaty skin, detailed beard stubble, white uniform with authentic stains and wrinkles, tasting a spoon in a busy kitchen, surrounded by delicate watercolor and ink illustrated pots, sketched ingredients floating like drawings, hand-drawn steam swirls, pencil-lined wooden counters and hanging utensils in loose artistic style, dramatic side lighting highlighting the photoreal figure against the textured illustrated background, warm inviting tones, striking and aesthetically pleasing composition." \
  "Grok fast" "A Photorealistic Chef in a Watercolor Kitchen"

queue_job 19 \
  "Photorealistic fluffy orange tabby cat with hyper-detailed fur, realistic eyes reflecting light, whiskers and paw pads, sitting gracefully on a bench inside an enchanting garden rendered in intricate wire-sculpture and pencil illustration style with sketched flowers, ink-drawn vines twisting around structures, loose watercolor sky and butterflies as line art, perfect contrast between the lifelike photographic cat and the dreamy hand-drawn environment, soft magical lighting, eye-catching and beautiful." \
  "Grok fast" "A Photorealistic Cat in a Wired-Sculpture Garden"

queue_job 20 \
  "Photorealistic graceful young female ballet dancer with realistic muscle definition, detailed tutu fabric with real folds and sheen, pointe shoes, performing an elegant pose on stage, enveloped by dramatic pen-and-ink illustrated theater interior with sketched ornate curtains, watercolor audience silhouettes, cross-hatched spotlights and architectural details, striking intentional contrast between her photoreal presence and the artistic non-photographic surroundings, dynamic composition, aesthetically captivating and memorable." \
  "Grok fast" "A Photorealistic Ballet Dancer in a Pen-Drawn Theater"

# --- Copilot Smart ---
queue_job 21 \
  "A photorealistic young woman in casual modern clothing, her skin and fabric rendered with real photographic detail, stands inside a surreal forest drawn entirely in black ink lines and watercolor washes. The trees are sketched with loose strokes, leaves suggested by faint pencil shading, and the ground is a patchwork of watercolor textures. The contrast between her lifelike presence and the illustrated environment feels striking, as if she has stepped into a sketchbook world. Light falls naturally on her, while the illustrated background remains flat and stylized, emphasizing the intentional clash of realism and art." \
  "Copilot Smart" "Photorealistic Woman in Ink Forest"

queue_job 22 \
  "A photorealistic man in a tailored suit, his face and clothing captured with real photographic sharpness, walks down a city street drawn entirely in pencil sketch style. The buildings are outlined with graphite strokes, windows shaded with crosshatching, and cars reduced to simple line drawings. His polished shoes reflect real light, contrasting with the flat pencil textures around him. The scene feels like a real person navigating a hand-drawn cityscape, the juxtaposition highlighting the surreal blend of reality and imagination." \
  "Copilot Smart" "Photorealistic Man in Pencil City"

queue_job 23 \
  "A photorealistic child with vivid detail in skin tone, hair, and clothing plays joyfully in a playground illustrated in watercolor. The swings, slides, and climbing frames are painted with loose brushstrokes, colors bleeding softly into one another, lacking sharp edges. The child's laughter and movement are captured with photographic clarity, while the watercolor environment feels dreamlike and fluid. The intentional contrast creates a whimsical image of a real child immersed in a painted fantasy world." \
  "Copilot Smart" "Photorealistic Child in Watercolor Playground"

queue_job 24 \
  "A photorealistic cat, its fur and whiskers rendered with photographic precision, sits calmly in a living room drawn entirely in ink and wire-sculpture style. The furniture is outlined with bold pen strokes, lamps and shelves appear as wireframe sketches, and shadows are suggested with hatching. The cat's lifelike presence contrasts sharply with the illustrated surroundings, as if a real animal has wandered into a sketched blueprint of a home. The surreal effect is eye-catching and intentional." \
  "Copilot Smart" "Photorealistic Cat in Ink Room"

queue_job 25 \
  "A photorealistic woman sipping coffee, her skin, hair, and clothing captured with real photographic detail, sits inside a cafe illustrated in pen and watercolor. Tables and chairs are drawn with loose ink lines, cups and plates painted with soft washes of color, and the background patrons reduced to sketchy outlines. The woman's lifelike realism stands out against the stylized cafe, creating a striking image of reality colliding with illustration. The contrast feels deliberate and aesthetically pleasing." \
  "Copilot Smart" "Photorealistic Woman in Illustrated Cafe"

# --- Mistral Think ---
queue_job 26 \
  "A hyper-detailed, photorealistic violinist with lifelike skin, intricate fabric textures on their formal attire, and natural lighting performing in the heart of a dreamy watercolor forest. The violin and the musician's hands are sharp, with visible wood grain and string reflections, while the surrounding ancient trees, soft moss, and floating leaves are rendered in loose, flowing watercolor strokes. The contrast between the crisp realism of the musician and the ethereal, painted forest creates a surreal, captivating scene." \
  "Mistral Think" "A Photorealistic Violinist in a Watercolor Forest"

queue_job 27 \
  "A meticulously detailed, photorealistic vintage Leica camera with authentic metal and leather textures, resting on a cobblestone street. The camera's lens, dials, and worn leather strap are in sharp focus, while the entire background—a bustling, old-world European city—is drawn in intricate pencil sketches. Buildings, streetlamps, and distant figures are rendered with hatching and cross-hatching, creating depth and texture. The juxtaposition of the tangible camera against the hand-drawn cityscape is visually striking." \
  "Mistral Think" "A Realistic Vintage Camera in a Pencil-Sketch City"

queue_job 28 \
  "A photorealistic ballerina mid-pirouette, her satin pointe shoes and delicate tulle tutu captured with photographic precision, stands center stage in a traditional ink-wash theater. The stage, curtains, and ornate proscenium arch are rendered in bold, expressive ink brushstrokes, with subtle gradients and splatter effects. The dancer's skin glows with realistic highlights and shadows, while the illustrated backdrop evokes a sense of movement and drama. The fusion of real and drawn elements is seamless and mesmerizing." \
  "Mistral Think" "A Lifelike Ballerina in an Ink-Wash Theater"

queue_job 29 \
  "A steaming, photorealistic ceramic coffee cup with visible steam, glossy glaze, and intricate latte art sits on a cafe table. The cup and saucer are in crisp focus, while the entire cafe—tables, chairs, windows, and patrons—is constructed from thin, interconnected wireframe lines, giving the impression of a 3D sketch. The contrast between the solid, tangible cup and the abstract, linear environment creates a modern, artistic tension." \
  "Mistral Think" "A Hyperrealistic Coffee Cup in a Wireframe Cafe"

queue_job 30 \
  "A photorealistic astronaut in a detailed, textured spacesuit, complete with reflective visor and intricate stitching, floats in a cosmic landscape. The astronaut and their suit are rendered with lifelike precision, while the surrounding nebulae, stars, and planets are drawn in soft, blended chalk pastels. The vibrant, dreamy colors of the illustrated galaxy contrast sharply with the astronaut's grounded, realistic presence, creating a surreal and awe-inspiring image." \
  "Mistral Think" "A Realistic Astronaut in a Chalk-Pastel Galaxy"

# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "A highly detailed, photorealistic astronaut floating gracefully inside a space station drawn entirely in intricate black-and-white pencil sketches. The astronaut features real skin texture visible through the visor, realistic fabric folds on the spacesuit, and authentic photographic lighting reflecting off the helmet. Surrounding them, the control panels, floating tools, and zero-gravity cables are rendered in expressive, textured graphite strokes and cross-hatching. The contrast between the hyper-realistic human subject and the hand-drawn, monochromatic sketched environment is striking and intentional. Cinematic composition, absolute masterpiece, visually stunning, seamlessly blending real-world photography with classic illustration styles to create a breathtaking visual experience of mixed media art." \
  "Qwen 3.7 Plus Thinking" "Photorealistic Astronaut in a Pencil-Sketched Space Station"

queue_job 32 \
  "A single, hyper-realistic red rose resting on a mossy stone, surrounded by a lush botanical garden rendered in soft, expressive watercolor washes. The rose features photographic macro details, real velvety petal textures, crisp dewdrops, and authentic natural lighting. In stark contrast, the surrounding leaves, blooming background flowers, and winding garden path are painted in loose, translucent watercolor strokes with visible paper texture and paint bleeds. The striking juxtaposition of the fully real, three-dimensional flower against the delicate, hand-painted illustrated flora creates a breathtaking, eye-catching visual harmony. Masterful blend of photorealism and fine art illustration techniques for a truly captivating aesthetic result that perfectly merges reality and imagination." \
  "Qwen 3.7 Plus Thinking" "Hyper-Realistic Red Rose in a Watercolor Garden"

queue_job 33 \
  "A photorealistic vintage leather-bound camera sitting on a wooden windowsill, looking out over a bustling metropolis drawn in dynamic pen and ink. The camera boasts real leather textures, authentic metallic reflections, precise glass lens details, and natural photographic lighting. Conversely, the sprawling cityscape outside the window, including towering buildings, flying birds, and intricate street details, is illustrated using bold ink lines, stippling, and cross-hatching techniques. The intentional contrast between the tangible, real-world object and the textured, monochromatic drawn environment is visually arresting. Aesthetically pleasing, highly detailed, merging real-life photography with classic architectural sketching to produce an absolutely stunning and memorable mixed media artwork that captivates the viewer." \
  "Qwen 3.7 Plus Thinking" "Vintage Leather Camera in an Ink-Drawn Cityscape"

queue_job 34 \
  "A photorealistic ballerina mid-pirouette on a grand stage, surrounded by a magnificent theater rendered entirely as intricate wire-sculpture illustrations. The dancer features real skin pores, authentic satin fabric folds on her tutu, realistic sweat glistening, and true studio lighting. In striking contrast, the grand velvet curtains, ornate proscenium arch, and the seated audience are depicted as delicate, three-dimensional wireframe sketches with metallic shading and structural linework. The intentional juxtaposition of the living, breathing human subject against the ethereal, hand-crafted wire-illustrated environment creates a breathtaking, eye-catching masterpiece of mixed media art that beautifully highlights the surreal contrast between physical reality and pure imagination." \
  "Qwen 3.7 Plus Thinking" "Photorealistic Ballerina in a Wire-Sculpture Theater"

queue_job 35 \
  "A hyper-realistic koi fish swimming just below the water surface, surrounded by a tranquil pond environment drawn in expressive, smudged charcoal. The fish showcases authentic photographic scales, real fin translucency, vivid orange and white pigmentation, and true underwater lighting refractions. In deliberate contrast, the rippling water surface, floating lily pads, and smooth river rocks are illustrated using rich charcoal strokes, heavy shading, and textured paper grain. The striking visual difference between the lifelike, vibrant aquatic creature and the moody, hand-drawn sketched habitat creates a deeply aesthetic and captivating image, blending reality with raw illustration to form a truly mesmerizing and unforgettable visual experience for the viewer." \
  "Qwen 3.7 Plus Thinking" "Hyper-Realistic Koi Fish in a Charcoal-Sketched Pond"

# --- GLM 5V ---
queue_job 36 \
  "A stunningly photorealistic young woman with luminous porcelain skin, individual pores visible, flowing auburn hair catching golden hour light, wearing a textured cream linen dress with natural fabric folds and subtle wrinkles, standing amidst an entirely hand-painted watercolor garden environment. Behind her, soft bleeding watercolor washes create dreamy flowers and foliage in delicate pastel pinks, blues, and greens with visible paper texture and brushstroke edges. The contrast between her hyper-real photographic presence—complete with subsurface scattering on skin, realistic eye reflections, and authentic material properties—and the loose, expressive watercolor illustration surrounding her creates a magical, surreal atmosphere. Gentle dappled illustrated sunlight filters through painted leaves onto her photoreal form." \
  "GLM 5V" "Photoreal Girl in Watercolor Garden"

queue_job 37 \
  "A completely photorealistic toddler with chubby cheeks showing natural skin texture, soft baby fine hair with individual strands, wearing a denim overall outfit with accurate stitching and fabric weight, sitting on a swing that exists within an entire world rendered in graphite pencil sketch style. The background features hand-drawn pencil trees with visible hatching and cross-hatching shading techniques, sketched playground equipment with rough pencil lines and construction marks, and a pencil-sketched sky with directional stroke clouds. The child's photorealistic skin shows authentic subsurface scattering, realistic eye moisture, and true-to-life material properties while everything around them remains intentionally unfinished, artistic, and illustrative with graphite texture, smudge marks, and hand-drawn aesthetic creating striking visual juxtaposition." \
  "GLM 5V" "Real Child in Pencil Sketch Playground"

queue_job 38 \
  "An intensely photorealistic jazz saxophonist with weathered hands showing veins, wrinkles, and authentic skin texture, wearing a worn leather jacket with realistic patina and metal zipper details, playing his instrument with passionate expression and sweat-dampened forehead, positioned inside a venue completely rendered in bold black ink pen-and-ink illustration style. The surrounding jazz club features dramatic ink cross-hatching shadows, stark black ink silhouettes of audience figures, ink-washed bar elements with varying line weights, and graphic novel-style ink backgrounds. The musician's hyper-real face captures every pore, stubble detail, and lifelike eye reflection while the environment maintains expressive ink drawing qualities with high contrast, intentional line work, and artistic ink splatter effects creating powerful aesthetic tension between mediums." \
  "GLM 5V" "Photoreal Musician in Ink Drawing Jazz Club"

queue_job 39 \
  "A breathtakingly photorealistic ballerina mid-pirouette with glistening perspiration on perfectly rendered skin, individual muscle definition visible beneath translucent pointe shoe satin, wearing a tutu with authentic tulle layering and realistic fabric physics, performing on a stage where the entire theater exists as an intricate wire sculpture installation art piece. The background features delicate wire-frame chandeliers, wire-twisted theater balconies with elegant metal curves, wire-mesh curtains, and abstract wire sculpture audience forms creating an ethereal, three-dimensional sketched environment. Her photorealistic body displays accurate anatomical detail, genuine skin subsurface scattering, and true photographic lighting interaction while surrounding wire elements cast illustrated shadows with artistic interpretation, blending dimensional wire art aesthetics with hyper-real human presence in captivating visual harmony." \
  "GLM 5V" "Real Ballerina in Wire Sculpture Theater"

queue_job 40 \
  "A deeply photorealistic elderly gentleman with distinguished white beard showing individual hair strands, weathered skin texture mapping age spots and wrinkles authentically, wearing a tweed jacket with precise wool fiber visibility and brass button reflections, reading a book while seated in a library entirely rendered in rich charcoal drawing style. The environment features heavily blended charcoal bookshelves with smudged shadow depth, charcoal-stroked armchairs with textural grain, expressive charcoal sketch windows with atmospheric perspective, and hand-drawn charcoal architectural details showing artist's mark-making. His photorealistic face captures lifetime character through genuine skin imperfections, realistic eye clarity with age-appropriate lens effects, and authentic material interactions while the charcoal surroundings provide artistic, moody, illustrated atmosphere with intentional medium contrast creating emotionally resonant imagery." \
  "GLM 5V" "Photoreal Elderly Man in Charcoal Sketch Library"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A photorealistic elderly man with weathered skin, silver beard, and sharp blue eyes, wearing a real leather jacket with visible stitching and authentic brass film camera strap, standing inside a vast hand-drawn landscape of ink crosshatching and watercolor washes. The illustrated mountains and pine trees around him are rendered in delicate pencil strokes and pen lines with rough paper texture clearly visible. Soft natural photographic lighting illuminates his real face and hands while the sketched environment remains flat and graphic. Extreme detail on skin pores and fabric weave against the artistic two-dimensional backdrop. Surreal contrast between dimensional reality and illustrated fiction." \
  "Kimi K2.6 Thinking" "The Photographer in the Sketchbook"

queue_job 42 \
  "A photorealistic young ballerina with porcelain skin and satin pointe shoes, real tulle skirt catching genuine stage light, posed en pointe within an elaborate garden drawn entirely in India ink and loose watercolor. The illustrated roses and vines surrounding her are sketched with bold pen strokes and bleeding pigment on textured paper. Her real skin shows subtle pores and soft blush while the botanical lines remain graphic and flat. Dramatic photographic spotlight creates authentic shadows on her face against the two-dimensional floral backdrop. The contrast between her dimensional physical presence and the hand-rendered illustrated environment feels magical and intentionally surreal." \
  "Kimi K2.6 Thinking" "The Ballerina in the Ink Garden"

queue_job 43 \
  "A photorealistic vintage motorcycle with chrome exhaust pipes, real leather seat showing authentic wear patterns, and gleaming metallic paint reflecting actual environmental light, parked on a street drawn entirely in graphite pencil and fine liner ink. The illustrated buildings and cobblestones surrounding it are rendered with crosshatching shading and architectural sketch lines on cream paper. Realistic photographic shadows fall beneath the heavy bike while the drawn environment remains flat and illustrative. Every bolt and rust spot on the motorcycle shows true material detail against the hand-sketched two-dimensional cityscape. The juxtaposition of tangible machinery and illustrated urban scenery creates a striking surreal visual paradox." \
  "Kimi K2.6 Thinking" "The Motorcycle in the Pencil City"

queue_job 44 \
  "A photorealistic tabby cat with individual fur strands, real whiskers catching soft light, and authentic amber eyes reflecting photographic detail, sitting calmly inside a forest drawn entirely in loose watercolor and pen ink. The illustrated trees and foliage around it are painted with bleeding pigments and delicate ink outlines on textured paper. Natural photographic sunlight illuminates the cat's real coat while the painted woodland remains flat and artistic. Every whisker and paw pad shows true organic texture against the hand-rendered two-dimensional backdrop. The deliberate contrast between the living feline subject and the illustrated natural environment creates an enchanting surreal scene." \
  "Kimi K2.6 Thinking" "The Cat in the Watercolor Forest"

queue_job 45 \
  "A photorealistic ceramic coffee cup with real steam rising, genuine liquid surface tension visible, and authentic ceramic glaze reflecting soft light, sitting on a desk inside a room drawn entirely in wireframe sculpture and technical pen illustration. The illustrated furniture and walls surrounding it are rendered in delicate ink lines and three-dimensional wireframe mesh on white paper. Natural photographic lighting catches the cup's real rim and handle while the sketched studio remains flat and schematic. Every coffee bubble and ceramic imperfection shows true material detail against the hand-drawn two-dimensional technical backdrop. The contrast creates a striking surreal dialogue between tangible object and illustrated space." \
  "Kimi K2.6 Thinking" "The Coffee Cup in the Wireframe Studio"

# --- Deepseek Instant ---
queue_job 46 \
  "A photorealistic young woman with porcelain skin, freckles, and flowing auburn hair, wearing a cream-colored linen dress, kneels to tend a garden, her hands and face rendered with sharp photographic detail, soft natural skin texture, and cinematic lighting. Surrounding her, every leaf, flower, vine, stone wall, and butterfly is drawn in loose graphite pencil sketches with visible hatching, smudged shading, and white paper texture, as if she has stepped into a monochrome illustrated botanical plate. The contrast between her vivid realism and the monochrome, hand-drawn environment is striking, with dappled sunlight casting realistic shadows that blend into sketchy outlines, creating a dreamy, intentional hybrid aesthetic." \
  "Deepseek Instant" "Photorealistic Woman in Pencil-Sketch Garden"

queue_job 47 \
  "A hyperrealistic male chef with stubbled jaw, sweat beads on his forehead, and a pristine white chef's jacket with visible cotton weave, holds a sizzling cast-iron pan, his expression focused and deeply lifelike. Surrounding him, the kitchen counter, hanging copper pots, herbs, flames, and tiled backsplash are rendered in loose Chinese ink-wash and fine pen hatching, with watery black strokes, splatters, and rice-paper grain, while he remains crisp, colorful, and photographically sharp. Steam rises realistically from the pan but dissolves into ink-brush swirls. The lighting creates a warm glow on his skin that sharply contrasts with the monochromatic, sketchy chaos around him, making his presence feel magical and grounded simultaneously." \
  "Deepseek Instant" "Realistic Chef in Ink-Wash Kitchen"

queue_job 48 \
  "A photorealistic little girl with curly blonde hair, rosy cheeks, denim overalls, and muddy sneakers, laughs while chasing a glowing firefly, her skin, fabric folds, and hair strands captured with true photographic precision and natural daylight. All around her, the meadow grass, wildflowers, distant trees, fluffy clouds, and even the firefly's trail are painted in soft, transparent watercolor washes with visible brushstrokes, paper grain, and color bleeding outside the lines, as if she has leaped into a children's storybook illustration. The wet-on-wet color blooms and pale pastels of the environment heighten her vivid realism, while her shadow on the grass is rendered with painterly edges, creating a charming, intentional dissonance that draws the eye instantly to her." \
  "Deepseek Instant" "Photorealistic Girl in Watercolor Meadow"

queue_job 49 \
  "A photorealistic middle-aged man with weathered hands, gray stubble, and a plaid flannel shirt, holding a wooden carving chisel, stands in his workshop, his face and tool displaying flawless photographic depth, pores, and wood grain on the chisel handle. His workbench, surrounding shelves of jars, hanging lamps, half-carved blocks, sawdust particles, and the wooden beams above are constructed as delicate, three-dimensional wire-frame sculptures—twisted metal lines, mesh, and skeletal forms—as if the entire room is a kinetic art installation made of bent steel wire. The sharp realism of his skin against the angular, airy wire environment creates a powerful visual tension, with realistic directional light casting intricate shadows onto the illustrated metallic framework." \
  "Deepseek Instant" "Realistic Woodworker in Wire-Sculpture Workshop"

queue_job 50 \
  "A photorealistic female astronaut with a clear helmet visor revealing her sharp features, flushed cheeks, and reflective visor rim, wearing a detailed NASA spacesuit with fabric creases and metallic connectors, floats gracefully in zero gravity, one hand reaching toward a control panel. The entire space station interior around her—modules, screens, tubes, floating pens, and the starry viewport—is illustrated in precise technical pen and stippled ink drawing, with cross-hatched shadows, dotted gradients, and paper texture, evoking an architectural blueprint or sci-fi comic. Her vibrant, photographic flesh tones and suit colors stand out against the stark black-and-white ink environment, while realistic volumetric light beams cut through the sketched air, making her feel like a living photograph accidentally pasted into a detailed engraving." \
  "Deepseek Instant" "Photorealistic Astronaut in Pen-Drawn Space Station"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A photorealistic elderly woman in a linen apron and sun-weathered hands kneels among illustrated wildflowers drawn in loose ink and watercolor washes. Her realistic skin texture and fabric wrinkles contrast sharply with the hand-sketched background of wispy pencil trees, crosshatched grass, and watercolor sky washes in soft blues and yellows. Her real hair catches golden hour light while the surrounding garden exists only as delicate pen outlines and splattered paint. She gently touches a sketch-rendered daisy. The composition is striking, the real subject grounded in an intentionally unfinished artistic world." \
  "ERNIE 5.1" "The Real Gardener"

queue_job 52 \
  "A photorealistic Black man in a sharp navy suit plays a real brass saxophone on a stage rendered entirely in expressive charcoal and ink illustration. His detailed skin, fabric stitching, and reflective instrument shine under realistic stage lighting while the background features loose gestural pencil strokes, smudged shadows, and watercolor splashes suggesting a smoky jazz club. Illustrated silhouettes of an audience sit in crosshatched booths. His breath is visible on the cold real brass, his fingers press real keys, all surrounded by rough sketched walls and dripping ink textures." \
  "ERNIE 5.1" "The Jazz Musician"

queue_job 53 \
  "A photorealistic young girl with freckles and a real knitted scarf reaches upward toward illustrated bookshelves drawn in detailed pen-and-ink with watercolor accents. Her realistic skin, eyelashes, and wool texture stand against hand-drawn arched ceilings, crosshatched wooden beams, and loosely painted hanging lanterns in warm amber and teal. Pencil-sketched pages flutter around her real hands as she pulls a volumetrically lit real book from a shelf that exists only as ink stippling and wash. The contrast between her photographic presence and the textured illustrative world feels magical and intentional." \
  "ERNIE 5.1" "The Library Explorer"

queue_job 54 \
  "A photorealistic male cyclist in professional gear with sweat-dampened real skin and a carbon-fiber bike pauses on a ridge surrounded by dramatic illustrated mountain scenery. Loose watercolor washes in deep indigo and burnt sienna form distant peaks while fine ink lines define craggy rock faces and sketched pine trees. His real sunglasses reflect light, his jersey shows fabric weave, his tires have photographic detail. The trail beneath him is a rough graphite pencil path winding through painted valleys. The entire environment feels like an open sketchbook brought to vivid atmospheric life around one real figure." \
  "ERNIE 5.1" "The Mountain Cyclist"

queue_job 55 \
  "A photorealistic middle-aged baker in a flour-dusted white coat stands behind a counter in a fully illustrated Parisian street scene. Her real face shows laugh lines, her hands have visible veins, her apron has authentic stains. The surrounding world is rendered in delicate ink linework and soft pastel watercolor — cobblestones sketched in pen, cafe awnings in loose washes of red and cream, illustrated bicycles leaning against crosshatched walls. A real baguette sits on the counter catching warm natural light while everything else lives as charming hand-drawn artistry, creating an arrestingly vivid contrast." \
  "ERNIE 5.1" "The Street Baker"

# --- LongCat Deep search ---
queue_job 56 \
  "A photorealistic elderly woman with deeply textured skin, wearing an oversized woven cashmere shawl, seated at a mahogany desk. Her hands showing every vein and wrinkle rest on an open leather-bound journal. Soft directional window light illuminates her completely, creating realistic shadows and subsurface scattering in her skin. Meanwhile, the entire room is rendered as a rough pencil sketch—bookshelves, desk, ink bottle, window frame, and floorboards all drawn with visible graphite lines, cross-hatching, shadow shading, and intentional smudges. The contrast is striking and intentional: she is fully three-dimensional and tangible while her environment exists as an incomplete, hand-drawn illustration with visible paper grain and eraser artifacts." \
  "LongCat Deep search" "The Scholar in the Sketch"

queue_job 57 \
  "A hyper-realistic vintage film camera with intricate metal details, leather strap, and dust particles floating in air, sitting on a wooden table. The camera shows every scratch, fingerprint, and lens reflection with photographic precision. Warm studio light creates specular highlights on its brass fittings. Surrounding this real object, the entire setting transforms into an ink and watercolor illustration—the table surface, wall behind, and falling leaves outside a window drawn with loose black ink strokes, watercolor washes bleeding uncontrollably, and splattered ink drops. The camera remains clinically sharp and real while its world dissolves into expressive hand-painted abstraction with visible paper texture and brush marks." \
  "LongCat Deep search" "Camera in the Watercolor Realm"

queue_job 58 \
  "Photorealistic young cellist with sweat on his brow, wearing a crisp white dress shirt with every fabric thread visible, performing passionately. His skin pores, eyelashes, and the shine on his wooden instrument are rendered with exacting photographic detail, lit by a single dramatic spotlight with realistic falloff. The concert hall around him is drawn entirely in pen and ink—rafters, seats, musicians, and curtains created with fine crosshatching, stippling, and flowing ink lines. The contrast is intentionally jarring: the musician and his cello emerge complete and three-dimensional from a world of pure illustration, with visible page grain and ink bleeds where his form meets the drawn architecture." \
  "LongCat Deep search" "Cellist in the Ink Hall"

queue_job 59 \
  "A photorealistic barista with detailed skin texture, wearing a canvas apron, pours latte art into a ceramic cup. Steam rises realistically from the espresso, and every water droplet on her arm is visible. The coffee cup and counter show exact reflections and refractive properties. Everything beyond is rendered in watercolor and colored pencil—the coffee machine, shelves, hanging plants, and storefront window all painted with loose bleeding washes, visible brushstrokes, and colored pencil outlines that dissolve before touching her. The contrast is aesthetic and deliberate: she is a fully realized photograph existing inside a living sketchbook page, with pigment blooms and watercolor bleeds embracing her silhouette." \
  "LongCat Deep search" "Barista in the Watercolor Cafe"

queue_job 60 \
  "Photorealistic astronaut in a pristine white EVA suit, visor reflecting distant stars, floating in zero gravity. The suit displays every stitch, material weave, and life-support detail with exacting realism. Light from a nearby sun creates authentic specular reflections on the visor and realistic shadow blending in the fabric folds. The entire space environment is rendered as pencil sketches—planets, stars, spacecraft, and cosmic dust drawn with soft graphite shading, visible construction lines, and rough erasure marks. The contrast is profound: a tangible human explorer suspended in a universe that exists only as an artist's preliminary drawing, with visible paper texture and charcoal smudges fading into the void." \
  "LongCat Deep search" "Astronaut in the Pencil Cosmos"

echo "✅ All 60 jobs queued in scheduler"
