#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Virtual Reality (photorealistic subjects, unfinished/glitching CGI surroundings)
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+35+-+Virtual+reality
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job 1 \
  "A young couple sits at a small round table in a cozy cafe, sharing a warm smile over steaming cups of coffee, their skin glowing with real photographic detail, fabric of their sweaters showing authentic weave and texture, hair catching natural window light with perfect realism. Behind them the cafe dissolves into unfinished virtual reality: wooden tables fade into gray low-polygon blocks, the far wall breaks apart into glowing blue wireframe mesh, hanging lamps flicker with digital glitch artifacts and scan lines, floor tiles vanish into a checkered UV grid. Sunlight through the window splits into pixelated fragments. Photorealism meets raw simulation, sharp contrast, cinematic depth of field, square composition." \
  "Claude Sonnet 5 medium" "Couple in Cafe VR Glitch"

queue_job 2 \
  "A tired commuter stands at a bus stop, photorealistic skin texture, real denim jacket wrinkles, realistic rain droplets on their glasses, holding a phone with lifelike hand detail, everything about the person fully rendered and convincing. The bus stop shelter behind them is half real half broken simulation: one side shows weathered glass and rusted metal, the other dissolves into translucent wireframe polygons and floating collision boxes. The street beyond glitches between real asphalt and a flat gray untextured plane, distant buildings flicker as low-poly placeholders, streetlights emit corrupted digital light glitch trails. Overcast photographic lighting on the person, unfinished CGI environment, square framing, sharp realism contrast." \
  "Claude Sonnet 5 medium" "Bus Stop Waiting VR Transition"

queue_job 3 \
  "A construction worker in a hard hat and reflective vest stands on a steel beam, muscles tense, sweat glistening realistically on sunlit skin, fabric creases and dust particles rendered with full photographic fidelity, tool belt textures crisp and tangible. The construction site around him breaks into raw simulation, scaffolding transforms into thin glowing wireframe struts, unfinished concrete slabs float as gray untextured cubes, cranes in the distance flicker between photoreal metal and blocky placeholder geometry, sky splits into pixel glitch bands and a visible horizon grid. Bright midday sun on the worker, cold sterile unrendered world around him, dramatic scale, square composition, cinematic contrast." \
  "Claude Sonnet 5 medium" "Construction Worker VR World"

queue_job 4 \
  "A hunter crouches quietly among tall trees, weathered camouflage jacket showing authentic fabric texture, real stubble and skin pores, breath faintly visible in cold air, rifle strap textured with worn leather realism, entirely convincing and human. The forest around him dissolves into incomplete simulation, tree trunks near the edges reduce to flat green wireframe cones, fallen leaves become a repeating low-resolution texture tile, distant fog glitches into scan-line static, sunlight beams fracture into pixelated shafts cutting through unfinished foliage. Ground textures shift between mud detail and gray placeholder polygons. Moody natural lighting on the hunter, eerie unrendered wilderness beyond, square frame, cinematic realism." \
  "Claude Sonnet 5 medium" "Hunter in Glitching Forest"

queue_job 5 \
  "Two tourists relax on a sunny beach, sunscreen sheen visible on realistic skin, swimsuit fabric folds and sand grains rendered with full photographic detail, sunglasses reflecting genuine light, completely lifelike and tangible figures. The beach environment around them fractures into raw virtual construction, ocean waves near the horizon flatten into a shimmering blue wireframe grid, palm trees glitch between lush photoreal leaves and skeletal low-poly frames, distant beach umbrellas dissolve into translucent geometric outlines, sky pixelates into corrupted gradient bands. Sand close to them looks real, further out becomes untextured gray plane. Warm natural sunlight, glitching horizon, square composition, sharp photoreal-to-CGI contrast." \
  "Claude Sonnet 5 medium" "Beach Tourists in Broken Simulation"


# --- Gemini 3.5 Flash ---
queue_job 6 \
  "A close-up photograph of a young couple sitting at a wooden cafe table, laughing. They are rendered with flawless photorealism, showing detailed skin pores, stray hairs, and the soft texture of their cotton shirts. In contrast, the cafe surrounding them is actively deconstructing into a virtual matrix. The coffee cups in their hands shatter into glowing turquoise wireframe lines. The background tables and the barista counter dissolve into low-polygon shapes, revealing a dark, void-like grid underneath. Digital pixelation and chromatic aberration artifacts streak across the edges of the frame, blending sharp, realistic sunlight with raw, glowing neon code." \
  "Gemini 3.5 Flash" "Glitch Cafe Reality"

queue_job 7 \
  "A crisp cinematic shot of a woman in a wool coat waiting at a city bus stop during a rainy evening. Her face, wet hair, and the fabric of her coat are perfectly photorealistic, catching the hyper-realistic reflections of streetlights. However, the bus stop bench she sits on transitions mid-way into a bright green 3D wireframe mesh. The pavement at her feet dissolves into untextured, gray low-poly blocks. The background city buildings are half-rendered silhouettes showing exposed digital structural grids, while erratic digital glitches and horizontal tracking lines tear through the neon signs, exposing the virtual simulation." \
  "Gemini 3.5 Flash" "The Unfinished Commute"

queue_job 8 \
  "A detailed photo of a male hiker standing atop a mountain peak, looking at the horizon. The hiker is entirely photorealistic, with visible sweat on his weathered skin, intricate weaving on his backpack, and realistic shadows cast on his gear. The rocky ground beneath his boots, however, abruptly turns into a stark white grid of polygons. The majestic mountain range in the background is only partially loaded, shifting from realistic snowy peaks into glowing blue wireframe geometry and unmapped digital voids. Subtle digital screen noise and green code fragments flicker across the sky, revealing the synthetic nature of the landscape." \
  "Gemini 3.5 Flash" "Simulated Summit"

queue_job 9 \
  "A sharp, realistic photo of a businessman focused on his laptop at a modern office desk. The man is rendered with high fidelity, showing realistic skin tones, fabric folds on his suit, and a natural expression. The laptop and desk surface under his hands look entirely authentic. However, the office environment around him is fracturing into a virtual environment. The office chairs and neighboring cubicles disintegrate into orange wireframes and untextured low-polygon forms. The back wall bleeds into a digital matrix grid, with horizontal glitch distortion lines running across the fluorescent ceiling lights." \
  "Gemini 3.5 Flash" "Office Grid Breakdown"

queue_job 10 \
  "A crisp, high-detail photograph of a hunter camouflaged in dense woods, aiming a rifle. The hunter's face, the texture of the camouflage gear, and the metallic finish of the rifle are captured with perfect photorealistic clarity. The immediate tree trunk he leans against is highly detailed with real bark textures, but its upper branches dissolve into sharp geometric wireframes. The forest floor behind him abruptly loses texture, turning into a flat grid of gray polygons. Digital glitches, glowing green artifacts, and pixelated distortion fields ripple through the distant trees, breaking the illusion of the natural environment." \
  "Gemini 3.5 Flash" "The Virtual Woods"


# --- ChatGPT ---
queue_job 11 \
  "A young couple sits at a cozy sidewalk cafe, sharing coffee and smiling naturally, both rendered with flawless photorealistic skin, realistic fabrics, subtle facial expressions, and authentic morning sunlight. The wooden table, porcelain cups, and nearby flowers remain fully real, but the surrounding street gradually transforms into an unfinished virtual reality simulation. Buildings dissolve into transparent wire-frame geometry, parked cars become low-polygon meshes, pedestrians flicker with digital glitches, and distant trees alternate between detailed foliage and geometric placeholders. Floating alignment guides, fragmented textures, missing pavement sections, and softly glowing grid overlays reveal the hidden CGI framework while preserving believable cinematic photography and natural depth of field." \
  "ChatGPT" "Morning Coffee Between Two Worlds"

queue_job 12 \
  "A businesswoman waits calmly at a suburban bus stop during golden hour, holding a leather handbag and checking her smartwatch, portrayed with highly realistic skin texture, tailored clothing, natural hair, and convincing photographic lighting. The bus shelter begins as perfectly real but gradually transitions into an incomplete virtual environment. Steel beams become exposed wire-frame structures, advertising posters remain half-rendered, the approaching bus appears partially assembled from low-polygon geometry, and nearby houses fade into simplified meshes. Sidewalk tiles disappear into glowing grid lines, digital artifacts ripple across the horizon, floating geometry markers hover above unfinished objects, and occasional pixel glitches expose the simulation beneath an otherwise believable, cinematic, photo-realistic scene." \
  "ChatGPT" "Waiting for the Bus in a Loading World"

queue_job 13 \
  "A construction engineer wearing a reflective safety vest and helmet studies architectural plans beside coworkers on an active construction site, every person captured with lifelike skin, realistic clothing textures, authentic safety equipment, and natural overcast daylight. Nearby machinery and building materials appear completely real before gradually transitioning into an unfinished virtual reality environment. Tower cranes dissolve into skeletal wire-frame structures, concrete floors become transparent polygon grids, unfinished walls reveal glowing edge geometry, and distant buildings lose textures entirely. Measurement overlays, floating coordinate axes, fragmented scaffolding, missing terrain patches, subtle compression glitches, and partially loaded assets create the unmistakable impression of a massive digital world still rendering around perfectly photorealistic human subjects." \
  "ChatGPT" "Construction Site Rendering in Progress"

queue_job 14 \
  "Two hikers pause on a scenic mountain overlook, wearing realistic outdoor jackets, backpacks, hiking boots, and weathered clothing illuminated by crisp alpine sunlight. Their faces, hands, equipment, and nearby rocks display exceptional photographic realism with convincing textures and natural atmospheric perspective. Beyond them, the breathtaking landscape slowly transforms into an unfinished virtual simulation. Snow-covered peaks convert into low-polygon terrain, forests become wire-frame silhouettes, waterfalls freeze into transparent geometric surfaces, and sections of sky reveal exposed rendering grids. Floating debug indicators, missing texture tiles, digital tearing, polygon transitions, luminous mesh outlines, and occasional visual glitches create a seamless blend between breathtaking nature photography and an incompletely rendered CGI universe." \
  "ChatGPT" "Mountain Trail Beyond Reality"

queue_job 15 \
  "People relax along a beautiful sandy beach during sunset, families walking, children playing, and surfers carrying boards, all portrayed with natural poses, realistic skin tones, detailed clothing, authentic wet sand reflections, and warm cinematic lighting. The foreground remains completely photorealistic while the environment progressively reveals the illusion of virtual reality. Ocean waves transform into angular polygon surfaces, distant boats become skeletal wire-frame models, palm trees lose textures to exposed geometry, and sections of the colorful sky fragment into rendering artifacts. Glowing grid lines emerge beneath the sand, floating calibration markers appear among beach umbrellas, subtle pixel distortions interrupt the horizon, and incomplete CGI assets blend convincingly with an otherwise realistic coastal photograph." \
  "ChatGPT" "Beach Sunset Simulation Error"


# --- Grok fast ---
queue_job 16 \
  "A young couple sitting at a cozy cafe table, laughing and sharing coffee, highly detailed photorealistic faces with natural skin textures, realistic hair, expressive eyes and fabric clothing under warm lighting. The cafe interior starts photorealistic but gradually transitions into unfinished digital space with visible low-poly wireframe models, glowing grid lines and digital glitches on walls and furniture, floating UI elements and partial rendering artifacts in the background, photorealistic foreground subjects contrasting with cyber VR environment, cinematic composition, sharp details." \
  "Grok fast" "Couple in Virtual Cafe"

queue_job 17 \
  "A middle-aged man in casual clothes standing at a city bus stop, checking his watch, ultra photorealistic skin pores, realistic clothing folds and natural lighting. The urban street scene partially dissolves into virtual reality with background buildings showing wireframe structures, low polygon trees and vehicles, digital scan lines and glitch effects distorting the skyline, seamless blend from real to CGI unfinished render, moody atmospheric lighting, detailed foreground character in immersive VR simulation." \
  "Grok fast" "Man Waiting at Bus Stop"

queue_job 18 \
  "A hunter with rifle walking through dense woods, photorealistic detailed face, realistic camouflage gear and skin textures with natural forest lighting. Surrounding trees and foliage start highly realistic but transition into incomplete CGI with visible wireframes, low-poly ground and distant trees, digital artifacts and floating code particles in the air, creating a striking contrast between the fully rendered human and the virtual environment, atmospheric depth, high detail." \
  "Grok fast" "Hunter in Glitchy Forest"

queue_job 19 \
  "Group of tourists taking photos at a scenic mountain overlook, photorealistic faces, detailed hiking clothes and backpacks with realistic sunlight and shadows. Majestic mountain landscape begins photorealistic but fades into unfinished virtual reality with wireframe peaks, low polygon clouds and glitchy horizon, partial rendering errors and digital noise in the distance, breathtaking view with perfect human details against the cyber VR backdrop, epic composition." \
  "Grok fast" "Tourists at Mountain Viewpoint"

queue_job 20 \
  "A professional woman hailing a yellow taxi on a busy city street, highly detailed photorealistic expression, realistic business attire and hair with dynamic urban lighting. The city environment transitions from realistic storefronts to digital wireframe buildings, low-poly cars and pedestrians in the background with glitch effects and matrix-like distortions, strong contrast between fully rendered foreground character and incomplete VR simulation, vibrant city atmosphere." \
  "Grok fast" "Woman Catching Taxi in City"


# --- Copilot Smart ---
queue_job 21 \
  "A young couple sits at a cozy cafe table, sipping coffee with warm sunlight streaming through the window. Their faces, clothing, and gestures are rendered in perfect photo-realism, with natural skin tones and fabric textures. Yet beyond them, the cafe interior begins to dissolve into unfinished CGI: chairs morph into wire-frame outlines, walls fade into low-polygon geometry, and the street outside glitches with digital artifacts. The scene blends everyday realism with surreal virtual reality cues, showing the uncanny transition between a believable world and its incomplete digital construction." \
  "Copilot Smart" "City Cafe in VR"

queue_job 22 \
  "A man waits at a bus stop, his posture casual, smartphone in hand, jacket and jeans captured with lifelike detail. The bus shelter glass reflects him realistically, but the background cityscape flickers with digital glitches: skyscrapers half-rendered, traffic lights reduced to wire-frame models, and pedestrians dissolving into polygon silhouettes. The contrast between his fully photo-realistic presence and the fragmented environment emphasizes the surreal immersion of virtual reality bleeding into daily life." \
  "Copilot Smart" "Bus Stop Glitch Reality"

queue_job 23 \
  "An office worker types at a desk, illuminated by natural light from a nearby window. His hands, keyboard, and clothing are perfectly photo-realistic, with realistic shadows and reflections. Yet the office around him shifts into unfinished CGI: cubicle walls fade into wire-frame grids, computer monitors glitch with pixelated distortions, and ceiling lights hover as low-polygon models. The juxtaposition of realism and digital incompleteness conveys the uncanny sensation of existing inside a virtual simulation." \
  "Copilot Smart" "Office Work in VR"

queue_job 24 \
  "A hunter stands in the forest, bow in hand, his face and clothing rendered with lifelike precision. The leaves closest to him shimmer with realistic detail, but deeper into the woods, trees dissolve into wire-frame trunks, branches glitch into jagged polygons, and the horizon flickers with incomplete rendering. The blending of natural realism with digital fragmentation creates a surreal atmosphere, as though the hunter is caught between reality and simulation." \
  "Copilot Smart" "Hunter in Digital Woods"

queue_job 25 \
  "Tourists relax on a sunny beach, their skin tones, swimsuits, and umbrellas captured in vivid photo-realism. Waves crash with natural detail near the shore, but further out, the ocean becomes a polygon mesh, sky gradients glitch into pixelated bands, and distant figures dissolve into wire-frame outlines. The scene merges the joy of a summer day with the eerie incompleteness of virtual reality, highlighting the fragile boundary between real and simulated worlds." \
  "Copilot Smart" "Beach Reality Distortion"


# --- Mistral Think ---
queue_job 26 \
  "A photo-realistic couple sits at a rustic wooden cafe table, their skin pores, fabric weave, and subtle micro-expressions rendered with ultra-high-definition, cinematic lighting that casts soft shadows. The foreground remains hyper-detailed and lifelike, while the cafe interior behind them gradually degrades into unfinished CGI: walls and furniture dissolve into low-poly meshes, exposed wireframe grids, and occasional flickering digital glitches. The large windows reveal a sprawling cityscape that seamlessly transitions from photorealistic architecture to abstract, half-rendered skyscrapers with floating vertices and fragmented geometry. The scene masterfully captures the warm, intimate moment between the couple against the surreal, digital decay of their surroundings, creating a striking contrast between human realism and virtual artifice in a single, immersive composition." \
  "Mistral Think" "Virtual Cafe Rendezvous"

queue_job 27 \
  "A hyper-realistic person stands at a sleek, modern bus stop, their skin texture, clothing folds, and natural hair rendered with photographic precision under soft, golden daylight. The foreground remains flawlessly detailed and lifelike, while the bus stop structure and urban street behind gradually transition into unfinished CGI: the metal poles, glass panels, and pavement break into low-poly geometry, exposed wireframe grids appear, and subtle digital glitches flicker across surfaces. The background city street dissolves into abstract shapes, half-rendered vehicles with floating vertices, and fragmented pavement that reveals the underlying digital mesh. The scene juxtaposes the perfect, tangible realism of the waiting individual against the increasingly digital, unfinished nature of their environment, creating a surreal, immersive blend of reality and virtual simulation." \
  "Mistral Think" "Digital Bus Stop"

queue_job 28 \
  "A photo-realistic construction worker in a yellow hard hat and work-worn clothes stands on a bustling building site, his skin, sweat, and fabric details captured with ultra-realistic precision under harsh, direct sunlight. The foreground remains sharply detailed and lifelike, while the construction site behind him degrades into unfinished CGI: scaffolding, steel beams, and concrete slabs dissolve into low-poly meshes, exposed wireframe grids emerge, and digital glitches distort the air. The background cityscape transitions from realistic, detailed buildings to abstract, half-rendered structures with floating vertices and fragmented geometry. The scene captures the raw physicality and effort of labor against the surreal digital decay of the environment, blending human realism with virtual artifice in a striking, immersive composition." \
  "Mistral Think" "Construction Site Glitch"

queue_job 29 \
  "A hyper-realistic hunter with a rifle and backpack stands in a dense, misty forest, his weathered skin, beard, and camouflage clothing rendered with lifelike detail under dappled sunlight filtering through the canopy. The foreground is crisp, natural, and hyper-detailed, while the forest behind him gradually dissolves into unfinished CGI: trees, rocks, and foliage break into low-poly geometry, exposed wireframe outlines appear on trunks and leaves, and subtle digital glitches flicker across the landscape. The background mountains transition from photorealistic peaks to abstract, half-rendered forms with floating vertices and fragmented geometry. The scene juxtaposes the raw, untamed realism of the hunter against the increasingly digital, unfinished nature of the wilderness, creating a surreal blend of reality and virtual simulation." \
  "Mistral Think" "Hunter in the Digital Woods"

queue_job 30 \
  "A group of photo-realistic tourists in colorful hiking gear stand on a rocky mountain overlook, their skin, clothing, and expressions rendered with ultra-high-definition detail under bright, clear alpine sunlight. The foreground remains hyper-detailed and lifelike, while the mountain landscape behind them degrades into unfinished CGI: jagged rock formations and winding trails dissolve into low-poly meshes, exposed wireframe grids emerge on distant peaks, and digital glitches distort the sky. The background valley transitions from photorealistic scenery with lush forests and rivers to abstract, half-rendered elements with floating vertices and fragmented geometry. The scene captures the awe and wonder of the natural world against the surreal digital decay of the environment, blending human realism with virtual artifice in a seamless, immersive composition." \
  "Mistral Think" "Mountain Tourists in a Glitching Reality"


# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "A photorealistic couple sitting at a cozy cafe table, holding hands and smiling. The woman wears a real knit sweater, the man a detailed cotton shirt. Their skin textures, hair, and facial expressions are perfectly lifelike with natural cinematic lighting. However, the cafe environment transitions into a virtual reality simulation. Half of the coffee cups and the wooden table dissolve into low-polygon meshes and glowing green wireframes. The background windows and street outside are completely unrendered, showing a dark digital grid with floating binary code and subtle digital glitches. The contrast between the hyper-realistic foreground subjects and the unfinished CGI background highlights the immersive virtual reality experience." \
  "Qwen 3.7 Plus Thinking" "Cafe Couple in Virtual Reality"

queue_job 32 \
  "A highly detailed, photorealistic young man waiting at a bus stop, checking his smartwatch. He wears a realistic denim jacket and leather shoes, with authentic skin pores and natural street lighting reflecting on his face. The scene is a virtual reality simulation. The bus stop bench and the pavement beneath his feet gradually degrade into unfinished CGI, featuring exposed wireframe structures and flat-shaded low-poly geometry. The distant city skyline is partially unrendered, replaced by a glowing neon grid and floating digital artifacts. Subtle pixelation and chromatic aberration glitches affect the far background, emphasizing the boundary between the perfectly rendered human subject and the simulated digital world." \
  "Qwen 3.7 Plus Thinking" "Bus Stop Virtual Reality Simulation"

queue_job 33 \
  "A photorealistic hunter standing in a dense forest, holding a wooden rifle. He wears a textured canvas hunting vest and realistic leather boots. His face shows authentic weathering, with real skin details and natural dappled sunlight filtering through the canopy. The forest environment is a virtual reality construct. The immediate foreground grass and tree trunks transition abruptly into unfinished CGI, revealing glowing wireframe meshes and untextured low-polygon blocks. The deep woods background is completely unrendered, displaying a vast dark void filled with a glowing digital grid, floating geometric shapes, and occasional visual glitches. This stark contrast highlights the photorealistic character inside a simulated digital nature scene." \
  "Qwen 3.7 Plus Thinking" "Virtual Reality Forest Hunter"

queue_job 34 \
  "A photorealistic female office worker typing on a laptop in a modern corporate cubicle. She wears a crisp white blouse with real fabric folds, and her skin has natural subsurface scattering under bright office fluorescent lights. The setting is a virtual reality environment. The sleek office desk and her coffee mug dissolve into unfinished CGI, showing raw wireframe outlines and low-resolution polygonal meshes. The office walls and ceiling are partially unrendered, fading into a dark, glowing digital matrix with floating data nodes and subtle rendering glitches. The hyper-realistic human element sharply contrasts with the degrading, simulated architectural surroundings, perfectly capturing the highly immersive virtual reality theme." \
  "Qwen 3.7 Plus Thinking" "Office Worker Virtual Reality Cubicle"

queue_job 35 \
  "A photorealistic couple walking barefoot on a sandy beach, holding hands and looking at the ocean. The woman wears a flowing cotton dress, the man linen shorts, both with highly detailed skin textures and realistic wind-blown hair. The beach is a virtual reality simulation. The sand beneath their feet and a nearby wooden surfboard transition into unfinished CGI, displaying exposed wireframes and flat-shaded low-poly geometry. The ocean waves and distant horizon are partially unrendered, replaced by a glowing cyan digital grid, floating voxel blocks, and subtle chromatic aberration glitches. The perfectly rendered foreground subjects contrast beautifully with the degrading, simulated coastal background environment, creating a stunning visual." \
  "Qwen 3.7 Plus Thinking" "Virtual Reality Beach Walk"


# --- GLM 5V ---
queue_job 36 \
  "A photorealistic young couple sits at a cozy cafe table, holding hands across steaming coffee cups, their skin showing natural pores and subtle imperfections, fabric textures of their clothes rendered in exquisite detail with realistic folds and soft shadows from warm ambient lighting. Behind them, the cafe interior gradually dissolves into unfinished CGI, walls transitioning into visible wireframe meshes and low-polygon geometry, background patrons appearing as incomplete digital constructs with floating polygon fragments. Digital glitch artifacts streak horizontally across the upper portion of the scene, while the couple remains perfectly sharp and tangible. Holographic grid lines faintly overlay the unfinished areas, revealing the virtual nature of this romantic moment suspended between reality and digital creation." \
  "GLM 5V" "Cafe VR Romance"

queue_job 37 \
  "A photorealistic woman stands at a modern bus shelter checking her phone, her face illuminated by screen glow showing every pore and natural skin texture, wearing a denim jacket with realistic stitching details and weathered fabric appearance. The bus stop structure behind her partially renders into exposed wireframe architecture, metal beams becoming transparent mesh grids, the glass panels fragmenting into low-polygon shards that float in space. Distant city buildings dissolve into blocky unfinished geometry with visible vertex points. Subtle chromatic aberration and pixelation effects creep from the edges toward the center, while scattered digital noise particles drift around the unrendered areas, creating an unsettling contrast between her complete human presence and the broken virtual world surrounding her." \
  "GLM 5V" "Bus Stop Reality Glitch"

queue_job 38 \
  "A photorealistic businessman types intensely on a laptop at a sleek desk, his focused expression captured with cinematic lighting highlighting sweat droplets on his forehead, dress shirt showing precise button details and fabric weave patterns, fingers positioned naturally on keyboard keys. The office environment around him progressively breaks down, walls transforming into wireframe blueprints with floating measurement lines, bookshelves deconstructing into primitive cube shapes, windows revealing void-like black spaces with occasional rendering errors flashing as colorful artifact bursts. His chair and desk maintain solid form while the floor beneath becomes a glowing grid pattern fading into darkness. Holographic interface elements flicker near the incomplete sections, emphasizing the thin boundary between his concentrated work and the collapsing simulation." \
  "GLM 5V" "Office Worker in Digital Void"

queue_job 39 \
  "Photorealistic hikers stand triumphantly on a rocky mountain peak, their hiking gear displaying authentic material properties, breathable jacket fabrics with proper texture, worn boots with dirt and scuff marks, backpack straps with realistic tension against their clothing. Their faces show genuine exhaustion and joy with wind-reddened cheeks and individual hair strands catching sunlight. The breathtaking alpine panorama behind them transitions dramatically from crisp distant peaks into unfinished terrain, mountain slopes becoming low-polygon meshes with visible triangular facets, clouds dissolving into flat textured planes, sky revealing its digital composition as layered gradient bands with occasional wireframe patches. Floating geometry particles drift upward from the unrendered regions while subtle scan-line effects overlay the boundary between real adventurers and their artificial environment." \
  "GLM 5V" "Mountain Summit Virtual Escape"

queue_job 40 \
  "A photorealistic couple walks barefoot along shoreline waves, golden hour lighting creating perfect subsurface scattering on their sun-kissed skin, wet sand clinging realistically to their ankles, flowing summer clothes billowing with accurate physics simulation and translucent fabric properties. The tropical beach paradise surrounding them suffers catastrophic rendering failure, palm trees morphing into skeletal wireframe structures with hanging polygon leaves, ocean waves breaking into jagged low-resolution geometry blocks, distant horizon line exposing its nature as a simple texture plane with visible seams. Color banding artifacts stripe across the sky while floating untextured assets drift through the air like digital debris. The couple's perfect photographic clarity contrasts sharply with the beautiful disaster of their virtual vacation destination falling apart at the seams." \
  "GLM 5V" "Beach Paradise Rendering Error"


# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A couple sits closely at a corner cafe table, sharing coffee and warm laughter. Their skin, clothing, and expressions are hyper-realistic with photographic detail, natural lighting, and subtle digital artifacts flickering on their hands. The cozy cafe interior transitions behind them from photorealistic marble counters and warm Edison bulbs into unfinished CGI, wire-frame chairs, low-polygon shelves, glitching textures, and floating polygon meshes. The boundary between reality and simulation blurs with digital noise and chromatic aberration. Cinematic composition, shallow depth of field, 8K detail, volumetric light rays, mixed media aesthetic, hyper-detailed faces, realistic fabric folds, unreal engine aesthetic, digital decay, virtual reality simulation." \
  "Kimi K2.6 Thinking" "Couple in a Virtual Cafe"

queue_job 42 \
  "A woman waits at a rain-slicked bus stop, checking her watch with a worried expression. Her face, coat, and leather bag are rendered in hyper-realistic photographic detail with natural skin pores, real fabric texture, and cinematic lighting. Behind her, the city street dissolves into unfinished CGI, wire-frame buildings, low-polygon vehicles, glitching traffic lights, and floating geometric meshes. The transition zone shows digital artifacts, chromatic aberration, and pixelated noise. Puddles reflect both photorealistic neon signs and wire-frame structures. Cinematic composition, shallow depth of field, 8K detail, volumetric fog, mixed media aesthetic, hyper-detailed portrait, realistic water droplets, unreal engine aesthetic, digital decay, virtual reality simulation." \
  "Kimi K2.6 Thinking" "Woman at a Virtual Bus Stop"

queue_job 43 \
  "A construction worker takes a lunch break on a steel beam high above the city. His weathered face, dirty safety vest, and calloused hands are hyper-realistic with photographic skin detail, real fabric weave, and natural sunlight. The surrounding skyline transitions into unfinished CGI, wire-frame skyscrapers, low-polygon cranes, glitching scaffolding, and floating polygon meshes. Digital artifacts and chromatic aberration creep across the scene boundary. The worker remains perfectly photorealistic while the city dissolves into virtual wire-frames. Cinematic composition, dramatic sunlight, shallow depth of field, 8K detail, volumetric dust particles, mixed media aesthetic, hyper-detailed portrait, realistic sweat droplets, unreal engine aesthetic, digital decay, virtual reality simulation." \
  "Kimi K2.6 Thinking" "Construction Worker in a Virtual City"

queue_job 44 \
  "A hunter kneels in an autumn forest, examining tracks in the fallen leaves. His camouflage jacket, weathered boots, and focused expression are hyper-realistic with photographic skin detail, real fabric texture, and natural dappled lighting. The surrounding woodland transitions into unfinished CGI, wire-frame trees, low-polygon underbrush, glitching foliage, and floating geometric meshes. Digital artifacts and chromatic aberration spread across the mossy ground. The hunter remains perfectly photorealistic while the forest dissolves into virtual wire-frames. Cinematic composition, shallow depth of field, 8K detail, volumetric morning fog, mixed media aesthetic, hyper-detailed portrait, realistic leaf textures, unreal engine aesthetic, digital decay, virtual reality simulation." \
  "Kimi K2.6 Thinking" "Hunter in a Virtual Forest"

queue_job 45 \
  "A family builds a sandcastle at sunset on a tropical beach. Their sun-kissed skin, wet swimwear, and joyful expressions are hyper-realistic with photographic detail, natural golden hour lighting, and subtle digital glitches on their hands. The ocean and shoreline transition into unfinished CGI, wire-frame waves, low-polygon palm trees, glitching clouds, and floating polygon meshes. Digital artifacts and chromatic aberration wash across the horizon. The family remains perfectly photorealistic while paradise dissolves into virtual wire-frames. Cinematic composition, shallow depth of field, 8K detail, volumetric sea spray, mixed media aesthetic, hyper-detailed faces, realistic water droplets, unreal engine aesthetic, digital decay, virtual reality simulation." \
  "Kimi K2.6 Thinking" "Family on a Virtual Beach"


# --- Deepseek Instant ---
queue_job 46 \
  "A photorealistic couple sits intimately at a small Parisian cafe table, their skin textures, fabric folds, and reflective coffee cups rendered with cinematic photographic detail and natural window light. Behind them, the charming street begins to dissolve into a chaotic digital vortex, buildings collapse into low-poly grey blocks, floating wireframe outlines trace missing rooftops, neon cyan grid lines slice through the air, and pixelated artifacts glitch across the awnings. The barista's arm flickers with temporary rendering errors while the foreground pastries remain perfectly crisp. This seamless blend of tangible human presence and unfinished CGI environment reveals the simulated nature of this memory." \
  "Deepseek Instant" "Virtual Cafe Encounter"

queue_job 47 \
  "A solitary businessman in a sharp suit stands under a transparent shelter at a rainy bus stop, his wet hair, leather shoes, and reflective puddle splash rendered with absolute photographic realism. The bus behind him is only half-formed, a jagged mesh of white wireframes and untextured polygons missing its wheels, while the rainy sky tears open with magenta scanlines and corrupted data blocks. The streetlamp overhead flickers between a solid metal pole and a skeletal outline. The distant cityscape fades into flat shaded proxy geometry. The man's patient expression holds steady, contrasting the frantic digital decay of his surroundings." \
  "Deepseek Instant" "Digital Bus Stop Glitch"

queue_job 48 \
  "A helmeted construction worker grips a heavy drill, his dust-covered face, worn denim jeans, and muddy steel-toe boots captured with hyperrealistic texture and sharp focus. The scaffolding beside him abruptly shifts from solid iron beams to transparent turquoise wireframe meshes, revealing missing bolts and hollow interiors. A crane in the background renders as a low-poly video-game model, its cables glitching into broken zigzag lines. Orange safety cones duplicate and flicker with chromatic aberration. Piles of bricks alternate between photorealistic stone and flat shaded cubes. The worker's sweaty brow stays convincingly human as reality crumbles around him." \
  "Deepseek Instant" "Wireframe Construction Zone"

queue_job 49 \
  "A grizzled hunter in a plaid jacket crouches behind a fallen log, his weathered face, detailed rifle scope, and individual beard hairs rendered with stunning photographic precision under dappled forest light. The massive oak tree beside him starts smooth and textured but its branches degrade into angular low-poly shapes, missing leaves replaced by floating green wireframe dots. The forest floor transitions from real mud and moss to a checkerboard of untextured gray quads. A deer in the distance appears as a flickering silhouette of overlapping transparent polygons. Sunbeams glitch into digital static bands, proving this wilderness is a rendering in progress." \
  "Deepseek Instant" "Unfinished Forest Hunter"

queue_job 50 \
  "Two photorealistic friends lounge on vibrant beach towels, their sun-kissed skin, wet swimsuits, and a half-empty bottle of sunscreen showing flawless reflections and subsurface scattering. The sparkling ocean waves behind them begin to unravel, foam dissolves into pixelated noise, the horizon splits with jagged wireframe grids, and a distant sailboat is merely a collection of rotating unshaded triangles. Seashells scattered nearby flicker between high-res scans and low-poly placeholders. The blue sky suddenly reveals a checkerboard of missing texture patches. The friends laugh naturally, completely unaware or ignoring the digital breakdown cascading across their simulated paradise." \
  "Deepseek Instant" "Pixelated Beach Afternoon"


# --- ERNIE 5.1 ---
queue_job 51 \
  "A photo-realistic couple sitting at a small Parisian cafe table, the woman laughing naturally with visible skin pores and delicate fabric texture on her linen blouse, warm golden hour light on their faces. Behind them the cafe interior seamlessly transitions from photorealistic brick walls into low-polygon geometric shapes, unfinished wire-frame chairs floating without textures, digital glitch artifacts tearing through the ceiling, holographic grid lines crossing the background. The wooden table beneath their hands remains fully rendered with realistic grain and coffee cup reflections while the far wall dissolves into bare CGI mesh and floating vertex points." \
  "ERNIE 5.1" "Cafe Glitch Reality"

queue_job 52 \
  "A photo-realistic young man in a denim jacket waiting at a bus stop bench, natural skin detail and real fabric stitching visible, overcast soft daylight illuminating his face with subtle shadows. The bench he sits on is fully rendered wood and metal but behind him the street scene fragments, buildings shift from realistic brick into low-poly wire-frame structures, the road surface glitches with pixelated cracks and floating polygon shards, digital distortion waves ripple through the sky, trees become untextured 3D mesh columns. Neon data streams overlay the fractured background while his figure remains perfectly photographic and lifelike." \
  "ERNIE 5.1" "Bus Stop Digital Fracture"

queue_job 53 \
  "A photo-realistic woman in a tailored blazer working at a modern office desk, real skin texture and precise fabric weave on her clothing, soft fluorescent lighting casting natural shadows across her focused expression. Her desk and keyboard are fully detailed but the office behind her progressively unravels, cubicles dissolve into wire-frame grids, ceiling tiles become exposed polygon meshes, windows show only digital void with floating vertex points, glitch lines slice through the background walls. Holographic UI elements flicker around her while the rest of the room transitions into unfinished CGI geometry and bare render scaffolding." \
  "ERNIE 5.1" "Office Rendering Error"

queue_job 54 \
  "A photo-realistic hunter in camouflage gear crouching beside a tree in a forest, detailed skin with dirt smudges and realistic fabric texture on his jacket, dappled sunlight filtering through leaves onto his weathered face. The tree trunk and ground beneath him are fully rendered with bark detail and moss but surrounding forest fades dramatically, nearby trees become low-polygon shapes with visible wire-frame edges, distant mountains dissolve into digital mesh, the sky glitches with chromatic aberration and floating polygon fragments. His rifle and boots remain photographic while nature around him transitions into bare CGI scaffolding and data artifacts." \
  "ERNIE 5.1" "Hunter in the Unrendered Woods"

queue_job 55 \
  "A photo-realistic tourist family walking along a sandy beach, detailed skin tones and real swimwear fabric with water droplets, bright tropical sunlight creating natural highlights and shadows on their bodies. The sand beneath their feet and nearby waves are fully rendered but the beach scene behind them breaks apart, palm trees become untextured wire-frame trunks, the ocean horizon dissolves into low-poly water planes with visible mesh edges, distant coastline fragments into floating geometric shards, digital glitch bands cut across the sky. Their footprints in the sand stay photorealistic while everything beyond them collapses into unfinished virtual geometry." \
  "ERNIE 5.1" "Beach Simulation Breakdown"


# --- LongCat Deep search ---
queue_job 56 \
  "A young couple sits at an outdoor Parisian cafe, the woman wearing a light summer dress with delicate floral fabric textures and the man in a crisp linen shirt, both rendered with photorealistic skin pores, natural lighting, and true-to-life depth of field. Their coffee cups and saucers show authentic ceramic glaze reflections. However, the cafe chairs behind them dissolve into low-poly wireframe meshes with visible triangular facets, while the cobblestone street transitions from photorealistic stone textures into unfinished blue grid lines and floating digital artifacts. The background Haussmann buildings flicker between architectural realism and jagged polygon fragments, with data streams and chromatic aberration glitching across the scene, revealing the virtual simulation beneath the surface reality." \
  "LongCat Deep search" "VR Cafe Glitch"

queue_job 57 \
  "A businessman in a tailored wool overcoat waits at a rainy bus stop, his face showing individual beard stubble, realistic skin texture under the overcast sky, and authentic fabric wrinkles on his coat with water droplets beading on the wool. His leather briefcase displays genuine stitching detail and metallic reflections. Yet the bus shelter behind him is half-rendered, with glass panels floating as translucent blue wireframe outlines and the metal frame appearing as unfinished CGI with missing textures. The wet asphalt road transitions from photorealistic reflections to glowing green grid coordinates, while digital corruption artifacts and scanning lines flicker through the streetlamp posts and the approaching bus exists as a low-poly silhouette with visible edge lines, exposing the incomplete virtual environment." \
  "LongCat Deep search" "Digital Bus Stop"

queue_job 58 \
  "A seasoned hunter stands in a misty forest clearing, wearing a camouflage jacket with authentic fabric weave, mud stains, and genuine leather boot texture. His face shows realistic weathered skin with wrinkles and a trimmed beard, holding a vintage rifle with authentic wood grain and metallic reflections. The ground beneath his boots is photorealistic with detailed fallen leaves and damp soil. However, the surrounding pine trees dissolve into low-poly geometric shapes with jagged wireframe edges and flat-shaded green polygons. The mist transforms into pixelated fog and digital static, while distant mountains appear as unfinished CGI meshes with visible topology lines. Glitch artifacts and RGB split effects ripple through the canopy, with data fragments floating between organic branches and the simulation's incomplete rendering." \
  "LongCat Deep search" "Pixelated Hunter"

queue_job 59 \
  "A female architect in a white hard hat and safety vest stands at a construction site, her face photorealistic with natural makeup, realistic skin pores, and authentic fabric tension on her hi-vis gear. She holds blueprints with legible ink lines and paper texture. The dirt beneath her boots shows realistic soil particles and tire tracks. Yet the construction equipment behind her is half-rendered, cranes appear as wireframe skeletons with visible edge loops, concrete barriers flicker between solid surfaces and transparent blue mesh, and the building skeleton transitions from rebar reality to glowing green blueprint lines. Digital glitches fragment the scaffolding into floating polygon shards, with chromatic aberration and data moshing revealing the virtual world's incomplete construction state." \
  "LongCat Deep search" "Virtual Construction"

queue_job 60 \
  "Two tourists stand at a mountain summit viewpoint at golden hour, wearing outdoor gear with realistic fabric textures, down jacket puffiness, and authentic backpack straps showing stress marks. Their faces show natural wind-flushed skin and detailed hair strands catching the sunset light, with cameras hanging from their necks displaying real metallic and plastic reflections. The rocky ledge they stand on is photorealistic with detailed stone texture. However, the mountain landscape behind them transitions progressively from realistic peaks to low-poly wireframe geometry, with triangular facets replacing natural contours. The sky flickers between photographic clouds and pixelated blue screen, while digital artifacts and wireframe grids spread across the valley like a virus, exposing the simulation's incomplete rendering of the natural world." \
  "LongCat Deep search" "Glitch Summit"

echo "✅ All 60 jobs queued in scheduler"
