#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Flat illustration style — simple shapes, flat solid color blocks,
#        limited palette, no texture/gradients/shading
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+37+-+Flat+art
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "Flat illustration of a woman pouring coffee in a sunlit kitchen, rendered in simple geometric shapes with no texture or gradients. Warm palette of terracotta, cream, and mustard yellow dominates the scene, with soft sage green accents on potted plants. Bold flat shapes define her robe, the mug, and countertop objects, using clean vector-style outlines. Shading is implied only through adjacent color blocks, never blended. Composition is centered and balanced for a square canvas, with generous negative space around the figure. Minimalist background patterns suggest tile and window light without detail. Style evokes modern editorial illustration, playful, calm, and inviting, with confident shape language and limited color count throughout the entire image." \
  "Claude Sonnet 5 medium" "Morning Coffee Ritual"

queue_job  2 \
  "Flat illustration of a lone hiker standing atop a mountain ridge, arms raised toward a setting sun. Bold flat color blocks in dusty orange, deep purple, and teal build layered mountain silhouettes without gradients or texture. The hiker is reduced to simple geometric forms, minimal facial detail, backpack rendered as a single flat shape. Sun is a solid circle with soft radiating flat rays. Depth communicated only through color layering and overlapping shapes, no shading. Composition centered for square format, symmetrical mountain ranges framing the figure. Style is clean, poster-like, reminiscent of modern travel illustration, confident linework, limited five-color palette, calm and inspiring mood throughout the entire scene." \
  "Claude Sonnet 5 medium" "Mountain Hiker at Sunset"

queue_job  3 \
  "Flat illustration of an orange tabby cat curled asleep on a windowsill, bathed in afternoon light. Simple rounded flat shapes form the cat's body, no fur texture, just solid color blocks in warm orange and cream. Window frame rendered in flat navy blue, potted plant beside cat in flat olive green with simple leaf shapes. Outside view shows a minimal flat cityscape in soft pink and lavender tones. No shading or gradients, dimension suggested only through color contrast between adjacent shapes. Square composition centered on cat, balanced negative space. Style is cozy, modern children's-book illustration, clean confident outlines, limited six-color palette, gentle and peaceful overall mood." \
  "Claude Sonnet 5 medium" "Cat Napping on Windowsill"

queue_job  4 \
  "Flat illustration of a colorful fruit stall at an outdoor farmers market, vendor standing behind neatly arranged produce. Flat geometric shapes represent apples, oranges, and grapes in bold red, orange, and purple, arranged in simple repeating patterns. Vendor rendered with minimal features, flat apron in mustard yellow. Striped awning above in flat teal and cream stripes. No texture or gradient anywhere, dimension shown only through flat color layering and shape overlap. Square composition balanced with stall centered, background kept minimal and softly toned. Style is cheerful modern flat design, clean vector outlines, limited warm palette, evoking community, freshness, and simple everyday joy throughout the entire illustration." \
  "Claude Sonnet 5 medium" "Farmers Market Stall"

queue_job  5 \
  "Flat illustration of an astronaut floating weightlessly against a deep navy space background dotted with simple flat stars. Astronaut suit rendered in flat white and red geometric shapes, helmet a single flat circle with a small reflective highlight shape. Earth appears small in the corner as a flat blue and green circle, continents simplified to basic shapes. No gradients, shading, or texture anywhere, dimension implied purely through flat color contrast. Composition centered for square canvas, astronaut floating diagonally with generous negative space of stars around them. Style is modern minimalist sci-fi illustration, bold confident outlines, limited five-color palette, evoking wonder, stillness, and quiet exploration throughout the scene." \
  "Claude Sonnet 5 medium" "Astronaut Floating in Space"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A minimalist flat vector illustration of a friendly astronaut and a quirky alien sharing a cup of tea on a small, perfectly curved crescent moon. The scene uses incredibly simple geometric shapes and crisp, clean outlines with no gradients, shadows, or textures. The background is a solid deep indigo sky dotted with simple, uniform yellow stars. The figures are rendered in flat blocks of solid pastel pink, soft teal, and vibrant mustard yellow color. There is a complete absence of depth or three-dimensional shading, emphasizing a charming, two-dimensional graphic design quality. The entire composition relies strictly on clean, sharp lines and a highly restricted color palette." \
  "Gemini 3.5 Flash" "Cosmic Tea Party"

queue_job  7 \
  "A clean flat illustration of a small, cozy A-frame cabin nestled deep within a dense forest of highly simplified, geometric pine trees. The scene depicts a gentle rain, represented by uniform, diagonal white lines falling against a solid, muted grey-blue sky. The cabin is constructed from basic triangular and rectangular shapes in warm orange and cream colors, with a glowing yellow window. There are absolutely no textures, complex shading, or realistic details, relying entirely on flat, solid color blocks to convey form. The entire composition is incredibly minimalist and two-dimensional, using a limited color palette of forest green, burnt orange, charcoal, and soft cream." \
  "Gemini 3.5 Flash" "Cozy Cabin Rain"

queue_job  8 \
  "A stylized flat vector illustration of a sleepy ginger cat curled up on a minimalist bookshelf surrounded by potted houseplants. Each book, leaf, and ceramic pot is reduced to its most basic, blocky geometric shape with clean outlines and zero texture. The background is a solid, clean cream wall with no shadows or depth. The color palette is strictly limited to bold, solid areas of coral orange, deep navy blue, mint green, and mustard yellow. There is no shading, gradients, or three-dimensional modeling, resulting in a completely flat, two-dimensional graphic design aesthetic that emphasizes simple forms and clean negative space." \
  "Gemini 3.5 Flash" "Cat on a Bookshelf"

queue_job  9 \
  "A minimalist flat illustration of a lone camel standing gracefully beside a single, highly stylized palm tree in a quiet desert. The landscape consists of smooth, curved layers representing sand dunes, rendered in flat blocks of terracotta and dusty pink. A giant, perfect circle represents a pale yellow sun in a solid, light sand-colored sky. The palm tree features simplified, geometric fronds in solid sage green with no individual leaf details or shading. The entire graphic is completely devoid of gradients, textures, shadows, or depth, presenting a purely two-dimensional composition with clean, sharp edges and a highly restrained, harmonious color palette." \
  "Gemini 3.5 Flash" "Desert Oasis"

queue_job 10 \
  "A dynamic flat vector illustration of a person riding a classic bicycle through a minimalist cityscape. The buildings in the background are represented by simple, overlapping rectangular blocks of solid color with uniform square windows. The cyclist and the bicycle are constructed from basic geometric shapes and clean, crisp lines, with no realistic details or textures. The sky is a solid, unshaded soft peach, while the city elements use bold blocks of royal blue, bright red, and clean white. The entire image has absolutely no three-dimensional depth, gradients, or shadows, creating a striking, two-dimensional graphic poster art style." \
  "Gemini 3.5 Flash" "Biking Through the City"

# --- ChatGPT ---
queue_job 11 \
  "A clean flat illustration of a cheerful cyclist riding through a modern city during a bright morning commute. Buildings are simplified into geometric rectangles, trees become rounded shapes, and clouds appear as smooth white silhouettes against a clear blue sky. Use a restrained palette of teal, coral, mustard, ivory, charcoal, and muted green with crisp vector-like edges. Eliminate realistic textures, gradients, and detailed shadows, relying instead on solid color blocks and simple overlapping forms to suggest depth. The composition is balanced, spacious, optimistic, and visually readable, emphasizing sustainable urban living through bold shapes, clear negative space, playful proportions, and harmonious modern graphic design." \
  "ChatGPT" "Minimalist Bicycle Commute"

queue_job 12 \
  "A charming flat illustration of a peaceful reading nook beside a large window overlooking a quiet garden. A comfortable armchair, stacked books, a steaming cup of tea, leafy houseplants, and a sleeping cat are rendered with simple geometric shapes and solid fills. Employ a limited palette of warm beige, olive green, terracotta, soft navy, cream, and golden yellow. Avoid textures, realistic lighting, or detailed shading, allowing color relationships and simplified forms to define every object. Maintain generous negative space and clean vector aesthetics while creating a calm, welcoming atmosphere that celebrates relaxation, comfort, mindfulness, and everyday happiness through elegant minimalist illustration." \
  "ChatGPT" "Cozy Reading Corner"

queue_job 13 \
  "A vibrant flat illustration showing a colorful underwater ecosystem filled with graceful sea turtles, tropical fish, coral formations, seaweed, and gentle ocean currents. Construct every element using simplified organic shapes with clean outlines or crisp edge separation. Use a carefully limited palette of turquoise, deep blue, coral orange, seafoam green, sunny yellow, and white. Skip realistic textures, reflections, bubbles, and volumetric lighting, relying instead on overlapping color fields to organize the composition. The scene feels lively yet uncluttered, balancing marine biodiversity with modern graphic simplicity, creating a cheerful educational poster aesthetic that highlights environmental appreciation through bold, accessible visual storytelling." \
  "ChatGPT" "Ocean Wildlife Harmony"

queue_job 14 \
  "A joyful flat illustration depicting families enjoying a colorful kite festival across a wide grassy park beneath a bright open sky. People are simplified into expressive silhouettes with friendly proportions while kites become bold geometric diamonds, circles, and playful abstract forms floating above. Apply a limited palette featuring sky blue, crimson, mustard, emerald, white, and dark slate. Exclude textures, realistic clouds, and detailed facial features, emphasizing clean shapes, consistent solid colors, and carefully arranged negative space. The composition communicates celebration, movement, and community through rhythmic placement of colorful elements, creating an energetic contemporary vector illustration with timeless graphic appeal and optimistic visual clarity." \
  "ChatGPT" "Festival of Kites"

queue_job 15 \
  "A serene flat illustration featuring a cozy wooden cabin surrounded by pine forests and distant mountains, with visual hints of all four seasons integrated into one harmonious landscape. Blossoming trees, green meadows, autumn foliage, and snowy peaks appear in clearly separated simplified sections. Use flat geometric forms and a restrained palette of forest green, burnt orange, icy blue, cream, brown, and muted lavender. Avoid texture, realistic perspective, heavy gradients, or complex shadows, instead expressing depth through layered silhouettes and contrasting color blocks. The balanced composition celebrates nature's changing rhythms with clean modern design, elegant minimalism, and inviting visual harmony suitable for editorial or poster illustration." \
  "ChatGPT" "Mountain Cabin Seasons"

# --- Grok fast ---
queue_job 16 \
  "A charming flat illustration of a cozy wooden cabin nestled among stylized pine trees in a peaceful forest clearing. The cabin features simple geometric forms with a warm terracotta roof, beige walls, and rectangular windows glowing with soft yellow light. Flat green triangular tree canopies and slender brown trunks surround it. A gentle winding path of earthy tones leads to the front door. Above, a clear blue sky with a few fluffy white clouds and a bright yellow sun. Limited color palette of greens, browns, blues, and warm yellows. Clean bold outlines, no textures or shading, minimal depth, vibrant yet simple composition emphasizing harmony and tranquility in flat design aesthetic." \
  "Grok fast" "Cozy Forest Cabin in Flat Style"

queue_job 17 \
  "Flat illustration of a bustling city street market at golden hour. Simple geometric buildings with colorful facades line the scene, featuring rectangular windows and flat rooftops in pastel pinks, blues, and yellows. Vendor stalls with striped awnings display fresh fruits and flowers in bold solid colors. Stylized people as simplified human forms walk along the street carrying shopping bags. A few bicycles and market signs add playful details. Warm orange sky with flat sun rays. Limited vibrant palette of primary and pastel colors. Sharp clean lines, no gradients or textures, emphasizing energy and community in a charming minimalist flat art style." \
  "Grok fast" "Vibrant City Street Market"

queue_job 18 \
  "A delightful flat illustration depicting a vibrant underwater coral reef scene. Stylized coral formations in simple rounded and branching shapes glow in bright pinks, oranges, and purples. Schools of colorful fish with basic oval bodies and fin details swim gracefully among the corals. A gentle sea turtle with smooth shell patterns glides nearby. Bubbles rise as flat white circles. Deep blue water background with lighter gradients suggested by color blocks. Seaweed sways in minimal wavy forms. Limited cheerful aquatic color palette. Bold black outlines, completely flat surfaces, no shading or realistic depth, capturing wonder and simplicity." \
  "Grok fast" "Playful Underwater Coral Reef"

queue_job 19 \
  "Flat illustration of a serene mountain lake at dawn. Majestic triangular mountain peaks in layered shades of cool blues and grays rise in the background. A perfectly still lake reflects the mountains using flat color mirroring. Simple evergreen trees with geometric foliage dot the lakeshore in rich greens. A small wooden dock extends into the water with minimal details. Soft pink and orange sunrise sky with flat circular sun. Limited calming palette of blues, greens, earth tones, and pastels. Clean precise lines throughout, no textures, ignoring perspective depth for pure two-dimensional harmony and peaceful atmosphere." \
  "Grok fast" "Serene Mountain Lake Landscape"

queue_job 20 \
  "Whimsical flat illustration of a cheerful garden tea party. A round table with striped tablecloth holds a simple teapot, cups, and plates of colorful pastries in bold shapes. Stylized flowers with circular petals and leaves in vibrant reds, yellows, and purples bloom abundantly around the scene. Two friendly characters in minimal clothing sit on benches enjoying tea. Butterflies flutter as flat winged forms. Lush grass and a picket fence in soft greens complete the setting. Bright sunny sky. Limited joyful spring color palette. Sharp outlines, solid color fills only, no shading or details, evoking pure delight and simplicity." \
  "Grok fast" "Whimsical Garden Tea Party"

# --- Copilot Smart ---
queue_job 21 \
  "A flat illustration of a modern city skyline, simplified into geometric shapes and bold blocks of color. Tall buildings are reduced to rectangles and trapezoids, with windows represented by minimal lines or dots. The palette is limited to three or four harmonious tones, such as muted blues, warm oranges, and soft grays. No shading or gradients are used, only flat areas of color. The sky is a single solid hue, with a stylized sun or moon as a circle. The composition emphasizes balance and clarity, evoking a clean, minimalist aesthetic that highlights the essence of urban life without unnecessary detail." \
  "Copilot Smart" "City Skyline in Flat Style"

queue_job 22 \
  "A flat illustration of a serene nature scene, featuring rolling hills, a river, and a few stylized trees. Each element is reduced to simple shapes: the hills as curved blocks of green, the river as a flowing blue stripe, and the trees as triangles or circles atop straight trunks. The color palette is limited to earthy greens, blues, and browns, with no shading or texture. The sky is a flat pastel tone, with a sun or cloud depicted as a simple circle or oval. The overall composition conveys tranquility and simplicity, focusing on pure form and color rather than detail." \
  "Copilot Smart" "Minimalist Nature Scene"

queue_job 23 \
  "A flat illustration depicting a group of people walking together, reduced to simple silhouettes and geometric shapes. Faces are minimal, with only dots or lines for eyes and mouths. Clothing is represented by bold blocks of color, with no shading or folds. The palette is limited to four or five contrasting tones, such as red, yellow, blue, and black. The background is a single flat color, allowing the figures to stand out. The composition emphasizes diversity and movement, capturing the essence of human interaction in a clean, modern style." \
  "Copilot Smart" "Flat Illustration of People"

queue_job 24 \
  "A flat illustration of an abstract landscape, where mountains, rivers, and sky are reduced to overlapping geometric shapes. Triangles represent mountains, rectangles form plains, and circles suggest the sun. The palette is limited to complementary colors, such as teal, coral, and mustard. No gradients or textures are used, only solid blocks of color. The composition is balanced and harmonious, with each shape carefully placed to create rhythm and flow. The artwork conveys a sense of place without literal detail, focusing on the beauty of form and color." \
  "Copilot Smart" "Abstract Flat Landscape"

queue_job 25 \
  "A flat illustration featuring a group of animals, such as birds, cats, or fish, simplified into basic shapes. Each animal is reduced to circles, triangles, and rectangles, with minimal lines for eyes or tails. The palette is limited to cheerful tones like orange, blue, and green, with no shading or texture. The background is a single flat color, ensuring clarity and focus on the animals. The composition is playful and balanced, evoking a sense of charm and whimsy while staying true to the flat illustration style." \
  "Copilot Smart" "Flat Illustration of Animals"

# --- Mistral Think ---
queue_job 26 \
  "A flat illustration of a modern cityscape at dusk, featuring geometric buildings with clean lines and block colors. The sky is a gradient of soft pastel hues, transitioning from peach to lavender. The buildings are simplified into basic shapes like rectangles and squares, with no shading or texture. Windows are represented as small, evenly spaced dots or squares. The color palette is limited to 5-6 muted tones, emphasizing simplicity and minimalism. The scene is devoid of depth, with all elements appearing on a single plane." \
  "Mistral Think" "Minimalist Flat Cityscape"

queue_job 27 \
  "A flat illustration inspired by vintage travel posters, depicting a stylized mountain range with a bright, sunny sky. The mountains are reduced to triangular and trapezoidal shapes, filled with solid, vibrant colors like teal, mustard, and rust. The sun is a simple circle with radiating lines, and the sky is a single, uniform shade of azure. The foreground features a minimalist train or car, also in flat colors, traveling along a single-line road. The composition is balanced, with a limited color palette of 6-7 bold, retro-inspired tones." \
  "Mistral Think" "Vintage Flat Travel Poster"

queue_job 28 \
  "A flat illustration of a lush botanical garden, featuring stylized plants and flowers. Each plant is reduced to simple, geometric shapes—circles for flowers, ovals for leaves, and rectangles for stems. The colors are flat and vibrant, with a palette limited to 5-6 bright, nature-inspired tones like emerald green, coral, and buttercup yellow. The background is a single, solid color, and there is no shading or depth. The arrangement is symmetrical, with plants evenly spaced and aligned." \
  "Mistral Think" "Flat Botanical Garden"

queue_job 29 \
  "A flat illustration of a whimsical space scene, featuring a simplified rocket ship, planets, and stars. The rocket is a combination of basic shapes—rectangles, triangles, and circles—filled with solid, bold colors like crimson, navy, and gold. The planets are perfect circles with flat, gradient-free colors, and the stars are small, uniform dots or simple geometric shapes. The background is a deep, solid black or dark blue, with no texture or shading. The color palette is limited to 6-7 cosmic-inspired tones." \
  "Mistral Think" "Flat Space Exploration"

queue_job 30 \
  "A flat illustration of an underwater scene, featuring stylized fish, coral, and seaweed. The fish are simplified into basic shapes like ovals, triangles, and rectangles, filled with solid, bright colors such as turquoise, orange, and magenta. The coral and seaweed are represented as abstract, geometric forms with no texture or depth. The background is a single, solid shade of light blue or aquamarine. The color palette is limited to 5-6 vibrant, ocean-inspired tones, and the entire scene appears on a single, flat plane." \
  "Mistral Think" "Flat Ocean Life"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "Flat illustration of a cozy corner cafe interior. Simple geometric shapes form the tables, chairs, and coffee counter. Solid, vibrant colors with a limited palette of warm terracotta, mustard yellow, and soft teal. No textures, no gradients, and minimal shading. Clean, crisp outlines define the espresso machine, hanging pendant lights, and a steaming coffee cup. A small potted plant sits on the counter. The composition is balanced and modern, emphasizing two-dimensional forms and flat areas of color. The overall aesthetic is minimalist, cheerful, and highly stylized, perfectly capturing the essence of modern vector art and clean digital illustration without any realistic details or complex depth." \
  "Qwen 3.7 Plus Tinking" "Cozy Corner Cafe"

queue_job 32 \
  "Flat illustration of a retro astronaut floating in deep space. The character is constructed from simple, bold geometric shapes with a chunky, stylized spacesuit. The background features flat, solid-colored planets and stars in a restricted palette of deep navy, bright coral, and pale yellow. Absolutely no textures, gradients, or realistic shading. Clean, sharp vector lines outline the helmet visor and floating tools. The design relies entirely on variations in color and shape to create a sense of form. The composition is dynamic yet strictly two-dimensional, embodying the core principles of minimalist flat design, modern digital art, and simplified graphic illustration with a playful, nostalgic vibe." \
  "Qwen 3.7 Plus Tinking" "Retro Space Explorer"

queue_job 33 \
  "Flat illustration of a bustling urban cityscape at sunset. Buildings are represented by simple, overlapping rectangular forms and basic geometric silhouettes. The scene uses a strict, limited color palette of muted purples, soft oranges, and dark slate blues. There are no textures, no gradients, and no complex shadows. Windows are depicted as simple grids of solid lighter colors. A few stylized, flat clouds float in the sky. The artwork completely ignores realistic depth, relying on flat layers of color and clean, crisp edges to define the architecture. The final image is a highly stylized, modern vector graphic that captures the energy of a city through pure, simplified, two-dimensional shapes." \
  "Qwen 3.7 Plus Tinking" "Minimalist Urban Skyline"

queue_job 34 \
  "Flat illustration of a curious red fox sitting in a stylized forest. The fox is composed of simple, angular geometric shapes, emphasizing clean lines and flat areas of vibrant orange, white, and dark brown. The surrounding trees are formed by basic triangular and circular forms in solid shades of emerald green and forest teal. The artwork features absolutely no textures, fur details, or realistic shading. Depth is suggested solely through overlapping flat shapes and slight color variations. The limited color palette and minimalist approach create a crisp, modern vector aesthetic. The composition is perfectly balanced, highlighting the beauty of simplified, two-dimensional graphic design and clean digital illustration." \
  "Qwen 3.7 Plus Tinking" "Geometric Forest Fox"

queue_job 35 \
  "Flat illustration of a modern creative workspace desk. The scene features a laptop, a steaming mug, a desk lamp, and scattered notebooks, all constructed from basic geometric shapes. The color palette is limited and harmonious, utilizing soft pastels like mint green, blush pink, and light grey. There are no textures, no wood grains, and no realistic shadows. Clean, uniform outlines define each object. The composition relies entirely on flat areas of solid color and simple forms to convey the items. The artwork embodies the minimalist flat design style, prioritizing simplicity, clarity, and a two-dimensional aesthetic over realistic details, resulting in a crisp, cheerful, and highly stylized vector graphic." \
  "Qwen 3.7 Plus Tinking" "Modern Creative Workspace"

# --- GLM 5V ---
queue_job 36 \
  "A serene mountain landscape at sunrise rendered in clean flat illustration style with bold geometric shapes and solid color blocks without gradients or textures. Rolling mountains layered in varying shades of teal, coral, and lavender create depth through color variation rather than shadow. A large circular sun in warm golden yellow sits in the upper right corner above stylized triangular peaks. Minimalist pine trees in deep forest green dot the foreground as simple triangular forms. The sky transitions from soft peach near the horizon to pale blue at the top using distinct horizontal bands of flat color. Small white clouds appear as perfect circles and ovals scattered across the sky. Clean vector-style edges, no outlines, limited harmonious palette, modern minimalist aesthetic, professional graphic design quality." \
  "GLM 5V" "Mountain Sunrise Landscape"

queue_job 37 \
  "A warm inviting coffee shop interior illustrated in contemporary flat design style featuring simplified geometric furniture and bold solid colors. Round tables in mustard yellow and terracotta orange sit beneath pendant lights shaped as basic cylinders hanging from a cream-colored ceiling. Barista counter in deep navy blue spans the background with coffee equipment reduced to essential rectangular and circular shapes. Large arched windows reveal abstract city buildings in muted sage green and dusty rose outside. Wooden floor shown as parallel horizontal lines in warm brown tones. Potted plants with oversized round leaves in fresh mint green add organic elements. Customers depicted as minimalist silhouettes holding simple cup shapes. No textures, no gradients, crisp edges, cohesive earthy color palette, modern editorial illustration feel." \
  "GLM 5V" "Cozy Coffee Shop Interior"

queue_job 38 \
  "A dynamic abstract geometric composition in pure flat illustration style consisting entirely of overlapping basic shapes with vibrant solid fill colors. Large circles, triangles, rectangles, and hexagons arranged in balanced asymmetrical layout across the canvas. Color palette features electric blue, hot magenta, sunny yellow, lime green, and coral red creating energetic visual rhythm. Each shape maintains complete opacity with sharp clean intersections where forms overlap. Thin white gaps separate adjacent elements enhancing the graphic poster-like quality. Small accent dots and diagonal lines add movement and interest without introducing dimension. Background is solid charcoal gray providing strong contrast. Absolutely no gradients, shadows, bevels, or texture effects anywhere. Vector art aesthetic, Swiss design influence, bold modernist approach, suitable for contemporary branding or digital media graphics." \
  "GLM 5V" "Abstract Geometric Composition"

queue_job 39 \
  "A futuristic smart city skyline depicted in sleek flat illustration style with streamlined architectural forms and a cool-toned limited palette. Skyscrapers rendered as tall rectangles with subtle variations in height, colored in gradients of steel blue, slate gray, and silver-white using only flat color blocks not actual gradients. Circular windows appear as repeating grid patterns on building facades. Floating transportation pods shown as elongated capsules in bright cyan and electric purple moving between structures. Wind turbines with three-blade propeller designs in mint green rise above rooftops. Digital network connections represented by thin dotted lines connecting various points across the scene. Small human figures as simple stick-like forms walk on elevated pedestrian paths. Clean minimalist aesthetic, no atmospheric perspective, tech-forward mood, corporate presentation quality, infographic-inspired visual language." \
  "GLM 5V" "Futuristic Smart City Skyline"

queue_job 40 \
  "A charming gathering of forest animals illustrated in playful flat design style with adorable simplified characters and nature elements. A friendly brown bear with perfectly round ears sits beside a wise owl with large circular eyes, both composed of smooth curved shapes and solid color fills. A small fox in burnt orange with an oversized fluffy tail curls nearby while a tiny rabbit in soft gray peeks from behind a mushroom cluster. Mushrooms feature rounded caps in cherry red with white spots on slender stems. Background trees are stylized as vertical columns with cloud-like canopies in layers of emerald and olive green. Grass appears as simple horizontal strokes in lime and chartreuse. Flowers are five-petal circles in pink and yellow scattered throughout. Child-friendly aesthetic, storybook quality, no outlines, cheerful pastel-accented palette, cute character design." \
  "GLM 5V" "Whimsical Forest Animals Gathering"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A vibrant flat illustration of a bustling modern city street at golden sunrise. Geometric buildings in coral, teal, and mustard yellow rise against a soft peach gradient-free sky. Simplified human figures with rounded limbs walk along bold colored sidewalks. Minimal trees with perfect circular canopies dot the wide avenue. Clean crisp vector shapes define square windows, rectangular doors, and sleek street lamps. Absolutely no gradients, shadows, or surface textures anywhere. Pure solid color blocks create spatial depth through carefully overlapping layers. A limited harmonious palette of warm and cool tones perfectly balances the entire composition. The scene feels modern, cheerful, and highly stylized with absolute visual clarity and contemporary graphic design aesthetics." \
  "Kimi K2.6 Thinking" "Urban Morning Commute"

queue_job 42 \
  "A peaceful flat illustration of a tranquil alpine mountain lake at golden dawn. Jagged geometric peaks in deep indigo and slate blue frame the scene behind rolling forested hills. The mirror-like water reflects simplified triangular pine trees and a pale amber sky using solid color blocks. A small vivid red canoe rests on the curved shoreline. Absolutely no gradients, textures, or realistic shading present. Depth is created through layered horizontal bands of distinct color. Clean crisp edges define every natural element. A restricted palette of cool blues, warm ambers, and vivid red accents creates perfect harmony. The composition feels balanced, calm, and modern with pure graphic simplicity and intentional minimal visual storytelling." \
  "Kimi K2.6 Thinking" "Serene Mountain Lake"

queue_job 43 \
  "A charming flat illustration of a cozy reading corner in a sunlit room. A rounded armchair in burnt orange sits beside a simple geometric bookshelf filled with colorful rectangular books. A potted plant with broad circular leaves adds greenery. Soft light streams through a large square window casting no shadows. The floor is warm terracotta. No textures, gradients, or three-dimensional effects. Depth comes from overlapping flat shapes and size variation. A limited palette of burnt orange, sage green, cream, and dusty rose creates warmth. Clean outlines and solid color fills define every object. The scene feels inviting, peaceful, and modern with delightful graphic simplicity and balanced composition." \
  "Kimi K2.6 Thinking" "Cozy Reading Nook"

queue_job 44 \
  "A lively flat illustration of an outdoor farmers market on a bright weekend morning. Colorful striped awnings in coral, lemon, and mint shelter wooden stalls with simplified geometric produce. Rounded apples, elongated carrots, and circular oranges sit in neat piles. Friendly vendors and customers have minimal facial features and bold clothing. No shading, textures, or perspective tricks. Depth is suggested through stacked flat layers and size differences. A cheerful limited palette of warm corals, cool mints, and sunny yellows dominates. Clean sharp edges separate every element. The atmosphere feels vibrant, community-focused, and modern with pure graphic clarity and joyful minimalistic design throughout the entire square composition." \
  "Kimi K2.6 Thinking" "Bustling Farmers Market"

queue_job 45 \
  "A dreamy flat illustration of a botanical garden under a starry midnight sky. Oversized geometric leaves in emerald and jade fill the foreground against deep navy background. Simplified flowers in magenta and gold bloom on thin straight stems. A crescent moon hangs above rounded treetops. No gradients, textures, or dimensional shading. Spatial depth is achieved through layered flat silhouettes and careful color value shifts. A magical limited palette of deep navy, rich emerald, bright magenta, and soft gold creates contrast. Clean smooth edges outline every organic shape. The scene feels enchanting, serene, and modern with pure graphic simplicity and sophisticated minimal visual storytelling in a balanced composition." \
  "Kimi K2.6 Thinking" "Midnight Botanical Garden"

# --- Deepseek Instant ---
queue_job 46 \
  "A flat illustration of a busy city bus crossing a bridge at sunset. The scene uses simple geometric shapes for buildings and the vehicle. The color palette is limited to warm oranges, deep purples, and silhouette blacks. No texture is present; the sky is a smooth gradient of flat color bands. The bus and cars are simplified rectangles and circles. Reflections in the water are indicated by horizontal color blocks. The composition is balanced with the bridge's structure creating a strong central focal point. The mood is calm and nostalgic, achieved solely through color and form." \
  "Deepseek Instant" "Sunset Commute"

queue_job 47 \
  "Flat illustration of a person sitting on a windowsill reading a book, with a sleeping cat nearby. The style uses clean, solid shapes and a restricted palette of soft blues, muted yellows, and warm grays. No shading or gradients are used; depth is created by overlapping simple forms. The window frames the scene, showing a flat, stylized view of clouds and a sun. The interior is minimal, with a plant and a rug defined by their basic outlines. The composition feels peaceful and intimate." \
  "Deepseek Instant" "Cozy Morning"

queue_job 48 \
  "Flat illustration of a vibrant farmers market scene. The artwork features simple, stylized produce stands with awnings made of solid blocks of primary colors. Figures are depicted as basic shapes with no facial features. The palette is limited to reds, yellows, greens, and navy blues. There is no texture; all elements are solid, unshaded areas of color. The composition is busy but orderly, with overlapping shapes creating a sense of depth without the use of perspective. It communicates a lively, community atmosphere." \
  "Deepseek Instant" "Market Day"

queue_job 49 \
  "A flat illustration depicting a yoga class in a park. The focus is on simple, fluid human forms comprised of curved and straight lines, all rendered in flat, solid colors. The color palette is restrained to soft greens, earthy browns, and vibrant teal for the mats. There is no texture or gradient; the grass and trees are simplified into large, unshaded shapes. The composition uses overlapping figures to create depth. The overall feeling is one of peace and balance, derived from the harmony of simple colors and forms." \
  "Deepseek Instant" "Yoga in the Park"

queue_job 50 \
  "Flat illustration of a camping scene under a starry night sky. The composition uses a very limited palette of dark blues, bright yellows, and white. The sky is a single flat color, with stars represented as simple dots and crosses. The tent and mountains are basic triangles and blocks, with no shading or texture. A campfire is a collection of simple orange and yellow shapes. The design relies on the contrast between the dark background and the bright, solid shapes to convey the warmth of the fire and the vastness of the night." \
  "Deepseek Instant" "Night Sky"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Flat illustration of a cozy corner coffee shop with simple geometric shapes, a barista behind a minimalist counter pouring coffee into a ceramic cup, two round tables with chairs, a potted plant in the window, warm limited color palette of mustard yellow burnt orange cream and soft brown, no texture or shading only flat color blocks, simple abstract wall art on the wall, a small chalkboard menu with basic typography, sunbeams represented by light yellow rectangles streaming through a square window, clean lines and minimal detail throughout the composition." \
  "ERNIE 5.1" "Morning Coffee Shop Scene"

queue_job 52 \
  "Flat illustration of a cyclist riding along a winding path through a simplified autumn park, trees reduced to circles and rectangles in warm fall tones of amber rust terracotta and olive green, a simple bridge arching over a flat blue stream, two birds as tiny silhouettes in the sky, limited palette of warm earth tones and muted teal, no gradients or texture only solid flat color shapes, a bench and lamppost as basic geometric forms, smooth rolling hills in the background as layered flat color bands, cheerful and serene mood." \
  "ERNIE 5.1" "Cyclist Through Autumn Park"

queue_job 53 \
  "Flat illustration of a rooftop urban garden at sunset, simplified geometric planter boxes with abstract flowers and succulents in coral pink sage green and lavender, a small bistro table with two chairs, a string of triangular pennant flags across the scene, city skyline as flat layered rectangles in soft purple and dusty blue, sun as a perfect flat circle in warm gold and peach, limited palette of sunset tones with no shading or texture, simple railing along the roof edge, potted herbs as small rounded shapes, peaceful evening atmosphere." \
  "ERNIE 5.1" "Rooftop Garden at Sunset"

queue_job 54 \
  "Flat illustration of a lone fisherman sitting in a small wooden boat on a perfectly calm lake, water depicted as flat horizontal bands of soft blue and teal, distant mountains as simple triangular shapes in muted indigo and grey, a single pine tree on the shore as a dark green cone with brown trunk, sky in gradient-free flat bands of pale yellow and light coral, fisherman as a simple silhouette with a flat orange hat, limited earthy and aquatic color palette, no texture or depth only clean geometric forms, a small dock extending as a flat rectangle into the water." \
  "ERNIE 5.1" "Fisherman on a Calm Lake"

queue_job 55 \
  "Flat illustration of a vibrant street market scene in an old European town, colorful market stalls as simple rectangular canopies in red teal and sunshine yellow, vendors selling abstract fruits vegetables and bread displayed as basic rounded shapes, cobblestone path suggested by small flat ovals in warm grey, buildings in the background as tall flat rectangles with simple square windows, a cat walking between stalls as a small orange silhouette, limited palette of cheerful primary and secondary colors, no texture or shading only bold flat color blocks, lively and bustling atmosphere." \
  "ERNIE 5.1" "Street Market in Old Town"

# --- LongCat Deep search ---
queue_job 56 \
  "A serene woodland scene featuring a gentle deer standing on a grassy knoll with mushrooms and wildflowers nearby, all rendered in flat illustration style. The composition uses clean geometric shapes and a limited color palette of forest greens, soft browns, blush pink, and butter yellow. There is no texture, shading, or atmospheric depth—only flat areas of vibrant solid color. Simple triangular pine trees line the background while stylized clouds float in a pale sky. The deer's silhouette is made of smooth, untextured forms with minimal detail, communicating volume only through color blocking. A few circular mushrooms and leaf shapes ground the foreground. The overall effect is calm, graphic, and modern, emphasizing pure form and flat color harmony over realism." \
  "LongCat Deep search" "Whimsical Forest Clearing"

queue_job 57 \
  "A charming small-town street lined with pastel-colored houses and shops, rendered in pure flat illustration. The scene features a bakery, a bookshop, and a florist with simple storefronts and awnings, all defined by clean lines and solid blocks of color without gradients. A vintage bicycle leans against a lamppost, while a cat sits on a doorstep. The palette is limited to warm terracotta, sage green, cream, and sky blue. There are no shadows or textures—depth is suggested only by overlapping shapes and slight size variations. Trees are stylized as rounded circles of foliage, and clouds are simplified puff shapes. The entire composition feels graphic, inviting, and minimal, ideal for modern flat design." \
  "LongCat Deep search" "Cozy Neighborhood Street"

queue_job 58 \
  "A minimalist home office desk setup illustrated in a flat style with no shading or perspective. The desk is a simple rectangular shape in warm wood tones, holding a sleek laptop, a ceramic mug, and a small potted succulent. Behind the desk is a pinboard with geometric prints and a framed abstract poster. A window shows a solid blue sky with one white cloud. The color palette is restricted to charcoal, cream, olive green, and soft terracotta. Every object—the lamp, pen holder, and keyboard—is reduced to its essential form using flat color areas and crisp edges. There are no reflections, shadows, or complex textures, creating a clean, graphic, and harmonious domestic scene." \
  "LongCat Deep search" "Modern Creative Workspace"

queue_job 59 \
  "A flat illustration of a sunlit breakfast nook with a round wooden table set for one. On the table are a steaming bowl of cereal, a glass of orange juice, and a folded newspaper. Through a nearby window, stylized trees and a soft blue sky are visible. The entire scene uses a limited palette of warm yellows, muted orange, soft cream, and gentle green. The illustration avoids texture, gradient fills, and realistic depth, relying instead on solid color fields and geometric simplification. The chair is a simple angular shape, the cup is a cylinder with no shine, and the cereal flakes are tiny abstract dots. The composition feels bright, calm, and modern through pure flat design." \
  "LongCat Deep search" "Morning Kitchen Bathed in Warmth"

queue_job 60 \
  "A dramatic coastal scene featuring a tall red-and-white striped lighthouse perched on a rocky cliff, rendered in flat illustration style. Below, simplified waves lap at the shore in layered bands of blue and teal, while above, a gradient-free sky transitions from tangerine to soft violet. Silhouetted birds fly in the distance as crisp white crescent shapes. The lighthouse is constructed from basic geometric forms—a cylinder tower with a flat railing and sharp conical roof—all colored in solid blocks of crimson and ivory. The rocks are jagged trapezoids without texture, and the sun is a perfect circle of gold. The piece uses a restricted sunset palette and avoids shading, emphasizing bold graphic color and elegant simplicity." \
  "LongCat Deep search" "Seaside Lighthouse at Sunset"

echo "✅ All 60 jobs queued in scheduler"

