#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Cave art about modern times — messages carved by the last humans
#        for the next civilization, depicting 2020s daily life
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+38+-+cave+art
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "Ochre and charcoal petroglyphs cover a weathered limestone panel, depicting a stick-figure human standing rigidly inside a crude rectangular outline representing a train carriage, surrounded by dozens of identical hunched figures staring downward at small glowing tablets held in their palms, incised sun and moon symbols marking a repeating daily cycle above the scene, scratched tally marks counting hours wasted in the box, deep bison-blood red pigment filling the negative space between figures, rough hand-stencils bordering the composition, cracked stone surface with natural mineral striations, torchlight flicker implied through uneven pigment density, ancient documentary intent, primal anthropological record of a lost daily ritual." \
  "Claude Sonnet 5 medium" "Cave Wall Commute"

queue_job  2 \
  "A wide cave panel rendered in umber, black charcoal, and faded red ochre shows a family of angular stick figures seated in a circle, each face replaced by a small carved rectangle glowing with painted white dots meant to represent light, a fire pit drawn beneath them left cold and unused, dogs sit ignored at the figures' feet, symbols of food bowls scattered but untouched, spiral motifs above representing wasted time, hand-print borders framing the ritual scene, deep gouges and natural rock fissures integrated into the composition, weathered patina suggesting thousands of years of erosion, solemn documentation of a vanished evening custom." \
  "Claude Sonnet 5 medium" "Feast of Screens"

queue_job  3 \
  "Primitive pictograph in burnt sienna and soot black covers an uneven rock face, showing worshipful stick figures kneeling before an oversized glowing rectangle mounted on a wall, smaller identical rectangles clutched in every hand, arrows and spirals radiating outward suggesting endless desire and distraction, a hierarchy of larger dominant figures atop a stepped pyramid labeled with coin-like symbols, ochre handprints stamped along the border as ritual signature, deep striations and mineral deposits crossing the image naturally, torch-soot shadows deepening the recesses, an anthropological record left in stone warning future beings of a civilization enslaved by glowing screens." \
  "Claude Sonnet 5 medium" "Sacred Rectangle of Endless Want"

queue_job  4 \
  "Weathered cave engraving in red ochre and charcoal depicts a herd of boxy metal creatures with four round feet, tiny human figures entering their bellies each dawn, parallel grooved lines representing endless gray pathways stretching to the horizon, smoke symbols rising from the beasts' rear, exhausted stick figures slumped after long migrations between stone hives, sun-and-moon cycle carved above showing repetition without rest, natural rock cracks integrated as pathways, ochre handprints and finger-drag textures bordering the scene, deep primal linework, documentary tone recording a strange daily pilgrimage undertaken by the last generation of Homo sapiens." \
  "Claude Sonnet 5 medium" "Ritual of the Metal Beast"

queue_job  5 \
  "A somber stone tablet carved in deep relief shows rows of identical small rectangles, each etched with unreadable symbolic scratches meant to represent names and faces scrolled endlessly by seated figures, charcoal-black pigment fills the recesses, ochre red marks a countdown of numerals near collapse, a lone standing figure raises both palms toward a fading sun disk, spiral and radiating-line motifs suggest overload and burnout, natural limestone cracks left visible and incorporated into the design, hand-stencil border marking authorship, weathered surface patina implying millennia of exposure, an epitaph left by the last civilization describing endless scrolling before their end." \
  "Claude Sonnet 5 medium" "Tomb of the Forgotten Names"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A rough, textured limestone wall in a dark cave, carved with an intricate frieze of modern life. It shows a central Homo sapiens in simple 21st-century clothes (hoodie, jeans), hunched over a faintly glowing hand-held rectangle (a smartphone), surrounded by etched symbols and diagrams: a Wi-Fi signal, a simple house, stylized food, and many tiny, abstract stick-figures with question marks and hearts (likes). The scene is chaotic but desperate, a message about a digital world lost. The entire frieze is framed by rough, uncarved stone, a window into a bygone era. Natural, flickering firelight from an unseen source rakes across the relief, emphasizing the deep, hand-carved grooves." \
  "Gemini 3.5 Flash" "The Internet Scroll"

queue_job  7 \
  "Deep in a dimly lit cave, the rough, uneven granite wall bears a deeply carved pictograph of an ancient 2020s commuter train. A line of small, etched Homo sapiens, each wearing a face mask and a backpack, is depicted crammed into the geometric shape of the train car. One central figure has its hand extended, touching a small, carved circle (a clock) which is segmented, with a hand pointing to '8 AM'. Below the train, simple glyphs represent a house and a taller building. The entire carving is crude yet legible, illuminated by the focused beam of a modern, hand-held flashlight held by a contemporary human explorer, revealing the raw, carved texture against the natural stone." \
  "Gemini 3.5 Flash" "The Daily Squeeze"

queue_job  8 \
  "A wide-angle photograph of a cavernous rock wall, dominated by a large, complex frieze chiseled into the sandstone. The scene depicts a Homo sapiens family of four, sitting around a rectangular table, all looking down at individual, carved slates (smartphones and tablets) that they are holding. A large, cracked sun symbol is etched at the top of the frieze, next to a small, simplified nuclear explosion icon and a line of stylized binary code. Below them, a short, crude sentence in a recognizable Latin alphabet: \"WE LOVED, BUT WE FORGOT HOW TO LOOK UP.\" The carving is weathered and ancient, its lines rough and imperfect, capturing a moment of profound, simple failure." \
  "Gemini 3.5 Flash" "The Last Supper"

queue_job  9 \
  "A detailed, low-relief carving on a volcanic rock face within a dark cave. It shows a continuous procession of Homo sapiens figures moving from left to right across the uneven surface. They are depicted with small, simple representations of their day-to-day life: one carries a rolling suitcase, another is pushing a shopping cart filled with carved boxes, a third has a child on their shoulders. Above them, an arched line of simple, stylized buildings (a city) is carved with a crack running through it. The central message, chiseled in bold, block letters beneath the procession, reads: \"WHERE WE WENT, WE CANNOT SAY. THE CITIES DID NOT HOLD.\"" \
  "Gemini 3.5 Flash" "The Great Migration"

queue_job 10 \
  "A close-up photograph of a section of a cave wall, its surface rough and damp, displaying a powerful, single glyph. In the center, a large, stylized eye is deeply etched into the stone, and below it, an open, rectangular frame containing a simple, crude depiction of a face with a question mark. Surrounding this central image are dozens of smaller, intricate carvings: a bicycle, a tree, a cup of coffee, a stylized cloud with rain, a handshake, and a tiny, detailed satellite dish pointing up at a simple crescent moon. The entire piece is a testament, a cry to be remembered for the mundane beauty of 2020s life, illuminated only by a single, focused headlamp." \
  "Gemini 3.5 Flash" "The Message in Stone"

# --- ChatGPT ---
queue_job 11 \
  "A vast prehistoric cave wall transformed into an archaeological chronicle of the early twenty-first century, carved by the final generation of modern humans for distant descendants. Primitive stone engravings depict shopping carts, supermarket shelves, barcode symbols, reusable bags, digital payment icons, overflowing refrigerators, cooking pans, takeaway coffee cups, and families comparing labels. Ancient charcoal pigments and ochre washes blend with surprisingly recognizable modern objects rendered as timeless pictographs. Cracks, mineral deposits, smoke stains, and weathered limestone emphasize immense age. Torchlight reveals carefully arranged scenes explaining everyday food gathering, consumption, and community life in the 2020s, preserving ordinary routines as sacred cultural memory after humanity's extinction." \
  "ChatGPT" "The Last Grocery Run"

queue_job 12 \
  "An immense limestone cavern covered with ancient-style petroglyphs documenting everyday digital life before human extinction. Stone carvings portray people staring into smartphones, scrolling endless feeds, taking selfies, participating in video meetings, sending messages, watching streaming entertainment, wearing headphones, charging devices, and navigating with map symbols. Social media icons become mysterious tribal glyphs integrated into authentic cave art composition. Natural mineral pigments, soot, engraved lines, and weathered textures create the appearance of thousands of years of erosion. Flickering torchlight illuminates this solemn visual archive, presenting ordinary life in the 2020s as an enigmatic message intentionally left behind for the civilization that would someday rediscover humanity." \
  "ChatGPT" "Echoes of the Endless Screen"

queue_job 13 \
  "A monumental cave mural carved by the final Homo sapiens records the rituals of modern work before civilization disappeared. Ancient engravings illustrate remote workers at laptops, crowded office cubicles, coffee breaks, business meetings, keyboards, wireless networks represented by symbolic waves, office chairs, spreadsheets transformed into geometric patterns, calendars, deadlines, commuting by train and bicycle, and exhausted workers returning home. The composition follows authentic prehistoric storytelling with layered scenes connected across rough limestone walls. Ochre, charcoal, white clay, and iron oxide pigments enrich deeply incised carvings. Weathering, mineral crystals, cracks, soot, and dramatic torch illumination create the convincing illusion of genuine prehistoric cave art preserving forgotten professional life." \
  "ChatGPT" "The Office of Stone"

queue_job 14 \
  "An enormous stone chamber filled with prehistoric carvings describing daily domestic life during the 2020s, created as humanity's farewell message before extinction. Ancient figures prepare meals, vacuum floors, wash clothes, exercise indoors, care for children, feed pets, water houseplants, adjust smart thermostats, and control lights with voice assistants symbolized as mysterious radiating circles. Household appliances become sacred pictograms harmoniously integrated into authentic cave painting traditions. Earth pigments, engraved stone textures, faded charcoal outlines, and naturally aged mineral stains create remarkable archaeological realism. Torchlight dances across weathered limestone, revealing an emotional visual encyclopedia of ordinary family existence intended for the next intelligent civilization." \
  "ChatGPT" "The Ritual of Connected Homes"

queue_job 15 \
  "A breathtaking prehistoric cave panorama preserving the daily journey of modern humans across cities before their disappearance. Stone carvings depict bicycles, buses, electric cars, subway trains, traffic lights, pedestrian crossings, apartment towers, delivery couriers, public parks, weather forecasts, umbrellas, and crowded sidewalks, all simplified into authentic cave art symbolism. The narrative flows continuously across rough limestone like an ancient historical record, combining engraved outlines with ochre, charcoal, clay white, and iron-red pigments. Deep erosion, mineral growth, smoke-darkened ceilings, fractured rock surfaces, and dramatic torchlight establish convincing archaeological authenticity. Every scene quietly explains ordinary urban life in the 2020s to civilizations yet unborn." \
  "ChatGPT" "Stone Chronicle of the Last Commute"

# --- Grok fast ---
queue_job 16 \
  "Ancient cave painting style on weathered stone wall, ochre and charcoal pigments, depicting a modern homo sapiens morning routine in 2020s, stick-figure human waking in rectangular bed inside box-like room, reaching for glowing rectangle smartphone on bedside, brewing coffee from machine, brushing teeth while staring at mirror reflection, simple symbols of alarm clock and window with city buildings outside, rough textured rock surface with hand stencils and animal-like modern car icons nearby, narrative sequence panels separated by lines, primitive artistic technique showing daily life message for future civilizations, detailed symbolic storytelling in prehistoric art form." \
  "Grok fast" "Morning Ritual in the Digital Age"

queue_job 17 \
  "Primitive cave art carved into stone, earth tones and black outlines, illustrating 2020s homo sapiens daily commute, line of simplified humans inside wheeled metal boxes on crowded roads with traffic lights, some figures holding glowing phones, tall rectangular skyscrapers in background, bridges and signs with abstract text symbols, smoke from vehicles, sequence showing leaving home to arriving at destination, rough stone texture with cracks and mineral deposits, handprints and symbolic wheels, educational message left by extinct modern humans about their hurried transportation life." \
  "Grok fast" "Commute Through Concrete Jungles"

queue_job 18 \
  "Ancient rock painting in traditional cave style using red ochre and manganese black, portraying modern office life of 2020s humans, figures seated at glowing screen rectangles on desks, typing on keyboards, video call windows with multiple faces, coffee cups and scattered papers, plants in pots, sequence of focused work then group meeting around large table with devices, abstract icons of clouds and networks, textured stone canvas with overlapping figures and tools, carved message describing sedentary screen-bound daily existence for future beings to decipher." \
  "Grok fast" "Digital Workspace and Virtual Connections"

queue_job 19 \
  "Prehistoric cave drawing on rugged limestone wall, vibrant mineral pigments, capturing 2020s shopping and consumption habits of homo sapiens, crowds of simplified people pushing carts through aisles filled with packaged goods, glowing screens showing online stores, money symbols exchanging hands, overflowing bags, fast food and delivery icons, narrative flow from home to bustling supermarket to home again, primitive artistic strokes with overlapping elements, stone surface details like fissures and ancient tool marks, profound record of material abundance and daily trade cycles." \
  "Grok fast" "Consumer Culture and Market Rituals"

queue_job 20 \
  "Stone age cave art rendered in charcoal and earthy reds, depicting modern humans evening routines in 2020s, family figures on couches facing large glowing television rectangles, others scrolling phones or laptops, dining at tables with delivered food boxes, exercise symbols or relaxation poses, city lights visible through windows, sequence panels showing transition from day to night, pets as companion figures, rough textured rock with layered pigments and symbolic stars or wifi waves, lasting message carved by previous civilization about leisure, technology, and family bonds in their era." \
  "Grok fast" "Evening Unwind in Connected Homes"

# --- Copilot Smart ---
queue_job 21 \
  "A carved stone mural depicting humans hunched over glowing rectangles, etched with primitive outlines of smartphones, social media icons, and endless scrolling gestures. Figures are shown in repetitive poses, heads bowed, fingers swiping, surrounded by symbolic hashtags and carved emojis. The cave wall captures the ritual of digital communication, portraying it as the defining daily act of homo sapiens in the 2020s. The imagery blends ancient petroglyph style with modern symbols, leaving a message for future civilizations about the obsession with handheld devices and virtual connection." \
  "Copilot Smart" "Cave Art of Smartphones"

queue_job 22 \
  "Etched silhouettes of cars, buses, and trains carved into stone, showing humans trapped in traffic lines and crowded compartments. Figures are drawn with weary expressions, clutching coffee cups, briefcases, and headphones. The cave wall depicts highways as endless serpents, while subway tunnels are carved as dark labyrinths. Symbols of clocks and calendars are scratched alongside, representing the daily grind of commuting. This artwork conveys the monotony and ritual sacrifice of time that defined modern life, preserved as a warning to future civilizations about the cost of progress." \
  "Copilot Smart" "Cave Art of Commuting"

queue_job 23 \
  "Stone carvings of supermarkets, shopping carts, and fast-food logos rendered in primitive iconography. Humans are shown carrying bags overflowing with goods, surrounded by carved symbols of dollar signs, barcodes, and advertisements. The cave wall depicts the ritual of consumption as a sacred act, with towering shelves and glowing screens etched as temples of modern worship. Figures are drawn in repetitive cycles of buying, eating, and discarding, leaving behind carved trash heaps. This artwork immortalizes the consumerist heartbeat of the 2020s, a message about abundance, waste, and desire." \
  "Copilot Smart" "Cave Art of Consumption"

queue_job 24 \
  "Carved outlines of humans seated before glowing rectangles, etched into stone with symbols of video call grids, headphones, and laptops. Figures are shown in fragmented poses, half dressed in formal attire above, casual below, symbolizing the duality of remote work. The cave wall depicts homes as caves within caves, with carved Wi-Fi signals radiating outward. Symbols of mute buttons, chat bubbles, and endless meetings are scratched alongside. This artwork preserves the strange ritual of working from home, a defining adaptation of modern humans, left as a record of resilience and isolation." \
  "Copilot Smart" "Cave Art of Work from Home"

queue_job 25 \
  "Etched stone murals of burning forests, melting ice, and storm clouds carved with primitive strokes. Humans are shown holding protest signs, recycling bins, and solar panels, surrounded by carved symbols of factories and smokestacks. The cave wall depicts the struggle against environmental collapse, with figures etched in both despair and hope. Symbols of Earth globes, water droplets, and wind turbines are scratched alongside, representing the fight for survival. This artwork serves as a carved testament to the climate crisis of the 2020s, a message to future civilizations about the fragility of nature and human responsibility." \
  "Copilot Smart" "Cave Art of Climate Struggle"

# --- Mistral Think ---
queue_job 26 \
  "A primitive cave wall, illuminated by flickering torchlight, covered in ancient carvings depicting modern life: a human figure hunched over a glowing rectangle (smartphone), surrounded by abstract symbols of Wi-Fi, social media likes, and emojis. The carvings are rough, made with stone tools, yet clearly show a coffee cup, a laptop, and a crowded subway. The colors are earthy—ochre, charcoal, and white clay—with a sense of urgency, as if the artist knew their time was limited. The scene is both nostalgic and eerie, a snapshot of a civilization on the brink, leaving its digital footprint in stone." \
  "Mistral Think" "Cave Art of Digital Life"

queue_job 27 \
  "A sprawling, primitive mural on a cave wall, telling the story of a daily commute: stick figures in suits and dresses, trapped in metal boxes on wheels (cars), moving in long, orderly lines. The cave artist used natural pigments to depict traffic lights, skyscrapers, and a giant, glowing sun (representing the office). The figures appear both hurried and exhausted, their postures slouched under the weight of invisible burdens. The mural is framed by handprints, a silent testament to the humans who once rushed through life." \
  "Mistral Think" "Cave Painting of the Last Commute"

queue_job 28 \
  "A cave wall filled with intricate carvings of a modern feast: a table laden with food containers, plastic utensils, and a glowing screen (TV) at the center. The figures around the table are connected by lines to small, glowing rectangles in their hands (phones), their faces lit by the artificial glow. The artist used deep reds and browns to convey warmth, but also isolation. The scene is both celebratory and melancholic, a final gathering before the end, etched into stone for future discoverers." \
  "Mistral Think" "Stone Carvings of the Last Feast"

queue_job 29 \
  "A chaotic, vibrant cave mural depicting a bustling modern city: towering structures (skyscrapers) reaching for the sky, tiny figures moving like ants, and strange, glowing rectangles (screens) everywhere. The artist used bold, primitive strokes to show airplanes in the sky, cars on the ground, and a network of lines connecting everything (the internet). The colors are bright and urgent, as if the artist wanted to ensure the message would last forever. The mural feels alive, yet hauntingly still." \
  "Mistral Think" "Prehistoric Graffiti of the Last City"

queue_job 30 \
  "A somber cave painting showing a group of humans standing in a circle, each holding a small, glowing object (a phone) to their ear or in their hands. The figures are simple, almost childlike, but their postures convey deep emotion—some are embracing, others are looking up at the sky. The background is filled with symbols of modern life: airplanes, buildings, and a large, glowing eye (a satellite). The colors are muted, with a focus on blues and grays, evoking a sense of finality and quiet acceptance. The scene is a silent farewell, carved into stone for eternity." \
  "Mistral Think" "Cave Art of the Last Goodbye"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "Ancient cave art carved deeply into rough stone walls, depicting the daily rituals of early twenty-first century humans before their sudden extinction. The petroglyphs show primitive stick figures hunched over small glowing rectangular stones, staring mesmerized. Above them, carved symbols of thumbs pointing upward represent digital worship. The artwork uses natural ochre pigments, charcoal smudges, and deep chisel marks. Faint outlines of modern delivery boxes and paper coffee cups surround the figures. The lighting is dramatic, illuminated by a flickering torch, casting long shadows across the textured rock. A poignant message left for future civilizations, capturing the isolated yet connected daily life of modern homo sapiens in the two thousand and twenties." \
  "Qwen 3.7 Plus Tinking" "The Glowing Rectangle"

queue_job 32 \
  "Prehistoric style cave paintings and deep stone carvings illustrating the mundane survival rituals of humans in the two thousand and twenties. The ancient artwork depicts figures sitting in isolated stone boxes, staring into flat glowing altars with carved keyboards. They are hunting invisible prey through the digital ether. Surrounding the central figures are primitive engravings of stacked cardboard boxes and masked faces, symbolizing the great plague era. The texture of the rock is rough and weathered, colored with faded red ochre and black charcoal. Illuminated by warm firelight, this archaeological masterpiece serves as a desperate historical record of modern daily life left behind for the next ancient civilization to discover and understand." \
  "Qwen 3.7 Plus Tinking" "The Remote Hunt"

queue_job 33 \
  "Ancient petroglyphs etched into a massive cavern wall, portraying the daily migration of twenty-first century humans before their sudden extinction. The cave art shows rows of geometric metal beasts with round feet, carrying trapped stick figures inside. Above the beasts, carved symbols represent pollution and rushing clocks. The primitive drawings are accented with natural earth tones, rusted reds, and deep shadowed chisel marks. Scattered around the main scene are faint carvings of paper coffee cups and rectangular phones. The rough stone texture and dramatic chiaroscuro lighting emphasize the solemnity of this extinct culture. This monumental stone canvas acts as a final warning and historical diary of modern commuting life for future descendants to decode." \
  "Qwen 3.7 Plus Tinking" "The Metal Beasts"

queue_job 34 \
  "Weathered cave art carved into a dark limestone surface, documenting the dietary habits and daily routines of humans in the two thousand and twenties. The primitive pictographs depict stick figures receiving square cardboard offerings from masked delivery hunters. They consume wrapped meats and sugary dark liquids from cylindrical containers. The ancient artists used crushed minerals and charcoal to create faded red and black hues. Deeply incised lines show the glowing screens the figures watch while eating. The rough, uneven rock face and dramatic chiaroscuro lighting emphasize the solemnity of this extinct culture. A profound archaeological message left in stone, explaining the modern convenience lifestyle to the next intelligent species on earth to find." \
  "Qwen 3.7 Plus Tinking" "The Feast of Convenience"

queue_job 35 \
  "Deeply carved stone reliefs and faded ochre paintings inside a vast cavern, illustrating the evening rituals of modern humans before their demise. The ancient cave art shows figures lying on soft rectangular nests, bathed in the light of large wall-mounted glowing slabs. They are motionless, watching carved moving pictures. Surrounding the bed are primitive symbols of tangled charging vines and empty beverage cylinders. The texture of the stone is highly detailed, rough, and ancient, utilizing natural pigments and deep shadow carving. Lit by a single warm flame, this poignant petroglyph serves as a final testament of modern leisure and digital consumption, preserved in the dark for future civilizations to decode and understand." \
  "Qwen 3.7 Plus Tinking" "The Sleep Ritual"

# --- GLM 5V ---
queue_job 36 \
  "Ancient cave wall carving depicting modern human daily life from the 2020s, rendered in primitive ochre and charcoal style on rough stone surface. Central figure shows homo sapiens holding glowing rectangular device called smartphone, surrounded by stick figures wearing face masks and carrying coffee cups. Carved pictograms show tiny humans inside small metal boxes moving on paved roads, symbols of WiFi signals, and calendar markings showing work-from-home routines. Weathered stone texture with natural cracks, prehistoric artistic technique combined with contemporary subject matter. Earthy reds, browns, blacks on beige rock background. Archaeological artifact aesthetic, message to future civilizations about digital age existence, mysterious and haunting atmosphere, highly detailed stone engraving texture." \
  "GLM 5V" "Daily Commute and Digital Connection"

queue_job 37 \
  "Prehistoric cave painting illustrating 2020s remote work culture, created with ancient pigment techniques on cavern wall. Scene shows seated figure hunched before illuminated screen rectangle, surrounded by domestic artifacts: coffee mug, snack containers, comfortable seating symbol. Pictorial narrative includes video call meetings represented by multiple faces in grid pattern, pet animals nearby, blurred boundaries between living space and workspace. Primitive artistic execution using iron oxide reds, manganese blacks, calcium white on textured limestone surface. Faded edges suggesting antiquity, intentional message carved by last humans describing pandemic-era isolation and virtual connectivity. Anthropological documentation style, mix of Paleolithic art conventions with modern technological elements, somber yet informative tone." \
  "GLM 5V" "The Home Office Ritual"

queue_job 38 \
  "Cave art masterpiece carved into sandstone cliff face portraying 2020s social media existence through primitive visual language. Composition features central humanoid figure taking self-portrait with handheld device, surrounded by symbolic representations of likes hearts, comment bubbles, follower counts, and notification icons rendered as abstract geometric shapes. Background shows endless scroll imagery and algorithm patterns. Ancient artistic medium—chipped relief carving with mineral pigments—depicting contemporary digital addiction and online persona curation. Warm terracotta tones, deep umbers, chalk whites against natural rock grain. Archaeological find aesthetic, warning to future species about attention economy and virtual validation seeking, melancholic documentation of screen-based civilization before collapse." \
  "GLM 5V" "Social Media and Digital Identity"

queue_job 39 \
  "Petroglyph-style artwork etched into granite cave surface documenting 2020s consumer lifestyle and instant gratification culture. Visual narrative depicts figures receiving packages from delivery vehicles, ordering food through apps shown as mystical tablets, accumulating material goods represented by stacked boxes and possessions. Includes symbolic rendering of one-click purchasing, subscription services, and same-day delivery logistics mapped as movement patterns. Primitive carving technique with bold incised lines and filled silhouettes using natural pigments—rust red, carbon black, clay yellow. Stone surface shows authentic weathering and mineral deposits. Time capsule quality, anthropological record of late-stage capitalism and convenience obsession, created by final generation as testament to consumption-driven society." \
  "GLM 5V" "Consumer Culture and Delivery Economy"

queue_job 40 \
  "Solemn cave mural painted with prehistoric materials on underground chamber walls, capturing 2020s existential dread about climate change and environmental collapse. Imagery shows melting ice symbols, rising water levels, extreme weather events depicted through primitive storm motifs, and humans wearing protective gear against polluted air. Contrasting scenes of pristine nature versus industrial destruction, endangered species represented in stylized animal forms, recycling symbols as mysterious glyphs. Executed in traditional cave art palette—iron oxide reds, charcoal blacks, gypsum whites—with rough brushwork and spatter techniques on uneven rock texture. Final message from extinct civilization explaining ecological crisis awareness, haunting memorial to anthropocene era, preservation of environmental consciousness for future discoverers." \
  "GLM 5V" "Environmental Anxiety and Climate Awareness"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "Ancient cave wall carved deeply into gray limestone, prehistoric petroglyph style depicting modern homo sapiens in business suits riding a crowded subway train, ochre and charcoal pigments mixed with crushed mineral blues, stick figures clutching rectangular glowing slabs called smartphones and paper vessels containing bitter stimulant drinks, underground iron tunnels rendered as sacred passages, hand stencils overlapping with briefcase silhouettes, faded sienna and umber tones with carbon black outlines, rough stone surface showing natural cracks and weathered patina, flat primitive perspective without depth, archaeological documentation style, message left for future civilizations describing daily survival rituals of the 2020s, museum artifact lighting, highly detailed natural stone texture, prehistoric art aesthetic." \
  "Kimi K2.6 Thinking" "The Morning Commute in Stone"

queue_job 42 \
  "Weathered sandstone cliff face etched with prehistoric carving techniques, ancient cave painting style showing modern humans in metal horseless carriages waiting in line at a glowing altar called a drive-thru window, ochre and sienna pigments depicting outstretched hands receiving paper-wrapped nourishment, stick figures with circular steering wheels and glowing rectangular devices, charcoal outlines of golden arches and beverage cups, mineral paint in iron oxide reds and yellows, cracked stone surface with lichen growth, flat perspective with overlapping symbols, handprints beside tire tracks, message for next civilization about the ritual of consuming food without leaving the carriage, paleolithic art aesthetic, torchlight illumination, rough textured surface." \
  "Kimi K2.6 Thinking" "The Sacred Drive-Thru Ritual"

queue_job 43 \
  "Deep cave interior wall covered in primitive ochre and manganese drawings, prehistoric petroglyph style depicting modern homo sapiens bowing before glowing rectangular altars called screens, stick figures sitting alone in dark caves illuminated by blue light, hands outstretched toward the rectangle god, crushed mineral pigments in charcoal black and cobalt blue, ancient carving techniques showing figures scrolling with thumb gestures, scattered around them are vessels of liquid stimulants and abandoned paper scrolls, flat perspective with symbolic notation, weathered limestone surface with natural erosion, message left for future civilizations explaining how the rectangle controlled all knowledge and social bonds, archaeological documentation style, flickering torchlight." \
  "Kimi K2.6 Thinking" "The Glow of the Rectangle God"

queue_job 44 \
  "Rough granite cave wall carved with primitive hunting scenes reimagined for modern times, ancient petroglyph style depicting homo sapiens gathering colorful plastic vessels and disposable containers from the great water temple called the supermarket, stick figures pushing metal wheeled baskets, ochre and umber pigments mixed with white clay, charcoal outlines of barcode symbols and paper receipts fluttering like sacred talismans, mineral paint in sienna and iron oxide, cracked stone surface with natural patina, flat perspective with overlapping figures, hand stencils beside plastic bag silhouettes, message for next civilization about the weekly ritual of gathering preserved nourishment from vast temples of abundance, paleolithic art aesthetic, museum lighting." \
  "Kimi K2.6 Thinking" "The Great Plastic Hunt"

queue_job 45 \
  "Ancient cave ceiling and wall covered in prehistoric pigment paintings, primitive petroglyph style depicting modern homo sapiens lying on soft platforms in dark caves staring at large glowing rectangles showing moving images, stick figures with blank expressions and open mouths, ochre and charcoal pigments mixed with crushed yellow minerals, symbols of remote controls and wireless signals carved as magical runes, vessels of fermented grain drinks beside the platforms, flat perspective with symbolic dreamlike composition, weathered sandstone surface with natural cracks and mineral deposits, message left for future civilizations describing the trance-like state of consuming endless moving stories, archaeological documentation style, torchlight casting dramatic shadows, rough stone texture." \
  "Kimi K2.6 Thinking" "The Streaming of Consciousness"

# --- Deepseek Instant ---
queue_job 46 \
  "Primitive petroglyph-style carving on a cracked limestone wall depicts a modern Homo sapiens from the 2020s. Central crouched humanoid figure holds a small rectangular tablet emitting zigzag lightning bolts, symbolizing wireless data. Surrounding engravings show a sequence: a hand tapping a glowing square, a floating eye representing the camera, a vertical pillar with horizontal bars indicating battery life, and small stick figures watching the same device. Deep chisel marks create rough textures, with natural red ochre and charcoal dust filling the grooves. The scene includes abstract speech bubbles containing geometric patterns, all rendered in a flat, two-dimensional prehistoric aesthetic, telling future civilizations about daily digital devotion." \
  "Deepseek Instant" "The Smartphone Ritual"

queue_job 47 \
  "Rough-hewn sandstone panel featuring a chaotic procession of angular wheeled boxes, each containing a tiny stick-figure driver, arranged in parallel lines to represent a traffic jam. Above, a large burning circle with rays denotes the sun tracking across the sky. A solitary figure stands beside a vertical post with a glowing green circle and red cross, symbolizing traffic lights. Chiseled zigzag paths behind the vehicles suggest exhaust fumes. The carving uses deep negative space, heavy line work, and sporadic mineral stains of manganese black. The composition feels frantic and repetitive, capturing the morning ritual of enclosed metal carriages, a daily migration etched permanently for alien archaeologists." \
  "Deepseek Instant" "The Daily Commute"

queue_job 48 \
  "Stone wall engraving depicting a seated round-bodied human before a tall rectangular altar, upon which rests a circular flat stone marked with triangular slices. A floating hand reaches toward the altar, while wavy steam lines rise from a small cylindrical cup nearby. On the altar's face, tiny inscribed squares resemble a menu board with numeric symbols. The background shows a crescent moon and stars, indicating nighttime eating. Crude tally marks on the side count calories. The artwork employs a mix of pecking and abrasion techniques, creating a grainy, pitted surface with subtle natural grey and cream tones, immortalizing the 2020s habit of ordering food through glowing rectangles while isolated." \
  "Deepseek Instant" "The Digital Feast"

queue_job 49 \
  "Carved into a dark cavern wall, a supine figure lies on a rectangular platform with four short legs, representing a bed. Beside the head, a small illuminated square emits horizontal sleeping Z-shaped lines, but also a thin connecting line to the figure's ear. A large circular calendar with crossed-out days hangs above, while a separate panel shows the same figure now upright, reaching for the square immediately upon waking. The linear narrative flows left to right, with crude arrows indicating time passage. The stone surface shows natural erosion, with deep incised contours and pale earthy pigments, documenting the peculiar addiction to screen-gazing before and after unconsciousness." \
  "Deepseek Instant" "The Sleep Cycle"

queue_job 50 \
  "Rugged dolomite surface etched with a large winged object soaring overhead, its body cylindrical with a tapered tail, trailing a straight dashed line across the sky. Below, miniature human figures tilt their heads upward, arms raised in unified gesture, while tiny rectangular devices in their hands point toward the bird. To the side, a spiral engraving represents jet engine noise. A smaller sequence shows the bird landing and disgorging tiny figures carrying squared bags. The chisel work is bold and simplistic, with heavy shadowing in the recesses and a patina of iron oxide. This visual message conveys awe for the roaring sky-beast that connected distant lands in the age of fossil fuels." \
  "Deepseek Instant" "The Flying Metal Bird"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Ancient cave wall carved with primitive stick figure art depicting modern human extinction prophecy, rough stone texture with ochre and charcoal pigments, stick figures hunched over glowing rectangular devices representing smartphones, crude carvings of cars and airplanes and skyscrapers, tribal symbols representing social media and supermarkets, primitive rendition of a human sitting in a cubicle, stick family inside a box-shaped house, dark cave interior with torchlight illuminating the carvings, prehistoric art style mixed with recognizable modern objects, earthy tones, archaeological atmosphere, mysterious and haunting." \
  "ERNIE 5.1" "The Last Carvings of Humanity"

queue_job 52 \
  "Weathered cave stone surface covered in ancient petroglyphs showing modern 2020 daily life, primitive stick figures staring at rectangular tablets and laptops, crude carvings of humans wearing masks during pandemic, stick figures queuing in lines at shops, simple drawings of delivery trucks and shopping carts, tribal representation of humans alone in apartments, rough etched figures driving automobiles, pigment of red ochre and black charcoal on limestone, torch-lit grotto environment, archaeological discovery feeling, primitive artistic style with surprisingly detailed modern references, somber mood." \
  "ERNIE 5.1" "Chronicles of the Screen Age"

queue_job 53 \
  "Deep cave interior wall with ancient hand-carved pictographs recording final human civilization, ochre paintings of stick figures commuting in metal boxes on roads, primitive depiction of humans eating from containers with forks, crude carvings of towering buildings and electrical towers, stick figures looking at small glowing screens constantly, tribal art showing humans isolated in small rooms, rough etchings of airplanes crossing skies and satellites orbiting earth, charcoal and red pigment on rough granite surface, flickering firelight casting shadows on carvings, haunting archaeological site atmosphere, primitive yet eerily recognizable modern scenes." \
  "ERNIE 5.1" "The Memory Wall of Homo Sapiens"

queue_job 54 \
  "Prehistoric cave wall etched with desperate farewell carvings by last humans before extinction, primitive stick figures showing modern routine including waking to alarm clocks, sitting in traffic, working at desks with computers, buying coffee in paper cups, scrolling phones while walking, crude drawings of humans in face masks and medical settings, tribal symbols for hospitals and airports, rough stone surface with layered ochre and charcoal markings, deep underground chamber with ancient torch remnants, somber earth tones, archaeological artifact feeling, primitive art style depicting recognizable 2020 human behaviors with haunting emotional weight." \
  "ERNIE 5.1" "Farewell Messages in Stone"

queue_job 55 \
  "Ancient limestone cave wall bearing primitive carvings left by extinct humans as warning to next civilization, stick figure art showing daily 2020 existence including humans glued to phones, driving cars in traffic jams, sitting in office cubicles, ordering food from phones, wearing masks in crowds, watching flat screens in dark rooms, crude tribal depictions of social gatherings replaced by video calls, rough etchings of polluted skies and plastic waste, red ochre and black charcoal pigments on textured stone, dim torchlight revealing centuries-old carvings, deeply melancholic archaeological scene, primitive yet unmistakably modern subject matter." \
  "ERNIE 5.1" "The Final Testament of Modern Man"

# --- LongCat Deep search ---
queue_job 56 \
  "A prehistoric cave painting carved into rough stone depicts humans in the year 2025 hunched over glowing rectangles, their faces illuminated by blue light in the darkness. The primitive figures sit motionless in curved formation around a central fire that pulses with wireless signals, their thumbs tapping invisible symbols on glass slabs. Hunters who once painted mammoths now capture spirit images with magic windows that freeze time. Elders gather in circles not to share oral traditions but to stare into their own private visions while ignoring the vast wilderness around them. The ancient ochre pigments show a species that had connected the entire world yet forgot how to look into each other's eyes." \
  "LongCat Deep search" "Digital Rituals of the Early 21st Century"

queue_job 57 \
  "Ancient rock art carved deep into granite shows the daily ritual of the 2020s, where metal beasts carry humans in endless migration across stone rivers. The cave wall depicts thousands of box-shaped creatures with glowing eyes, sitting in perfect gridlock formation under a grey sky, their riders staring forward in trance-like patience. Each beast breathes invisible poison that chokes the atmosphere while their masters slowly waste their lives in transit. Engineers carved their tribute to the combustion engine with sacred geometry, showing traffic lights like mystical symbols controlling the flow of civilization. The primitive figures clutch circular steering devices, worshipping their automobiles as modern deities of status and freedom." \
  "LongCat Deep search" "The Great Migration on Wheels"

queue_job 58 \
  "Prehistoric cave drawings etched into limestone walls reveal the domestic rituals of early 2000s humans who built protective caves within rectangular stone towers. The artwork shows figures pressing plastic buttons to summon food from distant lands, with refrigerated boxes humming in corners keeping provisions cold. Victims of convenience spend their days sitting on cushioned thrones watching glowing rectangles that broadcast moving specters into their dwellings. The primitive artists used ochre and charcoal to document automated cleaning machines, climate-controlled air circulating through metal veins, and the mysterious practice of ordering sustenance through speaking devices that deliver meals without hunting or gathering, erasing ancient survival skills from memory." \
  "LongCat Deep search" "Temples of Convenience"

queue_job 59 \
  "Sacred cave engravings in sandstone show the mysterious workplace rituals of 2020s humanity, where upright figures sit before glowing crystal tablets for endless cycles, typing on flat slabs that transform thought into invisible energy. The primitive drawings depict humans in identical rows under artificial sunlamps in enclosed concrete valleys, their fingers dancing across keyboards that write messages traveling at light speed. Artists carved visions of endless meetings where faces appear in small windows speaking into the void, while workers stare glassy-eyed at spreadsheets of numbers. The ancient artists documented a species that had conquered distance but chained themselves to glowing screens, trading sunlight for fluorescent illumination." \
  "LongCat Deep search" "The Paperless Labor"

queue_job 60 \
  "Ancient petroglyphs carved into cave entrances document the entertainment obsessions of early 21st century homo sapiens, who gathered in massive stone arenas to watch other humans chase spheres or perform ritual battles. The primitive artwork shows thousands of spectators rising in unified roars as warriors clash on painted fields or dancers move across illuminated stages while fans hold glowing magical windows aloft to capture the moment. Artists documented the sacred ritual of watching stories unfold on rectangular screens in dark chambers, consuming tales of distant lands while their own world outside decayed. The ochre pigments reveal a civilization that preferred watching life to living it." \
  "LongCat Deep search" "The Arena of Spectacle"

echo "✅ All 60 jobs queued in scheduler"

