#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Popotillo art (wheat straw painting) — nature, cities, typography
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+32+-+popotillo
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A traditional Mexican popotillo artwork crafted entirely from dyed wheat straw fibers, meticulously inlaid onto a dark wood panel to depict a sweeping valley landscape at sunset. Rolling hills built from countless thin straw strands in gradients of burnt orange, deep crimson, and golden yellow, each fiber catching light to create subtle metallic shimmer and texture. A winding river rendered in cool turquoise and silver straw cuts through the scene, bordered by cypress trees formed from layered emerald and olive straw mosaics. The sky above blends violet and amber straw in fine radiating lines mimicking sun rays. Folk art precision, handcrafted warmth, intricate fiber texture, museum-quality mosaic detail, square composition, warm natural lighting." \
  "Claude Sonnet 5 medium" "Popotillo Sunset Valley"

queue_job  2 \
  "An intricate popotillo mosaic composed of dyed wheat straw fibers inlaid on a deep espresso wood panel, portraying a stylized city skyline at night. Towering skyscrapers built from thin straw strips in shades of indigo, charcoal, and silver create angular geometric silhouettes against a midnight backdrop. Countless tiny straw fragments in warm amber and gold represent glowing windows scattered across the buildings, catching light like embers. A crescent moon woven from pale ivory straw glows above, surrounded by radiating straw lines suggesting starlight. Below, a reflective river of cobalt blue straw mirrors the illuminated skyline. Traditional Mexican folk art craftsmanship, fine fiber texture, handwoven precision, vibrant dyed straw palette, museum-quality detail, square composition, dramatic contrast." \
  "Claude Sonnet 5 medium" "Popotillo Skyline Nocturne"

queue_job  3 \
  "A decorative popotillo typography piece made from dyed wheat straw fibers meticulously inlaid onto a warm honey-toned wood panel, forming the bold word 'VIDA' in ornate folk-art lettering. Each letter is filled with dense straw mosaic patterns in vivid magenta, turquoise, and marigold hues, bordered by thin outlines of contrasting deep brown straw. Surrounding the lettering, delicate floral motifs bloom from straw strands in coral pink and sage green, echoing traditional Mexican folk embroidery. Fine straw striations create subtle texture and dimensional shading within each letterform. The background remains a soft cream straw weave, letting the vibrant text pop. Handcrafted precision, intricate fiber artistry, museum-quality mosaic detail, square composition, warm celebratory atmosphere." \
  "Claude Sonnet 5 medium" "Popotillo Word Art Bloom"

queue_job  4 \
  "A vibrant popotillo mosaic artwork made entirely of dyed wheat straw fibers inlaid on a rich mahogany wood panel, depicting a hummingbird hovering beside blooming hibiscus flowers. The bird's wings are formed from iridescent straw in emerald green and sapphire blue, arranged in overlapping feather-like strands that catch light dynamically. Its body features fine straw detailing in ruby red and copper tones. The hibiscus blossoms are crafted from layered straw petals in fuchsia and coral, with golden straw stamens radiating outward. Lush green foliage surrounds the scene, built from varied straw textures in forest and lime green. Traditional Mexican folk art craftsmanship, intricate fiber texture, handwoven detail, museum-quality precision, square composition, natural warm lighting." \
  "Claude Sonnet 5 medium" "Popotillo Hummingbird Garden"

queue_job  5 \
  "A radiant popotillo artwork crafted from dyed wheat straw fibers inlaid on a dark walnut wood panel, forming a symmetrical sun mandala inspired by Aztec calendar motifs. The central sun face is built from concentric rings of straw in fiery orange, deep red, and golden yellow, radiating outward in sharp triangular rays. Intricate geometric patterns encircle the sun, crafted from turquoise, obsidian black, and jade green straw arranged in precise repeating shapes. Fine straw striations add subtle texture and dimensional depth throughout the design. The outer border features a woven straw pattern in earthy terracotta tones. Traditional Mexican folk art precision, vibrant dyed straw palette, handcrafted symmetry, museum-quality fiber detail, square composition, warm dramatic lighting." \
  "Claude Sonnet 5 medium" "Popotillo Sun Mandala"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A masterfully crafted popotillo art piece displaying a stylized Aztec calendar wheel. Every single line, ring, and geometric glyph is meticulously composed of dyed natural wheat straw fibers, showcasing vibrant turquoise, deep terracotta, and brilliant gold hues. The textured straws are tightly arranged side-by-side on a dark, rustic wooden background, catching the light to create an intricate, layered mosaic effect. The central sun face features highly detailed, raised straw work. This breathtaking traditional Mexican folk art piece blends geometric precision with rich, organic textures, resulting in an eye-catching, culturally profound, and visually stunning masterpiece." \
  "Gemini 3.5 Flash" "Popotillo Art Aztec Calendar"

queue_job  7 \
  "A vibrant popotillo art interpretation of a bustling Tokyo street at night. The iconic cityscape is built entirely from thousands of slender, dyed wheat straw pieces, meticulously laid out to mimic glowing neon signs, towering skyscrapers, and reflective wet asphalt. Radiant pinks, electric blues, and vivid purples dominate the scene, contrasting sharply against a pitch-black background. Tiny, precisely cut straw fragments form the glowing kanji characters on billboards and the silhouettes of pedestrians. The unique sheen of the natural straw gives the futuristic urban landscape an incredible, unexpected organic texture, creating a spectacular fusion of ancient Mexican craft and modern metropolis." \
  "Gemini 3.5 Flash" "Popotillo Art Neon Tokyo Street"

queue_job  8 \
  "An enchanting autumn landscape rendered completely in the exquisite style of popotillo wheat straw painting. A gentle river winds through a dense forest, its shimmering water composed of slender straw fibers dyed in various shades of cerulean and silver. The riverbanks are lined with majestic trees boasting thick, layered canopies of brilliant amber, crimson, and burnt orange straws. Each individual leaf and ripple is represented by the natural, glossy texture of the precisely placed plant fibers. The composition captures the warm, golden hour light reflecting off the straw's surface, creating a peaceful, tactile, and aesthetically breathtaking vision of nature." \
  "Gemini 3.5 Flash" "Popotillo Art Autumn Forest River"

queue_job  9 \
  "A stunning piece of popotillo art capturing a swarm of monarch butterflies fluttering around a flowering oyamel fir tree. Each butterfly's wings are an intricate mosaic of intensely dyed orange and jet-black wheat straw threads, with tiny white straw dots along the edges. The background features a soft-focus mountain landscape made from muted green and earthy brown straws, creating a brilliant depth of field. The natural iridescence of the wheat straw makes the butterflies appear alive, vibrating with light and texture. This magnificent straw painting perfectly balances the delicate elegance of wildlife with the rich, tangible heritage of traditional Mexican folk media." \
  "Gemini 3.5 Flash" "Popotillo Art Monarch Butterfly Migration"

queue_job 10 \
  "An inspiring text art masterpiece created entirely through the traditional medium of popotillo straw painting. The word 'HOPE' is boldly centered, designed with elegant, flowing cursive typography where each letter is meticulously formed from layered, sun-bleached golden wheat straws. Surrounding and intertwining with the text are delicate floral flourishes and botanical vines made of emerald green and soft magenta dyed straws. The entire composition sits on a dark, textured charcoal canvas, making the brilliant natural gloss and three-dimensional relief of the straw art pop dramatically. It is a visually arresting, highly harmonious blend of modern graphic lettering and ancient artisan craftsmanship." \
  "Gemini 3.5 Flash" "Popotillo Art Typography Hope"

# --- ChatGPT ---
queue_job 11 \
  "An intricate popotillo art wheat straw painting depicting rolling terraced fields illuminated by the first golden rays of sunrise. Carefully arranged straw fibers of varying natural tones create flowing contours, shimmering highlights, and delicate textures across hills, winding paths, and distant farmhouses. Fine handcrafted detailing emphasizes the unique sheen of polished wheat straw, producing elegant gradients without paint. Tall trees, birds gliding through the morning sky, and soft drifting mist add depth and tranquility. Decorative folk-inspired borders subtly frame the composition while preserving realism. Museum-quality artisan craftsmanship, harmonious composition, refined natural palette, highly detailed handmade appearance, visually captivating, authentic popotillo technique, warm inviting atmosphere." \
  "ChatGPT" "Golden Sunrise Over Terraced Fields"

queue_job 12 \
  "A beautifully handcrafted popotillo art wheat straw painting portraying a peaceful alpine lake beneath a luminous full moon. Natural wheat straw strips are precisely cut, layered, and directionally arranged to capture shimmering reflections across calm water, textured mountain slopes, evergreen forests, and a sky filled with delicate stars. The varying grain patterns and golden hues of straw create remarkable contrast and dimensionality without artificial coloring. Elegant handcrafted precision enhances every leaf, rock, and ripple, celebrating traditional artisan techniques. Sophisticated composition balances realism with decorative beauty, creating a serene masterpiece rich in texture, warmth, and timeless craftsmanship suitable for gallery-quality folk art." \
  "ChatGPT" "Moonlit Mountain Lake Reflection"

queue_job 13 \
  "A richly detailed popotillo art wheat straw painting illustrating the charming skyline of a historic European city filled with elegant cathedrals, narrow streets, bridges, towers, and classical rooftops. Thousands of carefully aligned wheat straw fibers create radiant architectural textures, glowing windows, decorative facades, and intricate stonework through subtle changes in fiber direction and natural color. Soft afternoon sunlight enhances the reflective quality of polished straw while birds circle above the skyline. Ornamental flourishes inspired by traditional folk craftsmanship gracefully complement the architecture. Highly refined handmade artistry, exceptional precision, layered textures, balanced composition, authentic popotillo technique, aesthetically pleasing museum-quality decorative artwork." \
  "ChatGPT" "Golden Skyline of an Old European City"

queue_job 14 \
  "A sophisticated popotillo art wheat straw painting featuring the inspirational word 'HARMONY' crafted entirely from carefully layered wheat straw fibers, surrounded by abundant blooming wildflowers, graceful vines, butterflies, and flowing botanical ornaments. Every letter displays intricate variations in straw orientation that create luminous highlights, natural shadows, and remarkable dimensionality. The surrounding floral elements blend seamlessly into the typography, celebrating traditional handcrafted folk artistry with contemporary elegance. Delicate textures, polished straw surfaces, and subtle natural golden gradients produce a refined visual rhythm without paint. Highly detailed artisan craftsmanship, luxurious handmade appearance, balanced composition, eye-catching decorative design, authentic popotillo wheat straw technique." \
  "ChatGPT" "Elegant Floral Typography"

queue_job 15 \
  "An exquisite popotillo art wheat straw painting portraying a tranquil tropical shoreline at sunset with graceful palm trees, gentle ocean waves, distant islands, colorful clouds interpreted through natural straw tones, and a glowing horizon created entirely by layered wheat straw. Carefully oriented straw fibers simulate moving water, textured sand, swaying leaves, and luminous skies using only their natural sheen and direction. Fine handcrafted detailing enhances shells, tropical flowers, wooden boats, and delicate seabirds soaring overhead. Traditional artisan methods combine with elegant composition to produce a warm, immersive landscape. Authentic popotillo craftsmanship, museum-quality handmade texture, aesthetically pleasing natural palette, richly detailed decorative folk art masterpiece." \
  "ChatGPT" "Tropical Paradise at Sunset"

# --- Deepseek ---
queue_job 16 \
  "Popotillo wheat straw painting of a sprawling futuristic metropolis at golden sunset, intricate mosaic texture with thousands of tiny angled wheat strands interlocking perfectly, golden and amber strips meticulously inlaid to form towering geometric skyscrapers with reflective glass surfaces catching the dying light, warm ochre, burnt sienna, honey, and pale cream tones dominating the composition, dramatic side lighting casting long angular shadows across the straw grain revealing its natural fibrous texture, detailed aerial perspective with winding rivers represented by smooth raw sienna straw pieces, surrounding agricultural fields of natural unbleached wheat hues creating organic contrast against the rigid city grid, hyper-detailed Mexican folk art mosaic style with flat decorative aesthetic yet rich tactile grain, cinematic atmospheric glow across the entire square canvas, visually striking and meticulously crafted to celebrate this traditional medium." \
  "Deepseek" "Metropolis of Gold"

queue_job 17 \
  "Close-up popotillo art piece featuring a symmetrical sunflower mandala radiating outward, vibrant dyed wheat straw petals in deep golden yellows, bright oranges, and earthy crimson reds, each petal intricately cut and placed with precision to follow concentric spiral patterns, central core detailed with densely packed tiny straw splinters creating a textured seed head, background of natural unbleached straw with subtle diagonal weave, rich color gradient from luminous gold core to dark mahogany edges, even diffused lighting highlighting the delicate grain lines and individual piece edges, traditional Mexican folk art styling with highly ornamental symmetrical balance, sharp focus on the intricate straw mosaic technique, aesthetically warm and inviting, capturing the essence of handcrafted devotion." \
  "Deepseek" "Sunburst Mandala"

queue_job 18 \
  "Abstract popotillo wheat straw landscape painting depicting rolling desert dunes sweeping across the square frame, strips of natural and dyed straw arranged in fluid wave patterns mimicking sand ripples, color palette of pale champagne gold, honey amber, terracotta red, and chalky white straw pieces, geometric segmentation and angular cuts characteristic of straw mosaics creating a rhythmic visual flow, layered textures with overlapping pieces generating depth and gentle movement across the dunes, minimalist composition with bold negative space representing a clear sky using subtle cream straw, soft overcast lighting to emphasize the matte, non-reflective finish of the wheat, intricate interlocking joints revealing the artisan's handcrafted care, warm earthy atmosphere, visually soothing yet eye-catching, perfectly balancing abstraction with organic natural forms." \
  "Deepseek" "Desert Harmonic Dunes"

queue_job 19 \
  "Popotillo art text composition where the Spanish word 'HOGAR' is formed by intricate golden wheat straw inlays embedded within a lush desert nature scene, each letter constructed from tiny angled straw shards creating a rich gradient from pale blond to deep amber, surrounding imagery of towering agave plants and blooming cactus flowers made of green-dyed and natural straw strips with precise geometric leaf patterns, background of a starry night sky using dark indigo and charcoal straw pieces, warm firelight glow emanating from the text area to illuminate the surrounding flora, detailed folk craft texture with visible grain in every tile, balanced typography and illustrative elements working in harmony, vibrant earthy colors with subtle metallic sheen, aesthetically pleasing fusion of lettering and landscape, honoring traditional techniques." \
  "Deepseek" "HOGAR in the Wild"

queue_job 20 \
  "Detailed popotillo wheat straw mosaic of a vibrant colonial Mexican town square at twilight, featuring a grand stone church with intricate baroque facade details built from countless tiny straw inlays mimicking carved stone, surrounding arched porticos and cobblestone patterns composed of geometric straw tiles in warm ochre and terracotta, golden hour light casting soft amber highlights across the straw surface creating a cozy nostalgic atmosphere, bustling market stalls represented by colorful dyed straw shapes in teal, mustard, and rust, elevated viewpoint capturing the entire symmetrical plaza with perfect perspective, rich tapestry-like texture with contrast between smooth large pieces and rough fragmented sections, highly decorative and symmetrical layout, aesthetically charming and culturally resonant, sharp detailed execution evoking a sense of timeless celebration." \
  "Deepseek" "Colonial Pueblo Plaza"

# --- Grok fast ---
queue_job 21 \
  "A breathtaking mountain landscape rendered in traditional popotillo wheat straw mosaic art style, intricate golden straw pieces meticulously arranged to form majestic snow-capped peaks glowing under a warm sunset, reflective alpine lake in the foreground with shimmering straw reflections, pine forests detailed with layered straw textures creating depth and natural patterns, wildflowers blooming in vibrant straw hues along rocky shores, dramatic clouds swirling in the sky composed of fine straw filaments, highly detailed, aesthetically pleasing harmonious composition, rich earthy golden tones with subtle green and blue accents, masterful folk art technique showcasing the beauty of wheat straw craftsmanship, eye-catching intricate details throughout, perfect symmetry and balance in the scenic view." \
  "Grok fast" "Golden Wheat Straw Mountain Vista"

queue_job 22 \
  "Lush enchanted forest scene crafted entirely in exquisite popotillo wheat straw painting technique, towering ancient trees with textured bark made from interwoven golden straw strands reaching towards a dappled canopy, soft sunlight filtering through leaves depicted in delicate straw mosaics creating magical light patterns on the forest floor, winding path covered in fallen straw leaves leading to a hidden clearing, vibrant mushrooms and ferns in detailed straw work, ethereal mist rising with fine straw gradients, deer and birds subtly integrated into the natural composition, warm inviting atmosphere, aesthetically pleasing intricate folk art masterpiece, rich natural palette of golden yellows, earthy browns and emerald tones, captivating depth and texture." \
  "Grok fast" "Enchanted Popotillo Forest Cathedral"

queue_job 23 \
  "Futuristic yet timeless cityscape interpreted through beautiful popotillo wheat straw art, towering skyscrapers constructed from layered golden straw patterns with glowing windows made of luminous straw highlights, bustling streets below detailed with intricate straw vehicles and pedestrians, neon signs and billboards rendered in colorful straw mosaics blending traditional and modern elements, river flowing through the city center reflecting the straw-built skyline in shimmering patterns, dramatic twilight sky with purple and orange gradients formed by fine straw textures, bridges and architecture showcasing masterful craftsmanship, aesthetically pleasing dynamic composition full of energy and harmony, eye-catching detailed urban folk art." \
  "Grok fast" "Vibrant Popotillo City at Twilight"

queue_job 24 \
  "Powerful eagle in flight captured in stunning popotillo wheat straw mosaic style, majestic bird with expansive wings detailed in thousands of carefully placed golden straw feathers showing realistic texture and movement, soaring above dramatic canyon cliffs composed of stratified straw rock formations, winding river below sparkling with reflective straw elements, desert vegetation and distant mountains in intricate straw patterns, warm desert light bathing the scene in rich golden hues, clouds swirling with delicate straw wisps, highly detailed feathers and landscape elements creating depth, aesthetically pleasing symbolic composition celebrating nature and craftsmanship, captivating folk art beauty." \
  "Grok fast" "Majestic Popotillo Eagle Soaring"

queue_job 25 \
  "Dreamlike flower garden paradise created in traditional Mexican popotillo wheat straw painting, overflowing with blooming roses, sunflowers and exotic blossoms meticulously formed from vibrant colored straw pieces in intricate mosaic patterns, winding stone pathways made of textured straw tiles leading through lush greenery, ornate fountain at center with flowing water effects in layered straw, butterflies and hummingbirds hovering among flowers with delicate straw details, soft morning light casting gentle shadows enhancing the three-dimensional straw texture, harmonious pastel and golden color palette, aesthetically pleasing whimsical yet sophisticated folk art composition, eye-catching abundance of natural beauty and masterful detail." \
  "Grok fast" "Whimsical Popotillo Garden of Dreams"

# --- Copilot ---
queue_job 26 \
  "A breathtaking popotillo art depiction of a golden wheat field stretching endlessly under a radiant sky, each straw carefully arranged to mimic the shimmering texture of grain swaying in the breeze. The horizon glows with warm hues of orange and gold, blending seamlessly into soft blues above. A rustic farmhouse sits in the distance, its silhouette outlined with delicate straw patterns, while a winding dirt path leads the viewer's eye through the composition. The intricate straw textures create a tactile sense of depth, making the landscape both vibrant and serene, a harmonious balance of nature and artistry." \
  "Copilot" "Golden Wheat Landscape"

queue_job 27 \
  "A striking popotillo art interpretation of a bustling city skyline, where wheat straw is meticulously layered to form towering skyscrapers glowing under twilight. The reflective surfaces of glass buildings are recreated with shimmering straw patterns, capturing the interplay of light and shadow. Streets below pulse with energy, depicted through fine straw lines suggesting movement and rhythm. The sky transitions from deep indigo to soft lavender, enhancing the dramatic contrast between natural straw textures and modern architecture. This fusion of tradition and urban dynamism creates a visually captivating and culturally rich masterpiece." \
  "Copilot" "Urban Straw Skyline"

queue_job 28 \
  "An intricate popotillo art mandala radiating symmetry and balance, crafted entirely from wheat straw in luminous shades of gold, amber, and beige. Each geometric pattern is carefully aligned, forming concentric circles that symbolize harmony and spiritual unity. The delicate straw fibers catch light, adding a glowing effect that enhances the meditative quality of the piece. Subtle floral motifs emerge within the design, blending natural inspiration with sacred geometry. The artwork embodies both cultural heritage and timeless beauty, inviting contemplation and appreciation of craftsmanship through its mesmerizing detail." \
  "Copilot" "Sacred Straw Mandala"

queue_job 29 \
  "A serene popotillo art scene of a tranquil forest beside a reflective lake, where wheat straw is arranged to capture the delicate textures of trees and water. Tall pines rise gracefully, their straw outlines shimmering against a soft pastel sky. The lake mirrors the forest, with carefully layered straw creating rippling reflections that evoke calm and balance. A small wooden boat rests at the shore, its form outlined with fine straw detail, adding a human touch to the natural setting. The composition radiates peace, blending nature's quiet elegance with artisanal mastery." \
  "Copilot" "Straw Forest Reflections"

queue_job 30 \
  "A creative popotillo art composition where wheat straw is used to form bold, eye-catching text integrated into a mosaic of abstract shapes and patterns. Letters emerge from the straw fibers with tactile precision, glowing in golden tones against a backdrop of geometric designs. The interplay of text and form creates a dynamic visual rhythm, balancing readability with artistic abstraction. Subtle accents of color highlight certain words, while the straw's natural sheen adds depth and vibrancy. This piece demonstrates the versatility of popotillo art, merging communication and aesthetics into a unified masterpiece." \
  "Copilot" "Straw Text Mosaic"

# --- Mistral ---
queue_job 31 \
  "Popotillo art style, intricate wheat straw textures meticulously arranged to depict a serene rural meadow at the break of dawn, with golden light filtering through gently rolling hills of straw, soft warm hues of amber, gold, and honey blending seamlessly across the landscape, delicate straw weave patterns forming the illusion of grass, wildflowers, and distant trees, creating a peaceful and harmonious atmosphere where nature's beauty is captured in every carefully placed straw, soft gradients transitioning from the brightening sky to the shadowed earth, detailed foreground featuring individual wheat stalks and blades with visible texture, distant misty trees adding depth and scale, aesthetic balance between light and shadow, eye-catching composition with natural symmetry, traditional craftsmanship evident in the organic material's beauty, soft shadows cast by the rising sun, a golden hour glow illuminating the entire scene, evoking warmth, nostalgia, and tranquility through subtle texture variations and a harmonious earth-toned palette." \
  "Mistral" "Golden Straw Meadow at Dawn"

queue_job 32 \
  "Popotillo art style, wheat straw textures forming a vibrant urban skyline at sunset, golden and orange hues reflecting off straw-built skyscrapers, delicate weave patterns creating windows, streets, and architectural details, a bustling city life captured in organic material, soft gradients from the setting sun painting the scene in warm colors, detailed foreground with straw-textured buildings and streets, distant silhouettes of more structures, aesthetic balance between the urban environment and natural straw material, eye-catching composition with vertical and horizontal elements, traditional craftsmanship in every straw placement, organic material beauty, soft shadows from the low sun, sunset glow illuminating the cityscape, evoking modern beauty and warmth, subtle texture variations, harmonious blend of urban and natural elements, artistic depth through layering." \
  "Mistral" "Wheat Straw Cityscape at Sunset"

queue_job 33 \
  "Popotillo art style, intricate wheat straw arranged to form elegant text art and calligraphy, golden straw creating poetic phrases or meaningful words with stunning visual impact, delicate weave patterns forming each letter and character, soft warm hues enhancing the artistic typography, nature-inspired design elements integrated into the text, detailed foreground with individual straw pieces visible, aesthetic balance between the text and negative space, eye-catching composition with perfect letter spacing, traditional craftsmanship in the straw manipulation, organic material beauty, soft shadows adding depth to the letters, golden light illuminating the text, evoking artistic elegance and natural harmony, subtle texture variations in the straw, harmonious color palette, artistic depth through dimensional straw placement." \
  "Mistral" "Straw Text Art Calligraphy"

queue_job 34 \
  "Popotillo art style, wheat straw textures creating a magical forest path, dappled sunlight filtering through straw-woven trees, golden and green hues blending in the enchanted atmosphere, delicate weave patterns forming leaves, branches, and forest floor details, a mystical and serene environment captured in organic material, soft gradients of light and shadow playing across the scene, detailed foreground with individual straw pieces forming moss, rocks, and path elements, distant forest depth, aesthetic balance between light and dark areas, eye-catching composition with natural forest symmetry, traditional craftsmanship in every straw, organic material beauty, soft shadows from the canopy above, magical glow illuminating the path, evoking wonder and tranquility, subtle texture variations, harmonious color palette of forest tones." \
  "Mistral" "Enchanted Straw Forest Path"

queue_job 35 \
  "Popotillo art style, wheat straw textures forming a picturesque coastal village, golden thatched roofs and straw-built houses along a serene shoreline, soft warm hues of sunset reflecting on the straw and water, delicate weave patterns creating architectural details, boats, and coastal elements, a peaceful seaside life captured in organic material, soft gradients from the setting sun painting the sky and sea, detailed foreground with straw-textured buildings and docks, distant horizon with more village structures, aesthetic balance between land and water, eye-catching composition with horizontal and vertical elements, traditional craftsmanship in every straw placement, organic material beauty, soft shadows from the low sun, sunset glow illuminating the village, evoking coastal tranquility and warmth, subtle texture variations, harmonious blend of natural and man-made elements." \
  "Mistral" "Coastal Straw Village"

# --- QWEN 3.7 Plus ---
queue_job 36 \
  "A breathtaking nature landscape crafted entirely in traditional popotillo wheat straw mosaic art. The scene depicts a serene mountain valley with a winding river reflecting the bright sky. Intricate, fine parallel strips of dyed and natural golden wheat straw form the textured terrain, lush pine forest, and majestic snow-capped peaks. The artwork beautifully showcases the unique sheen and fibrous grain of the straw, creating a mesmerizing, eye-catching composition. Vibrant emerald greens, deep earthy browns, and brilliant sky blues are achieved through meticulously placed straw segments. The overall aesthetic is highly detailed, visually striking, and celebrates the beautiful, tactile essence of this unique folk art medium." \
  "QWEN 3.7 Plus" "Serene Mountain Valley Popotillo Landscape"

queue_job 37 \
  "A vibrant, eye-catching cityscape rendered in exquisite popotillo wheat straw painting technique. The image features a historic colonial town with colorful terracotta roofs, cobblestone streets, and brightly painted facades. Thousands of tiny, meticulously aligned wheat straw strips create the textured architecture, casting subtle shadows and highlighting the natural fibrous grain of the material. Dyed straws in brilliant ochre, crimson, and cobalt blue contrast beautifully with natural golden tones. The mosaic-like composition captures the bustling energy of the city through intricate parallel lines and geometric patterns. The overall aesthetic is aesthetically pleasing, rich in cultural heritage, and showcases the remarkable versatility and luminous quality of traditional straw mosaic artistry." \
  "QWEN 3.7 Plus" "Colonial Cityscape in Wheat Straw Mosaic"

queue_job 38 \
  "An aesthetically pleasing typographic artwork featuring the word NATURE, created entirely through traditional popotillo wheat straw mosaic technique. The bold, elegant letters are formed by thousands of meticulously aligned, finely cut strips of natural and dyed wheat straw. The text displays a stunning gradient of vibrant leaf greens, rich earthy browns, and golden yellows, mimicking the colors of a lush forest. The fibrous texture and natural sheen of the straw give the letters a three-dimensional, tactile appearance against a dark, contrasting background. Intricate parallel lines and subtle geometric shading within the typography highlight the masterful craftsmanship. This eye-catching text art beautifully merges modern design with ancient folk art traditions." \
  "QWEN 3.7 Plus" "Typographic Nature in Popotillo Style"

queue_job 39 \
  "A stunning, close-up botanical illustration of a blooming sunflower, masterfully crafted in popotillo wheat straw mosaic art. The intricate petals are formed by hundreds of fine, radiating strips of dyed golden and vibrant orange wheat straw, showcasing the material's natural fibrous grain and luminous sheen. The dark, textured center of the flower is created using tightly packed, deep brown and black straw segments, providing a striking visual contrast. Delicate green leaves frame the blossom, utilizing varying shades of emerald and lime straws to create depth through parallel line shading. This eye-catching artwork is aesthetically pleasing, highly detailed, and perfectly captures the organic beauty and unique tactile qualities of traditional straw painting." \
  "QWEN 3.7 Plus" "Blooming Sunflower Wheat Straw Botanical"

queue_job 40 \
  "An eye-catching abstract geometric mandala, meticulously constructed using the traditional popotillo wheat straw mosaic technique. The design features complex, symmetrical patterns of interlocking circles, starbursts, and sweeping curves, all formed by thousands of precisely aligned, finely cut strips of wheat straw. The artwork utilizes a rich, harmonious palette of deep indigo, vibrant magenta, radiant gold, and natural straw tones. The parallel lines of the straw create a mesmerizing optical effect, emphasizing the fibrous texture and natural sheen of the medium. This aesthetically pleasing composition highlights the incredible precision and craftsmanship of straw painting, transforming simple agricultural material into a breathtaking, highly detailed, and visually striking masterpiece of folk art." \
  "QWEN 3.7 Plus" "Abstract Geometric Mandala Popotillo Art"

# --- GLM 5.2 ---
queue_job 41 \
  "A breathtaking nature landscape rendered in traditional Mexican popotillo wheat straw painting art. A majestic mountain range under a glowing sunset, with vibrant orange, magenta, and deep purple skies crafted from meticulously placed dyed straw fibers. A winding river reflects the golden light, shimmering with the natural glossy texture of the polished wheat straw. Intricate details in the foreground pine trees, showcasing varied lengths, precise cuts, and angles of straw. The artwork features an aesthetically pleasing, tactile mosaic surface with a striking play of light and shadow. Highly detailed, eye-catching craftsmanship, fine art straw mosaic, rich warm autumn color palette, traditional cultural heritage artwork, masterpiece." \
  "GLM 5.2" "Golden Sunset Valley"

queue_job 42 \
  "An eye-catching futuristic cityscape created entirely in the traditional popotillo wheat straw painting style. Towering skyscrapers illuminated by vibrant neon pink, electric blue, and glowing yellow dyed straw fibers. The intricate mosaic technique captures the glowing reflections on wet city streets, using the natural sheen of the wheat straw to simulate artificial lights. Flying vehicles streak across the dark sky, formed by precisely cut golden straws. Aesthetically pleasing geometric patterns and meticulous fiber placement create a stunning tactile texture. The fusion of ancient Mexican folk art and cyberpunk aesthetics results in a visually striking, highly detailed masterpiece of contemporary straw mosaic craftsmanship." \
  "GLM 5.2" "Neon Straw Metropolis"

queue_job 43 \
  "A stunning typography artwork spelling the word DREAM, masterfully crafted using traditional popotillo wheat straw painting techniques. The letters are formed by meticulously placed, brightly dyed wheat straw fibers in shades of emerald green, sapphire blue, and radiant gold. Surrounding the text is an aesthetically pleasing pattern of swirling vines and blooming floral motifs, each petal and leaf defined by the precise angles, fine cuts, and natural glossy texture of the straw. The background features a contrasting dark, matte wooden surface to make the vibrant straw mosaic pop. Highly detailed, eye-catching artisanal craft, intricate tactile relief, beautiful color gradients, fine art typography masterpiece." \
  "GLM 5.2" "Straw Mosaic Dream Typography"

queue_job 44 \
  "A majestic peacock proudly displaying its magnificent tail, depicted in exquisite Mexican popotillo wheat straw painting art. The iridescent feathers are intricately constructed using dyed straw fibers in brilliant teal, indigo, and emerald green. The eye patterns on the feathers showcase the glossy, reflective quality of the cut wheat straw, creating an aesthetically pleasing shimmer. The bird's body features fine golden and brown straw textures, meticulously placed to mimic delicate plumage. Set against a simple, elegant backdrop, the tactile mosaic surface and precise craftsmanship make this traditional folk art piece incredibly eye-catching. Highly detailed straw mosaic, rich vibrant colors, beautiful tactile artwork, nature-inspired masterpiece." \
  "GLM 5.2" "Iridescent Straw Peacock"

queue_job 45 \
  "A mesmerizing geometric abstract composition rendered in the traditional popotillo wheat straw painting style. Intricate concentric circles and sharp angular patterns intertwine, created using meticulously cut and dyed wheat straw fibers. The color palette features striking contrasting tones of deep crimson, mustard yellow, midnight black, and natural beige straw. The natural glossy texture of the wheat straw creates a dynamic play of light and shadow across the precisely placed mosaic pieces, giving the flat surface a three-dimensional optical illusion. Aesthetically pleasing, eye-catching modern folk art, tactile relief, masterful artisanal craftsmanship, symmetrical balance, highly detailed organic material collage, contemporary traditional fusion." \
  "GLM 5.2" "Geometric Straw Illusion"

# --- Kimi K2.6 Thinking ---
queue_job 46 \
  "A stunning popotillo art composition depicting a dramatic sunset over ancient mountain peaks, meticulously crafted from hand-dyed wheat straw in rich gradients of burnt orange, deep crimson, and golden amber. The traditional Mexican folk art technique showcases thousands of individually placed straw fragments forming layered ridgelines that dissolve into atmospheric haze. Intricate cut-straw details define rocky textures while whole straw pieces create smooth sky transitions. The radiant sun, composed of radiating golden straw segments, casts warm light across the textured landscape. Deep earth tones contrast with luminous highlights, demonstrating masterful craftsmanship. This museum-quality wheat straw mosaic celebrates cultural heritage through breathtaking natural scenery, with each precisely placed element contributing to an awe-inspiring panoramic vista." \
  "Kimi K2.6 Thinking" "Sunset Over Ancient Mountains"

queue_job 47 \
  "A vibrant popotillo art cityscape depicting a futuristic metropolitan skyline at twilight, created entirely from dyed wheat straw in electric blues, magenta, neon pink, and deep violet tones. The traditional Mexican straw mosaic technique reimagines urban architecture through thousands of precisely cut straw fragments forming towering skyscrapers with illuminated windows. Reflective waterways below mirror the city lights using iridescent straw pieces. The composition balances geometric precision with organic straw texture, creating a striking contrast between folk art tradition and modern subject matter. Layered depth achieved through varying straw lengths and dye intensities. This contemporary wheat straw painting transforms urban energy into a tactile, visually captivating masterpiece that bridges cultural heritage with futuristic aesthetics." \
  "Kimi K2.6 Thinking" "Neon Metropolitan Skyline"

queue_job 48 \
  "An exquisite popotillo art nature scene depicting a lush tropical paradise, masterfully crafted from hand-dyed wheat straw in vibrant emerald greens, turquoise blues, and sunlit gold tones. The traditional Mexican folk art technique brings to life dense jungle foliage, cascading waterfalls, and exotic birds through thousands of individually placed straw fragments. Intricate cut-straw details define palm fronds and flowering vines while gradient dye work creates atmospheric depth in misty background mountains. A crystal-clear lagoon reflects the surrounding paradise using carefully selected iridescent straw pieces. The composition celebrates biodiversity and natural beauty through the tactile warmth of wheat straw. Each precisely placed element showcases exceptional craftsmanship, transforming organic material into a breathtaking immersive landscape that honors both tradition and nature's splendor." \
  "Kimi K2.6 Thinking" "Lush Tropical Paradise"

queue_job 49 \
  "A mesmerizing popotillo art composition integrating elegant typography with a serene forest landscape, meticulously crafted from hand-dyed wheat straw in rich forest greens, warm browns, and golden sunlight tones. The traditional Mexican folk art technique spells out the word 'GROW' using intricately arranged straw fragments that seamlessly transform into towering oak trees and winding vines. Thousands of precisely cut straw pieces create layered canopy depth, dappled light filtering through leaves, and textured bark details. The letterforms dissolve organically into the natural scenery, demonstrating masterful integration of text and image. Subtle gradient dye work captures atmospheric perspective in misty background glades. This contemporary wheat straw mosaic celebrates the harmony between human expression and natural beauty through exceptional craftsmanship." \
  "Kimi K2.6 Thinking" "Typography Forest Harmony"

queue_job 50 \
  "A breathtaking popotillo art seascape capturing powerful ocean waves crashing against rocky cliffs at dawn, masterfully created from hand-dyed wheat straw in deep navy blues, foamy whites, coral pinks, and golden sunrise tones. The traditional Mexican folk art technique translates fluid water motion into thousands of individually placed straw fragments, with curved cut-straw pieces suggesting dynamic wave movement and spray. Intricate layering creates translucent water effects and textured rock surfaces. The rising sun, composed of radiating amber and gold straw segments, illuminates the dramatic coastal scene. Precise gradient dye work captures the interplay of light on water and wet stone. This museum-quality wheat straw mosaic celebrates nature's raw power and serene beauty through exceptional tactile craftsmanship and cultural artistry." \
  "Kimi K2.6 Thinking" "Ocean Waves at Dawn"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A stunning popotillo wheat straw painting depicting a golden sunset over rolling green hills, warm amber and burnt sienna tones forming the sky with delicate straw textures creating soft gradients, a small rustic farmhouse silhouetted against the glowing horizon, wheat fields in the foreground rendered in fine golden straw strands with intricate woven detail, birds in flight suggested by thin curved straw pieces, rich textural depth showing individual straw fibers, warm earth tones dominating, folk art aesthetic with meticulous craftsmanship, natural lighting, rustic Mexican artisan style, handmade straw art, breathtaking countryside vista composed entirely of wheat straw." \
  "ERNIE 5.1" "Golden Wheat Sunset Over Rolling Hills"

queue_job 52 \
  "A captivating popotillo wheat straw painting of a charming Mexican village at twilight, a white adobe church with terracotta roof central to the composition, cobalt blue and deep purple straw forming the evening sky, warm orange lantern light glowing from windows crafted in layered straw, bougainvillea vines in magenta and pink using thin curled straw pieces, cobblestone pathway leading to the church door with textured straw paving, mountains in the distant background using pale tan straw, stars twinkling in the upper sky, intricate straw weaving showing traditional craftsmanship, folk art beauty, serene atmosphere, detailed textures throughout." \
  "ERNIE 5.1" "Mexican Village Church at Twilight"

queue_job 53 \
  "A magnificent popotillo wheat straw painting featuring a dramatic coastal cliff lighthouse at dawn, towering white and red striped lighthouse rendered in tightly woven straw, crashing turquoise and seafoam waves below made from layered blue and white straw strands, rocky cliff face in earthy brown and grey straw textures, soft pink and peach sunrise sky with radiating straw sunbeams, seagulls soaring overhead depicted by elegant curved straw silhouettes, wildflowers dotting the cliff top in yellow and lavender straw, misty ocean horizon blending into pale sky, rich dimensional texture, traditional Mexican straw art mastery, breathtaking seascape with incredible depth and warmth." \
  "ERNIE 5.1" "Coastal Cliff Lighthouse at Dawn"

queue_job 54 \
  "An enchanting popotillo wheat straw painting of a mystical forest pathway in autumn, towering trees with canopies of crimson, burnt orange, and golden yellow straw leaves creating a tunnel effect, a winding dirt path through the center using layered brown straw textures, sunlight filtering through branches in delicate pale gold straw rays, mushrooms and fallen leaves scattered along the ground in varied autumn tones, a small wooden bridge over a babbling stream with blue and silver straw water, deer peeking from behind a tree trunk, rich warm palette, incredible woven detail, folk art wonder, magical atmosphere, handcrafted straw artistry throughout." \
  "ERNIE 5.1" "Enchanted Forest Pathway in Autumn"

queue_job 55 \
  "A lively popotillo wheat straw painting of a bustling Oaxaca market square, colorful market stalls with striped awnings in red, green, and yellow straw, vendors selling fruits and flowers rendered in vivid straw colors, ornate colonial archways framing the scene with intricate straw details, cobblestone plaza in warm tan and grey woven straw, parrot and tropical bird motifs on banners, colorful papel picado flags strung overhead in multicolored straw, mountain backdrop in soft blue haze, warm golden afternoon light, joyful festive energy, traditional Mexican folk art medium, extraordinary texture and craftsmanship, eye-catching composition." \
  "ERNIE 5.1" "Vibrant Market Square in Oaxaca"

# --- LongCat ---
queue_job 56 \
  "A stunning popotillo art wheat straw mosaic depicting a dramatic sunset over a serene lake and mountain landscape. Thousands of tiny dyed straw fibers in brilliant oranges, deep reds, golden yellows, and rich purples are carefully arranged to create a shimmering textured surface that catches the light. The natural luster of the straw creates an iridescent quality, with each individual piece visible upon close inspection. The composition features layered mountain silhouettes in the background, a glowing sun melting into the horizon, reflective water with intricate ripple patterns, and foreground desert vegetation including cacti and agave plants. The craftsmanship shows the characteristic precision of traditional Mexican popotillo technique, with smooth gradients achieved through meticulous color transitions between straw pieces. The overall effect is luminous, rich in cultural heritage, and visually captivating." \
  "LongCat" "Popotillo Wheat Straw Mosaic Sunset Landscape"

queue_job 57 \
  "An eye-catching popotillo wheat straw text art piece featuring the bold Spanish phrase 'VIVA MEXICO' spelled out in elaborate decorative lettering. Each letter is composed of countless tiny pieces of dyed straw, creating a rich mosaic texture with brilliant colors including emerald greens, fiery oranges, royal blues, hot pinks, and sunshine yellows. The letters feature intricate ornamental flourishes and are surrounded by traditional Mexican folk art motifs such as flowers, leaves, and geometric patterns characteristic of Otomi textile designs. The background is a warm cream color that allows the vibrant straw colors to pop dramatically. The straw's natural glossy finish creates subtle light reflections across the entire composition. This piece showcases the extraordinary detail possible with popotillo technique, where each fine straw fragment is placed by hand into warm beeswax. The result is a culturally rich, texturally complex celebration of Mexican heritage that honors pre-Hispanic artistic traditions." \
  "LongCat" "Popotillo Art Text Design VIVA"

queue_job 58 \
  "A magnificent popotillo wheat straw mosaic portraying a vibrant Mexican colonial cityscape at golden hour. The artwork uses thousands of hand-dyed straw pieces to capture terracotta rooftops, whitewashed walls, blue and yellow Talavera tile details, and winding cobblestone streets. Bougainvilleas cascade in vivid magenta and fuchsia over garden walls, while palm trees and pepper trees provide dappled shadows rendered in various shades of green straw. The central plaza features a traditional kiosk with intricate metalwork details painstakingly recreated in tiny straw fragments. The straw mosaic technique creates a distinctive textured surface with subtle dimensionality, as each piece reflects light differently. The color palette draws from traditional Mexican art: cobalt blue, burnished gold, terracotta, cactus green, and sun-bleached white. The composition captures the warmth and architectural beauty of a colonial Mexican town, with layered hills in the background and dramatic clouds gathering above. This piece exemplifies how popotillo masters transform agricultural materials into sophisticated urban landscapes." \
  "LongCat" "Popotillo Wheat Straw Mexican Cityscape"

queue_job 59 \
  "A breathtaking popotillo wheat straw painting capturing the magical moment of monarch butterfly migration through the oyamel forests of central Mexico. Millions of monarch butterflies with wings of brilliant orange, black, and white are depicted through thousands of tiny dyed straw fragments, creating a sense of movement and ethereal beauty. The butterflies surround ancient trees whose bark texture is rendered in deep browns and natural straw tones, while forest floor details include wildflowers, moss, and fallen leaves in miniature mosaic style. Light filters through the canopy in golden shafts, created by layering translucent yellow and amber straw pieces to achieve luminosity. The artwork showcases the extraordinary capability of popotillo technique to create depth and atmospheric effects through careful color placement and the inherent reflective qualities of natural straw fibers. Rich reds, deep blacks, and creamy whites build the iconic monarch pattern, while the surrounding forest emerges in muted greens and earth tones. This nature scene honors both the ecological wonder of migration and Mexico's heritage of straw mosaic artistry." \
  "LongCat" "Popotillo Art Monarch Butterfly Migration"

queue_job 60 \
  "A mesmerizing popotillo wheat straw mosaic featuring an intricate geometric abstract pattern inspired by pre-Hispanic Mexican codices and indigenous textile designs. The composition features repeating diamond shapes, zigzag patterns, stepped frets, and stylized lightning bolts arranged in a symmetrical mandala-like formation. Bold, saturated colors dominate: electric blues, fiery reds, sunburst oranges, deep blacks, and brilliant whites combine in high-contrast arrangements. The straw mosaic technique creates a rich textured surface where each tiny piece of straw acts as a pixel in a larger digital-like image, yet retains organic warmth and handcrafted character. Borders featuring stylized serpents, stars, and floral motifs frame the central geometric composition. The natural sheen of the straw adds subtle dimensionality, with light creating shifting highlights across the surface as the viewer's perspective changes. This contemporary interpretation of traditional popotillo art demonstrates the medium's versatility beyond figurative imagery, celebrating Mexico's rich visual heritage through color, pattern, and extraordinary handcraftsmanship with natural materials." \
  "LongCat" "Popotillo Geometric Abstract Pattern"

echo "✅ All 60 jobs queued in scheduler"

