#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}


# --- AI Art 31: 3D Papercut Sculpture Theme ---

# Claude Sonnet 5 medium
queue_job 1 \
  "A multi-layered 3D papercraft diorama of a dramatic canyon at sunrise, dozens of hand-cut paper strata stacked with visible depth and soft shadow gaps between layers, warm amber and burnt-orange gradients transitioning into deep violet shadows, a winding paper river cut in thin blue-white strips catching light at the canyon floor, silhouetted paper cacti and wind-carved rock spires in the foreground, delicate paper clouds suspended on invisible layers overhead, subtle craft-paper texture and visible cut edges, soft studio lighting casting realistic layered shadows, macro photography style, tilt-shift depth of field, miniature diorama aesthetic, vibrant yet tactile color palette, pristine craftsmanship, centered symmetrical composition." \
  "Claude Sonnet 5" "Layered Canyon Sunrise"

queue_job 2 \
  "An intricate 3D papercraft cityscape built from stacked layers of cut cardstock, skyscrapers of varying heights rising in receding depth planes, warm golden dusk light glowing behind the skyline in a smooth paper gradient from coral to indigo, tiny paper-cut windows glowing amber, layered paper clouds drifting between buildings, a winding paper river or street reflecting the sunset colors, subtle drop shadows between each layer emphasizing dimensionality, visible paper grain and clean laser-cut edges, miniature diorama photography style with shallow depth of field, cinematic soft lighting, balanced and eye-catching composition, richly saturated yet elegant color harmony, professional handcraft aesthetic." \
  "Claude Sonnet 5" "Paper City Skyline at Dusk"

queue_job 3 \
  "A multi-tiered 3D papercraft forest scene centered on a cascading waterfall, sculpted from stacked layers of textured cut paper in emerald, moss, and deep pine tones, the waterfall rendered as overlapping curved white paper strips catching soft light, silhouetted paper pine trees and ferns arranged in staggered depth layers, delicate paper mist rising near the base, dappled sunlight beams cut from translucent vellum paper filtering through the canopy, small paper birds in flight, visible craft-paper texture and hand-cut edges throughout, soft diorama-style shadows between layers, macro tilt-shift photography aesthetic, warm inviting color palette, intricate yet clean composition, gallery-quality craftsmanship." \
  "Claude Sonnet 5" "Layered Forest Waterfall"

queue_job 4 \
  "A vibrant multi-layered 3D papercraft underwater reef scene, coral formations built from stacked cut-paper shapes in coral-pink, turquoise, and violet gradients, layered paper waves rippling above suggesting sunlit water, schools of small paper fish arranged at varying depths for parallax effect, a paper sea turtle gliding through the mid-layer, delicate paper bubbles rising toward the surface, soft caustic light patterns cut from translucent paper, visible paper texture and precise laser-cut edges, gentle shadows separating each layer for tactile depth, macro diorama photography style, tilt-shift focus, richly saturated yet harmonious palette, whimsical and eye-catching composition, refined artisanal craftsmanship." \
  "Claude Sonnet 5" "Papercraft Ocean Reef"

queue_job 5 \
  "A charming 3D papercraft diorama of a terraced mountain village at golden hour, layered paper rice terraces curving around a central paper mountain peak, small cut-paper houses with warm glowing windows nestled along the terraces, wispy paper clouds drifting at varying depths through the valley, a narrow paper footpath winding upward between layers, distant snow-capped peaks rendered in soft blue-white gradients, warm amber sunlight raking across the layered paper landscape casting soft directional shadows, visible cut-paper texture and crisp edges, tilt-shift macro photography style, cozy inviting color palette, intricate handcrafted detail, balanced centered composition, serene and eye-catching atmosphere." \
  "Claude Sonnet 5" "Terraced Mountain Village"

# Gemini 3.5 Flash
queue_job 6 \
  "A multi-layered 3D papercraft sculpture depicting a deep river gorge during autumn. The foreground features intricate, sharp silhouette cutouts of dark walnut trees and jagged rocks. Mid-ground layers reveal cascading paper waterfalls flowing into a winding river made of layered translucent vellum paper. Deep amber, crimson, and golden-orange paper layers form the dense forest on the canyon walls, stacked sequentially to create immense depth. In the background, soft mist rises between stylized paper mountains under a pale cream sky. Delicate, clean edge cuts and subtle drop shadows between every layer emphasize the tactile, physical paper medium, illuminated by warm, diffused overhead lighting." \
  "Gemini 3.5 Flash" "The Enchanted Autumn Gorge"

queue_job 7 \
  "A multi-layered 3D papercraft sculpture of a sprawling, futuristic steampunk city. The front layer showcases laser-cut silhouette fire escapes, detailed street lamps, and tiny pedestrian figures on a paper balcony. Deeper layers reveal concentric rings of intricate, overlapping gears, cogs, and clock faces made from textured metallic bronze and copper paper. Tall, geometric skyscrapers built from stacked cardstock rise in the mid-ground, featuring glowing windows created by back-lit cream paper. The furthest background layers display massive floating airships and stylized exhaust plumes cut from matte charcoal cardstock. The composition uses precise spacing, distinct paper edges, and dramatic side lighting to cast deep, realistic shadows." \
  "Gemini 3.5 Flash" "The Steampunk Clockwork Metropolis"

queue_job 8 \
  "A multi-layered 3D papercraft sculpture of a vibrant underwater coral reef. The outermost layer consists of delicate, lace-like sea fan silhouettes and waving kelp strands cut from deep teal paper. Moving inward, successive layers feature highly detailed, dimensional paper cutouts of brain coral, sea anemones, and schools of tiny tropical fish swimming through negative space. The paper colors transition from vivid neon pinks, electric blues, and glowing yellows to dark navy blue in the deepest background layer. Each element is slightly elevated on foam spacers, creating realistic physical depth. Soft, cool-toned lighting hits the edges of the textured cardstock, accentuating the clean cuts and sculptural shadows." \
  "Gemini 3.5 Flash" "The Bioluminescent Coral Reef"

queue_job 9 \
  "A multi-layered 3D papercraft sculpture capturing a serene winter forest. The immediate foreground features thick, textured white birch trunks with precise, dark gray ink-drawn bark details, standing out sharply. Successive mid-ground layers showcase progressively smaller, stylized bare branches and evergreen trees cut from pale mint and sage green paper, arranged to give an illusion of vast distance. A tiny, detailed paper silhouette of a stag stands perfectly framed between the central trees. The final background layer is a soft, solid lavender cardstock sky featuring a delicate, crescent moon cutout. Clear physical separation between the paper sheets creates soft, natural drop shadows under diffused, clean studio lighting." \
  "Gemini 3.5 Flash" "The Whispering Birch Forest"

queue_job 10 \
  "A multi-layered 3D papercraft sculpture representing a bustling cyberpunk cityscape at night. The closest layer features detailed, silhouette wire meshes, utility poles, and hanging paper lanterns. Behind it, layers of dense, stacked high-rises are constructed from dark matte black and charcoal gray cardstock. Interspersed between the buildings are vibrant, embedded strips of neon pink, cyan, and electric violet paper representing glowing holographic advertisements and signs. The background layers reveal distant, towering mega-structures and a massive, stylized full moon cut from textured off-white paper. Every layer is sharply cut with distinct edges, casting intricate, dramatic shadows that highlight the complex, physical construction of the paper artwork." \
  "Gemini 3.5 Flash" "The Neo-Tokyo Skyline"

# ChatGPT
queue_job 11 \
  "A meticulously crafted multi-layered 3D papercraft sculpture depicting an enchanted forest at dawn, composed of dozens of precision-cut paper layers that gradually reveal towering pine trees, graceful birches, winding woodland paths, delicate ferns, mushrooms, wildflowers, and a crystal-clear stream flowing toward the foreground. Soft rolling mist is represented by translucent vellum paper between the layers, while tiny birds, butterflies, deer, and foxes emerge from hidden openings. Every paper edge is clean and crisp with elegant shadows enhancing remarkable depth. Warm golden sunrise light filters through the intricate composition, emphasizing refined craftsmanship, harmonious color transitions, sophisticated textures, premium gallery-quality presentation, highly aesthetic, serene, magical, visually captivating." \
  "ChatGPT" "Whispering Forest Layers"

queue_job 12 \
  "A breathtaking multi-layered 3D papercraft sculpture portraying a magnificent floating city suspended above soft cloud formations, featuring elegant towers, domed buildings, graceful bridges, rooftop gardens, cascading waterfalls, airships, and soaring birds, all constructed from precisely cut layered paper with extraordinary dimensional depth. Every architectural element is stacked to create dramatic perspective, while subtle pastel gradients and metallic paper accents enhance visual richness. Wisps of clouds made from translucent paper weave between the structures, producing soft atmospheric separation. Gentle morning sunlight illuminates every intricate detail, casting beautiful layered shadows that celebrate exceptional papercraft artistry, imaginative fantasy architecture, refined craftsmanship, elegant composition, luxurious artistic presentation, highly decorative." \
  "ChatGPT" "Floating City Above the Clouds"

queue_job 13 \
  "A stunning multi-layered 3D papercraft sculpture illustrating a peaceful mountain valley during peak autumn, featuring layered mountain ranges, dense forests with brilliant red, orange, and golden foliage, winding rivers, waterfalls, charming wooden cabins, elegant suspension bridges, and a tranquil temple overlooking the landscape. Each precisely cut paper layer creates remarkable depth, revealing hidden details with every visual level. Intricate leaves, birds, and drifting clouds enrich the composition while delicate paper textures enhance realism without losing the handcrafted aesthetic. Soft afternoon sunlight creates dramatic shadow play across the layered artwork, producing an elegant museum-quality paper sculpture that feels warm, inviting, harmonious, visually rich, and exceptionally refined." \
  "ChatGPT" "Autumn Mountain Sanctuary"

queue_job 14 \
  "A highly detailed multi-layered 3D papercraft sculpture showcasing a picturesque coastal village beneath a luminous full moon, composed of carefully stacked paper layers representing dramatic cliffs, charming cottages, winding stone streets, sailing boats, rugged shorelines, gentle ocean waves, distant lighthouses, and graceful seabirds. The sea is formed with flowing layered curves that create convincing movement, while translucent paper elements represent moonlit reflections and sea mist. Deep navy, silver, white, and muted teal papers establish an elegant nighttime palette. Crisp laser-cut precision, sophisticated layering, rich dimensional shadows, exquisite craftsmanship, balanced composition, peaceful atmosphere, premium artistic presentation, eye-catching decorative beauty, and exceptional visual depth define the entire sculpture." \
  "ChatGPT" "Moonlit Coastal Village"

queue_job 15 \
  "A magnificent multi-layered 3D papercraft sculpture celebrating the four seasons within one harmonious botanical garden, where spring blossoms, vibrant summer flowers, colorful autumn trees, and delicate winter evergreens seamlessly transition across the layered composition. Intricately cut arches, gazebos, winding garden paths, ornamental ponds, elegant fountains, butterflies, songbirds, koi fish, and flowering vines emerge from successive paper layers, creating extraordinary three-dimensional depth. Carefully coordinated colors flow naturally between each seasonal section while soft ambient lighting enhances every crisp paper edge and shadow. Fine handcrafted precision, luxurious artistic design, graceful symmetry, premium layered paper textures, highly aesthetic composition, museum-quality craftsmanship, visually mesmerizing, sophisticated contemporary papercraft sculpture." \
  "ChatGPT" "Blooming Garden of Seasons"

# Grok Fast
queue_job 16 \
  "A highly detailed multi-layered 3D papercraft sculpture depicting a serene mountain landscape at golden hour, intricate cut paper layers creating depth with snow-capped peaks rising dramatically, dense evergreen forests in varying shades of green paper, a crystal-clear alpine lake reflecting the scene with subtle paper ripples, mist rolling through valleys formed by delicate layered silhouettes, warm sunlight casting soft shadows between paper strata, birds soaring in the sky with fine paper wing details, foreground wildflowers and rocks in textured paper cuts, overall harmonious composition with precise folds and edges emphasizing the tactile papercraft artistry, vibrant yet natural color palette, aesthetically pleasing balanced composition." \
  "Grok Fast" "Majestic Mountain Papercraft Panorama"

queue_job 17 \
  "Intricate multi-layered 3D papercraft sculpture of a bustling futuristic city at dusk, towering skyscrapers with glowing window patterns cut from layered iridescent paper, busy streets filled with paper-cut vehicles and pedestrians showing motion through layered depth, neon signs and billboards with delicate punched details, elevated trains weaving between buildings, a river flowing through the center with reflective paper layers, dramatic sunset sky with gradient paper clouds, rooftop gardens and bridges connecting structures, subtle paper textures and shadows adding three-dimensional realism, eye-catching urban energy captured in elegant layered paper art, harmonious composition with precise craftsmanship." \
  "Grok Fast" "Vibrant Cityscape at Dusk"

queue_job 18 \
  "Multi-layered 3D papercraft sculpture showcasing a vibrant underwater coral reef scene, delicate layered paper cuts forming colorful coral structures in pinks, oranges and purples with intricate branching patterns, schools of tropical fish swimming through with finely cut translucent fins, sea turtles and anemones in overlapping paper layers creating depth, shafts of sunlight piercing the water surface rendered in gradient paper, swaying seaweed forests in green tones, subtle bubbles and water currents suggested by paper folds, mysterious rock formations in the background, aesthetically pleasing oceanic wonder captured in tactile papercraft style with beautiful shadows and precise detailing." \
  "Grok Fast" "Enchanted Underwater Coral Reef"

queue_job 19 \
  "Highly detailed 3D papercraft sculpture of an enchanting autumn forest pathway, multi-layered paper trees with rich red, orange and golden foliage created through intricate cutouts, winding path covered in fallen leaves with textured paper layers, soft morning mist weaving between tree trunks formed by delicate silhouettes, small woodland creatures like deer and foxes peeking from behind layers, dappled sunlight filtering through canopy with warm paper shadows, mushrooms and ferns in foreground details, harmonious fall color palette, eye-catching depth and dimension achieved through masterful layered papercraft techniques, serene and magical atmosphere." \
  "Grok Fast" "Mystical Autumn Forest Pathway"

queue_job 20 \
  "Multi-layered 3D papercraft sculpture of a majestic desert oasis at twilight, towering sand dunes with smooth layered paper curves and wind-sculpted patterns, lush palm trees and vegetation surrounding a sparkling pool with reflective paper water effects, ancient stone ruins partially buried in sand with intricate architectural cut details, starry night sky transitioning from deep orange to indigo with delicate paper cloud formations, camels and nomadic figures in the distance, subtle paper textures and long dramatic shadows enhancing three-dimensional quality, breathtaking composition blending natural beauty and mystery in elegant papercraft artistry." \
  "Grok Fast" "Ancient Desert Oasis at Twilight"

# Copilot Smart
queue_job 21 \
  "A multi-layered 3D papercraft sculpture depicting a majestic mountain range rising above a tranquil valley, each layer cut with precision to reveal depth and perspective. The foreground features delicate paper trees with fine branches, while the midground shows rolling hills and winding rivers. The background layers rise into towering peaks capped with snow, their edges crisp and angular. Subtle shadows between layers enhance the illusion of depth, creating a mesmerizing landscape that feels alive. The composition balances light and dark tones, with intricate cutouts forming clouds drifting across the sky, resulting in an aesthetically pleasing, eye-catching paper-cut masterpiece." \
  "Copilot Smart" "Papercraft Mountain Vista"

queue_job 22 \
  "A 3D papercraft sculpture of a bustling city skyline, layered with intricate cutouts of skyscrapers, bridges, and streets. Each tier of paper adds dimension, with tall towers rising in the background and smaller buildings in the foreground. Windows and architectural details are carefully carved, while bridges and roads weave through the composition. The layering creates a sense of depth and perspective, with shadows enhancing the realism of the urban scene. The skyline glows with subtle highlights, suggesting evening light, and the overall design captures the vibrancy of city life in a visually stunning papercraft medium." \
  "Copilot Smart" "Papercraft City Skyline"

queue_job 23 \
  "A layered 3D papercraft sculpture portraying a serene forest path winding through dense trees. Each layer reveals new details: tall trunks with textured bark, leafy canopies, and delicate undergrowth. The path curves gently into the distance, inviting the viewer to step inside. Shadows between layers create a realistic sense of depth, while cutouts of birds and butterflies add life to the scene. The composition balances light filtering through the canopy with darker shaded areas, producing a tranquil, aesthetically pleasing atmosphere. The intricate craftsmanship transforms the forest into a captivating paper-cut artwork full of charm and detail." \
  "Copilot Smart" "Papercraft Forest Path"

queue_job 24 \
  "A multi-layered 3D papercraft sculpture capturing the dynamic motion of ocean waves crashing against rocky cliffs. Each layer is cut to form curling waves, foamy crests, and swirling currents, with darker tones in the depths and lighter highlights at the surface. The cliffs rise sharply in the background, their jagged edges contrasting with the fluid curves of the water. Shadows between layers enhance the sense of movement, while cutouts of seagulls and distant ships add narrative detail. The composition is both dramatic and harmonious, creating an eye-catching paper-cut scene that conveys the power and beauty of the sea." \
  "Copilot Smart" "Papercraft Ocean Waves"

queue_job 25 \
  "A 3D papercraft sculpture of a lush garden filled with flowers, vines, and ornamental arches. Each layer reveals new elements: roses and tulips in the foreground, winding paths and fountains in the midground, and tall hedges and trellises in the background. Intricate cutouts form petals, leaves, and decorative patterns, while shadows between layers add depth and realism. The composition is balanced with symmetry and flowing curves, creating a harmonious and aesthetically pleasing design. The garden feels alive with detail, transforming the papercraft medium into a captivating, eye-catching artwork that celebrates nature's beauty." \
  "Copilot Smart" "Papercraft Garden Scene"

# Mistral Think
queue_job 26 \
  "A hyper-detailed, multi-layered 3D papercraft sculpture of a mystical forest, with intricate paper-cut trees, mushrooms, and vines stacked in depth, casting soft shadows, vibrant autumn colors, warm golden light filtering through the layers, ultra-realistic paper texture, crisp edges, and a dreamy, ethereal atmosphere, cinematic composition, 8K resolution, hyper-detailed, photorealistic rendering." \
  "Mistral Thinking" "Forest Layers"

queue_job 27 \
  "A stunning 3D papercraft sculpture of a futuristic city skyline at dusk, with layered paper-cut skyscrapers, bridges, and neon signs, glowing windows, deep blues and purples in the sky, reflective glass-like paper surfaces, sharp geometric shapes, and a sense of depth and scale, ultra-detailed, cinematic lighting, 8K resolution." \
  "Mistral Thinking" "Urban Skyline"

queue_job 28 \
  "A breathtaking 3D papercraft sculpture of a snow-capped mountain range, with layered paper-cut peaks, pine forests, and a frozen lake, soft pastel colors, misty atmosphere, delicate paper textures, and a sense of tranquility, ultra-detailed, soft natural lighting, 8K resolution, hyper-realistic rendering." \
  "Mistral Thinking" "Mountain Serenity"

queue_job 29 \
  "A mesmerizing 3D papercraft sculpture of an underwater coral reef, with layered paper-cut coral, fish, and seaweed, vibrant turquoise and teal colors, bioluminescent glows, intricate paper textures, and a sense of movement, ultra-detailed, cinematic composition, 8K resolution, photorealistic rendering." \
  "Mistral Thinking" "Ocean Depths"

queue_job 30 \
  "A celestial 3D papercraft sculpture of a spiral galaxy, with layered paper-cut stars, planets, and nebulae, deep purples, blues, and pinks, glowing edges, intricate cosmic patterns, and a sense of vastness, ultra-detailed, ethereal lighting, 8K resolution, hyper-realistic rendering." \
  "Mistral Thinking" "Cosmic Galaxy"

# Qwen 3.7 Plus Thinking
queue_job 31 \
  "A multi-layered 3D papercraft sculpture of an enchanted forest landscape. Intricate paper-cut trees with vibrant green and autumn orange foliage, layered to create deep parallax depth. A winding river made of glossy blue paper flows through the center, reflecting soft studio lighting. Delicate paper mushrooms and tiny floral details add texture to the forest floor. The background features towering mountain silhouettes cut from textured kraft paper. Soft, diffused directional lighting casts realistic, crisp shadows between each paper layer, enhancing the three-dimensional effect. Macro photography style, shallow depth of field, highly detailed, aesthetically pleasing, vibrant colors, masterpiece craft art, beautiful composition, stunning visual." \
  "Qwen 3.7 Plus Thinking" "Enchanted Forest Papercraft Diorama"

queue_job 32 \
  "A stunning multi-layered 3D papercraft sculpture of a futuristic cyberpunk city. Towering skyscrapers made of folded and cut metallic paper, featuring glowing neon pink and cyan accents. Intricate paper-cut bridges and flying vehicles suspended between the buildings. Deep parallax layers create a massive sense of scale and depth. The background sky is a gradient of deep purple and midnight blue paper. Crisp, dramatic studio lighting casts sharp, realistic shadows across the textured paper surfaces, highlighting every geometric fold and cut. Macro photography, tilt-shift effect, highly detailed, vibrant aesthetic, eye-catching architectural diorama, masterpiece paper engineering, striking visual design, perfect lighting, amazing detail." \
  "Qwen 3.7 Plus Thinking" "Neon Metropolis Paper-Cut Cityscape"

queue_job 33 \
  "A breathtaking multi-layered 3D papercraft sculpture of a vibrant underwater coral reef. Intricately cut paper corals in bright magenta, coral, and teal tones, layered to create a stunning sense of oceanic depth. Delicate paper jellyfish and tropical fish float between the layers. The ocean floor features textured sand paper and swaying seaweed cutouts. Soft, caustic lighting effects mimic sunlight filtering through water, casting beautiful, rippling shadows across the layered paper surfaces. Macro photography, shallow depth of field, highly detailed, aesthetically pleasing, magical atmosphere, exquisite paper-cut craftsmanship, vivid colors, eye-catching marine diorama, beautiful composition, striking visual, amazing detail, perfect craft." \
  "Qwen 3.7 Plus Thinking" "Abyssal Coral Reef Paper Sculpture"

queue_job 34 \
  "A mesmerizing multi-layered 3D papercraft sculpture of a cosmic galaxy and nebula. Swirling clouds of stardust created from textured, torn paper edges in deep indigo, violet, and gold. Intricate paper-cut planets and crescent moons suspended on invisible threads between the layers. A central glowing sun made of layered yellow and orange paper radiates light. Dramatic, focused studio lighting casts deep, realistic shadows, emphasizing the vast three-dimensional depth of the space diorama. Macro photography, sharp focus on foreground layers, highly detailed, aesthetically pleasing, magical celestial landscape, exquisite paper engineering, vibrant and eye-catching, beautiful composition, striking visual, perfect craft, amazing detail." \
  "Qwen 3.7 Plus Thinking" "Celestial Cosmos Layered Paper Galaxy"

queue_job 35 \
  "A majestic multi-layered 3D papercraft sculpture of an alpine mountain valley at sunrise. Towering mountain peaks cut from textured grey and white paper, layered progressively to create immense depth. A serene lake in the foreground made of glossy, reflective blue paper. Tiny paper-cut pine trees dot the lower slopes. The sky features a beautiful gradient of warm sunrise paper colors, from soft peach to golden yellow. Bright, directional morning light casts long, crisp shadows across the intricate paper layers, highlighting the tactile texture of the craft. Macro photography, highly detailed, aesthetically pleasing, breathtaking landscape, beautiful composition, striking visual, perfect craft, amazing detail." \
  "Qwen 3.7 Plus Thinking" "Alpine Sunrise Mountain Valley Diorama"

# GLM 5.2 Turbo
queue_job 36 \
  "A breathtaking multi-layered 3D papercraft sculpture of an enchanted forest at twilight. The artwork features meticulously cut paper layers creating deep depth, from a dense, dark foreground of ferns and twisted roots to a softly glowing background of towering ancient trees. Delicate paper leaves in varying shades of emerald and sage green overlap perfectly. Tiny LED-like glowing fireflies are scattered through the midground. Soft, warm amber light filters from the very back layer, illuminating the intricate negative spaces. The sculpture has a magical, fairy-tale atmosphere with stunning shadows cast between the paper layers, highlighting the incredible texture and craftsmanship of the physical paper medium." \
  "GLM 5 Turbo" "Enchanted Twilight Forest Paper Diorama"

queue_job 37 \
  "An intricate multi-layered 3D papercraft sculpture depicting a futuristic cyberpunk cityscape. Countless meticulously cut paper layers build towering skyscrapers with complex geometric facades, stepping back to create immense urban depth. The color palette transitions from dark silhouettes in the foreground to vibrant neon pinks, electric blues, and glowing purples in the deep background. Tiny paper-cut windows and glowing holographic billboards pierce through the layers. Soft diffused lighting creates dramatic shadows between the architectural paper tiers, emphasizing the three-dimensional relief. The highly detailed paper edges and precise structural layers make this a visually striking, eye-catching masterpiece of miniature paper engineering and modern urban design." \
  "GLM 5 Turbo" "Neon Cyberpunk Megacity Paper Architecture"

queue_job 38 \
  "A stunning multi-layered 3D papercraft sculpture of a majestic mountain landscape at sunset. The composition features deeply layered paper silhouettes creating a vast sense of depth. The foreground showcases delicate, intricate paper wildflowers and tall grasses. The midground holds a perfectly still, reflective lake made of smooth, glossy blue cardstock. The background rises into sharp, snow-capped mountain peaks cut with geometric precision. The sky layer transitions from warm peach and golden yellow to deep twilight purple. Backlighting highlights the crisp, laser-cut edges of each paper tier, casting gentle gradient shadows that enhance the breathtaking three-dimensional topography of this serene nature scene." \
  "GLM 5 Turbo" "Golden Sunset Mountain Lake Paper Relief"

queue_job 39 \
  "A highly detailed multi-layered 3D papercraft sculpture of a traditional Japanese temple surrounded by blooming cherry blossoms. The artwork uses exquisite paper cutting to build a serene, layered scene. The foreground features intricate, delicate pink cherry blossom branches with tiny paper petals. Behind them, a beautifully detailed red and dark wooden pagoda sits centrally, its curved roofs and pillars rendered in precise architectural relief. Deeper layers reveal more fading temple structures blending into a misty, pale lavender background. Gentle, diffused front lighting enhances the crisp folds and textures of the craft paper, creating a tranquil, eye-catching three-dimensional diorama with incredible depth." \
  "GLM 5 Turbo" "Japanese Temple Cherry Blossom Paper Art"

queue_job 40 \
  "A mesmerizing multi-layered 3D papercraft sculpture illustrating a vibrant underwater coral reef. The piece utilizes up to twenty layers of intricately sliced paper to simulate the deep ocean. The foreground bursts with textured, brightly colored paper corals in neon orange, hot pink, and bright yellow. Midground layers feature delicate, flowing paper seaweeds and tiny, precisely cut tropical fish swimming between the tiers. The background fades into deep, translucent cerulean and navy blue paper layers, mimicking the filtering of ocean light. Strategic illumination from behind casts glowing aquatic shadows through the negative spaces, making the paper medium look magically fluid and lifelike." \
  "GLM 5 Turbo" "Vibrant Underwater Coral Reef Paper Sculpture"

# Kimi K2.6 Thinking
queue_job 41 \
  "A breathtaking multi-layered 3D papercraft sculpture of a serene mountain lake at dawn, meticulously crafted from textured watercolor paper in gradients of deep indigo, soft lavender, warm coral, and golden amber. Multiple depth planes reveal misty pine forests, snow-capped peaks with delicate paper snow texture, and a mirror-still lake reflecting the layered sky. Intricate die-cut details show tiny paper birds in flight, while rolled paper techniques create dimensional wildflowers along the shoreline. Soft directional lighting casts gentle paper shadows between each sculpted layer, emphasizing the handcrafted relief quality and tactile paper grain throughout the composition." \
  "Kimi K2.6 Thinking" "Mountain Lake at Dawn"

queue_job 42 \
  "A stunning multi-layered 3D papercraft sculpture of a futuristic Tokyo cityscape at twilight, constructed from precision-cut metallic and matte papers in electric cyan, magenta, warm white, and deep charcoal. Architectural layers recede into depth showing paper skyscrapers with intricate window cutouts, glowing neon signage rendered in translucent vellum overlays, and a bustling paper street level with tiny dimensional vehicles. Cherry blossom trees frame the scene with curled pink paper petals. Dramatic side-lighting creates sharp paper shadows and highlights the embossed texture of corrugated paper rooftops, wire-bridge details, and the handcrafted dimensional quality of this intricate urban paper diorama." \
  "Kimi K2.6 Thinking" "Tokyo Nightscape"

queue_job 43 \
  "A mesmerizing multi-layered 3D papercraft sculpture of a winding forest path in peak autumn, sculpted from richly textured handmade papers in burnt sienna, crimson, ochre, rust, and deep forest green. Progressive depth layers reveal paper trees with individually cut leaves creating a canopy tunnel, a meandering stream with layered blue vellum water effects, and distant rolling hills fading to atmospheric paper haze. Delicate quilling techniques form ferns and mushrooms along the path edges. Warm golden-hour lighting filters through the paper foliage, casting intricate lace-like shadows across the dimensional terrain and emphasizing the tactile relief of crimped paper bark and folded leaf textures throughout the handcrafted scene." \
  "Kimi K2.6 Thinking" "Autumn Forest Path"

queue_job 44 \
  "A vibrant multi-layered 3D papercraft sculpture of a thriving coral reef ecosystem, masterfully constructed from textured papers in tropical teal, coral pink, sunshine yellow, deep purple, and pearlescent white. Multiple sculpted planes show layered paper coral formations with fringed edges and bubble-like quilled textures, schools of tiny cut-paper fish swimming between dimensional sea anemones, and a sea turtle with tessellated shell patterns in the mid-ground. Translucent vellum layers suggest shimmering water and light rays penetrating from above. Careful backlighting creates a stained-glass effect through the paper layers while casting soft shadows that enhance the underwater depth and handcrafted tactile quality of this intricate marine paper diorama." \
  "Kimi K2.6 Thinking" "Underwater Coral Reef"

queue_job 45 \
  "A charming multi-layered 3D papercraft sculpture of a sun-drenched Mediterranean village cascading down a hillside, crafted from warm textured papers in terracotta, cream, sage green, azure blue, and golden yellow. Architectural depth layers feature paper houses with individually cut shutter windows, terracotta roofs with crimped paper tile texture, and winding stone staircases connecting the levels. Paper cypress trees and olive groves populate the landscape with curled and folded foliage techniques. A distant paper sea shimmers in layered blue gradients. Soft afternoon lighting creates warm paper shadows between the stacked village layers, highlighting the embossed stone wall textures, delicate balcony railings, and the overall handcrafted dimensional relief of this picturesque paper scene." \
  "Kimi K2.6 Thinking" "European Village Hillside"

# Deepseek Instant
queue_job 46 \
  "A multi-layered 3D papercraft sculpture depicting a serene mountain landscape at sunset. Deep indigo and violet silhouettes of pine forests form the foreground, intricately cut with tiny needle-like trees. Midground reveals sweeping valleys and rolling hills in warm amber, burnt orange, and soft pink hues, each layer casting delicate drop shadows that enhance depth. The background features majestic snow-capped peaks in pale lavender and cream, with a glowing paper sun peeking through. Crisp white highlights and subtle texture of handmade paper grain add realism. Soft diffused backlighting creates a magical, ethereal atmosphere, emphasizing the intricate layered cutouts." \
  "Deepseek Instant" "Enchanted Mountain Sunset"

queue_job 47 \
  "A stunning 3D papercut diorama of a futuristic cyberpunk city at night. Layered skyscrapers and flying vehicles are meticulously crafted from glossy and matte paper, featuring sharp geometric angles. Neon cyan, magenta, and electric yellow illuminate the edges of each cutout, while deep charcoal and navy shadows create dramatic contrast. Overlapping bridges and elevated highways connect towering structures, with tiny illuminated windows suggesting life. Reflective metallic paper accents catch the light, while soft ambient glow from below mimics streetlights. The composition offers immense depth through staggered layers, each precisely spaced, creating a visually captivating, dynamic urban sci-fi masterpiece." \
  "Deepseek Instant" "Futuristic Neon Metropolis"

queue_job 48 \
  "An immersive 3D paper sculpture of a vibrant underwater coral reef. Intricate layers of coral formations in coral pink, teal, and golden yellow fan outwards, with delicate perforated details mimicking polyp textures. Schools of tiny paper fish, cut with fin-like precision, swim between layered seaweed and anemone fronds. The background transitions from pale aqua to deep ocean blue, with wavy light beams suggesting sunlight filtering through water. Pearlescent and translucent paper adds a shimmering, aquatic feel. Each element is subtly raised, casting soft shadows that enhance the three-dimensional effect, creating a tranquil, eye-catching oceanic paradise full of organic movement." \
  "Deepseek Instant" "Coral Reef Underwater Oasis"

queue_job 49 \
  "A serene 3D papercut scene of a traditional Japanese garden in spring. Foreground features a curved wooden bridge made of brown kraft paper, with intricate railings, over a pond of layered translucent blue paper. Midground showcases blooming cherry blossom trees with thousands of tiny pink and white petal cutouts, their branches overlapping gracefully. Background includes a wooden pagoda and distant misty mountains in soft sage and gray. Delicate gold foil accents highlight architectural details. Soft, warm sunlight casts gentle shadows across each layer, emphasizing the handcrafted texture. The composition balances symmetry and natural asymmetry, evoking peace and aesthetic perfection." \
  "Deepseek Instant" "Japanese Cherry Blossom Garden"

queue_job 50 \
  "A breathtaking 3D paper sculpture of a mountaintop observatory gazing into a spiral galaxy. The foreground features rugged rocky peaks in textured gray and slate paper, with sharp, jagged cutouts. Midground presents the observatory dome with metallic silver paper and intricate latticework, a warm yellow glow emanating from its slit. The background unveils a magnificent swirling galaxy made of layered translucent vellum in deep purple, cosmic blue, and shimmering gold, dotted with tiny star punch-holes. Soft rim lighting highlights the dome's curvature and mountain edges. The layered depth creates a vast, awe-inspiring cosmic narrative, blending science and artistry perfectly." \
  "Deepseek Instant" "Observatory Under Starry Galaxy"

# ERNIE 5.1 Thinking
queue_job 51 \
  "A multi-layered 3D papercraft sculpture of an enchanted forest scene, cascading depth with overlapping paper cutouts forming towering trees, glowing mushrooms, and a winding river. Rich emerald greens, deep moss tones, golden amber accents, and soft lavender twilight hues. Delicate paper textures with visible layered edges, intricate leaf patterns and fern fronds cut from textured cardstock. Soft directional lighting casting gentle shadows between layers creating dramatic depth. Tiny paper birds perched on branches, a distant paper waterfall, foreground wildflowers in pastel tones. Whimsical, handcrafted aesthetic with tactile dimensional quality." \
  "ERNIE 5.1 Thinking" "Enchanted Forest Layers"

queue_job 52 \
  "A stunning multi-layered 3D papercraft sculpture depicting a quaint mountain village at sunrise, layered paper cutouts forming snow-capped peaks, terracotta-roofed cottages, winding cobblestone paths, and blooming cherry blossom trees. Warm peach and coral dawn sky transitioning to soft pink and pale blue. Visible paper grain textures with precise cut edges, each layer adding parallax depth. Small paper church steeple, hanging lanterns, and a wooden bridge over a paper stream. Shadows between layers create volumetric dimension. Delicate craftsmanship, cozy pastoral atmosphere, artisanal handmade quality throughout the composition." \
  "ERNIE 5.1 Thinking" "Mountain Village at Dawn"

queue_job 53 \
  "A breathtaking multi-layered 3D papercraft sculpture of an underwater coral reef scene, layered paper cutouts forming vibrant coral formations, swaying sea kelp, tropical fish, sea turtles, and a gentle sandy ocean floor. Vivid turquoise, deep sapphire blue, coral pink, and bright orange paper tones with translucent layered effects simulating light filtering through water. Detailed paper texture with intricate coral branch patterns and scale-like fish bodies. A paper lighthouse visible in the distant background layer. Soft diffused lighting creating ethereal underwater glow, tactile dimensional depth, mesmerizing handcrafted marine world." \
  "ERNIE 5.1 Thinking" "Ocean Coral Reef Depths"

queue_job 54 \
  "A striking multi-layered 3D papercraft sculpture of a futuristic cyberpunk cityscape at night, overlapping paper cutouts forming towering skyscrapers with neon signage, flying vehicles, rain-slicked streets, and holographic billboards. Electric cyan, hot magenta, deep violet, and warm amber glow tones against dark navy paper backgrounds. Precise geometric paper architecture with visible layered edges creating impressive parallax depth. Paper rain droplets, steam rising from vents, tiny paper figures on walkways. Dramatic rim lighting between layers, intricate circuit-pattern details, moody atmospheric fog effects, stunning handcrafted urban dystopia with vibrant energy." \
  "ERNIE 5.1 Thinking" "Cyberpunk Neon Cityscape"

queue_job 55 \
  "A charming multi-layered 3D papercraft sculpture of an autumn countryside harvest scene, cascading paper layers forming rolling hills, a rustic red barn, golden wheat fields, pumpkin patches, and scattered maple trees in fiery fall colors. Warm burnt orange, rich crimson, golden yellow, and deep brown earth tones with cream and tan paper accents. Detailed paper textures showing wood grain on the barn and individual leaf cutouts. A paper windmill, wooden fence, hay bales, and a distant church spire. Soft warm sunlight casting long shadows between layers, cozy nostalgic atmosphere, masterful handcrafted pastoral beauty with tactile dimensionality." \
  "ERNIE 5.1 Thinking" "Autumn Harvest Countryside"

# LongCat Deep Search
queue_job 56 \
  "A multi-layered 3D papercraft sculpture depicting an alpine landscape at dawn. Die-cut paper layers form snow-capped peaks rising behind pine forests, with birds and hot air balloons suspended above. Warm gold and soft pink light filters through intricate paper slats, casting sharp shadows across the corrugated foreground meadow. Each layer of trees and ridgelines creates genuine depth and parallax when viewed from an angle. The paper texture shows fiber grain, edges slightly curled by hand, with subtle embossing on snow surfaces. Soft volumetric lighting illuminates the paper fibers, giving everything a warm, tangible quality. The composition leads the eye from the detailed foreground flowers through the layered forest toward the luminous horizon, creating a captivating miniature world in warm, inviting tones." \
  "LongCat Deep Search" "Alpine Dawn"

queue_job 57 \
  "A multi-layered 3D papercraft sculpture capturing a cyberpunk Tokyo street at night. Layered paper cutouts form towering skyscrapers with glowing windows, elevated trains, and holographic advertisements, all built from hand-cut matte and metallic paper. Tiny paper figures walk beneath lit paper umbrellas while neon signs in pink and cyan cast colored shadows across the layered paper facades. The diorama features dramatic depth with foreground details of vending machines and paper food stalls, mid-ground crowds, and towering background buildings. Fiber optics twinkle through small paper openings, simulating city lights. The rough paper edges catch ambient light, giving the scene a beautifully crafted, hand-made quality that contrasts with the high-tech setting. The layered construction creates genuine shadows and a tangible sense of depth." \
  "LongCat Deep Search" "Neon Tokyo Night"

queue_job 58 \
  "A multi-layered 3D papercraft sculpture depicting a vibrant coral reef ecosystem. Dozens of hand-cut paper layers form intricate coral structures, sea fans, and anemones in neon oranges, pinks, and purples, each layer progressively smaller to create genuine depth. Curious paper fish, turtles, and jellyfish float between the layers, suspended at varying depths. Sunlight filters through the top layers, creating caustic light patterns on the sandy paper floor. The paper textures range from smooth waxy on fish scales to rough fabric-like on coral, with translucent paper used for fins and seaweed. Tiny bubbles rise through the layers. The entire composition glows with bioluminescent accents, creating an enchanting underwater tableau that highlights the precision of the paper cutting and the beauty of layered depth." \
  "LongCat Deep Search" "Coral Reef Dreamscape"

queue_job 59 \
  "A multi-layered 3D papercraft sculpture of a winding forest path in peak autumn. Hand-cut paper layers form trees ablaze in red, orange, and gold, with fallen leaves carpeting the corrugated paper ground. A rustic wooden bridge arches over a babbling paper stream, with tiny paper deer drinking at the water's edge. The diorama features dramatic depth, from the blurred, out-of-focus paper foliage in the foreground to the sharp, detailed trees at the path's bend. Subtle embossing gives texture to tree bark and rocks. Warm, directional lighting creates long, dramatic shadows across the scene, illuminating the paper fibers and giving every leaf a luminous quality. The composition leads the eye along the path into the mysterious, golden forest interior." \
  "LongCat Deep Search" "Autumn Forest Path"

queue_job 60 \
  "A multi-layered 3D papercraft sculpture depicting fantastical floating islands in the sky. Giant paper platforms drift among clouds, each topped with miniature forests, waterfalls that cascade into the void, and tiny paper houses hanging from the undersides. Paper birds and hot air balloons weave between the layers, suspended at various heights. The construction emphasizes dramatic vertical depth, with some islands in sharp detail and others faded into the misty background. Soft, ethereal lighting filters through the paper clouds, creating a dreamlike atmosphere. The rough paper edges and visible fiber textures give everything a handcrafted, storybook quality. Waterfalls are depicted with layered translucent paper that catches the light, creating a sense of motion in this serene, gravity-defying world." \
  "LongCat Deep Search" "Floating Islands"

echo "✅ All 60 jobs queued in scheduler"

