#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Collage art — cut/torn paper, ephemera, fabric, mixed-media pasted
#        compositions
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+36+-+collage+art
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A vibrant mixed-media collage art composition celebrating botanical abundance, built from torn magazine pages, pressed leaf textures, and yellowed vintage book paper layered into an exploding floral bouquet. Cut petals of glossy printed paper overlap hand-torn newsprint stems, edges deliberately rough and uneven, visible paper grain and slight paste wrinkles catching soft studio light. Fragments of botanical illustration plates peek between color blocks of aged ephemera, ticket stubs, and faded floral wallpaper scraps. The background is a warm cream cardstock textured with subtle fingerprints of glue residue. Analog scrapbook aesthetic, tactile paper depth, layered shadows between elements, asymmetrical balanced composition, richly saturated yet paper-toned palette, fine art collage photographed under natural window light." \
  "Claude Sonnet 5 medium" "Collage Bloom Botanica"

queue_job  2 \
  "A striking collage art portrait of a human face reconstructed entirely from torn city map fragments, newspaper columns, and cut photographs of urban windows and brick textures. Eyes are formed from clock-face cutouts, the jaw built with strips of subway ticket paper, hair rendered as layered strands of torn magazine typography in muted grays and ochre. Each fragment retains authentic paper texture, deckled edges, faint ink bleed, and subtle drop shadows suggesting handmade physical assembly rather than digital collage. Background remains a raw kraft paper sheet with visible fibers. Vintage sepia and cool blue tones dominate, evoking analog scrapbook craftsmanship, tactile depth, layered paper strata, fine art mixed-media portrait photographed in soft diffused daylight." \
  "Claude Sonnet 5 medium" "Fractured City Portrait"

queue_job  3 \
  "A dreamlike collage art seascape assembled from torn blue tissue paper, cut fragments of old nautical charts, vintage postage stamps, and sepia photographs of ships and lighthouses. Waves are built from overlapping strips of marbled paper and faded sheet music, their torn edges catching subtle shadow to imply real physical layering. A small paper boat cutout sails across a horizon made of yellowed newspaper clippings and pressed seaweed textures. Corners feature aged ephemera like ticket stubs and handwritten letter fragments, edges curling slightly as if aged by salt air. Muted teal, cream, and rust tones dominate, tactile handmade scrapbook aesthetic, richly layered paper depth, fine art collage photographed under warm natural light." \
  "Claude Sonnet 5 medium" "Ocean of Ephemera"

queue_job  4 \
  "An imaginative collage art composition fusing torn botanical illustration plates with cut fragments of vintage mechanical engravings, gears, and blueprint paper to form a surreal flower-machine hybrid. Petals are constructed from aged sepia gear diagrams, stems built with strips of graph paper and old ledger pages, roots dissolving into torn brass-toned engraving scraps. Every piece shows authentic paper texture, visible tears, faint foxing stains, and layered paste shadows suggesting handcrafted assembly. The background is warm ivory cardstock with subtle glue wrinkles. Palette blends sepia, brass, and muted sage green, evoking steampunk scrapbook artistry, tactile layered depth, asymmetrical composition, fine art mixed-media piece photographed in soft studio light." \
  "Claude Sonnet 5 medium" "Botanical Machine Dreams"

queue_job  5 \
  "A whimsical collage art night sky composition built from torn indigo tissue paper, cut fragments of old star charts, vintage postage stamps, and sepia astronomy diagrams. Stars are formed from small circular paper punches and gold foil scraps, constellations connected with delicate hand-cut paper threads. A crescent moon cutout, layered from cream cardstock and faded sheet music, glows softly against the deep paper sky. Torn newspaper clippings with astronomical text drift along the lower edge, their rough deckled borders casting subtle shadows suggesting real physical layering. Palette blends deep indigo, gold, and cream tones, tactile handmade scrapbook aesthetic, richly textured paper depth, fine art collage photographed under warm gallery lighting." \
  "Claude Sonnet 5 medium" "Paper Constellation"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A rich mixed-media collage art composition filling a square canvas. Features a central black-and-white vintage photograph of a bustling 1950s city street corner, partially overlaid with torn pieces of aged, yellowed newspaper clippings and distressed transit tickets. Textured layers include fragments of a colorful retro map showing winding streets, juxtaposed with delicate, pressed botanical illustrations of dried wildflowers. Textural depth is enhanced with rough, frayed edges of denim fabric, weathered postmarks, and spilled sepia ink splatters. The composition balances nostalgic urban elements and natural textures, creating a cohesive, layered visual narrative with high contrast and distinct tactile surfaces of pasted ephemera." \
  "Gemini 3.5 Flash" "Echoes of the Asphalt"

queue_job  7 \
  "A surrealist mixed-media collage art piece showcasing a dreamlike cosmological theme. The central figure is a sharp cutout of a mid-century astronaut, constructed from grainy magazine paper, floating among layers of antique astronomical sky charts and weathered star maps. Surrounding elements consist of torn pieces of shimmering gold leaf foil, textured handmade paper, and vibrant retro advertisements of abstract geometric shapes. Cutout imagery of human eyes and vintage mechanical gears are meticulously pasted alongside delicate threads of blue yarn and faded hand-written letters. The entire square composition has a distinct hand-crafted, tactile feel with visible paper edges, drop shadows, and a rich, layered, artistic depth." \
  "Gemini 3.5 Flash" "Celestial Whispers"

queue_job  8 \
  "An avant-garde mixed-media collage art composition capturing the essence of high fashion. The main subject is a striking female silhouette constructed from high-contrast black-and-white magazine cutouts and torn sheets of bold typography newsprint. Vibrant, irregular pieces of crimson silk fabric, textured emerald velvet ribbons, and metallic copper foil are pasted haphazardly around the figure. Accents of hand-torn kraft paper, abstract brush strokes of thick black acrylic paint, and vintage fashion sketches are layered together to create deep texture. Every element features visible, rough edges and subtle drop shadows, emphasizing the physical, hand-pasted nature of the artwork, resulting in a dynamic and stylish editorial aesthetic." \
  "Gemini 3.5 Flash" "Velvet and Newsprint"

queue_job  9 \
  "A whimsical botanical collage art composition filled with organic textures. The artwork features torn fragments of antique classical music sheets intertwined with detailed illustrations of butterflies cut from vintage nature guides. Layers of real-looking pressed ferns, dried lavender stems, and colorful floral cutouts of watercolor roses are pasted onto a background of rough, handmade mulberry paper with visible plant fibers. Scrap pieces of pastel linen fabric, faded handwritten ledger pages, and delicate lace trim add layers of vintage charm. The entire composition has a beautifully aged, rustic feel, highlighted by subtle shadows beneath the layered paper pieces, creating a rich three-dimensional tactile quality." \
  "Gemini 3.5 Flash" "Greenhouse Symphony"

queue_job 10 \
  "An abstract retro-futurist collage art composition combining diverse materials. The background features a rough, textured piece of gray cardboard with torn, corrugated edges showing through. Overlaid are sharp geometric shapes cut from vibrant 1980s neon-colored posters, side-by-side with weathered cutouts of vintage mechanical clock gears and scientific diagrams. Strips of textured black duct tape, glossy magazine snippets of modern architecture, and metallic silver foil accents are layered dynamically across the scene. Faint splatters of white paint and hand-drawn ink lines connect the disparate elements. The physical layout utilizes distinct overlapping layers and realistic drop shadows, giving the collage a high-fidelity, handcrafted tactile appearance." \
  "Gemini 3.5 Flash" "Chronos Distortion"

# --- ChatGPT ---
queue_job 11 \
  "A richly layered collage artwork assembled from hand-cut botanical illustrations, pressed flower silhouettes, vintage seed packets, faded handwritten journal pages, fragments of antique maps, recycled kraft paper, delicate lace fabric, watercolor paper scraps, translucent vellum, postage stamps, and subtle gold foil accents. Torn edges overlap organically to create depth while soft green, ochre, cream, dusty blue, and muted terracotta tones form a harmonious natural palette. Tiny ink sketches of birds, butterflies, and leaves are scattered throughout, blending seamlessly with realistic paper textures and visible adhesive imperfections. Warm diffused lighting, intricate handcrafted details, elegant composition, tactile mixed-media aesthetic, contemporary gallery-quality collage art celebrating nature, memory, craftsmanship, and quiet beauty." \
  "ChatGPT" "Botanical Memory Mosaic"

queue_job 12 \
  "An energetic contemporary collage composition portraying a vibrant modern city using torn magazine pages, colorful advertising fragments, newspaper headlines, subway tickets, architectural blueprints, corrugated cardboard, metallic foil paper, transparent acetate, textured fabric swatches, and bold geometric paper cutouts. Layered skyscrapers emerge from overlapping materials with visible cut edges, creating dynamic depth and movement. Bright cyan, crimson, yellow, charcoal, and white contrast with neutral recycled papers, while abstract traffic patterns and handwritten notes weave through the composition. Realistic paper fibers, subtle wrinkles, tape marks, and shadows emphasize handcrafted authenticity. Sophisticated mixed-media collage art balancing urban chaos, design precision, creative experimentation, and contemporary visual storytelling." \
  "ChatGPT" "City Rhythm Paper Symphony"

queue_job 13 \
  "A poetic collage artwork inspired by the sea, carefully assembled from vintage nautical charts, weathered book pages, blue handmade paper, translucent tissue paper, fragments of old postcards, linen fabric, seashell illustrations, botanical prints, faded photographs, and delicate white thread stitched across layered surfaces. Torn paper waves flow naturally through the composition while paper-cut fish, seabirds, coral, and sailing boats drift between textured layers. A calming palette of turquoise, deep navy, ivory, sandy beige, and seafoam green creates peaceful harmony. Visible paper textures, overlapping shadows, soft watercolor stains, subtle ink splashes, and authentic handcrafted details produce an elegant mixed-media collage with timeless coastal atmosphere and artistic sophistication." \
  "ChatGPT" "Ocean Dreams Collage"

queue_job 14 \
  "An imaginative collage artwork depicting an astronomical journey using antique star charts, celestial engravings, astronomy textbook pages, metallic paper circles, black handmade paper, holographic foil fragments, translucent vellum, constellation diagrams, postage stamps, handwritten scientific notes, and textured watercolor paper. Planets, moons, comets, and galaxies are built from layered cut paper with carefully torn edges and dimensional overlapping elements. Deep indigo, violet, silver, gold, black, and soft ivory dominate the refined color palette. Fine paper fibers, glue textures, folded corners, realistic shadows, and subtle embossed details reinforce the handcrafted appearance. Elegant mixed-media collage blending scientific curiosity, vintage exploration, dreamlike imagination, and contemporary artistic craftsmanship." \
  "ChatGPT" "Cosmic Paper Expedition"

queue_job 15 \
  "A striking artistic portrait created entirely as an elaborate collage from fashion magazine clippings, antique book illustrations, handwritten letters, colorful painted paper, patterned textiles, sheet music, vintage photographs, newspaper fragments, decorative washi tape, and textured recycled paper. Facial features emerge through carefully layered cut shapes while flowers, birds, geometric forms, and abstract symbols radiate around the figure, merging realism with surreal creativity. Rich jewel tones combine with soft neutrals, warm sepia, and elegant gold highlights. Visible torn edges, paper grain, overlapping textures, subtle adhesive marks, and handcrafted imperfections enhance authenticity. Sophisticated mixed-media collage art expressing identity, imagination, emotion, memory, and contemporary visual storytelling." \
  "ChatGPT" "Portrait of Imagination"

# --- Grok fast ---
queue_job 16 \
  "A vibrant mixed-media collage depicting a bustling futuristic city at dusk, composed of torn magazine clippings of skyscrapers, overlapping vintage newspaper headlines about technology and travel, cut-out photographs of crowded streets and neon signs, layered with fragments of old maps, fabric swatches in metallic textures, and postage stamps. Torn paper edges, visible glue marks, and textured brushstrokes create depth. Chaotic yet harmonious composition with overlapping translucent layers, handwritten notes, and ephemera like ticket stubs. Warm color palette blending deep blues, electric pinks, and golds. Highly detailed collage art style with physical imperfections and artistic imperfections." \
  "Grok fast" "Urban Dreams Collage"

queue_job 17 \
  "Surreal forest collage scene built from torn botanical illustrations, cut photographs of ancient trees and wildlife, layered fabric leaves in varied greens, pressed flower petals, and newspaper clippings of fairy tales. Overlapping elements include vintage map fragments showing winding paths, handwritten poetry snippets, and old book pages. Soft diffused lighting, visible paper textures, glue drips, and ragged torn borders. Dreamlike atmosphere with floating elements and depth through multiple transparent layers. Earthy tones mixed with ethereal pastels. Intricate mixed media collage with natural ephemera and artistic wear." \
  "Grok fast" "Whimsical Forest Reverie"

queue_job 18 \
  "Intimate portrait of a mysterious woman in collage form, face assembled from torn vintage photographs, magazine fashion cutouts, and fabric lace fragments. Background layered with old letters, faded postcards, sheet music snippets, and newspaper obituary clippings. Overlapping eyes from different eras, lips from glossy ads, hair from textured papers. Visible seams, yellowed tape effects, and ink smudges. Emotional and evocative mood with sepia, soft pinks, and deep burgundies. Masterful paper collage technique emphasizing memory and time through layered ephemera and deliberate imperfections." \
  "Grok fast" "Nostalgic Portrait Mosaic"

queue_job 19 \
  "Dynamic abstract collage explosion of geometric shapes and organic forms, created from torn colored construction paper, printed circuit board diagrams, fabric swatches, paint swipes, and magazine geometric patterns. Interwoven with metallic foil scraps, string fragments, and handwritten mathematical equations. Bold overlapping layers with contrasting textures, torn edges, and visible adhesive marks. Vibrant color explosion of reds, yellows, blues, and blacks creating visual rhythm. Modern mixed-media collage art full of energy, depth, and tactile quality." \
  "Grok fast" "Abstract Harmony Explosion"

queue_job 20 \
  "Dreamy oceanic collage landscape featuring cut-out photographs of crashing waves, torn nautical maps, vintage postcards of beaches, and fabric seaweed elements. Layered with seashell prints, old fishing net fragments, newspaper maritime stories, and handwritten journal entries. Overlapping translucent blue papers, visible water stains, and ragged paper borders. Depth through multiple glued layers showing time-worn textures. Serene yet mysterious mood with deep aquas, teals, sandy beiges, and white foam accents. Evocative mixed media collage celebrating sea memories and ephemera." \
  "Grok fast" "Oceanic Memory Layers"

# --- Copilot Smart ---
queue_job 21 \
  "A vibrant collage blending torn magazine clippings, faded photographs, and fragments of newspaper headlines layered over textured fabric swatches. The composition evokes nostalgia, with overlapping cityscapes, handwritten notes, and vintage ticket stubs arranged in chaotic harmony. Colors range from muted sepia tones to bold splashes of red and blue, creating contrast between past and present. The collage feels tactile, with jagged edges and uneven layers, as if assembled by hand on a studio table. Shadows and highlights emphasize depth, making the flat materials appear dimensional, while the overall mood suggests memory fragments stitched together into a living artwork." \
  "Copilot Smart" "Collage of Urban Memories"

queue_job 22 \
  "A delicate collage composed of torn botanical illustrations, pressed leaves, and fragments of watercolor paper layered with fabric textures. The arrangement features overlapping greens, earthy browns, and soft pastel hues, forming a dreamlike forest scene. Small cutouts of birds and butterflies from old magazines flutter across the composition, while handwritten notes and faded ink sketches peek through the layers. The collage combines organic shapes with geometric fragments, creating tension between natural flow and structured design. The tactile quality of paper edges and fabric fibers adds depth, while the overall mood conveys serenity and the quiet whispers of nature." \
  "Copilot Smart" "Collage of Nature's Whispers"

queue_job 23 \
  "A striking collage built from torn portraits, magazine cutouts of eyes and mouths, and fragments of handwritten letters layered with textured fabrics. The composition emphasizes human emotion, with overlapping facial features forming surreal expressions. Bold splashes of color—reds, yellows, and blues—contrast with monochrome newspaper fragments, creating tension between chaos and clarity. The collage feels raw and expressive, with jagged edges and overlapping layers suggesting vulnerability and complexity. Shadows and highlights enhance dimensionality, making the flat materials appear sculptural. The overall mood conveys the fragmented yet powerful nature of human identity and emotional expression." \
  "Copilot Smart" "Collage of Human Expression"

queue_job 24 \
  "A whimsical collage combining torn maps, vintage postcards, and fragments of travel brochures layered with fabric textures. The composition features overlapping landmarks, handwritten notes, and faded stamps, evoking the spirit of adventure. Colors range from muted earth tones to vibrant splashes of turquoise and orange, symbolizing distant seas and sunsets. Cutouts of airplanes, trains, and ships from magazines weave through the layers, while fragments of tickets and receipts add authenticity. The tactile quality of torn edges and layered paper creates depth, while the overall mood conveys wanderlust and the dreamlike quality of journeys imagined and remembered." \
  "Copilot Smart" "Collage of Travel Dreams"

queue_job 25 \
  "An energetic collage composed of torn geometric shapes, bold magazine typography, and fragments of painted paper layered with fabric swatches. The arrangement emphasizes abstraction, with overlapping circles, triangles, and jagged forms creating dynamic movement. Colors are vivid—reds, blacks, yellows, and metallic silvers—contrasting sharply against muted newspaper fragments. The collage feels chaotic yet intentional, with uneven edges and layered textures suggesting spontaneity. Shadows and highlights enhance dimensionality, making the flat materials appear sculptural. The overall mood conveys energy, disruption, and the beauty of chaos transformed into a striking visual composition." \
  "Copilot Smart" "Collage of Abstract Chaos"

# --- Mistral Think ---
queue_job 26 \
  "A dreamlike collage blending torn magazine pages of lush forests, vintage postcards of city skylines, and handwritten poetry fragments, all layered with translucent vellum and textured watercolor paper. The composition features a central tree with roots morphing into urban streets, surrounded by overlapping textures of aged parchment, metallic foil accents, and delicate pressed flowers. Soft pastel and earthy tones dominate, with subtle gold leaf highlights, ink splatters, and faint tea stains adding depth and history. The arrangement feels organic yet deliberate, with edges intentionally frayed, curled, or torn for a tactile, multidimensional effect." \
  "Mistral Think" "Surreal Nature-Urban Fusion Collage"

queue_job 27 \
  "A nostalgic collage composed of yellowed book pages, antique sheet music, and sepia-toned photographs, meticulously arranged to form the silhouette of a reading woman. The background is a patchwork of old newspaper clippings, handwritten letters in cursive, and faded botanical illustrations, with some elements slightly overlapping or peeling. Subtle tea stains, ink smudges, wax seal imprints, and faint watermarks add authenticity, while pops of burgundy, gold, and deep green from vintage postage stamps and decorative borders enrich the warm, muted palette." \
  "Mistral Think" "Vintage Literary Collage"

queue_job 28 \
  "A dynamic abstract collage featuring bold, overlapping geometric shapes cut from glossy magazine ads, colored paper, metallic foils, and patterned scrapbook paper. Sharp triangles, circles, and hexagons in vibrant primary colors contrast with black-and-white typography fragments. Some shapes are tilted, layered, or offset, creating depth and movement. The background incorporates grid paper, carbon copy patterns, faint pencil sketches, and watercolor washes, resulting in a modern, graphic effect with clean lines and balanced positive-negative space." \
  "Mistral Think" "Abstract Geometric Collage"

queue_job 29 \
  "A vibrant pop art collage bursting with torn comic book panels, retro advertisement cutouts, and bold 1960s magazine typography. The central focus is a stylized portrait made of overlapping speech bubbles, halftone dots, and neon-colored paper scraps. Glossy and matte finishes alternate for visual contrast, while metallic silver, electric blue, and hot pink accents add a futuristic touch. The layout is chaotic yet harmonious, with elements intentionally misaligned, rotated, or skewed, and subtle grid lines hinting at the source material." \
  "Mistral Think" "Pop Art Magazine Collage"

queue_job 30 \
  "A cutting-edge collage merging digital glitch art with traditional paper textures, featuring holographic foil strips, circuit board patterns, translucent acetate layers, and iridescent cellophane. Fragmented QR codes, pixelated typography, neon wireframe shapes, and binary code snippets float over a backdrop of crumpled metallic paper, frosted mylar, and static-cling vinyl. The high-contrast color scheme uses electric purples, cyans, magentas, and lime greens against deep blacks and metallic silvers, with elements appearing to glow, pulse, or flicker." \
  "Mistral Think" "Futuristic Digital Collage"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "A surreal mixed media collage art composition featuring torn vintage botanical illustrations of ferns and orchids layered over faded anatomical heart sketches. Cutouts of Victorian newspaper clippings with elegant serif typography are pasted haphazardly across the background. Fragments of aged sepia photographs showing mysterious hands and delicate moth wings are integrated into the design. The edges of the paper pieces are visibly ripped and textured, revealing layers of cream-colored cardstock beneath. Subtle fabric swatches of faded floral cotton add tactile depth. The color palette consists of muted mustard yellows, dusty rose, and deep forest greens, creating a nostalgic, dreamlike aesthetic with high contrast shadows." \
  "Qwen 3.7 Plus Tinking" "Vintage Botanical Anatomy Collage"

queue_job 32 \
  "A dynamic cyberpunk collage art piece constructed from torn tech magazine pages, glossy photographs, and metallic foil scraps. The composition depicts a towering futuristic cityscape with jagged skyscrapers formed by overlapping cutouts of circuit board patterns and neon-lit architectural blueprints. Fragments of Japanese kanji printed on translucent tracing paper are layered over vibrant magenta and cyan photographic strips. Ripped edges of dark charcoal cardstock create deep shadows and structural depth, while tiny pieces of reflective silver fabric simulate glowing holographic advertisements. The aesthetic is highly textured, blending gritty urban decay with sleek high-tech elements, utilizing a striking color palette of electric blue, hot pink, and stark black." \
  "Qwen 3.7 Plus Tinking" "Cyberpunk Cityscape Collage"

queue_job 33 \
  "A striking Bauhaus-inspired collage art composition built from precisely cut geometric shapes and torn construction paper. Bold primary colors like vivid crimson, deep cobalt blue, and bright sunflower yellow dominate the composition. The design features overlapping circles, sharp triangles, and sweeping arcs created from matte and glossy paper scraps. Fragments of vintage architectural blueprints and grid-patterned graph paper are subtly integrated into the background layers. Small pieces of coarse burlap fabric add a contrasting tactile element to the smooth paper surfaces. The arrangement is perfectly balanced yet dynamically asymmetrical, emphasizing clean lines, stark negative space, and a modernist aesthetic with crisp, sharp edges and flat, vibrant color blocking." \
  "Qwen 3.7 Plus Tinking" "Bauhaus Geometric Collage"

queue_job 34 \
  "A dreamlike celestial collage art composition merging deep ocean waves with a starry night sky. The artwork is crafted from torn pieces of vintage nautical maps, celestial star charts, and glossy nature magazine photographs. Swirling ocean waves formed by ripped blue and teal paper scraps transition seamlessly into a cosmic galaxy made of dark indigo tissue paper and glittering silver foil stars. Fragments of old handwritten letters and faded polaroid photographs of lighthouses are scattered throughout the cosmic waters. The visible torn edges and layered paper textures create a rich, tactile depth. The mood is mystical and tranquil, featuring a harmonious palette of midnight blues, pearlescent whites, and soft gold accents." \
  "Qwen 3.7 Plus Tinking" "Celestial Ocean Collage"

queue_job 35 \
  "A vibrant pop art collage art piece celebrating retro consumerism and comic book aesthetics. The composition is assembled from torn vintage advertisement pages, halftone dot printed paper, and glossy comic book panels. Bright, saturated colors like cherry red, lemon yellow, and turquoise blue clash energetically across the canvas. Cutouts of retro household items, classic sports cars, and exaggerated facial expressions are pasted in a chaotic, overlapping grid. Strips of red and white gingham fabric add a playful, domestic texture to the mixed media surface. The artwork features bold black outlines, stark Ben-Day dot patterns, and highly visible ripped paper edges, creating a loud, nostalgic, and visually explosive mid-century modern aesthetic." \
  "Qwen 3.7 Plus Tinking" "Pop Art Consumerism Collage"

# --- GLM 5V ---
queue_job 36 \
  "A surreal mixed-media collage artwork featuring torn pieces of vintage newspaper clippings with faded typography, weathered photographs of city streets from the 1950s, fragments of old postcards with handwritten notes, dried flower petals pressed between translucent vellum sheets, strips of colorful washi tape in geometric patterns, pieces of aged map parchment showing fictional coastlines, torn edges of music sheet paper with musical notations, snippets of fabric lace and burlap textures, vintage postage stamps from different countries, and metallic gold leaf accents scattered throughout. All elements layered with visible shadows and depth, creating a dreamlike urban narrative composition on a textured cream background with subtle coffee stains and ink splatters, artistic handmade aesthetic with overlapping transparent layers." \
  "GLM 5V" "Urban Memory Fragments"

queue_job 37 \
  "An intricate botanical collage composition featuring hand-cut silhouettes of exotic tropical leaves in various shades of emerald and sage green, pressed real flower specimens including roses and daisies with delicate petal details visible, torn pages from antique botanical illustration books showing scientific plant drawings, fragments of seed packets with vintage typography, pieces of handmade rice paper with watercolor washes in soft pastel tones, dried fern fronds and eucalyptus sprigs embedded between layers, vintage garden journal entries with cursive handwriting, butterfly wing patterns cut from iridescent paper, small circular frames containing microscopic plant cell diagrams, and threads of natural twine weaving through the arrangement. Layered with dimensional depth against a warm beige background, organic flowing composition with elements cascading diagonally." \
  "GLM 5V" "Botanical Dreamscape Montage"

queue_job 38 \
  "A celestial-themed collage artwork constructed from torn pieces of deep navy blue and midnight black textured paper creating a starry void background, cut-out circles of holographic foil paper representing planets and moons in varying sizes, fragments of old astronomy charts and star maps with constellation lines drawn in white ink, pieces of metallic silver and gold mylar film crinkled to resemble nebula clouds, vintage space mission photographs with astronauts and rocket ships, torn edges of glossy magazine pages reflecting rainbow light spectrums, sequins and tiny mirror shards scattered like distant stars, pieces of translucent vellum with chalk pastel smudges in purple and teal, rubber stamp imprints of geometric shapes, and thin strips of aluminum foil arranged in orbital paths. Dynamic cosmic composition with layered transparency effects." \
  "GLM 5V" "Cosmic Constellation Assemblage"

queue_job 39 \
  "An elegant fashion history collage featuring torn swatches of luxurious fabrics including silk satin, velvet, lace, and tweed in rich jewel tones, cut-out fashion illustrations from 1920s Vogue magazines showing flapper dresses and cloche hats, fragments of vintage sewing patterns with dotted lines and measurement markings, pieces of old perfume advertisements with Art Deco typography and glamorous models, buttons and beads glued as three-dimensional embellishments, torn edges of fabric care labels in multiple languages, snippets of handwritten dressmaker's notes on aged index cards, ribbon samples in silk and grosgrain textures, vintage jewelry photographs showing pearl necklaces and brooches, and watercolor fabric dye swatches bleeding into surrounding papers. Sophisticated vertical arrangement with overlapping layers creating depth and shadow, muted color palette of burgundy, champagne gold, and dusty rose." \
  "GLM 5V" "Vintage Fashion Timeline"

queue_job 40 \
  "A marine-inspired collage composition featuring torn pieces of aqua blue and seafoam green watercolor paper with salt crystal textures, cut shapes of translucent vellum resembling jellyfish and seaweed fronds, fragments of old nautical maps showing ocean currents and depth contours, vintage mermaid illustrations from storybooks with scales in iridescent colors, pieces of actual sandpaper and crushed shell fragments embedded in resin-like glue, torn edges of fishing net patterns printed on mesh fabric, snippets of poetry about the sea in typewriter font on aged paper, seaglass pieces in frosted green and amber tones pressed into the surface, coral branch silhouettes cut from pink and orange cardstock, and silver fish skeleton drawings layered beneath semi-transparent waves. Horizontal flowing composition with elements appearing to float and drift, coastal color palette with white foam accents." \
  "GLM 5V" "Oceanic Tidal Layers"

# --- Kimi K2.6 Thinking ---
queue_job 41 \
  "A handmade collage art composition featuring torn vintage postcards, aged airmail envelopes, yellowed passport stamps, and faded sepia photographs layered with translucent tracing paper and delicate tissue. Scattered ephemera include antique compass illustrations, weathered train tickets, delicate pressed wildflowers, and foreign currency fragments adhered with visible glue texture and subtle tape residue. Soft cream and muted teal color palette with rough paper edges, subtle creases, and overlapping translucent layers creating dimensional depth. Handwritten cursive notes in faded ink peek through torn corners and burned edges. Matte paper texture, analog cut-and-paste aesthetic, gentle shadows between overlapping elements, nostalgic wanderlust atmosphere, highly detailed mixed media artwork with authentic vintage character." \
  "Kimi K2.6 Thinking" "Vintage Travel Memories"

queue_job 42 \
  "An intricate collage art piece assembled from torn botanical illustrations, dried fern specimens, vintage seed packets, and handmade paper in sage green and dusty rose tones. Layered translucent vellum sheets reveal pressed pansies and handwritten plant names in elegant copperplate script beneath overlapping fern fronds. Scattered elements include moth illustrations, twine bows, watercolor leaf studies, and antique book pages with faded Latin text. Visible glue brushstrokes, deckled paper edges, and subtle coffee staining enhance the organic handmade quality. Soft natural lighting, gentle shadows between layers, harmonious muted earth tones, delicate washi tape strips, romantic herbarium aesthetic, highly detailed mixed media botanical artwork with textural depth." \
  "Kimi K2.6 Thinking" "Botanical Dreamscape"

queue_job 43 \
  "A dynamic collage artwork constructed from torn street posters, weathered newspaper clippings, spray paint stencils, and peeling billboard fragments layered over concrete gray and brick red textures. Jagged edges expose overlapping layers of faded concert flyers, vintage subway maps, and bold typographic ransom-note lettering in black and safety orange. Scattered elements include torn denim swatches, cracked paint chips, rusted metal textures, and gritty photocopied zine pages. Visible masking tape strips, staple marks, and wheat-paste residue emphasize the raw urban aesthetic. Dramatic high-contrast lighting, deep shadows between torn layers, contemporary street art atmosphere, chaotic yet composed layout, highly detailed mixed media collage with authentic metropolitan energy." \
  "Kimi K2.6 Thinking" "Urban Fragment Symphony"

queue_job 44 \
  "A surreal collage composition featuring torn astronomical charts, vintage moon phase engravings, silver foil fragments, and midnight blue velvet paper layered with translucent star maps. Scattered ephemera include antique compass roses, handwritten astrological calculations, dried lavender sprigs, and fragmented poetry in faded gold ink. Celestial elements of brass telescope illustrations, constellation diagrams, and aged celestial globes overlap with iridescent washi tape and delicate thread stitching. Deep indigo and warm amber palette with visible glue texture, burned paper edges, and subtle glitter dust. Ethereal soft lighting, mysterious shadows between dimensional layers, dreamlike cosmic atmosphere, romantic vintage scientific aesthetic, highly detailed mixed media celestial artwork with enchanting nostalgic depth." \
  "Kimi K2.6 Thinking" "Celestial Memory Map"

queue_job 45 \
  "A nostalgic collage artwork built from torn vintage vinyl record sleeves, yellowed concert ticket stubs, faded music sheet fragments, and textured Kraft paper in warm sepia and burnt sienna tones. Layered elements include peeling record label stickers, analog cassette tape ribbons, handwritten setlists in smudged pencil, and distressed wood grain textures. Scattered ephemera feature brass instrument silhouettes, microphone illustrations, and fragmented jazz poetry in bold letterpress type. Visible glue residue, rough torn edges, staple holes, and subtle coffee ring stains enhance the authentic analog aesthetic. Warm ambient lighting, soft shadows between overlapping layers, rhythmic visual composition, retro musical atmosphere, highly detailed mixed media collage celebrating vintage audio culture." \
  "Kimi K2.6 Thinking" "Analog Rhythm Archive"

# --- Deepseek Instant ---
queue_job 46 \
  "A rich collage composition blending the chaos of a metropolis with musical harmony. Torn edges of sheet music overlap with fragmented newspaper headlines about city life, while cut-out photographs of skyscrapers, bridges, and crowded streets are layered at dynamic angles. Swatches of textured gray and crimson fabric suggest movement and noise, with scattered vintage ticket stubs and postage stamps adding ephemeral depth. Hand-drawn treble clefs and notes float across the surface, connecting disparate elements. The palette mixes monochrome urban photography with warm sepia and bold red accents, creating a rhythmic, gritty, yet lyrical visual symphony of found paper and printed matter." \
  "Deepseek Instant" "Urban Symphony"

queue_job 47 \
  "A nostalgic collage celebrating forgotten flora, constructed from yellowed encyclopedia pages, torn herbarium sheets, and faded botanical illustrations. Pressed petals and fern fronds are rendered as actual paper cutouts with visible deckled edges, layered over handwritten diary entries and calligraphic script fragments. Delicate lace fabric and translucent vellum create subtle texture, while watercolor wash stains bleed softly into the background. Vintage seed packets and illustrated plant diagrams overlap with photographic close-ups of flowers, all assembled with visible glue shadows and curling corners. The soft palette of sage green, dusty rose, ochre, and cream evokes a gentle, antique garden preserved in paper." \
  "Deepseek Instant" "Botanical Memory"

queue_job 48 \
  "A steampunk-inspired collage of industrial fragments, featuring cut-out blueprints of clockwork mechanisms, torn pages from engineering manuals, and photographed brass gears interlocked at skewed angles. Metallic foil scraps and embossed paper simulate copper and steel plates, while watch parts and rivets appear as dimensional die-cut elements. Overlapping translucent vellum with technical diagrams adds depth, with handwritten calculation notes scrawled in pencil across the surface. Dark charcoal, burnished gold, and oxidized teal dominate the palette, punctuated by bright crimson paper hearts stitched with thread. The arrangement suggests a living machine, combining rigid mechanical precision with organic, hand-torn organic shapes." \
  "Deepseek Instant" "Mechanical Heart"

queue_job 49 \
  "A surreal nautical collage where a Victorian-era sailing ship glides through a sea of stars, constructed from antique celestial charts, torn map fragments, and illustrated ocean currents. The ship's hull is pieced together from wood-grain paper and copperplate engravings, while its sails are cut from yellowed sheet music and cloud photographs. Layered compass roses, astrolabe diagrams, and handwritten logbook entries float around the vessel, with torn edges revealing glimpses of a night sky beneath. Wispy cotton fabric simulates fog, and stamped moon phases add rhythm. The muted navy, silver, pearl, and sepia palette creates a dreamlike, ethereal journey across imagined horizons." \
  "Deepseek Instant" "Dreamscape Voyager"

queue_job 50 \
  "A vibrant celebration of global heritage, assembling torn magazine portraits of diverse faces interwoven with patterned paper from African kente, Indian block prints, and Japanese chiyogami. Cut-out architectural motifs—minarets, pagodas, and domes—overlap with fragments of multilingual newspaper text and musical score. Embroidered fabric swatches and gold foil accents add tactile richness, while hand-painted geometric borders connect the disparate pieces. Visible creases, curling corners, and glue smudges emphasize the handcrafted process. The explosive palette of terracotta, indigo, gold, emerald, and fuchsia creates a harmonious yet dynamic whole, representing unity through layered, fragmented cultural symbols and personal ephemera." \
  "Deepseek Instant" "Cultural Mosaic"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A vibrant mixed media collage composition featuring torn pieces of old newspaper clippings layered over faded magazine photographs of city skylines, strips of patterned wrapping paper in bold reds and teals, fragments of handwritten letters on yellowed paper, scraps of vintage fabric in floral prints, cut-out letters from different fonts pasted haphazardly, rough torn edges revealing underlying layers of coffee-stained cardstock, splashes of acrylic paint bleeding through paper textures, pieces of torn maps and postage stamps arranged in overlapping chaotic yet balanced arrangement, visible glue marks and white paste smudges, textured surface with dimensional depth." \
  "ERNIE 5.1" "Urban Memories Collage"

queue_job 52 \
  "An intricate collage artwork composed of pressed dried flower petals layered on torn pages from botanical encyclopedias, cut-out illustrations of exotic birds from vintage nature magazines, scraps of hand-painted rice paper in soft greens and creams, fragments of old botanical diagrams with ink wash details, pieces of sheer lace fabric overlapping watercolor paper, torn edges of sepia-toned photographs of gardens, handwritten plant labels on aged card stock, overlapping translucent vellum pieces creating depth, visible brayer marks and matte medium texture, rustic earthy palette with bursts of magenta and gold leaf accents throughout the composition." \
  "ERNIE 5.1" "Botanical Dreamscape Collage"

queue_job 53 \
  "A dynamic collage artwork built from torn concert ticket stubs layered over cut-out photographs of vintage microphones and instruments from old music magazines, strips of sheet music pages folded and pasted at angles, pieces of retro album cover art in bold pop colors, fragments of handwritten lyrics on lined notebook paper, scraps of brown kraft paper and corrugated cardboard, cut-out letters spelling rhythm and sound from different typography sources, splattered ink marks and rubber stamp impressions, pieces of denim fabric and torn vinyl record sleeves, overlapping textures with visible white glue residue, warm amber and electric blue color harmony throughout." \
  "ERNIE 5.1" "Vintage Music Collage"

queue_job 54 \
  "A layered collage composition featuring torn pieces of nautical charts and old maritime maps as the base, overlaid with cut-out photographs of vintage ships and lighthouses from travel magazines, scraps of blue and white striped fabric resembling sailor cloth, fragments of weathered postcards with ocean scenes, pieces of translucent wax paper creating water-like effects, torn newspaper clippings about sea voyages, cut-out starfish and shell illustrations from natural history books, rough-edged pieces of sandpaper and corrugated cardboard, handwritten navigation notes on aged parchment, visible paste and tape marks, palette of deep navy teal seafoam and warm sandy tones." \
  "ERNIE 5.1" "Ocean Voyage Collage"

queue_job 55 \
  "A joyful exploded collage made from torn pieces of brightly colored tissue paper in hot pink orange and electric yellow layered over cut-out photographs of carnival masks and dancers from cultural magazines, fragments of patterned Indian textile and African wax print fabric, scattered pieces of confetti and metallic foil scraps, torn comic book panels with bold ink lines, cut-out numbers and celebratory words from various print sources, pieces of hand-stamped paper with geometric patterns, rough torn newspaper edges revealing bright underlayers, splashes of gold and silver paint, visible adhesive texture and overlapping dimensional elements creating festive energy throughout." \
  "ERNIE 5.1" "Festival of Colors Collage"

# --- LongCat Deep search ---
queue_job 56 \
  "An ethereal collage featuring a central anatomical heart rendered in vintage medical illustrations, surrounded by fragmented botanical prints in muted sepia and faded crimson. Torn edges of handwritten love letters flutter across the composition like butterfly wings, their text partially obscured by layered washes of watercolor and ink splatters. Delicate lace patterns from old tablecloths overlap with microscope slides showing cellular structures, creating a dreamlike tapestry where science meets sentiment. Scattered vintage playing cards and clock face fragments add temporal mystery, while dried pressed flowers anchor the design in organic texture. The overall effect balances clinical precision with romantic nostalgia, executed in warm amber, rose, and antique cream tones with occasional pops of electric blue for visual tension." \
  "LongCat Deep search" "Anatomical Dreamscape Collage"

queue_job 57 \
  "A vibrant collage where wild botanical specimens of ferns and tropical leaves burst through layers of torn architectural blueprints and concrete texture fragments. Vintage road maps partially obscure newspaper clippings about city planning, their text creating a visual rhythm against the organic forms. Splashes of emerald green and rainforest greens contrast with stark graphite grays and blueprint cyan. Ripped postcards featuring overgrown urban ruins peek through the composition, their edges dissolving into watercolor washes that suggest nature reclaiming space. Small pressed wildflowers and herbarium specimens anchor different corners, their delicate stems intersecting with bold geometric shapes cut from subway schedule fragments. The piece merges controlled urban geometry with wild botanical chaos, celebrating the tension between concrete and chlorophyll through layered translucent tissue paper layers that soften harsh edges." \
  "LongCat Deep search" "Urban Nature Fusion"

queue_job 58 \
  "A dynamic textural collage built primarily from torn fragments of vintage dictionaries and encyclopedia pages, where oversized letters and punctuation marks become abstract shapes. The composition centers on the word MEMORY spelled out in mismatched typefaces cut from different paper stocks, surrounded by cascading columns of dictionary definitions oriented in every direction. Intersecting these text layers are strips of aged sheet music, creating a visual rhythm like a collaged musical score. Bits of old family photographs — a shoe, a clock face, a window — emerge from the typographic field, their nostalgic quality heightened by the surrounding ink-saturated text. Tea-stained parchment fragments and pieces of vintage wallpaper add tactility, while handwritten annotations in copper ink create connective threads between disparate textual elements. The palette remains sophisticated with warm ivory, charcoal black, and faded burgundy against soft cream backgrounds." \
  "LongCat Deep search" "Typographic Memory Grid"

queue_job 59 \
  "An evocative collage combining fragments from vintage travel brochures, faded foreign currency notes, and borders of international postage stamps. A central vintage passport photo of an unidentifiable traveler emerges from layers of torn railway tickets and boarding passes from the 1920s-1950s. Postcards featuring Istanbul bazaars, Parisian cafes, and Japanese temples overlap with handwritten letters in Cyrillic and Arabic scripts, their mysterious content adding exotic intrigue. Pieces of antique silk fabric from different cultures — a scrap of Indonesian batik beside a fragment of Scottish tartan — frame the edges. Language translation cards and faded transportation schedules create horizontal bands across the composition, while small pressed golden leaves and flattened paper flowers add natural elements to this nostalgic journey through time and space, all unified by warm sepia and aged gold tones." \
  "LongCat Deep search" "Cultural Travel Time Capsule"

queue_job 60 \
  "A haunting self-portrait collage composed entirely of torn fragments from different photographic sources — images of hands, eyes, lips, and textile patterns. A central eye in black and white emerges from layers of fashion magazine imagery and old fabric swatches, its iris collaged from fragments of colorful abstract paintings. Pieces of handwritten journal entries about identity weave through the composition, their text creating organic lines across the portrait's fragmented face. Vintage wallpaper patterns and stamps featuring famous art reproductions fill negative spaces, while translucent tracing paper layers at various opacities create depth and mystery. Cut-out letters from different magazines spell fragments of poetry about self-discovery, their typefaces deliberately mismatched to emphasize fragmentation. The overall palette balances cool photographic grays with warm textile tones — terracotta, dusty rose, and faded denim blue — resulting in a deeply personal meditation on identity, memory, and the assembled self." \
  "LongCat Deep search" "Fragmented Self-Portrait"

echo "✅ All 60 jobs queued in scheduler"

