#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: New York in the 1970s — street photography, period cars, fashion,
#        and signage across various NYC neighborhoods and eras
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+42+-+NY+1970s
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------
# --- Claude Sonnet 5 high ---
queue_job  1 \
  "A candid street photograph of Times Square in New York City in 1974, capturing the gritty, sun-bleached energy of the neighborhood just before its infamous decline into peak seedy glamour. Steam rises from a subway grate as pedestrians in the fashions of the era hurry past adult theater marquees and grindhouse cinemas. The scene is caught at golden hour, long shadows stretching across cracked asphalt, with grainy film texture reminiscent of Kodachrome stock and the observational street photography style of a candid frame from a low-budget crime film of that year. Muted ochre and rust tones dominate, cut by flashes of chrome and neon just beginning to flicker on." \
  "Claude Sonnet 5 high" "Times Square Neon 1974"

queue_job  2 \
  "A documentary-style photograph of a New York City subway platform in the summer of 1977, during the height of the transit system's roughest years. Graffiti-tagged train cars pull into a dim, tiled station lit by flickering fluorescent tubes, while commuters in period-accurate clothing wait with newspapers tucked under their arms. The air feels humid and heavy, rendered in the desaturated, high-grain look of press photography from that year, evoking the visual mood of the city during the blackout summer. Composition is candid and slightly off-kilter, as if shot quickly on 35mm film, with warm sodium-vapor lighting bleeding into cool shadow, capturing the tension and vitality of New York at that exact moment in its history." \
  "Claude Sonnet 5 high" "Subway Platform Summer 1977"

queue_job  3 \
  "A wide street-level photograph of Fifth Avenue in New York City, dominated by a boxy yellow Checker Marathon taxi cab idling at the curb beside a chrome-bumpered Chevrolet Impala. Pedestrians wear bell-bottom trousers, wide-collared polyester shirts, platform shoes, and oversized aviator sunglasses, with men sporting long sideburns and women in maxi coats and knit berets. Storefront awnings in faded orange and brown stripes line the sidewalk, and a hand-painted barbershop sign hangs above a doorway. The photograph has the warm, slightly faded color palette of an aging Kodachrome print, soft grain throughout, natural overcast daylight, and a documentary composition capturing everyday urban life with authentic period detail down to the hubcaps and hemlines." \
  "Claude Sonnet 5 high" "Checker Cab Fifth Avenue"

queue_job  4 \
  "A photograph of a Brooklyn brownstone stoop on a hot summer afternoon, where a family gathers around a portable transistor radio. A rusted Ford Pinto and a wood-paneled station wagon are parked along the curb, their paint faded by years of sun. Kids wear striped tube socks, cutoff denim shorts, and tie-dye t-shirts, while an older man sits in a folding lawn chair wearing a short-sleeve button-up shirt with a wide collar and dark polyester slacks. Laundry lines stretch between fire escapes overhead. The image has the warm, sun-faded color cast of an old Polaroid or amateur 35mm snapshot, soft natural light, visible film grain, and a nostalgic, lived-in composition true to inner-city Brooklyn of the period." \
  "Claude Sonnet 5 high" "Brooklyn Stoop Summer"

queue_job  5 \
  "A highly detailed photograph of a New York City corner bodega storefront, its hand-painted sign reading \"ROSA'S GROCERY - COLD BEER - LOTTO\" in bold red and yellow lettering above the entrance, with a smaller weathered placard beneath reading \"OPEN 24 HRS\". The awning is faded turquoise canvas with peeling white trim, and a cardboard sign taped inside the window reads \"EGG CREAM 25¢\". Crates of oranges and bananas sit stacked outside beside a rusted red Coca-Cola cooler chest. A payphone with a chrome handset stands on the corner, its metal body streaked with grime. Two men in flannel jackets and flat caps lean against the brick wall, one holding a folded newspaper with a visible masthead. The color palette is rich with brick red, mustard yellow, and faded teal, rendered in the warm, high-contrast grain of vintage color film photography, natural afternoon light casting long shadows across the sidewalk." \
  "Claude Sonnet 5 high" "Bodega Corner Detailed"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A grainy, raw 35mm color photograph capturing the authentic atmosphere of a gritty New York City subway platform in the year 1974. The scene is filled with authentic period details: weathered walls covered in layer upon layer of colorful, stylized graffiti tags, dim and flickering fluorescent lighting casting harsh shadows, and concrete floors littered with old newspapers. A few commuters stand waiting, capturing the distinct mood, tension, and texture of mid-1970s Manhattan transit." \
  "Gemini 3.5 Flash" "Subway Gritty Reality"

queue_job  7 \
  "A wide-angle cinematic street photograph showcasing the chaotic, vibrant energy of Times Square during a rainy night in 1978. The wet asphalt reflects the overwhelming glow of massive, flashing neon theater marquees and vintage billboards advertising Broadway shows. Crowds of people move along the sidewalks under umbrellas, capturing the specific, unpolished, and bustling nighttime atmosphere unique to New York City in the late 1970s." \
  "Gemini 3.5 Flash" "Times Square Neon Glow"

queue_job  8 \
  "A candid street photograph captured on a bustling Manhattan corner. In the foreground, a boxy yellow Checker Marathon taxi cab with distinct chrome bumpers streaks past, kicking up steam from a nearby pothole. On the sidewalk, a pedestrian walks briskly, dressed in quintessential period fashion: a sharp leather trench coat, wide-leg flared denim trousers, and platform shoes. The background features brownstone buildings and vintage metal trash cans, evoking a strong sense of nostalgia." \
  "Gemini 3.5 Flash" "Yellow Cabs and Street Style"

queue_job  9 \
  "A warm, hazy afternoon photograph in Central Park capturing casual everyday life. A couple walks along a leaf-strewn path, wearing classic era clothing: earth-toned corduroy jackets, oversized aviator sunglasses, and chunky knit sweaters. In the background, vintage steel-framed baby strollers and retro bicycles are visible against the classic Central Park skyline, with older architectural high-rises framing the upper edge of the frame under a soft, desaturated autumn sky." \
  "Gemini 3.5 Flash" "Central Park Autumn Stroll"

queue_job 10 \
  "A highly detailed, cinematic composition of a Lower East Side street corner. A prominent retro neon sign glows with bold red and blue text reading \"KATZ'S DELICATESSEN\" in a vintage font, alongside hand-painted window signs displaying prices like \"Hot Pastry \$1.50\". Outside on the sidewalk, a newsstand is stacked with vintage editions of the New York Post showing bold headlines from the era. A pristine cream-colored 1973 Ford Gran Torino is parked at the curb under the warm, amber glow of a towering street lamp, casting long shadows across the textured concrete pavement." \
  "Gemini 3.5 Flash" "Delancey Street Delicatessen"

# --- ChatGPT ---
queue_job 11 \
  "A candid street photography scene set in Midtown Manhattan, New York City in 1974, capturing the atmosphere of a busy weekday afternoon. Crowded sidewalks filled with office workers wearing wide-lapel suits, flared trousers, turtlenecks, polyester dresses, long trench coats, leather handbags, oversized sunglasses, and platform shoes. Yellow taxicabs weave through traffic beside a Ford LTD, Chevrolet Caprice, Plymouth Fury police car, and a blue-and-white MTA bus. Steam rises from street vents while orange construction barrels line part of the avenue. Vintage storefronts display hand-painted signs, neon hotel marquees, old bank logos, cigarette advertisements, and movie posters. Analog traffic lights, chrome parking meters, newspaper boxes, and classic cast-iron lampposts complete the authentic setting. Slight film grain, Kodachrome-inspired colors, realistic afternoon sunlight reflecting from skyscraper windows, documentary style, highly detailed, historically accurate." \
  "ChatGPT" "Midtown Manhattan Rush Hour, New York City, 1974"

queue_job 12 \
  "A vibrant documentary-style photograph depicting a neighborhood block party in the South Bronx, New York during the summer of 1978. Brick apartment buildings covered with colorful graffiti murals surround the gathering. Residents sit on folding chairs while children play with hydrant water spraying into the street. Young DJs perform beside towering homemade speaker stacks, breakdancers entertain a cheering crowd, and families enjoy the warm evening. Parked nearby are a Dodge Monaco, Chevrolet Impala, Pontiac LeMans, and a weathered Ford Econoline van. Fashion reflects the late 1970s with bell-bottom jeans, satin jackets, Kangol hats, tube socks, striped shirts, gold chains, afros, feathered hairstyles, and colorful sneakers. Utility poles carry layers of flyers and concert posters. Warm sunset lighting, rich urban textures, authentic neighborhood atmosphere, cinematic realism, subtle vintage film grain, highly detailed composition." \
  "ChatGPT" "South Bronx Block Party, New York, Summer 1978"

queue_job 13 \
  "A photorealistic nighttime street scene in Times Square during the late 1970s after a fresh rainstorm. Wet pavement mirrors hundreds of colorful neon lights and illuminated theater marquees. Crowds carrying umbrellas move between glowing cinemas, electronics shops, diners, magazine stands, and souvenir stores. Rows of classic yellow taxis pass beneath bright advertising signs while steam escapes from subway grates. Chrome bumpers sparkle under the reflections. Billboards advertise vintage cameras, airlines, Broadway productions, watches, cigarettes, and soft drinks using period typography and bold saturated colors. A newsstand displays newspapers with black-and-white headlines, postcards, magazines, and comic books. Every storefront appears busy and lived-in, with realistic reflections on windows, puddles, polished automobiles, and stainless steel surfaces. Moody cinematic lighting, exceptional realism, balanced composition, nostalgic atmosphere, high photographic detail." \
  "ChatGPT" "Rainy Times Square After Dark"

queue_job 14 \
  "A richly detailed documentary photograph of a bustling Lower East Side neighborhood market in the late 1970s. Narrow sidewalks overflow with fruit stands, flower vendors, bakery displays, newspaper kiosks, clothing racks, and small family-owned grocery stores. Delivery trucks unload fresh produce while pedestrians browse window displays. Apartment fire escapes cast geometric shadows across weathered brick buildings decorated with faded painted advertisements. Vintage bicycles lean against iron fences. The street is filled with realistic everyday details including wooden produce crates, handwritten price signs, striped awnings, rotary payphones, mailbox collection boxes, metal trash cans, and hanging street banners. Natural morning sunlight creates soft shadows and warm highlights across chrome, glass, and pavement. The atmosphere feels busy yet welcoming, emphasizing authentic urban life, documentary photography, rich textures, realistic color palette, subtle analog film characteristics." \
  "ChatGPT" "Lower East Side Morning Market"

queue_job 15 \
  "An ultra-detailed street-level photograph of 42nd Street and Seventh Avenue, New York City, autumn 1979, filled with authentic period details. Giant illuminated theater marquees display \"A CHORUS LINE\", \"SUPERMAN\", and \"APOCALYPSE NOW\". Neon storefront signs read HOTEL ASTOR, DINER OPEN 24 HOURS, CAMERAS FILM FLASH, RECORDS & TAPES, LIVE JAZZ TONIGHT, NEWSSTAND, and SUBWAY ENTRANCE. A glowing HOT DOGS 50¢ cart sits beside yellow taxis waiting at a red traffic light. Traffic includes a Chevrolet Caprice taxi, Dodge Diplomat sedan, GMC delivery truck, and MTA bus. Pedestrians wear earth-tone trench coats, plaid jackets, knit sweaters, leather boots, flared jeans, scarves, and wide-collared shirts. Bright red, amber, turquoise, deep blue, and warm white neon reflects across rain-soaked asphalt and polished chrome bumpers. Steam rises from street grates beneath elevated billboards, overflowing newspaper boxes, graffiti-covered utility cabinets, and crowded sidewalks. Hyper-realistic documentary photography, cinematic composition, fine analog film grain, exceptionally accurate late-1970s New York atmosphere." \
  "ChatGPT" "42nd Street Crossroads, New York City, 1979"

# --- Grok fast ---
queue_job 16 \
  "A highly detailed cinematic photograph of bustling Times Square in New York City in 1975, crowded sidewalks filled with pedestrians in 1970s fashion, bright colorful neon signs glowing against the evening sky, classic yellow Checker taxis and vintage cars on the streets, theater marquees advertising popular shows of the era, steam rising from manholes, gritty yet vibrant urban atmosphere, film grain, realistic lighting and shadows, shot on 35mm film, authentic 1970s New York street life scene." \
  "Grok fast" "Times Square Neon Nights 1975"

queue_job 17 \
  "Photorealistic image capturing a snowy Central Park in New York during the winter of 1972, people walking along paths wearing heavy coats, scarves and hats typical of early 1970s style, frozen lake with skaters, bare trees covered in snow, distant Manhattan skyline with iconic buildings of the period, soft winter light, detailed snow textures, atmospheric perspective, authentic 1970s New York winter day scene." \
  "Grok fast" "Central Park Winter Scene 1972"

queue_job 18 \
  "Vibrant 1970s New York street photography of heavy traffic on Broadway with numerous iconic yellow Checker taxis and Dodge Polara sedans from the era, pedestrians in bell-bottom pants, leather jackets, platform shoes and wide collars crossing the street, storefronts with period signage, newspaper stands, hot dog vendors, detailed car models and chrome reflections, warm afternoon sunlight, filmic color grading, highly realistic 1970 New York atmosphere." \
  "Grok fast" "Yellow Cab Traffic on Broadway"

queue_job 19 \
  "Dynamic scene of a Harlem street in 1970s New York featuring classic 1970s muscle cars like Ford Mustang Mach 1 and Chevrolet Impala parked along the curb, African American residents in afros, dashikis, and colorful 70s clothing styles, kids playing, stoop conversations, detailed brick buildings with fire escapes, corner bodegas, realistic textures and clothing details, golden hour lighting, authentic gritty yet lively 1970 New York neighborhood vibe." \
  "Grok fast" "Harlem Street Life with Vintage Cars"

queue_job 20 \
  "Ultra-detailed photorealistic view of 42nd Street in New York City in 1976 at dusk, crowded with people in polyester suits, mini skirts, platform heels and wide lapel jackets, bright neon signs reading \"PEEP SHOWS\", \"TIMES SQUARE\", \"ADULT THEATER\", \"PLAYLAND\", \"XXX\", flickering red blue and yellow lights reflecting on wet pavement, yellow taxis and old police cars, movie marquees for \"Taxi Driver\" and era films, steam from grates, trash on sidewalks, intricate architectural details, film grain, rich saturated colors, shadows and highlights, authentic gritty 1970s New York street energy." \
  "Grok fast" "Detailed 42nd Street Hustle 1976"

# --- Copilot Smart ---
queue_job 21 \
  "A bustling Times Square scene in New York during the 1970s, neon signs glowing against the night sky, marquees advertising films of the era, crowds of people in bell-bottom jeans, leather jackets, and wide-collared shirts moving through the sidewalks, yellow cabs weaving through traffic, and the atmosphere alive with the energy of the city. The prompt should emphasize the year and location, capturing the authentic vibe of Times Square in the 1970s, with gritty textures, warm tones, and a cinematic feel that reflects the cultural heartbeat of New York at that time." \
  "Copilot Smart" "Times Square 1970s Scene"

queue_job 22 \
  "A detailed street view of Brooklyn in 1977, showing brownstone buildings with fire escapes, graffiti on brick walls, and children playing stickball in the street. Cars like the Chevrolet Impala and Ford LTD are parked along the curbs, while adults in polyester suits and patterned dresses walk past corner stores. The prompt should highlight the year and location, ensuring the model depicts the authentic look of New York in the late 1970s, with muted colors, realistic shadows, and a nostalgic atmosphere." \
  "Copilot Smart" "Brooklyn Street 1977"

queue_job 23 \
  "A photorealistic Manhattan avenue scene in the 1970s, featuring rows of parked cars like Dodge Chargers, Pontiac Firebirds, and Cadillac Coupe de Villes, all with chrome details and vintage styling. Pedestrians wear flared trousers, platform shoes, and oversized sunglasses, while street vendors sell hot dogs from carts. The prompt should emphasize the fashion and car models of the decade, with warm sunlight casting long shadows across the pavement, and the city's architecture towering in the background." \
  "Copilot Smart" "Classic Cars on Manhattan Avenue"

queue_job 24 \
  "A lively Harlem jazz club scene in the 1970s, with glowing neon signs above the entrance reading \"Live Jazz Tonight,\" and posters advertising local musicians. Inside, the atmosphere is smoky and vibrant, with musicians in wide-lapel suits playing saxophones and trumpets, while the audience in colorful dresses and patterned shirts enjoys the performance. The prompt should highlight the clothing styles and cultural energy of the decade, with rich colors, dim lighting, and a sense of rhythm and movement throughout the composition." \
  "Copilot Smart" "Harlem Jazz Club Night"

queue_job 25 \
  "A highly detailed street corner in New York during the 1970s, with visible sign texts such as “Broadway,” “West 42nd Street,” and storefronts advertising “Pizza 99¢” and “Record Shop.” Billboards display bold typography and bright colors typical of the era, while graffiti tags cover brick walls. Cars like the AMC Gremlin and Oldsmobile Cutlass drive past, and pedestrians in denim jackets, patterned shirts, and bell-bottoms cross the street. The prompt should emphasize the authenticity of signage, colors, and textures, creating a vivid snapshot of everyday life in 1970s New York." \
  "Copilot Smart" "1970s New York Street Signs"

# --- Mistral Think ---
queue_job 26 \
  "A bustling, vibrant night scene at Times Square, New York City, in the year 1975. The iconic location is alive with the glow of countless neon signs in pink, blue, and white, advertising Broadway shows like \"A Chorus Line\" and \"Chicago,\" movies, and classic diners. Yellow Checker taxis, the quintessential symbol of 1970s New York, are scattered across the street, their headlights cutting through the urban haze. Crowds of people, dressed in the height of 1970s fashion—bell-bottom jeans in denim and corduroy, platform shoes, wide lapels on polyester shirts, and voluminous afros—mill about, some heading to theaters, others to late-night eateries. The air is thick with the energy of the city that never sleeps, and the marquees of famous theaters like the Minskoff and the Lyric shine brightly, casting a kaleidoscope of colors on the wet pavement below." \
  "Mistral Think" "Times Square at Night, 1975"

queue_job 27 \
  "A serene autumn afternoon in Central Park, New York, in the year 1978. The park is a haven of tranquility amidst the urban jungle, with winding paths lined by trees displaying their fall foliage in rich hues of orange, burnt sienna, and golden yellow. People in typical 1970s leisure attire—flared trousers in earthy tones, turtleneck sweaters, long wool coats, and knitted headbands—leisurely stroll, sit on cast-iron benches, or enjoy a picnic on checkered blankets. A vintage 1970s Ford Mustang Mach 1, polished and gleaming in its signature grabber orange paint, is parked on a nearby path, its bold, aggressive design a testament to the automotive style of the decade." \
  "Mistral Think" "Central Park in Autumn, 1978"

queue_job 28 \
  "A typical, sun-dappled street in New York during the mid-1970s, lined with parked classic cars that define the automotive landscape of the era. A Chevrolet Chevelle SS, with its sleek, muscular design and chrome accents, sits proudly next to a compact Ford Pinto, both cars reflecting the diverse automotive trends of the time. The buildings lining the street are tall and narrow, their facades adorned with intricate fire escapes, a quintessential feature of New York architecture, painted in shades of gray and rust-red. Pedestrians, dressed in the decade's signature styles—wide-lapelled suits in bold colors like mustard yellow and avocado green, disco-inspired shirts with psychedelic patterns, and afros—add a dynamic human element to the scene." \
  "Mistral Think" "1970s New York Street with Classic Cars"

queue_job 29 \
  "A lively, sunlit sidewalk scene in New York during the height of the disco era in the late 1970s. A group of stylish, confident New Yorkers, embodying the bold fashion of the time, walk down the pavement with an air of nonchalance. The men sport wide-collared shirts, often unbuttoned to reveal gold chains and medallions glinting in the sunlight, high-waisted flared trousers in denim or polyester, and platform shoes. The women wear glittery, form-fitting dresses in metallic gold and silver, high heels, and large, oversized sunglasses. Their hair is styled in voluminous afros, sleek, straight cuts, or layered shags. In the background, a graffiti-covered subway entrance adds an urban touch, while a newsstand displays magazines like \"Rolling Stone\" and \"The Village Voice.\"" \
  "Mistral Think" "Disco Era Fashion on a New York Sidewalk"

queue_job 30 \
  "A hyper-detailed, cinematic snapshot of a New York street corner at dusk in the mid-1970s. Dominating the scene is a large, vintage neon sign for \"Joe's Pizza,\" its letters glowing in classic red and white, with a flickering \"Open 24 Hours\" sign below in warm amber. A yellow Checker taxi, its roof adorned with a lighted \"NYC Taxi\" sign, is parked at the curb. The surrounding buildings are red brick with wrought-iron fire escapes. Pedestrians wear bell-bottom jeans, leather jackets with shearling collars, and colorful knitted scarves. Steam rises from a manhole cover, and the sky transitions from deep purple to orange. A newspaper stand displays a \"New York Times\" headline from 1976: \"City Faces Fiscal Crisis.\" Amber streetlights cast a warm glow on the cobblestone pavement, where a discarded soda can and crumpled movie ticket lie." \
  "Mistral Think" "Detailed 1970s New York Street Corner at Dusk"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "A gritty, atmospheric street-level photograph of Times Square in New York City in the year 1977. The scene captures the essence of the era with faded neon signs, peeling paint on the marquee of the Apollo Theater, and steam rising from a manhole cover. Pedestrians in vintage 1970s attire, including wide-lapel suits, polyester shirts, and platform shoes, walk past a classic yellow Checker Cab. The lighting is moody, with a mix of warm incandescent streetlights and the cool glow of neon, reflecting off the wet asphalt. The composition emphasizes the urban decay and vibrant, chaotic energy of 1970s New York, shot on 35mm film with visible grain and authentic period details." \
  "Qwen 3.7 Plus Tinking" "Times Square 1977"

queue_job 32 \
  "A candid documentary-style photograph of a bustling Lower East Side street corner in New York City in 1974. The scene features a classic stoop with residents sitting on the steps, wearing authentic 1970s fashion like turtleneck sweaters, corduroy jackets, and bell-bottom jeans. A vintage Ford Mustang and a Chevrolet Impala are parked along the curb, their chrome bumpers gleaming in the afternoon sun. Fire escapes zigzag up the brick facades of the tenement buildings, and a faded bodega sign hangs above the corner store. The atmosphere is raw and unfiltered, capturing the everyday life of the neighborhood with natural lighting, shot on Kodachrome film, showcasing the distinct architectural and cultural landscape of 1970s Manhattan." \
  "Qwen 3.7 Plus Tinking" "Lower East Side 1974"

queue_job 33 \
  "A stylish street photography shot capturing the essence of New York City fashion and automotive design in 1970. The focal point is a group of young New Yorkers walking down a tree-lined avenue, wearing highly specific 1970s clothing: men in tailored three-piece suits with wide lapels, silk ascots, and pointed-toe boots; women in colorful mod dresses, knee-high go-go boots, and oversized sunglasses. Parked along the street is a pristine 1970 Plymouth Barracuda in bright orange and a classic 1970 Chevrolet Chevelle in metallic blue. The background features classic pre-war New York architecture. The lighting is bright and crisp, highlighting the textures of the fabrics and the gleaming chrome of the cars, shot on medium format film for a sharp, vibrant, and highly detailed retro aesthetic" \
  "Qwen 3.7 Plus Tinking" "Fifth Avenue Fashion 1970"

queue_job 34 \
  "A dynamic traffic scene on the approach to the Brooklyn Bridge in New York City, specifically highlighting the vehicles and street style of 1970. The foreground features a detailed lineup of classic cars: a 1970 Dodge Challenger in bright yellow, a 1970 AMC Javelin in red, and a classic yellow Checker Marathon taxi. Pedestrians waiting at the crosswalk are dressed in authentic 1970s attire, including women in peasant blouses with fringe vests and men in denim jackets with corduroy collars and aviator glasses. The background shows the iconic stone towers of the bridge. The scene is bathed in the golden hour sunlight, creating long shadows and highlighting the retro automotive curves and the distinct fashion silhouettes, captured with a cinematic, nostalgic 35mm film look" \
  "Qwen 3.7 Plus Tinking" "Brooklyn Bridge Traffic 1970"

queue_job 35 \
  "A highly detailed, photorealistic street-level view of a Greenwich Village storefront in New York City. The central focus is a vintage record shop with a large, illuminated sign reading \"VILLAGE VINYL\" in bright cherry red and electric blue neon. The window display features album covers of classic 1970s rock and soul artists, with a hand-painted sign saying \"NEW ARRIVALS\". The building facade is made of weathered red brick, with a green awning above the door displaying the text \"OPEN DAILY\" in white serif font. A classic 1970s streetlamp casts a warm yellow glow. The sidewalk has a faded green \"CROSSWALK\" painted on the asphalt. Colors are highly saturated: the neon red contrasts with the deep green awning and the rich brown of the brick. Shot in ultra-high resolution, capturing every texture, peeling paint, and glowing filament." \
  "Qwen 3.7 Plus Tinking" "Greenwich Village Storefront 1975"

# --- GLM 5V Turbo ---
queue_job 36 \
  "A vibrant nighttime photograph of Times Square, New York City, in 1977, capturing the electric energy of the era before Disneyfication transformed the area. The scene is dominated by massive, glowing neon billboards advertising Camel cigarettes, Coca-Cola, and Broadway shows like \"A Chorus Line\" and \"Annie.\" Yellow Checker cabs crowd the intersection, their distinctive rounded shapes and checkerboard patterns instantly recognizable as quintessential 1970s New York taxis. Pedestrians in flared bell-bottom jeans, platform shoes, polyester shirts, and wide-lapel suits fill the crosswalks. The air feels thick with exhaust fumes and the promise of disco nights ahead. Grainy film photography aesthetic with rich saturated colors, light leaks, and that characteristic 1970s color palette of warm oranges, deep reds, and mustard yellows. Street vendors sell hot dogs from carts with \"NATHAN'S FAMOUS\" signage. The Twin Towers are visible in the distant skyline, standing tall as symbols of the decade. Graffiti tags adorn subway station entrances, and the overall atmosphere conveys the gritty yet glamorous spirit of New York at its most chaotic and creative peak." \
  "GLM 5V Turbo" "Times Square 1977 Neon Nigh"

queue_job 37 \
  "Summer afternoon in the South Bronx, New York, 1975, during the height of the borough's most challenging era yet also its most culturally fertile period. Burned-out abandoned buildings line the street, their windows boarded up or shattered, while graffiti-covered walls display early hip-hop style tagging in bold spray-painted letters. Young people gather on corners wearing Adidas sneakers, Kangol hats, leather bomber jackets, and gold chains—the birth of hip-hop fashion visible in real-time. A boombox rests on a fire hydrant, and kids play stickball in the street using a manhole cover as home base. Parked along the curb are period-authentic vehicles: a rusted Ford Pinto, a lime-green Dodge Dart, and a classic Chevrolet Impala with custom detailing. A bodega storefront displays hand-painted signs advertising \"BODEGA—COLD BEER—ICE\" in Spanish and English. The intense summer sun casts harsh shadows across cracked sidewalks littered with discarded soda cans and newspapers with headlines about the city's fiscal crisis. The image captures both urban decay and resilient community spirit, photographed in documentary style with Kodachrome film's distinctive warm tones and fine grain." \
  "GLM 5V Turbo" "South Bronx Summer 1975 Street Life"

queue_job 38 \
  "Elegant street scene along Fifth Avenue near Rockefeller Center in mid-1970s Manhattan, showcasing the sophisticated fashion of New York's elite during this glamorous decade. Wealthy shoppers stroll the sidewalk dressed in designer attire: women wear maxi dresses with bold floral patterns, platform wedge sandals, structured shoulder bags, and oversized tinted sunglasses; men sport wide lapels on their suit jackets, flared trouser legs, turtleneck sweaters under blazers, and carefully groomed mustaches. A gleaming black Cadillac Eldorado with whitewall tires and chrome detailing is parked at the curb, while a yellow cab waits nearby. Storefronts display the era's luxury brands with elaborate window displays featuring mannequins in Halston and Diane von Furstenberg wrap dresses. Doormen in traditional uniforms stand at attention outside exclusive apartment buildings. The street features vintage traffic lights, ornate metal trash cans, and newspaper vending machines displaying the New York Post and Daily News with their iconic bold headlines. Autumn leaves scatter across the pavement, and the golden afternoon light reflects off glass skyscrapers creating lens flare effects. Photographed with the shallow depth of field and warm color grading typical of 1970s fashion photography." \
  "GLM 5V Turbo" "Fifth Avenue Fashion Parade 1974"

queue_job 39 \
  "Evening atmosphere in Greenwich Village's MacDougal Street, New York, 1972, capturing the bohemian folk music scene at its cultural zenith. Acoustic guitar players perform on the sidewalk outside legendary venues like The Gaslight Cafe and Cafe Wha?, their cases open for tips. The crowd is a mix of beatnik holdovers and emerging hippie culture: young men with long hair, beards, and denim vests over tie-dye shirts; women in peasant blouses, long corduroy skirts, fringed leather bags, and round wire-rimmed glasses. Incense smoke mingles with cigarette smoke in the evening air. A Volkswagen Beetle van painted with peace symbols and psychedelic artwork is double-parked, its rear doors open revealing cushions and acoustic instruments inside. Vintage bookstore windows display dog-eared paperbacks by Kerouac and Ginsberg. Hand-painted folk club posters advertise open mic nights and feature performers like Bob Dylan and Joni Mitchell in their early careers. Cobblestone streets, wrought-iron street lamps casting amber pools of light, and brownstone stoops where residents sit chatting create an intimate neighborhood feel. The photograph has the moody, intimate quality of available-light street photography with rich shadows and the distinctive color rendition of early 1970s film stock." \
  "GLM 5V Turbo" "Greenwich Village Folk Scene 1972"

queue_job 40 \
  "Hyper-detailed gritty nighttime view of 42nd Street between Seventh and Eighth Avenues in Manhattan, 1978, at the notorious height of the \"Deuce\" grindhouse theater district era before Mayor Giuliani's cleanup. The street is a cacophony of neon signs in garish pinks, electric blues, acid greens, and blood-reds advertising adult entertainment with provocative text like \"XXX LIVE GIRLS,\" \"PEEP SHOWS 25¢,\" \"ALL NIGHT,\" and \"AIR CONDITIONED\" in mismatched fonts ranging from elegant script to crude hand-painted block letters. Marquee bulbs spell out movie titles including \"DEEP THROAT,\" \"THE EXORCIST,\" and \"TEXAS CHAINSAW MASSACRE\" above theater entrances with velvet ropes and ticket booths. Three-card monte games operate on the sidewalk while hustlers approach passersby. Abandoned cars including a stripped Ford Granada and a dented AMC Gremlin clutter the curb. Pornographic bookstores display magazines in plastic wrappers behind grimy windows. Trash overflows from overflowing dumpsters, and the street surface is slick with mysterious fluids reflecting the neon glow. Police cruisers with \"NYPD\" markings patrol slowly. Every surface is textured with grime, peeling paint, and urban decay. The image should have extreme detail visible even when zoomed: individual neon tubes flickering, specific brand names on discarded cups and newspapers, graffiti tags on walls, the weave pattern on clothing fabrics, reflections in store windows showing interior details, steam rising from subway grates with \"SUBWAY\" cast into the metal covers, and the specific model badges on every vehicle. Color palette emphasizes the sickly fluorescent tones mixed with deep shadows, captured with the high contrast and visible grain of pushed Tri-X film processed in D-76 developer, embodying the dangerous allure of 1970s Times Square at its most infamous." \
  "GLM 5V Turbo" "42nd Street Grindhouse District 1978 Hyper-Detailed"

# --- Kimi K2.6 Fast ---
queue_job 41 \
  "A wide-angle street-level photograph of Times Square in New York City, 1974. Neon signs glow in electric blues, hot pinks, and burnt oranges against the night sky. Crowds of pedestrians in wide-lapel polyester suits, platform shoes, and long feathered hair walk past marquees advertising Broadway shows. A Checker cab waits at the curb. Steam rises from a subway grate. The scene captures the gritty, electric energy of Midtown Manhattan during the city's most iconic decade." \
  "Kimi K2.6 Fast" "Times Square, 1974"

queue_job 42 \
  "Documentary-style photograph of a street corner in The Bronx, New York, summer 1977. Abandoned buildings with boarded-up windows line the block, covered in vibrant graffiti tags and political murals. A few kids in cutoff denim shorts and tube socks play near an open fire hydrant spraying water into the street. An old Pontiac Catalina sits parked on the cracked asphalt. The warm golden-hour light hits the brick facades, capturing the raw, resilient spirit of the neighborhood during a turbulent era." \
  "Kimi K2.6 Fast" "The Bronx, 1977"

queue_job 43 \
  "A candid street photograph on a Chelsea avenue in New York City, 1975. A woman in a burnt-orange wrap dress with oversized tortoiseshell sunglasses and a wide-brimmed floppy hat walks a Afghan Hound on a long leather leash. A man in a brown corduroy blazer, flared jeans, and thick sideburns leans against a powder-blue 1973 Chevrolet Impala parked at the curb. The storefront behind them displays hand-painted signs for a record shop. Fall leaves scatter the sidewalk. The color palette is muted earth tones with pops of mustard yellow and avocado green, shot on Kodachrome film with soft grain." \
  "Kimi K2.6 Fast" "Chelsea Street, 1975"

queue_job 44 \
  "A cinematic photograph of St. Mark's Place in the East Village, New York, 1976. A punk rocker with a torn black leather jacket, safety pins through the collar, spiked blue hair, and ripped fishnet stockings stands outside the CBGB club entrance. Next to them, a beat poet in a tweed newsboy cap and vintage army surplus coat smokes a cigarette beside a rust-colored 1972 Ford Pinto. The brick wall behind is plastered with concert flyers for The Ramones and Blondie. A neon \"OPEN\" sign flickers in a bodega window. The asphalt glistens from recent rain, reflecting the red and green traffic lights overhead." \
  "Kimi K2.6 Fast" "East Village, 1976"

queue_job 45 \
  "A hyper-detailed, vivid color photograph of the Coney Island boardwalk on a sweltering August afternoon in 1973. In the foreground, a hot dog vendor in a stained white apron and paper hat stands beside a bright yellow Nathan's Famous cart, the bold red cursive \"Nathan's\" logo clearly visible on the umbrella. A family of four — the father in a powder-blue short-sleeve polyester shirt with wide butterfly collar and high-waisted tan trousers, the mother in a floral halter maxi dress with cork wedge sandals, the children in striped tank tops and knee-length corduroy shorts — walks toward the Wonder Wheel. The vintage Ferris wheel rises in the background, its red and white gondolas catching the sunlight. To the right, a hand-painted wooden sign reads \"COLD BEER — SODA — COTTON CANDY\" in chipped red and blue letters. A 1971 Chevrolet Nova in metallic gold with a white vinyl roof is parked along the curb. The Atlantic Ocean glitters turquoise beyond the wooden planks. Seagulls wheel overhead. The sky is a saturated cerulean with puffy cumulus clouds. The entire scene is drenched in the golden, hazy light of late summer, rendered with the rich color saturation and subtle film grain of a 35mm Kodachrome slide." \
  "Kimi K2.6 Fast" "Coney Island Boardwalk, August 1973"

# --- Deepseek Vision ---
queue_job 46 \
  "A bustling street scene in Times Square, New York City, in the year 1974. The iconic neon billboards glow in the evening, showing advertisements for Broadway shows and cigarettes. Pedestrians in 1970s fashion walk by, the streets are crowded with yellow taxis, and the atmosphere is gritty yet vibrant. The image should capture the essence of mid-1970s Manhattan, with the looming dark sky and the bright city lights." \
  "Deepseek Vision" "Times Square 1974"

queue_job 47 \
  "A gritty underground subway station in New York City, 1976. Graffiti-covered train cars arrive at the platform, with commuters wearing bell-bottoms, plaid jackets, and wide-collar shirts. The station is dimly lit, with old fluorescent lights and tiled walls. The scene captures the raw, urban decay and the diverse crowd of the 1970s city life, showing a snapshot of daily life in the Bronx or Manhattan during that era." \
  "Deepseek Vision" "Subway Platform 1976"

queue_job 48 \
  "A sunny afternoon on a street corner in Brooklyn, New York, 1975. A classic yellow Checker Marathon taxi is parked at the curb, next to a olive green Ford Pinto and a brown Dodge Charger. Men in wide-lapel polyester suits and women in floral maxi dresses and platform shoes cross the street. A fire hydrant is spraying water onto the asphalt. The scene is lively with pedestrians, newsstands, and a hot dog cart, capturing the automotive and fashion styles characteristic of mid-70s New York." \
  "Deepseek Vision" "Street Corner with Checker Cab"

queue_job 49 \
  "A nighttime street scene on Fifth Avenue, New York City, 1977. A sleek black Cadillac Eldorado convertible drives past the lit windows of high-end stores. The driver wears a leather jacket and aviator sunglasses, while a woman in a sequined halter top sits in the passenger seat. The street is illuminated by amber streetlights and neon signs. The scene highlights the opulent and edgy style of late 1970s Manhattan nightlife, with period-appropriate vehicles and attire." \
  "Deepseek Vision" "Night Drive on Fifth Avenue"

queue_job 50 \
  "A highly detailed street corner in the South Bronx, New York, circa 1978. The dominant feature is a corner bodega with a faded red and white \"Grocery\" sign, and a hand-painted \"Lotto\" sign below it. Next door, a graffiti-covered wall has a large tag reading \"TAKE 5\" in neon green and orange spray paint. A rusty yellow Checker cab is parked diagonally, its rear door open. A middle-aged man in a brown leather bomber jacket and a woman in a long coat and floppy hat stand near a newsstand stacked with copies of the Daily News and the New York Post. The street features broken asphalt, a fire escape, and a trash can overflowing. The sky is overcast grey, contrasting with the vibrant colors of the graffiti and signage. The image should feel like a documentary photograph of the gritty, colorful, and resilient spirit of 1970s New York." \
  "Deepseek Vision" "Bodega Corner in the South Bronx"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A gritty nighttime street scene in New York City during the famous 1977 blackout, July 13th, 1977. Dark brownstone buildings line the block with shattered storefronts and broken glass on the sidewalk. People crowd the streets carrying flashlights and candles, silhouettes against the glow of a distant fire. Graffiti covers fire escapes and brick walls. Yellow Checker cabs are abandoned mid-street with doors open. A bodega with a metal roll-down gate half open spills warm light onto the pavement. The atmosphere is tense and chaotic yet oddly communal, with neighbors sharing food on stoops. Smoke rises from a distant building. The humid summer night air is visible through haze and steam rising from manhole covers. Shot in a documentary photography style with grainy 35mm film look, muted earth tones, deep shadows, and high contrast reminiscent of 1970s photojournalism." \
  "ERNIE 5.1" "New York City 1977 Blackout"

queue_job 52 \
  "Inside Grand Central Terminal in New York City, 1975, during the early morning rush hour. Commuters in wide-lapel suits and long trench coats flood the main concourse beneath the iconic celestial ceiling mural. Men wear fedoras and wide-brim hats, women in knee-length pleated skirts and polyester blouses. A Pan Am departures board with split-flap letters hangs overhead. The polished marble floors reflect the warm tungsten lighting. A newsstand sells copies of the New York Daily News and Daily News tabloids. Bell-bottom jeans and platform shoes visible among the crowd. Vintage advertising posters for Marlboro and Coca-Cola line the walls. The architecture is grand Beaux-Arts with brass fixtures and clock faces. Shot in analog film photography style with warm amber tones, slight grain, and soft focus edges characteristic of mid-1970s color photography." \
  "ERNIE 5.1" "Grand Central Terminal 1975"

queue_job 53 \
  "A bustling daytime scene at Times Square New York City 1974. A bright yellow 1973 Ford LTD Crown Victoria taxi cab is stopped at a red light, its chrome bumper gleaming under the sun. Pedestrians cross the street including a man in a brown leather aviator jacket, bell-bottom denim jeans, and a wide-collar disco shirt, and a woman in a flowing maxi dress with earth-tone geometric print and platform wedge sandals. The backdrop features massive hand-painted billboards advertising Coca-Cola, Winston cigarettes, and the Broadway show The Wiz. Neon signs for Bond Clothes and Pepsi flicker above. A hot dog vendor pushes a red metal cart on the corner. The streets are gritty with litter and steam rising from grates. Shot as a candid street photograph with saturated 1970s Kodachrome color palette, warm reds and oranges, slight lens flare, and natural afternoon sunlight casting long shadows." \
  "ERNIE 5.1" "Times Square Vintage Taxi 1974"

queue_job 54 \
  "A rainy autumn afternoon on Bleecker Street in Greenwich Village New York City 1976. A 1971 Chevrolet Chevelle SS in faded burnt orange is double-parked outside a cluttered record shop. The sidewalk is wet and reflective, puddles mirroring neon signs. A young man leans against the brick wall wearing a suede fringe jacket over a band t-shirt, faded Wrangler jeans with a wide belt, and Converse All-Stars. Next to him a woman in a suede miniskirt, turtleneck sweater, and knee-high brown leather boots holds an umbrella. The record shop window displays vinyl LPs by David Bowie and the Ramones. A handwritten poster on the door reads live folk music tonight. Fire escapes zigzag up red brick buildings. Trash bags line the curb. Shot in moody documentary style with desaturated cool tones, rain-slicked surfaces, and the characteristic softness of 1970s street photography with visible film grain and muted greens and browns." \
  "ERNIE 5.1" "Bleecker Street Village Scene 1976"

queue_job 55 \
  "A vibrant street corner in Loisaida the Lower East Side Puerto Rican neighborhood of New York City 1978. A weathered corner bodega with a hand-painted wooden sign reading El Sol Deli in red and yellow block letters on a dark green background sits beneath a rusted fire escape. The deli awning is faded red and white striped canvas. A 1975 Dodge Dart Swinger in avocado green is parked curbside. Outside the shop a hand-lettered cardboard sign on the sidewalk reads cold beer 50 cents and fresh pasteles today. Stacked crates of Coca-Cola bottles in red and white sit near the entrance. A woman in a colorful floral housedress and curlers in her hair steps out carrying a brown paper bag. Kids in flannel shirts and corduroy pants play stickball in the street. The building facade is peeling tan paint with colorful murals. Laundry hangs between fire escapes. Shot in vivid saturated 1970s color film with rich primaries, warm golden hour light, deep contrast, and the textured look of aged analog photography." \
  "ERNIE 5.1" "Loisaida Deli Corner 1978"

# --- LongCat Deep search ---
queue_job 56 \
  "Times Square in 1975, crowded streets illuminated by massive neon signs and marquees, yellow taxi cabs and buses moving slowly through traffic, pedestrians wearing bell-bottom jeans, polyester shirts with wide lapels, leather jackets, and platform shoes, vintage movie theaters with glowing marquees, newsstands with period newspapers and magazines, street vendors with carts, storefront advertisements and neon signs in colors of orange, yellow, green, and pink, warm evening light glowing across the urban landscape, capturing the gritty glamour and vibrant energy of 1970s New York City." \
  "LongCat Deep search" "Times Square 1975 Neon Nights"

queue_job 57 \
  "CBGB club on the Bowery in 1977, the iconic punk rock venue with its weathered brick exterior and hand-painted sign, young people in ripped jeans, leather jackets with band patches, spiked hair, and combat boots hanging around outside, graffiti-covered walls, vintage cars parked along the street including a 1973 Ford LTD and 1975 Cadillac Eldorado, neon beer signs glowing in windows, the raw rebellious atmosphere of downtown Manhattan's emerging punk scene, capturing the unpolished energy and counterculture spirit that defined late 1970s New York underground." \
  "LongCat Deep search" "CBGB Punk Rock Scene 1977"

queue_job 58 \
  "A 1970 Cadillac Eldorado in burgundy with white leather interior parked in front of an elegant limestone townhouse on the Upper East Side, next to a 1972 Ford LTD in powder blue, a 1973 Buick Century in dark green, and a 1974 Chevrolet Impala in white, drivers and pedestrians in period clothing including fur coats, fedora hats, and wide-legged trousers, doormen in uniform standing by entrance, street trees with autumn leaves, classic New York street lamps, the refined yet distinctly 1970s atmosphere of Manhattan's luxury automotive culture, captured in golden afternoon light with authentic vintage details and textures." \
  "LongCat Deep search" "1970s Cadillacs in Manhattan"

queue_job 59 \
  "Greenwich Village street corner in the mid-1970s, fashionable New Yorkers wearing wide-brimmed felt hats, oversized sunglasses, high-waisted bell-bottom trousers in earth tones, platform shoes and boots, leather mini skirts and chunky knit sweaters, men in corduroy blazers with suede elbow patches and turtlenecks, women with voluminous blow-dried hair and men with thick sideburns and mustaches, vintage RCA Victor television trucks passing by, storefronts displaying clothing and accessories, community bulletin boards covered in flyers, the eclectic bohemian style of 1970s Village fashion, captured in soft afternoon light with rich period textures." \
  "LongCat Deep search" "1970s New York Street Fashion"

queue_job 60 \
  "A classic chrome and stainless steel diner on 49th Street in Times Square, neon signs reading \"DINER\" in hot pink and turquoise blue, \"OPEN 24 HOURS\" in red neon, \"HAMBURGERS\" in yellow neon glowing inside the window, waitress in pink uniform with white apron visible through the window, classic menu board visible with prices like \"Burger \$1.50\" and \"Coffee 50 cents,\" counter stools with red vinyl upholstery, jukebox glowing orange in the corner, pedestrians in 70s clothing passing by, yellow cab exterior reflected in the chrome, capturing the authentic nostalgic glow and detailed signage of 1970s Times Square." \
  "LongCat Deep search" "Times Square Diner Neon Lights"

echo "✅ All 60 jobs queued in scheduler"

