#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Limited color palette multilayer stencil graffiti — Banksy-level
#        minimal colors up to 8-16 colors on layered stencils, protest and
#        scenery topics
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+40+-+stensil+graffity
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------
# --- Claude Sonnet 5 medium ---
queue_job  1 \
  "A multilayer stencil graffiti mural rendered in Banksy-inspired minimalism, three-color palette of matte black, bone white, and a single scorched red, depicting a small child holding a balloon shaped like a riot shield while soldiers' silhouettes retreat into a fractured wall of layered spray textures. Rough concrete backdrop with drips, overspray halos, and torn poster edges beneath the stencil layers. Each color occupies its own crisp masked layer with visible registration offset for authentic hand-cut stencil imperfection. High contrast, flat graphic shapes, no gradients, urban documentary framing like a found street photograph, dusk lighting casting long diagonal shadows across the wall, gritty textured spray grain throughout." \
  "Claude Sonnet 5 medium" "Silent Vigil"

queue_job  2 \
  "Eight-color layered stencil graffiti piece transforming a derelict factory wall into a surreal wheat field, ochre and mustard stalks stenciled over cracked cement, a lone farmer silhouette in indigo pushing a rusted shopping cart plow, smokestacks bleeding faded turquoise smoke into a dusty rose sky. Each stencil layer shows slight paint bleed and masking-tape edges, spray can drip trails pooling near the baseboard. Composition balances hope and industrial decay, bold flat color blocks separated by thin black keylines, weathered brick texture peeking through worn patches, golden hour warmth, documentary street-art photography feel, no gradients, high graphic contrast throughout." \
  "Claude Sonnet 5 medium" "Harvest of Concrete"

queue_job  3 \
  "Minimal two-color stencil graffiti in charcoal black and warning-sign yellow on a weathered subway wall, showing a human figure dissolving into television static lines while reaching toward a glowing antenna tower silhouette. Stark negative space dominates the composition, Banksy-style economy of line, single bold statement rather than clutter. Visible stencil bridges holding disconnected shapes together, authentic spray edge fuzz, drip marks trailing from the figure's outstretched hand. Cracked tile texture and grime streaks bleed through the yellow layer. Cold fluorescent underpass lighting, long shadow cast rightward, gritty urban realism, flat uninflected color fields, no gradient shading, poster-like graphic clarity." \
  "Claude Sonnet 5 medium" "Signal Lost"

queue_job  4 \
  "Twelve-color multilayer stencil mural depicting a coastal cliffside scene, teal and cobalt waves crashing beneath cream-colored gulls, a weathered lighthouse in rust orange standing against a violet dusk sky streaked with coral clouds. Each hue sits on its own precisely masked stencil layer, subtle overspray halos where layers meet, rough plaster wall texture showing through eroded color patches. Composition blends painterly scenery with graphic street-art boldness, thick black outline layer unifying all shapes. Salt-stained concrete base, drip trails beneath the lighthouse, distant boat silhouette in near-black. Golden late-afternoon light, flat color fields with zero gradients, weathered authentic outdoor mural photography aesthetic." \
  "Claude Sonnet 5 medium" "Tidewatchers"

queue_job  5 \
  "Four-color stencil graffiti protest piece in black, grimy white, blood-orange, and steel gray, portraying a homeless figure seated against a alley wall wearing a newspaper crown, spray-painted coins scattering around bare feet. Raw brick texture bleeds through thin color layers, authentic tape-edge stencil lines, heavy drip trails beneath the figure suggesting rain or tears. Composition is deliberately sparse and emotionally direct, Banksy-style social commentary with generous negative space framing the subject. Overlapping poster scraps and faded tag marks clutter the lower wall edge. Harsh overhead streetlight casting stark shadow, flat unblended color blocks, documentary night-photography mood, gritty spray texture throughout the entire piece." \
  "Claude Sonnet 5 medium" "Paper Crown"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A stunning multilayer stencil graffiti mural spray-painted onto a weathered, distressed brick wall, capturing a small child holding a nostalgic tin can telephone while looking up at a massive, towering satellite dish. This thought-provoking artwork utilizes a highly restricted color palette of deep charcoal gray, crisp off-white, and a single, striking focal accent of electric blue paint. Sharp, clean stencil cutouts, subtle overspray mist, and authentic vertical paint drips define the separate layers. The background exhibits gritty concrete textures and realistic urban weathering. Every layer remains clearly defined, creating a powerful, high-contrast visual commentary on modern human connection versus technological isolation." \
  "Gemini 3.5 Flash" "Echoes of Connection"

queue_job  7 \
  "A vibrant multilayer stencil graffiti artwork applied to a rough, dark asphalt surface, depicting a majestic stag stepping out from a dense forest of geometric, polygonal trees. The design features a bold, limited palette of eight distinct colors: warm terracottas, burnt ochre, forest greens, cool teal, pale cream, and stark black outlines. Each layer is meticulously aligned, displaying visible spray-paint texture, subtle alignment offsets, and fine misting. The composition balances natural majesty with harsh urban medium, emphasizing the layered physical depth of the stencils. The background is textured, realistic street pavement with faint cracks and colorful, accidental paint splatters." \
  "Gemini 3.5 Flash" "Concrete Wildfire"

queue_job  8 \
  "A striking, minimalist multilayer stencil graffiti in the signature style of classic street protest art, applied to a stained concrete underpass wall. The visual depicts a soaring white dove of peace, intricately entangled in a highly detailed, barcodes-patterned net. This piece uses a stark, high-contrast color scheme of soot black, ash gray, and a single vivid splash of crimson red dripping from the barcode. Sharp stencil borders, realistic paint overspray, and light aerosol textures define the layered application. The background is gritty, weathered concrete with faint water stains, conveying a raw, impactful, and deeply emotional message on commercialized liberty." \
  "Gemini 3.5 Flash" "Price Tag on Freedom"

queue_job  9 \
  "An elaborate, highly detailed multilayer stencil graffiti mural on a dark alleyway plaster wall, showcasing an surreal desert landscape. This complex piece utilizes a vibrant, twelve-color palette of neon pink, deep indigo, bright violet, glowing amber, sunset orange, and mint green, structured across numerous distinct aerosol layers. A massive, glowing crescent moon hangs over stylized saguaro cacti, casting long, sharp shadows. Each layer displays crisp, hand-cut stencil edges, fine paint misting, and textured overspray. The plaster background has subtle cracks and peeling paint, highlighting the physical depth, clean execution, and brilliant color transitions of the complex street art." \
  "Gemini 3.5 Flash" "Neon Oasis"

queue_job 10 \
  "A captivating multilayer stencil graffiti portrait of a woman's face fading into cascading digital glitch patterns, sprayed onto a rusted steel shipping container. The artwork employs an eight-color industrial palette consisting of rusted iron, deep navy blue, bright turquoise, mustard yellow, dusty pink, charcoal black, and stark white highlights. The stencil layers are beautifully stacked, showing realistic physical alignment offsets, dry spray textures, and subtle paint runs. The background of the corrugated metal container features authentic rust spots, rivets, and weather-worn textures, enhancing the gritty, cyberpunk-infused aesthetic and the high-contrast, tactile depth of the stencil art." \
  "Gemini 3.5 Flash" "Analog Dreams"

# --- ChatGPT ---
queue_job 11 \
  "A multilayer stencil graffiti mural covering a weathered concrete wall, using a restrained palette of charcoal black, matte white, crimson, faded cyan, mustard yellow, muted olive, pale gray, and rust orange. The composition features a young woman raising a paper megaphone that releases a flock of geometric birds instead of sound, symbolizing peaceful resistance and the spread of ideas. Crisp stencil layers overlap with subtle spray paint overspray, worn edges, paint drips, and realistic urban textures. Strong negative space, bold silhouettes, and carefully aligned stencil passes create striking depth while preserving a clean street-art aesthetic inspired by large-scale public murals. High visual impact, authentic aerosol finish, contemporary urban atmosphere." \
  "ChatGPT" "Silent Megaphone"

queue_job 12 \
  "A sophisticated multilayer stencil graffiti artwork depicting an enormous wildflower emerging through cracked pavement, rendered with layered masks in black, ivory, sage green, dusty teal, warm ochre, coral red, lavender, steel blue, and soft beige. The flower petals contain miniature city skylines and tiny silhouettes of people gathering peacefully, suggesting hope growing within dense urban life. Precise stencil registration, controlled spray gradients, paint splatters, faded wall stains, chipped concrete, and authentic mural weathering enhance realism. Balanced composition, bold graphic forms, dramatic contrast, and limited colors create an instantly recognizable street-art statement with elegant simplicity while maintaining rich visual complexity through successive stencil layers." \
  "ChatGPT" "Concrete Bloom"

queue_job 13 \
  "A large multilayer stencil graffiti mural transforming a neglected brick wall into an illusion of an open window overlooking distant mountains, forests, and a calm sea. Built from carefully stacked stencil layers using black, white, slate gray, turquoise, forest green, sandy beige, muted blue, warm brown, and pale gold accents. Flying birds seamlessly cross between the painted landscape and the real urban environment, blending fantasy with reality. Visible aerosol textures, stencil bridges, slight paint bleed, peeling wall fragments, faded pigments, and subtle drips create authentic street-art character. Strong graphic composition, generous negative space, and visually arresting contrast evoke optimism through minimalist yet expressive urban mural design." \
  "ChatGPT" "Window to the Horizon"

queue_job 14 \
  "An eye-catching multilayer stencil graffiti composition portraying a diver suspended beneath an enormous transparent jellyfish formed entirely from floating plastic bags and discarded bottles. Built with layered stencil masks in black, white, ocean blue, turquoise, muted violet, gray, pale aqua, sandy beige, emerald green, and small coral highlights. Clean silhouettes contrast with detailed environmental textures created through multiple stencil passes, realistic aerosol overspray, chipped paint, weathered concrete, scratches, and gentle drips. The mural communicates environmental urgency without excessive complexity, combining minimalist street-art language with carefully layered color fields, cinematic lighting, and powerful symbolic storytelling worthy of an iconic public wall." \
  "ChatGPT" "The Weight of Plastic"

queue_job 15 \
  "A vibrant multilayer stencil graffiti mural celebrating urban creativity through the image of a cyclist whose spinning wheels transform into swirling musical notes, abstract flowers, and colorful city lights. Executed with layered stencil techniques using black, white, indigo, electric blue, burnt orange, magenta, pale yellow, emerald, silver gray, and muted cream while maintaining a disciplined limited palette. Multiple stencil registrations generate crisp graphic depth, subtle tonal transitions, and dynamic movement. Authentic spray paint textures, soft overspray, paint drips, cracked plaster, faded posters, and rough masonry reinforce the realism of the wall surface. Energetic composition, bold negative space, contemporary mural aesthetics, and memorable visual storytelling create a striking piece of urban street art." \
  "ChatGPT" "Midnight Bicycle Symphony"

# --- Grok fast ---
queue_job 16 \
  "A multilayer stencil graffiti masterpiece in limited color palette of stark black, blood red, faded yellow and cool blue tones, Banksy-inspired urban wall art. A young child reaching desperately for a floating heart-shaped balloon, the string slipping from tiny fingers, layered stencils creating sharp edges and depth with 8-12 overlapping color layers. Cracked concrete wall background with subtle drips and spray textures. Minimalist yet emotionally powerful social commentary on lost innocence, high contrast shadows, clean stencil cutouts, gritty street art aesthetic, eye-catching composition with negative space." \
  "Grok fast" "Stencil Child and Balloon Protest"

queue_job 17 \
  "Multilayer stencil graffiti on abandoned city wall, restricted palette of deep teal, vibrant magenta, black and metallic gold. A sly urban fox standing alert amid crumbling buildings and overgrown vines, multiple stencil layers building intricate fur details and glowing eyes. 10-14 color separations for rich depth and texture. Faded graffiti tags in background, dramatic lighting with sharp silhouettes, protest-art vibe blending nature reclaiming concrete jungle. Dynamic composition, high visual impact, clean layered stencils with spray paint overspray effects." \
  "Grok fast" "Urban Fox in Neon Ruins"

queue_job 18 \
  "Powerful multilayer stencil street art in minimal palette of icy blue, charcoal gray, crimson red and off-white. Dozens of hands breaking through turbulent water surface reaching upward in desperation, layered stencils creating rippling water effects and dramatic depth with 8-12 color passes. Social protest theme highlighting climate crisis and struggle. Dark moody atmosphere, high contrast, gritty urban wall texture, sharp stencil edges, emotionally charged composition with strong negative space and symbolic power." \
  "Grok fast" "Drowning Hands Rising"

queue_job 19 \
  "Stunning multilayer stencil graffiti in elegant limited palette of cherry blossom pink, midnight black, soft sage green and antique gold. A fierce female samurai warrior standing under blooming cherry trees with katana drawn, intricate armor and flowing petals rendered through 12-16 precise stencil layers. Traditional meets modern street art fusion, peaceful yet strong scenery with falling blossoms. Perfect balance of minimalism and detail, clean sharp cuts, atmospheric depth on weathered brick wall." \
  "Grok fast" "Cherry Blossom Samurai"

queue_job 20 \
  "Hypnotic multilayer stencil graffiti mural using restricted colors of electric purple, acid green, deep black and bone white. A massive watchful eye emerging from city skyscrapers, layered stencils creating realistic iris texture and surveillance atmosphere with 10-14 overlapping passes. Social commentary on privacy and big brother society. Dramatic perspective, intense gaze drawing viewer in, sharp geometric buildings below, gritty concrete background with subtle cracks and spray textures, bold eye-catching street art." \
  "Grok fast" "Giant Eye Watching City"

# --- Copilot Smart ---
queue_job 21 \
  "A multilayer stencil graffiti artwork showing a lone figure holding a placard, rendered in stark limited colors, with bold contrasts of black, white, and red. The stencil layers create depth with 8–10 color separations, each carefully aligned to form a striking silhouette. The background is textured with faint spray paint overspray, giving an urban wall authenticity. The composition emphasizes social protest, with the figure's shadow layered in muted tones, while the placard message is left blank for interpretation. The minimal palette enhances the raw emotional power, echoing Banksy-level simplicity yet expanded with multiple stencil layers for richness." \
  "Copilot Smart" "Graffiti Protest Silhouette"

queue_job 22 \
  "A stencil graffiti composition of a city skyline at dusk, built from 12 layered stencils in muted blues, oranges, and grays. The limited palette creates a dramatic gradient effect, with each stencil layer adding architectural detail—windows, rooftops, and bridges. The graffiti style emphasizes sharp edges and spray textures, while the layering produces depth and dimension. The skyline is framed by abstract stencil clouds and faint silhouettes of birds, adding movement. The overall effect is both gritty and poetic, capturing the essence of urban life through minimal yet powerful color choices." \
  "Copilot Smart" "Urban Skyline Layers"

queue_job 23 \
  "A multilayer stencil graffiti of a dove in flight, symbolizing peace, rendered with 8–12 stencil layers. The palette is restricted to whites, grays, and soft blues, with occasional accents of gold for emphasis. Each stencil layer adds feather detail, wing curvature, and shadow depth, creating a dynamic sense of motion. The dove contrasts against a textured wall background, with faint spray paint halos suggesting light. The composition balances minimalism with layered complexity, making the dove appear luminous and hopeful, while still grounded in the raw, rebellious aesthetic of street art." \
  "Copilot Smart" "Graffiti Peace Dove"

queue_job 24 \
  "A stencil graffiti portrait of a masked protester, created with 10–14 stencil layers in a limited palette of black, gray, and muted reds. The face is partially obscured by the mask, emphasizing anonymity and resistance. Each stencil layer adds shading and detail to the eyes, mask folds, and clothing texture. The background features faint stencil lettering and abstract shapes, suggesting slogans without being explicit. The layered approach creates a haunting, powerful image that resonates with themes of protest and defiance, while the restricted palette keeps the focus sharp and impactful." \
  "Copilot Smart" "Masked Protester Portrait"

queue_job 25 \
  "A multilayer stencil graffiti depicting a tree growing through cracked pavement, symbolizing resilience. The palette is limited to greens, browns, and grays, with 8–16 stencil layers adding foliage detail, bark texture, and pavement cracks. The layering creates depth, making the tree appear vibrant against the urban decay. Spray paint overspray adds authenticity, while stencil shadows enhance realism. The composition balances natural beauty with urban grit, delivering a thought-provoking image that feels both rebellious and hopeful, embodying the spirit of graffiti as a medium for social commentary and artistic expression." \
  "Copilot Smart" "Graffiti Nature Scene"

# --- Mistral Think ---
queue_job 26 \
  "A multilayer stencil graffiti on a weathered urban wall, depicting a child holding a cluster of balloons shaped like the Earth, with each continent a distinct color (red, blue, yellow, green, purple, orange, black, white). The background features subtle textures of cracked paint and faded protest slogans, enhancing the depth of the 8-color palette. The child's silhouette is bold and black, contrasting sharply with the vibrant balloons. The scene evokes a sense of hope and activism, with a minimalist yet impactful design." \
  "Mistral Think" "Stencil Revolution"

queue_job 27 \
  "A multilayer stencil graffiti on a concrete surface, showcasing a tree with sprawling branches transitioning into the silhouette of a city skyline. The tree uses a palette of 12 colors (shades of green, brown, gray, and metallic silver), while the skyline is a stark black, creating a striking contrast. The background includes subtle textures of urban decay, adding depth and character to the piece." \
  "Mistral Think" "Urban Nature"

queue_job 28 \
  "A multilayer stencil graffiti on a brick wall, featuring a faceless figure holding a sign that reads \"Equality\" in bold, stenciled letters. The figure is rendered in 10 colors (black, white, red, blue, and various grays), with the sign in a vibrant red that stands out against the muted tones of the figure and background. The brick texture adds a raw, authentic feel to the artwork." \
  "Mistral Think" "Silent Protest"

queue_job 29 \
  "A multilayer stencil graffiti on a seaside wall, depicting a giant wave composed of plastic bottles and waste, with a small boat navigating through it. The wave uses a palette of 16 colors (blues, greens, whites, and grays), while the boat is a simple black silhouette. The background includes subtle textures of salt stains and faded graffiti tags, enhancing the environmental message." \
  "Mistral Think" "Ocean of Change"

queue_job 30 \
  "A multilayer stencil graffiti on a metal shutter, showcasing a bird in mid-flight breaking free from a cage. The bird is rendered in 8 colors (shades of blue, black, and white), while the cage is a stark black, creating a powerful contrast. The metal texture of the shutter adds an industrial feel, emphasizing the theme of liberation and resilience." \
  "Mistral Think" "Freedom in Flight"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "Multilayer stencil graffiti artwork on a weathered, textured brick wall. A rusty shopping cart transformed into a mechanical bull, ridden by a faceless business suit mannequin. Strict 3-color palette: stark black, vibrant crimson red, and faded off-white. Misregistered stencil layers showing authentic spray paint bleed, rough cut edges, and overlapping shadows. High contrast, bold graphic shapes, raw urban street art aesthetic, minimalist composition. Powerful social commentary on modern consumerism and corporate greed, striking visual impact, gritty concrete background, authentic spray paint drips, edgy underground art style, highly detailed stencil cuts, raw artistic expression, bold visual statement, striking contemporary urban masterpiece." \
  "Qwen 3.7 Plus Tinking" "Shopping Cart Rebellion"

queue_job 32 \
  "Complex 5-layer stencil graffiti mural on a cracked concrete surface. A majestic red fox sitting calmly amidst towering, brutalist city skyscrapers. Restricted color palette: deep charcoal, muted olive green, burnt orange, pale yellow, and pure white. Each stencil layer precisely aligned with slight intentional misregistration for a hand-crafted screen print feel. Intricate fur details achieved through negative space cutouts. Vibrant yet moody atmospheric lighting, urban wildlife theme, striking juxtaposition of nature and architecture. Gritty wall texture, faded edges, authentic aerosol spray gradients, masterpiece of contemporary street art, highly detailed, eye-catching visual narrative, raw artistic expression, bold visual statement." \
  "Qwen 3.7 Plus Tinking" "Concrete Jungle Fox"

queue_job 33 \
  "4-color multilayer stencil street art on a peeling plaster wall. A solitary figure hunched over a glowing smartphone, their face illuminated while the rest of the world fades into abstract digital noise. Limited palette: electric blue, neon magenta, pitch black, and stark white. Bold, blocky stencil shapes with sharp, clean cuts and deliberate spray paint overspray. The background features fragmented, glitch-like geometric patterns representing digital isolation. High contrast, moody cyberpunk undertones, poignant social critique of technology addiction. Rough wall texture, authentic aerosol halftone dots, striking visual rhythm, contemporary urban art masterpiece, highly detailed stencil layers, raw artistic expression." \
  "Qwen 3.7 Plus Tinking" "Screen Glow Isolation"

queue_job 34 \
  "Intricate 8-color multilayer stencil graffiti on a large, flat concrete wall. A massive, ancient tree whose roots morph into human lungs, with chainsaws cutting into the bark. Rich, earthy color palette: forest green, bark brown, rust red, sky blue, smog gray, shadow black, highlight white, and warning yellow. Complex overlapping stencil layers creating deep shadows and vibrant highlights. Detailed leaf textures and mechanical saw teeth. Poignant environmental protest art, striking visual metaphor for deforestation. Authentic spray paint texture, slight color bleeding between layers, gritty urban canvas, highly detailed screen print aesthetic, powerful and eye-catching contemporary street mural, raw artistic expression." \
  "Qwen 3.7 Plus Tinking" "Lungs of the Earth"

queue_job 35 \
  "6-layer stencil graffiti piece on a corrugated metal surface. A vintage cassette tape unraveling into a swirling, abstract tornado of musical notes and soundwaves. Retro-inspired color palette: synthwave purple, cyan, hot pink, mustard yellow, deep black, and off-white. Bold, graphic stencil design with sharp geometric edges and smooth aerosol gradients. The unraveling tape creates a dynamic, swirling composition that fills the visual space. Nostalgic tribute to analog music, vibrant and eye-catching street art. Corrugated metal texture, authentic spray paint drips, slight misregistration of the color layers, high contrast, raw urban aesthetic, highly detailed stencil cuts, raw artistic expression." \
  "Qwen 3.7 Plus Tinking" "Analog Resonance"

# --- GLM 5V Turbo ---
queue_job 36 \
  "A powerful multilayer stencil graffiti artwork depicting a young girl in a red hooded cloak holding a bouquet of wildflowers that transform into butterflies mid-flight, painted on a weathered concrete wall. Limited color palette of exactly six colors: crimson red, charcoal black, warm cream, sage green, soft amber, and steel blue. Five distinct stencil layers with clean crisp edges showing spray paint overspray texture and slight paint bleeds at layer boundaries. The background features subtle cracked concrete texture with faint underlying graffiti tags. Dramatic side lighting creates depth between stencil layers. Street art aesthetic reminiscent of Banksy's minimalist approach but with richer color complexity. High contrast, gallery-quality stencil work with visible paint droplets and authentic urban decay surrounding the central figure." \
  "GLM 5V Turbo" "Urban Resistance"

queue_job 37 \
  "Multilayer stencil graffiti masterpiece transforming an urban brick wall into a vibrant nocturnal jungle scene where exotic wildlife emerges from architectural elements. Precise eight-color palette: electric cyan, hot magenta, deep violet, lime green, midnight black, pale gold, coral orange, and cloud white. Seven intricate stencil layers depicting a leopard with glowing eyes perched on a windowsill, tropical leaves intertwining with fire escape ladders, and luminescent moths fluttering around street lamps. Each layer demonstrates professional stencil technique with sharp edges, controlled overspray, and perfect registration between color planes. The artwork seamlessly blends natural forms with industrial urban environment. Bioluminescent quality achieved through strategic color layering. Contemporary street art style combining nature themes with metropolitan grit, museum-quality execution." \
  "GLM 5V Turbo" "Neon Jungle"

queue_job 38 \
  "Emotive multilayer stencil graffiti portraying a row of five faceless business suits with television sets for heads, each screen displaying different emoticons while their tie-wearing necks morph into tree roots cracking through the pavement below. Restrained four-color scheme inspired by classic protest poster aesthetics: blood red, newsprint black, warning yellow, and raw umber. Six stencil layers with deliberately rough hand-cut edges and organic overspray patterns suggesting urgency and raw emotion. Background shows peeling plaster and exposed brick with subtle political slogans barely visible beneath. The composition balances satirical commentary with sophisticated artistic technique. Each figure slightly different height creating visual rhythm. Powerful social commentary executed with masterful stencil craftsmanship, gallery-ready urban intervention art with authentic aged wall patina." \
  "GLM 5V Turbo" "Silent Protest"

queue_job 39 \
  "Stunning maritime-themed multilayer stencil mural covering a large harbor wall, featuring a giant humpback whale breaching through stylized waves that transition into mountain peaks above the waterline. Sophisticated twelve-color gradient palette spanning ocean depths: Prussian blue, turquoise aqua, seafoam mint, pearl white, storm grey, sunset coral, golden sand, kelp forest green, deep indigo, foam white, bronze copper, and anchor black. Nine meticulously registered stencil layers creating smooth color transitions and dimensional depth. The whale's body incorporates subtle geometric patterns suggesting both biological scales and nautical charts. Seagulls rendered in minimal negative space. Waves feature dynamic motion lines achieved through layered stencil offsets. Professional large-scale street art technique with perfect paint density control, celebrating ocean conservation through breathtaking public art." \
  "GLM 5V Turbo" "Ocean's Lament"

queue_job 40 \
  "Surrealist multilayer stencil graffiti presenting an astronaut floating weightlessly whose helmet visor reflects a galaxy of stars while their tether rope unravels into musical notes that become birds flying toward a crescent moon. Dreamlike ten-color cosmic palette: nebula purple, starlight silver, astronaut orange, void black, aurora teal, comet gold, planet rust, space dust pink, eclipse blue, and astral white. Eight complex stencil layers with ethereal soft-edge blending techniques contrasting against hard geometric helmet details. The composition balances scientific realism with poetic imagination. Background features subtle celestial coordinate patterns and constellation lines. Each stencil level adds narrative depth from the realistic spacesuit texture to abstract cosmic phenomena. Visionary street art transcending traditional graffiti into fine art territory, executed with technical precision and boundless creativity." \
  "GLM 5V Turbo" "Cosmic Dreamer"

# --- Kimi K2.6 Fast ---
queue_job 41 \
  "A towering lone tree on a cracked concrete hill, roots breaking through asphalt. Four stencil layers: deep charcoal ground, slate blue shadows, oxidized copper leaves, and a single blood-red sun behind dying branches. Spray paint drips at edges, overspray halos around cutout shapes. Wheatpaste texture on industrial wall, weathered peeling corners. Stark minimal palette, high contrast silhouette, urban decay meets fragile nature. Banksy-style social commentary on environmental collapse, raw street art aesthetic with deliberate imperfection." \
  "Kimi K2.6 Fast" "The Last Tree"

queue_job 42 \
  "Giant hands emerging from factory smokestacks, cupped upward catching falling coins that transform into ash. Six stencil layers: pitch black background, smog gray, rust orange machinery, faded denim blue hands, gold coins, white ash particles. Bold graphic shapes with rough cut edges, aerosol splatter texture, stencil alignment slightly off-register. Painted on corrugated metal warehouse door. Commentary on labor exploitation and industrial waste, striking visual metaphor, limited palette maximum impact." \
  "Kimi K2.6 Fast" "The Unseen Worker"

queue_job 43 \
  "Woman in business silhouette shattering upward through a ceiling of glass shards that become birds. Five stencil layers: midnight blue void, concrete gray floor, warm amber figure, ice blue glass fragments, bone white birds in flight. Clean vector-like stencil cuts with deliberate overspray fade, wall texture showing through thin paint layers. Urban alleyway setting with exposed brick. Empowerment and barrier-breaking symbolism, minimalist yet emotionally charged composition, contemporary street art precision." \
  "Kimi K2.6 Fast" "The Glass Ceiling"

queue_job 44 \
  "Melting ice cave revealing a sleeping polar bear skeleton inside translucent blue walls. Seven stencil layers: deep navy background, arctic teal shadows, glacier white, permafrost gray, pale blue ice transparency, ivory bones, warning red meltwater drips. Layered stencil depth creating dimensional ice effect, spray paint gradient on cave interior, rough exterior wall integration. Climate crisis memorial painted on concrete flood barrier. Haunting beauty in environmental warning, masterful negative space usage, poignant street art elegy." \
  "Kimi K2.6 Fast" "The Last Glacier"

queue_job 45 \
  "Homeless figure sitting on a bench made of glowing phone screens, face illuminated by blue light while body fades to shadow. Six stencil layers: absolute black background, electric blue screen glow, warm amber face highlight, cool gray concrete, muted green bench, ghost white fading body. High contrast screen-light effect through layered translucent stencils, pixelated edge details, spray dot matrix texture. Painted on abandoned billboard structure. Commentary on technological isolation and digital inequality, provocative juxtaposition, iconic street art simplicity with layered meaning." \
  "Kimi K2.6 Fast" "The Digital Prophet"

# --- Deepseek Instant ---
queue_job 46 \
  "Multilayer stencil graffiti mural on cracked concrete. Limited color palette: deep navy blue, faded brick red, bone white, and charcoal black, totaling six stencil layers. Dominant foreground features a riot police silhouette holding a blooming rose, stencil edges sharp and overlaid with coarse halftone screen texture. Midground shows overturned shopping carts and scattered petals, rendered in two gray tone passes with visible spray paint splatters. Background contains fragmented skyscrapers and a hazy smoke plume, using a single negative-space stencil cut. Overlapping translucent layers create depth, with intentional misregistration offsets and gritty paint drips cascading downward. High-contrast chiaroscuro, distressed urban decay, socially charged street art composition." \
  "Deepseek Instant" "Concrete Rose"

queue_job 47 \
  "Multilayer stencil graffiti on corrugated metal panels. Limited palette of mustard yellow, muted teal, off-white, and carbon black, using eight distinct stencil levels. Main subject is a group of faceless school children standing in a row, hands bound behind their backs, rendered with crisp stencil cuts and subtle halftone dot shading. Midground features an abandoned chalkboard filled with erased equations and a tattered national flag, painted with two overlapping teal and yellow layers. Background shows a chain-link fence and a setting sun, executed as a single bold negative stencil. Heavy textured overspray, paint runs, and deliberate layer misalignment. Composition is frontal, confrontational, evoking protest and lost innocence, with a gritty documentary street art feel." \
  "Deepseek Instant" "Silent Chorus"

queue_job 48 \
  "Multilayer stencil graffiti on a peeling shipping container. Limited color scheme: ocean cyan, sand beige, rust brown, and chalk white, with ten distinct stencil passes. Foreground features a giant octopus tentacle emerging from a flooded subway grate, wrapping around a traffic signal, rendered with intricate stencil cutouts and fine spray mist gradients. Midground depicts submerged park benches and a drifting bicycle, using three beige and brown layers with heavy paint splatter effects. Background shows a submerged city skyline with a cracked moon, applied as a single white negative stencil overlay. Coarse halftone noise, overspray clouds, and deliberate stencil registration shifts create motion. Surreal environmental commentary, cinematic low-angle perspective, gritty nautical dystopia." \
  "Deepseek Instant" "Tidal Shift"

queue_job 49 \
  "Multilayer stencil graffiti on a burnt storefront shutter. Limited palette: vermilion red, ash gray, parchment white, and pitch black, using twelve stencil layers for rich texture. Central image is a ballerina dancing amidst falling embers, her tutu made of fragmented newsprint text, rendered with razor-sharp stencil edges and translucent mist overlays. Midground shows collapsed market stalls and a lone violin, painted in two ash-gray passes with coarse drip effects and stippled halftones. Background features a towering church spire engulfed in smoke, applied as a negative-space stencil with overspray halo. Intentional misregistration, paint cracks, and layered transparency. Theme of beauty amidst destruction, protest against cultural erasure, dramatic side lighting, raw urban canvas." \
  "Deepseek Instant" "Ashes and Petals"

queue_job 50 \
  "Multilayer stencil graffiti on a corrugated steel wall. Limited color palette: emerald green, burnt umber, ivory white, and slate blue, with sixteen stencil levels for maximum depth. Foreground shows a giant sleeping bear curled around a shattered clocktower, stencil details with fine hatching and dotted halftone shadows. Midground displays abandoned carousel horses overgrown with ivy, painted in three umber and green passes, featuring heavy splatter and misty overspray. Background includes a distant ferris wheel silhouette and cloudy sky, achieved via a double-negative stencil cut. Overlapping translucent layers, deliberate offset printing errors, and coarse grain texture. Dreamy dystopian playground, commentary on industrial decline, moody twilight atmosphere, high-art graffiti aesthetic." \
  "Deepseek Instant" "Rusted Lullaby"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Multilayer stencil graffiti art of an elderly beekeeper in a hazmat suit gently cradling a single glowing honeybee, limited palette of black white mustard yellow ochre and muted teal, distinct separated color layers showing shadow midtone and highlight stencils, spray paint drips on cracked concrete wall texture, bold graphic contrast, urban protest street art aesthetic inspired by Banksy minimalism, eight color maximum, sharp geometric edges, layered depth effect, raw emotional storytelling, gritty urban environment background faded brick, square composition, high detail stencil cutout style." \
  "ERNIE 5.1" "The Last Beekeeper"

queue_job 52 \
  "Multilayer stencil graffiti depicting a young girl standing knee deep in a sea of plastic bottles and bags, limited palette of navy blue white coral orange slate grey and pale pink, three to four distinct stencil layers creating depth and shadow separation, spray paint texture on weathered concrete wall, Banksy inspired social commentary minimalism, geometric simplified forms, bold graphic silhouettes, environmental protest art, sharp stencil edges with intentional overspray bleed, muted earth tones grounding the composition, layered color registration effect, urban decay background, square format." \
  "ERNIE 5.1" "Ocean of Plastic"

queue_job 53 \
  "Multilayer stencil graffiti of a child sitting on a rooftop edge reaching toward a paper airplane made of stars, limited palette of black white lavender burnt sienna forest green and warm cream, five layered stencil cuts showing progressive depth from dark shadow to bright highlight, spray paint on textured plaster wall, Banksy level minimalist storytelling, hopeful yet melancholic mood, clean geometric shapes with raw spray edges, social commentary on childhood innocence and urban poverty, color separation visible between layers, drips and imperfections, square composition." \
  "ERNIE 5.1" "Rooftop Dreamer"

queue_job 54 \
  "Multilayer stencil graffiti of a figure throwing a bouquet that explodes into doves and wildflowers, limited palette of black white crimson red olive green gold and soft grey, six distinct stencil layers creating dimensional shadow and form, bold graphic street art on aged brick wall, protest peace imagery with Banksy inspired simplicity, sharp angular cutout shapes contrasted with organic floral elements, visible color registration shifts between layers, spray paint misting and drips, urban rebellion aesthetic, muted background tones letting foreground pop, powerful symbolic composition, square format." \
  "ERNIE 5.1" "Flower Bomb Peace"

queue_job 55 \
  "Multilayer stencil graffiti of a surreal cityscape where buildings melt like Dali clocks into a river of clock gears, limited palette of black white steel blue rust orange pale yellow and charcoal, seven layered stencil levels creating complex depth and dimensional parallax, spray paint on massive concrete wall, surrealist protest art commenting on time and capitalism, Banksy meets street surrealism minimal colors, bold silhouette layers with precise cutout geometry, color bleed between stencil passes, industrial urban texture, haunting dreamlike atmosphere, square composition." \
  "ERNIE 5.1" "Melting Clockwork City"

# --- LongCat Deep search ---
queue_job 56 \
  "A powerful multilayer stencil graffiti artwork depicting a human figure wrapped in heavy chains made of corporate logos and currency symbols, breaking free in a burst of color. The composition uses a strict limited palette of only five colors: matte black for outlines and shadows, stark white for highlights, blood red for the chains, faded gold for the background wash, and concrete grey for texture. The stencil technique shows visible layer separations with slight misregistration effects typical of street art. Spray paint drips and overspray textures add authenticity. The figure's pose conveys struggle and liberation, set against a weathered urban wall background with subtle political poster remnants. Banksy-inspired social commentary with high contrast graphic impact." \
  "LongCat Deep search" "Corporate Chains"

queue_job 57 \
  "A striking multilayer stencil graffiti piece showing a wolf howling at a full moon, but the wolf's body is composed of crumbling city skyscrapers and urban architecture. The artwork employs a controlled palette of six colors: deep midnight blue for the night sky, silver white for the moon and building highlights, rust orange for atmospheric glow, charcoal black for structural outlines, sage green for subtle moss growth on buildings, and pale yellow for distant window lights. The stencil layers create depth with foreground wolf silhouette, midground city elements, and background sky. Visible spray paint texture and stencil cut-out edges give authentic street art feel. The composition balances negative space with detailed architectural elements within the animal form, creating a powerful nature versus urbanization statement." \
  "LongCat Deep search" "Urban Wilderness"

queue_job 58 \
  "An eye-catching multilayer stencil graffiti artwork exploring themes of digital privacy and surveillance. The central image shows a giant human eye with a camera lens iris, watching over a crowd of faceless figures. The limited color palette consists of exactly seven colors: glossy black for all outlines and deep shadows, bright white for highlights and eye reflection, electric blue for digital elements, warning yellow for caution symbols, blood red for accent details, metallic silver for technological components, and pale grey for the crowd figures. The stencil technique features sharp geometric cuts with visible layer separations. Spray paint overspray creates atmospheric haze. The composition uses strong diagonal lines and dramatic lighting to create tension. Street art aesthetic with Banksy-level social commentary on modern surveillance culture." \
  "LongCat Deep search" "Digital Surveillance"

queue_job 59 \
  "A thought-provoking multilayer stencil graffiti artwork depicting a polar bear sitting on a tiny melting iceberg, with the bear's body showing cracks and fragments breaking away. The artwork uses a carefully restricted palette of five colors: arctic white for the bear and ice, ocean blue for water elements, sunset orange for sky gradients, charcoal black for outlines and shadows, and coral pink for atmospheric warmth. The stencil layers create distinct depth planes: foreground ice, midground bear, background sky. Visible stencil misregistration and spray paint drips add street art authenticity. The composition emphasizes isolation and environmental crisis through stark contrast and minimal detail. The bear's expression conveys vulnerability, while the melting form symbolizes climate change impact. Urban wall texture shows through in background areas." \
  "LongCat Deep search" "Climate Melting"

queue_job 60 \
  "A bold multilayer stencil graffiti piece featuring a dove in flight holding an olive branch in one claw and a shopping bag in the other, symbolizing the conflict between peace and consumerism. The artwork employs a vibrant but limited palette of six colors: pure white for the dove's body, olive green for the branch leaves, bright red for the shopping bag, golden yellow for background halftone dots, deep black for all outlines and text elements, and sky blue for atmospheric background wash. The stencil technique shows crisp edges with intentional slight color misregistration. Spray paint texture and overspray create authentic street art feel. The composition uses dynamic diagonal flight path with the dove moving upward. Banksy-inspired social commentary with high contrast graphic style and subtle texture of weathered concrete wall." \
  "LongCat Deep search" "Consumerist Dove"

echo "✅ All 60 jobs queued in scheduler"

