#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Photo through the glass — portraits and scenes viewed through
#        rain-streaked, steamed, tinted, or reflective glass (windows,
#        mirrors, glass walls)
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+43+-+photo+through+the+glass
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------
# --- Claude Sonnet 5 high ---
queue_job  1 \
  "Photo taken through a rain-streaked cafe window at dusk, framing a man in his forties seated alone at a small round table just behind the glass, wearing a charcoal wool coat, both hands wrapped around a white porcelain cup, gaze lowered toward the table rather than the street. Rivulets of rain run diagonally down the outer pane, bending the warm amber glow spilling from pendant lamps inside the cafe into soft smeared streaks. On the glass surface itself, faint semi-transparent reflections of the wet street are visible: blurred red taillights, a distant traffic signal glowing green, and the ghostly silhouette of a pedestrian passing under an umbrella, layered directly over the man's seated form. The composition is shot from outside at eye level, medium shot, with the window frame's dark metal mullion cutting vertically through the left third of the frame. Shallow depth of field keeps the man in soft focus while the raindrops closest to the lens go fully abstract as bokeh circles. Muted, melancholic color palette of desaturated blues outside against warm amber inside, fine film grain, 35mm photographic realism, quiet contemplative mood." \
  "Claude Sonnet 5 high" "Cafe Window at Dusk"

queue_job  2 \
  "Photo through a steam-fogged glass shower panel in a softly lit bathroom, a woman in her late twenties stands just beyond the glass with her back partly turned, damp dark hair pushed off her shoulder, one hand raised to wipe a clear diagonal streak across the condensation at head height, revealing only a narrow sliver of her calm profile and open eye through the wiped section while the rest of her form remains a warm, diffused silhouette behind the fog. Morning light filters through a frosted window off-frame right, casting a soft golden wash across the pale tile and the fogged glass, which holds tiny individual water droplets catching the light like scattered pinpoints. The wiped streak acts as the sole point of sharp focus, framed by the surrounding blur of condensation, creating a natural vignette within the image itself. Composition is a tight vertical crop at chest height, glass filling the entire frame edge to edge. Palette is soft cream and blush tones with gentle golden highlights, photographic realism with a slightly soft, dreamy quality reminiscent of medium-format film, mood quiet and introspective, ordinary morning ritual rather than posed." \
  "Claude Sonnet 5 high" "Steamed Bathroom Glass"

queue_job  3 \
  "Photo through the scratched, slightly grimy window of a city night bus, a young woman of South Asian descent sits in the window seat, forehead resting lightly against the cool glass, dark hair falling loose across her shoulder, eyes half-closed in tired thought, wearing a denim jacket over a plain top. The glass carries a faint ghost-reflection of the bus's fluorescent interior strip lighting and the blurred outline of a standing passenger holding an overhead rail, layered translucently across the dark window alongside streaks of passing neon signage bleeding into long horizontal light trails from the motion outside. Outside the glass, out-of-focus city lights in magenta and cyan smear into soft bokeh streaks suggesting speed and late hour. Composition is a close three-quarter profile shot from just outside the bus, window frame's black rubber edge visible along the right side of the frame. Palette contrasts cool cyan-blue night tones outside with warm sodium-yellow interior light reflected on the glass. Photographic realism, slight grain, mood weary and pensive, the quiet solitude of a long commute home." \
  "Claude Sonnet 5 high" "Night Bus Reflection"

queue_job  4 \
  "Photo through the clean plate-glass window of a small corner shop at night, toned faintly amber from the glass's tint, a couple stands just outside the frame's edge reflected on the surface: a man and woman in their thirties laughing together, his arm around her shoulder, both slightly blurred as translucent reflections overlaid across the display behind the glass. Behind the glass, the shop's interior shows neatly arranged shelves of ceramics and dried flowers under warm string lights, softly out of focus to keep attention on the reflected figures. In the upper right corner of the window, a small hanging neon sign glows in cursive script reading \"OPEN\", its pink-orange light reflecting faintly downward across the glass surface. Composition is a straight-on medium shot, glass filling most of the frame, shop door frame visible along the left edge. Palette is warm amber and soft pink neon against the cooler blue of the night street glimpsed at the very edges. Photographic realism with gentle glass reflection layering, mood warm and content, a small unguarded moment of shared happiness caught in passing reflection." \
  "Claude Sonnet 5 high" "Neon Shop Window"

queue_job  5 \
  "Photo through a tall interior glass wall of a modern office at dusk, a man in his fifties stands alone just beyond the glass in a conference room, sleeves rolled up, one hand resting flat against the pane, head slightly bowed, city skyline visible through the window behind him growing dim with early evening light. The glass wall reflects the softly blurred silhouette of another figure walking past in the foreground corridor, translucent and overlapping the standing man's chest, suggesting motion and distance between them. Near the bottom corner of the glass, faint dry-erase marker text remains from an earlier meeting, only partially wiped, the visible fragment reading \"next steps\", its pale ghosted letters catching the cool overhead light. Composition is a wide medium shot at eye level, glass surface filling the frame with the vertical steel mullion positioned along the right third. Palette is cool blue-gray with a single warm desk-lamp glow behind the man, photographic realism, sharp architectural lines softened by faint reflections, mood isolated and contemplative, weight of an unfinished workday hanging in the stillness." \
  "Claude Sonnet 5 high" "Office Glass Wall"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A close-up photograph taken from the exterior through a rain-streaked cafe window, revealing a thoughtful 30-year-old East Asian woman sitting inside. She wears a chunky knit mustard-yellow sweater and holds a steaming ceramic mug with both hands, gazing softly toward the glass. Droplets and delicate rivulets of water stream down the glass surface, partially blurring the cozy interior light. Reflected on the outer surface of the glass, shimmering neon signs from the bustling city street and blurred headlights of passing cars create a vibrant bokeh of red and amber hues, blending the warmth of the indoor sanctuary with the moodiness of the rainy evening outside." \
  "Gemini 3.5 Flash" "Rainy Reflections at the Cafe"

queue_job  7 \
  "A side-angle photograph captured through the rain-slicked side window of a vintage taxi cab cruising through a city at night. Inside, a handsome 35-year-old Hispanic man with a neatly trimmed beard sits in the passenger seat, leaning back against the dark leather upholstery, looking out into the night. Soft blue and pink neon light from storefronts casts cool reflections across the moist exterior glass, intersecting with faint condensation patches on the inside. The interior lighting is soft and moody, highlighting the sharp contour of his face while the motion blur of the streetlights outside creates a rhythmic, cinematic atmosphere." \
  "Gemini 3.5 Flash" "The Midnight Taxi Ride"

queue_job  8 \
  "A high-contrast street photograph shot through the glass doors of an underground subway train pulled up at a brightly lit station platform. Visible inside the illuminated carriage is a stylish 28-year-old Black woman wearing a trench coat and headphones, standing near the pole with a relaxed expression. The glass of the train door features subtle fingerprints and faint scratches, reflecting the busy platform behind the photographer, where commuters walk past under warm industrial overhead lamps. The sharp partition of the glass creates a distinct layer between the bright public platform and the calmer cabin interior." \
  "Gemini 3.5 Flash" "Subway Car Dusk"

queue_job  9 \
  "A romantic lifestyle photograph taken through the framed display window of an artisan flower shop on a sunny afternoon. A charming 40-year-old Caucasian man with rolled-up shirt sleeves is arranging a colorful bouquet of fresh peonies and eucalyptus stems inside the store. Sunlight hits the clean storefront glass, creating sharp, brilliant reflections of leafy green oak trees and classic European townhouses across the street. The dual-layer effect overlays the vivid textures of the colorful floral arrangements inside with the sunny, tranquil outdoor street scene, filling the frame with warmth and natural beauty." \
  "Gemini 3.5 Flash" "Behind the Florist Glass"

queue_job 10 \
  "A dramatic night-time portrait taken from the dark sidewalk through the wide panoramic window of an old-school diner. Inside, a 32-year-old South Asian woman sits alone at a chrome-trimmed vinyl booth under bright, warm neon lighting, holding a glass of water. Condensation hangs heavy along the bottom edges of the window pane, tapering off into clear glass near her eye level. The high contrast between the dark exterior shadows and the glowing, vivid interior highlights her serene demeanor, while soft reflections of streetlamps shimmer faintly against the wet, steamy pane." \
  "Gemini 3.5 Flash" "Late Night Diner Solitude"

# --- ChatGPT ---
queue_job 11 \
  "A cinematic street photograph captured from outside a cozy corner cafe during a gentle evening rain, the camera focused through a large rain-speckled window where a woman in her thirties sits alone with a ceramic cup of coffee and an open notebook, her relaxed posture suggesting quiet reflection rather than sadness. The glass is covered with crisp droplets that distort tiny parts of the scene while preserving facial detail. Reflections of glowing street lamps, passing umbrellas, vintage storefront signs, and soft traffic lights drift across the glass without obscuring the subject, creating natural visual layers. Warm amber interior lighting contrasts with cool blue twilight outside, balancing comfort against the damp city atmosphere. Subtle depth of field, authentic lens behavior, realistic textures, documentary photography style, highly detailed skin, natural clothing, believable imperfections in the glass, emotionally rich yet understated, premium editorial street photography with elegant composition." \
  "ChatGPT" "Rain on the Corner Cafe"

queue_job 12 \
  "A photorealistic portrait viewed from outside a modern apartment through a tall floor-to-ceiling window covered with faint morning condensation and delicate streaks left by evaporating moisture. Inside, a man in his forties waters several lush houseplants while soft sunlight fills the room, creating an atmosphere of peace and renewal. The glass gently reflects neighboring buildings, pale blue sky, tree branches, and drifting clouds, blending the outdoor world with the quiet domestic interior without overpowering the subject. Minimal contemporary furniture, clean architectural lines, warm wooden textures, and scattered books reinforce an authentic lived-in environment. The composition emphasizes layered transparency, with reflections naturally framing the figure. Crisp focus on the subject through selective depth of field, subtle highlights on the glass surface, realistic global illumination, premium architectural lifestyle photography, calm optimistic mood, exceptionally natural color grading." \
  "ChatGPT" "Morning Apartment Window"

queue_job 13 \
  "A realistic urban night photograph taken through the rain-streaked side window of a moving taxi, where a woman in her fifties sits comfortably in the back seat looking toward the vibrant city outside with a gentle thoughtful smile. Colorful reflections from neon signs, illuminated billboards, traffic signals, and storefront lights spread across the wet glass, merging with her face to create complex visual layers while preserving realistic proportions. Tiny droplets, faint streaks, and subtle motion blur communicate movement through the city without reducing image clarity. Inside the taxi, dim ambient lighting softly illuminates natural skin tones and textured clothing, while outside the city pulses with saturated reds, blues, and golds reflected across the window. Editorial documentary photography, cinematic realism, authentic urban atmosphere, premium lens rendering, emotionally engaging composition centered on layered reflections and genuine human presence." \
  "ChatGPT" "Late-Night Taxi Reflections"

queue_job 14 \
  "A refined environmental portrait photographed through the expansive glass wall of a botanical greenhouse, where a man in his thirties carefully examines an exotic flowering plant among dense tropical foliage. The spotless yet reflective glass captures overlapping reflections of dramatic clouds, distant mountains, and elegant surrounding trees, visually blending nature outside with the lush interior landscape. Bright afternoon sunlight creates gentle highlights along the glass surface while soft shadows reveal depth among leaves and architectural steel frames. The subject remains clearly visible behind the reflections, establishing a harmonious relationship between person, plants, and the surrounding environment. Rich botanical textures, realistic humidity, subtle internal haze, premium nature photography aesthetic, balanced composition, natural colors, exceptional realism, highly detailed foliage, authentic reflections, peaceful contemplative atmosphere with museum-quality visual storytelling." \
  "ChatGPT" "The Greenhouse Between Worlds"

queue_job 15 \
  "A photorealistic street scene viewed from outside a city bus through its large slightly tinted side window moments after sunset. Inside, a diverse group of adult passengers quietly occupy separate seats while a woman near the window gazes outward, her expression relaxed and hopeful after a long day. The glass combines reflections of glowing shop windows, cyclists, evening pedestrians, illuminated advertisements, and rows of trees lining the boulevard, naturally layering the exterior city over the interior without hiding the passengers. Faint fingerprints, subtle dust, and realistic surface imperfections increase authenticity while warm cabin lighting softly models faces against the cooler blue evening outside. Balanced framing emphasizes the emotional connection between interior and exterior spaces, with crisp documentary realism, premium street photography style, realistic lens optics, outstanding dynamic range, and sophisticated visual storytelling driven by reflections and transparency." \
  "ChatGPT" "After the Bus Arrives"

# --- Grok fast ---
queue_job 16 \
  "A melancholic scene viewed through a rain-streaked cafe window at dusk, soft warm interior lights glowing against cool blue exterior tones, a middle-aged East Asian woman in her thirties sits alone at a wooden table near the glass wearing a cream sweater, chin resting on her hand as she gazes outward with quiet introspection, steam faintly blurring the lower pane, city street reflections overlaying her face with blurred neon signs and passing car lights creating layered melancholy atmosphere, gentle bokeh from raindrops on glass, cinematic framing with the window frame edges visible, soft diffused lighting, photorealistic, moody color grading, high detail, atmospheric depth." \
  "Grok fast" "A Lonely Rainy Cafe Window"

queue_job 17 \
  "Dynamic nighttime view through the large window of a city bus, warm yellow interior lighting contrasting deep indigo exterior, a confident Black man in his forties stands holding the overhead rail, wearing a dark coat and scarf, looking thoughtfully into the distance while faint reflections of bustling street life, traffic lights, and illuminated buildings merge across the glass surface creating a sense of motion and solitude, subtle condensation at the edges, other passengers softly blurred in background, grounded perspective as if standing on the sidewalk looking in, photorealistic with film grain, dramatic side lighting, urban nocturnal mood, intricate details on glass textures and reflections." \
  "Grok fast" "Urban Bus Reflection at Night"

queue_job 18 \
  "Intimate evening portrait seen through a large apartment window with sheer curtains partially drawn, golden hour remnants mixing with warm lamp light inside, a smiling Hispanic woman in her late twenties leans against the windowsill holding a steaming mug, wearing a soft knit cardigan, gentle expression of contentment as she watches the quiet street below, subtle reflections of nearby trees and neighboring building lights dance on the clear glass, plants visible on the sill inside, balanced composition centering her figure within the window frame, soft volumetric lighting, photorealistic, warm inviting tones, serene domestic atmosphere with rich textures." \
  "Grok fast" "Cozy Apartment Evening Glow"

queue_job 19 \
  "Atmospheric morning scene through the fogged glass of a small boutique shop window, soft natural daylight filtering through, a stylish Middle Eastern man in his thirties arranges vintage clothing on a mannequin inside, focused expression with rolled sleeves on his button-down shirt, condensation patterns on the glass partially obscuring and framing the view, faint reflection of the photographer's silhouette and street cafe tables visible on the right side, warm interior spotlights highlighting fabrics, grounded eye-level framing, photorealistic with realistic water droplets and steam effects, inviting commercial mood, detailed material textures." \
  "Grok fast" "Steamy Shop Window Display"

queue_job 20 \
  "Emotional close view through the rain-dotted side window of a vintage yellow taxi at twilight, soft dashboard glow illuminating the interior, a young Caucasian couple in their thirties sits closely in the back seat, the woman resting her head on the man's shoulder with peaceful smiles, city lights and wet streets reflecting beautifully across the curved glass creating romantic layered patterns, subtle fog on the lower window, taxi interior details like worn leather seats visible, cinematic composition focusing on their connection framed by the car window, photorealistic, moody yet tender lighting, evocative storytelling atmosphere." \
  "Grok fast" "Vintage Taxi Intimate Moment"

# --- Copilot Smart ---
queue_job 21 \
  "A man in a dark coat sits inside a softly lit cafe, framed by a large glass window streaked with rain. His face is turned toward the street, illuminated by warm amber light from hanging lamps above. Outside, blurred neon signs and passing car headlights reflect across the wet glass, layering his contemplative expression with streaks of color. The composition balances interior intimacy with exterior chaos, creating a mood of quiet melancholy." \
  "Copilot Smart" "City Reflections at Dusk"

queue_job 22 \
  "A woman leans against the window of a high-rise apartment, her silhouette softened by the glow of city lights behind her. The glass is slightly tinted, catching faint reflections of skyscrapers and distant billboards. Inside, warm tones of a lamp and scattered books create a cozy atmosphere, while the reflections outside amplify the sense of solitude. Her hand rests gently on the glass, as if reaching toward the world beyond." \
  "Copilot Smart" "Apartment Glow Through Glass"

queue_job 23 \
  "A man sits in the backseat of a taxi, his face partially obscured by the glass window. The glass is wet with streaks of rain, catching reflections of streetlights and blurred pedestrians. His expression is thoughtful, framed by the glow of the taxi's interior light. Outside, the city rushes past in distorted reflections, amplifying the sense of motion and fleeting moments." \
  "Copilot Smart" "Taxi Ride Reflections"

queue_job 24 \
  "A woman gazes out of a bus window, her face softly lit by the pale morning sun. The glass is slightly fogged, with faint condensation patterns framing her profile. Reflections of passing trees and buildings blur across the surface, merging with her calm expression. Inside, muted tones of the bus interior contrast with the bright reflections outside, creating a mood of quiet anticipation." \
  "Copilot Smart" "Bus Window Morning Light"

queue_job 25 \
  "Two friends sit at a cafe table near a floor-to-ceiling glass wall, laughing together. The glass reflects the bustling street outside, with bicycles, pedestrians, and shop signs layered over their joyful expressions. Inside, warm tones of coffee cups and pastries add intimacy, while the reflections amplify the vibrancy of city life. The interplay of interior warmth and exterior energy creates a mood of happiness framed through glass." \
  "Copilot Smart" "Glass Wall Cafe Scene"

# --- Mistral Think ---
queue_job 26 \
  "A steamy cafe window on a rainy evening in a European city, countless droplets cascading down the glass like liquid jewels, warm amber light from vintage pendant lamps spilling out onto the wet pavement, creating a cozy glow that contrasts with the cold blue tones of the rain-soaked street, the interior reflecting a lone patron in a wool sweater reading a leather-bound book at a dark wooden table, their face partially illuminated by the soft light, the city's neon signs and streetlights blurred and distorted on the wet surface, creating a dreamy, painterly effect, soft bokeh lights from distant cars and streetlamps in the background, cinematic depth of field with a 50mm lens, moody and atmospheric lighting with subtle vignettes, hyper-detailed textures of aged wood, condensation on glass, and the woven fabric of the patron's sweater, a sense of quiet solitude and warmth amid the storm outside, shot on Kodak Portra 400 film, evoking a timeless, nostalgic mood." \
  "Mistral Think" "Rain-Speckled Cafe Window"

queue_job 27 \
  "A sleek, modern high-end fashion shop window at dusk in a metropolitan downtown, its floor-to-ceiling glass surface immaculately clean and reflecting the vibrant neon signs of the bustling city street, mannequins dressed in elegant black evening wear and shimmering metallic fabrics visible inside, their sharp silhouettes contrasting against the glowing reflections of passing cars and illuminated billboards, the glass acting as both a mirror and a portal, juxtaposing the stillness of the meticulously arranged display with the dynamic energy of the urban night, passersby blurred in motion on the sidewalk, their forms distorted in the reflections, crisp and high-contrast lighting with deep shadows, ultra-realistic textures of glass, fabric, and metal fixtures, cinematic composition with a low angle shot, a mood of sophistication, allure, and modern luxury, evoking the pulse of city life and the allure of high fashion." \
  "Mistral Think" "Neon-Lit Shop Window at Night"

queue_job 28 \
  "A floor-to-ceiling glass wall of a minimalist penthouse apartment high above the city, the setting sun casting a warm golden glow through the transparent surface, a silhouette of a person standing inside with their hands resting on the glass, their form elegantly framed by the fiery hues of orange, pink, and purple in the sky, the city skyline far below reflected faintly on the glass, creating a layered effect of depth and perspective, the reflections subtly distorted by the curvature of the building, soft, diffused lighting with a golden hour palette, warm tones dominating the scene, a serene and contemplative atmosphere, ultra-detailed architecture with clean lines and modern materials, the natural light play creating intricate patterns on the walls and floor, evoking a sense of calm, introspection, and the beauty of solitude in a vast urban landscape." \
  "Mistral Think" "Sunset Through a Glass Wall"

queue_job 29 \
  "A fogged-up bus window on a chilly autumn morning, condensation forming intricate, organic patterns across the glass, a passenger's breath adding to the mist as they sit with their forehead nearly touching the cool surface, the blurred cityscape visible through the semi-transparent layer, streetlights and early risers reflected as soft, ghostly shapes, a newspaper held up by the passenger creating a partial shadow that dances across the glass, the mood quiet and introspective, soft pastel colors of dawn filtering through the fog, cinematic and slightly grainy texture with a vintage film aesthetic, the interior of the bus dimly lit with warm tones that contrast with the cool blues outside, evoking a sense of journey, solitude, and the quiet beauty of everyday moments, hyper-detailed textures of condensation, glass, and the worn fabric of the bus seats." \
  "Mistral Think" "Foggy Bus Window at Dawn"

queue_job 30 \
  "A taxi window at night in a rain-slicked city, the glass acting as a dynamic canvas for the city's vibrant life, neon signs in electric blue, pink, and green, headlights from oncoming traffic, and the glow of streetlamps painting streaks of color across its surface, the dim interior light illuminating the passenger's thoughtful expression, their face partially obscured by the kaleidoscope of reflections, raindrops streaking down the glass adding a dynamic, cinematic quality, each droplet catching and refracting the city lights like tiny prisms, deep contrasts between light and shadow creating a dramatic chiaroscuro effect, the mood one of urban mystery and quiet introspection, ultra-realistic details and textures of wet glass, the leather interior of the taxi, and the passenger's dark coat, evoking the feeling of being both an observer and a participant in the city's endless rhythm." \
  "Mistral Think" "Nighttime Taxi Window Reflections"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "A cinematic photograph taken from outside a rain-streaked cafe window at night. Inside, an elderly man with a weathered face and silver beard sits alone at a small wooden table, holding a steaming ceramic mug with both hands, staring thoughtfully into the distance. The glass is wet with heavy raindrops, creating a blurred, distorted view of the interior. Reflected on the surface of the wet glass are the glowing red and blue neon signs from the street outside, casting a moody, melancholic cyberpunk glow over the man's face. The lighting is low-key, with warm amber light from inside contrasting with the cool neon reflections. Shot on 35mm lens, shallow depth of field focusing on the raindrops and the man's expressive eyes, highly detailed, photorealistic, emotional atmosphere." \
  "Qwen 3.7 Plus Tinking" "Rainy Cafe Window Melancholy"

queue_job 32 \
  "A heartwarming street-level photograph looking through a heavily steamed-up bakery window from the outside. A young woman in her twenties with curly dark hair and a flour-dusted apron is inside, playfully wiping a clear circle in the condensation with her hand to peek out. She has a bright, genuine smile and crinkled eyes, looking directly through the cleared glass at the viewer. The rest of the glass is covered in thick, soft white steam. Behind her, the warm, golden interior of the bakery is softly blurred, showing racks of freshly baked golden croissants and hanging Edison bulbs. The reflection on the outer glass shows a bright, sunny cobblestone street with blooming green potted plants. The lighting is bright, cheerful, and natural, with a cozy and inviting mood, captured in high resolution, sharp focus on her joyful expression and the textured condensation." \
  "Qwen 3.7 Plus Tinking" "Steamy Bakery Window Joy"

queue_job 33 \
  "A striking architectural street portrait captured through the massive, pristine glass facade of a modern corporate skyscraper. In the foreground, a middle-aged woman of East Asian descent with sharp features and a tailored charcoal suit walks briskly, her expression focused and determined. The glass wall acts as a giant mirror, reflecting the towering steel and glass buildings of the bustling city street behind her, but the reflection is slightly overlaid with the faint, ghostly image of a serene, misty pine forest, creating a surreal contrast between urban ambition and inner peace. The glass is perfectly clean, offering a crystal-clear view of her while the double-exposure reflection adds depth. The lighting is crisp, overcast daylight providing soft, even illumination without harsh shadows, highlighting the sleek textures of her suit and the smooth glass surface, shot with a medium format camera for ultra-sharp details." \
  "Qwen 3.7 Plus Tinking" "Skyscraper Glass Wall Reflection"

queue_job 34 \
  "A nostalgic, moody photograph taken from the passenger seat looking through the slightly scratched, dark-tinted rear window of a vintage yellow taxi cab at night. An older man of South Asian descent with a thick mustache and a worn leather jacket sits in the back, his face illuminated by the soft, warm glow of the streetlights passing by. He is looking out the window with a pensive, quiet expression. The tinted glass darkens the exterior, but bright streaks of amber and white city lights blur across the surface, creating a sense of motion and passage of time. Faintly reflected in the dark glass is the silhouette of the driver and the glowing dashboard dials. The composition uses the window frame to create an intimate, voyeuristic framing, shot on 50mm film with rich grain, deep shadows, and a cinematic, neo-noir color palette emphasizing warm yellows and deep blues." \
  "Qwen 3.7 Plus Tinking" "Vintage Taxi Window Night"

queue_job 35 \
  "A serene, intimate photograph taken from the fire escape looking through half-open white wooden venetian blinds into a sunlit apartment window. Inside, a woman in her fifties with short silver hair and a comfortable oversized knit sweater sits in a plush armchair, deeply engrossed in a thick paperback book. The angled blinds cast dramatic, horizontal stripes of bright, warm morning sunlight and soft shadow across her face and the room. Through the gaps in the blinds, the lush green leaves of a potted monstera plant are visible in the foreground, slightly out of focus. There are no reflections on the glass, just the clean, crisp division of light and shadow. The mood is peaceful, quiet, and deeply relaxed. The lighting is natural and directional, highlighting the texture of the knit sweater and the dust motes dancing in the sunbeams, captured with a soft, dreamy aesthetic and high dynamic range." \
  "Qwen 3.7 Plus Tinking" "Apartment Blinds Morning Light"

# --- GLM 5V Turbo ---
queue_job 36 \
  "A photorealistic medium shot captured through a rain-speckled cafe window at twilight, where a young woman with shoulder-length dark hair sits inside gazing outward, her face softly illuminated by warm amber interior lighting that contrasts with the cool blue-violet evening outside, her expression contemplative and slightly melancholic as she rests her chin on her palm while raindrops streak down the glass surface creating organic distortion patterns that partially obscure her features, the wet glass simultaneously reflecting the blurred bokeh of passing car headlights and neon shop signs from the street outside which layer over her silhouette like a double-exposure effect, shot on Canon EOS R5 with 85mm f/1.2 lens at f/2.0 creating shallow depth of field that keeps her eyes sharp while the background dissolves into creamy circles of light, color grading emphasizing teal shadows and warm orange highlights, subtle film grain texture, vertical composition with the subject positioned using rule of thirds, atmospheric moisture visible on the glass surface catching and refracting the ambient light into tiny prismatic highlights." \
  "GLM 5V Turbo" "Rainy Cafe Window Portrait"

queue_job 37 \
  "A cinematic nighttime photograph taken from inside a moving city bus through the window beside a solitary male passenger in his thirties with short cropped hair wearing a dark wool overcoat, his profile silhouetted against the blur of streaming city lights outside as he stares forward with a pensive distant expression, the glass surface acting as a semi-transparent mirror reflecting the dim interior bus lighting and the faint glow of other passengers' phone screens while simultaneously revealing the kinetic smear of neon signs traffic lights and illuminated storefronts rushing past outside in long exposure trails, captured with Sony A7S III using 35mm lens at f/1.8 ISO 3200 producing natural digital noise that enhances the gritty urban atmosphere, cool color temperature dominated by electric blues magentas and deep blacks with occasional warm yellow-orange punctuations from street lamps, horizontal framing emphasizing the motion and the barrier between interior stillness and exterior chaos, slight lens flare from bright light sources, authentic bus window texture with minor smudges and condensation." \
  "GLM 5V Turbo" "Night Bus Window Solitude"

queue_job 38 \
  "An editorial fashion photograph shot through the pristine glass storefront of an upscale boutique during magical hour golden sunset light, featuring an elegant woman in her late twenties with flowing auburn hair wearing a cream-colored silk blouse standing inside near the window arranging merchandise with graceful deliberate movements, her figure bathed in the warm honey-toned sunlight streaming through the glass while the exterior street scene reflects subtly on the surface showing bare winter tree branches silhouetted against a coral-pink and lavender gradient sky plus the soft-focus shapes of pedestrians walking past carrying shopping bags, the reflection creating a ghostly layered composite image where interior and exterior realities merge beautifully, photographed with Phase One XF IQ4 150MP camera system and 80mm Schneider lens at f/4.0 for exceptional detail resolution, rich saturated colors with golden highlights on skin and fabric, elegant sophisticated mood suggesting luxury and tranquility, square composition centered on the subject with balanced negative space, crystal-clear glass with minimal distortion allowing both planes of focus to remain legible." \
  "GLM 5V Turbo" "Golden Hour Boutique Display"

queue_job 39 \
  "An intimate domestic scene photographed through a bathroom mirror heavily fogged with steam from a hot shower where a woman with wet dark hair wrapped in a white towel stands wiping condensation from the glass surface with her palm creating a clear circular viewport through which her eyes meet the camera directly with vulnerable honest expression, the surrounding steamy areas obscuring the rest of her face and body while the cleared circle reveals detailed skin texture water droplets on her shoulders and collarbones plus the soft bathroom lighting behind her casting gentle shadows, the mirror surface also faintly reflecting the out-of-focus shapes of toiletries on the counter and the shower curtain pattern adding depth layers to the composition, captured with Fujifilm GFX 100S and GF110mm f/2 lens at f/2.8 producing beautiful bokeh in the background elements, warm color palette of soft whites peach tones and muted earthy browns evoking privacy and morning ritual atmosphere, tight portrait cropping focusing on face and upper torso, high humidity visible as mist particles suspended in air catching light, raw unposed authenticity with natural imperfections." \
  "GLM 5V Turbo" "Steamed Bathroom Mirror Intimacy"

queue_job 40 \
  "A contemporary architectural photograph taken through the transparent glass partition wall of a modern open-plan office space where a professionally dressed woman in her mid-thirties with neat blonde bun wearing a navy blazer stands engaged in conversation with a male colleague gesturing toward a tablet screen they are both viewing, the glass divider between them and the camera creating complex multi-layered reflections that show overlapping images of the office interior including rows of computer monitors potted plants and other employees working in the background plus the exterior city skyline visible through floor-to-ceiling windows behind the subjects all simultaneously reflected on the glass surface creating an almost abstract geometric composition of transparency and mirroring, shot with Hasselblad X2D 100C and 90mm lens at f/5.6 for deep depth of field keeping all reflective planes reasonably sharp, clean clinical color grading with neutral whites cool grays and accent blues conveying professional corporate aesthetic, wide angle perspective showing environmental context, crisp modern glass quality with anti-glare coating subtle green tint at edges, dynamic business energy balanced with compositional sophistication." \
  "GLM 5V Turbo" "Corporate Glass Wall Layers"

# --- Kimi K2.6 High ---
queue_job 41 \
  "A solitary East Asian woman in her thirties sits at a counter inside a retro American diner, viewed from the sidewalk through a large rain-streaked glass window, her face softly illuminated by warm amber overhead lamps while cool blue neon signs from the street reflect across the wet glass surface in diagonal rivulets, she holds a white ceramic mug with both hands near her chin and gazes downward with a pensive expression, condensation and rain droplets blur the boundary between interior and exterior, cinematic photography style, shallow depth of field focusing on her eyes through the glass distortion, moody nocturnal atmosphere with high contrast between warm tungsten interior and cold sodium vapor exterior, subtle film grain, square framing." \
  "Kimi K2.6 High" "Midnight Diner Glow"

queue_job 42 \
  "A middle-aged Black man with short graying hair sits by the window of a moving city bus, photographed from the sidewalk through the tinted glass which reflects the overcast morning sky and passing concrete buildings, he wears a charcoal wool coat and rests his forehead gently against the cool glass with eyes closed, his breath creating a small patch of fog on the window, inside the bus other passengers appear as soft silhouettes while outside the reflection shows bare winter tree branches overlapping his profile, documentary photography style, natural diffused daylight, muted desaturated color palette, intimate medium shot, melancholic quiet mood, subtle scratches on the glass surface adding texture." \
  "Kimi K2.6 High" "Morning Commute Reflection"

queue_job 43 \
  "A South Asian woman in her forties arranges white lilies inside a small neighborhood flower shop, seen through the front display window covered in a thin layer of steam from a humidifier, her hands carefully positioning stems among brown craft paper wrapping, the glass also reflects the golden hour sunset from the opposite street painting orange and pink hues across the condensation, she wears a simple linen apron over a rust-colored sweater and looks down at her work with gentle concentration, soft volumetric light filters through the blooms and steam, lifestyle photography style, dreamy ethereal atmosphere, warm color grading, the window frame painted chipping white wood, shallow focus on her hands through the misty barrier." \
  "Kimi K2.6 High" "Florist's Steamy Glass"

queue_job 44 \
  "A tall Caucasian man in his fifties stands behind a floor-to-ceiling glass wall in a modern minimalist apartment, looking out at a snow-covered cityscape while the glass reflects the bare branches of a large oak tree from the courtyard behind the camera, he wears a dark turtleneck and holds a glass of amber whiskey in his right hand down at his side, his left hand pressed flat against the cold transparent surface leaving a faint palm print, the interior behind him dimly lit by a single pendant lamp casting long shadows, architectural photography style, crisp detail on the glass texture, cool winter light mixing with warm interior glow, contemplative isolated mood, high clarity." \
  "Kimi K2.6 High" "Glass Wall Solitude"

queue_job 45 \
  "A young Hispanic couple in their late twenties sits in the back seat of a yellow taxi at night, photographed through the rear passenger window from the street, the glass covered in light rain and reflecting vibrant pink and green neon signs from a busy downtown strip, the woman leans her head on the man's shoulder while he looks out the window with a distant expression, his hand rests on her knee, the taxi's interior lit by the soft glow of the dashboard and passing streetlights creating chiaroscuro patterns on their faces, cinematic film photography style, anamorphic lens flare, moody romantic tension, wet glass creating bokeh light orbs, urban nightlife atmosphere, deep shadows and selective color highlights." \
  "Kimi K2.6 High" "Neon Taxi Confession"

# --- Deepseek Vision ---
queue_job 46 \
  "A wet taxi cab window pane streaked with heavy rain droplets and condensation trails, the interior cabin dimly lit by amber dashboard glow, a solitary adult passenger of Southeast Asian descent with a contemplative gaze, their breath fogging the glass slightly, seated in the back seat looking outward, their hand resting near the window edge, outside the glass a blurred nocturnal cityscape with vibrant red and blue neon signboards reflecting and smearing across the wet surface, the reflection of the passenger's own silhouette overlapping the external lights, shallow depth of field focusing on the raindrops on the glass while the interior and exterior remain soft, moody cinematic style with teal and orange color grading, medium shot framed tightly to include the window frame edge and the side mirror, diffused streetlight illumination casting long shadows." \
  "Deepseek Vision" "Rainy Taxi Window Reflection"

queue_job 47 \
  "A steamy floor-to-ceiling cafe window pane partially cleared by a hand swipe, revealing a busy rain-slicked cobblestone street outside, a mature Caucasian female barista in a crisp white apron standing just behind the glass interior, leaning forward slightly with a focused expression as she pours delicate latte art into a ceramic cup, her sleeves rolled up, the warm interior glow of pendant lamps casting golden highlights on her face and hands, the window itself covered in a thin layer of steam and scattered water droplets that catch the light, reflecting the cozy wooden shelves and hanging mugs from the interior onto the glass surface, creating a layered composition where the reflected interior fuses with the blurred external pedestrians holding umbrellas, intimate documentary photography style, natural window lighting mixed with warm artificial overheads." \
  "Deepseek Vision" "Steamy Cafe Window with Barista"

queue_job 48 \
  "A full-height tempered glass wall of a high-rise corner office, the exterior surface immaculately clear with faint dust specks, a middle-aged Black male professional in a tailored charcoal suit standing with his back partially turned, one palm pressed flat against the cool glass, gazing out at a vast sprawling city skyline bathed in the deep orange and magenta hues of a setting sun, the exterior skyline sharp and expansive through the glass, while the glass surface simultaneously reflects the stark minimalist interior behind him—a white desk, a glowing monitor, and an abstract painting—superimposing these geometric shapes over the cityscape, creating a stark contrast between the warm exterior and cool interior fluorescent tones, wide establishing shot capturing the full wall and the person's profile, dramatic side lighting from the sunset creating a rim light effect on his figure." \
  "Deepseek Vision" "Modern Glass Wall Office Sunset"

queue_job 49 \
  "An aged storefront glass pane with subtle scratches and dust, framing a retro mannequin dressed in a vibrant 1970s velvet dress positioned just behind the glass inside a dimly lit boutique, the mannequin's faceless form posed elegantly with one arm extended toward the viewer, outside the glass a South Asian adult female passerby wearing a beige trench coat and holding a leather handbag, her reflection sharply cast onto the glass surface due to the interior spotlights, her reflection interacting spatially with the mannequin as if they are facing each other, the external sidewalk and parked bicycles visible through the lower portion of the glass, the reflection of street lamps and autumn leaves creating an overlay of warm orange tones over the cool blue interior, moody narrative portrait, shallow focus on the reflection of the woman's face while the mannequin and background blur, soft misty evening atmosphere." \
  "Deepseek Vision" "Vintage Boutique Shop Window at Dusk"

queue_job 50 \
  "A large tinted bus window pane covered with a fine layer of evening condensation and faint vertical streaks from the rain, a young adult Hispanic female passenger seated near the window, her temple gently resting against the cold glass, her eyes half-closed in a state of weary reverie, her dark hair spilling over her shoulder, outside the window the city moves in a rapid horizontal blur of golden bokeh lights from street lamps and passing vehicles, the reflection of her own calm face and the bus interior's blue overhead lights overlaid precisely over the exterior light trails, creating a ghostly double exposure effect, the glass's edge revealing a strip of the bus seat fabric and metal handrail, the composition cropping closely to her profile and the window, ambient low-light photography with high contrast and slight grain, the reflection of a distant traffic signal casting a red hue across her cheek." \
  "Deepseek Vision" "Night Bus Window with City Blur"

# --- ERNIE 5.1 ---
queue_job 51 \
  "A moody photograph shot through a rain-streaked cafe window at dusk, a young woman in her late twenties with dark curly hair and a burgundy knit sweater sitting alone at a small marble table behind the glass, her chin resting on her hand gazing softly outward, warm amber light from a pendant lamp inside illuminating her face while cool blue twilight reflects on the wet glass surface mixing with raindrop trails that distort her silhouette, a faint ghostly reflection of a neon \"OPEN\" sign reversed on the glass pane, the window frame dark wooden and slightly weathered, raindrops beading and streaming down creating natural lens-like distortions across the composition, shallow depth of field with the glass surface in sharp focus and her figure softly blurred behind, reflections of passing streetlights and a blurred taxi cab headlight streaking across the wet pane, square framing centered on her face through the layered glass, cinematic color grading with teal and orange tones, photorealistic street photography style." \
  "ERNIE 5.1" "Rain-Laced Cafe Window Portrait"

queue_job 52 \
  "A intimate photograph captured through a foggy bathroom mirror in a sunlit apartment, a man in his early thirties with a trimmed beard and bare shoulders standing close to the glass wiping condensation with his palm revealing his focused expression, the mirror surface half-steamed with visible breath-fog and water droplets clinging to edges, his warm skin tones contrasting with the cool grey-blue of the fogged glass, behind him a white tiled wall and a towel rack with a hanging navy towel softly out of focus, the cleared patch of mirror showing sharp detail of his tired eyes and damp hair while surrounding steam diffuses everything else into a dreamy glow, morning golden sunlight entering from a frosted window to the left casting long warm highlights across the tiles, square composition framed tightly on the mirror surface, naturalistic indoor lighting, editorial portrait photography with soft grain and muted desaturated palette." \
  "ERNIE 5.1" "Steamy Bathroom Mirror Morning"

queue_job 53 \
  "A candid photograph taken from outside looking through a city bus window at night, a middle-aged East Asian man in a grey wool coat and wire-rim glasses seated inside near the window with his forehead gently pressed against the cold glass, his eyes closed in quiet exhaustion, the glass surface reflecting the bright storefronts and neon signage of the street behind the camera creating a double-exposure effect where colorful commercial lights overlap his pale face, interior bus lighting casting a flat fluorescent green wash on his features while exterior reflections add warm reds and electric blues, other passengers as vague dark shapes in the deep background, condensation fogging the lower corner of the pane, the bus window frame aluminum and scratched, shot at eye level straight on through the glass, urban documentary photography style with high contrast and saturated reflections, rain beginning to speckle the outer surface." \
  "ERNIE 5.1" "Bus Window City Commute"

queue_job 54 \
  "A contemplative photograph seen through a floor-to-ceiling tinted glass wall of a modern office at blue hour, a Black woman in her forties with natural locs and a white blouse standing inside leaning against the glass partition with arms crossed, her expression calm and pensive, the tinted glass giving everything a cool teal-grey cast while her reflection merges with the view of the empty office behind her including a long conference table and ergonomic chairs, outside the glass the camera catches reflections of a parking lot with a few cars and a distant orange sunset bleeding through clouds, the glass surface clean but with subtle vertical streaks from cleaning, interior office lights off except for a single desk lamp creating a pool of warm light behind her that silhouettes her figure slightly, square framing symmetrically centered on her torso through the transparent barrier, architectural photography with clean lines and moody atmosphere, muted corporate tones." \
  "ERNIE 5.1" "Glass Wall Office Solitude"

queue_job 55 \
  "A cinematic photograph captured through the rain-dotted rear window of a yellow taxi at night, a South Asian couple in their late twenties sitting in the back seat, the woman with long black hair leaning her head on the man's shoulder as they both look out the opposite window away from camera, their faces visible through the glass but softened by water droplets and street light bokeh, the taxi window reflecting the wet road behind them with streaking red taillights and a blurred \"TAXI\" rooftop sign glowing yellow, interior dim with only dashboard glow casting faint green on their skin, the glass slightly tinted creating a warm amber overlay on the whole scene, outside rain pours heavily with city lights diffusing into colorful orbs across the pane, close square framing focused on their intertwined hands resting on the seat with faces partially visible through the layered reflections, film noir aesthetic with rich shadows and saturated highlights, photojournalistic intimacy." \
  "ERNIE 5.1" "Taxi Rear Window Farewell"

# --- LongCat Deep search ---
queue_job 56 \
  "A contemplative woman in her thirties sits alone at a small wooden table inside a dimly lit cafe, her chin resting on her hand as she gazes out the large window. Outside, a rainy city street glistens under the glow of neon signs and streetlamps. The glass pane is streaked with raindrops, blurring the vibrant reflections of passing cars and pedestrians with the warm, amber interior light. The composition is framed tightly on her profile and the wet glass, creating a mood of quiet melancholy and introspection. Cinematic lighting, shallow depth of field, photorealistic style, shot on 35mm lens." \
  "LongCat Deep search" "Solitary Reflection in the Rain"

queue_job 57 \
  "A bustling outdoor street market filled with colorful umbrellas and fresh produce stalls, viewed through the rain-soaked glass window of a closed shop. The wet glass distorts and refracts the vivid reds, yellows, and greens of the market, blending them with the dark reflections of the shop's interior. A smiling vendor in a yellow raincoat stands behind the glass, wiping the fog away to look out. The scene is dynamic and lively, capturing the joyful chaos of a city shower. Wide-angle perspective, high contrast, vibrant colors, editorial photography style." \
  "LongCat Deep search" "Vibrant Hues Through the Downpour"

queue_job 58 \
  "An elderly man with silver hair stands by the window of a vintage apartment, looking out at a breathtaking sunset over the city skyline. The window glass has a slight green tint and subtle imperfections, catching the golden hour light and reflecting the warm hues of the room's wooden furniture and old photographs. His posture is relaxed, one hand resting on the window frame, evoking a sense of peaceful nostalgia and quiet contentment. Soft, diffused natural light, warm color palette, painterly realism, medium shot." \
  "LongCat Deep search" "Golden Hour Reverie"

queue_job 59 \
  "The interior of a late-night city bus, viewed through a fogged-up window. A silhouette of a passenger sits in the background, while in the foreground, a hand has drawn a small heart in the condensation on the glass. Outside, the blurred lights of a passing subway station and wet pavement are visible through the cleared patch. The atmosphere is transient, lonely, and slightly mysterious, capturing a fleeting moment of urban isolation. Moody lighting, cool blue tones, cinematic composition, shot on 50mm lens." \
  "LongCat Deep search" "Transit Whispers"

queue_job 60 \
  "A couple sits at a candlelit table in a cozy, upscale restaurant, seen through a glass partition fogged with steam from a nearby kitchen. The glass softens their features and blends the warm glow of the candle with the reflections of hanging pendant lights. The woman laughs softly, leaning forward, while the man watches her with a gentle smile. The scene is intimate and romantic, with the steamy glass adding a dreamlike quality to the moment. Soft focus, warm ambient light, romantic mood, fine art photography style." \
  "LongCat Deep search" "Intimate Dinner Glow"

echo "✅ All 60 jobs queued in scheduler"

