#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Shadows — photorealistic exhibition-grade shadow art, unexpected
#        object/silhouette transformations, and interplay of light and
#        meaning
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+44+-+Shadows
# Structure: 13 models × 5 prompts = 65 tasks total
# ---------------------------------------------------------------------------
# --- Claude Sonnet 5 high ---
queue_job  1 \
  "Exhibition-grade shadow art installation photographed straight-on: a jumbled pile of rusted scrap metal, broken chair legs, tangled wire, and shattered glass fragments arranged on a low pedestal, a single warm spotlight angled from the left throwing a crisp black shadow across a white gallery wall that resolves into the unmistakable silhouette of an old man's profile, wrinkles suggested by wire tangles, photorealistic textures on the scrap, soft ambient fill light, shallow depth of field on the objects, sharp focus on the shadow's edge, quiet contemplative gallery mood." \
  "Claude Sonnet 5 high" "Junkyard Portrait"

queue_job  2 \
  "Close-up photorealistic shot of a clenched human fist held against a bare concrete wall under a single hard raking light from the right, the shadow it casts unexpectedly reading as a dove in flight with wings spread and beak pointed upward, fine dust particles floating visible in the light beam, skin texture and knuckle detail rendered crisply, the shadow edge razor sharp against the rough concrete grain, muted grey and amber palette, ironic tender mood contrasting aggression and peace." \
  "Claude Sonnet 5 high" "Fist Into Dove"

queue_job  3 \
  "Photorealistic architectural interior shot of a spiral concrete stairwell lit by a single skylight beam, a lone ballerina mid-leap on the lower steps caught in silhouette, her elongated warped shadow stretching diagonally up the curved wall above her in a dramatic twisting arc that exaggerates her leap into something monumental, dust motes drifting in the light shaft, cool blue-grey tones on the concrete, warm rim light on her figure, wide low-angle framing emphasizing the shadow's scale over the dancer herself." \
  "Claude Sonnet 5 high" "Stairwell Dancer"

queue_job  4 \
  "Intimate photorealistic macro shot of dappled shadow cast by an ornate wrought-iron window grille falling across a bare shoulder and collarbone resting near a sunlit windowsill, no other objects visible, the shadow pattern reading like delicate lace laid onto skin, warm late-afternoon sunlight, soft focus background, fine skin texture with visible pores and light freckles, high contrast between crisp shadow lines and glowing warm highlights, quiet serene mood, natural framing cropped tight at chest and neck." \
  "Claude Sonnet 5 high" "Lace on Skin"

queue_job  5 \
  "Exhibition still-life photograph of a disassembled bicycle, wheel rim, handlebars, chain, and pedal arranged in careful clutter on a dark plinth, a single focused spotlight from above-left casting their combined shadow onto a pale wall where the shapes align into the unmistakable silhouette of a galloping horse mid-stride, mane suggested by loose chain links, legs formed by spokes, photorealistic metal textures with visible rust and grease, crisp shadow edges, gallery-white backdrop, triumphant surprising mood." \
  "Claude Sonnet 5 high" "Bicycle Horse"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A photorealistic, ground-level medium shot captures a weathered brick alleyway bathed in late-afternoon sunlight. A street musician sits on a wooden crate playing an acoustic guitar, but the long dark shadow cast against the sunlit brick wall behind him reveals the sharp, unambiguous silhouette of a crowned monarch holding a regal scepter. The sun hangs low off-camera to the left, casting stark high-contrast warm light across the pavement while rendering the intricate shadow with extreme sharpness and clarity. Dust motes float in the warm golden light beam, emphasizing the spatial depth between the musician on the ground and the heroic shadow figure on the wall." \
  "Gemini 3.5 Flash" "Subtle Subversion in the Alleyway"

queue_job  7 \
  "An exhibition-grade gallery installation features a chaotic, intricately arranged pile of rusted wire, bent silver spoons, and clear glass shards mounted on a polished concrete pedestal. A single sharp spotlight positioned precisely to the front-left projects a remarkably clean, unified dark shadow onto the pristine matte white gallery wall behind it, revealing a perfectly detailed silhouette of a modern city skyline with towering skyscrapers and a suspension bridge. The contrast is crisp, with the textured, chaotic physical objects brightly illuminated in the foreground while the stark black shadow on the smooth wall delivers an unexpected geometric structure." \
  "Gemini 3.5 Flash" "The Sculpted Scrap City"

queue_job  8 \
  "A high-speed action photograph taken from a low angle on a sun-drenched outdoor asphalt basketball court shows a female athlete mid-air, extending her arm to lay up a basketball. Her long black shadow, cast crisply across the sun-bleached blue pavement below, bends and warps across the court's painted white lines to form the distinct silhouette of a bird in full flight with spread wings. The scene is illuminated by harsh, direct noon sunlight, creating deep dark shadows and brilliant highlights on her athletic wear, emphasizing the dynamic tension between her physical motion and the graceful shadow silhouette." \
  "Gemini 3.5 Flash" "Mirage on the Court"

queue_job  9 \
  "A cinematic wide shot set in a misty, cobblestone city street at night lit by a single warm gas streetlamp. A solitary man in a tailored trench coat and fedora walks past a damp stucco building wall, but the long, exaggerated shadow projected across the wet surface depicts a person wearing an elaborate masquerade mask holding an intricate Venetian mask up to their face. The streetlamp casts a warm amber glow on the damp cobblestones and light fog, creating a sharp contrast against the deep black, oversized shadow stretching across the reflective wall." \
  "Gemini 3.5 Flash" "Double Life in the Fog"

queue_job 10 \
  "A minimalist studio photograph of a single folded white paper crane resting on a smooth grey slate tabletop. A focused cool LED lamp positioned at a low angle from the side illuminates the paper structure, while the crisp shadow thrown across the slate surface forms the detailed, realistic silhouette of a living, feather-covered bird about to take flight. The lighting is precise and soft, highlighting the sharp geometric folds of the physical paper while maintaining deep, clean edges on the dark grey shadow, creating a subtle contrast between paper artifice and organic silhouette." \
  "Gemini 3.5 Flash" "The Origami Metamorphosis"

# --- ChatGPT +think ---
queue_job 11 \
  "A photorealistic fine-art photograph of a lone woman standing on a sunlit concrete plaza, viewed from a high oblique angle so her real body appears ordinary while her sharply defined shadow stretches across the ground as enormous feathered wings, created by carefully positioned architectural screens and sculptural foliage outside the frame. She stands upright with one hand slightly raised and her coat moving gently in the wind, while the shadow wings extend symmetrically behind her as though she is a mysterious angel. Late-afternoon sunlight creates crisp geometric edges, subtle warm highlights on the pavement, and deep neutral shadow tones. The composition emphasizes the contrast between the small human figure and the enormous symbolic silhouette, with realistic pavement texture, faint cracks, distant reflections, natural atmospheric depth, and meticulous exposure. Sophisticated contemporary gallery photography, cinematic but believable, elegant negative space, visually striking without surreal rendering artifacts." \
  "ChatGPT +think" "Borrowed Wings"

queue_job 12 \
  "A photorealistic exhibition-grade shadow photograph showing an old wrought-iron garden chair placed alone on a pale stone floor inside a quiet sunlit gallery, with a large branch, hanging leaves, and several delicate flowers positioned between a strong directional light source and the wall behind it. The physical chair remains simple and nearly empty, but its sharply projected shadow transforms into an elaborate overgrown garden gate covered with vines and blossoms, creating a poetic reversal between object and silhouette. A small elderly woman sits quietly on the chair reading a book, while her own shadow merges into the foliage and appears seated beneath a flowering tree. Soft architectural light from one side creates precise overlapping contours, subtle imperfections, realistic stone texture, and beautifully controlled tonal transitions. Museum-quality contemporary photography, restrained color palette, quiet contemplative mood, elegant symmetry, natural optical realism, finely resolved shadows." \
  "ChatGPT +think" "The Secret Garden"

queue_job 13 \
  "A photorealistic street photograph captured just after sunset, showing three commuters rushing across a narrow city intersection while warm storefront light and a bright overhead streetlamp cast unusually long shadows toward the camera. The people are dressed in realistic contemporary clothing, each captured mid-stride with natural running poses and subtle motion in coats and bags, yet their shadows tell a different story: one shadow appears to be calmly walking backward, another seems to hold an umbrella that the person does not carry, and the third stretches into the silhouette of a person standing completely still. Wet asphalt creates faint reflections beneath both people and shadows, while blurred traffic, glowing windows, traffic markings, and distant pedestrians establish a believable urban environment. The effect is created entirely through real lighting, perspective, and carefully arranged environmental elements, not digital fantasy. Documentary street photography blended with sophisticated fine-art composition, cinematic dusk atmosphere, crisp shadow edges, authentic urban detail, emotionally intriguing and visually elegant." \
  "ChatGPT +think" "Running Late"

queue_job 14 \
  "A photorealistic minimalist photograph of a solitary man standing on a vast pale concrete rooftop under intense midday sunlight, seen from a high viewpoint with the architecture forming a clean geometric frame around him. The man's actual figure is small, isolated, and completely still, wearing a dark suit and holding a folded newspaper, while his single sharply defined shadow expands across the pavement into the appearance of a huge cheering crowd made from overlapping silhouettes of dozens of raised arms, heads, and bodies. No additional people are physically present. The visual illusion is produced by carefully arranged architectural cutouts and reflective surfaces outside the composition, creating multiple intersecting shadow shapes that merge into one unexpected image. Hard sunlight, deep black shadow density, subtle concrete texture, sparse composition, precise perspective, sophisticated visual metaphor, museum-quality conceptual photography, clean modern architecture, calm yet psychologically powerful atmosphere." \
  "ChatGPT +think" "A Crowd of One"

queue_job 15 \
  "A photorealistic fine-art photograph of an empty rehearsal room with a polished wooden floor, several vintage musical instruments arranged naturally across the foreground, including a cello, violin, trumpet, upright piano, microphone stand, and music sheets. Strong golden light enters through tall side windows, casting all objects toward a blank cream-colored wall, where their combined shadows unexpectedly merge into the silhouette of a full orchestra performing together. The violin shadow appears to become a conductor's raised arm, the cello shadow forms part of a seated musician, and the microphone stand transforms into an elegant upright figure holding a baton. The real objects remain clearly identifiable in the room while the projected composition becomes visually coherent and surprising. Dust particles glow subtly in the sunlight, reflections shimmer across the polished floor, and realistic wood grain, brass surfaces, paper edges, and fabric textures create tactile photographic detail. Exhibition-grade conceptual photography, warm cinematic lighting, refined composition, poetic atmosphere, believable optics, visually satisfying shadow transformation." \
  "ChatGPT +think" "The Shadow Orchestra"

# --- Grok fast ---
queue_job 16 \
  "Photorealistic image of a solitary dancer mid-leap on a dark stage floor, her body arched backward with arms extended overhead, casting a sharp elongated shadow that stretches across the wooden boards and transforms into the silhouette of a soaring bird with spread wings, soft side lighting from a single spotlight creating crisp edges and subtle gradient falloff on the shadow while the dancer remains partially illuminated in cool blue tones, empty black background emphasizing the interplay of form and absence." \
  "Grok fast" "Shadow Ballet of the Unseen"

queue_job 17 \
  "Photorealistic close-up of an arrangement of rusty pliers, coiled wire, a broken clock face, and scattered screws on a white tabletop under directional overhead light, their combined shadows merging on the surface into the clear outline of a human face with closed eyes and a faint smile, high-contrast hard shadows with precise edges revealing unexpected harmony, neutral studio lighting highlighting metallic textures and the clean geometric fusion of the projected form." \
  "Grok fast" "Assemblage of Forgotten Tools"

queue_job 18 \
  "Photorealistic full-body shot of a firefighter in full gear standing upright with axe raised high in a ready stance, his shadow on the concrete wall behind him morphing into the silhouette of a small frightened child crouching with hands covering the face, harsh late-afternoon sunlight from the left creating elongated distorted proportions that invert the heroic posture into vulnerability, textured brick wall surface catching the shadow details with soft ambient fill light preserving realistic skin and fabric details on the figure." \
  "Grok fast" "Reverse of the Protector"

queue_job 19 \
  "Photorealistic street-level view of two figures running in opposite directions across a rain-slicked alley at night, their overlapping shadows on the wet pavement forming a single continuous silhouette of a handshake, neon signs and distant streetlamps casting multi-colored rim light that fragments the shadows into layered blues and ambers while reflections in the puddles double the effect, dynamic motion blur limited to the feet and lower legs keeping the upper bodies and shadow forms sharp and readable." \
  "Grok fast" "Urban Night Pursuit"

queue_job 20 \
  "Photorealistic medium shot of a single autumn maple leaf suspended mid-air by a thin invisible thread above a smooth concrete floor, its delicate veins and serrated edges casting a vast intricate shadow that spreads outward into the shape of an entire tree with branching canopy and trunk, soft diffused window light from the side producing long gentle gradients and fine detail in the shadow pattern, minimal empty space around the leaf emphasizing the dramatic scale difference and quiet contemplative mood." \
  "Grok fast" "Silent Cascade of Leaves"

# --- Copilot Smart ---
queue_job 21 \
  "A photorealistic image of a ballet dancer mid-leap in a sunlit studio, her body suspended gracefully while the shadow on the polished wooden floor exaggerates her form into a surreal, elongated silhouette that resembles wings. The light streams through tall windows, creating crisp contrast between the dancer's delicate figure and the bold shadow, giving the impression of transformation from human to bird." \
  "Copilot Smart" "Shadow of a Dancer"

queue_job 22 \
  "A nighttime urban street scene where a lone pedestrian walks past a glowing neon sign, their shadow stretching across the cracked pavement and merging with other shadows cast by bicycles, lampposts, and scattered objects. The interplay of artificial light and darkness creates an accidental collage, forming the outline of a giant face across the ground, as if the city itself is watching." \
  "Copilot Smart" "Shadow City Silhouette"

queue_job 23 \
  "A photorealistic image of a child holding a small toy sword in a bright park, the sunlight casting a shadow on the grass that transforms into the silhouette of a towering knight with shield and armor. The contrast between the innocent figure and the powerful shadow creates a striking reversal of meaning, blending playfulness with grandeur." \
  "Copilot Smart" "Reverse Meaning Shadow"

queue_job 24 \
  "A gallery installation where dozens of everyday objects—chairs, bottles, tools, and wires—are arranged in chaotic clusters under a spotlight. Their shadows converge on the white wall to form a perfectly clear image of a galloping horse. The composition is crisp, photorealistic, and exhibition-grade, with viewers standing nearby in awe, their own shadows blending into the artwork." \
  "Copilot Smart" "Exhibition Shadow Art"

queue_job 25 \
  "A photorealistic seaside scene at golden hour, where two friends run along the wet sand, their bodies blurred in motion while their elongated shadows stretch far ahead, sharp and clear. The shadows appear to be racing faster than the figures themselves, creating a playful illusion of competition between reality and its darker reflection, framed by glowing waves and warm light." \
  "Copilot Smart" "Beach Shadows in Motion"

# --- Mistral Think ---
queue_job 26 \
  "Photorealistic modern art gallery, a suspended arrangement of metallic tools and geometric shapes casting a precise shadow of a soaring eagle with outstretched wings onto a smooth white cyclorama wall, single overhead spotlight creating dramatic chiaroscuro lighting, razor-sharp shadow edges, subtle atmospheric dust, polished concrete floor, 50mm prime lens, f/2.8, shallow depth of field." \
  "Mistral Think" "Shadow Eagle Installation"

queue_job 27 \
  "Photorealistic dance studio with hardwood floor, two contemporary dancers in mid-air leap casting elongated shadows that merge into a single graceful figure on the white wall, late afternoon sunlight streaming through tall windows, warm golden hour light, visible wood grain, atmospheric depth, 85mm lens, f/2.4, soft bokeh in background." \
  "Mistral Think" "Shadow Dance Fusion"

queue_job 28 \
  "Photorealistic urban alleyway, a weathered iron peace sign sculpture bolted to a red brick wall, low afternoon sun casting its shadow as a sword shape onto the concrete pavement below, dramatic side lighting, high contrast, peeling paint, urban texture, 35mm lens, f/4.0, black and white photography style." \
  "Mistral Think" "The Peace Paradox"

queue_job 29 \
  "Photorealistic empty city street at golden hour, a long human shadow stretching across the asphalt with no visible person casting it, low angle sunlight, sharp shadow definition, subtle pavement cracks, warm amber light, urban architecture in background, 35mm lens, f/8.0, cinematic composition." \
  "Mistral Think" "The Invisible Walker"

queue_job 30 \
  "Photorealistic modern plaza, a glass and steel building casting a complex geometric web of shadows across the granite pavement and onto adjacent facades, golden hour light creating long diagonal patterns, pedestrians walking through the shadow grid, warm tones, 24mm tilt-shift lens, f/8.0, deep depth of field, architectural photography." \
  "Mistral Think" "Architectural Shadow Web"

# --- Qwen 3.8 Max Tinking ---
queue_job 31 \
  "Photorealistic exhibition-grade shadow art photograph, a chaotic suspended installation of twisted wire, broken glass shards, bent metal rods, and torn fabric pieces hanging from thin fishing lines in a dark gallery space, a single powerful warm tungsten spotlight positioned low and to the left at roughly 15 degrees illuminates the arrangement, the combined shadow projected onto a large white plaster wall behind forms the unmistakable elegant silhouette of a ballerina in arabesque pose with tutu and pointed toe, the shadow is crisp and detailed with soft penumbra edges, the physical objects are clearly visible as abstract junk in the midground catching glints of light, shot on a medium format camera at f/8, shallow depth separation between the installation and the wall, gallery lighting ambience with deep blacks in the surrounding space, the composition is centered with the shadow figure occupying the upper two-thirds of the wall, museum-quality fine art photography aesthetic, dramatic chiaroscuro, the mood is poetic and revelatory." \
  "Qwen 3.8 Max Tinking" "The Ballerina in the Wreckage"

queue_job 32 \
  "Photorealistic golden-hour street photography, a small child approximately seven years old mid-sprint with arms outstretched horizontally and hair blowing back, running along a sun-bleached concrete wall on the right side of frame, the late afternoon sun positioned extremely low behind and slightly left of the child casts a long stretched shadow onto the textured wall, a wrought-iron decorative fence segment stands between the child and the wall in the background, the fence bars and scrollwork merge with the child's shadow to transform the silhouette into a figure with large feathered angel wings spread wide, the shadow appears to take flight while the child simply runs, warm amber and honey-colored light wraps the scene, long parallel shadows of the fence bars stripe the lower portion of the wall, shot at 35mm equivalent f/5.6, the child is positioned in the lower-right third with the transformed shadow dominating the upper-left two-thirds of the wall, dust motes float in the golden backlight, the mood is innocent and magical, Kodak Portra 400 color rendering with soft grain." \
  "Qwen 3.8 Max Tinking" "Wings of the Fence"

queue_job 33 \
  "Photorealistic surreal editorial photograph, a solitary middle-aged man in a plain charcoal suit stands perfectly rigid and still with arms pinned to his sides and head slightly bowed on a vast empty salt flat at high noon, the harsh overhead sun casts a short dark shadow directly beneath him, however the shadow on the cracked white ground beneath depicts a wildly different figure in a dynamic flamenco dance pose with one arm arched overhead and one leg kicked back and head thrown in ecstasy, the shadow is razor-sharp with deep black core and minimal penumbra due to the overhead light, the contrast between the still man and his ecstatic shadow is stark and unsettling, shot from a slightly elevated three-quarter angle looking down at approximately 40 degrees, wide-angle 24mm lens capturing the expanse of white salt around the figure, the sky is a pale bleached gradient above, the composition places the man in the center with his contradictory shadow spreading below him, hyper-detailed skin texture on the man's hands visible at his sides, the mood is quietly absurd and philosophical, fine art photography with clinical precision." \
  "Qwen 3.8 Max Tinking" "The Dancer Who Stands Still"

queue_job 34 \
  "Photorealistic cinematic portrait photograph, a woman in her late thirties sits at a small wooden table in a dimly lit room facing the camera at a slight three-quarter angle, her expression is contemplative with parted lips and downcast eyes, a single bare incandescent bulb hangs to her upper right, between the bulb and her face a set of partially open venetian blinds is mounted on an unseen window frame just out of the top of the frame, the blinds cast sharp horizontal shadow stripes across her entire face and shoulders and the table surface, every other stripe of her skin is illuminated in warm amber while the alternating stripes fall into deep shadow, one hand rests on the table holding an unlit cigarette with a thin wisp of smoke rising through the shadow bands, the background is a dark textured wall with a faint circular shadow pattern from the bulb filament, shot at 85mm f/2.0 with the focus locked on her eyes, the depth of field softly dissolves the background, the color palette is restricted to warm ambers deep browns and blacks, the mood is confessional and tense, 1940s film noir aesthetic rendered in modern digital clarity, skin pores and individual eyelashes visible in the lit stripes." \
  "Qwen 3.8 Max Tinking" "Noir Confession"

queue_job 35 \
  "Photorealistic overhead flat-lay shadow photograph, a weathered wooden table surface viewed from directly above fills the frame, scattered across the table in an apparently random arrangement are approximately forty pieces of vintage silverware including forks knives spoons a whisk a corkscrew and several small metal gears and keys, a single hard directional light source enters from the upper left at a very low raking angle roughly 8 degrees above the table surface, the elongated shadows cast by the cutlery and objects onto the wood grain collectively form the recognizable skyline of a city at dusk with skyscrapers church spires water towers and tiny lit-window rectangles suggested by gaps between shadow shapes, the actual objects are clearly identifiable as kitchen items in the midground catching specular highlights along their tines and bowls, the wood grain texture is warm honey-colored with visible scratches and age, the shadow skyline stretches across the lower two-thirds of the frame while the objects cluster in the upper third, shot on a technical camera at f/11 for edge-to-edge sharpness, the mood is whimsical and contemplative, fine art still life photography with narrative depth." \
  "Qwen 3.8 Max Tinking" "The City in the Cutlery"

# --- GLM 5.3 Flash Think max ---
queue_job 36 \
  "Photorealistic photograph inside a contemporary art museum gallery: a chaotic found-object assemblage mounted on a slim black steel armature at chest height, built from tangled bicycle chains, bent coat hangers, wooden blocks, forks, coiled springs, wire loops and the neck of a broken violin, the sculpture itself looking like random scrap; a single warm spotlight on a ceiling track rakes across it from the left, and on the seamless white gallery wall behind, the combined shadows of all those parts interlock into one razor-sharp, unmistakable silhouette of a ballerina holding a perfect arabesque, arms extended, tutu flaring, toes pointed; to the right, a softly out-of-focus museum visitor in a gray sweater stands holding up a phone to photograph it, small in the frame for scale; polished concrete floor with a faint pool of reflected spotlight, dim framed artworks visible down the corridor behind; shot on a 50mm lens at f/2.8, crisp shadow edges, clean museum color grading, subtle vignette, high micro-detail, exhibition photography style." \
  "GLM 5.3 Flash Think max" "The Scrap Ballerina"

queue_job 37 \
  "Photorealistic vanitas still-life photograph in the spirit of Dutch Golden Age painting: a lush overflowing bouquet of red tulips, cream roses, purple anemones and eucalyptus sprigs arranged in a faceted crystal vase on a dark walnut table; one hard directional beam of window light rakes from the upper left across the blooms and stems; on the warm textured plaster wall behind, the overlapping shadows of petals, leaves and the vase merge into the unmistakable profile of a human skull, hollow eye socket, nasal cavity and teeth all legible in the silhouette, while the flowers themselves remain soft and romantic; a snuffed candle stub and three fallen petals rest on the table edge, the foreground dissolving into deep chiaroscuro shadow; shot on medium format, 90mm lens at f/8, rich tonal range, hyper-detailed petal veins and glass refractions, faint film grain, moody and elegant." \
  "GLM 5.3 Flash Think max" "Memento in the Bouquet"

queue_job 38 \
  "Photorealistic street photography shot in an empty cracked-asphalt parking lot at golden hour: the entire action told only in shadow, because the skater is out of frame; stretched hugely across the sunlit pavement is the long dark shadow of a skateboarder mid-trick, knees crouched, arms flung wide for balance, head tilted down, and floating separately a full meter above the body shadow is the crisp small shadow of the skateboard itself, frozen mid-kickflip with trucks and wheels clearly readable in silhouette; only the toe of a scuffed canvas sneaker and one wheel intrude into the extreme lower right corner of the frame; low raking sun makes every pebble and crack in the asphalt glow with sparkling grit, warm amber light against elongated cool shadow tones, faint heat haze and dust motes; shot on a 200mm lens at f/2.8, 1/2000s shutter, motion frozen, compressed telephoto perspective, editorial sports photography quality." \
  "GLM 5.3 Flash Think max" "Kickflip at Golden Hour"

queue_job 39 \
  "Photorealistic film noir photograph of a 1940s detective office at night, empty of any actual person yet occupied entirely by a shadow: on the far plaster wall, cast through venetian blinds by a streetlamp outside the rain-streaked window, stands the sharp striped shadow of a man in a fedora and trench coat holding a briefcase, one clean horizontal bar of blind-light cutting across where his eyes would be; beside the figure, the wavy shadow of window blinds and rain streaks trembles on the wall; in the foreground a wooden desk holds a glowing green banker's lamp, scattered case files, a half-full whiskey glass, and curling cigarette smoke drifting through a shaft of light and catching the glow; long soft reflections stretch across the polished wooden floorboards; shot on a 35mm lens at f/2, high-contrast black and white with a faint warm tint, deep true blacks, Tri-X 400 grain, cinematic low-key lighting, dramatic composition." \
  "GLM 5.3 Flash Think max" "The Visitor"

queue_job 40 \
  "Photorealistic photograph of a cozy child's bedroom late at night: in the softly out-of-focus foreground, a small pair of young hands with loosely interlaced fingers is held up between a warm amber bedside lamp and the pale blue wall; instead of a simple finger shape, the cast shadow on the wall is a photoreal, razor-sharp silhouette of a huge snarling wolf, ears pinned back, jaws open, individual fur edges readable within the shadow, magnified across the wall and into the ceiling corner so it towers over the room; the real hands glow warm and gentle by comparison, creating an eerie contrast between innocent source and monstrous shadow; on the rumpled sheets below sit a worn teddy bear and a half-open storybook, a tiny nightlight glowing near the door; warm lamp amber versus cool moonlit blue palette, shallow depth of field, 35mm lens at f/1.8, hyper-detailed textures, intimate yet slightly unsettling mood, cinematic photorealism." \
  "GLM 5.3 Flash Think max" "The Wolf Game"

# --- Kimi Instant ---
queue_job 41 \
  "A meticulously arranged cluster of twisted wire hangers, coiled metal springs, and broken clock parts scattered across a polished white marble gallery floor, illuminated by a single museum track light suspended from the ceiling at a forty-five degree angle, their combined shadow projected onto the pristine white wall behind them forming the hyper-detailed silhouette of a classical portrait of a woman in profile with elaborate flowing hair, photorealistic, exhibition-grade installation photography, stark high-contrast lighting, sharp shadow edges with soft penumbra, clean minimalist gallery space with exposed concrete ceiling, medium shot capturing both the chaotic metal objects in the foreground and the elegant shadow portrait dominating the background wall." \
  "Kimi Instant" "Shadow Portrait in Wire"

queue_job 42 \
  "A teenage boy running across a sun-scorched desert salt flat at late afternoon, his arms stretched wide and one leg kicked behind him in a joyful sprint, his elongated shadow stretching twenty feet across the cracked white earth transforming into the unmistakable shape of a large raptor bird in flight with individual feather details visible in the shadow silhouette, photorealistic, warm golden hour sunlight from camera left creating long dramatic shadows, dust kicking up from his bare feet, vast empty horizon line, wide environmental shot with the small figure and massive bird-shadow as the focal point, cinematic composition, subtle lens flare at the edge of frame." \
  "Kimi Instant" "The Bird That Was a Boy"

queue_job 43 \
  "A breakfast table scene at early morning with a ceramic coffee mug, a hardshell reading glasses case, a folded newspaper, and a stainless steel spoon arranged casually on a pale oak wood surface, lit by dawn sunlight streaming through a kitchen window from the right, their combined shadow cast onto the white plaster wall behind forming the detailed profile of a howling wolf with the spoon's curve becoming the snout and the newspaper's folded edge forming the raised ear, photorealistic, domestic interior setting, soft warm morning light with gentle shadow gradients, fine wood grain texture visible, shallow depth of field keeping the wall shadow in sharp focus, cozy yet surreal atmosphere, still life composition." \
  "Kimi Instant" "Kitchen Table Revelation"

queue_job 44 \
  "A construction worker in a yellow hard hat and orange safety vest standing on steel scaffolding twenty stories up, arms raised high holding a heavy wrench above his head in a gesture of triumph, his massive shadow cast by harsh midday sun onto the side of an unfinished concrete building facade below, the shadow intersecting with the building's own grid of shadows from scaffolding poles creating an abstract geometric pattern where the human silhouette becomes integrated into a larger architectural crosshatch, photorealistic, industrial setting, bright overhead sun creating razor-sharp black shadows against pale gray concrete, wide shot from an adjacent building showing both the small figure on the scaffolding and the monumental shadow pattern on the wall, documentary photography style." \
  "Kimi Instant" "Monumental Gestures"

queue_job 45 \
  "An elderly woman with silver hair sitting in a vintage burgundy velvet armchair, her weathered hands clasped in her lap and her face turned gently toward a large window covered in intricate handmade lace curtains, afternoon sunlight filtering through the floral lace pattern projecting complex shadow ornamentation onto her face and hands making her skin appear decorated with delicate floral filigree, the shadows following every wrinkle and contour of her aged skin with remarkable precision, photorealistic, soft diffused late afternoon light, rich warm tones, intimate close-up framing focusing on the hands and lower face, shallow depth of field with the lace curtain slightly out of focus in the background, quiet contemplative mood, fine detail in fabric texture and skin pores." \
  "Kimi Instant" "Lace and Legacy"

# --- Deepseek Think Search ---
queue_job 46 \
  "An eerie, photorealistic still life of a gavel, an inkwell with a single quill, and a dusty law book arranged on a polished mahogany surface. Cast from a single, unseen desk lamp positioned low and to the left, the objects' shadows stretch and merge across the wooden grain, forming the unmistakable silhouette of a howling wolf's head, complete with a snout and perked ears, as if the objects themselves are transmuting into a spectral beast. The lighting creates deep, high-contrast shadows and a moody, cinematic atmosphere, shot on a 50mm lens with a shallow depth of field, focusing on the photorealistic textures of the wood and leather." \
  "Deepseek Think Search" "The Auctioneer's Lament"

queue_job 47 \
  "A dramatic, wide-angle shot capturing a solitary ballet dancer in a flowing white tutu, executing a grand jete in a sun-drenched, abandoned industrial warehouse with high, vaulted ceilings. A single, powerful beam of afternoon sunlight cuts through a grime-caked window, casting her shadow onto the gritty, concrete floor. In a striking twist of lighting physics, the shadow is not the dancer's reflection but instead depicts a crouching, isolated figure, arms wrapped around its knees, embodying a stark emotion of solitude and despair that completely reverses the dancer's own expression of joyful athleticism, creating a poignant visual dichotomy." \
  "Deepseek Think Search" "The Dancer's Double"

queue_job 48 \
  "An extreme macro, exhibition-grade photograph of a single, polished white marble sphere resting on a brilliant white, matte surface. A soft, diffused overhead light creates a barely visible, soft shadow beneath the sphere, but the true focal point is the sphere itself, which acts as a convex mirror. On its reflective surface, the distorted, warped shadow of the photographer and the studio lights are captured, creating a complex, abstract miniature world contained within the sphere. The lighting is studio-perfect and clinical, emphasizing the photorealistic textures of the marble and its minute reflections, resulting in a quiet, minimalist, and intellectually engaging composition." \
  "Deepseek Think Search" "The Macro in the Marble"

queue_job 49 \
  "A painterly, photorealistic depiction of an elderly man in a worn trench coat, sitting alone on a park bench at dusk in a bustling city plaza. The setting sun, positioned directly behind him, casts a long, imposing shadow that stretches across the cobblestones. However, his shadow does not mimic his static posture; instead, its silhouette is that of a tall, slender figure striding forward confidently, holding a briefcase, embodying the ambition and relentless energy of the city around him. The interplay of warm, golden-hour light illuminating the man's weary face against the deep, cool, lengthening shadows of the cityscape creates a contemplative and powerful street photography aesthetic." \
  "Deepseek Think Search" "The City's Silhouette"

queue_job 50 \
  "A studio portrait of a focused, middle-aged sculptor with a chisel and mallet in hand, working on a large block of raw, gray marble. A single, intense spotlight from a tall studio window illuminates the scene, casting the shadow of the sculptor and his block onto the back wall. The shadow on the wall is not of the block, but of the finished, smooth, and classical sculpture of a female bust that the sculptor is aiming to create, effectively projecting his artistic vision into reality as a ghostly, ephemeral form. The lighting is dramatic and chiaroscuro, highlighting the dust particles in the air and the photorealistic textures of the marble dust on his hands and apron." \
  "Deepseek Think Search" "The Sculptor's Studio"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Late afternoon golden hour sunlight spilling through a vintage lace curtain, casting intricate overlapping floral and geometric shadow patterns across a weathered wooden window sill, a half-empty ceramic mug and a single dried lavender sprig resting on the surface, their soft elongated shadows blending into the larger lace design, photorealistic, shallow depth of field, warm soft rim lighting, subtle dust motes floating in the sunbeam, muted neutral color palette, exhibition grade fine art photography." \
  "ERNIE 5.1" "Silent Window Sill Shadow"

queue_job 52 \
  "A curated arrangement of seemingly unrelated everyday objects including a bent metal spoon, a spool of thread, small glass marbles, and a folded sheet of paper placed on a plain white gallery wall plinth, a single sharp spotlight positioned at a low angle behind the collection, their combined merged shadows forming the perfectly recognizable silhouette of a leaping deer, clean crisp shadow edges, no visible harsh glares on the objects, minimalist gallery lighting, high contrast, hyperrealistic, museum exhibition quality." \
  "ERNIE 5.1" "Unexpected Object Shadow Art"

queue_job 53 \
  "A young person mid-stride running across an empty sun-dappled urban sidewalk at golden hour, their body slightly out of frame at the top edge of the shot, their long stretched dynamic shadow fully taking over the lower two thirds of the frame, the shadow's arms outstretched and legs bent in clear running motion, small scattered leaf shadows overlapping the edges of the human shadow, rough concrete texture visible under the shadow, warm low sun lighting, candid photorealistic street photography, soft natural contrast." \
  "ERNIE 5.1" "Running Street Shadow"

queue_job 54 \
  "A plain white ceramic teacup sitting upright on a dark wooden table under a single direct overhead spotlight, the shadow cast directly beneath it defying expectation to show the clear detailed silhouette of a flying bird with outstretched wings, the hidden thin curved wire structure tucked just out of direct sight between the light and the cup, sharp clean shadow edges, deep moody low key lighting, subtle soft reflections on the table surface, hyperrealistic, quiet surreal fine art aesthetic." \
  "ERNIE 5.1" "Reversed Teacup Shadow Illusion"

queue_job 55 \
  "Two friends pausing mid-step on an old concrete outdoor staircase as the sun dips below the horizon, their two separate shadows stretching far ahead on the steps in front of them and merging perfectly at the tip to form the shape of a single open heart, soft fading blue and orange dusk ambient light, long soft shadow edges, weathered chipped paint on the stair risers, photorealistic, warm gentle mood, natural unposed composition." \
  "ERNIE 5.1" "Dusk Staircase Double Shadow"

# --- LongCat Think search ---
queue_job 56 \
  "A single beam of intense sunset light cuts through a dusty studio window, striking an arrangement of ordinary objects on a weathered oak table. A glass paperweight rests beside a half-peeled apple and a crumpled silk scarf. These three mundane items project a single, enormous shadow onto a slightly textured plaster wall twenty feet behind. The shadow is not a simple outline; it's an intricate, photorealistic depiction of a slender, ballerina-like giraffe in mid-pirouette, its delicate legs formed by the curve of the apple peel, the body by the refracted light through the paperweight, and the flowing scarf creating the illusion of a tutu dissolving into shadow. The light is golden, warm, and directional, casting long, soft-edged shadows with rich tonal gradations. Shallow depth of field blurs the foreground objects slightly, drawing the eye entirely to the monumental, magical shadow figure on the wall beneath a faint lens flare where light hits the window pane." \
  "LongCat Think search" "Shadow Symphony of Desk Objects"

queue_job 57 \
  "A low-angle photorealistic photograph captures a lone sprinter in the final, desperate lunge for a finish line during the magic hour. Positioned at the far end of a cinder track, long, morning-like shadows stretch impossibly long from behind the athlete, racing along the dark ash surface toward the camera. The runner, a woman in a sleek competition suit, is caught completely horizontal in a straddle lean, her torso silhouetted against a blazing, low sun that is partially obscured by a distant industrial silo. Her elongated shadow stretches for fifty meters on the ground, a distorted, action-focused version of her that appears to use a discarded javelin's reflection as a spear. Dust is suspended in warm, slanted light rays, adding texture and atmosphere to the granular, hyper-realistic shadow and making the scene feel both epic and frozen in time." \
  "LongCat Think search" "Runner Against the Setting Sun"

queue_job 58 \
  "An exhibition-grade shadow art installation in a pristine white gallery. A chaotic but deliberate assortment of items is suspended at varying heights from the ceiling by almost invisible wires: a carrot, a hand-thrown ceramic mug, a broken wristwatch, and a brass skeleton key. Under precisely aimed pinspot lights from multiple angles, their shadows converge and intermix flawlessly on a gleaming, polished concrete floor. The composite shadow is not a random mess but forms a stunningly detailed, three-dimensional-feeling portrait of a mythical griffin in repose, the carrot becoming a flame-like mane in the shadow, the watch gears creating intricate eye texture. The lighting is cool, crisp, and clinical, creating razor-sharp shadow edges with zero spill, while subtle reflections on the polished floor mirror the floating objects above." \
  "LongCat Think search" "Alchemy of the Mundane"

queue_job 59 \
  "A dimly lit, atmospheric photo inside an old wooden boathouse. The subject is a single, large basswood oar resting diagonally against a rain-streaked window. On the sunlit sandy hill beyond the window, the oar's shadow casts not the expected oar shape but the unmistakable, hyper-realistic shadow of a giant, pike-like fish fossil in high relief. The fossil is defined by the nicks, wood grain, and handle shape of the oar, which in the shadow appear as fine bone details. Late afternoon, diffused cloud-filtered light is the sole source, creating long, soft shadows with low contrast. The scene has a quiet, mysterious, and melancholic earth-toned mood, with floating dust motes caught in the narrow beams of light near the oar." \
  "LongCat Think search" "Whispering Reversal"

queue_job 60 \
  "Abstract architectural shadow play at noon in a modern city square. The hard sunlight bleaches onto geometric polished granite cubes that serve as public seating. Between them are thin, precisely angled slices of Corten steel, acting as sharp shadows. These physical objects, together with their razor-sharp cast shadows and bright highlights, form a seamless, tessellated pattern of cubes, planes, and stark diagonal lines across multiple levels. It resembles a constructivist painting, with the deep, dark azure shadows contrasting intensely against the bright white and orange stone, dissecting the composition in a bold, graphic, and optically engaging rhythm unreadably cold at first glance." \
  "LongCat Think search" "Urban Tessellation"

# --- MiniMax M3 ---
queue_job 61 \
  "A young woman in a cream linen dress sits hunched on a worn wooden stool against a pale plaster wall, her head dropped into her hands in quiet despair, while her cast shadow on the wall behind her is a confident dancer caught mid-leap with arms thrown wide and one leg kicked high in joyful abandon, lit by a single warm tungsten bulb from screen-left so the shadow stretches large and dramatically expressive, photorealistic editorial portrait, shallow depth of field, golden hour interior mood, subtle 35mm film grain, soft vignette, melancholic yet hopeful atmosphere." \
  "MiniMax M3" "The Puppet"

queue_job 62 \
  "A flat museum-white gallery wall illuminated by a single low-angle spotlight raked across the floor, on the floor sits a carefully composed still life of ordinary household objects — a wooden hair comb, a silver fork, a twisted wire, a dried fern frond, a wine glass, a short length of chain, a bent dessert spoon — whose combined overlapping shadows on the wall resolve unmistakably into the silhouette of a galloping horse mid-stride with mane streaming behind, photorealistic installation art documentation, crisp sharp shadow edges, museum-grade neutral lighting, 4K archival clarity, minimalist gallery atmosphere, contemplative mood." \
  "MiniMax M3" "Shadow Garden"

queue_job 63 \
  "A vast empty white salt flat at golden hour stretches to the horizon beneath a warm amber and cool blue gradient sky, at the far edge stands a single tiny human figure with arms folded, while the figure's enormous elongated shadow races across the entire foreground in dramatic foreshortening, the shadow frozen in mid-run with a long coat flying behind and arms swinging wide even though the source figure stands perfectly still, photorealistic cinematic composition, very low camera angle nearly grazing the cracked salt surface, anamorphic widescreen framing, contemplative and quietly surreal mood." \
  "MiniMax M3" "The Stalker"

queue_job 64 \
  "Two people — a man in a long dark wool coat and a woman in a faded red knit sweater — stand three feet apart on a rain-slicked cobblestone alley beneath the cone of a single buzzing sodium-vapor streetlamp, neither touching, both gazing down at their own shoes, while their two separate silhouettes on the wet pavement merge seamlessly into a single embracing figure with arms wrapped tightly around each other and foreheads pressed together, photorealistic night street photography, subtle long-exposure motion blur on distant taillights, noir atmosphere, muted teal and amber sodium palette, reflections of the streetlamp shimmering in the puddles." \
  "MiniMax M3" "Confession Booth"

queue_job 65 \
  "A man in a vintage brown tweed suit and scuffed oxford shoes stands at the base of a tall sun-bleached concrete wall on a warm summer afternoon, his real body relaxed with both hands tucked in his pockets and shoulders dropped, but his cast shadow has detached and floats several feet up the wall in a horizontal sprinting pose with arms pumping, as if the shadow has escaped him and is climbing away, the man tilts his head up to look at his own runaway shadow with quiet bewilderment and parted lips, photorealistic midday hard sunlight, razor-sharp shadow edges, mid-century Italian street photography aesthetic, warm ochre and pale terracotta tones, wry and dreamlike mood." \
  "MiniMax M3" "Doppelganger's Mirror"

echo "✅ All 65 jobs queued in scheduler"
