#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Ai Art 46 - photographic negative space. Empty space as the subject
#        itself or as a powerful composition tool directing attention,
#        aesthetically pleasing and tasteful. No bottom-margin numeral marker
#        in this theme.
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+46+-+negative+space
# Structure: 12 models x 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------

# --- Sonnet 5.5 Max ---
queue_job 1 \
  "A quiet architectural photograph of a single vintage red chair standing alone on a vast pale concrete floor inside a nearly empty modern gallery, positioned slightly left of center with the chair facing toward the open right side of the frame. The enormous uninterrupted expanse of cool off-white floor and softly textured wall dominates the composition, creating strong photographic negative space that makes the chair feel isolated yet intentional. Long gentle morning shadows extend behind the chair, adding depth without competing with the subject. Soft directional window light creates subtle tonal gradients across the empty surfaces, while the red upholstery provides the only strong color accent. Minimalist fine-art photography, restrained palette, delicate natural texture, balanced asymmetrical composition, realistic materials, elegant editorial atmosphere, carefully controlled exposure, subtle film grain, quiet contemplative mood." \
  "Sonnet 5.5 Max" "Solitary Red Chair"

queue_job 2 \
  "A cinematic coastal photograph of a small white lighthouse standing alone on a rocky shoreline near the far left edge of the image, surrounded by an immense pale blue-gray sea and an expansive overcast sky. The lighthouse is tiny compared with the surrounding emptiness, emphasizing scale and using negative space as the dominant visual element. A narrow line of dark rocks leads gently toward the lighthouse while most of the frame remains open water and softly layered clouds. The horizon sits low, leaving a vast field of luminous sky above the subject. Diffused dawn light creates soft gradients rather than harsh shadows, with subtle atmospheric haze reducing distant detail. Fine-art landscape photography, understated natural colors, realistic weathered textures, refined composition, calm solitude, elegant visual simplicity, gentle filmic contrast, serene and contemplative editorial aesthetic." \
  "Sonnet 5.5 Max" "Lighthouse in the Distance"

queue_job 3 \
  "An editorial fashion photograph of a lone woman in a long black coat standing near the extreme bottom-right corner of a monumental warm beige architectural wall, seen from a slightly distant perspective. She stands upright in profile, looking toward the enormous empty wall that occupies most of the frame, leaving a dramatic field of uninterrupted negative space above and to her left. Her small human scale contrasts with the massive geometric architecture, making the empty surface feel like an intentional visual object. Soft late-afternoon sunlight grazes the wall, revealing subtle concrete texture and creating a delicate gradient of warm tones. The woman's silhouette remains crisp but understated, with minimal accessories and natural posture. Contemporary fine-art photography, minimalist architectural composition, muted colors, sophisticated fashion editorial mood, realistic texture, restrained contrast, quiet introspection, carefully balanced visual tension." \
  "Sonnet 5.5 Max" "Woman Beneath the Vast Wall"

queue_job 4 \
  "A poetic photograph of a single person holding a bright red umbrella while walking alone along an enormous empty sandy beach, positioned near the lower center-left of the composition. The person is small and partially silhouetted, while the vast wet sand, pale mist, and soft gray sky dominate the image, creating powerful photographic negative space. A thin reflective strip of water mirrors the muted figure and umbrella without distracting from the emptiness. The shoreline curves gently through the lower portion of the frame, providing a subtle compositional guide toward the distant horizon. Soft overcast coastal light produces diffuse reflections and delicate tonal transitions, with the red umbrella serving as the sole saturated color. Fine-art documentary photography, minimalist landscape composition, realistic atmospheric haze, tasteful desaturated palette, quiet melancholy, elegant visual restraint, subtle film grain, strong sense of scale and solitude." \
  "Sonnet 5.5 Max" "Red Umbrella on Empty Beach"

queue_job 5 \
  "A minimalist winter photograph of a single leafless tree standing alone near the lower-left portion of a broad snow-covered field, its delicate branches reaching upward into an enormous uninterrupted pale gray sky. Most of the composition is empty atmosphere, emphasizing negative space as an active visual element rather than simple background. The tree casts a very soft elongated shadow across the snow, while faint tracks curve through the foreground and disappear before reaching it. Gentle winter light creates almost monochromatic shades of white, silver, and muted blue-gray, with subtle texture visible in the snow and fine branch detail. The horizon remains low and understated, giving the sky overwhelming visual weight and making the solitary tree appear fragile yet purposeful. Fine-art landscape photography, refined minimalist composition, realistic natural detail, soft diffused illumination, restrained tonal contrast, elegant Scandinavian editorial aesthetic, calm silence, contemplative mood, subtle analog film texture." \
  "Sonnet 5.5 Max" "Tree Against an Empty Winter Sky"


# --- Gemini 3.6 Flash ---
queue_job 6 \
  "A minimal minimalist photograph capturing a solitary dark cedar tree positioned off-center in the lower right third of the frame. Surrounding the lone tree is vast, soft white fog that fills the remaining canvas, creating an expansive, completely uncluttered negative space. The ethereal mist gently dissolves the horizon, leaving only subtle, light-gray gradient shifts that draw immediate focus to the crisp, detailed silhouette of the cedar's delicate branches. High contrast between the dark bark and the glowing white background emphasizes isolation and calmness. Soft diffusion of ambient overcast morning light creates a clean, peaceful atmosphere, perfect for a balanced square composition." \
  "Gemini 3.6 Flash" "Solitary Cedar in Fog"

queue_job 7 \
  "A minimalist high-angle photograph showing a tiny white sailboat gliding near the top right corner of the frame. The vast majority of the image is occupied by deep, uniform azure ocean water that functions as a striking dark negative space. Soft, subtle ripple textures on the liquid surface break the monochrome blue without distracting from the small boat, which leaves a delicate white foam wake behind it. Direct, brilliant midday sunlight casts a subtle highlight along the vessel's hull, making the miniature subject stand out sharply against the immense, quiet expanse of calm open sea." \
  "Gemini 3.6 Flash" "Sailing Vessel on Endless Blue"

queue_job 8 \
  "An aesthetic minimalist architectural-style landscape photograph featuring a sharp, sweeping crest of a smooth golden sand dune cutting diagonally across the bottom left corner. The rest of the image consists of a massive, perfectly seamless sky filled with a pale dusty blue hue that acts as dominant negative space. Crisp late-afternoon side lighting casts a deep, clean shadow along one edge of the sand ridge, while the fine grain texture on the lit side remains sharp and defined. The immense empty sky occupies nearly eighty percent of the canvas, guiding the viewer's eye along the elegant curve of the sand line." \
  "Gemini 3.6 Flash" "Dune Edge against Clear Sky"

queue_job 9 \
  "A minimalist conceptual indoor photograph depicting a dark, architectural interior dominated by a large, featureless black wall that creates negative space across three-quarters of the scene. Near the center, a single square recessed window lets in a bright beam of natural daylight, casting a distinct, sharp geometric quadrilateral light patch onto the polished floor. The extreme contrast between the rich, deep shadows and the vibrant square of illumination highlights the simplicity of space and light. The composition remains pristine and uncluttered, framing silence and geometry within a balanced square layout." \
  "Gemini 3.6 Flash" "Minimalist Modernist Window Frame"

queue_job 10 \
  "A calm minimalist wildlife photograph depicting a single grey heron standing motionless in the bottom left section of a completely quiet body of water. The smooth water surface reflects a hazy, pale gray sky, acting as a soft, continuous canvas of pale negative space that fills almost the entire composition. Tiny, barely visible concentric rings expand in thin lines around the bird's legs, breaking the quiet mirror finish of the pond. Soft, overcast winter light diffuses evenly across the environment, rendering the detailed plumage of the heron as a sharp, elegant focal point against the empty white and light-gray space." \
  "Gemini 3.6 Flash" "Heron in Still Winter Water"


# --- ChatGPT ---
queue_job 11 \
  "A quiet architectural photograph of a single vintage red chair standing alone on a vast pale concrete floor inside a nearly empty modern gallery, positioned slightly left of center with the chair facing toward the open right side of the frame. The enormous uninterrupted expanse of cool off-white floor and softly textured wall dominates the composition, creating strong photographic negative space that makes the chair feel isolated yet intentional. Long gentle morning shadows extend behind the chair, adding depth without competing with the subject. Soft directional window light creates subtle tonal gradients across the empty surfaces, while the red upholstery provides the only strong color accent. Minimalist fine-art photography, restrained palette, delicate natural texture, balanced asymmetrical composition, realistic materials, elegant editorial atmosphere, carefully controlled exposure, subtle film grain, quiet contemplative mood." \
  "ChatGPT" "Solitary Red Chair"

queue_job 12 \
  "A cinematic coastal photograph of a small white lighthouse standing alone on a rocky shoreline near the far left edge of the image, surrounded by an immense pale blue-gray sea and an expansive overcast sky. The lighthouse is tiny compared with the surrounding emptiness, emphasizing scale and using negative space as the dominant visual element. A narrow line of dark rocks leads gently toward the lighthouse while most of the frame remains open water and softly layered clouds. The horizon sits low, leaving a vast field of luminous sky above the subject. Diffused dawn light creates soft gradients rather than harsh shadows, with subtle atmospheric haze reducing distant detail. Fine-art landscape photography, understated natural colors, realistic weathered textures, refined composition, calm solitude, elegant visual simplicity, gentle filmic contrast, serene and contemplative editorial aesthetic." \
  "ChatGPT" "Lighthouse in the Distance"

queue_job 13 \
  "An editorial fashion photograph of a lone woman in a long black coat standing near the extreme bottom-right corner of a monumental warm beige architectural wall, seen from a slightly distant perspective. She stands upright in profile, looking toward the enormous empty wall that occupies most of the frame, leaving a dramatic field of uninterrupted negative space above and to her left. Her small human scale contrasts with the massive geometric architecture, making the empty surface feel like an intentional visual object. Soft late-afternoon sunlight grazes the wall, revealing subtle concrete texture and creating a delicate gradient of warm tones. The woman's silhouette remains crisp but understated, with minimal accessories and natural posture. Contemporary fine-art photography, minimalist architectural composition, muted colors, sophisticated fashion editorial mood, realistic texture, restrained contrast, quiet introspection, carefully balanced visual tension." \
  "ChatGPT" "Woman Beneath the Vast Wall"

queue_job 14 \
  "A poetic photograph of a single person holding a bright red umbrella while walking alone along an enormous empty sandy beach, positioned near the lower center-left of the composition. The person is small and partially silhouetted, while the vast wet sand, pale mist, and soft gray sky dominate the image, creating powerful photographic negative space. A thin reflective strip of water mirrors the muted figure and umbrella without distracting from the emptiness. The shoreline curves gently through the lower portion of the frame, providing a subtle compositional guide toward the distant horizon. Soft overcast coastal light produces diffuse reflections and delicate tonal transitions, with the red umbrella serving as the sole saturated color. Fine-art documentary photography, minimalist landscape composition, realistic atmospheric haze, tasteful desaturated palette, quiet melancholy, elegant visual restraint, subtle film grain, strong sense of scale and solitude." \
  "ChatGPT" "Red Umbrella on Empty Beach"

queue_job 15 \
  "A minimalist winter photograph of a single leafless tree standing alone near the lower-left portion of a broad snow-covered field, its delicate branches reaching upward into an enormous uninterrupted pale gray sky. Most of the composition is empty atmosphere, emphasizing negative space as an active visual element rather than simple background. The tree casts a very soft elongated shadow across the snow, while faint tracks curve through the foreground and disappear before reaching it. Gentle winter light creates almost monochromatic shades of white, silver, and muted blue-gray, with subtle texture visible in the snow and fine branch detail. The horizon remains low and understated, giving the sky overwhelming visual weight and making the solitary tree appear fragile yet purposeful. Fine-art landscape photography, refined minimalist composition, realistic natural detail, soft diffused illumination, restrained tonal contrast, elegant Scandinavian editorial aesthetic, calm silence, contemplative mood, subtle analog film texture." \
  "ChatGPT" "Tree Against an Empty Winter Sky"


# --- Grok fast ---
queue_job 16 \
  "A solitary weathered wooden fishing boat rests motionless on a vast mirror-still lake at dawn, positioned in the lower left third of the frame while expansive empty water and soft gradient sky occupy the remaining two-thirds as pure negative space, the pale misty horizon line barely dividing the two empty planes, gentle ripples around the boat's hull the only disturbance, cool blue-gray tones fading into warm peach light on the distant edge, high-resolution photographic style with shallow depth of field isolating the boat, clean minimalist composition that lets the surrounding void pull the eye toward the small vessel and convey quiet isolation." \
  "Grok fast" "Negative Horizon Solitude"

queue_job 17 \
  "A single vibrant green maple leaf floats suspended against a seamless expanse of pure soft white background, centered slightly off to the right with abundant empty space surrounding it on all sides, the leaf's delicate veins and serrated edges sharply detailed under even diffused studio lighting that casts a faint soft shadow beneath, the negative space itself becoming the dominant compositional element that frames and elevates the tiny organic form, ultra-clean photographic still-life aesthetic with perfect tonal neutrality and precise focus on the leaf's translucent texture." \
  "Grok fast" "Balanced Leaf and Void"

queue_job 18 \
  "A solitary figure in a long dark coat walks slowly away from the viewer along a narrow empty pier that stretches into thick white fog, the person small and centered low in the lower half while the upper two-thirds dissolve into featureless luminous mist that erases horizon and sky, soft volumetric light filtering through the fog creating gentle gradients of gray, the vast negative space of fog acting as both environment and compositional force that isolates the walker and draws attention to their solitary path, atmospheric photographic style with muted desaturated palette and subtle film grain." \
  "Grok fast" "Lone Walker in Fog"

queue_job 19 \
  "A simple white ceramic coffee cup with a thin gold rim sits alone near the bottom edge of a large seamless matte black surface that extends endlessly in every direction, the cup's curved handle and soft steam rising upward the only details, dramatic single-source side lighting casting a long elegant shadow across the empty expanse, the overwhelming dark negative space surrounding the small object turning emptiness into the primary subject that guides the eye and emphasizes quiet contemplative stillness, refined product-photography aesthetic with high contrast and razor-sharp focus." \
  "Grok fast" "Ceramic Cup on Infinite Table"

queue_job 20 \
  "A lone white seagull glides with wings fully extended in the upper right corner of an immense clear azure sky that fills the entire remaining frame with uninterrupted pure blue gradient fading toward the horizon, no clouds or land visible, soft natural daylight illuminating the bird's feathers and casting a faint shadow on its underwing, the vast empty sky functioning as active negative space that isolates the bird and creates a sense of boundless freedom and scale, clean high-key photographic composition with crisp detail on the subject against the infinite void." \
  "Grok fast" "Bird Against Open Sky"


# --- Copilot Smart ---
queue_job 21 \
  "A vast pale sand dune occupies the lower edge of the frame while an immense uninterrupted sky fills nearly the entire composition, a solitary traveler in dark clothing standing far from camera near the horizon line, tiny and motionless, the empty sky acting as the dominant subject and visual weight of the image, minimalist fine art photography, subtle wind textures on sand, soft golden-hour light, muted beige and blue palette, impeccable balance between scale and solitude, ultra-clean composition, contemplative atmosphere, high-end medium format photography, realistic detail, elegant use of photographic negative space directing all attention toward the distant figure." \
  "Copilot Smart" "Silent Dune Horizon"

queue_job 22 \
  "An overhead view of a calm white tabletop with a single black ceramic cup placed near one corner, the remaining surface completely empty and pristine, the negative space forming the primary visual element and creating tension through asymmetry, studio still-life photography, soft diffused daylight, delicate shadows, premium editorial aesthetic, minimalist design sensibility, refined textures, crisp focus, subtle tonal transitions, gallery-quality composition where emptiness becomes an object in itself and guides the eye directly to the cup." \
  "Copilot Smart" "The Shape of Absence"

queue_job 23 \
  "A tiny sailboat drifting across a dark tranquil sea beneath an enormous moonlit night sky, the boat placed close to the lower edge while expansive empty darkness dominates most of the frame, long-exposure photography, gentle reflections on water, deep navy tones, cinematic atmosphere, delicate moon glow, serene and poetic mood, luxury fine art print style, exceptional visual restraint, the vast negative space creating emotional impact and emphasizing isolation, scale, and stillness." \
  "Copilot Smart" "Moonlit Ocean Silence"

queue_job 24 \
  "A minimalist architectural interior with smooth concrete walls, a single rectangular window casting a bright shaft of sunlight across the room, no furniture and no clutter, most of the scene occupied by clean shadowed surfaces, architectural photography, geometric precision, soft dust particles visible in sunlight, subtle gray tones, elegant modern design, museum-like calm, the empty room serving as the true subject while light directs attention through carefully controlled negative space, sophisticated and aesthetically pleasing composition." \
  "Copilot Smart" "Window of Light"

queue_job 25 \
  "A pristine snow-covered landscape stretching endlessly in every direction, nearly all of the frame composed of pure white snow and soft overcast sky, a single vivid red umbrella resting alone near the edge of the composition, minimalist fine art photography, high-key exposure, delicate snowfall, gentle atmospheric depth, clean monochromatic environment interrupted by one striking focal point, tasteful color contrast, tranquil winter mood, masterful use of negative space where emptiness amplifies the visual importance of the small isolated object." \
  "Copilot Smart" "Red Umbrella in Snow"


# --- Mistral ---
queue_job 26 \
  "A minimalist fine-art photograph of a humpback whale tail fluke rising from calm open ocean, shot from a high aerial drone perspective directly above, the tiny dark fluke placed in the bottom left third of the frame while the rest of the image is vast uninterrupted pastel-grey water with soft gradient light, the immense empty water surface acts as the dominant subject, gentle sun-glint ripples radiate outward from the fluke, soft diffused overcast lighting, muted monochromatic palette, serene contemplative mood, medium-format film emulation, extremely clean composition with generous negative space directing all attention to the whale." \
  "Mistral" "Negative Space No 1, Lone Whale"

queue_job 27 \
  "A fine-art photograph of a single human figure in a flowing dark coat walking across an immense white salt flat, the tiny figure placed low in the frame at the lower right corner, above and around the figure stretches an enormous seamless pale sky of soft white and pale blue occupying nearly the whole image, the emptiness itself feels like a tangible weight, subtle film grain, natural soft daylight, quiet melancholic atmosphere, long horizontal emptiness evoking solitude, high-end gallery print aesthetic, sharp figure against infinite void." \
  "Mistral" "Negative Space No 2, Desert Wanderer"

queue_job 28 \
  "A minimalist photograph of a single bright red balloon floating in a completely empty soft grey sky, the balloon is a small vivid dot positioned in the upper left area, the remaining ninety percent of the frame is smooth atmospheric gradient negative space in tones of silver and warm cream, a faint whisper of fog below, the blank atmosphere functions as the true subject, clean uncluttered composition, natural diffused light, editorial stillness, subtle color contrast between the red and neutral field, contemplative modern art mood, crisp focus on the balloon texture." \
  "Mistral" "Negative Space No 3, Red Balloon"

queue_job 29 \
  "A quiet interior photograph of a woman reading a book beside a large bare window, she sits on the right side of the frame lit by soft natural window light, while the left two-thirds of the image is a vast plain white wall of soft shadow gradient, the empty wall dominates the composition and creates visual silence around her, muted warm neutral tones, shallow depth of field, gentle side lighting shaping her profile, linen curtain edge barely visible, calm intimate mood, high-key aesthetic, fine-art photography, the wall's blankness balances and frames her presence." \
  "Mistral" "Negative Space No 4, Window Reader"

queue_job 30 \
  "A minimalist architectural photograph of a lone dark circular doorway arch set against an immense smooth sand-colored plaster wall, the small arch positioned near the lower right of the frame, the surrounding flat textured wall fills nearly the entire image as luminous empty space, a single thin diagonal shadow line crossing the blank field, harsh warm Mediterranean sunlight, earthy beige and umber palette, the unadorned wall surface reads as the main subject, strong geometric simplicity, editorial travel photography style, tranquil abstract stillness, tack-sharp texture detail." \
  "Mistral" "Negative Space No 5, Arch Silhouette"


# --- Qwen 3.8 Max Thinking ---
queue_job 31 \
  "A cinematic photograph dominated by negative space: a single black umbrella held by a small, distant figure standing on an empty, rain-slicked plaza, positioned in the lower-left third of the frame, while the vast upper area is filled with a smooth, fog-shrouded pale gray sky. The figure is small and crisp against the enormous emptiness, shoulders slightly turned, motionless, so the viewer's eye is pulled immediately to this tiny focal point. Soft diffuse light from an overcast sky, no harsh shadows, subtle reflections stretching beneath the umbrella, faint rain streaks visible only near the figure. Minimal composition, muted palette of charcoal, slate, and misty white, fine grain texture, shot as if with a 50mm lens at f/2.8, shallow atmosphere haze, elegant and contemplative, award-winning street photography aesthetic, perfectly balanced empty space functioning as the true subject." \
  "Qwen 3.8 Max Thinking" "Solitary Umbrella in Rain"

queue_job 32 \
  "A refined minimalist nature photograph where negative space carries the composition: a single bare tree branch with a few delicate twigs entering from the bottom-right corner, reaching diagonally upward, against an immense, cloudless winter sky of soft pale cream-blue gradient filling the entire frame. No horizon, no ground, only the branch silhouette in dark warm brown against the vast emptiness, with one tiny dried leaf clinging near the tip. Gentle directional morning light rakes across the branch, revealing subtle bark texture while the sky remains smooth and empty, creating quiet tension between the small organic detail and the overwhelming open space. Shot in the style of large-format fine art photography, ultra clean exposure, delicate tonal range, meditative and tasteful, the empty sky functioning as a powerful compositional object that directs all attention to the fragile branch." \
  "Qwen 3.8 Max Thinking" "Lone Branch Against Winter Sky"

queue_job 33 \
  "An architectural interior photograph built entirely on negative space: one small red vintage wooden chair with a curved back and turned legs, placed off-center in the lower-right region of a vast empty white room with smooth plaster walls, polished pale concrete floor, and no furniture whatsoever. A single shaft of soft daylight from an unseen window falls diagonally across the floor, its edge crisp, illuminating the chair while the upper two-thirds of the frame remains serene, featureless white wall that reads as pure silence. The chair casts one long gentle shadow stretching toward the lower-left corner. Neutral white balance with the chair's deep crimson as the sole color accent, museum-like stillness, ultra minimal styling, gallery quality fine art photography, the emptiness itself acting as a sculptural presence that magnifies the small object's character and scale." \
  "Qwen 3.8 Max Thinking" "Red Chair in White Room"

queue_job 34 \
  "A moody fine art seascape photograph dominated by negative space: a tiny lone sailboat with a single white triangular sail, positioned low in the frame slightly left of center, gliding across an enormous expanse of deep indigo water that merges into a heavy overcast sky of charcoal gray, the horizon line placed very low so the vast sky swallows ninety percent of the image. The boat is barely larger than a thumbnail, crisp and legible, its wake a faint pale thread trailing behind, the water surface rendered almost textureless through long-exposure smoothing so the emptiness feels liquid and infinite. Soft ambient light with no sun visible, subtle tonal gradient from darker top to lighter horizon, cinematic desaturated palette of navy, steel, and bone white, contemplative and painterly, the boat functioning as a single punctuation mark within the overwhelming quiet space." \
  "Qwen 3.8 Max Thinking" "Sailor on Open Sea"

queue_job 35 \
  "A graphic minimalist photograph where negative space is the star: one small black swallow perched on a thin horizontal telephone wire crossing the frame at the lower third, wings folded, head turned slightly to the left, silhouetted against an enormous smooth sky at golden hour blending from soft apricot near the horizon to pale dusty rose above. Nothing else in the frame, no clouds, no buildings, no landscape, only the bird, the taut wire with a gentle sag, and boundless warm emptiness that glows with diffused evening light. The bird occupies a tiny fraction of the composition yet commands total attention through placement on a rule-of-thirds intersection. Shot on a telephoto lens compressing the sky into a flat color field, clean edges, delicate feather detail, serene Japanese-inspired aesthetic of ma, tasteful and quietly powerful, the empty sky functioning as luminous negative space that gives the small subject monumental presence." \
  "Qwen 3.8 Max Thinking" "Single Bird on Telephone Wire"


# --- GLM 5.3 Think Max ---
queue_job 36 \
  "Fine art minimalist photograph of a single person standing small in the lower right of the frame, dwarfed by an enormous plain terracotta-orange plaster wall that fills nearly the entire square image. The person is a woman in a flowing dark teal dress, seen from behind at eye level, walking slowly along the base of the wall. The wall surface is smooth matte plaster with subtle texture, and one thin diagonal shadow falls from the top left corner, giving the empty expanse a quiet sculptural presence. A pale concrete strip of ground occupies only the bottom tenth of the frame. Soft late-afternoon sunlight creates a gentle warm gradient across the wall, no clouds, no other objects. Shot on medium format film with an 80mm lens, sharp focus on the figure, smooth tonal falloff, subtle grain. The vast uncluttered negative space presses all attention onto the tiny figure, evoking solitude and calm in an editorial fine-art aesthetic." \
  "GLM 5.3 Think Max" "Vermilion Silence"

queue_job 37 \
  "Fine art monochrome photograph of a lone pine tree standing in shallow still water, placed along the left third of the frame and rising only halfway to the top edge. Dense white fog fills the entire upper two thirds as a vast field of pure emptiness, with the tree's upper branches dissolving softly into the mist. Below, a glassy lake surface mirrors a faint ghost of the trunk. Desaturated palette of pale grays and soft whites, flat overcast light, long exposure smoothing the water to silk. Shot from a low, close-to-water perspective with a 50mm lens, fine film grain, gentle tonal gradations, no visible horizon line, no other trees, birds, or objects. The overwhelming empty fog acts as the true subject, compressing all visual weight onto the small dark tree and evoking stillness, isolation, and quiet breath. High-key minimalism with a gallery print aesthetic." \
  "GLM 5.3 Think Max" "Vessel of Fog"

queue_job 38 \
  "High-key minimalist photograph of a single black bird gliding in flight, wings fully extended in a horizontal glide, positioned small in the lower left quadrant of the frame. The remaining ninety percent of the image is a seamless featureless white sky, softly luminous and slightly warm toward the top, reading as an immense field of empty light. The bird is rendered as a crisp silhouette with clearly defined feather edges on both wings and a fanned tail. Captured with a 400mm telephoto lens at 1/2000 second, perfectly sharp, no clouds, no power lines, no horizon. Soft diffused daylight from behind the camera flattens the background into pure white with a faint creamy gradient. The vast negative space surrounds the tiny subject like silence around a single note, instantly directing the eye to the bird and evoking freedom and solitude. Fine art nature photography, museum print quality, clean edges, subtle grain." \
  "GLM 5.3 Think Max" "One Note in the Silence"

queue_job 39 \
  "Minimalist desert photograph at golden hour: an endless sea of smooth rippled sand in warm beige and apricot tones fills almost the entire frame. A single tiny human figure in a dark flowing robe walks along a distant dune crest positioned just below the upper edge, casting one long elegant shadow that draws a thin diagonal line across the empty slope. Low side light from the right rakes across gentle wind ripples, giving the bare sand a soft sculptural texture while keeping it calm and uncluttered. No plants, no rocks, no horizon beyond a hazy pale sky blending into the dune line. Shot from a high vantage point with a 135mm lens compressing the distance, sharp focus on the figure, smooth gradient tonal falloff. The overwhelming emptiness of the dune becomes the subject itself, channeling all attention toward the lone traveler and evoking vastness, silence, and quiet perseverance. Editorial fine-art travel aesthetic, muted warm palette, subtle film grain." \
  "GLM 5.3 Think Max" "The Silent Crossing"

queue_job 40 \
  "Fine art interior photograph of a dark, nearly black room. In the center of the frame stands a tall empty arched doorway opening onto pure blinding white light, and this luminous empty arch is the only subject of the image. The glowing arch shape is perfectly symmetrical and occupies the middle third of the composition, its radiance bleeding softly onto the charcoal walls and stone floor around it. The surrounding darkness fills the rest of the frame, rich with the faint texture of aged plaster, so the bright void of the open doorway reads as a solid glowing object floating in shadow. No furniture, no people, no decor, only the architecture of light and absence. Captured on a tripod with a 35mm lens, exposed one stop under to deepen the shadows, natural daylight flooding from beyond the doorway. Quiet contemplative mood where the emptiness itself becomes the object, pulling the viewer's gaze toward the light. Gallery exhibition quality, deep blacks, luminous whites, subtle film grain." \
  "GLM 5.3 Think Max" "Threshold of Light"


# --- Deepseek Vision ---
queue_job 41 \
  "A tiny lone figure wearing a bright yellow raincoat stands at the lower right of an immense snow-covered field, back turned, arms relaxed, facing a distant pale horizon. The vast unbroken snowfield fills most of the frame, becoming a quiet negative space that acts as the main subject. Photographic, medium-format film aesthetic, 35mm lens, deep depth of field, soft overcast light, subtle grain, cool white and muted blue shadows. The figure occupies only a small area, while the empty snow sweeps upward and left, guiding the viewer's eye across the stillness. Minimal, tasteful, high-key composition, crisp details in the coat and snow texture, serene winter atmosphere. The negative space is not empty but a powerful compositional presence, balancing isolation and calm." \
  "Deepseek Vision" "Snowfield Silhouette"

queue_job 42 \
  "A single closed red umbrella lies tilted on wet dark asphalt at the center-left, its glossy fabric catching soft rain reflections. The surrounding empty pavement extends to every edge, vast and mirror-like, forming a deep photographic negative space that dominates the frame. Photographic, top-down perspective, 50mm lens, shallow depth of field, twilight lighting, subtle blue and amber reflections, fine film grain. The umbrella is small but vivid, while the dark wet asphalt becomes a silent object of its own. Composition places the umbrella off-center, with broad empty pavement drawing attention inward. Minimal urban scene, tasteful, moody, aesthetic, with the negative space directing focus to the solitary red shape. Clean composition, no distracting elements." \
  "Deepseek Vision" "Red Umbrella on Wet Asphalt"

queue_job 43 \
  "A solitary swallow perches on a thin horizontal wire at the far left edge of the frame, tiny and still, while an enormous pale morning sky fills nearly the entire image. The vast empty sky is the negative space and the true subject, soft gradient from peach near the horizon to cool blue above. Photographic, telephoto lens, deep depth of field, natural dawn light, delicate grain, minimal composition. The bird occupies a small area at the left, and the expansive emptiness extends right and upward, directing the viewer's attention to the tiny living detail. Peaceful, tasteful, high-key, with subtle cloud texture and atmospheric perspective. The negative space feels expansive, quiet, and intentional, balancing solitude with openness." \
  "Deepseek Vision" "Swallow and Empty Sky"

queue_job 44 \
  "A person in a dark wool coat walks through a sunlit concrete corridor, positioned small at the far right, mid-stride, facing away. A massive blank white wall fills the left and center of the frame, with a single narrow shadow falling diagonally. The wall's empty surface is photographic negative space, acting as a solid compositional object. Photographic, wide-angle 28mm lens, deep depth of field, harsh afternoon sunlight, high contrast, crisp architectural lines, muted beige and charcoal palette. The figure is isolated by the vast wall, and the empty area guides the eye from left to right toward the walker. Minimal, modern, tasteful, with subtle concrete texture and geometric balance. Negative space creates tension, scale, and quiet drama." \
  "Deepseek Vision" "Concrete Corridor Walker"

queue_job 45 \
  "A single white dandelion seed floats above a dark polished table at the upper right, delicate filaments catching a soft spotlight. A large expanse of deep black negative space fills the lower and left areas, becoming a velvet-like object that anchors the composition. Photographic macro still life, 100mm macro lens, shallow depth of field, dramatic chiaroscuro lighting, subtle dust motes, rich blacks, fine grain. The seed is tiny and luminous, while the surrounding darkness directs attention to its fragile structure. Minimal, elegant, tasteful, with gentle reflections and soft falloff. The empty space feels intentional and powerful, balancing delicate detail against vast quiet. Photographic negative space as both subject and frame." \
  "Deepseek Vision" "Dandelion Seed on Black"


# --- ERNIE 5.1 ---
queue_job 46 \
  "Soft matte black ceramic mug resting on the far left edge of a pale oak table, the entire remaining 70% of the frame filled with smooth, dusted off-white empty wall, faint cool north light spilling across the surface casting a single thin 2cm long shadow, shot on 35mm Kodak Portra 400, shallow depth of field, quiet muted tones, no extra objects, clean uncluttered framing that lets the empty wall hold equal visual weight to the mug itself." \
  "ERNIE 5.1" "Minimalist Window Still Life with Negative Space"

queue_job 47 \
  "A single weathered grey granite boulder sits at the absolute bottom right corner of the frame, the rest of the wide empty frame filled with soft pale foggy ocean water stretching to a hazy horizon, golden hour dawn light wrapping gently around the rock's edges, fine grain medium format film texture, no other land, birds or debris in sight, the vast empty water space acting as the primary compositional element guiding the eye directly to the small quiet rock." \
  "ERNIE 5.1" "Solitary Coastal Rock at Low Tide"

queue_job 48 \
  "A crisp off-white linen napkin draped loosely over a single thin brass hook mounted on the far left side of a tall plain plaster wall, 80% of the frame is completely unadorned soft warm off-white empty wall, soft diffused overcast daylight filtering in from an unseen side window, subtle soft shadow falling 10cm below the napkin, shot on medium format Ilford HP5, gentle monochrome tonal range, no furniture, decor or distractions anywhere in the frame." \
  "ERNIE 5.1" "Single Hanging Linen Napkin in Empty Room"

queue_job 49 \
  "One well-worn deep navy blue cloth bound book lying flat at the very top edge of a wide warm reclaimed pine floor, the entire lower two thirds and right half of the frame is bare smooth empty floor planks, low angled late afternoon sunlight stretching a long faint shadow across the empty wood, shot on 35mm film, warm natural wood tones, no other objects, marks or clutter, the expansive empty floor space feels intentional and holds its own quiet presence next to the small book." \
  "ERNIE 5.1" "Lone Vintage Hardcover Book on Wooden Floor"

queue_job 50 \
  "A single thin dried pale yellow wildflower stem standing upright at the exact bottom left corner of the frame, the remaining 90% of the frame filled completely with soft uniform pale grey overcast sky, no clouds, birds or other features visible in the sky, soft even diffused daylight, shot on 120mm medium format, gentle muted pastel tones, the massive empty sky space dominates the composition and makes the tiny single stem feel far more intentional and striking than it would in a crowded frame." \
  "ERNIE 5.1" "Sparse Wildflower Stem Against Overcast Sky"


# --- LongCat Deep search ---
queue_job 51 \
  "A single leafless oak tree stands centered in the lower third of a vast, fog-shrouded meadow, its dark, gnarled branches sharply defined against a seamless expanse of pale, desaturated gray mist that fills the upper two-thirds of the frame. Soft, diffused overcast light eliminates harsh shadows, creating a quiet, ethereal atmosphere with subtle tonal gradations in the fog. The negative space of the mist acts as a visual void, emphasizing the tree's solitary presence and evoking a sense of calm isolation. Fine art landscape photography, muted monochromatic palette, minimalist composition, no other objects or distractions in the scene." \
  "LongCat Deep search" "Lone Tree in Misty Field"

queue_job 52 \
  "A stark white concrete wall fills the entire frame, interrupted only by a single, razor-sharp diagonal shadow cast by an unseen architectural overhang, dividing the composition into two distinct geometric planes of pure white and soft, cool gray. The shadow edge is perfectly crisp, creating a bold abstract shape that becomes the sole subject. Bright, direct midday sunlight creates high contrast between the illuminated and shaded areas, with no texture or imperfections visible on the smooth wall surface. The negative space of the white wall dominates the frame, directing full attention to the interplay of light and geometric form. Ultra-minimalist architectural photography, clean lines, high-key lighting, square composition emphasizing spatial tension." \
  "LongCat Deep search" "Minimalist Architectural Shadow"

queue_job 53 \
  "A tiny human figure in a dark coat walks along the lower edge of an immense, empty beach at low tide, positioned at the left intersection of the rule of thirds. The upper three-quarters of the frame are occupied by a seamless, overcast pale gray sky that merges almost imperceptibly with the wet, reflective sand at the horizon line. Soft, shadowless diffused light creates a muted, contemplative mood, with the figure's small scale emphasizing the overwhelming vastness of the surrounding negative space. The empty sky and sand form a continuous, textureless void that isolates the subject and evokes profound solitude. Fine art street photography, desaturated tones, minimalist composition, no other people, objects, or landmarks visible." \
  "LongCat Deep search" "Solitary Figure on Vast Beach"

queue_job 54 \
  "A single white goose feather floats perfectly still on the surface of a glass-still, dark indigo lake, positioned slightly off-center in the lower half of the frame. The upper half is filled with a deep, uniform twilight sky that gradients subtly from near-black at the top to a faint indigo at the horizon, with no clouds or stars. The feather's delicate, intricate barbs are sharply in focus, creating a stark textural contrast against the smooth, infinite negative space of the water and sky. Soft, cool ambient light from the twilight creates a serene, meditative atmosphere, with the feather appearing to hover in a void. Minimalist nature photography, monochromatic blue palette, extreme negative space, no ripples or other elements disturbing the water's surface." \
  "LongCat Deep search" "Single Floating Feather"

queue_job 55 \
  "A single, perfectly curved sand dune ridge cuts diagonally across the lower third of the frame, its smooth, wind-sculpted surface rendered in soft, warm beige tones with subtle shadow gradations. The upper two-thirds are filled with a vast, cloudless pale azure sky that gradients from a deeper blue at the top to almost white at the horizon. The dune's elegant, minimalist curve is the sole subject, with the immense negative space of the sky emphasizing its graceful shape and the desert's overwhelming emptiness. Bright, clear midday sunlight creates soft, even illumination on the dune with no harsh shadows. Fine art landscape photography, warm and cool color contrast, extreme minimalism, no vegetation, people, or wildlife present." \
  "LongCat Deep search" "Desert Dune Negative Space"


# --- MiniMax M3.1 flash preview ---
queue_job 56 \
  "A single unglazed clay vessel, small and matte terracotta, resting alone on the crest of a smooth pale sand dune that occupies only the lower third of the frame. The dune surface is finely wind-rippled, softly modeled by low golden-hour light raking from the left side. The vessel sits slightly off-center, its rounded silhouette casting one long clean shadow that stretches to the right and fades at the edge of the sand. Everything above the dune is an enormous empty sky, a soft cream-to-peach gradient with no clouds, holding the majority of the frame as deliberate breathing room. Medium format film rendering, shallow tonal contrast, fine sand texture, muted desert palette, delicate grain. Minimalist fine-art photography, no people, no text, uncluttered and calm." \
  "MiniMax M3.1 flash preview" "Quiet Vessel, Vast Dune"

queue_job 57 \
  "A lone woman in a pale linen dress stands in the far corner of a vast white plaster room, small within the frame, arms relaxed at her sides, head turned slightly toward a tall window just out of view. Soft daylight from that window washes the empty wall in a gentle gradient and casts her faint elongated shadow diagonally across the bare floorboards. Everything else is emptiness: unfurnished floor, a single seam, bare walls. Wide-angle composition with the subject anchored in the lower corner, expansive unoccupied wall filling the upper and right portions of the frame. Overcast daylight, desaturated ivory and bone palette, 35mm perspective, subtle grain, contemplative architectural fine-art photography, no text, nothing else in the room." \
  "MiniMax M3.1 flash preview" "Figure in White Room"

queue_job 58 \
  "A weathered wooden jetty extends from the bottom center of the frame into a hazy, almost invisible horizon over flat calm sea. One tiny distant figure stands motionless at the far end, facing away, coat still, providing the only human scale. Sky and water merge into one soft silver-grey plane, the horizon a delicate low line. Negative space dominates the composition: unbroken, empty water on either side of the pier frames the solitary silhouette. Overcast diffused light, low contrast, muted palette of pewter, pale sand, and faded teal. Smooth long exposure flattens the sea surface, 50mm, fine grain, quiet minimalist seascape, contemplative, uncluttered, no text." \
  "MiniMax M3.1 flash preview" "The Long Jetty"

queue_job 59 \
  "The empty space itself is the subject: a deep rectangular alcove recessed into a sunlit white plaster wall, its interior resting in cool shadow, a single small ceramic disc placed on the far bottom ledge of the recess. Hard afternoon sun strikes the surrounding wall, producing one clean bright band so the void reads as a deep, deliberate frame within the frame. The alcove is positioned on a vertical third, with a large plain expanse of empty wall to the left. Raking light, crisp geometric edges, warm bone-white against soft umber shadow, medium format detail, subtle grain, architectural still-life photography, meditative and restrained, no people, no text." \
  "MiniMax M3.1 flash preview" "The Alcove"

queue_job 60 \
  "A nearly black concrete facade at dusk fills the frame, with a single warm-lit window glowing in the upper left quadrant while the rest of the building dissolves into shadow. The negative space is the vast dark wall: bare board-formed concrete, faint horizontal seams, one thin projecting ledge. That small, specific pool of amber light anchors the composition and makes the surrounding emptiness read as scale and stillness. A narrow sliver of deep indigo sky sits above the roofline. Long exposure, low noise, restrained palette of charcoal, indigo, and a single warm window. Quiet cinematic urban minimalism, crisp architecture, no people, no text." \
  "MiniMax M3.1 flash preview" "Blue Hour Facade"


echo "✅ All 60 jobs queued in scheduleri"
