#!/usr/bin/env bash
set -euo pipefail

MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Abstract 3D wallpapers — non-photorealistic digital 3D renders,
#        flowing/geometric/crystalline forms, premium desktop/tablet/phone
#        wallpaper aesthetic
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+45+-+Abstract+3D+wallpapers
# Structure: 13 models × 5 prompts = 65 tasks total
# ---------------------------------------------------------------------------

# --- Sonnet 5 high ---
queue_job  1 \
  "Abstract 3D digital render of molten liquid chrome ribbons twisting and flowing through empty space, hyper-polished metallic surfaces reflecting soft cool light in shades of ice blue, silver, and deep steel gray. The forms curve and coil like frozen mercury caught mid-motion, some sections smooth and mirror-like while others ripple with fine wave textures. Subtle volumetric fog drifts behind the central shapes, catching faint rim light along the edges. Studio-style three-point lighting with a soft key light from the upper left and cool blue fill from the right, creating gentle gradients across the metal. Deep charcoal to near-black background keeps focus on the flowing forms, with a few small floating chrome spheres scattered at varying depths for parallax interest. Composition stays loosely centered with generous negative space on all sides so it reads well whether cropped wide or tall. Octane render quality, ultra-smooth surfaces, physically-based reflections, subtle chromatic aberration on highlights, clean and minimal, high production value, no clutter, no text, no logos. Calm, elegant, futuristic mood, aesthetically pleasing and screen-friendly." \
  "Sonnet 5 high" "Liquid Chrome Drift"

queue_job  2 \
  "Abstract 3D render of thick molten glass forming an organic blooming shape, like a flower or coral caught mid-transformation, glowing from within with warm amber, deep orange, and molten gold light. The glass surface is thick and viscous, with soft internal caustics and light scattering through translucent folds, occasional bubbles trapped inside catching tiny highlights. The main form sits slightly off-center, tendrils and petal-like extensions curling outward and thinning into delicate glass threads that fade into a warm dark background of muted maroon and near-black. Subtle embers or floating light particles drift in the space around the sculpture, softly out of focus. Lighting is warm and directional, as if from a low sunset angle, casting long soft shadows and rich rim highlights along the glass edges. Surface detail includes fine cracks and swirl patterns inside the glass without breaking its glow. Cinema 4D and Octane render aesthetic, physically accurate refraction, smooth gradients, cinematic warmth, no text, no logos, no photorealistic skin or objects. Composition kept loose and balanced with breathing room around the form so it works across square, portrait, and widescreen crops. Cozy, luxurious, quietly dramatic mood." \
  "Sonnet 5 high" "Molten Glass Bloom"

queue_job  3 \
  "Abstract 3D digital artwork featuring a cluster of soft, semi-transparent spheres resembling soap bubbles, each surface shimmering with pastel iridescence shifting between lilac, mint, blush pink, and pale gold. The spheres vary in size and float at different depths, some crisp and in focus in the foreground, others softly blurred toward the back, creating gentle depth of field. Thin, delicate film-like surfaces show faint rainbow interference patterns and soft specular highlights. Background is a smooth pastel gradient moving from soft lavender at the top to warm cream near the bottom, kept simple and airy so it never competes with the bubbles. A few tiny sparkle particles and soft light flares drift through the scene for extra polish. Lighting is bright, soft, and diffused, like an overcast studio setup, avoiding harsh shadows. Overall composition is loosely centered with open space around the edges, letting the piece crop gracefully into square, tall, or wide formats. Rendered in a clean, modern 3D style with smooth subsurface scattering and soft ambient occlusion, no text, no logos, no realistic objects. Mood is light, dreamy, calming, and cheerful, ideal as a fresh, elegant wallpaper for any screen." \
  "Sonnet 5 high" "Iridescent Bubble Field"

queue_job  4 \
  "Abstract 3D render of large faceted crystal shards suspended in a dark, moody void, their sharp geometric surfaces glowing with vivid neon purple and electric cyan internal light. The crystals overlap and fracture into smaller angular fragments that drift outward, some catching bright specular highlights while others sit in soft shadow, giving strong depth and contrast. A thin haze of dark violet fog fills the background, occasionally pierced by faint beams of colored light suggesting hidden light sources behind the formation. Reflective facets bounce color between the crystals, creating small pockets of magenta and teal where the two main hues blend. The overall palette stays close to near-black, deep purple, and glowing cyan-magenta accents for a moody, high-contrast, futuristic feel. Composition centers the largest cluster with smaller shards receding into the darkness at varying depths, leaving clean empty space around the edges for flexible cropping across square, portrait, and ultra-wide formats. Rendered with sharp physically-based glass and crystal shading, subtle bloom on the brightest edges, cinematic lighting, no text, no logos, no characters. Sleek, moody, sci-fi inspired atmosphere, striking enough to feel premium on any desktop, tablet, or phone screen." \
  "Sonnet 5 high" "Neon Crystal Fracture"

queue_job  5 \
  "Abstract 3D digital render of soft, matte clay-like waves and rounded blob forms layered across the frame like a gentle sculpted landscape. The shapes have a smooth, chalky, non-reflective surface finish in a soothing pastel palette of dusty peach, sage green, powder blue, and warm sand, blending softly where the forms overlap. Rounded ridges and shallow valleys create a minimal, almost topographic pattern, lit from a high soft angle that produces gentle, diffused shadows and subtle ambient occlusion in the creases. No harsh reflections or glossy highlights, keeping the material feel soft and tactile like unglazed ceramic or modeling clay. The composition spreads gently across the frame with a slightly higher concentration of forms toward the lower portion, leaving open, airy space near the top and sides so it adapts cleanly to square, tall, and wide crops. Background fades into a very soft off-white to pale blue gradient, keeping everything calm and uncluttered. Rendered in a clean, modern minimalist 3D style, smooth geometry, gentle color grading, no text, no logos, no photorealistic elements. Overall mood is warm, cozy, and quietly cheerful, the kind of soft, undemanding scene that feels pleasant to look at all day on a desktop, tablet, or phone." \
  "Sonnet 5 high" "Pastel Clay Waves"


# --- Gemini 3.5 Flash ---
queue_job  6 \
  "3D abstract digital render of fluid obsidian ribbon-like shapes floating in a dark zero-gravity void. The smooth, glossy black surfaces reflect vibrant neon cyan, deep magenta, and ultraviolet light gradients, creating rich specular highlights and soft chromatic aberration. Intricate geometric fractures and tiny glowing particles drift through the composition. High contrast visual depth, ray-traced reflections, subsurface scattering, ambient occlusion, sleek minimalist aesthetic, ultra-clean digital art style, smooth volumetric light shafts cutting through delicate glass geometry, cinematic ambient color harmony designed for a modern desktop background." \
  "Gemini 3.5 Flash" "Liquid Obsidian and Neon Chromatic Flow"

queue_job  7 \
  "Abstract 3D digital architectural geometry featuring overlapping frosted glass shards and translucent crystal pyramids. Light refracts through the faceted structure, splitting into soft pastel spectrums of iridescent peach, mint green, lavender, and champagne gold. Layered depth with soft depth of field, gentle ray-traced shadows, and subtle caustic light patterns cast onto a clean, neutral gradient background. Volumetric soft glow, delicate frosted textures, clean minimal layout, sophisticated spatial composition, high-end 3D graphic design render, perfect balanced lighting and smooth color transitions." \
  "Gemini 3.5 Flash" "Prismatic Crystallized Lattice Architectural Waves"

queue_job  8 \
  "Abstract 3D digital landscape composed of smooth, sweeping topographic wave curves made from matte ceramic and liquid chrome materials. Deep royal blue and emerald green hues dominate the undulating ribbons, with thin glowing lines of molten gold tracing the contour edges. Floating translucent spheres and subtle volumetric fog float between the flowing layers, creating an expansive sense of depth and scale. Elegant lighting setup with soft key lights and subtle rim lighting, highly detailed surface shaders, meditative dark aesthetic, balanced contrast, modern luxury graphic design render." \
  "Gemini 3.5 Flash" "Bioluminescent Topographic Silk Terrain"

queue_job  9 \
  "Dynamic 3D abstract visual art piece featuring interlocking matte pastel tubes, sleek gold wires, and floating metallic toruses suspended in an airy studio environment. Soft gradient background shifting smoothly from warm coral to pale indigo. Soft ambient occlusion shadows create a strong tactile feel of physical depth and form. Clean geometric alignment, precise rendering of brushed metal and soft-touch plastic shaders, playful yet refined compositional flow, subtle bloom effect around warm light sources, contemporary motion-graphics aesthetic, ultra-crisp details." \
  "Gemini 3.5 Flash" "Futuristic Geometric Kinetic Splines"

queue_job 10 \
  "3D abstract digital visual composition featuring suspended, complex polyhedral shapes constructed from gradient-dyed glass and polished brass. Rich gradient transitions from deep warm sunset orange and crimson to deep velvety purple and navy. Thin laser-like light beams intersect the geometry, scattering luminous dust particles and creating intricate caustic patterns in atmospheric fog. Depth of field subtly blurs the background, focusing sharp details on the central floating sculptures. Balanced visual weight, hyper-detailed rendering of light dispersion and material refraction, dramatic dark mode wallpaper style." \
  "Gemini 3.5 Flash" "Volumetric Vapor Wave Polyhedrons"


# --- ChatGPT +think ---
queue_job 11 \
  "A refined 3D abstract digital render for a modern desktop wallpaper, featuring several broad, weightless ribbons flowing through a deep midnight-blue space in elegant overlapping curves. The ribbons have smooth sculptural surfaces with a sophisticated gradient of electric cyan, violet, magenta, and subtle indigo, producing luminous color transitions without looking metallic or photorealistic. Large flowing forms create a strong sense of depth, while smaller translucent loops weave between them. Soft volumetric glow and carefully controlled ambient lighting emphasize the three-dimensional shapes. The composition is spacious and uncluttered, with generous areas of darker negative space suitable for desktop icons. Smooth gradients, polished digital-render aesthetics, elegant abstract geometry, fluid motion, premium futuristic design, harmonious color balance, crisp edges, subtle atmospheric haze, visually calming yet dynamic, high-end generative 3D artwork designed to remain attractive as a computer, tablet, or smartphone background." \
  "ChatGPT +think" "Floating Chromatic Ribbons"

queue_job 12 \
  "A sophisticated 3D abstract wallpaper composed of interconnected translucent geometric structures floating in a dark atmospheric environment. The main forms resemble smooth crystalline tubes, curved polygons, and impossible architectural loops, arranged as an elegant flowing network rather than a literal object. Use a restrained palette of deep charcoal, cobalt blue, luminous turquoise, and small accents of warm coral-orange. The structures should appear like digitally sculpted glass and glowing acrylic, with internal light softly traveling through their surfaces. Add subtle refraction, layered transparency, delicate bloom, and soft shadows, while keeping the image clearly stylized as a premium digital render rather than photorealism. The composition should have a strong central visual flow surrounded by spacious negative space, making it practical as a desktop background. Clean futuristic aesthetics, smooth surfaces, precise geometry, sophisticated lighting, balanced asymmetry, deep dimensionality, minimal visual clutter, elegant gradients, and a luxurious technology-inspired atmosphere." \
  "ChatGPT +think" "Neon Glass Topology"

queue_job 13 \
  "A dreamy 3D abstract digital artwork depicting a series of soft sculptural forms suspended inside an infinite pastel environment. Create large rounded shapes resembling inflated ceramic waves, smooth pebbles, curved platforms, and floating organic loops, arranged as if gravity has been suspended. Use a sophisticated palette of lavender, powder blue, pale peach, soft mint, cream, and subtle pink, with gentle transitions between colors. The objects should have smooth matte and satin surfaces with occasional translucent sections, creating tactile depth without photorealistic textures. Soft diffuse illumination surrounds the forms, producing delicate shadows and subtle ambient glow. The composition should feel peaceful, modern, spacious, and aesthetically refined, with an elegant visual rhythm and plenty of uncluttered background. Premium abstract 3D render, contemporary digital art, smooth gradients, rounded geometry, soft atmospheric depth, minimalism, harmonious pastel colors, sophisticated composition, visually relaxing and suitable as a long-term desktop, tablet, or smartphone wallpaper." \
  "ChatGPT +think" "Pastel Gravity Fields"

queue_job 14 \
  "A dramatic yet elegant 3D abstract wallpaper built around enormous flowing sculptural waves resembling liquid metal frozen in motion. Create layered ribbons and folded surfaces that twist through a dark abstract environment, with smooth polished geometry and controlled reflective highlights. The color palette combines graphite black, deep emerald, midnight teal, and intense aurora-green highlights with occasional hints of electric blue. The forms should look digitally sculpted rather than physically photographed, with exaggerated curves, seamless surfaces, and surreal impossible folds. Use directional lighting to create long luminous highlights along the edges and subtle glowing reflections across the surfaces. Keep the background dark and atmospheric, with faint gradients and soft haze providing depth without distracting from the main shapes. High-end futuristic 3D digital render, sophisticated abstract composition, dramatic depth, flowing geometry, luxurious color grading, elegant negative space, smooth surfaces, visually immersive but uncluttered, designed as a striking premium wallpaper for modern displays." \
  "ChatGPT +think" "Liquid Metal Aurora"

queue_job 15 \
  "A vibrant contemporary 3D abstract composition featuring a monumental smooth sculptural core surrounded by several floating orbital rings and curved geometric fragments. The central form should resemble a softly faceted organic crystal or folded mathematical sculpture, with flowing surfaces transitioning between saturated blue, turquoise, violet, and luminous fuchsia. Around it, thin elliptical rings and ribbon-like structures orbit at different depths, creating a graceful sense of movement and dimensionality. Introduce subtle glowing edges, translucent layers, soft bloom, and carefully balanced studio-style digital lighting. The environment should be a deep gradient space shifting from navy to indigo, with faint atmospheric particles used sparingly. The overall image should feel like premium contemporary digital art: colorful but controlled, futuristic but elegant, energetic without becoming chaotic. Smooth 3D geometry, polished rendering, clean gradients, sophisticated lighting, strong depth, balanced asymmetry, generous negative space, and a visually memorable composition suitable for a stylish desktop, tablet, or smartphone wallpaper." \
  "ChatGPT +think" "Orbiting Color Sculpture"


# --- Grok fast ---
queue_job 16 \
  "A mesmerizing 3D digital render of cascading crystalline geometric forms floating in an infinite void, sharp angular prisms and multifaceted octahedrons interlocking in elegant spiral formations, translucent surfaces refracting soft internal glows of electric cyan, deep violet, and shimmering magenta, smooth polished facets catching subtle light rays that create delicate caustics and prismatic flares across the composition, gentle volumetric fog weaving between the structures adding depth and atmospheric softness, clean minimal background fading into pure black for maximum contrast, highly detailed surface textures with micro-bevels and subtle subsurface scattering, balanced composition suitable for desktop immersion, serene yet dynamic energy, pure abstract digital art style with no realism, cinematic lighting from multiple soft sources, ultra clean render quality emphasizing form and color harmony." \
  "Grok fast" "Ethereal Crystal Cascade"

queue_job 17 \
  "Elegant 3D abstract composition of flowing liquid metal ribbons and undulating metallic sheets twisting through space in graceful organic curves, surfaces gleaming with brushed platinum, molten gold, and iridescent teal gradients that shift under soft directional lighting, subtle ripples and reflective distortions across the fluid forms creating infinite depth, interspersed with hovering polished spheres of varying sizes that catch and bounce light between them, smooth continuous surfaces without harsh edges, gentle ambient occlusion enhancing volume, cool cyan rim lighting outlining the silhouettes against a deep charcoal gradient background, sophisticated and luxurious aesthetic, highly detailed digital render focused on material quality and fluid motion, contemplative and modern desktop wallpaper feel, pure non-photorealistic CGI abstraction." \
  "Grok fast" "Liquid Metal Symphony"

queue_job 18 \
  "Vibrant 3D abstract digital artwork featuring interlocking geometric lattices and blooming polyhedral clusters expanding outward from a central core, sharp clean edges of tetrahedrons, cubes, and dodecahedrons arranged in radial symmetry, surfaces glowing with intense neon pink, electric lime, and deep indigo emissions, soft internal illumination making each face appear lit from within, delicate wireframe overlays and thin connecting beams adding structural elegance, subtle particle haze of glowing dust motes floating between forms, high contrast against pure black void, precise hard-surface modeling with perfect edge definition, balanced negative space for visual breathing room, energetic yet harmonious color palette, polished digital render style emphasizing light emission and geometric purity, ideal abstract desktop background with modern futuristic vibe." \
  "Grok fast" "Neon Geometric Bloom"

queue_job 19 \
  "Dreamlike 3D abstract scene of large translucent gradient orbs and soft volumetric spheres gently overlapping and intersecting in a floating arrangement, each orb filled with smooth color transitions from peach to soft lavender to muted teal, delicate internal light sources creating soft glowing cores and gentle bloom effects, thin ethereal ribbons of light weaving between the forms connecting them in subtle arcs, extremely smooth matte and semi-gloss surface finishes with soft subsurface scattering, calm diffused lighting that eliminates harsh shadows, airy composition with generous empty space, pastel color harmony promoting tranquility, clean digital render without noise or texture grit, peaceful and meditative aesthetic perfect for desktop wallpaper, pure abstract CGI focusing on softness, color gradients, and volumetric presence." \
  "Grok fast" "Soft Gradient Orbs"

queue_job 20 \
  "Sophisticated 3D digital abstract of endless interlocking fractal ribbons and twisting ribbon-like structures stretching across a wide horizontal plane, surfaces finished in matte charcoal with selective metallic copper and sapphire blue accents catching soft side lighting, recursive self-similar patterns that grow more intricate toward the center while remaining clean and readable, gentle curvature and continuous flow creating a sense of infinite expansion, subtle depth of field softening distant elements, cool blue ambient fill light balanced with warm copper highlights, minimalist yet richly detailed forms, elegant negative space framing the main structures, high-end digital art style with precise modeling and refined material response, contemplative and expansive feel ideal for panoramic desktop use, pure non-photorealistic abstraction centered on form, rhythm, and refined color accents." \
  "Grok fast" "Fractal Ribbon Horizon"


# --- Copilot Smart ---
queue_job 21 \
  "A mesmerizing 3D abstract wallpaper featuring interlocking geometric shapes in vibrant neon hues of cyan, magenta, and lime green, floating in a dark void. The composition emphasizes fluid motion, with glowing edges and soft gradients blending into one another, creating a sense of infinite depth. The digital render highlights symmetry and balance, while subtle particle effects add a futuristic shimmer. Designed to be aesthetically pleasing, this artwork evokes energy and creativity, perfect for a dynamic desktop background that feels alive yet harmonious." \
  "Copilot Smart" "Chromatic Geometry Flow"

queue_job 22 \
  "An abstract 3D render of crystalline waves stretching across a surreal horizon, shimmering with iridescent blues, purples, and silvers. The layered structures resemble frozen glass ripples, bending light into dazzling reflections. The wallpaper conveys serenity and elegance, with smooth curves and refracted highlights that suggest both motion and stillness. The interplay of transparency and opacity creates a dreamlike atmosphere, ideal for a calming yet visually striking desktop background." \
  "Copilot Smart" "Crystal Wave Horizon"

queue_job 23 \
  "A futuristic 3D abstract wallpaper inspired by digital circuitry and organic growth, where glowing lines form intricate floral patterns. Electric blues, radiant oranges, and deep violets intertwine, radiating outward like neon petals. The composition balances sharp angular geometry with soft radial symmetry, producing a captivating fusion of technology and nature. The glowing bloom pulses with energy, making it an eye-catching yet soothing digital render for desktops and mobile devices." \
  "Copilot Smart" "Neon Circuit Bloom"

queue_job 24 \
  "A surreal 3D abstract wallpaper featuring molten metallic forms flowing like liquid across a reflective surface. Chrome-like textures in silver, gold, and bronze twist into fluid ribbons, catching highlights and shadows in mesmerizing patterns. The design emphasizes depth and dimensionality, with smooth gradients and shimmering reflections that evoke both strength and elegance. This digital render creates a luxurious, modern aesthetic, perfect for a desktop background that feels bold yet refined." \
  "Copilot Smart" "Liquid Metal Mirage"

queue_job 25 \
  "A hypnotic 3D abstract wallpaper showcasing a swirling vortex of prismatic shards, glowing in radiant rainbow tones. The shards spiral inward, creating a sense of infinite motion and dimensional depth. Light refracts across the surfaces, producing dazzling highlights and soft shadows that enhance the illusion of movement. The composition blends chaos and harmony, offering a vibrant, energetic digital render that transforms any desktop into a portal of color and imagination." \
  "Copilot Smart" "Prismatic Vortex Dream"


# --- Mistral Think ---
queue_job 26 \
  "A mesmerizing 3D abstract composition featuring swirling neon cosmic nebulae in vibrant hues of electric purple, hot pink, and cyan. The scene is filled with glowing particles and ethereal light trails, creating a sense of depth and movement. Intricate geometric shapes float within the nebula, adding structure to the organic flow. The background transitions smoothly from deep black to rich violet, enhancing the otherworldly atmosphere. The overall aesthetic is futuristic and dreamlike, perfect for a desktop or mobile wallpaper." \
  "Mistral Think" "Neon Cosmic Nebula"

queue_job 27 \
  "A stunning 3D abstract wallpaper showcasing intricate fractal geometry in a symphony of metallic gold, silver, and iridescent blue. The fractals expand and twist in a hypnotic dance, with sharp edges and smooth gradients creating a dynamic contrast. Subtle glows and reflections add depth, while a dark, velvety backdrop makes the colors pop. The design balances complexity and elegance, offering a visually captivating experience for any screen." \
  "Mistral Think" "Fractal Geometry"

queue_job 28 \
  "A fluid and dynamic 3D abstract artwork featuring liquid crystal formations in a palette of emerald green, sapphire blue, and amethyst purple. The crystals appear to melt and reform, creating a sense of constant motion. Soft, diffused lighting highlights the translucent surfaces, while scattered light refractions add a magical touch. The composition is both calming and energizing, ideal for a modern and stylish wallpaper." \
  "Mistral Think" "Liquid Crystal Flow"

queue_job 29 \
  "A bold 3D abstract wallpaper inspired by cyberpunk aesthetics, with a glitchy matrix of neon green, electric blue, and fiery orange. The design incorporates fragmented geometric patterns, digital noise, and sharp, angular lines that evoke a high-tech, futuristic vibe. The background is a deep, almost black charcoal, making the vibrant colors stand out. The overall look is edgy and futuristic, perfect for tech enthusiasts." \
  "Mistral Think" "Cyberpunk Glitch Matrix"

queue_job 30 \
  "A vibrant 3D abstract wallpaper featuring holographic prismatic waves in a spectrum of rainbow colors. The waves ripple and intersect, creating a kaleidoscopic effect with shimmering, translucent surfaces. The background is a gradient of soft pastel tones, providing a gentle contrast to the vivid foreground. The design is both playful and sophisticated, making it a versatile choice for any device." \
  "Mistral Think" "Holographic Prismatic Waves"


# --- Qwen 3.7 Plus Thinking ---
queue_job 31 \
  "3D abstract digital render of a desktop wallpaper featuring smooth, flowing liquid chrome and frosted glass geometric shapes intersecting in a mesmerizing composition. Vibrant neon cyan and magenta lighting casting soft, colorful reflections on the glossy, highly polished surfaces. Deep matte black background to make the luminous colors pop intensely. Subtle glowing microscopic particles floating gracefully in the ambient air. High-end octane render style, ray tracing, global illumination, ultra-detailed, smooth color gradients, aesthetic minimalist composition, perfect for a modern PC background, 8k resolution, crisp edges, mesmerizing fluid dynamics, clean and sophisticated visual experience." \
  "Qwen 3.7 Plus Thinking" "Neon Cyberpunk Glass and Fluid"

queue_job 32 \
  "Aesthetic 3D abstract wallpaper design composed of soft, flowing silky ribbons and smooth matte clay-like abstract blobs intertwining gracefully. Gentle pastel color palette featuring soft lavender, mint green, and blush pink hues. Soft, diffused studio lighting creating gentle, natural shadows and a dreamy, calming atmosphere. The textures are a beautiful mix of velvety matte finishes and subtle pearlescent silk sheens. Floating geometric primitives like spheres and toruses scattered softly in the background. Unreal Engine 5 render style, soft focus, beautiful depth of field, highly detailed, soothing visual, clean composition, modern digital art, perfect for a minimalist tablet or smartphone background, bright and airy mood." \
  "Qwen 3.7 Plus Thinking" "Pastel Soft Clay and Silk"

queue_job 33 \
  "Moody 3D abstract digital render featuring towering, minimalist monolithic structures made of dark, heavily textured concrete and brushed metal. Thick volumetric fog weaving through the geometric gaps, creating a mysterious, deep, and atmospheric environment. Subtle, warm amber rim lighting highlighting the sharp edges and intricate contours of the abstract architecture. Deep shadows and striking high contrast. Cinematic lighting, high-end digital art style, octane render, ray-traced reflections, ultra-sharp details, brutalist aesthetic, moody and sophisticated color grading, dark grey and charcoal tones with hints of glowing orange. Ideal for a sleek, professional desktop wallpaper, immersive and grand scale composition." \
  "Qwen 3.7 Plus Thinking" "Dark Monolithic Architecture and Fog"

queue_job 34 \
  "Vibrant 3D abstract wallpaper showcasing intricate, crystalline fractal structures growing outward in a dynamic, explosive composition. Brilliant prismatic light refracting through the translucent crystals, creating a stunning spectrum of vivid purple, electric blue, and shimmering gold colors. Glowing energy cores pulsing at the center of the geometric formations. High-gloss, glass-like materials with sharp, precise edges and flawless reflections. Cinematic volumetric rays piercing through the crystal clusters. Masterpiece digital render, vivid colors, high dynamic range, sharp focus, magical and energetic atmosphere, complex geometry, beautiful light scattering, perfect for a striking gaming or creative desktop background, ultra-detailed textures." \
  "Qwen 3.7 Plus Thinking" "Vibrant Fractal Crystal and Light"

queue_job 35 \
  "Modern retro-futuristic 3D abstract wallpaper featuring a glowing, perspective wireframe grid stretching infinitely into a digital horizon. Floating, perfectly smooth metallic spheres and hollow rings hovering elegantly above the illuminated grid. A vibrant sunset gradient background transitioning seamlessly from deep violet to bright hot pink and neon orange. Subtle lens flares and chromatic aberration adding a nostalgic yet highly modern digital touch. Intense neon glow effects outlining the geometric shapes. High-quality 3D render, synthwave aesthetic, clean vector-like lines, smooth gradients, vibrant and energetic color palette, crisp details, perfect for a stylish and nostalgic PC or tablet background, visually striking and perfectly balanced." \
  "Qwen 3.7 Plus Thinking" "Retro-Futuristic Synthwave Grid and Spheres"


# --- GLM 5.3 Flash Think max ---
queue_job 36 \
  "A mesmerizing 3D abstract wallpaper featuring flowing translucent glass waves with smooth, liquid-like curves, rendered in soft pastel gradients of lavender, baby blue, mint green and blush pink. The translucent surfaces refract gentle light, creating subtle rainbow dispersion and glowing caustics along their edges. Background fades from deep indigo at the bottom to a soft white haze at the top. Silky smooth glossy surfaces, soft studio lighting, global illumination, gentle depth of field. Clean minimalist composition with balanced negative space and a centered subject, staying elegant in any crop. High-end digital 3D render aesthetic, octane render style, ultra smooth, dreamy atmosphere, premium desktop wallpaper, ultra high resolution, masterpiece quality." \
  "GLM 5.3 Flash Think max" "Iridescent Glass Waves"

queue_job 37 \
  "A striking 3D abstract wallpaper of floating geometric crystal clusters, sharp faceted polygons with beveled edges, rendered in polished obsidian black with glowing neon edges in electric cyan and hot magenta. Dramatic rim lighting traces each facet, with volumetric glow and subtle bloom radiating from the crystal cores. Deep charcoal background with a faint radial gradient and tiny floating dust particles catching the light. High contrast cyberpunk-inspired palette, glass and metal material mix, reflective chrome accents. Centered, slightly symmetrical composition with generous negative space around the subject so it crops beautifully in any canvas shape. Clean digital 3D render, octane style, razor-sharp details, futuristic, premium desktop wallpaper aesthetic, ultra high resolution." \
  "GLM 5.3 Flash Think max" "Neon Crystal Cluster"

queue_job 38 \
  "A playful 3D abstract wallpaper featuring soft matte clay shapes, inflated spheres, squishy rounded toruses and gentle pillowy blobs, floating in a calm pastel scene. Color palette of cream white, peach, soft coral, muted sage and warm beige. Subtle fabric-like texture on the matte surfaces, tiny soft contact shadows, gentle ambient occlusion. Background is a seamless pastel gradient from powder pink to vanilla with a large soft-focus glow behind the main cluster. Friendly, cozy, minimalist aesthetic, everything rounded, no sharp edges. Balanced centered composition with airy negative space that adapts gracefully to any canvas shape. Studio softbox lighting, gentle global illumination, trendy 3D illustration style, blender render look, clean adorable wallpaper, high resolution." \
  "GLM 5.3 Flash Think max" "Pastel Clay Blobs"

queue_job 39 \
  "A luxurious 3D abstract wallpaper of molten liquid chrome ribbons twisting through space, mirror-polished metallic surfaces reflecting a gradient environment of burnt orange, deep purple and midnight blue. The flowing metal forms elegant loops and knots with crisp mirror reflections, soft anisotropic highlights and delicate light streaks running along the curves. Dark background gradient from rich aubergine to black, subtle volumetric fog adding depth, faint golden particle sparks floating around. High-end jewelry-commercial rendering aesthetic, ray-traced reflections, physically based materials, cinematic studio lighting with a soft key light from above. Flowing centered composition that stays balanced in any crop. Ultra-detailed glossy digital 3D render, sophisticated premium desktop wallpaper, ultra high resolution." \
  "GLM 5.3 Flash Think max" "Liquid Chrome Ribbons"

queue_job 40 \
  "A serene 3D abstract wallpaper of smooth layered waves resembling silky topographic dunes or stacked paper landscapes, flowing diagonally across the frame. Monochromatic gradient palette shifting from deep teal through aqua to soft seafoam, each layer separated by a thin glowing cream-colored edge light. Matte frosted surfaces with a gentle satin sheen, soft shadows pooling between layers, dreamy atmospheric haze in the distance. Clean background gradient fading from pale mint at the top to darker teal at the bottom. Calm, meditative, minimalist aesthetic with flowing rhythm and generous negative space in the upper third. Balanced composition that adapts gracefully to any canvas shape. Smooth 3D render, soft studio lighting, elegant modern high-resolution desktop wallpaper." \
  "GLM 5.3 Flash Think max" "Teal Layered Dunes"


# --- Kimi Instant ---
queue_job 41 \
  "A dark charcoal void background with sweeping 3D translucent ribbons of electric cyan and hot magenta twisting through infinite space, soft volumetric fog catching the neon glow at their edges, polished glass-like surfaces with subtle chromatic aberration and caustic light refractions, scattered geometric wireframe spheres floating at varying depths, gentle bloom and lens flare on the brightest curves, smooth gradient transitions between cool blue and warm coral, matte metallic floor plane reflecting soft ambient light, cinematic depth of field with foreground elements slightly blurred, clean digital render aesthetic, no photorealism, abstract futuristic wallpaper, serene and hypnotic mood, high contrast between dark negative space and luminous colored forms, subtle film grain texture." \
  "Kimi Instant" "Neon Meridian"

queue_job 42 \
  "Soft pastel dreamscape of floating organic blob shapes in pale peach, lavender, and mint green suspended in a milky white atmosphere, semi-transparent frosted glass material with soft subsurface scattering creating inner glow, gentle overlapping layers creating depth, smooth rounded forms with no sharp edges, delicate caustic patterns cast onto a subtle reflective surface below, airy volumetric haze between objects, soft global illumination with warm light from above, minimal and calming composition with generous negative space, matte and glossy material mix, subtle rainbow iridescence on glass edges, abstract 3D digital art render, clean modern aesthetic suitable for any screen, peaceful and meditative atmosphere, gentle color harmony." \
  "Kimi Instant" "Aurora Glass"

queue_job 43 \
  "Deep obsidian black environment featuring sharp angular crystalline structures emerging from below, faceted surfaces reflecting dramatic saturated gradients of deep violet, burnt orange, and teal, polished mirror-like material with subtle scratches and imperfections for texture, scattered floating polygon shards catching rim light, strong directional lighting from upper left creating long elegant shadows, subtle particle dust floating in light beams, abstract geometric landscape with dramatic perspective leading to vanishing point, high contrast chiaroscuro lighting, metallic and glass hybrid materials, slight chromatic separation on sharp edges, cinematic composition with foreground crystal out of focus, sophisticated dark mode wallpaper aesthetic, moody and contemplative digital render." \
  "Kimi Instant" "Obsidian Prism"

queue_job 44 \
  "Warm golden hour palette of flowing liquid metal waves in bronze, amber, and soft rose gold cascading across the frame, smooth undulating 3D topography with reflective satin finish, subtle anisotropic highlights following the curves, soft ambient occlusion in the wave valleys, distant floating orbs of warm white light creating soft bokeh, gentle gradient sky from pale yellow to soft coral, abstract fluid dynamics frozen in time, polished digital sculpture aesthetic, harmonious warm monochromatic scheme with subtle complementary blue accents in reflections, clean render with physically based materials, elegant and luxurious feel, generous breathing room in composition, uplifting and energizing mood, subtle texture on metal surfaces like brushed aluminum." \
  "Kimi Instant" "Solar Flare"

queue_job 45 \
  "Minimalist arctic-inspired abstract scene with smooth white and pale gray sculptural forms resembling wind-carved ice or soft architectural concrete, soft diffused overcast lighting with no harsh shadows, single accent of pale sky blue and soft periwinkle in subtle gradient panels, gentle rolling hills of matte material meeting a perfectly still reflective surface below creating mirror symmetry, sparse floating geometric rings in frosted glass material, extremely clean and uncluttered composition with vast negative space, soft ambient fog blending horizon into sky, meditative and tranquil atmosphere, premium modern design aesthetic, subtle surface imperfections and micro-texture on matte forms, cool temperature palette, serene and focused mood, abstract 3D render with elegant simplicity." \
  "Kimi Instant" "Arctic Zen"


# --- Deepseek Think Search ---
queue_job 46 \
  "A mesmerizing 3D abstract digital artwork featuring a complex labyrinth of translucent, iridescent glass tubes and organic wave-like structures floating in a soft, ethereal void. The composition is dominated by sweeping, curved ribbons of pastel pink, cyan, and shimmering gold that intertwine and loop around a central, glowing crystalline core. Subtle chromatic aberration and caustic light refractions scatter rainbows across the scene, creating a dreamy, high-end render aesthetic. The background is a gentle gradient of milky white to soft lavender, with volumetric fog adding depth and mystery. Smooth, polished surfaces contrast with matte, velvety textures on smaller floating geometric primitives like dodecahedrons and torus knots. Delicate, floating particles of light drift throughout the frame, enhancing the sense of a serene, futuristic digital utopia. The overall mood is calm, sophisticated, and visually refreshing, making it an ideal desktop background that balances intricate detail with a clean, uncluttered feel. Soft ambient occlusion and global illumination ensure a hyper-realistic render quality that feels both tangible and otherworldly." \
  "Deepseek Think Search" "Ethereal Glass Labyrinth"

queue_job 47 \
  "A dramatic and vibrant 3D abstract wallpaper depicting a surreal, low-poly horizon line where smooth, organic bioluminescent shapes erupt from a dark, cosmic plane. The scene is bathed in intense neon purple, electric turquoise, and fiery orange, with a heavy emphasis on glowing rim lights and deep, contrasting shadows. In the foreground, large, fluid blob-like sculptures with a glossy, wet appearance sit atop a reflective, chrome-like surface, mirroring their vivid colors. Behind them, a series of floating, interconnected wireframe spheres and glowing neon rings ascend into a starry, atmospheric fog. The midground features a dynamic flow of particle trails that mimic a digital aurora borealis, weaving between the abstract forms. The render showcases high-fidelity textures, including microscopic craters on metallic surfaces and a subtle noise grain that adds depth. The wide, expansive composition draws the eye across the canvas, offering a perfect balance between chaotic energy and structured harmony. This piece evokes a futuristic synthwave vibe, filled with luminous depth and a mesmerizing, almost hypnotic visual rhythm, perfect for a dynamic and colorful desktop." \
  "Deepseek Think Search" "Neon Nebula Horizon"

queue_job 48 \
  "A sophisticated, high-contrast 3D abstract composition centered around a collection of perfectly sculpted, matte-finished geometric shapes suspended in a dense, misty void. The palette is a restrained yet rich monochrome scheme, utilizing deep charcoal blacks, smooth mid-tone grays, and stark white highlights, punctuated by a single, striking pop of vivid crimson red on a cascading ribbon. The main subject is a massive, fragmented torus that appears to be breaking apart into smaller, perfectly aligned cubes and octahedrons, all drifting slowly downward through a soft volumetric fog. Dramatic, directional lighting casts long, crisp shadows across the scene, emphasizing the texture and form of each individual polygon. A subtle, low-poly grid pattern lies far below, barely visible through the haze, adding a sense of scale and grounding. The overall aesthetic is clean, architectural, and deeply contemplative, blending surrealism with rigid geometry. Glowing edge lines trace the contours of the main shapes, creating a sleek, sci-fi minimalist vibe. The serene, balanced arrangement and lack of clutter make this an exceptionally calming yet visually striking wallpaper choice." \
  "Deepseek Think Search" "Monochrome Minimalist Forms"

queue_job 49 \
  "An explosive and energetic 3D abstract render showcasing a dynamic collision of fluid simulations and rigid neon structures. The composition features a massive, twisting column of viscous, liquid-like material that splashes and fractures into hundreds of glowing, glassy shards, all set against a deep, immersive midnight blue background. The color scheme is a high-voltage mix of blazing magenta, vivid lime green, and intense electric blue, with each liquid droplet acting as a tiny prism, refracting light in all directions. Interwoven within the fluid chaos are precise, angular wireframe grids and holographic data lines that pulse with a soft, animated glow, giving the image a technological, cybernetic edge. The lighting is dramatic, with multiple key lights creating a complex interplay of reflections and caustics across the glossy surfaces. Floating particles and tiny, glowing orbs add a sense of depth and motion, while a subtle chromatic aberration effect sharpens the futuristic feel. The render quality is pristine, with every splash and ripple captured in stunning detail, resulting in a bold, vibrant, and highly engaging desktop wallpaper that feels alive with digital energy." \
  "Deepseek Think Search" "Cyberpunk Fluid Dynamics"

queue_job 50 \
  "A soft, whimsical, and highly tactile 3D abstract artwork depicting an enchanted, surreal garden composed entirely of smooth, clay-like organic shapes and blooming floral structures. The palette is a soothing blend of pastel mint green, creamy peach, soft dusty rose, and gentle lilac, all bathed in a warm, diffused daylight that creates a cozy, inviting atmosphere. In the center, a large, spiral-shaped succulent-like form unfurls its petals, each one displaying a subtle gradient and a velvety, matte texture that looks incredibly soft to the touch. Surrounding it are smaller, floating bell-shaped blooms and curved, pebble-like stones that hover gracefully in the air, connected by delicate, glowing golden threads. The background is a simple, out-of-focus gradient wash of pale beige and light pink, providing a clean canvas that highlights the intricate details of the main subjects. Soft, rounded drop shadows and gentle ambient occlusion give the scene a tangible, plush toy aesthetic, while tiny, sparkling dust motes float lazily around the forms. The overall composition is balanced, serene, and undeniably charming, blending abstract geometry with organic botany to create a heartwarming and aesthetically pure digital escape." \
  "Deepseek Think Search" "Dreamlike Clay Garden"


# --- ERNIE 5.1 ---
queue_job 51 \
  "3D abstract art desktop wallpaper, smooth translucent geode forms floating in soft color gradients of lavender, pale teal and warm peach, subtle internal crystalline refractions that catch gentle ambient light, matte polished digital render, no sharp edges, balanced negative space optimized for desktop icons, soft depth of field that keeps central shapes calm and uncluttered, faint glowing rim light around each form, clean minimalist aesthetic that feels calm and premium, no photorealistic details, pure digital render style, smooth color transitions that do not distract from daily screen use." \
  "ERNIE 5.1" "Soft Gradient Geode Desktop Wallpaper"

queue_job 52 \
  "3D abstract art desktop wallpaper, delicate glowing wireframe structures weaving through a muted deep indigo nebula space, thin neon lines in soft cyan and muted gold that never overpower the scene, floating low-poly abstract orbs scattered across the frame, soft volumetric fog that adds gentle depth, digital render with clean anti-aliased edges, balanced composition that leaves quiet dark areas for desktop icons, no harsh bright flashes, calm futuristic atmosphere that feels immersive but not overwhelming, smooth gradients between dark space and glowing elements, perfect for long hours of screen use." \
  "ERNIE 5.1" "Glowing Wireframe Nebula Desktop Wallpaper"

queue_job 53 \
  "3D abstract art desktop wallpaper, smooth matte clay-like organic forms slowly morphing across the frame, warm earth tones of terracotta, soft cream and muted sage, gentle overlapping curves that create soft shadow layers, no hard lines or realistic textures, clean digital render with subtle ambient occlusion, plenty of quiet empty space on one side for desktop shortcuts, soft diffused top lighting that gives every shape a calm tangible feel, cozy and grounded aesthetic that works well for work and study screens, smooth surfaces with zero grain or noise." \
  "ERNIE 5.1" "Clay Morph Organic Flow Desktop Wallpaper"

queue_job 54 \
  "3D abstract art desktop wallpaper, large floating abstract prism casting soft dispersed rainbow light across a neutral off-white base, subtle refracted color streaks that are desaturated and gentle, no loud saturated colors, smooth glossy prism surface that catches light softly, faint floating micro light particles in the air around it, clean digital render with soft bloom effect, balanced composition that keeps most of the background calm and unbusy, soft depth that does not interfere with icon visibility, elegant light-focused aesthetic that feels fresh and calm every time you look at the screen." \
  "ERNIE 5.1" "Prism Light Refraction Desktop Wallpaper"

queue_job 55 \
  "3D abstract art desktop wallpaper, simplified low-poly cubist forms floating gently against a soft muted misty background, limited color palette of dusty blue, pale mustard and soft taupe, subtle soft shadows under each geometric shape that create gentle depth, no complex textures or photorealistic details, clean digital render with smooth flat color faces, carefully arranged layout that reserves a large quiet area for desktop icons, soft ambient side lighting that adds subtle dimension without harsh contrast, calm modern aesthetic that stays pleasing even during all-day screen use." \
  "ERNIE 5.1" "Floating Minimal Cubism Desktop Wallpaper"


# --- LongCat 2 Think search ---
queue_job 56 \
  "3D abstract art desktop wallpaper featuring flowing crimson liquid metal ribbons suspended in dark void space, hyper-detailed digital render with dynamic swirling motion, glossy reflective surfaces catching specular highlights, deep burgundy and scarlet color palette with subtle gold metallic accents, smooth organic curves intersecting with sharp geometric fragments, volumetric lighting creating dramatic depth, cinematic composition with central focal point, ultra smooth 3D render style like Octane or Blender Cycles, dark background environment, high contrast lighting, elegant and modern aesthetic suitable for 4K desktop wallpaper." \
  "LongCat 2 Think search" "Crimson Fluid Dynamics"

queue_job 57 \
  "Vibrant 3D abstract wallpaper composed of floating translucent geometric crystal shards in cyan magenta and electric orange, sharp angular facets with glowing neon edges, holographic iridescent material that splits light into rainbow spectrums, softly fusing into dark gradient background with subtle grid pattern, distant bokeh spheres adding depth, digital art render aesthetic that combines precision of CAD with organic psychedelic flow, dynamic arrangement suggesting explosive expansion frozen in time, clean high-tech visual language suitable for modern PC background, sharp focus and highly detailed surface textures." \
  "LongCat 2 Think search" "Neon Geometric Crystals"

queue_job 58 \
  "Pastel-themed 3D abstract digital art wallpaper showcasing undulating silk fabric waves in gradient colors shifting from soft lavender to mint green and baby blue, smooth semi-translucent material floating gracefully in weightless space, soft ambient occlusion shadows adding realism, delicate subsurface scattering mimicking real fabric quality, bright airy composition with plenty of negative space, dreamy and calming atmosphere, rendered with premium 3D software aesthetic, subtle particle dust floating around edges, minimalist yet visually engaging perfect for tablet or phone background, high quality 4K resolution artwork." \
  "LongCat 2 Think search" "Aurora Silk Waves"

queue_job 59 \
  "Cyberpunk-inspired dark 3D abstract wallpaper featuring glowing cyan neon circuitry lines traversing through abstract organic void shapes, dark charcoal environment with intense rim lighting, metallic chrome surfaces reflecting distorted holograms, volumetric light beams piercing through geometric openings, digital glitch aesthetic with subtle pixel displacement effects on edges, high-tech futuristic vibe with emphasis on interconnection and data flow, moody atmospheric lighting with strong contrast between deep shadows and bright accent highlights, detailed render suitable for gaming setup aesthetics." \
  "LongCat 2 Think search" "Cyber Circuit Voids"

queue_job 60 \
  "3D abstract desktop wallpaper depicting floating iridescent soap bubble clusters in space, each sphere showing full-spectrum chromatic aberration and thin-film interference patterns, soft gradient background transitioning from peach to periwinkle, translucent material properties with caustic light refractions, delicate surface tension details and beautiful specular reflections, dreamlike quality with bubbles of varying sizes creating depth through scale, digital art render approach emphasizing material physics and light behavior, clean composition with balanced visual weight, aesthetically pleasing and modern suitable for any device background." \
  "LongCat 2 Think search" "Prismacolor Bubble Universe"


# --- MiniMax M3 ---
queue_job 61 \
  "Smooth molten chrome abstract sculpture floating in soft pastel gradient space, polished liquid metal forming organic flowing ribbons and droplet clusters, iridescent rainbow reflections dancing across the surface, subtle soft studio lighting, dark teal to dusty lavender background, high-end 3D render with subsurface scattering, cinematic depth of field, clean minimal composition, ultra detailed reflections, futuristic desktop wallpaper aesthetic, octane render quality, matte and glossy contrast." \
  "MiniMax M3" "Liquid Chrome Drift"

queue_job 62 \
  "Cluster of smooth 3D rounded pebble shapes in matte pastel colors, soft mint green, blush pink, baby blue, and cream beige, arranged in balanced organic composition, gentle studio lighting with soft shadows, clean minimal gradient background in warm off-white, clay-like texture with subtle surface imperfections, isometric perspective, calming modern aesthetic, high quality 3D render, perfect for desktop wallpaper, soft ambient occlusion, gentle depth of field." \
  "MiniMax M3" "Soft Pastel Pebbles"

queue_job 63 \
  "Abstract 3D wireframe mountain landscape with glowing neon pink, cyan, and purple edges, floating geometric platforms and grid lines, retro synthwave aesthetic combined with futuristic digital art, dark navy gradient sky with subtle stars, clean vector-like precision, soft bloom lighting effect, layered depth creating parallax feel, vaporwave color palette, ultra detailed line work, modern desktop wallpaper, 8K render quality." \
  "MiniMax M3" "Neon Wireframe Cityscape"

queue_job 64 \
  "Collection of transparent frosted glass geometric shapes, spheres, cubes, and twisted torus forms, hovering in weightless arrangement, soft iridescent edges catching prismatic light, muted background in deep eggplant purple to charcoal gradient, minimalist composition with generous negative space, premium 3D render with caustics, subtle volumetric haze, elegant and sophisticated mood, perfect for tablet or desktop wallpaper, photorealistic material studies." \
  "MiniMax M3" "Floating Glass Geometry"

queue_job 65 \
  "Surreal 3D abstract coral-like organic structure growing upward, soft biological curves and branching tubular forms, warm coral pink, terracotta orange, and sunset yellow color palette, sandy matte texture with subtle bumps, dreamy bokeh background in peach and rose gold gradient, soft directional lighting from upper left, nature-inspired digital sculpture, elegant vertical composition suitable for 9:16 mobile or 16:9 desktop wallpaper, octane render, gentle ambient glow." \
  "MiniMax M3" "Organic Coral Bloom"

echo "✅ All 65 jobs queued in scheduler"
