#!/usr/bin/env bash
set -euo pipefail


MODEL="${MODEL:-}"
if [[ -z "$MODEL" ]]; then
  echo "❌ MODEL is not set. Export it before running:" >&2
  echo '   export MODEL="HiDream-ai/HiDream-O1-Image"' >&2
  exit 1
fi

# ---- HELPERS ---------------------------------------------------------------
urlencode() {
  local string="$1" encoded="" i char
  for (( i=0; i<${#string}; i++ )); do
    char="${string:i:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) encoded+="$char" ;;
      *) printf -v encoded '%s%%%02X' "$encoded" "'$char" ;;
    esac
  done
  printf '%s' "$encoded"
}

# queue_job INDEX PROMPT GENERATOR_MODEL TITLE
# Negative prompt logic:
#   GUIDANCESCALE <= 1  → pass metadata tag as negative_prompt
#   GUIDANCESCALE >  1  → pass empty string
queue_job() {
  local index="$1"
  local prompt="$2"
  local gen_model="$3"
  local title="$4"
  local task_name
  task_name="$(printf '%02d' "$index") ${prompt:0:16}"

  printf "[QUEUE %02d] %s…\n" "$index" "${prompt:0:120}"

  local neg_prompt=""
  if (( $(echo "$GUIDANCESCALE <= 1" | bc -l) )); then
    neg_prompt="<Prompt generated by ${gen_model}><Title: \"${title}\">"
  fi

  local json
  json=$(jq -n \
    --arg  prompt   "$prompt"   \
    --arg  neg      "$neg_prompt" \
    --arg  sampler  "$SAMPLER"  \
    --arg  model    "$MODEL"    \
    --argjson steps  $STEPS     \
    --argjson cfg    $CFG       \
    --argjson ag     $AG        \
    --arg gnm        "$GUIDANCENAME" \
    --argjson gsc    $GUIDANCESCALE \
    --argjson w      $WIDTH     \
    --argjson h      $HEIGHT    \
    --argjson seed   $SEED      \
    '{
      sd_model_checkpoint: $model,
      checkpoint:           $model,
      prompt:               $prompt,
      negative_prompt:      $neg,
      steps:                $steps,
      cfg_scale:            $cfg,
      cfg_true:             $ag,
      guidance_name:        $gnm,
      guidance_scale:       $gsc,
      width:                $w,
      height:               $h,
      sampler_name:         $sampler,
      seed:                 $seed,
      batch_size:           1,
      n_iter:               1,
      save_images:          true
    }')

  curl -s -X POST "$SCHED?name=$(urlencode "$task_name")" \
    -H "Content-Type: application/json" \
    -d "$json" > /dev/null
}

# ---- PROMPTS ---------------------------------------------------------------
# Theme: Pareidolia — photorealistic scenes with a subtle hidden face effect,
#        either emergent, prompt-guided by object placement, or explicit
# Source: https://wiki.liutyi.info/display/AI/Ai+Art+41+-+Pareidolia
# Structure: 12 models × 5 prompts = 60 tasks total
# ---------------------------------------------------------------------------
# --- Claude Fable 5 ---
queue_job  1 \
  "Photorealistic wide shot of an old fishing shed on a quiet Scandinavian harbor at blue hour, soft overcast light fading into teal sky. The shed's weathered timber facade subtly exhibits a pareidolia effect: its architectural elements coincidentally suggest a calm, sleeping face, though nothing is literal and the illusion should be faint enough to miss at first glance. Two small round windows with dark glass, a horizontal driftwood beam low on the wall, peeling paint patterns and knots in the planks all belong naturally to the building. Wet cobblestones in the foreground reflect a single warm lamp, coiled ropes and a rusty anchor lean against the wall, gulls perched on the ridge. Muted Nordic palette of grey-blue, ochre and faded red, fine film grain, shallow atmospheric haze over the water, high dynamic range, cinematic composition with the shed slightly off-center. The scene must remain a completely believable, aesthetically pleasing seascape photograph first, with the hidden face only as an accidental-looking secondary read." \
  "Claude Fable 5" "Weathered Harbor Shed at Dusk"

queue_job  2 \
  "Photorealistic overhead-angled still life on a rustic oak kitchen table in warm morning sunlight streaming through linen curtains. Near the center, two shallow ceramic espresso cups filled with dark coffee sit side by side about a cup-width apart, and a short distance below them a single croissant lies horizontally with its curved side facing up, its crescent bowing gently downward at the ends. Above and between the cups, a small dusting of spilled flour forms two faint vertical streaks. Around this arrangement, naturally scattered: a butter dish, a folded newspaper, a jar of honey with a wooden dipper, crumbs, a sprig of rosemary. Soft golden side light, gentle shadows, shallow depth of field with the cups and croissant in crisp focus, warm color grade of cream, amber and terracotta, Kodak Portra film aesthetic, cozy editorial food photography style. The composition should feel like an unstaged breakfast moment, elegant and inviting, every object physically plausible and belonging to the scene." \
  "Claude Fable 5" "Morning Kitchen Still Life"

queue_job  3 \
  "Photorealistic landscape photograph of a moss-covered granite cliff face rising from a misty pine forest at dawn, cool diffuse light, thin fog drifting between dark trunks. The rock formation carries a subtle pareidolia effect: erosion patterns, cracks, lichen patches and shadowed hollows in the stone loosely evoke an ancient, weathered visage gazing sideways into the fog, so understated that most viewers would see only geology. No carved features, no symmetry, nothing sculptural, purely natural stone texture. A narrow waterfall threads down one side of the cliff, ferns and fallen needles cover the foreground, a raven perched on a dead branch mid-frame. Desaturated palette of slate grey, deep green and pale silver mist, crisp detail on wet rock, soft bokeh in distant trees, large-format landscape photography feel, quiet and slightly mystical atmosphere. The image must succeed as a beautiful moody forest scene even if the hidden face reads as nothing more than random erosion." \
  "Claude Fable 5" "Foggy Forest Rockface"

queue_job  4 \
  "Photorealistic interior photograph of a dusty attic in late afternoon, a single shaft of warm sunlight falling through a round dormer window onto wooden floorboards. On an old dresser against the far wall, two brass doorknobs rest side by side near the front edge, spaced a hand-width apart and catching identical glints of sun. Directly below them, a slightly open dresser drawer sags at one corner, its dark gap curving gently. A vertical strip of peeling wallpaper hangs between and above the knobs. The rest of the attic is naturally cluttered: a covered armchair under a white sheet, stacked leather suitcases, a birdcage, cobwebs glowing in the light beam, floating dust motes. Warm amber and umber tones against deep shadow, strong chiaroscuro, fine grain, nostalgic documentary style reminiscent of large-format interior photography. Everything must look like an authentic forgotten attic captured candidly, with careful attention to the dresser arrangement while keeping it entirely incidental in feel." \
  "Claude Fable 5" "Attic Window Light"

queue_job  5 \
  "Photorealistic photograph of a sun-bleached wall in an abandoned nursery school, shot straight-on, soft daylight from a broken window at left. The wall carries a subtle pareidolia effect built from real objects: two faded circular sticker outlines where wall clocks once hung sit at equal height a shoulder-width apart, a rusted coat hook protrudes between and slightly below them, and beneath the hook a long horizontal water stain curves faintly upward at both ends. Read together they hint at a gentle smiling presence watching the empty room; seen as mere objects they are only decay and absence. The emotional meaning of the image flips depending on whether the viewer perceives the face — a warm lingering guardian, or just a ruin stripped of its children. Peeling pastel paint in powder blue and cream, a small overturned wooden chair on the dusty floor, scattered dry leaves, muted melancholic color grade, fine grain, documentary urbex photography style, quiet and contemplative. The illusion must stay understated, discoverable only on a second look, and the photograph must remain hauntingly beautiful either way." \
  "Claude Fable 5" "The Abandoned Nursery Wall"

# --- Gemini 3.5 Flash ---
queue_job  6 \
  "A high-resolution, photorealistic long exposure shot of a serene mountain waterfall cascading over dark, moss-covered basalt rocks. The water flows smoothly down, creating intricate patterns of white foam and dark shadows among the jagged stone formations. The natural placement of two dark, circular recesses in the rock face near the top pool, combined with a vertical split in the stone and a wide, curved ledge covered in green ferns below, seamlessly blends into the landscape. Soft, diffused daylight filters through an overhead forest canopy, casting gentle mist into the air and highlighting the rich textures of the damp stone and vibrant foliage, creating an aesthetically pleasing and tranquil nature scene." \
  "Gemini 3.5 Flash" "Subtle Cascade"

queue_job  7 \
  "A cinematic, photorealistic macro photograph of a rustic wooden coffee table during an early morning, captured in soft, directional side-light. An artisanal ceramic mug sits near the center, surrounded by scattered coffee beans, a few dark chocolate squares, and a partially unfolded linen napkin. The natural swirling crema on the surface of the espresso features two distinct dark spots, perfectly aligned above a curved, dark drop of coffee that has spilled onto the weathered wood grain of the table just beneath the mug. The shallow depth of field keeps the warm, rich textures of the wood and ceramic sharply in focus, while the background gently blurs into cozy, ambient shadows." \
  "Gemini 3.5 Flash" "Coffee Break Still Life"

queue_job  8 \
  "A sharp, photorealistic architectural photograph of a minimalist mid-century modern residential building facade under a clear, late afternoon sky. The clean concrete wall is divided by geometric lines, featuring two identical square windows on the upper level, each with matching dark slate window frames and drawn grey blinds. Directly centered below them, a narrow rectangular frosted glass window is positioned vertically, while a wide, horizontally aligned concrete bench sits at the base of the structure. The sharp angles of the building cast long, dramatic architectural shadows across the pavement, delivering a clean, balanced, and aesthetically striking urban composition with rich textures of brushed concrete and reflective glass." \
  "Gemini 3.5 Flash" "Urban Facade"

queue_job  9 \
  "A breathtaking, photorealistic wide shot of a vast sand dune landscape during the golden hour, where rolling ripples of orange and red sand stretch toward the horizon. The wind has carved unique patterns into the ridges, creating a subtle pareidolia effect where two dark, shaded hollows under a crest align perfectly above a deep, vertical sand fissure and a long, sweeping crescent ridge below. The low sun casts deep, high-contrast shadows that accentuate the fine texture of every individual grain of sand, producing a highly aesthetic, dramatic desert landscape that remains completely natural and believable at first glance." \
  "Gemini 3.5 Flash" "Desert Mirage"

queue_job 10 \
  "A photorealistic, highly detailed close-up shot of an ancient, gnarled oak tree trunk deep within a misty autumnal forest. The weathered, deeply grooved grey bark is covered in patches of bright green moss and pale lichens, forming natural shapes where two distinct knot holes sit side by side. A vertical split in the trunk drops down between them, meeting a wide, mossy horizontal ridge that curves slightly upward at the ends. If the viewer perceives the face, the image transforms into an intimate, mysterious portrait of the forest watching back; if missed, it remains a beautifully serene, textured study of ancient nature. Soft, damp light filters through the distant trees, illuminating the rich textures of the bark." \
  "Gemini 3.5 Flash" "Gaze of the Forest"

# --- ChatGPT ---
queue_job 11 \
  "A photorealistic botanical greenhouse at golden hour, filled with lush ferns, orchids, climbing vines, weathered terracotta pots, and soft shafts of warm sunlight filtering through slightly dusty glass. Tiny droplets cling to broad leaves after recent watering, while an old wooden bench sits beside scattered gardening tools. The composition should naturally create a subtle pareidolia effect somewhere within the scene, emerging only through the accidental relationship between ordinary objects rather than any intentional face-like design. The effect should be faint enough that many viewers overlook it on first glance, rewarding slower observation. Every plant, texture, reflection, and shadow should remain believable and visually pleasing on its own. Rich natural colors, realistic depth of field, delicate atmospheric haze, fine botanical detail, cinematic photography, authentic imperfections, tranquil mood, elegant composition." \
  "ChatGPT" "Quiet Greenhouse Memory"

queue_job 12 \
  "A photorealistic cozy kitchen illuminated by cool morning light entering through a large window. On a wooden countertop, arrange a ceramic teapot near the upper center, place two slightly different-sized coffee mugs beneath it with comfortable spacing, and position a folded linen towel below them in a gentle curved shape. Around these objects scatter realistic breakfast items, sliced bread, herbs, a glass jar, fruit, and subtle reflections on polished stone. The arrangement should remain completely natural as a lived-in kitchen while the relative placement of the teapot, mugs, and towel quietly suggests a human face only after careful observation. The illusion must remain delicate and never cartoonish or symmetrical. Even if the viewer never notices the hidden impression, the image should still feel like an elegant editorial interior photograph with beautiful lighting, believable materials, soft shadows, and refined photographic realism." \
  "ChatGPT" "Morning Kitchen Before Coffee"

queue_job 13 \
  "A highly detailed photorealistic coastal shoreline during low tide shortly after sunrise, featuring wet sand, scattered smooth stones, shells, tangled seaweed, driftwood, and tiny reflective pools left by the retreating ocean. Arrange one larger rounded stone slightly above two smaller darker stones, with a gently curved ribbon of seaweed positioned below them, while all other natural debris appears randomly distributed. Nothing should resemble an intentional sculpture or artwork. The relative positioning alone should quietly encourage the human brain to perceive a subtle facial expression hidden within the landscape, yet remain easy to miss during an initial viewing. The shoreline itself should remain the visual priority, emphasizing delicate textures, mirror-like reflections, cool morning colors, realistic moisture, atmospheric perspective, crisp macro-level detail blended with expansive coastal scenery, and authentic nature photography." \
  "ChatGPT" "Low Tide Conversation"

queue_job 14 \
  "A photorealistic rainy city street moments after midnight, illuminated by neon reflections, warm café windows, distant traffic, bicycles, umbrellas, and glossy cobblestones covered in shallow puddles. A weathered traffic sign occupies the upper portion of the frame, beneath it two softly glowing circular reflections appear in separate puddles, while a gently curving crack through the wet pavement passes below them. The scene should intentionally encourage an extremely subtle pareidolia effect through both careful object placement and the natural tendency of the viewer to recognize facial patterns, yet everything must remain entirely plausible as ordinary urban infrastructure. No object should literally resemble facial features by design. Prioritize cinematic rain atmosphere, rich reflections, realistic lens behavior, shallow depth of field, soft bokeh, restrained color palette, and believable documentary-style street photography." \
  "ChatGPT" "City Rain After Midnight"

queue_job 15 \
  "A photorealistic reading room inside an old library during late afternoon, with tall wooden shelves, worn leather books, warm amber sunlight, floating dust particles, and an empty vintage armchair beside a small round table. A hanging reading lamp occupies the upper center, two stacked books rest on opposite sides of the tabletop beneath it, and a loosely folded scarf drapes across the front edge of the chair. Together, both the subtle pareidolia effect and the careful placement of these everyday objects should create a barely perceptible impression of a thoughtful elderly face watching over the room without introducing any actual face or supernatural element. The illusion should remain ambiguous enough that viewers who notice it may suddenly reinterpret the entire image as comforting company rather than an empty room, while those who never see it simply experience an elegant, peaceful library interior. Ultra-realistic textures, cinematic natural lighting, sophisticated composition, timeless atmosphere, and museum-quality architectural photography." \
  "ChatGPT" "The Empty Chair That Isn't Empty"

# --- Grok fast ---
queue_job 16 \
  "A hyper-realistic photograph of a vast desert canyon at golden hour, warm sunlight casting long shadows across layered sandstone formations. In the mid-ground, a weathered rock outcrop with natural crevices, bulges, and erosion patterns subtly suggests the contours of a thoughtful elderly face in profile—deep-set eye socket from a shadowed recess, a gentle nose ridge, and a faint mouth line from a horizontal crack—barely noticeable at first glance. Sparse desert shrubs and a winding dry riverbed in the foreground add depth and tranquility. Fine dust particles in the air, realistic textures on the stone with visible grain and mineral streaks, soft atmospheric haze in the distance, cinematic composition with perfect balance and natural color grading, 8k detail, photorealistic." \
  "Grok fast" "Subtle Rock Face in Canyon"

queue_job 17 \
  "Photorealistic interior of a rustic wooden cabin, soft morning light filtering through a small window onto an aged timber wall. The intricate wood grain, knots, and natural imperfections on the planks subtly coalesce into the suggestion of a serene woman's face looking gently downward—two dark knots positioned as eyes, a vertical grain line as nose, and softer curves forming lips and cheekbones, almost hidden among the organic patterns. A wooden shelf with a few old books and a dried flower vase below, warm earthy tones, dust motes in light beams, highly detailed wood textures with cracks and varnish wear, peaceful and aesthetically pleasing atmosphere, sharp focus, natural lighting, photorealistic masterpiece." \
  "Grok fast" "Wooden Wall Pareidolia"

queue_job 18 \
  "A beautifully arranged still life on a sunlit wooden kitchen table, photorealistic. Two round peaches placed slightly apart in the upper portion act as eyes, a gently curved banana positioned centrally below suggests a subtle smile, and surrounding green leaves and scattered berries create soft cheek and hair contours through their placement and shadows. The overall composition of fresh fruits and foliage guides the eye to perceive a calm, contemplative face emerging from the arrangement without any obvious features. Soft natural window light creating gentle shadows, dew drops on fruit skins, rich colors and textures, shallow depth of field, elegant and harmonious composition, highly detailed, photorealistic." \
  "Grok fast" "Fruit Arrangement Suggestion"

queue_job 19 \
  "Hyper-realistic night photograph of a quiet residential neighborhood street, warm streetlights and glowing windows in apartment buildings. The strategic placement of illuminated windows and architectural details across two adjacent buildings creates a subtle pareidolia effect: two windows aligned as eyes, a balcony shadow line suggesting a nose, and a row of smaller lights below forming a faint, mysterious smile. The arrangement invites the brain to see a watchful face in the cityscape while remaining a completely ordinary urban scene. Wet pavement reflecting lights, soft bokeh from distant traffic, cinematic night atmosphere, realistic details, moody yet aesthetically pleasing, photorealistic 8k." \
  "Grok fast" "City Lights Face Illusion"

queue_job 20 \
  "Photorealistic dense ancient forest scene at twilight with tall trees, moss-covered rocks, and gentle mist. The central massive tree trunk and surrounding branches, combined with two prominent knot holes and a horizontal bark ridge, are positioned to form the subtle suggestion of a wise, ancient face gazing directly forward—eyes from the knots, nose and mouth from natural bark formations—creating a powerful pareidolia effect. Viewers who notice the face perceive a protective guardian spirit watching over the woods, while others see only a beautiful, peaceful forest landscape, completely flipping the emotional meaning and atmosphere of the image upon recognition. Soft diffused light, rich foliage details, ethereal mood, intricate textures, photorealistic." \
  "Grok fast" "Ambiguous Forest Guardian"

# --- Copilot Smart ---
queue_job 21 \
  "A serene coastal scene at twilight, where large weathered stones rest along the shoreline. Their arrangement subtly suggests the contours of a human face when viewed from a certain angle — a broad forehead formed by a flat rock, two rounded stones aligned like eyes, and a curved driftwood piece resembling a mouth. The effect is not immediately obvious, blending naturally into the environment. The golden sunset reflects off the water, casting warm highlights across the stones, enhancing the illusion without making it overt. The composition remains photorealistic, aesthetically pleasing even if the pareidolia is overlooked." \
  "Copilot Smart" "Pareidolia Sunset Stones"

queue_job 22 \
  "A dense forest canopy photographed from below, where overlapping branches and clusters of leaves create intricate patterns against the sky. The placement of two darker leaf clusters appears like eyes, while a curved branch beneath them resembles a subtle smile. The pareidolia effect is faint, requiring careful observation to notice. Sunlight filters through the foliage, illuminating patches of green and gold, adding depth and beauty to the scene. The overall image is a tranquil, photorealistic depiction of nature, with the hidden face-like impression emerging only after prolonged viewing." \
  "Copilot Smart" "Forest Canopy Whispers"

queue_job 23 \
  "A city street at dusk, where lampposts, windows, and shadows align in a way that suggests a human face. Two lit windows on the upper floor of a building resemble eyes, while a curved shadow cast by a balcony railing forms a mouth. The arrangement is subtle, blending seamlessly into the urban environment. The warm glow of streetlights contrasts with the cool blue of the evening sky, creating a visually balanced composition. The pareidolia effect is guided by the relative positioning of architectural elements, yet remains understated and easily missed at first glance." \
  "Copilot Smart" "Urban Shadows at Dusk"

queue_job 24 \
  "A tranquil mountain lake reflecting the peaks above, where the mirrored shapes form a subtle pareidolia effect. Two smaller peaks reflected in the water appear as eyes, while a curved shoreline beneath them resembles a mouth. The illusion is guided by the placement of natural elements, but remains delicate and not immediately obvious. The photorealistic image captures crisp details of the mountains, the shimmering water, and the soft hues of dawn light. Even without noticing the hidden face, the scene is aesthetically captivating, offering a layered visual experience." \
  "Copilot Smart" "Mountain Reflection Mirage"

queue_job 25 \
  "A piece of driftwood lying on a sandy beach, its twisted form and surrounding shells arranged to create a subtle pareidolia effect. Two shells positioned near the top resemble eyes, while a curved crack in the wood suggests a mouth. The effect flips the meaning of the image depending on perception: at first glance, it is simply natural debris on the shore, but once the face-like impression is seen, the driftwood takes on a hauntingly human presence. The photorealistic composition emphasizes textures — the grain of the wood, the smoothness of the shells, and the soft sand — making the image visually compelling whether or not the pareidolia is recognized." \
  "Copilot Smart" "Dual Meaning Driftwood Face"

# --- Mistral Think ---
queue_job 26 \
  "A serene desert landscape at golden hour, where a cluster of weathered sandstone rocks in the foreground subtly forms the silhouette of a contemplative human face in profile, their shadows and highlights accentuating the illusion. The rocks are part of a larger, untouched formation, with no human interference. Warm, diffused light bathes the scene, with a distant mountain range under a clear sky. The pareidolia is delicate, blending seamlessly into the natural scenery, almost imperceptible at first glance. The composition is balanced, with the rocks slightly off-center, inviting exploration. The mood is tranquil, mysterious, and subtly surreal." \
  "Mistral Think" "Whispering Rocks"

queue_job 27 \
  "A vast, open sky at twilight, filled with wispy cirrus clouds that casually arrange into the faint outline of a pensive face gazing downward. The clouds are thin and translucent, their edges softened by the gradients of the setting sun, painting the sky in lavender, peach, and pale blue. The pareidolia emerges only after a moment, its features formed by natural gaps and densities in the clouds. The horizon is unbroken, with a hint of distant landscape below, grounding the scene in reality. The image is hyper-realistic, capturing the fleeting, ephemeral nature of the phenomenon." \
  "Mistral Think" "Clouds of Thought"

queue_job 28 \
  "A quiet forest clearing at night, illuminated by the soft glow of a full moon. In the center, a tall, slender tree with a knotted trunk stands slightly to the left, its branches spreading like outstretched arms. To the right, a large, smooth boulder rests, its surface catching the moonlight to form a pale, oval shape. Between them, a small, circular pond reflects the moonlight, creating a bright, eye-like gleam. The tree, boulder, and pond are positioned so that, from a distance, they subtly resemble the profile of a serene face: the tree as the forehead and hair, the boulder as the cheek, and the pond as the eye. A gentle mist hovers above the ground, enhancing the dreamlike quality." \
  "Mistral Think" "The Tree and the Moon"

queue_job 29 \
  "A dimly lit, minimalist interior space with a single large window allowing a shaft of afternoon sunlight to stream in. The light casts elongated, abstract shadows of a potted plant, a standing lamp, and a small side table onto the opposite wall. The shadows are sharp and defined, but their arrangement creates the uncanny illusion of a human face in profile: the plant's shadow forms the hair and forehead, the lamp's shadow creates the nose and mouth, and the table's shadow suggests the chin and jawline. The room is sparse and modern, with neutral tones and clean lines, ensuring the focus remains on the interplay of light and shadow. The pareidolia is understated, requiring a moment of observation to notice." \
  "Mistral Think" "Shadows on the Wall"

queue_job 30 \
  "A dramatic coastal cliffside at dusk, with the ocean stretching into the horizon under a moody, overcast sky. The cliff's rugged surface is a mix of dark, weathered rock and patches of hardy vegetation. Among the formations, a large, flat rock forms the \"forehead,\" a vertical crack serves as the \"nose,\" a circular depression acts as the \"eye,\" and a jutting ledge suggests the \"mouth,\" creating the illusion of a colossal, ancient face embedded in the cliff, silently observing the sea. The duality lies in the perception: without noticing the face, the cliff appears as a majestic, untouched natural wonder; once the face is seen, the scene transforms into something mythical and alive, as if the cliff itself possesses a hidden consciousness. Soft, diffused lighting highlights the rock's textures, making the effect both subtle and hauntingly beautiful." \
  "Mistral Think" "The Watcher in the Cliff"

# --- Qwen 3.7 Plus Tinking ---
queue_job 31 \
  "A highly detailed, photo-realistic macro photograph of a crumpled white linen bedsheet illuminated by soft, warm morning sunlight streaming through a window. The deep, gentle folds and creases of the fabric create subtle shadows that naturally form the faint, serene contour of a sleeping human face in profile. The pareidolia effect is extremely subtle, easily missed at a first glance, blending seamlessly into the natural texture of the woven cotton. The lighting highlights the delicate threads and slight imperfections of the fabric, creating a peaceful, aesthetically pleasing still life. Shot on a medium format camera, 85mm lens, shallow depth of field, soft bokeh in the background, cinematic lighting, 8k resolution, photorealistic textures." \
  "Qwen 3.7 Plus Tinking" "Morning Slumber in Linen"

queue_job 32 \
  "A stunning, photo-realistic close-up landscape photograph of a weathered, silver-grey piece of driftwood resting on wet, dark sand at a misty beach during golden hour. The natural grooves, knotholes, and peeling bark of the wood, combined with the soft, diffused reflections in the wet sand, subtly suggest the melancholic expression of an old man looking out at the sea. The facial features formed by the wood grain are highly understated and require a second look to notice, maintaining the authentic appearance of natural debris. The scene is beautifully composed with a shallow depth of field, focusing sharply on the central texture of the wood while the ocean waves blur softly in the background. Natural lighting, highly detailed textures, National Geographic style photography, ultra-realistic, 8k." \
  "Qwen 3.7 Plus Tinking" "Coastal Melancholy"

queue_job 33 \
  "A photo-realistic top-down flat lay photograph of a rustic wooden cafe table. In the upper left quadrant, two small, dark ceramic espresso cups filled with black coffee are placed exactly side-by-side with a two-inch gap between them. Directly below the center gap of the cups, a small, curved silver spoon rests point-down. Beneath the spoon, a crumpled white paper napkin is shaped into a gentle, upward-curving crescent. Scattered coffee beans form faint, textured arched shapes above the cups. The lighting is moody and directional, casting soft shadows that enhance the depth of the objects. The composition is perfectly symmetrical and balanced, creating a highly aesthetic, minimalist still life with rich, warm tones and sharp, realistic textures of wood, ceramic, and paper." \
  "Qwen 3.7 Plus Tinking" "Cafe Symmetry"

queue_job 34 \
  "A highly detailed, photo-realistic interior photograph of a cozy, dimly lit vintage library bookshelf. On the middle shelf, two identical, glowing amber glass globes are placed symmetrically, acting as bright focal points. Exactly centered between and slightly below the globes, a vertical stack of three thick, leather-bound books with gold-leaf spines is tightly packed together. Directly beneath the books, a polished mahogany bookend is carved into a smooth, wide, downward-curving arc. Above the glass globes, the shadows cast by the shelf above create two distinct, angled dark patches. The scene is illuminated by a warm, localized desk lamp just out of frame, highlighting the dust motes in the air and the rich textures of the leather, glass, and wood. The composition is striking, moody, and perfectly balanced." \
  "Qwen 3.7 Plus Tinking" "Vintage Library Watche"

queue_job 35 \
  "A breathtaking, photo-realistic wide landscape photograph of a serene, sunlit alpine meadow with a massive, ancient granite rock formation in the background. The prompt explicitly requests a subtle pareidolia effect where the natural fissures, moss patches, and shadows on the central rock form the distinct shape of a human face. The placement of the objects is specific: two deep, shadowed crevices form the eyes in the upper third, a vertical crack with hanging lichen forms the nose in the center, and a jagged, downward-curving shadow at the bottom forms the mouth. Crucially, while the overall scene is a beautiful, peaceful nature landscape, the subtle face formed by the rocks has an expression of silent, agonizing screaming. This creates a psychological flip: the image is a gorgeous mountain vista until you notice the screaming face, instantly changing the mood from tranquil to deeply unsettling and eerie. Cinematic lighting, 8k, highly detailed." \
  "Qwen 3.7 Plus Tinking" "The Screaming Mountain"

# --- GLM 5V Turbo ---
queue_job 36 \
  "A photorealistic interior scene at golden hour, showing a slightly fogged bathroom window with natural condensation patterns and water droplets running down the glass. Through the translucent surface, soft diffused daylight filters into a minimalist modern bathroom featuring white marble surfaces, a sleek chrome faucet reflecting warm light, and a folded white towel on the edge of a porcelain sink. The window glass itself should naturally form an ambiguous facial-like pattern through the organic arrangement of condensation trails, droplet clusters, and varying opacity areas—two slightly darker oval regions positioned in the upper portion where moisture has gathered differently, with a faint vertical streak below suggesting a nose-like formation, and curved water trails below that might suggest a mouth. The overall atmosphere is serene, contemplative, and aesthetically clean, with the pareidolia effect being extremely subtle—something you might only notice after staring at the window for several seconds. The lighting should be soft and natural, creating gentle shadows and highlights on all surfaces. High detail, 8k quality, realistic textures, cinematic composition." \
  "GLM 5V Turbo" "The Watchful Window"

queue_job 37 \
  "A breathtaking landscape photograph taken during blue hour at a remote desert location, featuring dramatic natural rock formations under a deep twilight sky transitioning from indigo to soft purple near the horizon. In the foreground, weathered sandstone boulders and eroded stone structures create an ancient, almost mystical atmosphere with subtle ambient light catching the textured surfaces. Among the central rock formations, the natural erosion patterns, shadow play from side-lighting, and the specific arrangement of protrusions and crevices should organically suggest a vague humanoid or face-like silhouette when viewed as a whole—two raised portions of stone casting shadows that resemble eye sockets, a natural vertical ridge between them, and a curved erosion line below that could be interpreted as a jawline or mouth area. Sparse desert vegetation including small hardy shrubs and scattered pebbles add texture to the sandy ground. Distant mountains fade into atmospheric haze. The pareidolia must be extremely subtle and natural-looking, integrated seamlessly into genuine geological features. Professional landscape photography style, hyper-realistic, dramatic yet peaceful mood, exceptional detail in rock textures." \
  "GLM 5V Turbo" "The Guardian Rock Formation"

queue_job 38 \
  "A sophisticated photorealistic still life composition on a dark polished walnut wooden table, illuminated by soft directional window light from the left side creating gentle shadows and highlights. The scene features carefully arranged everyday objects: in the upper left area, place two round vintage brass coasters sitting approximately three inches apart, their circular shapes and metallic patina catching light similarly. Below and centered between them, position an elegant elongated silver letter opener lying vertically at a slight angle, its tapered end pointing downward. In the lower portion of the arrangement, place a gently curved dark leather watch strap or a crescent-shaped antique key lying horizontally with a slight upward curve. Surround these central elements with aesthetic supporting items—a partially filled crystal glass of amber liquid to the right, a closed leather-bound book with aged pages visible at the spine beneath, scattered dried lavender sprigs adding organic texture, and a small ceramic dish containing two dark espresso beans. The overall color palette should be warm and refined with rich browns, golds, and deep shadows. The spatial relationship between the primary objects should create an unconscious facial pattern recognition without any actual face being depicted. Fine art photography aesthetic, shallow depth of field, museum-quality composition." \
  "GLM 5V Turbo" "The Arranged Still Life"

queue_job 39 \
  "An enchanting forest photograph captured during the magical hour of early morning, showing a natural woodland clearing surrounded by tall ancient trees with moss-covered trunks and a canopy of fresh spring green leaves filtering dappled sunlight onto the forest floor. Within this clearing, nature has arranged elements in a specific configuration: two prominent rounded boulders of similar size sit in the upper area of the clearing, roughly four feet apart, both covered in patches of pale green lichen and surrounded by small ferns growing at their bases. Precisely between and slightly below these two stones, a slender young sapling grows straight upward, its thin trunk creating a vertical element in the center. Below this sapling, a fallen log or a naturally curved exposed tree root arcs across the ground in a gentle smile-like curve, with wildflowers and grasses growing along its length. The surrounding environment includes scattered autumn leaves in shades of amber and rust, delicate mushrooms emerging from the earth, morning mist lingering in pockets near the ground, and soft beams of sunlight creating god rays through the canopy above. The entire scene feels untouched and wild, yet the spatial arrangement of these natural elements creates an inadvertent suggestion of facial features. National Geographic quality nature photography, ethereal atmosphere, incredibly detailed botanical elements, peaceful and mysterious mood." \
  "GLM 5V Turbo" "The Forest Clearing Composition"

queue_job 40 \
  "A striking architectural photograph of a brutalist concrete building facade photographed at sunset, where the interplay of geometric shadows, recessed windows, and structural elements creates a profound perceptual ambiguity. The building's surface features a grid-like pattern of deep rectangular window recesses—specifically, two larger dark rectangular openings positioned symmetrically in the upper-middle section of the frame, with a prominent vertical concrete pillar or structural rib running between them. Below this central pillar, a horizontal architectural element such as a cantilevered balcony edge or a projecting concrete beam creates a strong linear shadow or physical feature that curves slightly upward at its ends. Additional smaller windows or decorative indentations appear below this horizontal element in a pattern that could suggest teeth or additional facial details when the overall configuration is perceived holistically. However, when viewed without perceiving the pareidolia, the image reads simply as an abstract study of modernist architecture, playing with light and shadow on raw concrete surfaces. Include environmental context: dramatic cloud formations reflected in the glass windows, warm golden-hour light raking across the concrete texture emphasizing its rough aggregate surface, a solitary human figure walking past for scale, and perhaps birds silhouetted against the sky. The photograph should work beautifully as pure architectural art regardless of whether the viewer experiences the pareidolia moment—but once seen, the face-like arrangement becomes impossible to unsee, fundamentally shifting the image's emotional resonance from cold and imposing to strangely sentient and watchful. Professional architectural photography, high dynamic range, moody atmospheric lighting, thought-provoking conceptual depth." \
  "GLM 5V Turbo" "The Dual-Perception Architectural Study"

# --- Kimi K2.6 Fast ---
queue_job 41 \
  "A close-up, photorealistic overhead shot of a breakfast plate on a rustic wooden table. Two fried eggs sit slightly apart near the top of the plate, their yolks positioned like eyes gazing upward. A single strip of crispy bacon curves gently beneath them, forming a subtle, melancholic mouth. The toast at the bottom edge frames the composition like a chin. Soft morning light streams from a window, casting delicate shadows. The arrangement is casual and natural, as if placed without intention, yet the brain quietly registers a sleepy, contemplative face in the scattered meal. Shallow depth of field, warm tones, editorial food photography aesthetic." \
  "Kimi K2.6 Fast" "Morning Toast"

queue_job 42 \
  "A sweeping landscape photograph of rolling hills at golden hour, shot from a high vantage point. Three distinct cumulus clouds drift in alignment above the horizon line—two smaller, rounder clouds positioned symmetrically, with a longer, softer cloud formation resting just below them. The negative space between the hills and the sky creates an ambiguous silhouette that suggests a serene, watchful face in the atmosphere. The terrain below is lush and green, bathed in late afternoon light. The pareidolia effect is atmospheric and dreamlike, requiring a second glance to notice the gentle facial structure formed entirely by meteorological chance. Cinematic, Ansel Adams-inspired composition with subtle tonal gradations." \
  "Kimi K2.6 Fast" "Clouds Over the Valley"

queue_job 43 \
  "A photorealistic image of a weathered industrial wall inside a forgotten factory. A large, circular rust stain dominates the upper center, its irregular edges forming an eye-like shape. Below and to the right, a vertical pipe junction creates a shadow that falls like a nose profile. A dark, horizontal crack in the concrete near the bottom, partially covered by a discarded rag, completes the illusion of a solemn, aged face. The textures of peeling paint, oxidized metal, and dust are hyper-detailed. The lighting is dim and moody, coming from a single high window. The face is not immediately apparent—it emerges only after observing the wall's decay as a whole, a ghost in the architecture." \
  "Kimi K2.6 Fast" "The Abandoned Workshop"

queue_job 44 \
  "A photorealistic seascape at twilight. In the foreground, four dark, rounded boulders rest on wet sand. Two similar-sized stones sit side by side near the top of the frame, with a third, elongated stone placed directly below and between them. A fourth, flat stone lies at the bottom, slightly curved upward at the edges. Their arrangement, combined with the reflective water pools around them, creates the subtle impression of a stoic face gazing out to sea. The sky is a gradient of deep purples and muted oranges. Long exposure smooths the water into mist. The pareidolia is quiet and geological—the viewer should question whether they are seeing a face or merely stones until the pattern locks into place." \
  "Kimi K2.6 Fast" "Rocky Shore at Dusk"

queue_job 45 \
  "A photorealistic image of a moss-covered oak tree trunk in a dense, misty forest. Two dark hollows in the bark, caused by old branch removals, sit at roughly eye level—symmetrical enough to suggest a gaze but irregular enough to seem natural. A vertical fissure in the bark below them, filled with darker moss, traces downward like a nose. At the base, the flared roots create two subtle ridges that frame the lower trunk like cheekbones or a jawline. The overall effect creates a wise, ancient face that seems to emerge from and sink back into the wood depending on how long you look. If you see the face, the tree becomes a silent sentinel watching over the forest; if you don't, it is simply a beautiful, gnarled oak in atmospheric fog. Soft, diffused light filtering through the canopy, shallow depth of field, magical realism aesthetic with botanical accuracy." \
  "Kimi K2.6 Fast" "The Forest Guardian"

# --- Deepseek Instant ---
queue_job 46 \
  "A photorealistic overhead shot of a secluded forest floor covered in a thick layer of crisp autumn leaves in rich amber, burnt orange, and deep crimson, lit by soft dappled sunlight filtering through bare branches. Among the scattered foliage, a subtle arrangement of leaves is deliberately positioned to mimic a faint, melancholic human face in three-quarter view: two slightly elongated oak leaves serve as narrowed eyes, a curved maple leaf suggests a downturned mouth, and a cluster of smaller birch leaves forms a crooked nose, all blending naturally with the chaotic leaf litter so the effect is barely perceptible at first glance. The overall composition is a serene, painterly woodland scene with shallow depth of field, yet the intentional placement of these specific leaves within the natural debris is meant to trigger facial recognition, though the model may simply render a random picturesque pile." \
  "Deepseek Instant" "Autumn Leaves Pareidolia"

queue_job 47 \
  "A hyper-detailed, wide-angle photograph of a vast dried-up lakebed at golden hour, where the sun casts long, dramatic shadows across a geometric network of deep fissures in sun-baked terracotta clay. Within this organic crack pattern, a specific cluster of intersecting lines and raised polygonal plates is subtly orchestrated to outline the profile of a sleeping giant's face, with a long horizontal crack forming the closed eyelid, a jagged vertical fissure tracing the nose bridge, and a curved depression suggesting a relaxed mouth, all integrated into the larger terrain so naturally that it requires a deliberate second look. The scene is bathed in warm, cinematic light with a hazy horizon, emphasizing texture and earthy tones, while the request for this specific crack arrangement to produce pareidolia is a challenging test for the model, likely resulting in a beautiful yet abstract geological study." \
  "Deepseek Instant" "Cracked Mudflat Visage"

queue_job 48 \
  "A photorealistic, waist-level shot of a shallow, crystal-clear mountain stream flowing over a bed of smooth, water-worn pebbles in shades of grey, white, and slate, with the water creating gentle ripples and specular highlights. To guide pareidolia, arrange a cluster of submerged stones in the lower-left foreground so that two similarly sized, oval light-grey pebbles sit horizontally aligned as eye sockets, a slightly elongated, darker stone placed vertically between them and below to act as a nose, and a crescent-shaped flat stone curving beneath that to form a subtle, serene smile, while the surrounding pebbles are scattered randomly to mask the intentionality. The flowing water partially obscures these features, making the face emerge only when the viewer's gaze lingers, with the overall composition remaining a tranquil nature scene of sparkling water and smooth rocks, aesthetically pleasing regardless of recognition." \
  "Deepseek Instant" "River Stones Profile"

queue_job 49 \
  "A highly detailed macro-photographic close-up of a rugged, moss-covered tree trunk in a misty woodland, where a small colony of bracket fungi and delicate white mushrooms grows naturally from the bark crevices. The placement is carefully crafted so that two semi-circular shelf fungi project from the wood at equal height and slight distance, mimicking a pair of wide-set eyes, with a single, slender, pale mushroom growing vertically directly beneath them to suggest a nose, and a lower, horizontally elongated cluster of tiny, overlapping fungi forming a thin, straight mouth, all integrated into the textured, lichen-dappled bark surface so the anthropomorphic resemblance remains ambiguous and fleeting. Soft, diffused forest lighting enhances the earthy browns and greens, and while the prompt explicitly defines the relative positions to create a subtle facial illusion, the natural randomness of the growth should ideally conceal the effect, yielding a stunning botanical study even if the face fails to materialize." \
  "Deepseek Instant" "Fungi Face on Bark"

queue_job 50 \
  "A breathtaking, photorealistic panoramic landscape of a misty mountain range at sunrise, where a jagged ridgeline and overlapping cloud banks are deliberately composed to form a colossal, stoic human face in profile facing left, with a prominent peak as the nose, a sweeping escarpment as the brow, and a drift of low-lying fog as the chin and jawline, all illuminated by warm alpenglow. The direct instruction is to position these topographical and atmospheric elements so that the face emerges from the silhouette, but the transformative twist is that perceiving this face flips the entire image's narrative: without recognition, it is a tranquil, majestic vista of untouched wilderness evoking peace and solitude, yet once the facial outline locks into place, the same scene transforms into a watchful, ancient titan silently guarding the valley, imbuing the landscape with an eerie, sentient presence that feels either protective or ominous, thus the meaning pivots entirely based on the viewer's momentary perceptual shift, maintaining aesthetic brilliance as a pure landscape if the effect is missed." \
  "Deepseek Instant" "Guardian Ridge or Serene Horizon"

# --- ERNIE 5.1 ---
queue_job 51 \
  "Photo-realistic image of a weathered stone cliff face at golden hour, warm sunlight raking across the rough texture. The eroded rock surface has a subtle arrangement of cracks, shadows from jutting mineral deposits, and a small pool of dark water in a depression, all naturally positioned so that a faint human-like visage seems to emerge — two dark niches suggest eye sockets, a horizontal fissure hints at a mouth, and a protuberance of lichen-covered stone suggests a nose bridge, but upon close inspection each element is purely geological. Surrounding vegetation of moss and small ferns frames the scene. The overall mood is serene and contemplative, shot with shallow depth of field, natural lighting, high detail, 8K texture quality, nature photography style." \
  "ERNIE 5.1" "Ghostly Crevice"

queue_job 52 \
  "Photo-realistic overhead shot of a rustic wooden kitchen countertop scattered with everyday items: two dark round avocados placed symmetrically, a peeled banana curving between them, a red bell pepper with its stem pointing upward, and a scattering of coffee beans. The arrangement and shadows cast by warm window light create a subtle face-like impression — the avocados as eyes, the banana as a crooked smile, the pepper stem as a nose — but each object remains obviously itself, no intentional face shape. Wooden grain texture, linen napkin in corner, soft morning light through sheer curtains, shallow depth of field, food photography aesthetic, warm color palette, natural tones, high resolution detail." \
  "ERNIE 5.1" "Kitchen Illusion"

queue_job 53 \
  "Photo-realistic image of a damp forest floor after rain, mossy logs and fallen leaves arranged by nature. A large overturned root cluster has two dark hollows, a curved piece of birch bark rests below suggesting lips, and dappled light through the canopy creates a shadow pattern that hints at cheekbones and a forehead. The effect is barely perceptible, requiring a second look to notice the face-like configuration among the organic debris. Ferns and tiny mushrooms surround the scene, mist rising faintly, cool green and brown tones, macro and mid-range detail, natural ambient lighting, shallow depth of field, wildlife documentary photography style, serene and mysterious atmosphere." \
  "ERNIE 5.1" "Forest Floor Whisper"

queue_job 54 \
  "Photo-realistic urban rooftop scene at dusk, a row of old brick chimneys silhouetted against a dramatic sky. One chimney has a broken cap, a second has vines draping, and a third is slightly shorter, their relative heights and the dark smoke wisps curling between them form a ghostly face profile when viewed from a distance — the tallest chimney as a forehead, smoke trails as hair, the shorter ones as chin and jaw. The sky transitions from deep orange to indigo, city lights beginning to glow below, atmospheric haze, cinematic composition, detailed brick and mortar texture, editorial photography quality, moody and evocative." \
  "ERNIE 5.1" "Cloud and Chimney"

queue_job 55 \
  "Photo-realistic image of an ancient gnarled tree trunk split into two main trunks leaning toward each other in a misty meadow at dawn. The bark texture, knots, and a dark hollow between the trunks can be perceived as either the solemn face of an old man with deep-set eyes and a furrowed brow, or as two figures embracing face to face — the interpretation flips depending on what the viewer's mind latches onto first. Soft golden backlight, dewdrops on surrounding grass, low fog, muted earth tones with hints of amber, fine art nature photography, contemplative and ambiguous mood, extremely detailed bark and atmosphere, shallow depth of field, painterly yet photographic quality." \
  "ERNIE 5.1" "The Old Man or The Lovers"

# --- LongCat Deep search ---
queue_job 56 \
  "A close-up macro photograph of a cluster of ripe figs resting on a mossy stone surface in a sunlit garden. The figs are naturally split open at different angles, their interiors showing star-shaped patterns and tiny seeds. Through the random arrangement of the fruits and the play of dappled light across their surfaces, the composition inadvertently creates pareidolia - the suggestion of a gentle, watchful face emerges from the cluster's shadows, seed patterns, and the clefts where fig stems attach. No fig is intentionally shaped like a facial feature. Ultra-realistic, shallow depth of field, golden hour lighting, botanical illustration aesthetic." \
  "LongCat Deep search" "Fig Pareidolia on Sunlit Stone"

queue_job 57 \
  "An extreme close-up of a weathered leather-bound book lying open beside a vintage brass key and a single dried oak leaf on an antique desk. The interplay of the book's worn spine, the key's bow and bit, and the leaf's central vein and lobes creates a subtle pareidolia effect - the arrangement suggests a contemplative face when the negative space between objects is perceived as features. Each object remains distinctly itself, only forming the impression through their placement and surrounding shadows. Photo-realistic, warm tungsten lighting, rich textures, fine detail." \
  "LongCat Deep search" "Archival Desk Objects"

queue_job 58 \
  "A minimalist still life composition on a textured linen cloth. Three items are carefully arranged: a small round mirror positioned at the top center, and below it, two mismatched silver spoons placed parallel to each other with their bowls facing upward. The mirror reflects a soft window light while the spoons' handles point downward. The spatial relationship between these objects - the mirror as one feature and the two spoons as another - creates a subtle pareidolia impression where the brain perceives a face from the negative space and alignment. The scene remains elegant and abstract whether the effect is noticed or not. Ultra-realistic studio lighting, shallow depth of field, sophisticated neutral palette." \
  "LongCat Deep search" "Mirror and Silver Spoons Still Life"

queue_job 59 \
  "A wide-angle interior shot of a cozy reading nook. On a rustic wooden shelf, three objects are placed: a small terracotta pot with a single yellow daisy at the top left, a smooth river stone in the center, and a brass candle holder at the top right. Below them, two vintage leather bookends shaped like arches frame a row of books. The relative positions - the two top objects flanking the central stone, with the bookends forming a base - create a sophisticated pareidolia arrangement where a gentle face is suggested through spacing and object relationships rather than through any literal facial forms. Warm afternoon light streams through a nearby window. Photo-realistic, rich textures, inviting atmosphere." \
  "LongCat Deep search" "Bookshelf with Decorative Objects"

queue_job 60 \
  "A dramatic landscape photograph of a solitary granite cliff face at sunset. At the cliff's summit, two natural oval rock cavities weathered by centuries of wind stand side by side, appearing like closed eyes. Below them, a horizontal fissure in the stone creates a subtle mouth-like formation. Directly acknowledging this pareidolia, the image simultaneously presents as: a majestic natural monument when the face is overlooked, and a sleeping ancient guardian when the features are recognized. The composition balances both readings - whether you perceive the face or not, the scene remains breathtakingly beautiful. Ultra-realistic, dramatic golden hour lighting, deep shadows, cinematic composition, 8K detail." \
  "LongCat Deep search" "Cliff Guardian at Sunset"

echo "✅ All 60 jobs queued in scheduler"

